OPM/opm-common

cmake/Modules/OpmSatellites.cmake

existing DEPENDS parameter was for test interdependencies and not
target dependencies. reserve DEPENDS for target dependencies

changed: add TEST_DEPENDS parameter in opm_add_test

---

cmake/Modules/OpmLibMain.cmake

move target here so it can be shared across modules. needs to be merged in tandem with requests for the separate modules which will be sent shortly (or we end up with duplicate targets). @bska for review.

added: check-commits target

---

cmake/Modules/FindERT.cmake
cmake/Modules/OpmLibMain.cmake

This looks for the python module of ERT. Will be used for regression tests in opm-autodiff.

Look for python module in ERT

---

cmake/Modules/opm-core-prereqs.cmake

this is required for OPM/opm-core#834

add opm-material to the prerequisites of opm-core

---

cmake/Modules/FindERT.cmake
cmake/Modules/FindERTPython.cmake

- Using standard python 'import ert' and introspection.
- Using dist-packages (debian) and site-packages (!debian).

Changed code for finding ERT Python

---

cmake/Modules/Finddune-fem.cmake
cmake/Modules/ewoms-prereqs.cmake

This PR adds a find module for ewoms to find the dune-fem module.

Make ewoms find dune-fem.

---

CMakeLists.txt
cmake/Modules/OpmProject.cmake

fixed: we need different paths in installed and in-tree config file

---

cmake/Modules/Findopm-data.cmake

If a variety of this PR is merged - I will continue to merge this: https://github.com/OPM/opm-parser/pull/588

Added Findopm-data module.

---

cmake/Modules/OpmPackage.cmake

fixes https://github.com/OPM/opm-common/issues/53

fixed: also check lower-case module variable

---

redhat/opm-common.spec

add redhat packaging

---

CMakeLists_files.cmake
opm/common/data/SimulationDataContainer.cpp
opm/common/data/SimulationDataContainer.hpp
tests/test_SimulationDataContainer.cpp

Added methods to register cell and face data in a SimulationDataContainer.

SimulationDatacontainer

---

README.md

The status indicates the build status of the master branch.
Example of appearance: https://github.com/jepebe/opm-common/tree/travis

Added Travis status to README.md

---

CMakeLists_files.cmake
opm/common/data/SimulationDataContainer.cpp
opm/common/data/SimulationDataContainer.hpp
opm/common/util/numeric/cmp.cpp
opm/common/util/numeric/cmp.hpp
tests/test_SimulationDataContainer.cpp
tests/test_cmp.cpp

1. Added small utility implementation for comparing double values
2. Added method `SimulationDataContainer::equal( )`

Added util/numeric/cmp.hpp

---

opm/common/data/SimulationDataContainer.cpp
opm/common/util/numeric/cmp.hpp

Bug also discovered by compiler warnings.

Minor bugfix and silence a warning.

---

opm/common/data/SimulationDataContainer.cpp
opm/common/data/SimulationDataContainer.hpp
tests/test_SimulationDataContainer.cpp

1. Added method to query for the number of component
2. Added cell data iterators.

Add iterator

---

cmake/Modules/Findopm-output.cmake
cmake/Modules/opm-output-prereqs.cmake

Added initial prereqs and find rules for opm-output.

Added cmake files for opm-output.

---

CMakeLists_files.cmake
cmake/Modules/opm-material-prereqs.cmake
opm/common/OpmLog/CounterLog.cpp
opm/common/OpmLog/CounterLog.hpp
opm/common/OpmLog/EclipsePRTLog.cpp
opm/common/OpmLog/EclipsePRTLog.hpp
opm/common/OpmLog/LogBackend.cpp
opm/common/OpmLog/LogBackend.hpp
opm/common/OpmLog/LogUtil.cpp
opm/common/OpmLog/LogUtil.hpp
opm/common/OpmLog/Logger.cpp
opm/common/OpmLog/Logger.hpp
opm/common/OpmLog/OpmLog.cpp
opm/common/OpmLog/OpmLog.hpp
opm/common/OpmLog/StreamLog.cpp
opm/common/OpmLog/StreamLog.hpp
opm/common/OpmLog/TimerLog.cpp
opm/common/OpmLog/TimerLog.hpp
tests/test_OpmLog.cpp

Removed OpmLog from parser and added it here

Added log functionality from opm-parser

---

cmake/Modules/FindZOLTAN.cmake
cmake/Modules/OpmSatellites.cmake
debian/control
debian/libopm-common1-dev.install
debian/libopm-common1.install
redhat/opm-common.spec

Pre-changes:
- support zoltan provided by trilinos.
- run all tests through mpi-run.
Main changes:
- Packaging updates for rhel6/7 and ubuntu.
@atgeirr Unless there are objections please hit the green.

Updates for 16.04 packaging

---

jenkins/build-opm-module.sh
jenkins/build.sh

- add a generic function to build upstream modules
- add a generic function to build downstream modules
- add downstream trigger support in this module

updates for jenkins build scripts

---

cmake/Modules/FindSuperLU.cmake
cmake/Modules/OpmLibMain.cmake

this fixes two smaller issues I ran into on a freshly installed ubuntu 16.04 system. Although it seems to Work for Me (TM), the second patch may cause some trouble on systems with newish cmake versions and should thus be further tested before it is merged.
@akva2: can I trigger jenkins builds for this module?

Misc fixes

---

opm/common/OpmLog/LogUtil.hpp

This messageType is a shortcut for getting all the message expect ``Debug`.

Define one useful message type.

---

opm/common/OpmLog/LogUtil.cpp
opm/common/OpmLog/LogUtil.hpp
tests/test_OpmLog.cpp

See discussion here https://github.com/OPM/opm-common/issues/132

change yellow to blue.

---

cmake/Modules/Findopm-flowdiagnostics.cmake
cmake/Modules/opm-flowdiagnostics-prereqs.cmake

This enables using the OPM build system in the new module [opm-flowdiagnostics](https://github.com/OPM/opm-flowdiagnostics).

Recognize OPM-Flowdiagnostics as an OPM Module

---

opm/common/OpmLog/StreamLog.cpp
opm/common/OpmLog/StreamLog.hpp

Maybe convenient for developers?

Log: StreamLog can optionally open in append mode.

---

.travis.yml
travis/build-and-test.sh
travis/build-prereqs.sh
travis/clone-opm.sh

Reorganized travis config - see commit message.
If this is merged I will create PR's like this: https://github.com/OPM/opm-parser/pull/824 for the other modules.

Script for travis to build and test downstream.

---

cmake/Modules/FindERT.cmake
cmake/Modules/OpmPackage.cmake

These improvements will set the foundation for automated builds for VS2015

VS2015 : Improvements to FIND functions for ERT and find_opm_package

---

cmake/Modules/opm-output-prereqs.cmake

fixed: set correct config variable

---

cmake/Modules/OpmSatellites.cmake
jenkins/build-opm-module.sh
travis/build-and-test.sh
travis/build-prereqs.sh
travis/clone-opm.sh

this hopefully adds the  eWoms module to the travis CI system. it is basically the union of #164 and #163. Thanks to @joakim-hove for the initial patch.

Travis ewoms

---

cmake/Modules/ewoms-prereqs.cmake

this is the build system side of OPM/ewoms#70...

make dune-localfunctions optional for eWoms

---

cmake/Modules/FindCwrap.cmake
cmake/Modules/OpmPythonTest.cmake

Added feature for locating module `cwrap`, similar to the way we locate module `ert`.

Added FindCwrap, add to pythonpath

---

redhat/opm-common.spec

update redhat6 packaging

---

cmake/Modules/FindCXX11Features.cmake

as a bonus it makes it easy to experiment with c++14

added: use cmake mechanisms to enable c++11 with cmake >= 3.1

---

jenkins/build-opm-module.sh

use the BUILDTHREADS environment variable
convenient for local use

added: allow building with multiple threads in jenkins scripts

---

cmake/Modules/opm-simulators-prereqs.cmake

this is the companion PR to OPM/opm-simulators#790 .

[POC] added ewoms dependency to opm-simulators.

---

CMakeLists_files.cmake
cmake/Modules/opm-common-prereqs.cmake
opm/common/Unused.hpp

this PR requires quite a bit of mob-up PRs in other modules. make sure to also merge these.

move the Unused.hpp file from opm-material to here

---

jenkins/build.sh
travis/build-and-test.sh

opm-grid move in dependency graph

update downstream list

---

cmake/Modules/Findopm-core.cmake

quotes in quotes makes happy man sad.

fix test program

---

jenkins/update-opm-data.sh

work in progress, ignore for now. do NOT merge.

add script for automating data updates

---

cmake/Modules/OpmLibMain.cmake

remove libtool archive generation

---

.travis.yml

required by some scripts. ref https://github.com/OPM/opm-simulators/pull/1093
@andlaus

fixed: install bc on travis builder

---

opm/common/OpmLog/LogUtil.cpp
opm/common/OpmLog/LogUtil.hpp

Changed terminal output color for problem messages to magenta from red

modify terminal output color for problem messages

---

debian/rules
redhat/opm-common.spec

Backport from 2017.04 release branch.

disable native tuning in packaging

---

jenkins/update-opm-data.sh

So many scripts, I forgot to point this one out..

add a missed ert -> libecl

---

cmake/Modules/OpmCompile.cmake

Previously, this failed if one dependency was a static library compiled
without -fPIC. This is is the case for library libsuitesparseconfig on
Debian which has no dynamic alternative. The error messages read e.g.
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libsuitesparseconfig.a(SuiteSparse_config.o): relocation R_X86_64_PC32 against undefined symbol `malloc@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
```
With this patch we change the target_link_libraries call when using
BUILD_SHARED_LIBS=ON. We only pass the dynamic libraries as PUBLIC such
that they will get linked to the library. The static ones are passed as
INTERFACE libraries. This means that they will be automatically …

Allow using external static libraries with BUILD_SHARED_LIBS=ON

---

opm/common/Exceptions.hpp

Adds new message types (Probleminfo and Warninginfo) which can be used to provide additional information about a problem or warning without being explicitly logged as a problem or warning

Add exception TooManyIterations

---

opm/common/OpmLog/LogUtil.cpp
opm/common/OpmLog/MessageFormatter.hpp
tests/test_OpmLog.cpp

- Adds linespace before Problem, Message, Bug and Error log output

Message formatting edit

---

cmake/Modules/FindPETSc.cmake
cmake/Modules/OpmLibMain.cmake

add option to enable PETSc

---

cmake/Modules/OpmSatellites.cmake

this surfaced while doing OPM/ewoms#220.

also compile tests marked `ONLY_COMPILE` on `make test-suite`

---

cmake/Modules/opm-flowdiagnostics-applications-prereqs.cmake

changed: update opm-flowdiagnostics-applications prereqs

---

cmake/Modules/OpmAliases.cmake

add another alias for UMFPACK

---

redhat/opm-common.spec

Should be backported to release branch after merge.

update redhat packaging

---

CMakeLists_files.cmake
opm/core/utility/parameters/Parameter.cpp
opm/core/utility/parameters/Parameter.hpp
opm/core/utility/parameters/ParameterGroup.cpp
opm/core/utility/parameters/ParameterGroup.hpp
opm/core/utility/parameters/ParameterGroup_impl.hpp
opm/core/utility/parameters/ParameterMapItem.hpp
opm/core/utility/parameters/ParameterRequirement.hpp
opm/core/utility/parameters/ParameterStrings.hpp
opm/core/utility/parameters/ParameterTools.cpp
opm/core/utility/parameters/ParameterTools.hpp
tests/test_param.cpp
tests/testdata.param

This imports the ParameterGroup code from opm-core.

Import ParameterGroup code from opm-core

---

jenkins/build-opm-module.sh

not only if we build downstreams. ref https://github.com/OPM/opm-upscaling/pull/232 @bska

fixed: perform installation at end of main module

---

cmake/Modules/OpmProject.cmake

in 9737538708ed0b14f989245e446e89af6f9cb1c
sorry about that :/

fixed: this test code slipped through

---

CMakeLists_files.cmake
opm/core/utility/MonotCubicInterpolator.cpp
opm/core/utility/MonotCubicInterpolator.hpp
opm/core/utility/NonuniformTableLinear.hpp
opm/core/utility/RootFinders.hpp
opm/core/utility/SparseVector.hpp
opm/core/utility/linearInterpolation.hpp
tests/test_nonuniformtablelinear.cpp

@atgeirr: In addition to the files you listed i included the associated test.

Import some generic utility classes from opm-core

---

cmake/Modules/OpmInit.cmake
cmake/Modules/OpmLibMain.cmake

if not, prereqs do not see this file, and the option ends
up not being operational for prereqs looking for MPI.

fixed: we need to do mpi disabling earlier

---

jenkins/update-opm-data.sh

ref https://github.com/OPM/opm-output/pull/242#issuecomment-362370893

fixed: trim whitespace in pr number

---

opm/common/utility/ConditionalStorage.hpp
tests/test_ConditionalStorage.cpp

Trivial changes, will self-merge when green.

Silence unused argument warnings.

---

jenkins/build-opm-module.sh

can help identifying issues with builds

changed: output last log entry in branches for jenkins builds

---

cmake/Modules/OpmInstall.cmake
cmake/Modules/OpmLibMain.cmake
cmake/Modules/OpmProject.cmake
cmake/Modules/OpmSatellites.cmake
cmake/Templates/opm-project-config.cmake.in

okay, @blattms, let's start at this end then since you pointed out the regression in opm-parser.

added: add exported targets

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCONINJE

to fix https://github.com/OPM/opm-parser/issues/1034

adding missing SURFACE_WATER_FRACTION to WCONINJE

---

jenkins/update-opm-data.sh

some more for the guys in the back.

fixed: remove left-over opm-parser/opm-output references

---

src/opm/output/eclipse/Summary.cpp
tests/SUMMARY_EFF_FAC.DATA
tests/test_Summary.cpp

This is the work of @lars-petter-hauge : #343  - but due to some minor f.. I have completed it with one final micro commit.

Timestep fix

---

src/opm/output/eclipse/Summary.cpp

Efficiency factors should also be applied for historic volumes.

Add eff_fac for historic volumes

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/C/CARFIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/C/COMPDATL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENDFIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/REFINE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WELSPECL
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Add some LGR related keywords - purely for parsing benefit.

Add LGR related keywords

---

src/opm/parser/eclipse/EclipseState/Schedule/WellInjectionProperties.cpp

quells a sca warning. no hard feelings if you prefer to keep it as-is.

changed: use initializer list for enums

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Runspec.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQExpression.hpp
opm/parser/eclipse/EclipseState/UDQConfig.hpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQExpression.cpp
src/opm/parser/eclipse/EclipseState/UDQConfig.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/U/UDQPARAM
src/opm/parser/eclipse/share/keywords/keyword_list.cmake
tests/parser/UDQTests.cpp

This a *very* initial start of UDQ support; currently just some parsing and keywords.

Internalize UDQ keywords

---

jenkins/setup-opm-tests.sh
jenkins/update-opm-tests.sh

fixed: missing OPM_DATA_ROOT -> OPM_TESTS_ROOT

---

opm/parser/eclipse/EclipseState/Schedule/UDQExpression.hpp

harmless but quells a sca warning.

mark constructor explicit

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

return std::map of std::shared_ptr for getVFPxTables()

---

jenkins/update-opm-tests.sh

opm-data -> opm-tests

---

CMakeLists_files.cmake
opm/output/eclipse/DoubHEAD.hpp
opm/output/eclipse/InteHEAD.hpp
opm/output/eclipse/LogiHEAD.hpp
opm/output/eclipse/WriteRestartHelpers.hpp
src/opm/output/eclipse/CreateDoubHead.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/CreateLogiHead.cpp
src/opm/output/eclipse/DoubHEAD.cpp
src/opm/output/eclipse/InteHEAD.cpp
src/opm/output/eclipse/LogiHEAD.cpp
tests/test_DoubHEAD.cpp
tests/test_InteHEAD.cpp
tests/test_LogiHEAD.cpp

This is another PR for the same thing, it is #392 with an extra commit documenting some literals as previously discussed. It is marked WIP, as I get local test failures. I'll run jenkins anyway to see if it's only my system, but the PR should not be merged until I have resolved those failures.

Add Initial Implementation of Correctly Sized Header Vectors for Restart

---

redhat/opm-common.spec

fix redhat 6 packaging

---

jenkins/build-opm-module.sh

This is manually merging the pr branch into master instead of relying on the github refs to do so.
I don't particularly like it, it will be less robust but ...

changed: manually merge pr's to work around slow updating merge refs

---

opm/parser/eclipse/EclipseState/AquiferCT.hpp
src/opm/parser/eclipse/EclipseState/AquiferCT.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCT

Adds conversion factors for AQUCT constants to SI units

Handle conversion of constants in parser

---

jenkins/build-opm-module.sh

had some more consequences than expected, not all of them desired

revert 'set -e' addition in jenkins script

---

jenkins/build-opm-module.sh

Causes too much trouble to be worth the gain. Sorry @joakim-hove

Revert #401

---

opm/parser/eclipse/EclipseState/Schedule/WellTestConfig.hpp
src/opm/parser/eclipse/EclipseState/Schedule/WellTestConfig.cpp

Add method for getting all the wells in the WellTestConfig

---

opm/parser/eclipse/EclipseState/Schedule/WellTestConfig.hpp
src/opm/parser/eclipse/EclipseState/Schedule/WellTestConfig.cpp

Reverts OPM/opm-common#415
See: https://github.com/OPM/opm-common/pull/415#issuecomment-395300770

Revert "Add method for getting all the wells in the WellTestConfig"

---

src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp

Requires: https://github.com/Statoil/libecl/pull/418

Use double overload for eclGrid

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MESSAGES

The MESSAGES keyword actually has thirteen items. This adds the last item to the keyword.

The MESSAGES keyword needs a thirteenth item

---

opm/parser/eclipse/EclipseState/Schedule/WellTestState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/WellTestState.cpp
tests/parser/WTEST.cpp

This may need some modification when our understanding on connection vs completions matures.

Add posibility to store closed completions in wellTestState

---

opm/parser/eclipse/EclipseState/Eclipse3DProperties.hpp
src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp

More small pieces in the completion support saga.

Add no deck constructor to Eclipse3DProperties

---

opm/parser/eclipse/EclipseState/Schedule/WellTestState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/WellTestState.cpp

quells a sca warning.
@totto82 as much as i like to dance, this is getting annoying. i fix one, you add new one the very same day ;)

fixed: pass string by const ref

---

CMakeLists_files.cmake
examples/opmpack.cpp

A utility - also a possible way to fix the test failures in #463

Add application opmpack to load a deck and dump it again as one stream

---

opm/parser/eclipse/Deck/Deck.hpp

Ref https://github.com/OPM/opm-upscaling/pull/260
Not sure what the conclusion is but this is the removal approach.

changed: delete assignment operator in Deck class

---

CMakeLists.txt

See: https://github.com/OPM/opm-simulators/pull/1544

Add cmake variable $OPM_PACK_COMMAND

---

examples/test_util/compareECL.cpp
examples/test_util/compareSummary.cpp
opm/test_util/EclFilesComparator.hpp
opm/test_util/summaryComparator.hpp
src/opm/test_util/EclFilesComparator.cpp
src/opm/test_util/summaryRegressionTest.cpp

useful for debugging purposes. replaces scripts in opm-simulators.
@alfbr as requested.

added: error analysis support in compareSummary / compareECL

---

opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
src/opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
tests/parser/MULTREGTScannerTests.cpp

Handle defaulted region numbers in MULTREGT keyword.

Multregt default

---

src/opm/output/eclipse/RestartIO.cpp
tests/test_Restart.cpp

Thrpes solution section

---

tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_Summary.cpp

Use plain C api instead of not-so-succesfull C++ wrapper; to facilitate use of proper C++ some time in the future.

Use c testare

---

src/opm/output/eclipse/Summary.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

This PR is a complete WIP and has obvious mistakes.

Support CTFAC

---

src/opm/parser/eclipse/share/keywords/900_OPM/M/MINPVFIL

I suppose the dimensions of MINPVFIL should mimic MINPV

fix unit of minpvfil

---

src/opm/output/eclipse/EclipseIO.cpp

Do not output summary data for initial state.

Summary start at1

---

cmake/Templates/opm-project-config.cmake.in

Debugging & testing this was really painful - think I have got it right now. Sorry for the noise.

Add quotes to ensure string evaluation

---

cmake/Modules/ConfigVars.cmake

Some configuration scripts probe and just set HAVE_FOO without any
values, whereas others set it explicitly to 1. If these two are mixed,
for instance that the same package is used by two of our prerequisites,
but in different manner, then we get compatibility warnings when we try
to run the configuration script, even though there is no real conflict.
dune-fem, dune-alugrid and dune-localfunctions have this problem (around
release 2018.04).
This patch special-code the test so if the old value was previously
either just defined or explicitly set to the value 1, a warning will not
be issued if then suddenly the other variant is used.

Do not warn if just def'ed HAVE_ vars are set to 1

---

src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/libECLRestart.cpp

The restart merge broke various builds, in particular those using clang (static analyzer jobs).

Fixups after restart merge

---

CMakeLists.txt
cmake/Modules/OpmBashCompletion.cmake
etc/opm_bash_completion.sh.in
jenkins/build-opm-module.sh

based on @andlaus work in ewoms.

added: cmake glue for adding bash tab completion for an installed product

---

opm/output/eclipse/AggregateMSWData.hpp
src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Compsegs.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/WellConnections.cpp

Added improvements and corrections to code for writing of Eclipse compatible restart file in order to handle more general well data (Connection and segmented well data)

EclipseRestart-improvements

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Aquifetp.hpp
src/opm/parser/eclipse/EclipseState/Aquifetp.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFETP
tests/parser/AquifetpTests.cpp

Hi everyone!
First of all a small introduction is needed. My name is Wessel and since september I am working at TNO together with Rohith, Frank and Kelvin on the OPM project. My first task is to implement the Fetkovich Aquifer. 
For this I created the required parsing and test files for this. This is my first time doing real software developement, so please give me all the feedback and support you can think of! This merge is for dealing with the AQUFETP keyword in the input file. 
Thanks for the feedback, hope to hear soon from you guys!
Wessel

Aquifet parser implementation

---

src/opm/parser/eclipse/Parser/Parser.cpp

Add a better error message for parse errors

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/ActionContext.hpp
opm/parser/eclipse/EclipseState/Schedule/ActionX.hpp
opm/parser/eclipse/EclipseState/Schedule/Actions.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/Parser/ParseContext.hpp
src/opm/parser/eclipse/EclipseState/Schedule/ActionContext.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Actions.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/Parser/ParseContext.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/ACTIONX
tests/parser/ACTIONX.cpp

This PR implements a container to hold/manage ACTIONX keywords. There is much work remaining before we have a working ACTIONX implementation, but this should be ready to be merged now.
What is missing includes
1. A parser to parse the ACTIONX expressions.
2. Generate the context for the evaluation.
3. Apply the keywords in the action.
I'll proceed one PR at a time.

 ACTIONX container

---

opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.hpp
src/opm/output/eclipse/libECLRestart.cpp
tests/parser/ScheduleTests.cpp

quell some static analyzer and compiler warnings.

Some small cleanups

---

cmake/Modules/OpmSatellites.cmake

Fix boost and property setting for tests.

Fix test macro

---

opm/output/data/Wells.hpp
src/opm/output/eclipse/Summary.cpp
tests/test_Summary.cpp

The corresponding PR in opm-simulators awaits merging of OPM/opm-simulators#1611

Add output of well phase potential

---

opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
src/opm/parser/eclipse/Deck/Section.cpp
tests/parser/DynamicStateTests.cpp

One more small step in process towards ACTIONX support.

Add method update_equal() to DynamicState

---

msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
tests/msim/test_msim.cpp

Add finterface to hook in arbitrary functions for well rates and solution data in the MOCK simulator.

Add functions for well rates and solutions to mock simulator

---

opm/parser/eclipse/EclipseState/Schedule/Actions.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Actions.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp
tests/parser/ScheduleTests.cpp

Add (empty) method to eval actions. Will hook this up from the simulator.

Add method Schedule::evalActions() to evaluate ACTIONX

---

opm/parser/eclipse/EclipseState/Schedule/ActionAST.hpp
opm/parser/eclipse/EclipseState/Schedule/ActionX.hpp
src/opm/parser/eclipse/EclipseState/Schedule/ActionAST.cpp

The last commit may not be desirable, just say so and we'll drop it.

Some SCA error janitoring

---

examples/test_util/summaryComparator.cpp
examples/test_util/summaryIntegrationTest.cpp
examples/test_util/summaryRegressionTest.cpp
opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp

Adapt to C++ changes in libecl summary nodes: https://github.com/Statoil/libecl/pull/538
I intend to merge this - along with the libecl PR on friday 30.th of november. The two PR must be merged together.

Adapt to C++ changes in libecl

---

src/opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

Otherwise, we get zero value for liquid rate. 
I will check whether I can find related test here. If yes, I will update the test.

updating liquid rate for WCONHIST

---

examples/test_util/EclRegressionTest.hpp
opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
opm/parser/eclipse/EclipseState/Schedule/ActionAST.hpp
opm/parser/eclipse/EclipseState/Schedule/Well.hpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/output/eclipse/libECLRestart.cpp
src/opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ActionAST.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ActionContext.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Connection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/test_RFT.cpp
tests/test_Summary.cpp

Also fix a small compile-error for me on clang.

Silence various warnings

---

opm/parser/eclipse/EclipseState/Schedule/WellTestState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/WellTestState.cpp

This is needed by downstream code, PR coming soon.

Add function WellTestState::lastTestTime().

---

src/opm/parser/eclipse/Parser/ErrorGuard.cpp

Look ma - he is using `iomanip`!

Format the ErrorGuard::dump() nicer

---

src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/WellConnections.cpp

Some janitoring

---

opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Actions.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Actions.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

Small - quite trivial preparations for ACTIONX - it is a long and winding road.

Msim actionx preparations

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

Minor changes to schedule object - to facilitate ACTIONX

Schedule minor

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Runspec.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ.hpp
opm/parser/eclipse/EclipseState/UDQParams.hpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ.cpp
src/opm/parser/eclipse/EclipseState/UDQParams.cpp
tests/parser/UDQTests.cpp

Trivial rename of UDQ parameters.

Renamed UDQConfig -> UDQParams

---

src/opm/parser/eclipse/EclipseState/Grid/GridProperties.cpp
tests/parser/GridPropertyTests.cpp

Ensure units are applied with the MINVALUE and MAXVALUE keywords

---

CMakeLists.txt
msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
opm/parser/eclipse/EclipseState/Schedule/Action/ActionAST.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Actions.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionAST.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/msim/actionx1.include
tests/msim/test_msim_ACTIONX.cpp
tests/parser/ACTIONX.cpp

With this the `ACTIONX` keyword "works" - for the body keyword `WELOPEN`, and when applied to the `msim` mock simulator - it is a start!

Msim actionx

---

src/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTOUT
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Request multiple files for input and output.

Read keywords MULTIN and MULTOUT

---

src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
src/opm/parser/eclipse/share/keywords/900_OPM/F/FREEBC
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

This PR adds OPM customized keywords for specifying free boundary conditions.

Add input keywords for setting free boundary conditions

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQExpression.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQWellSet.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQ.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQExpression.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQWellSet.cpp
tests/parser/UDQTests.cpp

More udq - it never ends ... This PR contains the class `UDQAssign` which implements the `ASSIGN` action of the UDQ keyword, and the class `UDQWellSet` which is derived from the `UDQSet` base class.

Udq assign

---

CMakeLists_files.cmake
src/opm/output/eclipse/AggregateGroupData.cpp
tests/test_AggregateGroupData.cpp
tests/test_AggregateMSWData.cpp

Added unit tests to ensure that the code works as they should on the  group structure in the
example data set. The structure contains two group levels, a well group level and a node group
level.

Added unit tests to the functions that writes group & field data to Eclipse-restart file

---

opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQExpression.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunctionTable.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQWellSet.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQExpression.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunctionTable.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQInput.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQWellSet.cpp
tests/parser/ACTIONX.cpp
tests/parser/UDQTests.cpp
tests/test_Summary.cpp

I have extracted the trivial / unrelated commits from #656 to a small PR which can be merged first.

Udq parse pre commits

---

CMakeLists_files.cmake
src/opm/output/eclipse/AggregateMSWData.cpp
tests/test_AggregateMSWData.cpp

Added unit tests for writing of multisegment well (MSW) data to Eclipse Compatible restart file. Added changes to allow for more general MSW structure allowing for discontinuous segment numbering.

Unit tests for writing of multisegment well (MSW) data to Eclipse Compatible restart file.

---

opm/parser/eclipse/EclipseState/AquiferCT.hpp
src/opm/parser/eclipse/EclipseState/AquiferCT.cpp

Forward declare EclipseState in the AQuiferCt class.
Will self-merge as soon as Jenkins is in the green.

Aquifer include

---

opm/parser/eclipse/EclipseState/Grid/FaultCollection.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Tables/SimpleTable.hpp
opm/parser/eclipse/EclipseState/Tables/TableSchema.hpp
opm/parser/eclipse/EclipseState/Util/OrderedMap.hpp
src/opm/parser/eclipse/EclipseState/Grid/FaultCollection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Tables/SimpleTable.cpp
src/opm/parser/eclipse/EclipseState/Tables/TableSchema.cpp
tests/parser/OrderedMapTests.cpp

A drive by improvement while starting on the big well refactoring.

Change OrderMap to more closely resemble std::map

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

Added a "super" function to get wellnames; not really in use yet - that is coming.

Implement Schedule::wellNames()

---

opm/parser/eclipse/EclipseState/Schedule/MSW/updatingConnectionsWithSegments.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Compsegs.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Compsegs.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/updatingConnectionsWithSegments.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ConnectionTests.cpp
tests/parser/MultisegmentWellTests.cpp
tests/parser/ScheduleTests.cpp

The Well had a property total number of connections - this has been removed in favor of quering the connections object when it is needed.

Removed well property total number of connections

---

src/opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/T/THPRESFT
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

it is like THPRES, but for faults instead of EQUIL regions.

add the THPRESFT keyword

---

opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp

Thanks to @hnil  and @bska for spotting and explaining the issue.

Section keyword 'SUMMARY' was incorrectly identified as UDQ a keyword

---

CMakeLists_files.cmake
opm/output/eclipse/VectorItems/connection.hpp
tests/test_AggregateConnectionData.cpp

A set of unit tests for writing of well connection data to an Eclipse compatible restart file has been developed / constructed. The unit tests include the vectors ICON, SCON and XCON.

Unit tests for writing well connection data to Eclipse Compatible restart file

---

src/opm/output/eclipse/LoadRestart.cpp

This commit switches the segment result reload code to indexing the RSEG vector primarily by the segment number from the input file. The original scheme of using the linear index and extracting the segment number from ISEG was based on a terrible misunderstanding [%].
This is the second half of commit 0a730d94 (PR #697)
[%] Pointy Hat: @bska

RSEG: Index Results by Segment Number

---

external/cjson/README.opm
external/cjson/cJSON.c
external/cjson/cJSON.h

Update cJSON library to version 1.7.10

---

opm/parser/eclipse/EclipseState/Aquancon.hpp
src/opm/parser/eclipse/EclipseState/Aquancon.cpp
tests/parser/AquanconTests.cpp

This is an alternative PR to #716 which some random bastard closed.

Aquancon segfault

---

src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
src/opm/parser/eclipse/Generator/KeywordGenerator.cpp
src/opm/parser/eclipse/Parser/ParserEnums.cpp
src/opm/parser/eclipse/Parser/ParserKeyword.cpp
tests/parser/ScheduleTests.cpp

Trivial ... just want it out of the way from other diff.

White space

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

A runner up in the "most PR's in OPM 2019" competition.

Use DeckItem::to_bool( )

---

opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
tests/test_Summary.cpp

This just extracts some minor changes out from #674
- <kbd>tab</kbd> &rightarrow; <kbd>space</kbd> changes
- Remove trailing <kbd>space</kbd>
- Add one public method in the `Well`class.
- Add missing property in `<<` implementation.
- `std::string` &rightarrow; `const std::string&` in signature

Misc minor changes: whitespace++

---

opm/parser/eclipse/EclipseState/Schedule/GroupTree.hpp
src/opm/parser/eclipse/EclipseState/Schedule/GroupTree.cpp

A small commit to aid in debugging the new well implementation.

Add operator<< to GroupTree class + whitespace

---

examples/test_util/EclOutput.cpp

this closes https://github.com/OPM/opm-common/issues/749

fixing an overflow problem in EclOutput::make_doub_string

---

src/opm/output/eclipse/Summary.cpp

This is a minor change to support the well refactoring.
In current master this not have any effect, but it will simplify the refactoring.

Add query function need_wells() in the Summary implementation

---

examples/test_util/ESmry.cpp

This fixes issue found when using this class with summary files generated from the commercial simulator.

Fixed defect in ESmry constructor. 

---

opm/parser/eclipse/Deck/UDAValue.hpp

mark constructors explicit

---

opm/io/eclipse/EGrid.hpp
src/opm/io/eclipse/ERft.cpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/EclFile.cpp

Some small sca-induced janitoring stuff.

Remove unused variables and reduce scope

---

opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
tests/test_Summary.cpp

Add group awareness to the SummaryState object - needed for the UDQ saga.

Add group awareness to SummaryState

---

opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
tests/test_Summary.cpp

Small utility methods used in the UDQ sequel

Add size() and num_wells() methods to SummaryState

---

CMakeLists.txt
jenkins/build-opm-module.sh
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

The new well model has been merged - so this has served it's purpose.

Removed well testing from Schedule constructor

---

src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
tests/test_Summary.cpp

Fix total check - take 2; compare substrings.

Update total check in SummaryState

---

.gitmodules

@atgeirr : Care to verify this?

Update url to equinor repo in submodule

---

tests/parser/AquiferCTTests.cpp
tests/parser/AquifetpTests.cpp

Created to test the master branch.

some white space cleaning up

---

src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.hpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
src/opm/parser/eclipse/Units/Dimension.cpp

Some more stuff from sca and/or compiler warnings.

More janitoring

---

python/python/sunbeam/schedule.py
python/sunbeam/connection.cpp
python/sunbeam/schedule.cpp
python/sunbeam/well.cpp
python/tests/connection.py
python/tests/schedule.py
python/tests/wells.py

These alterations makes it possible to compile sunbeam in a separate build dir.

Compile sunbeam2

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp

Yet another small trivial - trying to get the clutter away while bisecting.

UDQASTNode: check if well/group exists before assigning

---

opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp

Summarystate operator<<

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well2.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well2.cpp

Add st arg

---

tests/msim/uda.include

Test deck for UDA simulations. Not in use (yet) - will merge quite quickly

Add test deck for UDA simulation

---

src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.hpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCONPROD
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

Baby steps. Use the UDA for WCONPROD::RESV

Use UDA for WCONPROD::RESV

---

examples/opmhash.cpp
msim/src/msim.cpp
opm/parser/eclipse/EclipseState/Grid/GridProperties.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/InjectionControls.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/ProductionControls.hpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
src/opm/parser/eclipse/EclipseState/Grid/GridProperties.cpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQContext.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunctionTable.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well2.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/Parser/Parser.cpp
test_util/EclRegressionTest.cpp
test_util/EclRegressionTest.hpp
tests/parser/ScheduleTests.cpp
tests/parser/UDQTests.cpp
tests/parser/WellTests.cpp
tests/test_ERft.cpp

Most of them are shadowing warnings.

Fixing warnings

---

src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

Do not classify 'SUMTHIN' directive as UDQ keyword

---

jenkins/build-opm-module.sh
python/CMakeLists.txt
python/pycmake/PythonPackage.cmake
python/tests/CMakeLists.txt
python/tests/group_tree.py
python/tests/grupnet.py
python/tests/parse.py
python/tests/wells.py

Adding python testing to jenkins build system.

jenkins will build python.

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.hpp
opm/parser/eclipse/EclipseState/InitConfig/InitConfig.hpp
opm/parser/eclipse/Units/Units.hpp
src/opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.cpp
src/opm/parser/eclipse/EclipseState/InitConfig/InitConfig.cpp
src/opm/parser/eclipse/Parser/ParserItem.cpp
src/opm/parser/eclipse/Units/UnitSystem.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMFSC
src/opm/parser/eclipse/share/keywords/keyword_list.cmake
tests/parser/FoamTests.cpp

This replaces #871, it can be considered my reviewed and updated version of that PR.
Also includes a minor fix for the ParserItem code generation, that bit me during development.

Add FoamConfig class and support

---

jenkins/build-opm-module.sh

I did not get the `libecl=637` to work - trying an alternative.

Jenkins libecl build

---

examples/opmi.cpp

Add basic log output to the opmi application

---

CMakeLists.txt
test_util/EclFilesComparator.cpp
test_util/EclRegressionTest.cpp
test_util/EclRegressionTest.hpp
tests/msim/test_msim.cpp
tests/parser/ParserTests.cpp

Mostly to satisfy static code analyzers.

Various janitoring

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
tests/parser/GroupTests.cpp

Minor fix in the group rewrite - this property is unused.

Remove unused group rate

---

opm/parser/eclipse/Units/UnitSystem.hpp
src/opm/parser/eclipse/Units/UnitSystem.cpp
tests/parser/UnitTests.cpp

Minor refactor of the UnitSystem construction - still leaves something to be desired .... To enable unit conversion in the opmpack utility.

Unit system refactor

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQInput.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQInput.cpp
tests/parser/UDQTests.cpp

Some small changes to support UDQ writing UDQ/UDA information to restart files.

Udq usage - preparations

---

opm/output/eclipse/AggregateGroupData.hpp
src/opm/output/eclipse/AggregateGroupData.cpp

The files `AggregateGroupData.cpp` and `AggregateGroupData.hpp` have slightly inconsistent indentation. As part of the `Group2` changes I need to make many - small changes to these files, and it is difficult to without affecting the indentation significantly - I have tried. Have therefor made this PR with only white space changes, when this is merged the real `Group2`related changes should not create additional white-space noise.
I have no strong feelings about this, and if someone else wants to submit a PR which makes the indentation in these files consistent that is fine by me. I will self merge this PR quite soon - morning of 24.th of July, because it is currently holding back the `Group2` changes.

Indentation changes

---

src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
tests/parser/ScheduleTests.cpp

Remove #define INVALID_GROUP_RATE - just use 0

---

opm/parser/eclipse/EclipseState/Schedule/Group/GroupTree.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GroupTree.cpp

Make GroupTree iterators private

---

opm/parser/eclipse/EclipseState/Schedule/Group/GroupTree.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GroupTree.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Make GroupTree::handleSeqIndex() private

---

opm/output/eclipse/WindowedArray.hpp
tests/test_WindowedArray.cpp

Add invalid size zero in WindowArray and WindowMatrix

---

opm/output/eclipse/WindowedArray.hpp
src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/output/eclipse/AggregateWellData.cpp

Issue hidden by transitive includes in some standard library implementations.
While here, also sort standard headers where appropriate.

Include <stdexcept> Where Necessary

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group2.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group2.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/GroupTests.cpp

Minor requirement for UDA based group rates

Add UnitSystem member ot Group2 class

---

src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp

These were discovered while trying to figure out why the original model 2 no longer ran. It turns out that recently merged code dealing with output (in particular FILLEPS) executed the buggy code parts, which apparently had never been ran before, triggering the bug.

Bugfix: multiple bugs in dealing with SLGOF dealt with.

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQANCONL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQANNC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQANTRC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCWFAC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFET
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFLUX
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUNNC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AUTOCOAR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AUTOREF
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Added keywords beginning w/ A.

WIP: Add keywords a

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BIGMODEL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BOUNDARY
src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BPARA
src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BPIDIMS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BRINE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BTOBALFA
src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BTOBALFV
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Adding keywords beginning w/ B.

Add keywords beginning w/ B

---

src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp

most of the related information is in #914, #919 and #920 .

removing potential keywords from ALL in SUMMARY (attempt no. 2)

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/Parser/ParseContext.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/Parser/ParseContext.cpp
tests/SPE9_CP_PACKED.DATA
tests/parser/ScheduleTests.cpp
tests/parser/data/integration_tests/SCHEDULE/SCHEDULE_WELLS_AND_GROUPS
tests/parser/data/integration_tests/SCHEDULE/SCHEDULE_WELSPECS_GRUPTREE

Add ParseContext behaviour to trimming of well/group names

---

jenkins/build-opm-module.sh

set this to run tests in parallel.

added: environment variable TESTTHREADS in build-opm-module.sh

---

opm/parser/eclipse/Units/UnitSystem.hpp
tests/parser/UnitTests.cpp

The energy dimension was not fully added.

Add missing energy to unit system measure table

---

src/opm/parser/eclipse/Units/UnitSystem.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WAGHYSTR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WAITBAL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WALKALIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WALQCALC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WAPI
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WBHGLR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WBOREVOL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCALCVAL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/Z/ZIPP2OFF
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Some keywords on Z and W. These keywords introducve the new dimensions 'energy' and 'API' which must be added to the unit system first.
When this is merged we have the "X", "Y" and "Z" Eclipse100 keywords fully covered. "W" is a long haul.

Keywords Z and W

---

opm/parser/eclipse/Parser/Parser.hpp
opm/parser/eclipse/Parser/ParserKeyword.hpp
opm/parser/eclipse/RawDeck/RawKeyword.hpp
src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Parser/ParserKeyword.cpp
src/opm/parser/eclipse/RawDeck/RawKeyword.cpp
tests/parser/ParserTests.cpp
tests/parser/RawKeywordTests.cpp
tests/parser/integration/IntegrationTests.cpp

More preparations for parsing Python code

Rawkeyword refactor

---

opm/parser/eclipse/Utility/Stringview.hpp
src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/RawDeck/StarToken.cpp
tests/parser/StringTests.cpp

Small changes to `string_view`:
1. Add `string_view::find(char c)`
2. Changed `string_view::substr()`arguments to follow `std::string::substr()`

String view find char

---

src/opm/parser/eclipse/Parser/Parser.cpp

Small message for .LOG / .PRT file with parsing progress.

Add log message with parsing progress

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group2.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.hpp
opm/parser/eclipse/Parser/ParseContext.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group2.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp
src/opm/parser/eclipse/Parser/ParseContext.cpp
tests/parser/ScheduleTests.cpp

Allows the reading GCONPROD field GUIDE_RATE.

WIP: kw GCONPROD: reads GUIDE_RATE.

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DATUMR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DATUMRX
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DCQDEFN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DELAYACT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DIAGDISP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DIFFC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DIFFDP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DIFFMMF
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DIFFMR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DIFFMTHT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DIFFMX
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DIFFMY
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DIFFMZ
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Adding some keywords beginning w/ D.

Add keywords D

---

cmake/Modules/OpmFind.cmake
cmake/Modules/OpmPackage.cmake
jenkins/build.sh
jenkins/update-opm-tests.sh

Upstream of https://github.com/OPM/ewoms/pull/532

changed: rename ewoms to opm-models

---

CMakeLists_files.cmake
msim/src/msim.cpp
opm/parser/eclipse/Deck/DeckKeyword.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/ActionResult.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Actions.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Condition.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/Deck/DeckKeyword.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Actions.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

This prepares the ActionX system for restart - the first commit stores the internalized `ACTIONX` keywords in a `DynamicState<Actions>` container and stores each individual condition in a vector of conditions.
@jalvestad: This is still work in progress, but I think it has come quite far - so you could give it a spin.

Convert Schedule::Actions to a DynamicState<Actions>

---

opm/parser/eclipse/Parser/Parser.hpp
src/opm/parser/eclipse/Parser/Parser.cpp

Convenience overload added for Python.

Add Parser::parseFile(fname, parseContext) overload

---

src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.cpp

Trivial, will self-merge when green.

Add missing include.

---

python/cxx/parser.cpp
python/python/opm/_common.py
python/python/opm/io/parser/__init__.py
python/tests/test_parser.py

Can extract parserkw's in python.

Can extract parserkw's in python.

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WGORPEN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WH2NUM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WH3NUM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WHEDREFD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WHTEMP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WLIFTOPT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WLISTARG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WLISTNAM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WNETCTRL
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Some keywords for your amusement

Add W keywords - including WNETCTRL

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DZNET
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ECLMC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EDITNNCR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EHYSTRR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENDDYN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENPCVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENSPCVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EPSDBGS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EPSDEBUG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EQLZCORN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ESSNODE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EXCAVATE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EXTFIN
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Adding keywords starting with (primarily) E.

Add keywords E

---

python/setup-build.sh.in
python/setup.py

Check CC environment variable

---

opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp

Some warnings sneaked in - sorry ;-(

Fix GuideRate warnings

---

test_util/convertECL.cpp

when converting from formatted to binary files.  This bug was only related to naming of result files and not content of the formatted files. 
This should hopefully be robust and easy to extend if that is needed.

convertECL update, fixed bug with file extensions 

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Action/Condition.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Condition.cpp
tests/parser/ACTIONX.cpp

This changes the internalization of the ACTIONX conditions to support restart.
I guess/hope this is a step in the right direction, but I am slightly uncomfortable - in particular I am uncertain on how paranthesis in the expression should be handled.

Actionx restart

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMFCN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMFRM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMFSO
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMFST
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMFSW
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMMOBP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMMOBS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FORMFEED
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASBEGIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASCONC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASEND
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASFCOMP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASFDECR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASFDELC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASFIELD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASFTARG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASMONTH
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASPERIO
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASSATC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GASYEAR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCALECON
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCONCAL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCONENG
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Added last of the keywords beginning w/ F.  Started to add keywords beginning w/ G.

added keywords beginning w/ F and G.

---

src/opm/output/eclipse/EclipseIO.cpp

This PR replaces the existing RFT file output defined in terms of private class `RFT` with the function `RftIO::write()` introduced in PR #976.
---
Note: This PR ~depends~ **depended** on #976 and ~must not be merged before it~ is ready for review now.

Hook New RFT File Writer up to Central ECLIPSE I/O Facility

---

opm/parser/eclipse/Deck/DeckItem.hpp
opm/parser/eclipse/Parser/ParserItem.hpp
src/opm/parser/eclipse/Deck/DeckItem.cpp
src/opm/parser/eclipse/Generator/KeywordGenerator.cpp
src/opm/parser/eclipse/Parser/ParserItem.cpp
src/opm/parser/eclipse/Parser/ParserRecord.cpp
src/opm/parser/eclipse/Units/Dimension.cpp
tests/parser/ParserTests.cpp

This PR just extracts trivial changes from: #1021 
A small step in the small step towards world domination. Fasten seat belts!

Misc small items

---

tests/parser/ScheduleTests.cpp

i can't imagine the compiler will optimize out this code.

fixed: remove unused variable

---

CMakeLists.txt
CMakeLists_files.cmake
opm/parser/eclipse/Python/Python.hpp
python/cxx/parser.cpp
src/opm/parser/eclipse/Python/Python.cpp
src/opm/parser/eclipse/Python/PythonInterp.cpp
src/opm/parser/eclipse/Python/PythonInterp.hpp
tests/parser/EmbeddedPython.cpp

Starting to pass handles to currently active C++ objects down to Python

 Python context

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCONTOL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCUTBACK
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GDCQ
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GDCQECON
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GDIMS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GDRILPOT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GETGLOB
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GI
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GIMODEL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GINODE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GLIFTLIM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GNETDP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GNETPUMP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRADGRUP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRADRESV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRADRFT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRADWELL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRAVCONS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRAVDR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRAVDRB
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRAVDRM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRDREACH
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRUPMAST
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRUPRIG
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Added keywords beginning w/ G.

added keywords beginning w/ G only.

---

CMakeLists_files.cmake
opm/parser/eclipse/Deck/DeckValue.hpp
src/opm/parser/eclipse/Deck/DeckValue.cpp
tests/parser/DeckValueTests.cpp

This introduces a new class DeckValue as part of issue #1038.
This class is similar to UDAValue, but can hold integer values as well.

introduced new class DeckValue.

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGDFIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGDFMD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGDFPA
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGEXSS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGFLIM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGFMOD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGINIT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGLABY
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGLINK
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGMULT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGPROP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGPULL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGSEP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGSOLV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGTABL
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Add W keywords up to WSEGTABL

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group2.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well2.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.cpp
tests/parser/ScheduleTests.cpp

More changes to the GuideRate implementation - this code still suffers from the fact we - as in @totto82 and myself do not really understand what we are doing or where we are going. But this should at least be a step in the right direction. 
Totally safe to merge - as the code is not in use yet.

Guide rate nnn

---

src/opm/output/eclipse/Summary.cpp

Minor edit in warning message.

Modify warning message

---

src/opm/parser/eclipse/Parser/Parser.cpp

Small change to the Reading keyword messages making them consistent with the other logging messages.

Made Reading message consistent with other messages.

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRUPSLAV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRUPTARG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GSATINJE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GSEPCOND
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GSSCPTST
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GSWINGF
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GTADD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GTMULT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GUIDECAL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GUPFREQ
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GWRTWCV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HALFTRAN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HAxxxxxx
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HBNUM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HDISP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMAQUCT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMAQUFET
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMAQUNUM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMDIMS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMFAULTS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMMLAQUN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMMLCTAQ
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMMLFTAQ
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMMLTWCN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMMULTFT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMMULTxx
src/opm/parser/eclipse/share/keywords/000_Eclipse100/H/HMPROPS
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Adding keywords beginning w/ G and H.

Adding keywords beginning w/ G and H. 

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSURFACT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WTADD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WTEMPQ
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WTHPMAX
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WTMULT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WVFPDP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WVFPEXP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WWPAVE
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

The remaining keywords on W - that was a long haul!

Add remaining W keywords

---

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
tests/parser/EclipseGridTests.cpp

In the case of degenerate cells there was a division by zero when calculating cell coordinates, this led to cells with volume `nan` and no joy. The first commit just removes some trailing whitespace - the relavant change is in the second commit.

Degenrate cells

---

CMakeLists_files.cmake
GenerateKeywords.cmake
opm/parser/eclipse/Deck/DeckKeyword.hpp
opm/parser/eclipse/Deck/DeckValue.hpp
src/opm/parser/eclipse/Deck/DeckKeyword.cpp
src/opm/parser/eclipse/Deck/DeckValue.cpp
tests/parser/DeckValueTests.cpp

A partial response to issue #1038: A new DeckKeyword constructor.

DeckKeyword constructor w/ DeckValue records

---

src/opm/output/eclipse/WriteInit.cpp

Flow's saturation function finalizers don't currently handle models with fewer than three active phases.  Don't attempt to fill in scaled endpoint vectors in this case, but issue a warning that we're ignoring `FILLEPS` here.

INIT File: Bypass FILLEPS for Two-Phase Systems

---

opm/parser/eclipse/EclipseState/Grid/Box.hpp
opm/parser/eclipse/EclipseState/Grid/BoxManager.hpp
src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
src/opm/parser/eclipse/EclipseState/Grid/Box.cpp
src/opm/parser/eclipse/EclipseState/Grid/BoxManager.cpp
src/opm/parser/eclipse/EclipseState/Grid/GridProperties.cpp
tests/parser/BoxTests.cpp
tests/parser/GridPropertyTests.cpp

A small step on the way to support 3D properties with only active cells.

Consider active cells in BOX implementation

---

opm/parser/eclipse/Deck/DeckKeyword.hpp
src/opm/parser/eclipse/Deck/DeckKeyword.cpp
tests/parser/DeckValueTests.cpp

Added new Deckkeyword constructors for data keywords:
```c++
DeckKeyword(const ParserKeyword& parserKeyword, const std::vector<int>& data);
DeckKeyword(const ParserKeyword& parserKeyword, const std::vector<double>& data);
```

deckkeyword: new constructors takes (ParserKeyword, std::vector).

---

src/opm/parser/eclipse/Parser/Parser.cpp

Minor rephrase of error message

Rephrased error message

---

CMakeLists.txt
CMakeLists_files.cmake
python/cxx/deck.cpp
python/cxx/export.cpp
python/cxx/export.hpp
python/cxx/unit_system.cpp
python/setup.py
python/tests/test_parser.py

In python, deck has a memberfunction that returns the UnitSystem.

python: added class UnitSystem.

---

opm/io/eclipse/ESmry.hpp
src/opm/io/eclipse/ESmry.cpp
tests/test_ESmry.cpp

Update of ESmry, now supporting non-unified result files. (backport of PR #1092)

---

python/cxx/deck_keyword.cpp

The secret janitor assistant taking a stab at some warnings.

Exc warning

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/I/ISOLNUM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/J/JFUNCR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/K/KRNUM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/K/KRNUMMF
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LANGMPL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LANGMUIR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LANGSOLV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LGRCOPY
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LGRFREE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LGRLOCK
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LGROFF
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LGRON
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LINKPERM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LKRO
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LKRORG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LKRORW
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LKRW
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LKRWR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LOAD
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

added keyword JFUNCR.
added keywords KRNUN, KRNUMMF.
added keywords LANGMPL, LANGMUIR, LANGSOLV.
added keywords LGRCOPY, LGRFREE, LGRLOCK.
added keywords LGROFF, LGRON, LINKPERM.
added keywords LKRO, LKRORG, LKRORW.
added keywords LKRW, LKRWR, LOAD.

added keywords beginning w/ I, J, K and L. (backport of PR #1099)

---

opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.cpp

TODO test if this way of scaling the target is correct.

convert targets. 

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MESSOPTS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MESSSRVC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MINNNCT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MINPORV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MLANG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MLANGSLV
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

added keywords MINPORV, MLANG, MLANGSLV.

Added keywords beginning w/ M. (backport of PR #1119)

---

src/opm/output/eclipse/Tables.cpp
tests/test_Tables.cpp

Specifically, store oil density values for every region before water density values for every region, and gas density values after water density values for every region.
This is the format expected in ECLIPSE's INIT file, and used by ResInsight's fall-back flux calculator mode for flow diagnostics.

TAB Vector (INIT): Store Phase Density Data By Columns

---

src/opm/io/eclipse/EclFile.cpp
src/opm/io/eclipse/EclOutput.cpp
tests/test_EclIO.cpp

This PR makes sure the formatted IO classes can read and write representations of NAN and INF values.
Of course the main problem is probably that you have NAN/INF in the first place.

Formatted inf

---

opm/parser/eclipse/EclipseState/Grid/Box.hpp
src/opm/parser/eclipse/EclipseState/Grid/Box.cpp
tests/parser/BoxTests.cpp

Small utility PR in the 3D field refactoring - maintain index of data elements in a BOX.

Add data_index to Box::index_list

---

CMakeLists_files.cmake
src/opm/parser/eclipse/EclipseState/Grid/GridProperties.cpp
src/opm/parser/eclipse/EclipseState/Grid/Operate.cpp
src/opm/parser/eclipse/EclipseState/Grid/Operate.hpp

This PR is just a small simplification on the way to facilitate the 3D property refactoring

Extract operate

---

src/opm/io/eclipse/ESmry.cpp

This PR fixes a bug in ESmry which was introduced with PR #1092 (support for non-unified result files). The bug (which is now fixed) caused a severe performance regression on ESmry for unified result files.

fixing severe performance issue with ESmry

---

opm/parser/eclipse/Deck/DeckKeyword.hpp
python/cxx/deck_keyword.cpp
python/python/opm/tools/time_vector.py
python/tests/test_deck.py
python/tests/test_parser.py
src/opm/parser/eclipse/Deck/DeckKeyword.cpp
tests/parser/DeckValueTests.cpp

Deckkeyword unit

---

tests/parser/data/integration_tests/BOX/BOXTEST1

Small testdata updata - similar to: #1145

Moved FLUXNUM to GRID section

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MPFANUM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULSGGD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULSGGDV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTOUTS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTREAL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTREGD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTREGH
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTSIG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTSIGV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULT_XYZ
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NARROW
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NCONSUMP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NEFAC
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Added more keywords beginning with M.

Added more keywords beginning with M.

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/Q/QHRATING
src/opm/parser/eclipse/share/keywords/000_Eclipse100/Q/QMOBIL
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Keywords on Q

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MPFANUM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULSGGD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULSGGDV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTOUTS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTREAL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTREGD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTREGH
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTSIG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULTSIGV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MULT_XYZ
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NARROW
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NCONSUMP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NEFAC
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

added keywords MULTOUTS, MULTREAL, MULTREGD.
added keywords MULTREGH, MULTSIG, MULTSIGV.
added keywords NARROW, NCONSUMP, NEFAC.

added more keywords beginning with M. (backport of #1154)

---

CMakeLists.txt
python/enable-python.sh.in

Minor change to python enable script

---

opm/parser/eclipse/Deck/DeckKeyword.hpp
python/cxx/converters.hpp
python/cxx/deck_keyword.cpp
python/tests/test_parser.py
src/opm/parser/eclipse/Deck/DeckKeyword.cpp
tests/parser/DeckValueTests.cpp

Python:
DeckKeyword can take numpy vectors.

DeckKeyword w/ vectors: takes numpy vectors. 

---

debian/changelog
dune.module
redhat/opm-common.spec

bump version to 2019.10-rc2

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NETCOMPA
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NETWORK
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NEWTON
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NEXT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NEXTSTPL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NINENUM
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

added keywords beginning w/ N.

added keywords beginning w/ N.

---

ExtraTests.cmake

Make sure these decks work in opm-common

Add parse testing of model2 decks

---

changelog.md

Please review carefully. Will be in the release, too.

Added entries to changelog concerning 2019.10 release

---

opm/io/eclipse/EclFile.hpp
src/opm/io/eclipse/EclFile.cpp
tests/test_EclIO.cpp

Motivated by #1181 - but I guess this possibility makes sense also in the C++?

Add optional argument preload=false to EclFile constructor

---

opm/parser/eclipse/EclipseState/Grid/Box.hpp

A small trivial constructor to support the Field properties refactoring

Add constructor to Box::cell_index

---

opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/FieldPropsTests.cpp

Add `FieldPropsManager::has<T>()` method - semantics is not really intuitive?!

Add has<T>() method to FieldPropsManager

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Group/GConSale.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GConSale.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCONSALE
tests/parser/GroupTests.cpp

Keyword GCONSALE added to Schedule in DynamicState.

Adding keyword GCONSALE to Schedule.

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ConnectionTests.cpp
tests/parser/FieldPropsTests.cpp

A small step towards active-cells-only 3D properties.

Field properties downstream

---

opm/parser/eclipse/EclipseState/Schedule/Action/ActionResult.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionResult.cpp
tests/parser/ACTIONX.cpp

Some minor updates to `Action::Result`class

Add copy constructor + contains() method to Action::Result

---

dune.module

Note: Must be merged in sync across repos.

bump version to 2020.04-pre

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Group/GConSale.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GConSump.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GConSale.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GConSump.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/GroupTests.cpp

Keyword GCONSUMP is handled by Schedule.

Schedule handles keyword GCONSUMP.

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NUPCOL
tests/parser/ScheduleTests.cpp

Flow needs a default value of NUPCOL larger then 3.

Change default NUPCOL to 12

---

opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

To enable better error messages

Add Location member to SummaryNode instances

---

src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
src/opm/parser/eclipse/EclipseState/Grid/GridProperties.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/C/COPYREG
tests/parser/CopyRegTests.cpp
tests/parser/Eclipse3DPropertiesTests.cpp

Small step in the 3D refactoring

Item rename

---

python/python/opm/io/ecl/__init__.py

Minor refactor - to simplify additional monkey patching.

Minor refactor to monkey-patching

---

opm/parser/eclipse/EclipseState/Aquancon.hpp
src/opm/parser/eclipse/EclipseState/Aquancon.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFETP
tests/parser/AquanconTests.cpp

Original Message:
"By default, the aquifer connections can only be specified at the faces between active and inactive cells.
The current implementation does not consider this logic, this PR is adding this part..."
For more see #1068

improvements related to Aquifer modeling (Backport of pr #1068)

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
tests/parser/FieldPropsTests.cpp

Field properties regions

---

CMakeLists.txt
test_util/summary.cpp

new program summary base on opm I/O classes. This program is similar to summary.x.

new program summary

---

opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/ConnectionTests.cpp
tests/parser/Eclipse3DPropertiesTests.cpp
tests/parser/FieldPropsTests.cpp

Minor step for 3D properties refactor

Add TableManager argument to FieldProps constructor

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
tests/parser/FieldPropsTests.cpp

Nothing big - just many small reorganisations.

More 3D Property changes

---

src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp

Satfunc lookup: prepare for only active cells

---

tests/parser/ACTIONX.cpp

testfile ACTIONC.cpp: removed 'if 0'.

---

opm/parser/eclipse/Deck/value_status.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
tests/parser/FieldPropsTests.cpp

Use enum `value::status` to keep track of defaulted / set / ... in FieldProps

Fp value status

---

opm/parser/eclipse/EclipseState/EclipseState.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp

Trivial commit to enable testing/use of the new 3D field implementation in downstream modules.

Add EclipseState::fieldProps() method

---

opm/parser/eclipse/Deck/value_status.hpp
opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/FieldPropsTests.cpp

Add property to check if 3D popertye has been defaulted

Fp defaulted

---

opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp

Small step in the 3D refactor process

FieldProps::default_region() - public property

---

opm/parser/eclipse/EclipseState/Tables/PlyrockTable.hpp
opm/parser/eclipse/EclipseState/Tables/Rock2dTable.hpp
opm/parser/eclipse/EclipseState/Tables/Rock2dtrTable.hpp

fixed: forward declared the intended classes

---

tests/parser/UDQTests.cpp

Minor step for 3D refactor - pre cleanup test.

Update test fixture to use correct grid

---

opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
tests/parser/SimulationConfigTest.cpp
tests/parser/ThresholdPressureTest.cpp

Use new 3D property for THPRES initialization

Thpres refactor

---

src/opm/parser/eclipse/EclipseState/EclipseState.cpp

Fix for: https://github.com/OPM/opm-simulators/pull/2194#issuecomment-559429494

Disable 3D property testing of ROCKNUM

---

src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp

Minor 3D - we have got a test for this now!

Enable ROCKNUM in FieldProps

---

src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
tests/parser/Eclipse3DPropertiesTests.cpp

add lwsltnum

---

examples/msim.cpp
examples/opmi.cpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/msim/test_msim.cpp
tests/msim/test_msim_ACTIONX.cpp
tests/parser/ACTIONX.cpp
tests/parser/EclipseStateTests.cpp
tests/parser/GeomodifierTests.cpp
tests/parser/GroupTests.cpp
tests/parser/MessageLimitTests.cpp
tests/parser/ParseContextTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/SummaryConfigTests.cpp
tests/parser/TuningTests.cpp
tests/parser/UDQTests.cpp
tests/parser/WLIST.cpp
tests/parser/WellSolventTests.cpp
tests/parser/WellTests.cpp
tests/parser/WellTracerTests.cpp
tests/parser/integration/IOConfigIntegrationTest.cpp
tests/parser/integration/ParseKEYWORD.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp
tests/parser/integration/TransMultIntegrationTests.cpp
tests/parser/integration/parse_write.cpp
tests/test_EclipseIO.cpp
tests/test_Restart.cpp
tests/test_Summary.cpp

Use FieldPropsManager in WellConnection - to calculate connection factors

Use FieldPropsManager in WellConnection

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Debug/status  message for WELOPEN

Log message when a well status changes from WELOPEN

---

opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
opm/parser/eclipse/EclipseState/Grid/TransMult.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
src/opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
src/opm/parser/eclipse/EclipseState/Grid/TransMult.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/MULTREGTScannerTests.cpp
tests/parser/TransMultTests.cpp

Enable testing of the new 3D properties in the Transmult code

 Add FieldPropsManager argument to TransMult constructors

---

opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp

Add temporary default constructor for FieldPropsManager

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/msim/actionx1.include
tests/parser/WellTests.cpp

See inline comment in `Well::handleWELOPEN()`

Make sure well is closed if all connections are closed for ACTIONX

---

opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp
src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp

Reorganized satfunc initializers to work for nactive and nglobal cell vectors

Reorganize satfunc initializers

---

jenkins/build-opm-module.sh

Enable 3D property testing in opm-material on jenkins

---

opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/FieldPropsTests.cpp

Add optional global flag to FieldPropsManager::porv()

---

src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Parser/ParserItem.cpp

- Fix init list order
- Remove unused functions

Janitoring

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
tests/parser/FieldPropsTests.cpp

The saturation functions should be autocreated/initialized. A bot back and fort on whether to internalize grid in FieldProps

Add autocreation of saturation functions from get<T>(keyword)

---

opm/parser/eclipse/EclipseState/Aquifetp.hpp
src/opm/parser/eclipse/EclipseState/Aquifetp.cpp

Some whitespace cleanup and remove unused includes in Aquifetp

---

opm/parser/eclipse/Parser/ParserKeyword.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp
src/opm/parser/eclipse/Parser/ParserKeyword.cpp

A little janitoring - or maybe it is called cleaning up your mess in this case?

Quell warning

---

opm/parser/eclipse/EclipseState/Schedule/MSW/SpiralICD.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/SpiralICD.cpp

fixed: this should be an int, not a double

Fix accessor type

---

opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp

It is all about memory reduction.

Add small struct to report memory usage from FieldPropsManager

---

tests/parser/integration/BoxTest.cpp

Add missing #ifdef

---

tests/parser/FieldPropsTests.cpp

Added some adidtional testing.

Add some extra testing of FieldPropsManager::get_copy

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/Valve.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Valve.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SEGMENT_PROBE
tests/parser/MultisegmentWellTests.cpp

This is still in the early WIP stage. No test is added yet. 
I think I made a bad decision to develop this based on the WSEGSICD branch, which makes WSEGSICD has to be ready and go in first.
It can be changed.  It will depend on whether we manage to get WSEGSICD in easily. 
And also this keyword looks like has the potential to create rather complicated situation.

Support wsegvalv

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQActive.hpp

This seems unused. Copy-paste issue?

remove unused member from UDQActive::InputRecord

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Possibly introduced in an earlier rebase operation.
Closes #1336.

COMPDAT: Prune Duplicate 'updateConnctions' Call

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PVTWSALT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/STWG
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

This adds the remaining alternating-record type keywords.

Add alternating keywords

---

opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/FieldPropsTests.cpp

Add active_size() method to FieldPropsManager

---

opm/parser/eclipse/EclipseState/InitConfig/Equil.hpp
opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.hpp
opm/parser/eclipse/EclipseState/InitConfig/InitConfig.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
opm/parser/eclipse/EclipseState/Tables/SimpleTable.hpp
opm/parser/eclipse/EclipseState/Tables/TableColumn.hpp
opm/parser/eclipse/EclipseState/Tables/TableContainer.hpp
src/opm/parser/eclipse/EclipseState/InitConfig/Equil.cpp
src/opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.cpp
src/opm/parser/eclipse/EclipseState/InitConfig/InitConfig.cpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
src/opm/parser/eclipse/EclipseState/Tables/SimpleTable.cpp
src/opm/parser/eclipse/EclipseState/Tables/TableColumn.cpp
src/opm/parser/eclipse/EclipseState/Tables/TableContainer.cpp

Another round of serialization preparation

---

src/opm/parser/eclipse/Parser/Parser.cpp

Add default: clause in switch

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/ACTIONS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AMALGAM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/APILIM
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/APIVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUALIST
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCHGAS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCHWAT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BDENSITY
src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BGGI
src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BOGI
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Adding some keywords missed in the first big round of keyword adding:
ACTIONS, AMALGAM, APILIM, APIVD, AQUALIST, AQUCHGAS, AQUCHWAT, BDENSITY, BGGI and BOGI.

Adding some keywords

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/ADSORP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/ROCK
src/opm/parser/eclipse/share/keywords/keyword_list.cmake
tests/parser/ParserTests.cpp

Adjusting size of keyword ROCK to unknown. 
Adding keyword ADSORP.

keyword ROCK: size->UNKNOWN. Added keyword ADSORP.

---

opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/Eclipse3DPropertiesTests.cpp
tests/parser/FieldPropsTests.cpp

Added comments to FieldPropsManager..hpp and refactored the internals of the FieldProps implementation. No API changes

Fp comments

---

python/cxx/deck_keyword.cpp

Expose methods `DeckItem::hasValue()` and `DeckItem::defaultApplied()` to Python methods `has_value()` and `defaulted()`

Python has alue

---

src/opm/common/utility/numeric/calculateCellVol.cpp

Some reorganisation of the calculations in the Cell Volume calculations - seem to give  a decent speed up the startup for moderate effort.
Full EclipseState 1m8s versus 1m45s on my machine on a large model

Init speedup

---

examples/opmi.cpp

Add some timing output to opmi application

Add time summaries to opmi

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp

Store the result of "all elements initialized" check

Add internal flag to check if all FieldProps values have been set

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
python/cxx/eclipse_state.cpp
python/cxx/export.cpp
python/cxx/export.hpp
python/cxx/field_props.cpp
python/python/opm/_common.py
python/python/opm/io/ecl_state/__init__.py
python/setup.py
python/tests/test_field_props.py
python/tests/test_props.py
src/opm/parser/eclipse/EclipseState/EclipseState.cpp

When cmake switch ENABLE_3DPROPS_TESTING is ON, this will enable testing and use of FieldPropsManager in Python as well.

Python: added class FieldProperties.

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Action/PyAction.hpp
opm/parser/eclipse/Python/Python.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/PyAction.cpp
src/opm/parser/eclipse/Python/Python.cpp
tests/parser/PYACTION.cpp

Add PyAction skeleton code

---

GenerateKeywords.cmake

Fixup: leftover from code generation refactor

---

src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Parser/ParserKeyword.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PVTWSALT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PVZG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/STOG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/STOW
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/STWG
tests/parser/ParserTests.cpp
tests/parser/integration/ParseKEYWORD.cpp

Ahh these keywords - they just neeeever end ... ;-(

Fixup of alternating records special case

---

opm/parser/eclipse/Deck/UDAValue.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/Deck/DeckOutput.cpp
src/opm/parser/eclipse/Deck/UDAValue.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellEconProductionLimits.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellFoamProperties.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellInjectionProperties.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellPolymerProperties.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
src/opm/parser/eclipse/EclipseState/Schedule/eval_uda.cpp
tests/parser/GroupTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/UDQTests.cpp
tests/parser/WellTests.cpp
tests/parser/integration/ParseKEYWORD.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

A start on fixing up after: https://github.com/OPM/opm-common/pull/1351

Uda raw data

---

opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

also add accessors and equality operator

make SummaryConfig constructible from variables

---

CMakeLists_files.cmake
opm/io/eclipse/rst/header.hpp
opm/output/eclipse/VectorItems/intehead.hpp
src/opm/io/eclipse/rst/header.cpp
src/opm/output/eclipse/InteHEAD.cpp
tests/test_InteHEAD.cpp

OK - this should be ready for review now.

 Rst header

---

CMakeLists.txt

make it work fine with the 'super-build' CMakeLists.txt

fixed: use PROJECT_XXX instead of CMAKE_XXX

---

CMakeLists_files.cmake
opm/io/eclipse/rst/connection.hpp
opm/io/eclipse/rst/header.hpp
src/opm/io/eclipse/rst/connection.cpp
src/opm/io/eclipse/rst/header.cpp
tests/test_AggregateConnectionData.cpp
tests/test_InteHEAD.cpp

Simple POD class for connection info loaded from restart file

---

src/opm/output/eclipse/EclipseIO.cpp

This commit ensures that we do not create RFT output files unless the simulation model specifically requests such output (e.g., through keywords WRFT or WRFTPLT).  Notably, the `OutputStream::RFT`
constructor will also create the file so we must take care not to form an object of this type unless actually needed.
~As an implementation detail, we scan the SCHEDULE section for the first active RFT event&mdash;represented by its report step&mdash;and then cache this step to simplify later lookups.~

Don't Output RFT Files Unless Specifically Requested

---

docs/keywords.txt
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCONHIST

Consistency with other keywords

Clean up item names in json for WCONHIST

---

opm/parser/eclipse/Utility/String.hpp
tests/test_PaddedOutputString.cpp

Small utility function used in the Well / Group POD classes.

Add trim method to PaddedOutputString<N>

---

CMakeLists_files.cmake
ExtraTests.cmake
opm/io/eclipse/rst/connection.hpp
opm/io/eclipse/rst/group.hpp
opm/io/eclipse/rst/header.hpp
opm/io/eclipse/rst/segment.hpp
opm/io/eclipse/rst/state.hpp
opm/io/eclipse/rst/well.hpp
opm/output/eclipse/VectorItems/group.hpp
src/opm/io/eclipse/rst/connection.cpp
src/opm/io/eclipse/rst/group.cpp
src/opm/io/eclipse/rst/header.cpp
src/opm/io/eclipse/rst/segment.cpp
src/opm/io/eclipse/rst/state.cpp
src/opm/io/eclipse/rst/well.cpp
tests/rst_load.cpp
tests/test_AggregateConnectionData.cpp
tests/test_AggregateMSWData.cpp
tests/test_AggregateWellData.cpp
tests/test_InteHEAD.cpp
tests/test_rst.cpp

Simple `state` class for well and group information loaded from restart file.

POD classes for restart info

---

opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
tests/parser/DynamicStateTests.cpp
tests/parser/DynamicVectorTests.cpp
tests/parser/EventTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/TimeMapTest.cpp

Small step on the this task: https://github.com/OPM/opm-common/issues/1396

Time map immutable

---

src/opm/output/eclipse/Summary.cpp

In the current master, Norne generates more than 1100 warnings for unhandled summary keywords. Many of those are duplicates, because the same warning will be repeated for all involved wells. With this PR, we will only see each (keyword, location) combination warned about once. This reduces the number of such warnings on Norne to 87 or so.
This restores older warning behaviour in terms of numbers of warnings, but keeps the most important feature that was added: printing the deck location of the triggering keyword. Furthermore, the warnings are now sorted by location first rather than by keyword first.

Remove duplicate warnings for unhandled summary keywords.

---

opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
src/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp

One fix and one unused member removal.

Fix TimeMap constructor and remove IOConfig member

---

src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENDSCALE
tests/parser/TimeMapTest.cpp

TimeMap iterate only over SCHEDULE section

---

opm/parser/eclipse/EclipseState/EclipseConfig.hpp
opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.hpp
src/opm/parser/eclipse/EclipseState/EclipseConfig.cpp
src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp

Minor cleanup / refactor to which is a minor step on this: https://github.com/OPM/opm-common/issues/1396
Downstream: https://github.com/OPM/opm-simulators/pull/2308
All these small steps - not did I know that they were life itself.

Ecl config cleanup

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/SimulationConfig/RockConfig.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/RockConfig.cpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
tests/parser/SimulationConfigTest.cpp

Internalize rock pecularities
Dwonstream: https://github.com/OPM/opm-simulators/pull/2303

Rock config

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

To enable constructing wells from restart file

Add Schedule::addWell() overload which does not take Deck arguments

---

CMakeLists_files.cmake
opm/io/eclipse/rst/connection.hpp
opm/io/eclipse/rst/state.hpp
opm/io/eclipse/rst/well.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
src/opm/io/eclipse/rst/connection.cpp
src/opm/io/eclipse/rst/state.cpp
src/opm/io/eclipse/rst/well.cpp
tests/parser/ScheduleRestartTests.cpp
tests/test_AggregateConnectionData.cpp
tests/test_AggregateWellData.cpp

Additional small steps on https://github.com/OPM/opm-common/issues/1396

Rst testing

---

src/opm/io/eclipse/rst/connection.cpp
tests/test_AggregateConnectionData.cpp

Bug in default handling in switch - funny this even compiled

Fix bug in switch default case

---

CMakeLists_files.cmake
opm/io/eclipse/rst/segment.hpp
opm/output/eclipse/VectorItems/msw.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/SpiralICD.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/Valve.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/icd.hpp
src/opm/io/eclipse/rst/segment.cpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/SpiralICD.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Valve.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/icd.cpp
tests/parser/MultisegmentWellTests.cpp

Small updates to the segment implementation. To simplify instantiation from restart file. Part of: https://github.com/OPM/opm-common/issues/1396

Segment updates

---

opm/io/eclipse/rst/segment.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
src/opm/io/eclipse/rst/segment.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/updatingConnectionsWithSegments.cpp

More small updates to the segment model.
Part of the https://github.com/OPM/opm-common/issues/1396 sequel

Segments updates2

---

opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/MultisegmentWellTests.cpp
tests/rst_load.cpp

Several small simplifications of MSW input code. The code originally had "openings" (which were not completed) for a more complex input scheme - with this PR those openings are removed. The benefit is simplification.
Small step on: https://github.com/OPM/opm-common/issues/1396
Dwonstream: https://github.com/OPM/opm-simulators/pull/2333

Wellsegments state

---

opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Compsegs.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/updatingConnectionsWithSegments.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp

Simplify the code for connection segments and connections to one function call.
https://github.com/OPM/opm-common/issues/1396

Connection segment

---

ExtraTests.cmake

The test will be significantly refactored - remove for now.

Remove rst_load based test

---

opm/common/utility/FileSystem.hpp
tests/test_OutputStream.cpp

sorry about that. @bska @atgeirr

fixed: wrong preprocessor check for gcc7

---

opm/parser/eclipse/EclipseState/Schedule/VFPInjTable.hpp
opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.hpp
src/opm/parser/eclipse/EclipseState/Schedule/VFPInjTable.cpp
src/opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.cpp
tests/parser/ScheduleTests.cpp
tests/parser/TableManagerTests.cpp

Drop use of boost::multi_array in VFP classes

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/WTEST.cpp
tests/parser/WellTests.cpp

Simplify adding wells to Schedule object
Part of: #1396

Add new Schedule::addWell() overload + update Well constructor args

---

redhat/opm-common.spec

Use devtoolset-8 in redhat packaging

---

opm/parser/eclipse/EclipseState/Tables/BrineDensityTable.hpp

Add size() method to BrineDesityTable

---

opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp

Use std::size_t instead of int for size

---

opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
tests/parser/GroupTests.cpp

- One class vs struct declaration.
- Unused variables in a test.

Silence warnings.

---

opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp

Part of #1396
Downstream: https://github.com/OPM/opm-simulators/pull/2360

Simplify WellSegments serialization construction

---

examples/opmpack.cpp

Minor improvement in the opmpack utility - it can now copy over binary files which are refered to in the deck - most notably this includes the restart file.

The opmpack utility can also copy restart and import files

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Small reshuffle of the spin-through-keywords functionality in Schedule
Part of: #1396

Extracted timestepnning keywords from the regular handleKeyword()

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Add restart info to TimeMap() constructor

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Tables/DenT.hpp
opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/Tables/DenT.cpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
tests/parser/TableManagerTests.cpp

Add simple POD class to internalize keywords xxxDENT
Dowstream:
https://github.com/OPM/opm-material/pull/404
https://github.com/OPM/opm-simulators/pull/2362

Add simple POD class to internalize keywords xxxDENT

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Tables/SolventDensityTable.hpp
opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/Tables/SolventDensityTable.cpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp

To avoid deck usage downstream.

added: internalize SDENSITY table

---

opm/output/eclipse/VectorItems/well.hpp
src/opm/output/eclipse/AggregateWellData.cpp

Small simplification for: #1396

Remove opm specific well type WTUnk

---

examples/opmpack.cpp

The old implementation caused some problems in https://github.com/OPM/opm-simulators/pull/2358

Fix bug/problem in copy_file in opmpack

---

opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.hpp
src/opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

there is no vappars per pvt region. do not store it as such either.

changed: simplify OilVaporizationProperties

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Tables/StandardCond.hpp
opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/Tables/StandardCond.cpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp

To avoid deck usage downstream

internalize StandardConditions

---

opm/parser/eclipse/EclipseState/Tables/FlatTable.hpp
opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/parser/eclipse/EclipseState/Tables/Tables.cpp

To avoid deck usage downstream

internalize TLMIXPAR

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/InitConfig/InitConfig.hpp
opm/parser/eclipse/EclipseState/InitConfig/PolymerConfig.hpp
src/opm/parser/eclipse/EclipseState/InitConfig/InitConfig.cpp
src/opm/parser/eclipse/EclipseState/InitConfig/PolymerConfig.cpp

Feels somewhat over-engineered just for a bool but it follows established patterns.

added: PolymerConfig class

---

opm/parser/eclipse/EclipseState/Tables/FlatTable.hpp
opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/parser/eclipse/EclipseState/Tables/Tables.cpp

To avoid deck usage downstream

internalize PLMIXPAR

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp

Trivial rename to help my own sanity

Rename function WellConnections::orderConnections()

---

opm/parser/eclipse/EclipseState/Runspec.hpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp

To avoid deck usage downstream

internalize STONE|STONE1|STONE2

---

opm/output/eclipse/VectorItems/connection.hpp
opm/output/eclipse/VectorItems/well.hpp
src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/output/eclipse/AggregateWellData.cpp

Add items to resart file - magic numbers provided by @tskille 
This will add two new items to the `SWEL` vector and one new item to the `SCON` vevctyor, for each well and connection - i.e. data update is required.

Restart items

---

opm/parser/eclipse/EclipseState/Runspec.hpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
tests/parser/RunspecTests.cpp

unfortunate naming, unfortunate location
Follow-up to https://github.com/OPM/opm-common/pull/1543

changed: relocate and rename StoneType enum

---

opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

As discussed at dev-meeting, this is the start of moving the serialization support into the classes.

add serialization template to SummaryConfig

---

src/opm/output/eclipse/AggregateMSWData.cpp

Various small drive-by refactorings/improvements while I try to reassamble a valid MSW state from a restart file.

Segment reorder refactor

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Jenkins fails on #1436 (works on my machine ...) so I am breaking it up.

Add context aware Schedule::cmp() function

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Implement Shcedule::laod_rst() function

Initialize Schedule from restart file

---

CMakeLists_files.cmake
ExtraTests.cmake
tests/rst_test.cpp

Add integration test for restart based Schedule init

---

opm/io/eclipse/rst/connection.hpp
opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
src/opm/io/eclipse/rst/connection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp

Extracted small commits from the effort to initialize a MSW well from restart file
Part of #1396

Rst msw init

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

This adds serialization v2 for Schedule.

Add serialization template to Schedule

---

opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/Edit/EDITNNC.hpp
opm/parser/eclipse/EclipseState/Grid/GridDims.hpp
opm/parser/eclipse/EclipseState/Grid/NNC.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/BCConfig.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/RockConfig.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.hpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp

More internal serialization support.

Internal serialization in EclipseState - part 1

---

opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/Grid/Fault.hpp
opm/parser/eclipse/EclipseState/Grid/FaultCollection.hpp
opm/parser/eclipse/EclipseState/Grid/FaultFace.hpp
opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
opm/parser/eclipse/EclipseState/Grid/TransMult.hpp
opm/parser/eclipse/EclipseState/Util/OrderedMap.hpp
src/opm/parser/eclipse/EclipseState/Grid/Fault.cpp
src/opm/parser/eclipse/EclipseState/Grid/FaultCollection.cpp
src/opm/parser/eclipse/EclipseState/Grid/FaultFace.cpp
src/opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
src/opm/parser/eclipse/EclipseState/Grid/TransMult.cpp

Sits on top of https://github.com/OPM/opm-common/pull/1568
It is becoming very hard to keep these PR's separate.

Internal serialization in EclipseState - part 2

---

opm/parser/eclipse/EclipseState/EclipseConfig.hpp
opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
opm/parser/eclipse/EclipseState/InitConfig/Equil.hpp
opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.hpp
opm/parser/eclipse/EclipseState/InitConfig/InitConfig.hpp
src/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
src/opm/parser/eclipse/EclipseState/InitConfig/Equil.cpp
src/opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.cpp

Sits on top of https://github.com/OPM/opm-common/pull/1573

Internal serialization in EclipseState - part 3

---

opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/EndpointScaling.hpp
opm/parser/eclipse/EclipseState/Runspec.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Actdims.hpp
opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQActive.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQInput.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParams.hpp
opm/parser/eclipse/EclipseState/Tables/Tabdims.hpp
src/opm/parser/eclipse/EclipseState/EndpointScaling.cpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQActive.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp

Sits on top of https://github.com/OPM/opm-common/pull/1578
Now https://github.com/OPM/opm-common/pull/1565 is also a prerequisite.
I am doing so much extra work moving things between branches now, I will halt the work until prerequisites have been processed.

 Internal serialization in EclipseState - part 4

---

src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp

Use mutable accessor instead of assigning directly

Use Well::updateRefDepth() in Well::updateSegments()

---

opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp

Exactly what constitutes the top segment is not entirely clear to me - here I have just made the current implementation more explicit.

Add method WellSegments::topSegment()

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ScheduleTests.cpp

Remove unused members and methods from WellConnections
Downstream: https://github.com/OPM/opm-simulators/pull/2482

Remove num removed

---

src/opm/output/eclipse/AggregateConnectionData.cpp

This is a small refactoring to help myself complete this: #1606

Minor refactoring for improved readability

---

src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/AggregateWellData.cpp

Use reference

---

tests/test_AggregateConnectionData.cpp

With this PR the test `test_AggregateConnectionData` is updated to use "more real" connection data. Part of #1396

Connection testing

---

test_util/convertECL.cpp

Another morning, another compile error...

Fix type mismatch error for EclEntry.

---

opm/output/data/Wells.hpp
python/cxx/eclipse_io.cpp
tests/test_Wells.cpp

Small function to enable connection lookup based on global index. Extracted from: #1614

Find connection

---

CMakeLists.txt
opm/parser/eclipse/EclipseState/Schedule/Action/Actions.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/PyAction.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Actions.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/PyAction.cpp
tests/parser/ACTIONX.cpp

Small fixes in preparation for #1620

Pyaction fixup

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/Tables/SimpleTable.hpp
opm/parser/eclipse/EclipseState/Tables/TracerVdTable.hpp
opm/parser/eclipse/EclipseState/TracerConfig.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Tables/SimpleTable.cpp
src/opm/parser/eclipse/EclipseState/Tables/Tables.cpp
src/opm/parser/eclipse/EclipseState/TracerConfig.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/T/TBLK
tests/parser/TracerTests.cpp

Add some dimension trickery on top of #1627 
My blood sugar is dangerously low at the moment - if someone wants to point out that I have got the dimsensions wrong they are most probably right.
Is this this tracer stuff in use? Someone want's to step up with a real example?

Internalize tracers

---

src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp

In particular, declare that the injection well supports RATE, RESV, and THP limits/targets if such values are available in the SWEL array.

Simulation Restart: Restore All Available Injection Control Modes

---

src/opm/io/eclipse/SummaryNode.cpp
src/opm/output/eclipse/Summary.cpp

quell compiler warnings

---

opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ScheduleRestartTests.cpp

Connections sort item

---

tests/parser/MessageLimitTests.cpp
tests/parser/WellTests.cpp
tests/parser/integration/ParseKEYWORD.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

Remove stale boost includes

---

opm/parser/eclipse/Python/Python.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Python/Python.cpp
src/opm/parser/eclipse/Python/PythonInterp.cpp
src/opm/parser/eclipse/Python/PythonInterp.hpp
tests/parser/EmbeddedPython.cpp

Make sure PythonInterpreter can be safely disabled

---

src/opm/io/eclipse/ESmry_write_rsm.cpp

quell shadowing warnings

---

opm/io/eclipse/ESmry.hpp
src/opm/io/eclipse/ESmry.cpp

Some small changes to ESmry - not very interesting on their own, but steps towards supporting DATES in the RSM files. 
Related to - and should be merged before: #1669

Esmry rm seqtime

---

opm/common/utility/TimeService.hpp
opm/io/eclipse/ESmry.hpp
python/cxx/eclipse_io.cpp
python/python/opm/io/ecl/__init__.py
src/opm/common/utility/TimeService.cpp
src/opm/io/eclipse/ESmry.cpp
tests/parser/TimeMapTest.cpp
tests/test_ESmry.cpp

Timezones are currently eating at my soul ....

Use std::chrono instead of std::vector<int> to store start date

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp

Changes required to restart M2 without historical schedule section - work in progress.

Rst msw M2

---

opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp

This feature adds the method `bool DynamicState<T>::is_new_data(size_t time_step)`, which returns `true` if the data at `time_step` is changed from `time_step - 1`, or else `false`.

Allow interrogating DynamicState for changes in data

---

opm/io/eclipse/ESmry.hpp
src/opm/io/eclipse/ESmry_write_rsm.cpp
src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp

Respect the DATE keyword in RUNSM output

Runsum dates

---

src/opm/io/eclipse/ESmry_write_rsm.cpp

Minor fixes to the generated RSM files - these files really require the whitespace perfectly aligned!

Rms output fixup

---

opm/common/utility/TimeService.hpp
src/opm/common/utility/TimeService.cpp
src/opm/io/eclipse/rst/header.cpp
tests/parser/DynamicStateTests.cpp
tests/parser/DynamicVectorTests.cpp
tests/parser/EventTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/TimeMapTest.cpp

A small convenience for those of us who are `{ }` challenged.

Add three argument (year, month, day) constructor TimeStampUTC

---

opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp

This PR needs downstream changes.

Scale guiderates with rates

---

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
tests/parser/EclipseGridTests.cpp

 Grid cleanup

---

opm/io/eclipse/ESmry.hpp
python/cxx/eclipse_io.cpp
python/tests/test_esmry.py
src/opm/io/eclipse/ESmry.cpp
test_util/summary.cpp

- new overload function for keywordList, list keys based on pattern (string argument)
- summary program wild card elements (keys including * or ?)
- python bindings to new member function

Updates of ESmry

---

opm/parser/eclipse/EclipseState/EndpointScaling.hpp
opm/parser/eclipse/EclipseState/Runspec.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/PYACTION.cpp

To quell some warnings emitted with clang(-8).

Some more janitoring

---

opm/parser/eclipse/EclipseState/Schedule/Action/PyAction.hpp

Just add an empty API point so that the changes in the simulator can be merged. The real content comes in #1620 
Downstream api consumer: https://github.com/OPM/opm-simulators/pull/2528

Add api for PyAction::run()

---

CMakeLists.txt
CMakeLists_files.cmake
msim/src/msim.cpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/share/keywords/900_OPM/E/EXIT
src/opm/parser/eclipse/share/keywords/keyword_list.cmake
tests/EXIT_TEST.DATA
tests/msim/msim_exit_status.cpp
tests/test_exit_status.sh

Add OPM special keyword EXIT which can be used to terminate simulation in ACTIONX block

Action exit

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFET
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFETP

AQUCT, AQUFET, AQUFETP
It should not change any cases we are using.

small adjustments for a few AQU keywords

---

opm/io/eclipse/rst/well.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/io/eclipse/rst/well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/WTEST.cpp
tests/parser/WellTests.cpp

This is for reporting; if input is different from default we log a warning and ignore it.

Check WELSPECS values

---

opm/io/eclipse/rst/well.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/io/eclipse/rst/well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/WTEST.cpp
tests/parser/WellTests.cpp

Internalize PVT number for well. Will be output in WELSPECS report

Add pvt_table as member for Well

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/REGION_PROBE

This fixes a "Unknown keyword" bug; the fix is a bit band aid and not 100% correct. A more thorough fix will require a more significant refactoring I think.

Minor fixup to REGION fip summary keyword regexp

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/C/CPIFACT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/C/CPIFACTL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GETDATA
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LXFIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LYFIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LZFIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/O/OUTSOL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PERMJFUN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PLYESAL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PLYKRRF
src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/RADFIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SAMG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WELMOVEL
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Keywords ... fond memories ... :_)

Add some missing keywords

---

CMakeLists_files.cmake
msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
opm/parser/eclipse/EclipseState/Schedule/Action/PyAction.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/Python/Python.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Actions.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/PyAction.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/Python/EmbedModule.hpp
src/opm/parser/eclipse/Python/PyRunModule.cpp
src/opm/parser/eclipse/Python/PyRunModule.hpp
src/opm/parser/eclipse/Python/Python.cpp
src/opm/parser/eclipse/Python/PythonInterp.cpp
src/opm/parser/eclipse/Python/PythonInterp.hpp
tests/act1.py
tests/action_missing_run.py
tests/action_syntax_error.py
tests/msim/MSIM_PYACTION.DATA
tests/msim/action1.py
tests/msim/action2.py
tests/msim/test_msim_ACTIONX.cpp
tests/parser/ACTIONX.cpp
tests/parser/EmbeddedPython.cpp
tests/parser/PYACTION.cpp
tests/wclose.py

This code is getting very close to "complete and usable" - up until now the Python code has been just a module, and the context from the simulator has been injected into the model prior to running. I.e. as part of this PR there is a test module `action2.py` which looks like:
```Python
wells_shut = False
sim = context.sim
schedule = context.schedule
report_step = context.report_step
for well in sim.wells:
if sim.well_var(well, "WWCT") > 0.50:
schedule.shut_well(well, report_step)
wells_shut = True
context.result = wells_shut
```
this works - but in particular it is difficult to check the syntax up front. I have considered the alternative where the script must have a function `run()`:
```Python
def run(schedule, sim, report_step):
wells_shut = False
for well in sim.wells:
if …
```

Run pyaction

---

src/opm/output/eclipse/report/WELSPECS.cpp

Fill on some of the unknown elements in WELSPECS report

Welspecs unknown

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/output/eclipse/report/WELSPECS.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/WTEST.cpp
tests/parser/WellTests.cpp

Add undefined items to the WELSPECS report

Internalize Gas inflow equation flag in Well - for reporting

---

CMakeLists.txt

to quell some (shadowing) warnings

changed: mark pybind11 headers as system headers

---

python/setup.py

fixed: it's test_suite, not tests_suite

---

opm/parser/eclipse/Deck/DeckItem.hpp
opm/parser/eclipse/Parser/ParserItem.hpp
opm/parser/eclipse/Utility/Typetools.hpp
src/opm/parser/eclipse/Deck/DeckItem.cpp
src/opm/parser/eclipse/Deck/DeckOutput.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
src/opm/parser/eclipse/Parser/ParserItem.cpp
src/opm/parser/eclipse/Parser/raw/RawRecord.hpp
src/opm/parser/eclipse/Parser/raw/StarToken.cpp
src/opm/parser/eclipse/Parser/raw/StarToken.hpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/U/UDQ
tests/parser/ParserTests.cpp
tests/parser/UDQTests.cpp

A deep dive into real innards of the parsing process to fix: #1680

Raw string quote

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/ScheduleTests.cpp

Check if well structure (connections++) has changed. Will not flag a change for changes in production/injection

Add function Schedule::changed_wells() to use in WELSPECS reporting

---

src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/report/WELSPECS.cpp

Rebased++ version of #1710
On top of #1729

Report check time

---

opm/output/eclipse/WriteRPT.hpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/WriteRPT.cpp
src/opm/output/eclipse/report/WELSPECS.cpp

- The table datastructures are created dynamically
- Pass a context variable to all fetcher functions
- Add function to look up grid cell depth

Changes in WELSPECS reports implementation

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
tests/parser/MultisegmentWellTests.cpp

Add utility function to calculate depth change of one segment

Add method WellSegments::segmentDepthChange()

---

src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp

Fixup to: https://github.com/OPM/opm-common/pull/1731#issuecomment-618028278

Segment sorting - check if already in order

---

opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
tests/parser/MultisegmentWellTests.cpp

Small utility function to get a set of branch id's from a a WellSegmnent

Add method WellSegments::branches()

---

opm/parser/eclipse/Units/Units.hpp
src/opm/io/eclipse/ERsm.cpp
src/opm/output/eclipse/Summary.cpp

Unconditionally add  'YEARS` to the summary files. Will require a data update.

Summary years

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PRVD
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Add keyword PRVD

---

src/opm/output/eclipse/report/WELSPECS.cpp

The WELSPECS report will need some refactoring - this is a step on the way.

Welspecs report refactor

---

src/opm/io/eclipse/ESmry_write_rsm.cpp

- MAI -> MAY
- Update text header with simulation time and flow version
Some minor tweaks in the RSM file. ~~Will in addition need to calculate the YEARS column - hope to get that into the release.~~

Small fixes to RSM output

---

CMakeLists.txt

Python files should go in $PREFIX/dist-packages on debian

---

tests/test_calculateCellVol.cpp
tests/test_cubic.cpp

Remove #include which is not needed

---

opm/output/eclipse/WriteRPT.hpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/WriteRPT.cpp
src/opm/output/eclipse/report/WELSPECS.cpp

This feature adds Unit System awareness to WELSPECS reports, along with refactors from #1732.

Add Unit System awareness to WELSPECS reports

---

opm/parser/eclipse/Deck/UDAValue.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/Deck/UDAValue.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQActive.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellInjectionProperties.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WELTARG
tests/parser/ScheduleTests.cpp

Continuation of #1762 
With this PR UDA values can be used in WELTARG - not tested all the way through flow; but I the opm-common part should be OK

Weltarg uda

---

opm/output/eclipse/WriteRPT.hpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/WriteRPT.cpp
src/opm/output/eclipse/report/WELSPECS.cpp

This feature implements the Group Hierarchy Data visual subreport in WELSPECS.

Implementing Group Hierarchy Report

---

opm/parser/eclipse/EclipseState/Schedule/Group/GTNode.hpp
src/opm/output/eclipse/report/WELSPECS.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GTNode.cpp

Group level report

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/GasLiftOpt.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/GasLiftOpt.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GLIFTOPT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LIFTOPT
tests/parser/ScheduleTests.cpp

This PR internalizes the kewyords `LIFTOPT, GLIFTOPT` and `WLIFTOPT` which controls the use of gas lift optimization.

Internalize keywords for Gas Lift Optimization

---

opm/parser/eclipse/EclipseState/Schedule/Group/GTNode.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/output/eclipse/report/WELSPECS.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

Now this was a really bad one - surprising it has not kicked before

Bug: pointer -> to stack variable - fix with parent *name*

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/O/OPERATER
tests/parser/FieldPropsTests.cpp

See: https://github.com/OPM/opm-simulators/issues/2603#issuecomment-626301572 - which is essentially spot on.

Fp operate maxlim

---

examples/make_lodsmry.cpp

Let make_lodsmry also work without OpenMP.

---

opm/parser/eclipse/EclipseState/Schedule/Network/ExtNetwork.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Network/ExtNetwork.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/NetworkTests.cpp

Tha almightly VFP table - can also be used for network manipulations!

When defining branch properties: vfp == 0 should delete branch

---

src/opm/output/eclipse/AggregateUDQData.cpp

As requested from restart department.

Fix group number used in IUAP restart array

---

opm/parser/eclipse/EclipseState/EclipseConfig.hpp
opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
python/cxx/eclipse_config.cpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/parser/eclipse/EclipseState/EclipseConfig.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp

This is a rebased version of #1786 with one extra commit. Will merge when Green. Sorry it has taken so long.

Halvor opm restart

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp

Fixes: https://github.com/OPM/opm-simulators/issues/2647

All shut message

---

opm/parser/eclipse/EclipseState/Schedule/GasLiftOpt.hpp
src/opm/parser/eclipse/EclipseState/Schedule/GasLiftOpt.cpp

Added getters for `gaslift_increment()` and `min_eco_gradient()` in the `Opm::GasLiftOpt` class.

Added some getters for LIFTOPT.

---

opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp

Just extracted trivial commits from: #1804

Sicd refactor step0

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Refactorings to get rid of unwanted manipulation of ICD object in opm-simulator.
The main content of this PR is the new COMPSEGS handling in commit: "Refactor COMPSEGS handling"

Segment perf length

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Group/GPMaint.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GPMaint.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GPMAINT
tests/parser/GroupTests.cpp

Started to add support for GPMAINT in input layer
Dwonstream: https://github.com/OPM/opm-simulators/pull/2636

Add code to internalize GPMAINT keyword in Group objects

---

opm/parser/eclipse/EclipseState/Schedule/Group/GPMaint.hpp

Fix: bug in serializer function for GPMaint class

---

tests/parser/GroupTests.cpp

Quell a warning - and verify the build

Remove unused variable

---

examples/make_lodsmry.cpp

Number of threads mumbo was never applied.

fixed: include config.h for HAVE_OPENMP

---

opm/output/eclipse/AggregateUDQData.hpp
src/opm/output/eclipse/AggregateUDQData.cpp
src/opm/output/eclipse/CreateUdqDims.cpp

Remove trailing whitespace

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
src/opm/output/eclipse/AggregateUDQData.cpp

Small change extracted from: #1835

Udq named constant

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

Create utility method Schedule::restart_groups() - changes forked off from #1835

Schedule restart group

---

src/opm/output/eclipse/LoadRestart.cpp

Restartview - add code to handle `<std::string> / ECL::CHAR` type. Small change extracted from: #1835

Restartview

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/output/eclipse/AggregateUDQData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

Actually use the `Schedule::restart_groups()`- this should have been part of #1838

Use Schedule::restart_groups()

---

CMakeLists_files.cmake
src/opm/output/eclipse/LoadRestart.cpp
tests/UDQ_BASE.DATA
tests/UDQ_RESTART.DATA
tests/test_Restart.cpp

This is #1835 which was accidentally closed
A testcase is prepared here: https://github.com/OPM/opm-simulators/pull/2658

Recover UDQ values from restart file

---

opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
python/cxx/summary_state.cpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
tests/test_Summary.cpp

Use SumState::has_group_var() / SumState::get_group_var()

---

src/opm/output/eclipse/AggregateGroupData.cpp

Use SummaryState::has_group_var() / SummaryState::get_group_var()

---

opm/output/data/Wells.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

Output brine related rates and totals
Currently, the total rates are wrong. This needs to be fixed before merging

add brine output

---

python/cxx/schedule.cpp
python/tests/test_schedule.py

Minor step to facilitate PYACTION based actions

Add python wrapper for Schedule::wellNames( const std::string& )

---

src/opm/output/eclipse/AggregateGroupData.cpp

Small refactorings on the way to support restart with UDQ/UDQ values in use

Igrp fix refactor

---

msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
opm/output/data/Groups.hpp
opm/output/eclipse/RestartValue.hpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/output/eclipse/RestartValue.cpp
tests/test_EclipseIO.cpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_restartwellinfo.cpp

Add data::GroupValues member to RestartValue

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/WLIST.cpp

Update WLIST to handle WLIST and well pattern arguments

---

msim/src/msim.cpp
opm/parser/eclipse/EclipseState/Schedule/Action/ActionContext.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WList.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WListManager.hpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionContext.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WListManager.cpp
tests/parser/ACTIONX.cpp
tests/parser/WLIST.cpp

With this PR the ACTIONX evaluator can use WLIST arguments.

Actionx wlist

---

opm/output/data/GuideRateValue.hpp
tests/test_data_GuideRateValue.cpp

Missed in commit 4f7d41ee1.
Pointy Hat: [at]bska.

GuideRateValue: Insert Copyright Notice

---

python/enable-python.sh.in

Update PYTHONPATH in enable-python.sh

---

opm/json/JsonObject.hpp
src/opm/json/JsonObject.cpp
tests/json/jsonTests.cpp

This is something I have used in my internal fighting with the restart files - might be of interest? I'm putting it up here so I know where it is ;-)

Add build and write functionality to JsonObject

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Tables/TLMixpar.hpp
opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/Tables/TLMixpar.cpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
tests/parser/TableManagerTests.cpp

Fix for: https://github.com/OPM/opm-common/issues/1855

Implement TLMIXPAR as dedicated vector of struct - not table

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCUTBACK

Add GLR_LIMIT to WCUTBACK

---

src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
tests/parser/RestartConfigTests.cpp

Fix for: https://github.com/OPM/opm-common/issues/1862
Thank you to @bska for providing the test case which constitutes the bulk of this PR. With some help from Equinor I have concluded that report step 1 should *not* have a restart file.

Correctly handle RPTRST in SOLUTION section

---

src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/AggregateGroupData.cpp

Some logical tests in the code has been corrected / improved - testing ongoing

Corrections and improvements to Eclipse compatible restart file output 

---

opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp
tests/test_Summary.cpp

Remove function SummaryConfig::requireFIPNUM

---

CMakeLists_files.cmake
opm/common/utility/Serializer.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.cpp
tests/parser/UDQTests.cpp
tests/test_Serializer.cpp

Slightly expand on the very basic serializer used for `SummaryState`- now also used for `UDQState`.

Serializer class

---

opm/common/utility/Serializer.hpp
tests/test_Serializer.cpp

See discussion here: https://github.com/OPM/opm-common/pull/1895#pullrequestreview-479985190

Handle empty strings in serializer

---

opm/parser/eclipse/EclipseState/Grid/Box.hpp
src/opm/parser/eclipse/EclipseState/Grid/Box.cpp
tests/parser/BoxTests.cpp

Small preparation to allow for global 3D properties.

Box global list

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/WellTests.cpp

Add boolean flag to indicate whether a well has been an open producer 
Support code for alternative implementation of: https://github.com/OPM/opm-common/pull/1912

First production

---

msim/src/msim.cpp
src/opm/output/eclipse/Summary.cpp
tests/SPE1CASE1.DATA
tests/msim/test_msim.cpp
tests/parser/SummaryConfigTests.cpp

Support for summary variable FMWPA - number of abondoned wells.

Add functionality for FMWPA - number of abondoned wells

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
tests/parser/FieldPropsTests.cpp

This PR adds *limited* support for storing/handling all the cells in 3D field. The support is specifically aimed at addressing a situation which arises with a combination of MULTZ and PINCH:ALL; it is not fully general and does in particular not support all operations on 3D keywords.
~~Test case: https://github.com/OPM/opm-tests/pull/356~~
~~Regression test: https://github.com/OPM/opm-simulators/pull/2765~~

Enable some support for global keywords

---

opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp

Support functionality for `RPR__XXX` summary keywords.

Add method SummaryConfig::keywords( pattern )

---

src/opm/parser/eclipse/EclipseState/Schedule/Network/Node.cpp

So we can add a test in downstream..

fixed: implement Node::serializeObject

---

CMakeLists_files.cmake
opm/common/OpmLog/KeywordLocation.hpp
opm/common/OpmLog/LogUtil.hpp
opm/parser/eclipse/Deck/DeckKeyword.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Condition.hpp
opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/common/OpmLog/LogUtil.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/Deck/DeckKeyword.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Condition.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Parser/raw/RawKeyword.cpp
src/opm/parser/eclipse/Parser/raw/RawKeyword.hpp
tests/parser/ACTIONX.cpp
tests/test_OpmLog.cpp

A small step in the work of improving error messages

Keyword location

---

opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/DynamicStateTests.cpp

Small changes to support the atrocity `UDQ` in `ACTIONX`

Dynamicstate update equal

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

This feature replaces the current heavily `else if`-based dispatch method used in `Schedule::handleKeyword` with an `std::unordered_map<std::string, std::function>`-based lookup, as part of move towards a single, clear path through the handler for the purposes of error handling.

Schedule Keyword Handler Dispatch

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/msim/test_msim_ACTIONX.cpp
tests/msim/udq_in_actionx.include

The purpose of this PR is to allow for defintion of new UDQ entries inside a ACTIONX block.

Udq in actionx

---

opm/common/OpmLog/KeywordLocation.hpp
opm/parser/eclipse/EclipseState/Runspec.hpp
opm/parser/eclipse/Parser/ParserKeyword.hpp
opm/parser/eclipse/Parser/ParserRecord.hpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GPMaint.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Parser/ParserItem.cpp
src/opm/parser/eclipse/Parser/ParserKeyword.cpp
src/opm/parser/eclipse/Parser/ParserRecord.cpp
src/opm/parser/eclipse/Parser/raw/RawRecord.cpp
src/opm/parser/eclipse/Parser/raw/RawRecord.hpp
tests/parser/DeckTests.cpp
tests/parser/ParserTests.cpp

Small steps in preparations for error messages

Error prepare

---

src/opm/io/eclipse/ERsm.cpp

Debugging aid to understand RSM failure here: https://github.com/OPM/opm-simulators/pull/2788

Add error message when comparing summary and rsm files

---

opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/parser/eclipse/share/keywords/001_Eclipse300/S/SALINITY
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

I need something to set the constant salinity used by the CO2STOR model. 
See OPM/opm-material#427

Add keyword SALINITY with unit molality

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

This feature updates the code in `Schedule.cpp` and `KeywordHandlers.cpp` to be overall more consistent, mostly in terms of whitespace and braces, as well as other minor consistency fixes (such as normalising to `std::size_t`).

Various Code Consistency Changes in Schedule.

---

src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/Parser/ParseContext.cpp

Needed for OPM/opm-simulators#2807 as current master would throw an error.

Make transmissibility modifier tests run

---

opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
opm/parser/eclipse/EclipseState/Grid/TranCalculator.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/FieldPropsTests.cpp

These are small drive-by improvements & preparations for #1963

Tran calc init

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/RTEMP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/RTEMPA

Believe it is the way to solve #519 (based on comparison with a few other keywords), but I haven't spent time on figuring out how to build opm-common from source, nor if it propagates further into e.g. OPM Flow. Therefore not tested...

UNTESTED: Added size: 1 to RTEMP and RTEMPA

---

opm/common/utility/OpmInputError.hpp

Should have been removed with #1983

Remove leftover template<...>

---

src/opm/parser/eclipse/EclipseState/Aquancon.cpp
src/opm/parser/eclipse/EclipseState/AquiferCT.cpp
src/opm/parser/eclipse/EclipseState/Aquifetp.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
src/opm/parser/eclipse/EclipseState/Grid/FaultCollection.cpp
src/opm/parser/eclipse/EclipseState/Grid/TransMult.cpp
src/opm/parser/eclipse/EclipseState/TracerConfig.cpp

Various log and info messages emitted during the construction of EclipseState sub objects.

Create grid info

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp

Time keyword info logging

---

examples/msim.cpp
examples/opmi.cpp
opm/output/data/Aquifer.hpp
opm/output/eclipse/Summary.hpp
opm/parser/eclipse/EclipseState/AquiferCT.hpp
opm/parser/eclipse/EclipseState/AquiferConfig.hpp
opm/parser/eclipse/EclipseState/Aquifetp.hpp
opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
opm/parser/eclipse/Parser/ParseContext.hpp
python/cxx/eclipse_config.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/AquiferCT.cpp
src/opm/parser/eclipse/EclipseState/AquiferConfig.cpp
src/opm/parser/eclipse/EclipseState/Aquifetp.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/Parser/ParseContext.cpp
tests/msim/test_msim.cpp
tests/msim/test_msim_ACTIONX.cpp
tests/msim/test_msim_EXIT.cpp
tests/parser/SummaryConfigTests.cpp
tests/parser/integration/parse_write.cpp
tests/test_EclipseIO.cpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp
tests/test_restartwellinfo.cpp

adding aquifer summary keywords

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Add Group constructor based on RstGroup

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp

Fix struct/class warning.

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ConnectionTests.cpp

Replace expressions comparing size() to 0 with calls to empty().

Add Convenience Predicate WellConnections::empty

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Establish group <-> group relationship when loading from restartfile

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

With this PR the output from the Schedule construction will be like:
**Start**
```
Processing dynamic information from
/home/hove/work/OPM/opm-tests/norne/NORNE_ATW2013.DATA line 455
```
**Every change of input file**
```
Reading from: /home/hove/work/OPM/opm-tests/norne/INCLUDE/VFP/DevNew.VFP line 9
```
Normal `DATES`processing:
```
Starting report step 4/248 at 1997-11-14 8.0 days - line 204
Processing keyword WCONHIST at line 208
Processing keyword WCONINJE at line 212
Processing keyword GECON at line 216
Complete report step 4 (17.0 days) at 1997-12-01 / 25.0 days
Starting report step 5/248 at 1997-12-01 25.0 days - line 221
Processing keyword WCONHIST at line 225
Processing keyword WCONINJE at line 230
Complete report step 5 (16.0 days) at 1997-12-17 / 41.0 days
The remaining …
```

Schedule msg

---

tests/test_EclRegressionTest.cpp

The regression test program depends on this.

Ensure *HEAD Arrays Have Sufficient Size

---

opm/io/eclipse/rst/header.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/io/eclipse/rst/header.cpp
src/opm/io/eclipse/rst/state.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/test_AggregateWellData.cpp
tests/test_InteHEAD.cpp
tests/test_rst.cpp

Rst commits

---

src/opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.cpp

The code for parsing the dimensions string is not particularly robust or anything .... ;-)

Dimension string does not accept space

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Parser/raw/RawRecord.cpp
src/opm/parser/eclipse/Parser/raw/RawRecord.hpp
tests/parser/DeckTests.cpp
tests/parser/ParserTests.cpp
tests/parser/RawKeywordTests.cpp

Improved some error messages on the way

No wells message

---

src/opm/output/eclipse/Summary.cpp
tests/SPE1CASE1.DATA
tests/msim/test_msim.cpp

The counting of abondoned wells should handle both ShUT and STOP

Count of abondoned wells should handle both STOP and SHUT

---

CMakeLists_files.cmake
opm/common/OpmLog/InfoLogger.hpp
opm/common/OpmLog/KeywordLocation.hpp
src/opm/common/OpmLog/InfoLogger.cpp
src/opm/common/OpmLog/KeywordLocation.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/TracerConfig.cpp

This PR will limit the number of messages printed for when applying the MULTFLT and TRACER keywords.

Message limits for MULTFLT and Tracer

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunction.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunction.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunctionTable.cpp

Fix for: https://github.com/OPM/opm-common/issues/2027

Renamed UDQ functions: MIN -> UDQ_MIN and MAX -> UDQ_MAX

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQContext.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.cpp
tests/parser/UDQTests.cpp

These are small UDQ refactorings - to simplify future change in semantics.

Udq assign define

---

opm/io/eclipse/rst/header.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp

Flow did not restart in a day .... ;-)
I desperately need to get commits in the bank; will merge quite fast when this is green.

Use optional - and default to self - for reinj and voidage groups

---

opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

More small commits on restart + groups mission.

Rst group commits

---

tests/parser/EclipseGridTests.cpp

Remove not interesting test code

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp
tests/parser/UDQTests.cpp

`128 / 2 / 4 / 8 == 8`- right!

Ensure that division is left assosiative in UDQ parser

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.hpp
opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/UDQTests.cpp

Extracted the safe commits from #2044

Include udq summary commits

---

src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

WPIL is the productivity index of liquid (water + oil).

Don't Treat WPIL as Completion Keyword

---

src/opm/output/eclipse/Summary.cpp

Now ... the UDQ_M3 case should work.

Store extra summary parameters from UDQ and restart in common map

---

src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

Backport latest set of bug fixes for the summary feature to the 2020.10 OPM release.

Summary bugfixes

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp
tests/parser/UDQTests.cpp

Better (good??) handling of leading sign in UDQ expressions.

Udq leading sign

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp

Minor improvement in error message

Improve error message for failed udq

---

src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
tests/parser/GroupTests.cpp

Correctly handle blank string as default for item 10 in GCONPROD.

Blank string is default rate in GCONPROD

---

src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
src/opm/parser/eclipse/EclipseState/Grid/FaultCollection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.cpp
src/opm/parser/eclipse/EclipseState/TracerConfig.cpp

Looked through the output from running norne, and added newline where it seemed natural. One small step in making the output more helpful to users.

Added newline where natural.

---

test_util/EclRegressionTest.cpp

Remove extra printf

---

opm/output/eclipse/VectorItems/group.hpp
src/opm/output/eclipse/AggregateGroupData.cpp

While working with the code to *read* restart files I need to understand the code *writing* restart files better. This PR (and there will be more is mainly trivial changes to the code; moving things around a bit, giving names to some magic integers and so on. 
Personally I think it improves readability - but the main purpose is for myself to better understand the code; and then eventually be able to write the code to read the restart files properly.

Refactor main IGRP::staticContrib function

---

opm/output/eclipse/VectorItems/group.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleTypes.hpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleTypes.cpp

Reverts OPM/opm-common#2082
This was merged prematurely - sorry.

Revert "Igrp prod"

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp

Trivial commits extracted from: #2059

Summary completion commits

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Changes / refactoring to support GCONPROD in ACTIONX

Make section and keyword index optional in Schedule handlerContext

---

opm/parser/eclipse/EclipseState/Schedule/GasLiftOpt.hpp
src/opm/parser/eclipse/EclipseState/Schedule/GasLiftOpt.cpp
tests/parser/ScheduleTests.cpp

Add methods GasLiftOpt::has_well() and GasLiftOpt::has_group()

---

tests/parser/UDQTests.cpp

Hmmm - this seems to work on my machine

Udq minus bugx

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleTypes.hpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleTypes.cpp

Small utility function to return injection phase of well

Add method WellType::injection_phase()

---

src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WELL_PROBE
tests/parser/SummaryConfigTests.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

WGITL, WGIRL, WWITL, WWIRL, WGPTL, WGPRL, WLPTL, WOPTL, WOPRL, WWPTL and WWPRL

Summary completion

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

Support `GCONPROD` in `ACTIONX` block.

Actionx gconprod

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GLIFTOPT
tests/parser/ACTIONX.cpp

Actionx gliftopt

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

Allow use of `WELPI` keyword in `ACTIONX` blocks.

Actionx welpi

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQContext.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQContext.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.cpp
tests/msim/actionx1.include
tests/msim/test_msim_ACTIONX.cpp
tests/parser/UDQTests.cpp
tests/test_AggregateUDQData.cpp

The UDQ variables can be switched on and off with the `UPDATE` action:
``` 
UDQ
UPDATE FU_xx OFF /
/ 
```

Support UDQ UPDATE

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp

fixed: initializer list order

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ConnectionTests.cpp
tests/parser/WellTests.cpp

This PR will automatically SHUT a well with zero connections in the input layer. Lots of nicely formatted warnings all over the place

Automatically shut wells with no connections

---

msim/src/msim.cpp
opm/output/eclipse/Summary.hpp
src/opm/output/eclipse/Summary.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp

To simplify eval and upcoming work.
Downstream: https://github.com/OPM/opm-simulators/pull/2930

Store references to EclipseState and Schedule in Summary class

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.cpp
tests/parser/UDQTests.cpp

When combining scalar UDQ's and vector UDQ's the scalar will be expanded to a vector. With this PR the vector UDQ can be both lhs and rhs in an operation

Udq type cast

---

msim/src/msim.cpp
opm/output/eclipse/Inplace.hpp
opm/output/eclipse/Summary.hpp
src/opm/output/eclipse/Inplace.cpp
src/opm/output/eclipse/Summary.cpp
tests/test_Inplace.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp

Downstream: https://github.com/OPM/opm-simulators/pull/2937

Support summary keyword RHPV

---

opm/parser/eclipse/EclipseState/Schedule/Action/ASTNode.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/ActionAST.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.hpp
opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionAST.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
tests/parser/ACTIONX.cpp
tests/parser/TimeMapTest.cpp

Go through the ACTIONX expressions and determine which summary keys are required.

ACTIONX: Determine required summary keywords

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ConnectionTests.cpp

Pass wellname to `Connections::loadCOMPDAT()` in order to improve error message.

Improve error message for connection in inactive cell

---

opm/parser/eclipse/Deck/DeckItem.hpp
opm/parser/eclipse/Utility/Typetools.hpp

this broke ActionX in parallel

fixed: missing serialization for rsval in DeckItem

---

src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculator.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculatorCollection.cpp
tests/parser/PAvgTests.cpp

Fixup for: https://github.com/OPM/opm-simulators/pull/2957

Pavg fixup

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Use argument reportStep + 1 when evaulating WELPI in  ACTIONX

---

src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
tests/parser/EclipseGridTests.cpp

To support the test case SPIDER_CAKESLICE in the opm-tests, support for the DZ keyword was needed in the spiderweb implementation. This pull requests provides a general implementation so that arbitrary DZ values can be used.
Question: with this change cylindrical grids can be made where the Z size of the grid elements can be set arbitrary. Doing that, e.g. by making one element larger than all the others gives something that visually seems right as judged using resinsight. But does it make sense? Can flow handle this? If not, should we only support Z layers that are uniform? In that case, this may not be the most appropriate implementation.
Next question would be:should DR and DTHETAT also be supported? If so, it is not clear to me how that would be done using the existing code as a …

Allow use of both DZ and DZV when creating a spiderweb grid

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculator.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculator.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/PAvgTests.cpp

Start to support PORV based averaging in the WBP calculator.

Add PORV argument when creating PAvgCalculator
