OPM/opm-common

opm/io/eclipse/SummaryNode.hpp
src/opm/io/eclipse/SummaryNode.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

This feature adds `::Aquifer` to `Opm::EclIO::SummaryNode::Category` (and, by extension, to `Opm::SummaryConfigNode::Category`.
This PR requires the resolution of #1609.

Add Aquifer Category

---

tests/parser/EmbeddedPython.cpp

As pointed [here](https://github.com/OPM/opm-common/pull/1641#issuecomment-604460925) breaks a test when Python is not enabled. I'll pust this band aid fix now; a bit uncertain on The Right &trade; fix

Temporarily protect against deref when python is disabled

---

opm/io/eclipse/ESmry.hpp
opm/io/eclipse/SummaryNode.hpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/SummaryNode.cpp
tests/test_SummaryNode.cpp

This feature integrates `Opm::EclIO::SummaryNode` in `Opm::EclIO::ESmry`.
Adds the public interface `ESmry::get(const SummaryNode&)`, and `ESmry::summaryNodeList()`, which allow fetching vectors by a `SummaryNode` (from any source).

Integrate SummaryNode in ESmry

---

tests/parser/EmbeddedPython.cpp

Without this, clang thinks it is a declaration, not a function call. Not sure why gcc accepts it, maybe it was not checked?
See https://en.wikipedia.org/wiki/Most_vexing_parse for explanation.

Use braces to force correct parsing.

---

tests/test_RFT.cpp

sched uses python, so we have to reorder the members instead

fix faulty fix in 811d2e2a643e75feb8573f90f6246a47627eb7b8

---

opm/output/eclipse/WriteRestartHelpers.hpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/InteHEAD.cpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/output/eclipse/WriteInit.cpp
tests/test_AggregateActionxData.cpp
tests/test_AggregateUDQData.cpp
tests/test_AggregateWellData.cpp
tests/test_InteHEAD.cpp
tests/test_rst.cpp

This PR introduces a special case for the restart file writing code.  In particular we no longer write dynamic data vectors (e.g., `*WEL`, `*GRP`, `*CON`) to the restart file if we're being asked to output
the initial condition (i.e., report step/sequence number 0).
Add the report step as a new explicit parameter to `createInteHEAD()` instead of inferring this value from the "sim_step" and output dynamic sizes as zero for report_step=0.  While here, also correct an omission from earlier commit 7986e99 (PR #640).  We must ensure that the maximum number of wells in the field (`intehead[163]`) is at least as large as the current number of active wells (`intehead[16]`).
As a small carry-on piece of luggage, this PR also reduces the number of times we copy the Schedule object's complete wells. …

Don't Output Dynamic Data to Restart File for SEQNUM=0

---

cmake/Scripts/WriteVerSHA.cmake

The purpose of this is to be able to write:
```
Compiled time = 24-12-2020 at 19:10:10
```
in the startup message. The current PR just generates the symbol, actually using / inserting it must be done in opm-simulators.

Generate BUILD_TIMESTAMP macro with build system

---

opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
python/cxx/connection.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

Do not handle WellPI as a separate entity in the Connection class - just multiply with the transmissibility factor right away.

WPIMULT: directly multiply the connection transmissibility factor

---

cmake/Modules/UseVersion.cmake

OK - this is embarassing; after merging https://github.com/OPM/opm-common/pull/1653 and https://github.com/OPM/opm-simulators/pull/2506 things would not build locally at my machine.
This recovers the build; just how `Useversion.cmake` and `WriteVerSHA.cmake` interact is above my cmake pay grade; so kids - stay at home and play with Python - let real men fiddle with cmake.

Embed build timestamp also in UseVersion.cmake

---

CMakeLists_files.cmake
opm/io/eclipse/ESmry.hpp
opm/io/eclipse/SummaryNode.hpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/ESmry_write_rsm.cpp
src/opm/io/eclipse/ESmry_write_rsm_file.cpp
src/opm/io/eclipse/SummaryNode.cpp
src/opm/output/eclipse/EclipseIO.cpp
tests/SPE1CASE1.DATA
tests/msim/test_msim.cpp
tests/test_ESmry.cpp

This feature adds writing an RSM file from an `Opm::EclIO::ESmry` object, with the following interfaces:
1. `Opm::EclIO::ESmry::write_rsm(std::ostream& os) const`: Writes the summary to `os`
2. `std::ostream& ::operator<<(std::ostream& os, const ESmry& smry)`: Wraps `write_rsm()`
2. `ESmry::write_rsm_file() const`: Writes to a file with the same name as the runspec, in the same directory, with the extension `.RSM` (e.g. `ESmry("SPE1CASE1.SMSPEC").write_rsm_file() => SPE1CASE1.RSM`)

Write RSM File

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/RPTConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/RPTConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/test_ReportConfig.cpp

This feature adds the handling of `RPTSCHED` keywords in a time-sensitive (i.e. `DynamicState<T>`-based) manner. It expands the interface of `Opm::Schedule` as follows:
1. Adds `report_config(std::size_t timeStep)`: Gets the report configuration at `timeStep`.
It also adds `Opm::RPTConfig: public std::unordered_map<std::string,unsigned>`, a container for report settings, with the following interface (in addition to its normal `unsigned_map` interface):
1. `RPTConfig::RPTConfig(const DeckKeyword&)`: Creates a new config entry based on the passed keyword and its arguments.

Handle RPTSCHED keywords in a time-sensitive manner

---

src/opm/output/eclipse/Summary.cpp

This commit adds the aliases `WGIP` and `WWIP` for the existing summary vector names 'WGPI' (potential gas injection rate at well level), and 'WWPI' (potental water injection rate at well level), respectively.
Some [datasets](https://github.com/OPM/opm-tests/blob/e8a6cba3acf8ad4a0da821f02af6d4e73cda0ca8/model2/include/summary.inc#L147-L151) in 'opm-tests' use these alias names.

Summary: Recognise Aliases for Potential Phase Injection Rates

---

msim/src/msim.cpp
src/opm/output/eclipse/AggregateWellData.cpp
tests/SPE1CASE1.DATA
tests/msim/test_msim.cpp
tests/msim/test_msim_ACTIONX.cpp

As I understand it: The active control of a well is written to an element in the IWEL vector - this is an integer with an encoding like OilRate == 1 and RESVRate == 5; for a well which is closed the value 0 should be used.
In OPM the active control and the open/shut status of a well are encoded in different variables, so that we can get active_control == RESV for a shut well. This creates problems when going back and forth between Eclipse encoding and OPM variables.

Rst well shut

---

opm/parser/eclipse/Units/UnitSystem.hpp
src/opm/parser/eclipse/Units/UnitSystem.cpp

This feature
1. Resolves an issue where calling `UnitSystem::name()` would give the wrong unit name for field units for certain values.
2. Adds compile time checks to UnitSystem.cpp to guard against accidental silent string concatenation (the root cause of the issue in 1).

[FIX] Wrong unit names given for field units with certain values of UnitSystem::measure

---

src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp

This feature resolves a build issue caused by different standard library headers pulling in different other standard library headers on different compilers/platforms; in this case `<string>` was not pulled in on AppleClang from other headers.

[FIX] Resolves a build error on macOS/AppleClang 11.0.3

---

CMakeLists_files.cmake
opm/common/utility/TimeService.hpp
opm/io/eclipse/ERsm.hpp
src/opm/common/utility/TimeService.cpp
src/opm/io/eclipse/ERsm.cpp
src/opm/io/eclipse/ESmry_write_rsm.cpp
src/opm/io/eclipse/rst/header.cpp
test_util/EclRegressionTest.cpp
tests/msim/test_msim.cpp
tests/parser/DynamicStateTests.cpp
tests/parser/DynamicVectorTests.cpp
tests/parser/EventTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/TimeMapTest.cpp
tests/test_ERsm.cpp

This is on top of #1683. The new content is the last commit, where a test is added in the `compareECL`machinery. If a `CASE.RSM`file is found it is compared with the current summary data - this a comparison of the "same data" - just formatted in different ways. The comparison does therefor not take numerical precision and so on into account.

Rsm regression test

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp

This is to ensure that also the `rank != 0` processes have access to a Python object. There will be further changes - but this should be the API change.

Schedule: add std::shared_ptr<Python> arg to "default" constructor

---

src/opm/output/eclipse/EclipseIO.cpp

This is a fixup to #1672 and specifically [this comment.](https://github.com/OPM/opm-common/pull/1672#issuecomment-612478962)
The report should eventually end up in the PRT file; for the moment it should just go to `/dev/null` - which is implemented with this PR; `std::cout` output clobbering up the terminal was a mismerge of debug code. 
> I'm also not too impressed by the fact that we output this information—which is mostly unchanging—on every timestep rather than limited to report-steps only.
With this PR it is only created for every report step; but there is more in this direction. It is not yet clear (to me at least) how much information should be output when there is a change - specifically should the `WELSPECS` information for *all* wells be output when *one* well has changed? That …

Write report to stringstream and not stdout

---

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp

The sumIdir() and sumJdir() methods were called inside loop nests over i and j. Since the methods themselves were linear in nx and ny, respectively, this was a quadratic algorithm. Performance only becomes an issue for large (> 10k) values of NX or NY, which was thought not to ever happen. This assumption was wrong.
This can occur for example when the grid is "abused" by using NNCs (and no "normal" cartesian connections) to make the simulator run on an arbitrary unstructured grid.

Address performance issue for DX/DY/DZ/TOPS grids.

---

cmake/Modules/OpmCompilerChecks.cmake

when using clang, whether or not we should link to stdc++fs
cannot easily be detected. it depends on the c++ lib used
(libstdc++ vs libc++), as well as the versions of these.
to avoid messing up in general, this adds an option for forcing
linking to stdc++fs, even when using clang. it defaults to false
to not break existing build setups where it works. is required
for building on jenkins

changed: add option for using clang with libstdc++

---

src/opm/parser/eclipse/Parser/createDefaultKeywordList.cpp

We do not support boost in that version anymore and do not use its locales anyway.
Closes #1667

Revert hack for old boost versions (commit 59863939)

---

opm-common-prereqs.cmake
opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
python/setup.py
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp

The purpose of this PR is to calculate the volume for all the active cells in one go, the purpose of that again is to get an openmp based speedup for the volume calculations.
For this PR it is essential that all `ACTNUM` manipulations go through the `resetACTNUM` function. Facilitating that ended up in refactoring which got a little out of hand. This #1687 should be merged first. 
Update: the change here was simplified and #1687 is no longer required; I still think #1687 is an improvement though - and intend to merge it.
**OpenMP:** The core of this PR is to add a small function with an `omp` pragma. It seems to work - but I have to questions:
1. Should the use of OpenMP be protected by some build switch; and possibly some flags should be updated? Now I have just added the `omp`pragma and …

Cache cell volume

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
tests/parser/UDQTests.cpp

The purpose of this is to be able to assign numerical value to the UDQ in a PYACTION code.

Default construct UDQ keywords with value 0 when defined with UNIT

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/GroupTests.cpp

For groups we must flag whether they are available for group control separately for injection and production. This is requested by Equinor
Downstream: https://github.com/OPM/opm-simulators/pull/2541

Separate flags for available_for_group_control for injectors and producers

---

src/opm/parser/eclipse/share/keywords/001_Eclipse300/O/OPTIONS3
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

Need to be able to have the schedule section manipulation  code support the E300 keyword OPTIONS3. Maybe adding this file is sufficient?
```python
import json
from collections import OrderedDict
keyw =  OrderedDict()
keyw["name"] = "OPTIONS3"
keyw["sections"] = ["RUNSPEC", "SCHEDULE"]
keyw["size"] = 1
keyw["items"] = []
for a in range(288):
keyw["items"].append(OrderedDict(name="ITEM"+str(a+1), value_type="INT", default=0))
open('OPTIONS3.dirty', 'w').write(json.dumps(keyw))
```
```bash
jq . < OPTIONS3.dirty > OPTIONS3
```

Add json file for OPTIONS3, E300.

---

cmake/Templates/opm-project-config.cmake.in

Set flag for embedded Python in the opm-common-config.cmake file

---

opm/parser/eclipse/Deck/Deck.hpp

If not, no modifications are applied in parallel.

fixed: initialize iterators after deserialization

---

src/opm/parser/eclipse/Python/PyRunModule.hpp

to avoid warnings for the pybind11 members with hidden visibility

changed: explicitly set visibility on PyRunModule

---

src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp

This should be a fix for bug mentioned here: https://github.com/OPM/opm-common/pull/1703#issuecomment-617824398

Update connections should hanlde empty list

---

CMakeLists_files.cmake
examples/wellgraph.cpp

This program reads a deck and creates a graph from the group/well structure. It is stored as a file in the "dot" language used by GraphViz.
For example, running it on a case from `opm-tests/model4`:
```
wellgraph MOD4_GRP.DATA
```
will result in the output file `MOD4_GRP.gv` containing:
```
// This file was written by the 'wellgraph' utility from OPM.
// Find the source code at github.com/OPM.
// Convert output to PDF with 'dot -Tpdf MOD4_GRP.gv > MOD4_GRP.pdf'
strict digraph MOD4_GRP
{
FIELD -> { MOD4 }
MOD4 -> { UPPER LOWER AQF }
UPPER -> { MAIN SE }
LOWER -> { CENTRAL }
MAIN -> { NE NW }
node [shape=box]
AQF -> { WID1 WID2 }
NE -> { OPU4 WIU3 OPU5 }
NW -> { OPU1 OPU2 WIU1 OPU3 WIU2 }
SE -> { OPU6 WIU4 OPU7 }
CENTRAL -> { OPL1 OPL2 OPL3 WIL1 WIL2 OPL4 OPL5 }
OPL1 [color=red]
WID1 …
```

Add 'wellgraph' utility program.

---

examples/wellgraph.cpp

This way, the [dot(1)](https://en.wikipedia.org/wiki/Graphviz) program won't generate errors like
```
Badly delimited number 1_ splits into two tokens
```
when presented with a well name like '`INJE-1_N`'.

Wellgraph: Quote Names to Transparently Handle Dashes

---

cmake/Modules/UseOpenMP.cmake

This should allow downstream to automatically use the correct compile and linke flags for CMake > 3.9. For older versions we fall back to the old approach.
Closes #1751

Use OpenMP::OpenMP_CXX taget when linking libopmcommon

---

src/opm/output/eclipse/Summary.cpp
tests/SUMMARY_EFF_FAC.DATA
tests/test_Summary.cpp

As with all rate-like quantities, the `*EFAC` values affect the group tree level above the level where the factor is applied

Summary Output: Make Group Potentials Aware of Efficiency Factors

---

cmake/Modules/FindZOLTAN.cmake

Otherwise we experience compilation errors if OPM is configured with deactivated MPI and activated and found dune-alugrid (compile error that mpi.h is not found). This commit fixes this for me.

[CMake] Find Zoltan only if MPI is available.

---

opm/output/data/Groups.hpp

See: https://github.com/OPM/opm-common/issues/1756
Function actually seems to be unused?

Remove unused function from Group output data

---

cmake/Modules/OpmDefaults.cmake
opm-common-prereqs.cmake

to automatically trigger find_package(OpenMP) in downstream modules (e.g. Dumux).
Tested on my system with cornerpoint example in Dumux.
Hopefully closes #1751

Mark OpenMP as prerequisite for opm-common

---

opm/parser/eclipse/EclipseState/Schedule/Network/Branch.hpp

Compile fix for clang. Does not need to be backported, since #1746 was not. (Unless I misunderstood something serious).

Add missing include statement.

---

src/opm/io/eclipse/SummaryNode.cpp

Should fix: https://github.com/OPM/opm-simulators/issues/2581

Update regexp to allow for digits in UDQ name

---

opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Compsegs.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ConnectionTests.cpp
tests/parser/MultisegmentWellTests.cpp

Slight refactor of the segment information embedded in a connection object, instead of two doubles this PR uses:
```
std::optional<std::pair<double, double>> perf_range;
```
where the optional is empty for a normal well. Purpose is to simplify WELSPECS report for MSW well.

Connection - Segment interaction implemented with optional pair

---

src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp

The solvent model in Eclipse (annoyingly) enforce family 2 input for solvent models. I haven't found any reasons why. This will allow Flow to use family 1 input in kombinasjon with SOF2 for solvent models again. This used to work so I have many cases where SOF2 and family 1 is combined and don't want to convert all those to family 2.

Allow for mixing of SOF2 from familiy 2 and family 1 for 3p + solvent 

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

This was an omission from: #1746

Fix: integrate ExtNetwork instance in Schedule serialization

---

opm/output/eclipse/AggregateWellData.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/ActionResult.hpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionResult.cpp
tests/parser/ACTIONX.cpp

This is a preparatory step on the way to merge #1772.
This PR does not change logic in any way, but it does change the `ZWEL` vector in the restart files and a data update will be required. 
With this PR the action name is added to the `ZWEL` array exactly at the report step when it evaluates to true; previously it was added to `ZWEL` also in situations where the action did not evaluate to true. Consider the action:
```
ACTIONX
FALSE AND /
WUPR '*' = 1 /
/ 
```
In this case the result object will evaluate to `false`, but the internal list of wells will still contain the name of all wells where the second condition applies[1] - and in current master those wells will be added to `ZWEL`. For this PR that is changed and the action name is only added to `ZWEL` for exactly the timestep where …

Make sure the action name is only added to ZWEL when it is true

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SOLVDIRS

Parsing a DATA deck with 
```
SOLVDIRS
'-Y'  /
```
gives the error 
```
terminate called after throwing an instance of 'std::invalid_argument'
what():  
Failed to parse keyword: SOLVDIRS
In file /home/berland/xxxx.DATA, line 119
Error message: PARSE_EXTRA_DATA: The RawRecord for keyword "SOLVDIRS" in file"/home/bxxxxx.DATA" contained 2 too many items according to the spec. RawRecord was: PROPS
```
This is due to a missing `size` section in the corresponding  json, which is added in this PR.

Add size to SOLVDIRS json

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

This also exposed a bug: we do not handle lists of groups. Addressed by removing such list (replace with the single group matching pattern) in test case. The action expression involving the group list was never actually evaluated, since the start-time of the action was too high, making the action not `ready()` and therefore evaluate to false without evaluating any subexpressions.

Fix start-time of ACTIONX actions.

---

src/opm/io/eclipse/EclUtil.cpp

Compile fix for clang. Will self-merge when green, unless beat to it.

Add missing <array> include.

---

opm/output/eclipse/AggregateGroupData.hpp
opm/output/eclipse/VectorItems/group.hpp
opm/output/eclipse/VectorItems/well.hpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
tests/test_AggregateGroupData.cpp
tests/test_AggregateWellData.cpp

This commit identifies vector items in `XWEL` and `XGRP` that hold guide rate values at the well and group levels, and adds functionality to output those values to the restart file.  We do not identify such
value at the FIELD level.  As with other summary-like quantities, we expect to pick up the fully converted values from a `SummaryState` object.
Calculating and storing the guide rate quantities in `SummaryState` is the subject of future work.
Thanks to @jalvestad for invaluable assistance in identifying these vector items.

Restart: Prepare to Output Well/Group Guide Rates

---

tests/test_ActiveGridCells.cpp

With the double braces, I get
```
/home/bernd/Dumux/opm-common/tests/test_ActiveGridCells.cpp: In member function ‘void Default::testLocal::test_method()’:
/home/bernd/Dumux/opm-common/tests/test_ActiveGridCells.cpp:36:30: error: ‘[0] =’ used in a GNU-style designated initializer for class ‘std::array<long unsigned int, 3>’
36 |     inactive.insert({{1,1,0}});
|                              ^
```

avoid designated initializer error

---

cmake/Modules/OpmFind.cmake

When using CMAKE_DISABLE_FIND_PACKAGE_<name>=ON for a required package
CMake did not issue an errors since we never trigger the find_package
call. With this commit we now check whether such package is required
and send an error.

Send error for required but disabled packages.

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/MSW/SICD.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/SICD.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/MultisegmentWellTests.cpp

This PR is a preparation for implementing AICD support in opm-common. Turns out that AICD is a perfect superset of SICD  - the plan is therefor to have one `ICD` with some extra optional `AICD`settings. The very first step - which is this PR - is to rename the `SpiralICD` class to the more generic `ICD`.

Rename SpiralICD -> SICD

---

opm/common/utility/FileSystem.hpp

Clang defines `__GNUC__` to 4, as that represents its level of support for the GNU C dialect. The gcc compiler does not provide a macro indicating the compiler separately from the dialect supported. We must therefore use the `__clang__` macro to avoid false positives.

Ensure clang uses the normal standard headers.

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

the update call can invalidate the reference since the underlying
smart pointer is replaced, and when there are no remaining references,
it is deleted.

fixed: reorder logging and update call

---

cmake/Modules/UseVersion.cmake
cmake/Scripts/WriteVerSHA.cmake

to avoid rebuilds for things only needing project versions

changed: move build timestamp to separate header

---

src/opm/io/eclipse/ESmry.cpp

fixing invalid write in src/opm/io/eclipse/ESmry.cpp, Reported by @berndflemisch ,   [issue #1813](https://github.com/OPM/opm-common/issues/1813).

fixing invalid write in src/opm/io/eclipse/ESmry.cpp

---

src/opm/output/eclipse/Summary.cpp

SMSPEC: Emit Empty Unit String if UDQ Unit Undefined

---

opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Compsegs.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Compsegs.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

This work aims to enable restart of segment ICD's.
@jalvestad: You could try to give this a spin to investigate the problem with restarting models with valves.

Reshuffle segments and connections after restart

---

cmake/Modules/OpmLibMain.cmake

These can be really annoying if dependencies are not in system include directories. Let users disable them if they so please.

add a cmake flag to disable warnings

---

test_util/EclRegressionTest.cpp

When developing https://github.com/OPM/opm-common/pull/1695 it is found that the segment summary keywords are not compared for regression test.
It is a attempt to add some to see what will happen. 
Comments and suggestions are needed here.  @akva2

attempting to adding segment summary keywords for regression test

---

opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/icd.hpp
src/opm/io/eclipse/rst/segment.cpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/SICD.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/icd.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/icd_convert.hpp
tests/parser/MultisegmentWellTests.cpp

The `Segment`type can have exactly one ICD type attached - `std::variant<>` models this quite well.
@akva2 : Any hints on how to get this through the serialization?

Use std::variant<> to hold ICD alternatives

---

opm/output/data/Cells.hpp
src/opm/output/eclipse/RestartIO.cpp

This PR introduces a new tag, `RESTART_OPM_EXTENDED`, for cell-based quantities that don't have ECLIPSE-compatible names/contents.  The ResInsight post-processor will visualize such variables, but we must not output these variables to an ECLIPSE-compatible restart file.
At present `RESTART_OPM_EXTENDED` is recognized at the output layer (function `RestartIO::save()`) and behaves as an alias of `RESTART_AUXILIARY`.  My goal, however, is to deprecate the latter&mdash;tentatively in OPM 2020.04 with a `[[deprecated]]` annotation and to convert all current uses in the OPM codebase to either `RESTART_SOLUTION` or `RESTART_OPM_EXTENDED` as appropriate.  Then I would like to retire the `RESTART_ AUXILIARY` tag entirely&mdash;tentatively in OPM 2020.10&mdash;since the tag does not serve a …

New Solution Vector Tag for Restart File Output

---

opm/parser/eclipse/EclipseState/Runspec.hpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

It seems NUPCOL is only properly dealt with if in the SCHEDULE section, not RUNSPEC section.
Opening this PR with just the failing test now.

Handle NUPCOL in RUNSPEC correctly

---

opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.cpp
tests/parser/UDQTests.cpp
tests/test_Summary.cpp

This will ensure that an values will not escape from the UDQ evaluation.
@alfbr: I will continue with adding more tests, both here in opm-common and also in opm-tests - but the "UDQSet will check for nan values" commit should be the immediate fix to the problem we discussed on :phone:

UDQSet will check for nan values

---

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
opm/parser/eclipse/EclipseState/Grid/PinchMode.hpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
src/opm/parser/eclipse/EclipseState/Grid/PinchMode.cpp
tests/parser/EclipseGridTests.cpp

While we currently only support GAP and do not need this, we will need it eventually to support NOGAP in the simulator.

Support querying GAP/NOGAP mode for Pinch form EclipseGrid.

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp

If GCONSALE is used, we do https://github.com/OPM/opm-common/blob/master/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp#L1860
ie we pass class with an unitialized member. Inside updateInjection we do https://github.com/OPM/opm-common/blob/master/src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp#L129
this means the unitialized value ends up in the map. This led to indeterminism in data output causing havoc in https://github.com/OPM/opm-common/pull/1408

fixed: add missing initializer

---

CMakeLists_files.cmake
msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
opm/output/eclipse/AggregateActionxData.hpp
opm/output/eclipse/AggregateWellData.hpp
opm/output/eclipse/EclipseIO.hpp
opm/output/eclipse/RestartIO.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Actions.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/State.hpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Actions.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/State.cpp
tests/parser/ACTIONX.cpp
tests/test_AggregateActionxData.cpp
tests/test_AggregateWellData.cpp
tests/test_EclipseIO.cpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_restartwellinfo.cpp
tests/test_rst.cpp

The purpose of this PR is to add an object `Action::State`which keeps track of how many times an action has been run (i.e. succeeded), and the last time it was run. This was previously handled with a pair of mutable members in `ActionX` class - remember this kids: `mutable` as a way to implement functionality (beyond caching) **always** comes back to bite you.
The `Action::State`object is owned by the simulator. Main content of PR is adding `Action::State&`argument all over the place.
Downstream: https://github.com/OPM/opm-simulators/pull/2674

Add class Action::State to keep track of ACTIONX count

---

src/opm/output/eclipse/AggregateGroupData.cpp

This PR switches the group control debug output to `std::cout` into a conditional mode that is controlled by a file-wide PP symbol
```
ENABLE_GCNTL_DEBUG_OUTPUT
```
that we set to zero here.  This allows the developers to turn on additional debug output when needed without confusing those who are not actively working on the feature.

Group Data: Conditionally Enable Debug Output

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp
tests/parser/UDQTests.cpp

OK - this solves bug with a leading '-' in the UDQ parser, but exposes a new one with numerical literals in scientific form ....
On top of: #1848 which fixes the scientific literals

Udq sign bug

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp
tests/parser/UDQTests.cpp

The UDQ tokenizer splits on the '-' character - that creates rtouble when parsing numerical literals on scientific form: 1E-5
Fixed in this PR

Udq scientific

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp

Assign `stod` result to a `std::ignore` object to maintain the `token_size` side effect without creating an otherwise unused value of type `double`.  While here, also put the `next_token` helper into an anonymous namespace to avoid generating warnings of the form
```
no previous declaration for ...
```

UDQDefine: Suppress 'Unused Variable' Warning

---

msim/src/msim.cpp
opm/output/data/Groups.hpp
opm/output/eclipse/Summary.hpp
src/opm/output/eclipse/Summary.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp

This commit adds a level of indirection to the current per-group summary quantities that is directly assigned by the simulator.  In particular, introduce a new structure named
```
GroupData
```
that contains a `GroupConstraints` object and make the per-group values into `map<string, GroupData>` rather than the current `map<string, GroupConstraints>`.  This is in preparation of adding support for reporting group-level production/injection guiderates (`Gx[IP]GR`) to the summary file.
Update tests and APIs accordingly.
---
Note: Since this PR alters a client API, there is a companion PR (edit: PR OPM/opm-simulators#2696) in downstream module opm-simulators.  This PR **must not** be merged without also merging the companion PR lest there be a build break.

Make Structure for Per-Group Summary Data from Simulator

---

src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Parser/raw/RawKeyword.cpp
tests/parser/ParserTests.cpp

See: #1856 
We have `ParseContext` configuration of keywords which are too long - i.e. like `GUIDERATE` - where the default behavior is to warn about the too long keyword, but still continue parsing. Unfortunately this did not work for two reasons:
1. There was another check of keyword length before the one with `ParseContext` configurability - so the exception was thrown anyway.
2. The regular expression based matching for the `xxx_PROBE` keywords is too gready - and would in this case match. That problem is still there - but the two long check is performed before the regexp matching.

Fix handling of too long 8 characters keywords like GUIDERATE

---

CMakeLists_files.cmake
opm/output/data/GuideRateValue.hpp
tests/test_data_GuideRateValue.cpp

This commit introduces a container
```C++
Opm::data::GuideRateValue
```
that packages a `std::array` and `std::bitset` into that array. This container is intended as the main vehicle for transporting per-phase guiderate values (Oil, Gas, Water, and Resvoir Voidage Volume supported initially) calculated by the simulator to the output layer.  We support the serialization operations read and write in order to plug into the collective communications layer used in the simulator.
Add unit tests to exercise the new container.

Output: Add Container for Transporting Guiderate Values

---

opm/output/data/Groups.hpp
opm/output/data/Wells.hpp

This commit introduces datamembers of type
```C++
Opm::data::GuideRateValue
```
to the `Opm::data::Well` and `Opm::data::GroupData` structures. Collectively, these datamembers enable transporting guiderate values calculated elsewhere&mdash;e.g., in the opm-simulators module&mdash;to the output layer for final processing and output to the summary and/or the restart files.
We support outputting both production and injection guiderate values at the group level.  Guiderate values at the well level are interpreted as production or injection according to the well type.

Output: Transport Guiderate Values to Output Layer

---

cmake/Modules/Finddune-geometry.cmake
cmake/Modules/OpmPackage.cmake

Finding a module always succeeded even if the test program didn't even compile (might have been a feature).

Require test source code to compile and fix test for dune-geometry (>2.7)

---

src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp

These are (marginally) easier to understand than their raw integer values.  While here, also insert the missing 'GRUP' case for producers.

Restart Wells: Use IWEL WMCTL Values as Switch Cases

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.cpp

The small utility class UDQScalar reimplemented with `std::optional<double>` - this is also a small part of improved undefined handling in the UDQ code

Use std::optional<double> in UDQScalar

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQToken.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQToken.hpp
tests/parser/UDQTests.cpp

The UDQ syntax is .... weird; in particular the token `*` can be both a multiplier sign - and all wells/groups; i..e. this is a legit way to calculalte GOR:
```
UDQ
DEFINE WUGOR  WGPR '*' * 1 / WOPR '*' /
/
```
Previosuly to this PR the '*' might in some situations be mistaken for a multipler. 
Dwonstream: https://github.com/OPM/opm-simulators/pull/2733

Fix UDQ parsing for mix of '*' and *

---

msim/src/msim.cpp
src/opm/output/eclipse/Summary.cpp

The call to `udq::eval()` has up until now been included in the `Summary::eval()` - moved out to enable additional arguments to the `udq::eval()`function.
Dwonstream: https://github.com/OPM/opm-simulators/pull/2737

Remove call to udq::eval() from Summary::eval()

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
tests/parser/FieldPropsTests.cpp

It is possible to define your numerical region keywords as:
```
REGIONS
FIPXYZ
......  /
```
This PR adds support for them in the FieldProps system.

Allow FIPxxx keywords in FieldProps manager

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.hpp
tests/parser/UDQTests.cpp

The UDQ functionality has set union functions `UADD, UMUL, UMIN` and `UMAX` - these should be evaluated with the lowest presedence - i.e. below `+`. This PR fixes that.
```
UDQ
ASSIGN FU_PAR1 10.0 /
ASSIGN FU_PAR2 2.0 /
ASSIGN FU_PAR3 3.0 /
DEFINE FU_UADD FU_PAR1 UADD FU_PAR2 /
DEFINE FU_UMUL FU_PAR1 UMUL FU_PAR2 + FU_PAR3/
/
-- FU_UADD = 10 + 2 = 12
-- FU_UMUL = 10 * (2 + 3) = 50
```

Correctly parse and handle UADD / UMUL / UMIN / UMAX set operations

---

src/opm/output/eclipse/WriteInit.cpp

It happens when we tried to compile OPM on a cluster with Intel compilers. 
It failed in the compiling the related line due to 
identifier "n" is undefined. I believe it is related to the implementation of the compiler. 
It can be verified through the following sample code
``` c++
int main()
{
for (auto max_n=10, j = decltype(max_n){}; j < 10 * max_n; ++j) {
j += j;
}
}
```
There are much more to make the OPM can be compiled by Intel compilers, and we did not succeed in the end. 
But I think it might be good to use code compatible with more compilers.

rewriting a for loop for intel compilers

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Tuning.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/TuningTests.cpp

Internalize WSEGITER settings in Tuning implementation
**Background:** The maximum number of well iterations can be set both with the `TUNING` keyword and the `WSEGITER` keyword. opm has up until now *completely* ignored the `WSEGITER` keyword. With this PR the `Tuning` implementation has been updated to also load the items from `WSEGITER`. The maximum number of well iterations is stored in the `INTEHEAD` restart vector, several of our testcases contain a essentially ignored `WSEGITER` keyword, but with this PR the maximum number of well iterations is updated and we need a data update.

Add wsegiter

---

msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
opm/output/eclipse/EclipseIO.hpp
src/opm/output/eclipse/EclipseIO.cpp
tests/test_EclipseIO.cpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_restartwellinfo.cpp

To enable keeping track of defined / undefined UDQ values in the restart files.
Downstream: https://github.com/OPM/opm-simulators/pull/2748

Add UDQState argument to output writer

---

src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

This PR adds support for outputting the guiderate summary vectors
```
[GW][OGWV]PGR, [GW][GW]IGR
```
under the assumption that the values are fully calculated at another level and that we therefore only need to extract the numerical values and convert the rate units to output conventions.  We assume that such values are communicated to the summary output layer by means of a `GuideRateValue` object.
The assumption of values already being calculated leads to a small change in the `need_wells()` function.  We're now able to exclude guiderate values at the group level from those vectors that require setting up a well vector.  This is a (tiny) performance improvement.

Add Guiderate Summary Output

---

tests/test_ArrayDimChecker.cpp

My bad, forgot this include when quelling the warning the other day..

fixed: add missing include for boost version

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp

The `FieldProps` machinery for 3D fields throws away all the inactive cells; now it turns out we might need the inactive cells in some cases after all ....
This PR just reorganizes the metadata for 3D fields, so that it will be simpler to add support for a global field at a later stage.

Reorganize field properties metadata

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp

A usage of designated initializers had sneaked in

Remove use of designated initializer

---

opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/FieldPropsTests.cpp

The `FieldProps::get_global<T>()` function will create a vector with `nx*ny*nz` elements and fill in a default value for the inactive cells. Previously the function would *always* use the fill value 0; now it will use the field specific default value - e.g. 1.0 for `MULT?`, if no default is specified for a keyword the value 0 is used.

Fieldprops: Correct default

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp

Note that there is still a member function of the same name.
The function causes compile errors for me, I guess gcc is more lenient in its parsing of un-instantiated templates than clang is.

The distribute_toplayer() is unused.

---

src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQContext.cpp
tests/parser/UDQTests.cpp

Extracted the change which induces data update from: #1911

Add TIMESTEP as context variable in summary eval

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQContext.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQContext.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.cpp
tests/parser/UDQTests.cpp
tests/test_AggregateUDQData.cpp

Commit message from second commit:
**Differentiate better between UDQ ASSIGN and UDQ DEFINE**
A quite typical situation is that a UDQ keyword is first initialized with UDQ
ASSIGN statement, and then subsequently a formula for updates every timestep is
entered with UDQ DEFINE:
```
UDQ
ASSIGN FU_VAR1 0 /
DEFINE FU_VAR1 FU_VAR1 + 1 /
/
```
Then the assign statement should be run once, and the define formula should be
evaluated for every subsequent timestep.

Udq assign

---

opm/io/eclipse/SummaryNode.hpp
opm/output/eclipse/RegionCache.hpp
opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/output/eclipse/RegionCache.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp
tests/test_SummaryNode.cpp
tests/test_regionCache.cpp

The region summary keywords can optionally take a region name as in `RPR__XYZ` to report pressure in the `XYZ` numerical region - which has been defined with `FIPXYZ`. This PR is the start of such support. 
The current needs some love and care git wise - but otherwise it is starting to get ready to be merged.
The current code does not actually add any new keywords, but it builds part of  the infrastructure for `RPR__XYZ` keywords

Add basic support for xxx_REG summary keywords

---

opm/parser/eclipse/Units/UnitSystem.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellBrineProperties.cpp
src/opm/parser/eclipse/Units/UnitSystem.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSALT

The salt concentration has unit density, not identity.

Fix unit for salt concentration in WSALT

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp
tests/test_GuideRate.cpp

This PR centralises the way we incorporate damping factors (item 10 of the `GUIDERAT` keyword) into the calculation of group/well guide rates.  In particular, we create a structure that manages both the current and the previous (damped) guiderate values and ensures that the new guiderate value is
```
GR_p = f*GR_p' + (1 - f)*GR_p^{n-1}
```
with `GR_p'` denoting the "raw" guiderate value calculated directly from potential rates at the current timelevel (n).  `GR_p^{n-1}` is the damped-and previously used-guiderate value from timelevel n-1. Finally `f` denotes the damping factor.  This is the same approach used previously, but with some small changes to exclude zero-valued guiderates.
We furthermore remove one of the early returns in `GuideRate::get()`. There is no need to return the …

Refactor Damping Factor Implementation

---

opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.hpp
src/opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.cpp

The ALQ values where not scaled in the VFP table. For ALQ_GRAT scaling on the gas_rate seems natural. But what to do for COMP, DUMP and BEAN??? Does anybody know what they represent?

scaling of the Alq values

---

opm/parser/eclipse/EclipseState/Runspec.hpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp

also add it to comparison operator. thanks to @totto82 for noticing (https://github.com/OPM/opm-common/pull/1923)

fixed: serialization nupcol in Runspec

---

src/opm/output/eclipse/Summary.cpp

Make sure the "TIMESTEP" variable is available in `SUmmaryState`- even if it has not been requsted in summary output.

Unconditionally add "TIMESTEP" to SummaryState

---

opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp
src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
tests/parser/FieldPropsTests.cpp

This PR introduces a new helper structure, `RawFunctionValues`, which collects unscaled saturation function values that are needed for vertical scaling of saturation functions using keywords such as
```
KRO, KRORG, KRGR, PCW
```
and their hysteretic and directional counterparts.  We also introduce a new helper function, `getRawFunctionValues`, which extracts those values from the function tables in `TableManager`.
Add a set of unit tests to exercise the new feature.

Saturation Functions: Add Means of Retrieving Select Function Values

---

CMakeLists.txt
debian/control
opm-common-prereqs.cmake
redhat/opm-common.spec

In C++20 the library `fmt`which replaces `printf()` and `<<` based formatting - looks very good. 
Before C++20 we can use the external library: https://github.com/fmtlib/fmt/ - which is essentially what was included for C++20. 
For the ongoing work with improvements in error messages this would be extremely valuable, I therefor suggest that we use `fmtlib` until we switch to C++20. 
This PR assumes that fmtlib is installed on your system (it is available as binary package on RH, Ubuntu & Debian) and integrates that in the build system - the cmake integration is quite naive and probably needs some love and attention from someone in the know.

Add build dependency on fmtlib

---

src/opm/output/eclipse/EclipseIO.cpp

If the last report step happens to be split into multiple substeps (e.g., convergence problems or TUNING settings &c), then we will write the RSM file for each substep which will slow down the process.  This commit explicitly ensures that we don't output the RSM file unless it is the last substep of the final report step.

Don't Write RSM File for Substeps

---

debian/control
redhat/opm-common.spec

- missing comma in debian control
- wrong name for redhat

fix packaging files for libfmt

---

CMakeLists.txt
debian/control
examples/opmhash.cpp
external/fmtlib/LICENSE.rst
external/fmtlib/README.opm
external/fmtlib/include/fmt/chrono.h
external/fmtlib/include/fmt/color.h
external/fmtlib/include/fmt/compile.h
external/fmtlib/include/fmt/core.h
external/fmtlib/include/fmt/format-inl.h
external/fmtlib/include/fmt/format.h
external/fmtlib/include/fmt/locale.h
external/fmtlib/include/fmt/os.h
external/fmtlib/include/fmt/ostream.h
external/fmtlib/include/fmt/posix.h
external/fmtlib/include/fmt/printf.h
external/fmtlib/include/fmt/ranges.h
redhat/opm-common.spec

The attempt at using binary packages for fmtlib was not very successfull - it turned out that the header only mode was broken for Debian and Ubuntu 18.04 packages. In this PR we have reverted the changes based on using an external fmtlib package and instead embedded the fmtlib header files in opm-common.
Have also added one commit which actually uses the `fmt::format()` function instead of `ioamanip`

Embed fmtlib

---

msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
opm/output/data/Groups.hpp
opm/output/eclipse/RestartValue.hpp
opm/output/eclipse/Summary.hpp
opm/parser/eclipse/EclipseState/Schedule/Network/ExtNetwork.hpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/output/eclipse/RestartValue.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Network/ExtNetwork.cpp
tests/parser/NetworkTests.cpp
tests/test_EclipseIO.cpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp
tests/test_restartwellinfo.cpp

This commit adds a level of indirection to the existing group-level data (active controls and guiderates), and adds a new `NodeData` level to the `data::` protocol for transporting values from the simulator to the output layer.
Update all call sites and users accordingly.
While here, also add a way of retrieving all network nodenames in anticipation of handling node-level summary output requests like
```
GPR
/
```
in the `SummaryConfig` class.
Note: This is an API break and is accompanied by a follow-up PR in the opm-simulators module.  This PR cannot be merged unless the two are merged in concert.

Prepare for Outputting Network Node Pressure to Summary File

---

opm-common-prereqs.cmake

Otherwise the user still needs to have an installed version on the system in addition.
I thought the aim of embedding was to save users from installing it, but ithout this I got:
```
CMake Error at cmake/Modules/OpmFind.cmake:135 (find_package):
By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "fmt", but
CMake did not find one.
Could not find a package configuration file provided by "fmt" with any of
the following names:
fmtConfig.cmake
fmt-config.cmake
Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
to a directory containing one of the above files.  If "fmt" provides a
separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first): …
```

Also remove fmtlib from opm-common-prereqs.cmake

---

opm/io/eclipse/SummaryNode.hpp
opm/parser/eclipse/Parser/ParseContext.hpp
src/opm/io/eclipse/SummaryNode.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/Parser/ParseContext.cpp
tests/parser/SummaryConfigTests.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

This PR adds an evaluation function for the `GPR` summary vector.  We assume that the actual value is calculated elsewhere and passed in unchanged from the caller of `Summary::eval()`.  We therefore need only convert the value to output units and hook this procedure up to the table of known output functions.
As a prerequisite we add a new `Node` category to the `SummaryConfigNode` and a processor for this category which knows about the distinction between nodes and groups.  It uses member function `ExtNetwork::node_names()` to produce configuration nodes whose named entity is the node rather than a group.  Deriving this list of node names across all timesteps is potentially expensive, so perform this operation at most once and pass the result into the processor from the `SummaryConfig` …

Add Support for 'GPR' (Network Node Pressure) Summary Keyword 

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Grid/FieldData.hpp
opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
opm/parser/eclipse/EclipseState/Grid/Keywords.hpp
opm/parser/eclipse/EclipseState/Grid/TranCalculator.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/FieldPropsTests.cpp

Previously modifications were applied directly to the field properties. Unfortunately, for unset TRANX this resulted in modifying 1.0 even if the simulator is calculating transmissibilities itself. This was one of the reasons why we got wrong results (others are in the simulator code).
Now these operations recorded in a calculator which can later be applied to compressed arrays using apply_tran.
Based upon #1919. I needed to reorganize quite some stuff to support parallel in opm-simulators. Among other things, FieldData is now accessible from there (previously that was a nested class of FieldProps).
There will come a downstream PR in opm-simulators once my code is cleaned up and test.

Adds a calculator for modifying transmissibilities.

---

opm/parser/eclipse/Deck/DeckOutput.hpp
src/opm/parser/eclipse/Deck/DeckOutput.cpp

Fix for: https://github.com/OPM/opm-common/issues/1948

Special case output of UDQ and ACTIONX keywords - no split

---

opm/parser/eclipse/EclipseState/Runspec.hpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/share/keywords/900_OPM/C/CO2STOR
src/opm/parser/eclipse/share/keywords/keyword_list.cmake
tests/parser/RunspecTests.cpp

The flag is used to trigger a CO2-BRINE specific PVT model.

Add CO2STOR keyword in Runspec section

---

opm/parser/eclipse/EclipseState/Tables/PvtoTable.hpp
opm/parser/eclipse/EclipseState/Tables/PvtxTable.hpp
opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/parser/eclipse/EclipseState/Tables/Tables.cpp

This PR relaxes the requirement that the saturated formation volume factor for oil ("Bo") be strictly increasing as a function of the dissolved gas/oil ratio ("Rs").  In a way, we partially revert commit dbf2a4c425af69804f552bab836ca1a3e838a2bd (PR #342).  We have seen cases for which the strictly increasing criterion fails to hold but which nevertheless run, at least if the monotonicity requirement only breaks for very high values of Rs.
We therefore introduce a special purpose system for detecting and reporting this situation.  In this case, output such as
```
Warning: Non-Monotonic Oil Formation Volume Factor Detected
* PVTO [PVTNUM = 1]
Record  9: FVF 1.23 at RS 123 is not greater than FVF 2.34 at RS 120
Record 10: FVF 1.22 at RS 125 is not greater than FVF 1.23 at RS 123
Record 11: …
```

Support Non-Monotonic Saturated Oil FVF in PVTO

---

src/opm/output/eclipse/Summary.cpp

The injection rate for completions was capped at zero - but to support xflow we need to allow negative IR.

Cir negative

---

src/opm/output/eclipse/Summary.cpp

This feature resolves a minor issue were a range variable was accidentally left as a copy, rather than a reference.

Range Variable Correction

---

opm/common/utility/OpmInputError.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/Parser/Parser.cpp

Wrap construction of all the "big four" in `try catch` blocks.
Messages should be refined - but this should be enough to guarantee that all errors have been logged before leaving opm-common.
OK guys: This was new syntax to ya?!

Throw opm error

---

src/opm/parser/eclipse/Units/UnitSystem.cpp

This commit adds a minimum amount of compile-time size checking for the various arrays that go into defining the conversion factors and unit strings.  Using `static_assert()` we guarantee that the arrays at least have the expected size lest the translation unit fail to compile.

Unit Conversion Tables: Add Size Consistency Checking

---

opm/parser/eclipse/EclipseState/Grid/TranCalculator.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/FieldPropsTests.cpp

This PR will condense TRAN operations like
```
MULTIPLY
TRANX 0.50 1 10 1 10 1 1 /
TRANX 1.25 1  10 1 10 2 2 /
...
/
```
to one tran calculator operation per keyword and TRAN direction. This should significantly reduce the memory consumption for this usage pattern. See the post merge disussion here: #1932 
The possible TRAN manipulations in the EDIT section are quote limited:
1. Direct assignment with e.g. `TRANX`
2. Keywords `EQUAL`, `MULTIPLY`, `ADD`, `MINVALUE` and `MAXVALUE`.
The other manipulation keywords like e.g. `OPERATE` and `EQUALREG` are not supported and will give rise to an exception. These other keywords have never really worked, but previously the failure has been silent. To support `TRAN` modifications for these additional keywords is certainly possible - in some cases …

Tran calc condense

---

CMakeLists_files.cmake
opm/common/utility/OpmInputError.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/Parser/Parser.cpp
tests/parser/ParseContextTests.cpp
tests/test_OpmInputError_format.cpp

This feature adds a `try-catch` block in `Opm::Schedule::handleNormalKeyword()` which logs any non-`Opm::OpmInputError` exceptions to the error log with as detailed location information as possible, before rethrowing them.
Additionally, it adds some flexibility to format interpolation when initialising `OpmInputError`, and adds a convenience initialiser for rethrowing with a nested exception.

Exception Catch and Release

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/RockConfig.hpp
opm/parser/eclipse/EclipseState/Tables/TableManager.hpp

It warns whenever uninitialized data is sent. Please check whether the selected defaults are sound.

Fix some warnings when running with valgrinds MPI wrapper.

---

CMakeLists_files.cmake
GenerateKeywords.cmake
opm/common/utility/OpmInputError.hpp
src/opm/common/utility/OpmInputError.cpp
src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
tests/parser/ParseContextTests.cpp
tests/test_OpmInputError_format.cpp

As pointed out [here](https://github.com/OPM/opm-simulators/pull/2817#issuecomment-701427161) the fmtlib dependency had entered into the API of opm-common - not OK.
With this PR the `include <fmt/format.h>`is moved away from the `OPmInputError.hpp` header file - slightly unfortunate because the variadic template trickery which is now removed was quite elegant. But we can live with that.

Mkae sure fmtlib is not a dependency in the public api

---

src/opm/output/eclipse/Summary.cpp

The list of "schedule" wells is empty in at least one case&mdash;when we're configuring the SMSPEC nodes.  Don't blindly assume that there is always a non-empty sequence of wells.

ALQ Rate: Don't Index Into Empty Vector

---

src/opm/parser/eclipse/EclipseState/Schedule/ArrayDimChecker.cpp

A wrong value was used in the ArrayDimChecker error message. Fix bug which sneaked in here: #1946

Fix bug in ArradDimChecker message

---

src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

The message is actually wrong. If we are to emit a message at all, it needs to be a warning when RUNSUM is set but SEPARATE is not set. Personally, I believe the RSM format is so rarely used that we need not cater to any messages.

Remove confusing message

---

opm/output/data/Wells.hpp
src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/output/eclipse/Summary.cpp
tests/test_AggregateConnectionData.cpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp
tests/test_Wells.cpp

This PR switches to getting the output files' connection transmissibility factor from `Opm::data::Connection` instead of
`Opm::Connection`.  This is in preparation for implementing the WELPI feature, in which the CTFs are occasionally adjusted based on the dynamic simulation state.

Summary/Restart: Get CTF From Simulator 

---

opm/parser/eclipse/Parser/ParseContext.hpp
opm/parser/eclipse/Parser/ParserKeyword.hpp
src/opm/parser/eclipse/Parser/ParseContext.cpp
src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Parser/ParserKeyword.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/RTEMPVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/T/TEMPVD
src/opm/parser/eclipse/share/keywords/001_Eclipse300/T/TEMPVD
tests/parser/ParseContextTests.cpp

This feature adds support in `/src/opm/parser/eclipse/share/keywords/**` for two new root level items in keyword definitions:
This entry is a list of strings, which are the names of other keywords that are required to be present at a point before the keyword is read, such as in `AQUCT`:
```json
{
"name": "AQUCT",
"sections": [
"GRID",
"PROPS",
"SOLUTION",
"SCHEDULE"
],
"//": "New entry.",
"requires": [
"AQUDIMS"
],
"items": [
{ . . . }
]
}
```
If all of the required keywords are not present at the time at which this keyword is reached, an exception is thrown.
This entry is a list of strings, which are the names of other keywords that may not be present in the file when this keyword is reached, such as in `RTEMPVD`:
```json
{
"name": "RTEMPVD",
"sections": [
"PROPS",
"SOLUTION"
],
"//": …
```

Required and Prohibited Keywords

---

opm/parser/eclipse/EclipseState/Schedule/Events.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ConnectionTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

This PR adds logic implementing the static parts of the WELPI keyword.  We internalize the keyword data, record appropriate events and provide hooks for dynamically adjusting the per-connection transmissibility factor (`Connection::CF()`) when those events occur.
We implement support at ~~three~~ four levels
* **Connection**:
Add new public member functions `prepareWellPIScaling` and `applyWellPIScaling` which, respectively, creates bookkeeping data to track if the connection is subject to CF scaling and actually applies that CF scaling.
* **WellConnections**:
Add new public member functions `prepareWellPIScaling` and `applyWellPIScaling` which, respectively, creates bookkeeping data to track those connections which are subject to CF scaling and actually applies that CF scaling.
* …

Add Support Infrastructure for WELPI Feature 

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DX
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DXV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DY
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DYV
src/opm/parser/eclipse/share/keywords/000_Eclipse100/T/TRACERKM

This PR is mainly to draw the attention towards the new functionality provided here: #1996
It is now possible in json to specify keyword dependencies via `"requires" : [... ]` and mutually exclusive keywords with `"prohibits": [..]`

Keyword interaction

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp

The dates keywords are parsed in the `Schedule`initializer list - they did not get the full error handling fairy dust; now they do.
```bash
Error: Problem with keyword DATES
In /home/hove/work/OPM/opm-tests/udq_actionx/include/schedule_dates line 68.
Internal error: map::at
```

Schedule error msg

---

opm/io/eclipse/rst/state.hpp
src/opm/io/eclipse/rst/state.cpp
test_util/EclRegressionTest.cpp
tests/test_EclRegressionTest.cpp

The purpose of this PR is to enable more context rich comparisons in the regression testing; instead of
```
Keyword: IWEL, origin Restart, sequence 51
Value index                 = 3026
(first value, second value) = (1, 0)
Non floating point values not identical 
```
you can now get something like:
```
Different active_control for well: OPL1  reference: -1  simulation: 4
```
This is only a first step - just what I need right now - if it is deemed valuable it can be improved & extended. The current code is *in addition* to the existing code and will not (yet) influence the pass/fail status of a test.

Use restart object in regression testing

---

opm/parser/eclipse/EclipseState/Schedule/Events.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
tests/parser/ScheduleTests.cpp

This is different from `COMPLETION_CHANGE` which is unconditionally recorded when processing `COMPDAT`.  This event is recorded only when the `Well`'s internal `WellConnections` structure actually changes and informs clients that they may need to rerun any dynamic `WELPI` scaling.  Such scaling will not be automatically forwarded onto the
new `WellConnections` structure.
This is arguably a hack.

Record Event if WellConnections Change

---

opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
python/cxx/summary_state.cpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
tests/test_Summary.cpp

To be used by UDQ evaluation. Check if we have a particular summary variable for wells / groups - for *any* well/group.

Add SummaryState functions has_well_var() and has_group_var()

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQContext.cpp
tests/parser/UDQTests.cpp

When asking for a well result like like `WWCT:OP1` - differentiate between invalid variable like `WWXT` which gives an exception and invalid well which gives an empty `std::optional<double>`.

Udq allow missing well

---

src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp

The shadowing is a little unusual, it is the member of the Well class containing the WellProductionProperties class that is shadowed.

Silence shadowing warnings.

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleTypes.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

This PR switches the wells' notion of "preferred" phase to coincide with the injected phase for injector wells&mdash;at least for those wells whose injected phase is specified in `WCONINJE` or `WCONINJH`.  We need this ability in order to correctly interpret productivity index values specified in the `WELPI` keyword and to calculate the corresponding dynamic value as part of rescaling the transmissibility values.  This ability is particularly important when an injection well switches from injecting water to injecting gas or the other way around due to the mobility differences.  Producing wells's preferred phase remain as the phase declared in `WELSPECS`.
While here, also extend the `Well`'s representation of a `WELPI` record from an `optional<double>` into an `optional<struct>` with the …

Use Injected Phase as Preferred Phase for Injectors

---

opm/parser/eclipse/EclipseState/Schedule/Events.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ConnectionTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

This PR adds a new member function
```C++
Schedule::applyWellProdIndexScaling(well_name, report_step, scalingFactor)
```
which applies WELPI-based CTF scaling (by `scalingFactor`) for all pertinent report steps from `report_step` and until the end of the simulation run.  We take care to apply the relevant scaling exactly once, and in order to guarantee this we use ~~`OrderedMap::unique()`~~ `DynamicState<>::unique()` and also add a special-purpose predicate
```C++
Well::hasSameConnectionsPointers(const Well& other)
```
which returns true if and only if the internal `WellConnections` pointers of `*this` and `other` are the same&mdash;meaning `*this` and `other` share the exact same `WellConnections` object.
We also add a communications channel which determines the connections' WELPI-based …

Apply WELPI CTF Scaling at Schedule Level

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/WellTests.cpp

1. The well reference depth should *not* be updated when new connections are
added with COMPDAT.
2. The well reference depth should be recalculated when the well is updated with
the WELSPECS keyword.

Changes to well reference depth

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp

"No it doesn't work - but we have got the best error messages!"
Adding a `KeywordLocation` member to the `UDQDefine` structure to provide better error messages.

Udqdefine location

---

src/opm/output/eclipse/Summary.cpp
tests/msim/test_msim_ACTIONX.cpp
tests/msim/udq_in_actionx.include

Will scan the UDQ expressions and assert that all required summary keys are evaluated; although they are not requested in the summary output.
This PR "requires" a data update in the the DUDW restart vector; that was not the intention and it should certainly be verified externally. The DUDW vector in the restart file manages which wells are UDQ active, and with this PR two new wells are marked as active, that was not the topic of the PR at all - but I think it is an accidental fix. My summary of what happens is:
**master**
```
SUMMARY
WGLIR
P1 P2 P2 /
....
UDQ
DEFINE WUGASRA 75000 - WGLIR '*' /
```
The `WGLIR` keyword is only defined for the producers `P1, P2` and `P3`, when expanding the `*` in the `DEFINE WUGASRA 75000 - WGLIR '*' /`expression it is expanded to these three wells, and …

Include udq summary

---

src/opm/output/eclipse/Summary.cpp

Th `glir` function used to evaluate `WGLIR, GGLIR and `FGLIR` did not properly sum over wells. Now it does.

Summary function glir should sum over all argument wells

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp

Small preparations to facilitate restart; bith the active group control and the group control requested in the deck should be in the restart file.

Rename group production control mode variable

---

opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
tests/parser/TimeMapTest.cpp

When restarting we search for the correct time-point to start simulating, previously we had to have a DATES keyword right on the restart date. With this PR it is possible to get there with TSTEP as well.
@alfbr: Will you try this on your restart case?

Allow restart date to be at a TSTEP

---

cmake/Modules/FindParMETIS.cmake

The parmetis.h distributed via the parmetis binding of scotch with Ubuntu 18.04 (libscotchparmetis-dev) includes the header
scotch.h located in /usr/include/scotch/. Therefore our check of the include file failed. With this commit we check the parmetis.h header another time with the scotch include path added. Now parmetis is found on my Ubuntu.
This is a bugfix and should be included into the release.
@totto82 @atgeirr Please check whether this solves your problem.

[cmake] Use scotch include dir for parmetis bindings of scotch.

---

src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

If one of the keywords in one of the lists like `ALL` is not supported the error message is
```
Warning: Unhandled summary keyword ALL/WPI
In /home/hove/work/OPM/opm-tests/wecon_wtest/3D_WECON.DATA line 179
```

Improve error message for unhandled meta summary keyword

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/ScheduleTests.cpp

Utilities in order to support completion summary keywords like: `WOPRL`

Add function bool Well::hasCompletion( int )

---

src/opm/output/eclipse/AggregateMSWData.cpp
tests/test_AggregateMSWData.cpp

The current code that aggregates flow rates from connection to segment levels assumes that the simulator generates connection results for the open connections only.  Relax this restriction as upcoming work in the context of WELPI will require generating at least the CTFs even for shut connections.

MSW: Support Connection Results for All Connections

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

This PR switches the WELPI scaling factor protocol to requiring that the caller convert the effective PI value to output units before calling
```
Well::getWellPIScalingFactor()
```
This clearly makes the function less convenient to use, but is on the other hand the only way to guarantee that client code has a consistent view of the "preferred" phase for injectors.  PR #2018's approach of capturing the preferred phase at the time of processing `WELPI` was, while well-intentioned, based on a misunderstanding of the way these keywords interact.  Moreover, my [answer](https://github.com/OPM/opm-common/pull/2018#issuecomment-707997529) to @joakim-hove's [question](https://github.com/OPM/opm-common/pull/2018#issuecomment-707991480) in turn was based on an incomplete understanding of what goes …

Defer Unit Conversion for WELPI Values

---

opm/io/eclipse/SummaryNode.hpp
opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

~~Some summary keywords can have optional qualifying data following the keyword
name, like RPR__REG for region pressure based on FIP region FIPREG and WOPRL__2
for oil production rate from completion 2.~~
My `std::variant`based solution was a bit over engineering .... simplified significantly ...

Use general datatype for extra data in summary keywords

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ScheduleTests.cpp

Get set of connections from one connection in the same completion - support COPRL and cousins.

Get connections from global index

---

CMakeLists.txt

cmake does not properly interpret the SYSTEM marker in lists of
include directories. this causes issues downstream when using
dunecontrol / the in-tree cmake config files.
Closes #2091

workaround cmake issue

---

opm/parser/eclipse/EclipseState/Schedule/MSW/SpiralICD.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/Valve.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionValue.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
src/opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.cpp

The missing includes lead to compiler errors on Ubuntu 20.10.
Note that this only concerns the 2020.04 release branch, more recent branches are fine.

add missing includes of standard library headers

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
tests/parser/GroupTests.cpp

To replace numerous `group.name() == "FIELD"` checks.

Add method Group::is_field()

---

src/opm/output/eclipse/Summary.cpp

The `schedule_wells` vector is guaranteed to be empty when we're configuring the set of summary vectors to report.  Don't blindly access the `.front()` element.

Summary: Don't Index Out-of-Bounds During Node Configuration

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ConnectionTests.cpp

This commit adds a new helper function
```
getCompletionNumberFromGlobalConnectionIndex
```
which returns an `optional<int>` containing the completion number of the connection with the associated global cell index, or `nullopt` if no such connection exists.  We then reimplement the CxL summary keywords in terms of this function to handle connections being added dynamically during the simulation.  The connections at the end of
the simulation, from which we configure all connection-related summary nodes, might not accurately reflect the connections existing at all times during the simulation.

CxL: Account for Dynamically Changing Set of Connections

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCON

mostly related to default value.
default_value is used, while it looks like not working.

correcting the definition of the keyword AQUCON

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/PAvg.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/PAvg.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WPAVE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WWPAVE
tests/parser/PAvgTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/SummaryConfigTests.cpp

Load and internalize WPAVE and WWPAVE keywords. These keywords are loaded as a first step towards supporting the `WBP?` keywords - to complete the `WBP?` work is a *large task*.

Internalize WPAVE and WWPAVE keywords

---

opm/output/eclipse/VectorItems/group.hpp
src/opm/output/eclipse/AggregateGroupData.cpp

I am currently working on reading Schedule information from the restart file, this obviously requires understanding the content of the restart files. This is complex and I am struggling a bit getting a complete understanding of the code writing restart files, currently focusing on the `IGRP` array assembled in [AggregateGroupData.cpp](https://github.com/OPM/opm-common/blob/master/src/opm/output/eclipse/AggregateGroupData.cpp#L863). When just reading the code is not enough to get a full understanding my normal way to "get into" a code is to start making small changes, move some code around, extract blocks of code into functions, reduce nesting by e.g. early return and so on.
The main focus of the current PR is the [branching logic](https://github.com/OPM/opm-common/blob/master/src/opm/outpu …

AggregateGroupData - refactoring

---

src/opm/io/eclipse/EclOutput.cpp

We would write outside the alocated buffer, and fail to write the nul terminator, when presented with inputs of very small size
(denormalized numbers in the order of 1.0e-101 or smaller).  Switch to using `std::snprintf` and expand the buffer size to work around this problem.
While here, also fix a subtle issue in determining whether or not we should insert the exponent character 'D' into the formatted output. Since we add one upon formatting the number, we also need to use a non-symmetric condition for the 'D' character lest we fail to output correctly formatted versions of
```
-2.9440373045442E-100 (=> -0.29440373045442D-99)
-2.9440373045442E+99  (=> -0.29440373045442+100)
```
This fixes a strange segmentation fault we would sometimes see when upgrading reference solution data.

Don't Overrun Formatting Buffer in 'doub_string_ecl'

---

CMakeLists_files.cmake
opm/output/eclipse/Inplace.hpp
src/opm/output/eclipse/Inplace.cpp
tests/test_Inplace.cpp

To be used to pass values from the simulator to the Summary function. Will probably be expanded with time.
Downstream: https://github.com/OPM/opm-simulators/pull/2920

Add container to hold on to Original in place values

---

opm/common/utility/Serializer.hpp
opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.cpp
tests/test_Serializer.cpp
tests/test_Summary.cpp

Add methods `put_vector() / get_vector()` and rename map overloads to `put_map() / get_map() `
The serializer in opm-common is used to serialize (and then collect on IO Rank) some classes from opm-common. The current use of this serializer is [here](https://github.com/OPM/opm-simulators/blob/ebf0d2d0d7582c94b2622d0773d72d05c9528fee/ebos/eclwriter.hh#L335). A bit more coming up with #2124
I realize this is a bit on the side of my main competence and I know the current implementation is not something to brag about. If someone want to flex their C++ muscles and improve it  - or rewrite to use the existing system I am all smiles.

Serializer vector

---

src/opm/output/eclipse/RestartIO.cpp

This makes it slightly easier to diagnose output errors.
While here, also convert to using libfmt to log output to the restart files.  The library knows how to format `std::tm{}` objects using format strings from `std::strftime()` which means we get month names for free.
Existing report format:
```
Restart file written for report step:  4/39.  Date: 2018/12/15
```
New report format:
```
Restart file written for report step  4/39, date = 15-Dec-2018 00:00:00
```
~Whether or not to include the time of day, `00:00:00` in the example above, is debatable and I'm open to dropping it.  It might be useful for `LAB` units or if the `START` time is not midnight though.~

Report Element Counts for Solution Vector Size Mismatch

---

opm/io/eclipse/SummaryNode.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

This PR adds support for outputting the productivity index of a well's preferred phase at the well and connection levels to the summary file (keywords `WPI` and `CPI`).
Update unit tests accordingly.
This PR depends on values calculated in OPM/opm-simulators#2846 and must not be merged before that PR is in the master branch.

Support Outputting Preferred Phase PI to Summary File

---

src/opm/output/eclipse/Summary.cpp

I know you don't like defaults but this does gives exactly the same behavior, without the warnings spew.

add explicit defaults to quell warnings

---

python/Dockerfile
python/Dockerfile.create
python/generate-pypi-package.sh
python/setup-docker-image.sh

- add python 39
- add exports from docker container to host
- disable building tests for opm-common.
probably quite some overlap with https://github.com/OPM/opm-common/pull/2129  i did this in parallel without noticing the other PR. have successfully deployed nightly builds from jenkins with these changes.

Some fixes to pypi packaging

---

src/opm/output/eclipse/AggregateWellData.cpp
tests/test_AggregateWellData.cpp

This pr contains corrections to SWEL that will handle correctly 
i. the use of WCONHIST data with zero rates for each of oil, water or gas rates and 
ii. the use of WELOPEN 'SHUT'
In both these cases the relevant SWEL[0],  [1] and [2] need to be set to zero.
This PR is ready for review and merge when OK.

Correction of SWEL to handle zero rates in WCONHIST and WELOPEN SHUT

---

src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

Two fixes for evaluation of summary variable "ROEW":
1. Make sure the "original_inplace" variable can be safely accessed.
2. Make sure the ROEW variable is evaluated *after* "WOPT"

Make sure original_inplace can be safely accessed

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
tests/parser/FieldPropsTests.cpp

To support PERMR and PERMTHT they are internally translated to PERMX and PERMY, since they should behave as aliases.
As a result PERMR and PERMX can be used interchangeably, and the same is true for PERMTHT and PERMY.
There are a few limitations:
- the `keys()` methods from `FieldProps` and `FieldPropsManager` will not return the aliases.
- The `erase()` and `extract()` methods from `FieldProps` will not function with the aliases. Deleteing the aliased keywords will also remove the aliased keyword. However, these methods seem not to be exposed in `FieldPropsManager()`

Support PERMR and PERMTHT as aliases for PERMX and PERMY

---

src/opm/parser/eclipse/Parser/Parser.cpp

There are some keywords which are "user defined", like e.g.
```
FIPXYZ
1 2 3 43 5 6 /
```
where the 'XYZ' part is defined by the user. For these keywords creating the mapping from deck keyword to parserkeyword is a bit more involved, with recent changes to support summary keywords like `ROEW_XYZ` it has become even more involved. For large models the time to look up the parskeyword for e.g. `FIPXYZ` has become prohibitive.
With this PR the result of looking up the parserkeyword is stored in a temporary variable to speed things up.

Cache parser keyword

---

src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp

The summary keyword ROEW equals "Production from wells / initially_in_place". Initial implementation was based on "WOPT" - but it was not obvious how to assign wells to regions. In this PR the connections are used instead.

Summary keyword ROEW is based on COPT and not WOPT

---

src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp

Use value from WCONPROD as default. The simulator does not set the alqvalue if gas optimization is not used
Multiply with efficiency factor when accumulation group rates

Fix gaslift output

---

tests/summary_deck.DATA

This restores `test_Summary` for WPI vectors.
This PR supersedes and closes #2152.

Summary Test Deck: Open Wells 1, 2, 3, and 6 at First Step

---

opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp

When using ActionX we can update a well in the middle of the timeseries. This would previously copy the updated well value to all consecutive timesteps, now only until the first "different value".

Dynamicstate update

---

opm/common/utility/numeric/calculateCellVol.hpp
opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
src/opm/common/utility/numeric/calculateCellVol.cpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
tests/parser/EclipseGridTests.cpp
tests/test_calculateCellVol.cpp

This pull request works towards support for cylindrical grids, by defining a spider web, and introducing corrections for the cylindrical case. Following changes are made in the grid code as initial steps towards this goal:
- The cylindrical case defines a spider web according to the parameters for a cylindrical grid.
- The getCellVolume method is changed to return the volume for cells for a cylindrical grid overlayed on the spiderweb.

Support cylindrical grids as a spiderweb with corrected volumes

---

opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/msim/actionx2.include
tests/msim/test_msim_ACTIONX.cpp
tests/parser/DynamicStateTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WTEST.cpp
tests/parser/WellTests.cpp

Picture this:
Eclipse will interpret the keywords in an imperative fashion - as if Eclipse was a DSL for reservoir simulation. This is particularly appearant when it comes to the Schedule section where well controls and timestepping is controlled through a series of keywords. In opm we do it differently - all the information from the entire .DATA file is parsed and internalized and the rest of simulation uses the `EclipseState` and `Schedule` datastructures. This has worked quite well, but the ACTIONX stuff which allows for dynamic updates to the the schedule information does *not* fit very well into the existing `Schedule`class - it is a bit like:
In this PR we record the time-range for the active well open events, this is an attempt to update the correct time-range for well information …

Manage well status with a shared pointer: To enable/improve runtime updates

---

opm/output/eclipse/VectorItems/connection.hpp
src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/output/eclipse/AggregateWellData.cpp

SWEL: improvements to handle lift gas correctly depending on which units are used for lift gas rates
XCON: Improvements needed in some cases to get (more) correct eclipse restart from flow run.
NOTE: these changes has been copied from PR 2160 to be treated as a separate PR (here).
This PR is then ready for review  and merge when OK.
NOTE: I have run tests, ctest gives no errors. However, when I run make check all checks fail due to  differences between Jenkins and local machine results. I would  appreciate if @bska could help run tests to check if the results are OK.

Changes for SWEL  for correct handling of lift gas plus improvements to XCONN

---

src/opm/parser/eclipse/EclipseState/EndpointScaling.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/I/IPCG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/I/IPCW
src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PCG
src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PCW
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SGCR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SGL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SGLPC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SGU
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SOGCR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SOWCR
tests/parser/FieldPropsTests.cpp
tests/parser/RunspecTests.cpp

Existence of certain EPS keywords (`SWL`, `SGCR`, others) is sufficient to activate the end-point scaling option.  The deck does not **need** to have the `ENDSCALE` keyword in these cases, but it is recommended that `ENDSCALE` nevertheless be used.
On the other hand, certain other keywords do require the presence of `ENDSCALE` so record this in "requires" clauses.

Relax EPS Activation Criterion

---

src/opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculator.cpp

Remove a noisy warning - will blow up anyway if actually used.

Remove check and warning for use of porv based WBP calculation

---

opm/parser/eclipse/EclipseState/Runspec.hpp
python/tests/data/CORNERPOINT_ACTNUM.DATA
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SGFN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SGOF
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SLGOF
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SOF2
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SOF3
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SWFN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SWOF
tests/parser/ParserTests.cpp
tests/parser/RunspecTests.cpp
tests/parser/TableContainerTests.cpp
tests/parser/TableManagerTests.cpp
tests/parser/data/integration_tests/GRID/CORNERPOINT_ACTNUM.DATA
tests/parser/integration/ParseKEYWORD.cpp

This information is generally useful so we should have a single source of truth and not have to reimplement the logic every time we need it.

Make Saturation Function Family Available in Runspec

---

src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp

Users should not have to supply synthetic relative permeability or capillary pressure functions in a single-phase run.

Don't Require Saturation Functions for One-Phase Runs

---

opm/parser/eclipse/EclipseState/Schedule/Events.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp

This adds PRODUCTION/INJECTION_UPDATE event for WELTARG and WEFAC.
For the usage I need, I don't see any point of keeping separate events types for WELTARGS and WEFAC but maybe I am wrong.

add WELTARG and WEFAC to events

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculator.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculator.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WPAVEDEP
tests/parser/WellTests.cpp

Minor preparation to handle variable reference depth through the `WPAVEDEP` keyword in the `WBPx` calculations. NB: The actual `WPAVEDEP` keyword will be handled after: #2178

Add reference depth member to PAvg and PAvgCalculator

---

opm/parser/eclipse/EclipseState/Schedule/MSW/SICD.hpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGAICD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGSICD
tests/parser/MultisegmentWellTests.cpp

WSEGAICD and WSEGSICD used SEG1 and SEG2, while all
other WSEG* keywords use SEGMENT1 and SEGMENT2 for the same
item.

Use consistent names in WSEG* keywords

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp
tests/parser/ScheduleTests.cpp

This should be the first PR to be merged in the #2176 effort. With this PR the keywords in the Schedule section are internalized in a new class `ScheduleDeck` - which is essentially a somewhat glorified `std::vector<DeckKeyword>` - this new container is owned by the `Schedule` class and will have application lifetime.
For now the new `ScheduleDeck`will be used to assemble to full `Schedule` datastructure, but in the future the plan is to be able to manipulate this structure directly by adding keywords and "play it again Sam".

Sched deck

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/ScheduleTests.cpp

This is a first PR in the #2176 effort. With this PR a new `ScheduleState[1]` class is created, and the `Schedule` class gets a new member `std::vector<ScheduleState>`. One `ScheduleState`contains the accumulated scehdule state up until this time. Currently it only internalizes the `WPAVE` keyword in the form of a `std::shared_ptr<PAvg>` member, but eventually the goal is that the `Schedule` class should only consist of container of report step indexed `ScheduleState` instances.
When this work has been completed everything about time can (hopefully!) be greatly simplified, in particular the long term members `DynamicState<T>` and `TimeMap` can just be removed. This will make the time handling in the `Schedule`class less special cased. 
The PR: #2183 should only affect `Schedule` …

Add sched tstep

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
tests/parser/ScheduleTests.cpp

Reverts OPM/opm-common#2215
Damn - merged the wrong PR.

Revert "Use std::map for groups"

---

examples/make_lodsmry.cpp

When OpenMP is disabled using -DUSE_OPENMP=OFF then a linking error occurs in make_lodsmr. This PR fixes this by using #ifdef _OPENMP instead of #if HAVE_OPENMP.

Linking issue when OpenMP is disabled.

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

This is to enable reiterating over the Schedule section *without* grid and field properties.

Use pointers to grid and fieldprops in Schedule construction

---

opm/parser/eclipse/Units/UnitSystem.hpp
opm/parser/eclipse/Units/Units.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/Units/UnitSystem.cpp

Setting unit SECONDS for summary vector TCPU. The unit is output to the SMSPEC file. The current version of flow is not outputting  any unit for this vector. Second is used for all unit systems.

Adding unit SECONDS for summary vector TCPU

---

src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/output/eclipse/AggregateWellData.cpp

The wells maintain their own insertion index, so we do not need to infer the index from the well name order.

Revert to Looping Well Names

---

src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/share/keywords/001_Eclipse300/C/CO2STORE
src/opm/parser/eclipse/share/keywords/keyword_list.cmake
tests/parser/RunspecTests.cpp

According to the OPM manual CO2STORE and not CO2STOR should be used to enable the co2 storage option. This makes aligns the simulator with the manual. CO2STORE is also used by E300 to enable its co2 storage option.

add CO2STORE as alias for CO2STOR

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MSUM_PROBE
src/opm/parser/eclipse/share/keywords/keyword_list.cmake
tests/parser/SummaryConfigTests.cpp

We currently load and internalize all the keywords .... except those we do not load. 
There is a *myriad* of summary keywords and many of these we do not load at all; let all alone handle sensibly ...
This PR adds loading to some of them and should fix: #2232

Add summary keywords of the form MSUMxxx

---

src/opm/parser/eclipse/EclipseState/EclipseState.cpp

Extra `,` while concatenating strings completely f..ed up the varargs function call. Now error message from EclipseState construction should be correctly displayed.

Eclipsestate error msg

---

opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ConnectionTests.cpp
tests/parser/MultisegmentWellTests.cpp
tests/parser/ScheduleTests.cpp

The connection length and effective radius is used by the exotic MW polymer model. Storing it here removes this explicit usage of the grid in the well model.

Adding connection length and effective radius to the connection

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp

Small step on the #2176 journey
Downstream: https://github.com/OPM/opm-simulators/pull/3027

Export VFP tables as reference wrappers instead of pointers

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

A long time ago the homemade[1] container `OrderedMap` was created to maintain insert order for wells and groups. Turned out the wells and groups also needed to hold their own here - i.e. carry member `insert_index`. Hence the insert order was mainted doubly, with this PR wells and groups are stored with `std::unordered_map<>`. 
The `Schedule::getWells()` function will return proper well objects in insert order, `Schedule::wellNames()`will return well names in *random order*.
[1]: Kjære gud i høyden - dette har jeg laga på sløyden!

Use ordinary map for wells

---

src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp

Member comparison missing from `ScheduleState::operator==()`

Add missing WellOrder== in ScheduleState==

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/NameOrder.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/NameOrder.cpp
tests/parser/ScheduleTests.cpp

With this PR the groups are managed internally with a `std::unordered_map<>` and a separate class `GroupOrder` manages the ordering.
The small `GroupOrder`class was initially implemented with inheritance from class `NameOrder`- but-I-could-just-not-get-that-to-work-for-f...-sake so I ended with a separate small class.

Use normal map groups

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp

clang does not consider default template parameters when resolving template arguments.
in particular this broke static analysis jobs.

fixed: add some type aliases and explicit template parameters

---

src/opm/parser/eclipse/EclipseState/Schedule/Well/WellEconProductionLimits.cpp

Max gas liquid ration is not supported in the simulator. But this bugs wrongly spam the log file with "max-gas-liquid... not supported" for cases where gas-oil ratio is set.

fix max_gas_liquid_ratio

---

msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

Part of #2176 
To enable better messages when the ACTIONX keywords are applied.
Downstream: https://github.com/OPM/opm-simulators/pull/3047

Pass simulation time argument to Schedule::applyAction()

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp

Add mutable overloads for map_member methods get() and operator()

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

A preparation for WELPI + ACTIONX. Pass the simulated WellPI from the simulator, and let the opm-common code handle the scaling.

Apply WELPI is based on newWellPI and not scaling factor

---

opm/output/data/Aquifer.hpp
opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.hpp
opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.hpp
opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/SingleNumericalAquifer.hpp
opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/SingleNumericalAquifer.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/AquiferTests.cpp
tests/parser/EclipseGridTests.cpp

This is a continuation of PR https://github.com/OPM/opm-common/pull/2246. 
Numerical aquifer cells technically are cells belong to the grid, while they can be specified with relatively arbitrary properties to these cells, like porosity, volume, pore volume, depth, pvtnum, satnum... they can have properties totally independent of the other parts of the grid.  We need to update some of the field props due to numerical aquifer cells.  We did not update all of them in the field props, because downstream are not using them. But maybe we should update them anyway?
To make the numerical aquifer work, we also need to do the following:
1. isolate numerical aquifer cells with other reservoir grid cells
2. connect the aquifer cells with NNCs
3. connect the reservoir cells  (connection cells) to the …

Numerical Aquifer continue

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
python/tests/test_schedule.py
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/ScheduleTests.cpp
tests/parser/UDQTests.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

The schedule refactoring is approaching the finishing line. When this PR is merged the `Schedule`class has been more-or-less 100% rewritten to use the `ScheduleState`class with snapshots of the entire state instead of multiple `DynamicState<T>` vectors which manage dynamic state indpendently for different properties. For this particular PR I intend to clean up the commits, and then I consider it ready for merging. When this is merged the following tasks remain:
1. The WELPI keyword is a very different beast - the implementation in this PR is just a minimal refactor based on the existing implementation. Maybe it would make sense to refactor the WELPI implementation to match the (not yet ready) ACTIONX version of the same keyword?
2. Support WELPI + ACTIONX; to enable that has been the goal …

Well use SchedState

---

src/opm/parser/eclipse/Units/UnitSystem.cpp

this ensures that we are using the same units as the commercial simulator.

change units for water cut vectors

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
tests/parser/FieldPropsTests.cpp

Unconditionally include TRAN? keywords in FieldProps::keys<double>()

---

src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/FieldPropsTests.cpp

Must allow the fieldprops to return invalid vectors to fully support the TRAN calculator

FieldProps can return invalid data if allow_unsupported is true

---

python/cxx/parsecontext.cpp
python/tests/test_parse.py

Fix of: https://github.com/OPM/opm-common/issues/2262

Expose ParseContext::ignore_keyword() in Python

---

opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DRSDT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DRSDTR
src/opm/parser/eclipse/share/keywords/900_OPM/D/DRSDTCON
src/opm/parser/eclipse/share/keywords/keyword_list.cmake
tests/parser/ScheduleTests.cpp

This adds a version of DRSDT useful for co2 storage. See the corresponding PR i opm-simulators for more details.

Add DRSDTCON to allow for convective DRSDT

---

opm/parser/eclipse/EclipseState/Schedule/MSW/SICD.hpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/SICD.cpp
tests/parser/MultisegmentWellTests.cpp

Use `std::optional<double>` to hold ICD max flow rate.
@jalvestad : with this it should be possible to avoid the ` == std::numeric_limits<double>::max` in #2319

Use std::optional<double> for ICD maximum flow rate

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCONHIST
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCONPROD
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

With this PR opm-common accepts 'UDA' values for ALQ in WCONPROD / WCONHIST. Downstream the simulator will still access the ALQ values as double only - and there weill be an exception if trying to simulate with UDA values for ALQ.
Updating the simulator to handle UDA values is actually a quite small task; I started on it - but I would prefer to get this in first.

Handle UDA values for ALQ in WCONPROD / WCONHIST

---

examples/msim.cpp
examples/opmi.cpp
opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
python/cxx/eclipse_config.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/msim/test_msim.cpp
tests/msim/test_msim_ACTIONX.cpp
tests/msim/test_msim_EXIT.cpp
tests/parser/PAvgTests.cpp
tests/parser/SummaryConfigTests.cpp
tests/parser/integration/parse_write.cpp
tests/test_EclipseIO.cpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp
tests/test_restartwellinfo.cpp

This PR is just an API change; which is to prepare for better checking of summary keywords with arbitrary FIPNUM regions - like:
```
RPR__ABC
1 2 3 /
```

Add fieldprops argument to SummaryConfig constructor

---

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp

There's no need to require that the client creates an actual, mutable array object on the stack (or elsewhere) in order to form an `EclipseGrid` instance.
This is nevertheless mostly to make it easier to use the `COORD`/`ZCORN` constructor usable in unit tests.

Accept Temporary 'Dimension' Arguments in EclipseGrid Constructor

---

opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/msim/test_msim.cpp
tests/parser/EclipseStateTests.cpp
tests/parser/IOConfigTests.cpp
tests/parser/RestartConfigTests.cpp
tests/parser/ScheduleRestartTests.cpp
tests/parser/ScheduleTests.cpp
tests/rst_test.cpp

To avoid overriding the Schedule object after construction; again a part of the Schedule refactor cleanup effort.

Add optional argument to override output interval - EBOS paramstyle

---

opm/parser/eclipse/EclipseState/Runspec.hpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
tests/parser/RunspecTests.cpp

This commit internalises the items `NANAQU` (5) and `NCAMAX` (6) of the `AQUDIMS` keyword into a new structure
```
AquiferDimensions
```
hooked up to the `Runspec` class.  This is in preparation of adding restart output for analytic aquifers (Carter-Tracy and Fetkovich).

Partially Internalise AQUDIMS in Runspec

---

examples/msim.cpp
examples/opmi.cpp
opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
opm/parser/eclipse/Parser/ParseContext.hpp
python/cxx/eclipse_config.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/Parser/ParseContext.cpp
tests/SPE1CASE1.DATA
tests/msim/test_msim.cpp
tests/msim/test_msim_ACTIONX.cpp
tests/msim/test_msim_EXIT.cpp
tests/parser/PAvgTests.cpp
tests/parser/SummaryConfigTests.cpp
tests/parser/integration/parse_write.cpp
tests/test_EclipseIO.cpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp
tests/test_restartwellinfo.cpp

Handle various types of invalid summary region keywords; check that the FIPNUM region is defined; both in sense of the actual keyword and the numerical value.
Behavior controlled with ParseCOntext - default is a warning.

Summary invalid fipnum

---

CMakeLists_files.cmake
opm/output/eclipse/ActiveIndexByColumns.hpp
src/opm/output/eclipse/ActiveIndexByColumns.cpp
tests/test_ActiveIndexByColumns.cpp

The protocol for outputting an aquifer's active cell IDs to the restart file requires that the cells be enumerated according to their column.  In particular, the aquifer's notion of a model's active cells correspond to a cell ordering of the form
```C++
for (i = 0; i < Nx; ++i)
for (j = 0; j < Ny; ++j)
for (k = 0; k < Nz; ++k)
use(X(i, j, k))
```
instead of the common ordering, sometimes referred to as "natural ordering"
```C++
for (k = 0; k < Nz; ++k)
for (j = 0; j < Ny; ++j)
for (i = 0; i < Nx; ++i)
use(X(i, j, k))
```
which is employed elsewhere.
This commit adds a special purpose mapping facility which will translate active cell IDs from natural ordering to the columnar enumeration.  The facility is intentionally bare-bones because we do not expect to use it outside of the restart …

Add Special Purpose Active Cell Enumeration by Columns 

---

opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.cpp

to make sure the same order when traversing the m_aquifers during parallel running across different processes.
the consistent order is important for running the BlackoilAquiferModel in parallel when numerical aquifers are involved.

using std::map for m_aquifers of NumericalAquifers

---

cmake/Modules/Findcjson.cmake
opm-common-prereqs.cmake

This was somehow deactivated when merging opm-parser to opm-common.
This will now use Debian's libcjson package if installed.

Recover external cjson library support.

---

CMakeLists.txt
opm-common-prereqs.cmake
python/setup-build.sh.in
python/setup-install.sh.in
python/setup-package.sh.in
python/setup-test.sh.in

Otherwise python2 might be found, but OPM needs python3.
Closes #2343

Explictly search for python3 (CMake >= 3.12.0) and send error if only python2 is found

---

CMakeLists.txt
opm-common-prereqs.cmake

If fmtlib is present on the system we used that one in the normal mode (not header only). Otherwise we fall back to the embedded one in header only mode. Might even save some compile time (At least it feels like I am getting less compiler warnigs).
BTW There is a chicken and egg problem with config_hook and source_hook: One cannot add libraries in the former one that are needed by GenerateKeywords.cmake (which is included in the latter) as source_hook is run before config_hook. That is the reason why the fmtlib logic was moved out of the hooks.
Much cleaner than my first try #2291, anyway.
Let's hope it works with python

Enable usage of fmtlib on the system.

---

opm/parser/eclipse/EclipseState/Schedule/Action/ActionValue.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionValue.cpp
tests/parser/ACTIONX.cpp

Action well conditions like:
```
WBHP 'P1' > 200
```
i.e. with fully specified well name - are evaluated as scalars. With this PR we ensure that the well name `P1` is still available in the result objects matching wells.

Make sure action results contain well for fully specified condition

---

opm/parser/eclipse/EclipseState/Aquifer/Aquancon.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/Aquancon.cpp

We need this information to form part of the per-connection restart output to the `SCAQ` array.  The accumulation uses the same
procedure as for the total influx coefficient, but is always based on the geometric face area instead of the tabulated aquifer influx
coefficient.

Accumulate Effective Aquifer Connection Face Area

---

cmake/Modules/OpmCompile.cmake
cmake/Modules/OpmFind.cmake
cmake/Modules/OpmPackage.cmake

add_definitions is deprecated or at least its use discoraged. This also saves manually adding the -D qualifier!
This is actually needed by our buildsystem magic if it searches for packages written for newer versions. Some of these projects omit the -D qualifiers and the definitions would end up on the command line as e.g `c++ USE_pybind11` instead of `c++ -DUSE_pybind` and we will get errors about not exising files (define is intepreted as source file).
Tested also on Ubuntu 18.04

Use add_compile_definitions to add defintions

---

opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
tests/parser/GroupTests.cpp
tests/parser/ScheduleTests.cpp
tests/test_GuideRate.cpp

This adapt the guiderate classes to handle injection groups. It needs to be merge together with downstream changes in opm-simulators.

Add guiderate for injection groups

---

opm/output/data/Wells.hpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/Summary.cpp
tests/test_AggregateWellData.cpp
tests/test_RFT.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp

This PR adds a new data member
```
Well::Status dynamicStatus
```
to the `data::Well` object.  This member records the simulator's notion of a well's open/shut/stop status and is especially needed to support `WECON`-type status changes once the simulator maintains both open and shut wells.
While here, also change multiple summary primitives to not look up the same values repeatedly.

Record Dynamic Well Status in Output Wells

---

opm/output/eclipse/InteHEAD.hpp
opm/output/eclipse/VectorItems/intehead.hpp
opm/parser/eclipse/EclipseState/Runspec.hpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/InteHEAD.cpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
tests/test_InteHEAD.cpp

This pull request containts corrections to the InteHead array to account for the use of:
1. ROCKOPTS - item 3: Table region to be used
2. Well list data in Eclipse compatible Restart file
- WELLDIMS:
- Item 11:  The maximum number of well lists that a well may belong to at any time
- Item 12:  The maximum number of dynamic well lists in the simulation
The implementation of restart file output for the well lists will be a separate pullrequest (not included here).
The PR passes all unit tests and regression tests appart from test 118: 
118 - compareECLInitFiles_flow+NORNE_ATW2013
The differences are in the INIT file, and relates to value indexs [30] and [302], both should have default value equal to 1 which they have in this PR.
This PR is ready for review and merge after revision based on …

Corrections to InteHead to account for ROCKOPTS data and Well lists

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

When an ACTIONX keyword has evaluated to true the Schedule section is replayed. This can become quite confusing in the .PRT file - with the current PR the reruns are formatted to stand out better.

Add prefix the schedule messages to highlight ACTIONX rerun

---

CMakeLists.txt
cmake/Modules/Finddune-common.cmake
cmake/Modules/OpmInit.cmake
cmake/Modules/OpmLibMain.cmake
python/setup.py.in

to ease packaging process.
Currently we will always use the system's pybind. We could make that optional,

Support system pybind

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

When Actionx has updated well(s) we must notify the simulator of which wells have been updated.
Downstream: https://github.com/OPM/opm-simulators/pull/3116

Schedule::applyAction() will return a set of wells affected

---

CMakeLists_files.cmake
opm/io/eclipse/EclFile.hpp
opm/parser/eclipse/Deck/DeckKeyword.hpp
opm/parser/eclipse/Deck/ImportContainer.hpp
src/opm/io/eclipse/EclFile.cpp
src/opm/parser/eclipse/Deck/DeckKeyword.cpp
src/opm/parser/eclipse/Deck/ImportContainer.cpp
src/opm/parser/eclipse/Parser/Parser.cpp
tests/parser/ImportTests.cpp

This keyword adds support for the `IMPORT`keyword which can be used to load keywords from a (typically binary) file with result formatted keywords. The list of supported keywords is hardcoded - and yet quite short, it is trivial to add new ones though.

Import container

---

opm/parser/eclipse/EclipseState/Aquifer/AquiferCT.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferCT.cpp

The data member `cell_id` isn't actually used anywhere outside of object serialization.  Just remove it.

Remove Cell ID Member from CT Aquifer Representation

---

debian/rules

At some point running tests without enabling embedded python broke.
Since this is an oversight in packaging, I fix it there, but the tests should also be fixed (I'll look into that later).

enable embedded python in ubuntu packages

---

opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
tests/parser/FieldPropsTests.cpp

to manage endpoint values. Similar to: https://github.com/OPM/opm-common/pull/2411
Downstream: 
https://github.com/OPM/opm-material/pull/450
https://github.com/OPM/opm-simulators/pull/3144

Use std::optional and value objects instead of std::shared_ptr

---

src/opm/output/eclipse/RestartIO.cpp

This fixes a real field case in which the network is only activated (keywords `BRANPROP` and `NODEPROP`) fairly late in the simulation run.

Output Network Arrays Only if Network is Active

---

opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.hpp
opm/parser/eclipse/EclipseState/EclipseConfig.hpp
opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/Grid/FieldData.hpp
opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
opm/parser/eclipse/EclipseState/Grid/Keywords.hpp
opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp
opm/parser/eclipse/EclipseState/Grid/TranCalculator.hpp
opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
opm/parser/eclipse/EclipseState/InitConfig/InitConfig.hpp
opm/parser/eclipse/EclipseState/Runspec.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.hpp
opm/parser/eclipse/Units/UnitSystem.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.cpp
src/opm/parser/eclipse/EclipseState/EclipseConfig.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
src/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
src/opm/parser/eclipse/EclipseState/InitConfig/InitConfig.cpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
src/opm/parser/eclipse/Units/UnitSystem.cpp
tests/parser/FieldPropsTests.cpp
tests/rst_test.cpp

Also check the eclipsestate in the restart testing. 
The `xxx::rst_cmp()` family of functions compare objects in a manner where differences due to one being a restart and one not being restart are not considered.

Add  EclipseState comparison to rst_test application

---

CMakeLists_files.cmake
opm/output/eclipse/AggregateAquiferData.hpp
opm/output/eclipse/InteHEAD.hpp
opm/output/eclipse/RestartIO.hpp
opm/output/eclipse/VectorItems/aquifer.hpp
opm/output/eclipse/VectorItems/intehead.hpp
opm/output/eclipse/WindowedArray.hpp
opm/parser/eclipse/EclipseState/Aquifer/AquiferCT.hpp
opm/parser/eclipse/EclipseState/Aquifer/Aquifetp.hpp
src/opm/output/eclipse/AggregateAquiferData.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/InteHEAD.cpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/Aquancon.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferCT.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/Aquifetp.cpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
tests/test_AggregateAquiferData.cpp
tests/test_InteHEAD.cpp
tests/test_Restart.cpp

We support both Fetkovich and Carter-Tracy aquifers.  We presently output trivial values only in the `ACAQ` (per-connection, double precision elements), but otherwise assemble reasonable values for many items.
We leverage the fact that the aquifer connections do not change throughout the simulation run.  The "Aggregate" API is therefore constructed in such a way that most of the expensive operations (e.g., mapping active cell IDs to their columnar counterparts) happens once (in the constructor) and the per-aquifer operations are performed for each restart output step.  We intend that one aquifer output object be constructed at the start of the simulation run, if needed, and that this object will live until simulation shutdown.
If a simulation run uses analytic aquifers we construct an …

Add Restart Output Facility for Analytic Aquifer Data

---

opm/output/data/Wells.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp

Various serialization ickies. These really only affects the test where default constructed objects are in use and not real code where a deck is loaded. The exception is the Schedule.hpp operator[] usage fix.

Fix some valgrind errors in test_ParallelRestart

---

CMakeLists_files.cmake
opm/common/utility/Serializer.hpp
opm/parser/eclipse/EclipseState/Grid/Keywords.hpp
opm/parser/eclipse/EclipseState/Grid/TranCalculator.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GTNode.hpp
opm/parser/eclipse/EclipseState/Schedule/MessageLimits.hpp
opm/parser/eclipse/EclipseState/Schedule/Tuning.hpp
opm/parser/eclipse/EclipseState/SimulationConfig/RockConfig.hpp
opm/parser/eclipse/EclipseState/Tables/Aqudims.hpp
opm/parser/eclipse/EclipseState/Tables/Eqldims.hpp
opm/parser/eclipse/EclipseState/Tables/PlyshlogTable.hpp
opm/parser/eclipse/EclipseState/Tables/Regdims.hpp
opm/parser/eclipse/EclipseState/Tables/Tabdims.hpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/parser/eclipse/EclipseState/Grid/TranCalculator.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MessageLimits.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Tuning.cpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/RockConfig.cpp
src/opm/parser/eclipse/EclipseState/Tables/Aqudims.cpp
src/opm/parser/eclipse/EclipseState/Tables/Eqldims.cpp
src/opm/parser/eclipse/EclipseState/Tables/Regdims.cpp
src/opm/parser/eclipse/EclipseState/Tables/Tabdims.cpp
tests/parser/TuningTests.cpp

This avoid including headers in headers. In particular, these are somewhat large, generated headers, and they sit in classes that are pulled in a lot of places.

Avoid headers in headers

---

opm/parser/eclipse/EclipseState/SimulationConfig/RockConfig.hpp
tests/rst_test.cpp

This fixes the breakage in opm-common seen after merging PR #2438.
Note that the PR was not the cause of the problem as such.

Fix fallout from PR #2438

---

src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp

Seems to be the reference behavior

ActionX wait time compared with =>

---

cmake/Modules/OpmInit.cmake
cmake/Templates/opm-project-config.cmake.in

OpmPackage is needed as it defines find_package_deps. The CXX standard needs to be set as some cmake package config scripts will add incompatible compile switches like -std=gnu++11 otherwise (I guess because of import targets with INTERFACE_COMPILE_FEATURES), that will break the build.
Note that this is only an issue if an OPM module is used outside of OPM.
@totto82 Should be part of the release, too. There are users...

Include OpmPackage in opm-project-config.cmake and force -std=c++17

---

opm/output/eclipse/VectorItems/intehead.hpp
src/opm/output/eclipse/CreateInteHead.cpp

This PR checks that gas lift is active before outputting a positive value in `INTEHEAD[EACHNC]`.  Unless gas lift is activated through keyword `LIFTOPT`, that item in `INTEHEAD` must be zero.
Thanks to @tskille for identifying the issue.

Don't Output Gas Lift Parameters Unless Active

---

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
tests/parser/EclipseGridTests.cpp

This is an internal property - should not be part of the public API. Part of larger fix for the combination of IMPORT and MAPAXES.
Downstream: https://github.com/OPM/opm-grid/pull/532

Remove getMAPAXES from EclipseGrid public api

---

opm/common/ErrorMacros.hpp
opm/io/eclipse/ESmry.hpp
opm/parser/eclipse/Parser/Parser.hpp

this is at best bad practice and can lead to confusing
errors because compiler will interpret it as Opm:: if there
is no 'foo' symbol available in the Opm namespace and give
confusing 'no symbol Opm::Opm::foo' error messages.

fixed: do not use Opm:: prefix when inside namespace Opm

---

src/opm/parser/eclipse/Parser/ParserItem.cpp
tests/parser/TuningTests.cpp

For very small values the default used in the 
```
ParserKeywords::Keyword::Item::defaultValue = ...
```
initializations was incorrectly set to zero; the "normal" defaults was already correct. Discovered through this: https://github.com/OPM/opm-common/issues/2448

Make sure precision is retained in very small default values

---

opm/parser/eclipse/EclipseState/Runspec.hpp
opm/parser/eclipse/EclipseState/Tables/Regdims.hpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/AggregateNetworkData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/EclipseState/Tables/Regdims.cpp
tests/test_AggregateWellData.cpp

This pull request contains corrections / improvements to the following restart tables:
1. INOBR - change of dimensions to be compatible with Eclipse 100 v. 2019.2 
2. ZACN - correction to handle field properties as rhs - quantities
3. IH[ROCKOPTS_TTYP] - correction to handle the use of more than one set of fluid-in-place regions (NMFIPR)
4. SWEL - correction to handle prediction type wells correctly for SWEL [0 - 3]
The pull request is ready for review.

Some corrections / improvements to the eclipse - compatible restart file

---

opm/parser/eclipse/Deck/DeckKeyword.hpp
src/opm/parser/eclipse/Deck/DeckKeyword.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/DeckValueTests.cpp

Makes logic statements more explicit and removes a number of "signed vs. unsigned" comparison operations.

Add 'empty' Predicate to DeckKeyword Type

---

opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/AquiferTests.cpp
tests/parser/SummaryConfigTests.cpp

This PR extends the `SummaryConfig` aquifer processing to recognize numeric aquifer keywords without an explicit list of aquifer IDs, i.e., summary keywords of the form
```
ANQR
/
```
To this end, we add new helper functions `{analytic,numeric}AquiferIDs()` which form lists of pertinent IDs.  We then ensure that we create nodes only for proper subsets of these ID sets.
Add unit tests to both the analytic and numeric configurations to ensure that we generate these output sets or input errors when the input file refers to IDs of incorrect type or out of range.

Output Summary for all Numeric Aquifers When ID Defaulted

---

opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquiferCell.hpp
opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquiferCell.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.cpp
tests/parser/AquiferTests.cpp

When forming restart arrays for numerical aquifers (`IAQN` and `RAQN`) we need to know the total number of records in the input `AQUNUM` keyword as well as the record ID of each individual record.  This PR adds a tracking mechanism for this information.
While here, also add unit tests that verify that we've correctly interpreted the `AQUNUM` records.

Track AQUNUM Records for Restart Purposes

---

opm/output/eclipse/AggregateAquiferData.hpp
opm/output/eclipse/InteHEAD.hpp
opm/output/eclipse/VectorItems/aquifer.hpp
opm/output/eclipse/VectorItems/intehead.hpp
src/opm/output/eclipse/AggregateAquiferData.cpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/InteHEAD.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/output/eclipse/Summary.cpp
tests/test_AggregateAquiferData.cpp
tests/test_InteHEAD.cpp

This PR generates the `IAQN` and `RAQN` restart vectors pertaining to numeric aquifers.  The arrays are sized according to the number of records in the input `AQUNUM` keyword.  `RAQN` is a mix of static and dynamic information, including the cumulative total inflow volume of water from the aquifer into the model.  IAQN is exclusively static information.
We add new members to `AggregateAquiferData` and ensure that the numeric aquifer arrays remain empty when no numeric aquifers exist in the model.  Add unit tests for these new arrays and update existing unit tests to account for new dimension items.
We also ensure that we always generate the `ANQP`, `ANQR`, and `ANQT` summary vectors in models with numeric aquifers since those values go into `RAQN`.

Add Restart Output for Numeric Aquifers

---

opm/parser/eclipse/Deck/DeckItem.hpp
src/opm/parser/eclipse/Deck/DeckItem.cpp
src/opm/parser/eclipse/Parser/ParserItem.cpp

This should on average save a fraction of 0.5 * (1 - 1/g) of memory - where 'g' is the `std::vector` growth factor (guessing for 2?).

Add shrink_to_fit() for underlying storage in DeckItem

---

opm/common/OpmLog/OpmLog.hpp
src/opm/common/OpmLog/OpmLog.cpp

IN order to implement: https://github.com/OPM/opm-simulators/pull/3310

Expose function stdoutIsTerminal() as static member in OpmLog

---

src/opm/output/eclipse/CreateInteHead.cpp

The number of data items per well segment in the `RSEG` restart vector turns out to depend on the number of active phases (Oil, Gas, Water) in the simulation run.  In particular, the following relations hold
Case | Distribution | `NRSEGZ`
--------|------------|----------
Single phase | Oil, Gas, or Water | 126
Two phases | Oil/Gas, Oil/Water, Gas/Water | 134
Three phases | Oil/Gas/Water | 146
This PR implements that variability.
The output layer does not currently use any items above index 110 so this does not alter the contents of `RSEG`, only the size, for single phase or two-phase simulation runs.

Account for RSEG Size Depending on Number of Active Phases

---

msim/src/msim.cpp
opm/output/data/Aquifer.hpp
opm/output/eclipse/RestartValue.hpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/output/eclipse/RestartValue.cpp
tests/test_EclipseIO.cpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_restartwellinfo.cpp

This PR prepares for using more dynamic aquifer quantities from the simulator layer as part of the restart I/O process.  We add `MessageBuffer` support to the `CarterTracyData` and `FetkovichData` sub structures in order to hook into the `CollectToIORank` system and promote the `aquifer` member of `RestartValue` to first class status.  The latter means that clients will always need to form a `data::Aquifers` object when constructing a non-defaulted `RestartValue` object.

Communicate Dynamic Aquifer Data

---

opm/parser/eclipse/Deck/DeckItem.hpp
src/opm/parser/eclipse/Deck/DeckItem.cpp
src/opm/parser/eclipse/Parser/ParserItem.cpp

Another low hanging fruit for reducing the memory consumption like #2488.
We either reserve or use std::vector::insert instead of just blindly using push_back.

Prevent reallocations where possible when parsing items.

---

jenkins/update-opm-tests.sh
opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
tests/parser/UDQTests.cpp

This PR adds a new member function, `updateUDQActive`, to the group injection properties.  This is inspired by the function of the same name in the group production properties and fills the same purpose.  This, in turn, enables tracking whether a `GCONINJE` keyword activates a user-defined argument.  That status is in turn needed to generate the `IUAD` and `IUAP` restart vectors in the restart file in the face of models for which the only UDA is in `GCONINJE`.  To this end, also identify the integer values corresponding to `GCONINJE` UAD modes.

Track UDA Active Status for Group Injection Controls

---

opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.cpp

Not that it matters very much - but now the `GuideRateModel`class is fully const - which simplifies reasoning a bit.

Make method GuideRateModel::updateLINCOM() const

---

opm/output/data/Wells.hpp
opm/output/eclipse/AggregateConnectionData.hpp
opm/output/eclipse/AggregateMSWData.hpp
opm/output/eclipse/AggregateWListData.hpp
opm/output/eclipse/AggregateWellData.hpp
opm/output/eclipse/Summary.hpp
opm/output/eclipse/WriteRFT.hpp
src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/output/eclipse/WriteRFT.cpp
tests/test_AggregateConnectionData.cpp
tests/test_AggregateMSWData.cpp
tests/test_AggregateWellData.cpp
tests/test_RFT.cpp

Class is named `WellRates`but also carries a `using Wells = WellRates`- downstream used a mix of the two.
Downstream: https://github.com/OPM/opm-simulators/pull/3379

Rename data::WellRates -> data::Wells

---

docs/keywords.txt
opm/common/utility/numeric/SparseVector.hpp
opm/common/utility/parameters/Parameter.hpp
opm/common/utility/parameters/ParameterGroup.hpp
opm/common/utility/parameters/ParameterGroup_impl.hpp
opm/common/utility/parameters/ParameterMapItem.hpp
opm/common/utility/parameters/ParameterRequirement.hpp
opm/common/utility/parameters/ParameterStrings.hpp
opm/common/utility/parameters/ParameterTools.hpp
opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
python/cxx/deck_keyword.cpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/EclOutput.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/Parser/ParseContext.cpp
src/opm/parser/eclipse/Parser/raw/StarToken.cpp

Cool, that lintian even checks spelling adn proposes fixes.
Ecoding should always be UTF-8 as national encodings are being phased out (at least on Debian). There might be more such problems in cpp files that are not checked, though.

Debian spelling and encoding fixes

---

cmake/Templates/Doxyfile
opm/output/OutputWriter.hpp

This deactivates the message that the doxygen documentation was build at a certain time.
In Debian builds should be reproducible, i.e. packages build at a different time, by a different use, with a different local, etc should be identical. Still not there yet, but this is at least a small step towards it.

For discussion: Deactive timestamping in doxygen for reproducible builds.

---

opm/output/eclipse/Inplace.hpp
src/opm/output/eclipse/Inplace.cpp

The `PoreVolume` value is supposed to be calculated at reference conditions (i.e., no rock compressibility or temperature effects), but being able to report the non-reference condition value is beneficial.  This commit adds a slot for accumulating that value per FIP region and transporting the aggregated values to the PRT output system.

Add 'Inplace' Slot for Dynamic Pore Volume

---

opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/CreateDoubHead.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

Some minor changes (hopefully improvements) falling off the restart chore. The commit "Add method GuideRate::init_grvalue()" is needed from the simulator when setting guiderates

GuideRate / restart - minor stuff

---

opm/output/eclipse/AggregateAquiferData.hpp
opm/parser/eclipse/EclipseState/Aquifer/AquiferCT.hpp
opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.hpp
opm/parser/eclipse/EclipseState/Aquifer/Aquifetp.hpp
src/opm/output/eclipse/AggregateAquiferData.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferCT.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/Aquifetp.cpp
tests/parser/AquiferTests.cpp
tests/test_AggregateAquiferData.cpp

This PR switches to using the simulator's notion of initial aquifer pressure, aquifer mass density of water, aquifer water viscosity, and aquifer time constants.  These values will, ultimately, come from the `*_data` structures for the analytic aquifers but the simulator is the only system that is able to compute equilibrated initial pressure values if that is defaulted in the input.
To this end, rename various data members of the `*_data` structures to aid the reader who may not be intimately familiar with the details of the analytic models.  We switch the `initial_pressure` into an `optional<double>` instead of a `pair<bool,double>` with `std::nullopt` representing defaulted initial aquifer pressure values in the input file.
We also add logic and private data members to compute/store …

Centralise Aquifer PVT Property Calculations and Use Simulator's Values for Restart Output

---

CMakeLists_files.cmake
opm/parser/eclipse/Parser/Parser.hpp
python/cxx/parser.cpp
python/opm/_common.py
python/opm/io/parser/__init__.py
python/tests/data/SPE1CASE1B.DATA
python/tests/data/props_spe1case1b.inc
python/tests/test_parse_deck.py
src/opm/parser/eclipse/Parser/Parser.cpp
tests/SPE1CASE1B.DATA
tests/parser/ParserTests.cpp
tests/props_spe1case1b.inc

The python version of the opm-parser is used in a number of scripts in my company for parsing specific parts of a data deck. 
The efficiency of these scripts will be improved significantly by this PR, since large part of a data deck can be ignore.  
This is PR is ready for review.

Functionality for parsing only selected sections of a data deck

---

opm/parser/eclipse/Parser/Parser.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellEconProductionLimits.cpp

Removes warning `extra ';'` in GCC's `-Wpedantic` mode.

Prune Needless Trailing ';' On Certain Close Braces

---

opm/io/eclipse/rst/state.hpp
src/opm/io/eclipse/RestartFileView.cpp
src/opm/io/eclipse/rst/state.cpp
test_util/EclRegressionTest.cpp
tests/msim/test_msim.cpp
tests/parser/ScheduleRestartTests.cpp
tests/parser/ScheduleTests.cpp
tests/rst_test.cpp
tests/test_AggregateUDQData.cpp
tests/test_rst.cpp

This is in preparation of unconditionally loading analytic aquifer information from the restart file.  Update callers to new API.

Reimplement RstState::load In Terms of RestartFileView

---

CMakeLists_files.cmake
opm/output/data/Aquifer.hpp
src/opm/output/data/Aquifer.cpp
src/opm/output/eclipse/AggregateAquiferData.cpp
src/opm/output/eclipse/LoadRestart.cpp
tests/test_AggregateAquiferData.cpp
tests/test_Restart.cpp

This commit adds a new helper class,
```
Opm::data::TypeSpecificData
```
which holds type-specific sub-structures for Carter-Tracy, Fetkovich, and Numerical aquifers.  We implement this facility in terms of ~`std::variant<>` of `shared_ptr<>` to~ a `std::variant<>` of simple structures.  In turn, use the type-specific data for numerical aquifers to fill in the initial aquifer cell pressures where not available in the input data.

Collect Type-Specific Aquifer Data in Single Structure 

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.cpp
tests/parser/UDQTests.cpp

When the UDQs are loaded from the restart file the arguments are provided differently - create a new constructor++ for `UDQAssign` to prepare for loading from restart file.

Alternative selector implementation for UDQAssign loaded from rst

---

src/opm/io/eclipse/rst/state.cpp

The arrays are sized according to the number of variables of each category (well, group, field), not the number of UDQs.  While here, also split the restart UDQ definition out of the main loop for readability.

Don't Use Common Start Offset for UDQ Restart Variables

---

ExtraTests.cmake

When passing parameters to test runners based on Boost.Test we need to distinguish the parameters that are intended for the test case and those that are intended for the Boost.Test framework (e.g., `--run_test=`).

Separate Test Command Line Arguments from Runner Arguments

---

opm/parser/eclipse/EclipseState/TracerConfig.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/TracerConfig.cpp

Simulation based on non-default tracer units has been activated. 
`TracerConfig` keeps track of unit names and generates associated name tags for summary.

Some support for non-default tracer amount units.

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/WriteRestartFileEvents.hpp
src/opm/parser/eclipse/EclipseState/Schedule/WriteRestartFileEvents.cpp
tests/parser/WriteRestartFileEventsTests.cpp

This commit adds a new helper object
```
Opm::WriteRestartFileEvents
```
that identifies when a restart file output event occurs as well as the most recent output event prior to a particular report step.  We implement this facility in terms of a dense bit vector that wastes up to 63 bits of space.  Most of the logic is devoted to finding the most recent previous output event, of which the core routine is counting the number of leading zero bits in a 64 bit value.  We've elected to implement this in a portable manner using binary search, although most implementations provide efficient intrinsics for this operation, e.g., GCC's `__builtin_clzl`.  In C++20 we can use the new function `std::countl_zero()` from `<bit>`.

Add Utility to Track Restart Output Events

---

opm/io/eclipse/rst/udq.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.hpp
src/opm/io/eclipse/rst/udq.cpp
src/opm/output/eclipse/AggregateUDQData.cpp

`RstState` is a `struct` and should be forward declared as such. While here, also fix a shadowing variable warning and reduce the scope of another variable to eliminate a dead store.

Fix Mismatched Tags

---

opm/parser/eclipse/Parser/ParserKeyword.hpp
src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Parser/ParserKeyword.cpp
src/opm/parser/eclipse/Parser/raw/RawKeyword.cpp
src/opm/parser/eclipse/Parser/raw/RawKeyword.hpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/B/BRINE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SAVE
tests/parser/ParserTests.cpp
tests/parser/RawKeywordTests.cpp
tests/parser/integration/IntegrationTests.cpp
tests/parser/integration/ParseKEYWORD.cpp

This PR will refactor the configuration of the number of records in a deck keyword. The purpose of this is to support / enable some of the ongoing keyword validation effort; but it will also increase the parsing quality of some "difficult keywords".
Main result of this refactoring is an optional "min_size" : "XXX" setting.

Expand KeywordSize class

---

src/opm/output/eclipse/AggregateWellData.cpp

Make sure the cumulatives are correct also for wells which change between producer and injector.

Unconditionally store both production and injection cumulatives

---

opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.hpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
tests/parser/ThresholdPressureTest.cpp

Support EQLOPTS option IRREVER in THPRES. The simulator itself does still not support IRREVER - that must be trapped by the simulator.

Support EQLOPTS option IRREVER in THPRES keyword

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQToken.cpp
tests/parser/UDQTests.cpp
tests/test_AggregateUDQData.cpp

The UDQDefine::input_string() function will return normalized input which is
equivalent to the deck input string, but not necessarily identical. Normalizing
which might give rise to differences:
- All selectors/qualifiers in expressions like "WWCT '*'" are quoted.
- Whether to pad operators with space like "170 + FU_PAR10" or "170+FU_PAR10" is
hardcoded and independent of the space used in the input.
The motivation for this normalization is to simplify/enable identical output irrespective of whether this is a normal run or a restart run.
This will inuduce a data update due to changes in the ZUDL vector - cool if Equinor can verify this PR.

Normalise input data in UDQ definitions

---

opm/output/eclipse/EclipseIO.hpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/msim/test_msim.cpp

Report steps do not influence the `SUMTHIN` intervals and the special value
```
SUMTHIN
0.0 /
```
turns off the "thinning" process.  This refactoring introduces a new helper variable, `sumthin_active_`, which caches whether `SUMTHIN` is active (i.e., exists and has strictly positive value).
While here, also ensure that the ministep IDs have non-unit steps when `SUMTHIN` ends up skipping an output event.

Refactor SUMTHIN Implementation

---

src/opm/parser/eclipse/Parser/Parser.cpp
tests/parser/ImportTests.cpp

Closes #2599
Utilizes the function used for `INCLUDE` to process the path given to `IMPORT`.
Also added the scenario to one of the existing tests

Support PATHS in IMPORT keyword

---

opm/io/eclipse/EGrid.hpp
src/opm/io/eclipse/EGrid.cpp

- getting xyz values from EGrid file
- partially loading ZCORN array, loading only z-values associated with selected layer
- will be used by application resinsight, user interface discussed with Ceetron

Adding member function getXYZ_layer to EGrid

---

CMakeLists.txt
CMakeLists_files.cmake
examples/make_ext_smry.cpp
opm/io/eclipse/ESmry.hpp
opm/io/eclipse/ExtESmry.hpp
opm/io/eclipse/ExtSmryOutput.hpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/ExtESmry.cpp
src/opm/io/eclipse/ExtSmryOutput.cpp
src/opm/output/eclipse/Summary.cpp
test_util/convertECL.cpp
test_util/summary.cpp
tests/test_ExtESmry.cpp

The LODSMRY file name has been part of opm-common for nearly one year.
- converting from SMSPEC/UNSMRY to LODSMRY
- converting from binary LODSMRY to formatted FLODSMRY
I have tried to clean up all of these after the decision to go further with ESMRY instead of LODSMRY.  
I have also updated the summary application to support both SMSPEC/UNSMRY and ESMRY file format
A new class ExtESmry has been added. This class has more or less same design and functionality as ESmry, except this this class will work on ESMRY files.

cleanup after renaming from LODSMRY -> ESMRY

---

opm/parser/eclipse/Deck/ImportContainer.hpp
src/opm/parser/eclipse/Deck/ImportContainer.cpp

While here, also use a more efficient way of forming a `vector<double>` from a `vector<float>` source.

Add Include Guards to Protect From Multiple Inclusion

---

opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp

This is mostly for reporting purposes if the calling code knows that the values stored in the `GuideRate` container are in output units. The output layer, and particularly the [`Summary`](https://github.com/OPM/opm-common/blob/f89d3fe75a5ae322524ce7744e009c856526129e/opm/output/eclipse/Summary.hpp#L68) facility, expects that its input values are strictly SI.

Add Guiderate Value Accessor for SI Units

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/SPE1CASE1_RPTONLY.DATA
tests/msim/test_msim.cpp

This former restricts summary output events to coincide with the report step while the latter (`*O`) turns off this restriction and makes summary output for every timestep.

Add Support for RPTONLY and RPTONLYO

---

src/opm/output/eclipse/LoadRestart.cpp

Needed to initialise restarted runs.
This is adapted from #2507.

Load Active Constraints and Guide Rates at Group Level

---

cmake/Modules/UseOptimization.cmake

at some point cmake started adding -DNDEBUG to default release CXX flags.
thus we have to invert logic and use -UNDEBUG to remove instead.
note: this will uncover current issues in opm-simulators.
https://github.com/OPM/opm-simulators/pull/3462 fixed test_glift1
https://github.com/OPM/opm-models/pull/667 fixed SPE5CASE1_DYN

fixed: make WITH_NDEBUG cmake option work again

---

opm/parser/eclipse/EclipseState/Schedule/Action/ActionResult.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/State.hpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionResult.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/State.cpp
tests/parser/ACTIONX.cpp

Store the `Action::Result`instance when an action has evaluated to true. NB: This is quite naive - it will currently store the result when an action evaluates to true, if a new true value comes around it will be updated. If the action evaluates to false it will not be cleared (maybe it should?). 
Restart testing will reveal the correct semantics here.
Downstream: https://github.com/OPM/opm-simulators/pull/3482
This should update some elements in the ZWEL vector for models with ACTIONX - i.e. an update_data will be required

Store action results

---

CMakeLists_files.cmake
opm/io/eclipse/RestartFileView.hpp
opm/io/eclipse/rst/aquifer.hpp
opm/io/eclipse/rst/state.hpp
opm/parser/eclipse/EclipseState/Aquifer/Aquancon.hpp
opm/parser/eclipse/EclipseState/Aquifer/AquiferCT.hpp
opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.hpp
opm/parser/eclipse/EclipseState/Aquifer/Aquifetp.hpp
opm/parser/eclipse/EclipseState/EclipseState.hpp
src/opm/io/eclipse/RestartFileView.cpp
src/opm/io/eclipse/rst/aquifer.cpp
src/opm/io/eclipse/rst/state.cpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/Aquancon.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferCT.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/Aquifetp.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp

This PR adds support for creating the analytic aquifer objects
* `Opm::AquiferCT`
* `Opm::Aquifetp`
* `Opm::Aquancon`
* `Opm::AquiferConfig`
from information stored in the restart vectors
* `{I,S,X}AAQ`
* `{I,S}CAQ`
We add a new helper class
```
Opm::RestartIO::RstAquifer
```
which contain the same data members as the `*_data` structures of the analytic aquifer objects.  Those analytic aquifer objects then get friendship from the `*_data` structures in order to assign the private members from the corresponding restart information.  We finally add a gateway to `EclipseState` that consumes an `RstAquifer` instance and overwrites the internal `AquiferConfig` object when the restarted run contains analytic aquifers.
Update `RstState` constructor `API` to meet requirements of `RstAquifer`, …

Load Analytic Aquifer Objects From Restart File

---

src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WELL_PROBE
tests/2_WLIFT_MODEL5_NOINC.DATA
tests/test_Summary.cpp

This PR adds a guard to the `xGLIR` accumulation procedure.  In particular, we do not accumulate anything unless the ALQ type is gas rate.  We do however output a well-level value if the ALQ type is gas/liquid ratio.  This guard requires passing the `Schedule` object as part of the `fn_args`, so update the call sites accordingly.
With this in place we also implement the `WALQ` summary vector which essentially copies the simulation model's VFP input ALQ value to the summary output.

Implement WALQ Summary Vector

---

src/opm/io/eclipse/EclUtil.cpp

Use range-for instead of a counted loop.  While here, also mark a few objects as `const` to avoid inadvertent modifications.

Fix "Signed vs. Unsigned" Comparison Warning

---

examples/make_ext_smry.cpp

Making only the variable declaration and not the assignment conditional was stupid of me.

fixed: do not assign value to nonexistent variable

---

CMakeLists_files.cmake
opm/output/eclipse/AggregateActionxData.hpp
opm/output/eclipse/WriteRestartHelpers.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Actions.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/CreateActionRSTDims.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Actions.cpp
tests/parser/ACTIONX.cpp
tests/test_AggregateActionxData.cpp

The AggregateActionxData class makes extensive use of an instance variable `std::vector<int> actDims` - the content of this vector is partly related to the class `Actdims` - but not the same. To avoid confusion this PR renames the `actDims`instance to "something with rst" in the name.
While here the construction of the `AggregateActionxData` class rewritten slightly - mainly to reduce the visibility/lifetime of the `std::vector<int> action_rst_dims` instance. 
Not really important in any way - but a smell step to get better understanding/overview of the ACTIONX data in the restart file.

Rename actDims in AggregateActionxData

---

opm/io/eclipse/rst/state.hpp
src/opm/io/eclipse/rst/state.cpp
tests/msim/test_msim.cpp
tests/parser/ScheduleRestartTests.cpp
tests/parser/ScheduleTests.cpp
tests/rst_test.cpp
tests/test_AggregateUDQData.cpp
tests/test_rst.cpp

Preparation to parse keyword strings read from the restart file.
Downstream: https://github.com/OPM/opm-simulators/pull/3515

Add Parser argument to restart loader

---

src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp

This fixes a private testcase - but I have struggled to create a small test out of it.

Protect against unset optional when checking restart config

---

src/opm/output/eclipse/AggregateUDQData.cpp

Two different values were used for the size of IGPH restart vector - which lead to a segmentation fault.

Unconditonally use number of groups for IGPH restart vector

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
tests/parser/UDQTests.cpp

In current master we will automatically create a `UDQ ASSIGN` statement corresponding to a `UDQ UNITS` statement. That linking is removed in this PR.
Preparation for: https://github.com/OPM/opm-common/pull/2660

Remove uda autocreate

---

src/opm/output/eclipse/AggregateActionxData.cpp
tests/test_AggregateActionxData.cpp

This PR contains changes to add item to SACT index [4] that contains the time for the last triggering of an action plus a unit test for the same. 
The PR is ready for review and merge after comments and corrections / improvements based on comments from reviewers.

Add correct value for SACT[4] - equal to last time that the action was triggered

---

src/opm/parser/eclipse/Parser/ParserKeyword.cpp

Fixes: https://github.com/OPM/opm-common/issues/2637

Remove debug output from parser keyword generation

---

opm/io/eclipse/ESmry.hpp
opm/io/eclipse/SummaryNode.hpp
opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/io/eclipse/ERsm.cpp
src/opm/io/eclipse/ESmry.cpp
src/opm/output/eclipse/Summary.cpp

Update of class Opn::EclIO::ESmry, now supporting LGR related summary vectors
- local block data starting with 'LB'
- local well connections starting with 'LC'
- local well data starting with 'LW'
This PR is also fixing a bug related to inter-regions summary data.

Adding support for LGR related summary vectors

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/RestartConfigTests.cpp
tests/parser/integration/IOConfigIntegrationTest.cpp

Mind the first commit which removes a test which I am uncertain about. Our simplified treatment of the `SAVE`keyword is that we should output a normal restart file at the location of the `SAVE`keyword - without any interaction with the other keywords controlling restart output. Consider the situation:
```
DATES     -- 0010
1 'JAN' 2020 /
/
SAVE
DATES     -- 0011
1 'FEB'  2020 /
/
```
for this configuration flow will in master write restart file `CASE.X0011` at `1 'FEB' 2020`, the aim of the PR is rather to write the restart file `CASE.X0010` at `1 'JAN' 2020` instead. That is solved by the commit: https://github.com/joakim-hove/opm-common/commit/c7b1a76b3c5c405561c8affb6c5a5aa3f5ebaea2 - however it turns out that a complex integration with a combination of `RPTRST / RTPSCHED / SAVE` fails …

Assign SAVE keyword to previous report step

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQActive.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
tests/parser/ScheduleTests.cpp

This to enable calling `UDQ::eval_assign()` at the start of each report step - and use the new assignments as UDA values.
Downstream:  https://github.com/OPM/opm-simulators/pull/3513

Split udq eval in eval_assign() and eval_define()

---

tests/parser/EclipseGridTests.cpp

the parantheses confused the preprocessor and the wanted code did not execute at all.
quells the warnings that clearly spelled this out.

fixed: use curly-braces

---

python/cxx/deck.cpp
python/cxx/eclipse_config.cpp
python/cxx/eclipse_state.cpp
python/cxx/schedule.cpp

I am adding this PR as a preparation for some modifications of the Python interface in `opm-simulators`. The idea is to be able to do something like the following from Python:
```Python
from opm.io.parser import Parser
from opm.io.ecl_state import EclipseState
from opm.io.schedule import Schedule
from opm.io.summary import SummaryConfig
from opm.simulators import BlackOilSimulator
deck  = Parser().parse('SPE1CASE1.DATA')
state = EclipseState(deck)
schedule = Schedule( deck, state )
summary_config = SummaryConfig(deck, state, schedule)
sim = BlackOilSimulator( deck, state, schedule, summary_config  )
sim.step_init()
sim.step()
sim.step_cleanup()
```
By using `std::shared_ptr` as the holder type for these classes they can be shared with `opm.simulators`. For example, after the `schedule` …

Use std::shared_ptr as holder type for some Pybind11 classes

---

opm/common/utility/TimeService.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/ActionValue.hpp
src/opm/common/utility/TimeService.cpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ASTNode.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp
tests/parser/ACTIONX.cpp

[New math](https://www.youtube.com/watch?v=UIKGV2cTgqA):
When evaluating numerical month arguments in ACTIONX statements the values should be rounded before comparison - i.e.
```
MNTH = 4.25 
```
should evaluate to `true` for the month of April.

Round numerical month values to integer before comparison

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.cpp

We don't need the reason to test the well since it should be operable under both E and P condition to open up again.

return unique vector of names and not a map with wells and reason

---

src/opm/io/eclipse/rst/well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp

Without this we would end up with very wrong BHP limits for this case&mdash;e.g., upper BHP limit of 1 ATM for injectors&mdash;and this would obviously mean that restarted runs do not converge.
While here, also correct a couple of misprints.
Thanks to @tskille for providing a test case based on [opm-tests/model1/BASE_MODEL_1.DATA](https://github.com/OPM/opm-tests/blob/563b9d2a529e6258f1f2091953615aa681e49a16/model1/BASE_MODEL_1.DATA).

Set Appropriate Restart BHP Limit for History Wells

---

opm/output/eclipse/VectorItems/group.hpp
src/opm/output/eclipse/AggregateGroupData.cpp

This pull request contains improvements of the Eclipse-compatible restart file. The improvements are:
1. Output of Guiderate control code for general guiderate input.
2. Output of correct values for IGRP (WInjActiveCMode, GInjActiveCMode, GConInjeWInjCMode and GConInjeGInjCMode)
The pull request is ready for review and merge after improvements based on comments from reviewers.

Improve Eclipse-compatible restart file. Output correct Guiderate control and FIELD level control

---

src/opm/parser/eclipse/Deck/FileDeck.cpp

Use Opm::prximate instead of fs::proximate. Fixes compilation issue like
```
opm-common/src/opm/parser/eclipse/Deck/FileDeck.cpp: In member function ‘void Opm::FileDeck::dump_shared(std::ostream&, const string&) const’:
opm-common/src/opm/parser/eclipse/Deck/FileDeck.cpp:331:44: error: ‘proximate’ is not a member of ‘fs’
std::string include_file = fs::proximate(block.fname, output_dir);
```

Fix compilation with g++-7 lacking fs::proximate

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellTestConfig.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestConfig.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WTEST.cpp

The WTEST keyword has ovewrite semantics - not update semantics.
Downstream: https://github.com/OPM/opm-simulators/pull/3559

WTEST - consecutive keywords overwrite instead of updating

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.cpp
tests/parser/WTEST.cpp

This PR changes the semantics of opening wells which are managed by WTEST. The data structure used to manage the state of wells closed due to WTEST manages a bool flag closed, which is set to false when the well is opened. This affects how the method counts the number of wells in the container. Assuming the chain of events is as follows:
1. Well "W1" is closed with WTEST: A new entry for well "W1" is added to the `WellTestState` container with the `closed` flag set to `true`.
2. Well "W1" is reopened: We find the "W1" well in the container and flip the `closed` flag to `false`.
Now - the point is that the method counting wells does not differentiate between closed and open wells, so in this we will get one well even after the well has been opened again. With this PR the count method …

WellTestState: will only count actually closed wells

---

opm/parser/eclipse/EclipseState/EclipseState.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp

Mostly a convenience method that avoids resorting to ugly `const_cast<>` expressions in client code.

Support Resetting ACTNUM At EclipseState Level

---

opm/io/eclipse/rst/group.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/io/eclipse/rst/group.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp

A group may have limits but no active control at the time of restart.
While here, also support restoring a limited `ExceedAction` value from the restart file.

Restore Group Level Controls if Limits Exist

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.cpp
tests/parser/WTEST.cpp

Updated comment:
```C++
/*
The purpose of this container is to manage explicitly *closed wells*,
since the class has no relation to the set of of wells defined in the
Schedule section the concept of open wells and totally unknown wells is
slightly murky:
well_is_closed("UNKOWN_WELL") -> false
This implies that we have not explicitly closed a well with name
'UNKNOWN_WELL', but since we do not know whether the well is at all
defined it does not make sense to extrapolate to:
well_is_open("UNKNOWN_WELL") -> true.
That is the reason we do not have any xxx_is_open() predicates.
*/
```

Remove WellTestState::xxx_is_open() predicates

---

opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp

Needed to properly report group-level injection guide rates in the summary file.
Forgotten in PR #2605 (commit 2a374fc53).

Add Guide Rate Value Accessor for SI Units

---

cmake/Modules/OpmSatellites.cmake

Upstream of https://github.com/OPM/opm-simulators/pull/3604

use -e when passing exename to test drivers

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

This handles the case where the `SUMTHIN` and/or `RPTONLY` keywords are given in the `SUMMARY` section instead of (or in addition to) the `SCHEDULE` section.

Initialize RPTONLY/SUMTHIN Settings From SUMMARY Section

---

opm/parser/eclipse/EclipseState/Schedule/GasLiftOpt.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/GasLiftOpt.cpp
tests/test_Summary.cpp

This PR contains two substantial changes:
1. In the case gas lift optimization is enabled (and the ALQ setting is GRAT) we fetch the value from WGLIR and use that also for WALQ.
2. If the ALQ setting is IGLR we calculate WGLIR = WLPR * ALQ - where the ALQ/IGLR setting comes directly from the WCONPROD item.
NB: As pointed out by @bska in a comment the UNITS to use for the `WALQ` summary output is not trivial. The current approach is that *if at least one well is configured with gas lift optimization* - we use the unit of `measure::gas_surface_rate` - otherwise we use unit dimensions.

Use gas lift rate value for WALQ output when gas lift rate optimization is in action

---

opm/output/eclipse/VectorItems/group.hpp
src/opm/output/eclipse/AggregateGroupData.cpp
tests/MOD4_TEST_IGRP-DATA.DATA
tests/test_AggregateGroupData.cpp

This pull request contains code to output the sequence number of nodes according to the sequence entered with the BRANPROP keyword.  This sequence number is added for the groups that are nodes in the external network defined by the BRANPROP and NODEPROP keywords.
The pull request is ready for review and merge after corrections / improvements based on feedback from reviewers.
The pull request has been checked for unit test in opm-common (ctest) and make check in opm-simulators. The only error discovered is for test 131 (opm-simulators) and is related to IUAP - which should not be affected by this PR.

Add item IGRP[NWGMAX + 39] to the Eclipse-compatible restart file

---

src/opm/output/eclipse/LoadRestart.cpp

The `xLPT` curves should not start at zero in a restarted simulation run.  This commit initialises the cumulative liquid production volume using the value
```
xOPT + xWPT
```
with the individual terms taken from `XWEL` or `XGRP` as appropriate.
Thank you to @tskille for identifying the issue and suggesting the "OPT + WPT" solution.

Ensure Continuous Cumulative Liquid Production On Restart

---

opm/output/eclipse/VectorItems/network.hpp
src/opm/output/eclipse/AggregateNetworkData.cpp

In preparation of adding initial support for restarting simulations featuring the extended network model.

Identify Extended Network Model Node Name Item in ZNODE

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.hpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp

Fix for: https://github.com/OPM/opm-common/issues/2812

Avoid use of generated header S.hpp in header file

---

src/opm/io/eclipse/rst/state.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

If constraints are applied at the field level, e.g., through the `GCONINJE` keyword, then we must incorporate those constraints into FIELD when restarting a simulation run.  This PR takes a step in this direction by explicitly loading the `*GRP` array entries pertaining to FIELD and special casing
```
Schedule::addGroup(rst_group, time)
```
to look for `rst_group.name == "FIELD"`.  In that case, we update the injection and production properties of the existing FIELD group as needed.
While here, also update the diagnostic message of `Group::delGroup()` to report the name of the purported parent group.  This is an aid to analysing rare conditions.

Load Field-Wide Constraints From Restart File

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
tests/parser/ACTIONX.cpp

If well rates have been adjusted with e.g. WCONHIST in an ACTIONX block we need to inform the simulator on the way back.

Register well as "touched" by WCONHIST and WCONINJE in ACTIONX block

---

opm/parser/eclipse/EclipseState/Tables/FlatTable.hpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/parser/eclipse/EclipseState/Tables/Tables.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GRAVITY
tests/parser/TableManagerTests.cpp

This commit activates support for the `GRAVITY` keyword.  We treat this as a fallback alternative to the `DENSITY` keyword and simply convert `GRAVITY` data to `DENSITY` data on input.  This means that fluid densities at surface conditions will be reported to the `.INIT` file as if they were entered using the `DENSITY` keyword.

Support GRAVITY As Fallback for DENSITY

---

opm/parser/eclipse/EclipseState/EclipseState.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
tests/parser/integration/TransMultIntegrationTests.cpp

Better name - first small PR in an effort to support MULTXYZ keywords in the ACTIONX section.
Downstream: https://github.com/OPM/opm-simulators/pull/3669

Rename EclipseState::apply_geo_keywords -> apply_schedule_keywords

---

opm/parser/eclipse/EclipseState/EclipseState.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp

This is required in order to broadcast runtime updated transmissibility multipliers.

Add mutable EclipseState::getTransMult()

---

opm/parser/eclipse/Deck/DeckValue.hpp
python/cxx/deck_keyword.cpp
python/opm/io/deck/__init__.py
python/tests/test_parser.py
src/opm/parser/eclipse/Deck/DeckKeyword.cpp
src/opm/parser/eclipse/Deck/DeckValue.cpp

Continues the work in #2781. The plan is to split that PR up into two PRs, where this is the first and the second, to be  submitted later, will handle insertion of keywords into the schedule at given report steps.
This PR adds support for UDA values items when constructing `DeckKeyword`s from `DeckValue`s. This is needed when constructing `DeckKeyword`s from Python. For example `WCONPROD` has an UDA value argument for the oil rate:
```python
from opm.io.parser import Parser
from opm.io.deck import DeckKeyword
from opm.io.ecl_state import EclipseState
from opm.io.schedule import Schedule
deck  = Parser().parse('SPE1CASE1.DATA')
state = EclipseState(deck)
schedule = Schedule( deck, state )
report_step = 3
oil_target = 30000  # stb/day
well_name = "PROD"
well_status = "OPEN"
control_mode = …
```

Add support for UDA values in DeckKeyword constructor.

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Action/SimulatorUpdate.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

Add struct SimulatorUpdate which is used to communicate generic "values" back to the simulator which must be updated after a ACTIONX has run. Currently the struct only contains the wells which need to get rates/status reinitialized in the simulator, but more properties are coming.

Add struct SimulatorUpdate to transport results back to simulator

---

src/opm/parser/eclipse/EclipseState/EclipseState.cpp

Use `OpmInputError` instead of `std::logic_error` in order to capture incorrect restart config.
Improves: https://github.com/OPM/opm-common/pull/2759#issuecomment-966099869

Use OpmInputError for restart input problems

---

CMakeLists_files.cmake
GenerateKeywords.cmake
opm/parser/eclipse/Deck/Deck.hpp
opm/parser/eclipse/Deck/DeckSection.hpp
opm/parser/eclipse/Deck/DeckView.hpp
src/opm/parser/eclipse/Deck/Deck.cpp
src/opm/parser/eclipse/Deck/DeckSection.cpp
src/opm/parser/eclipse/Deck/DeckView.cpp
tests/parser/DeckTests.cpp
tests/parser/WellTests.cpp

The `Deck` has always had a base class `DeckView(Internal)` which only holds to iterators and not the actual keywords. The base view class has been a private implementation detail - which I frankly never really understood/liked. With this PR the `Deck`does not have any base class any longer, and a new class `DeckView` is added. The `DeckView` class is based on `std::vector<std::reference_wrapper<DeckKeyword>>` where the real keywords are in the `Deck`.
This PR does not change the API in any way, but the plan is to also clean up/simplify the deck api in subsequent PR's 
The `DeckView` makes use of my first custom iterator - feel free to slaughter it!

Refactor Deck and DeckView class hierarchy

---

CMakeLists_files.cmake
opm/io/eclipse/rst/network.hpp
opm/io/eclipse/rst/state.hpp
src/opm/io/eclipse/rst/network.cpp
src/opm/io/eclipse/rst/state.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleRestartTests.cpp

This PR adds a new helper class, `RstNetwork`, that loads the raw data representing the extended network model from restart vectors `IBRAN`, `INODE`, `RNODE`, and `ZNODE`.  We support loading the information that is currently output to those restart vectors, but those do not include every option supported by the input keywords `BRANPROP` and `NODEPROP`.
The `RstNetwork` type supports querying whether or not the extended network model is active and, if so, to get iterable collections of branches and nodes that are geared towards constructing `ExtNetwork` objects.

Support Loading Extended Network Model From Restart

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
python/cxx/deck.cpp
python/cxx/schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Continues the work in #2821 of splitting PR #2781 into two parts (this is the second part).
Adds support for adding keywords to the SCHEDULE section after the deck has been read from file from Python. The plan is to be able to update/change the SCHEDULE from Python by adding a keyword block at a certain report step. For example:
```python
from opm.io.parser import Parser
from opm.io.deck import DeckKeyword
from opm.io.ecl_state import EclipseState
from opm.io.schedule import Schedule
from opm.io.summary import SummaryConfig
from opm2.simulators import BlackOilSimulator
deck  = Parser().parse('SPE1CASE1.DATA')
state = EclipseState(deck)
schedule = Schedule( deck, state )
parser = Parser()
active_unit_system = deck.active_unit_system()
default_unit_system = deck.default_unit_system() …
```

Implement support for adding keywords to the schedule from Python.

---

cmake/Templates/opm-project.pc.in

This hides them for shared libraries that do not need them.
Should fix the following lintian warnings:
```
W: libopm-common-dev: pkg-config-references-unknown-shared-library usr/lib/x86_64-linux-gnu/pkgconfig/opm-common.pc -lpython3.7m (line 12)
W: libopm-common-dev: pkg-config-references-unknown-shared-library usr/lib/x86_64-linux-gnu/pkgconfig/opm-common.pc -lstdc++fs (line 12)
W: libopm-common-dev: pkg-config-references-unknown-shared-library usr/lib/x86_64-linux-gnu/pkgconfig/opm-common.pc -lgomp (line 12)
W: libopm-common-dev: pkg-config-references-unknown-shared-library usr/lib/x86_64-linux-gnu/pkgconfig/opm-common.pc -lboost_system (line 12)
W: libopm-common-dev: pkg-config-references-unknown-shared-library usr/lib/x86_64-linux-gnu/pkgconfig/opm-common.pc -lcjson (line 12)
``` …

List link dependencies as private.

---

CMakeLists.txt

Currently, an rpath to the install directory of `libopmcommon.so` is generated for `libopmcommon_python.so`, but a similar rpath is not added to the `libopmcommon.so` in the build directory. It is useful to be able to use the build directory libraries when not compiling with `-DOPM_INSTALL_PYTHON` or when developing.
This PR fixes issue #2843 for me.

Add rpath to libopmcommon.so in the build directory.

---

CMakeLists.txt
CMakeLists_files.cmake

Small change: register a lists of tests the "normal" way.

Register ecl io tests using the file list in CMakeLists_files.cmake

---

opm/output/data/Cells.hpp
src/opm/output/eclipse/RestartIO.cpp

Tracer restart 3D vectors should have an addition header 'ZTRACER' with name and units for the tracer data coming in the next restart vector. This PR is a small preparation to output the 'ZTRACER' vector.
Add restart output type `RESTART_TRACER_SOLUTION`. With this PR there is absolutely no change, but when this and accompanying PR in opm-simulators is merged the remaining work can be done under the hood in opm-common.
Downstream: https://github.com/OPM/opm-simulators/pull/3702

Add restart output type RESTART_TRACER_SOLUTION

---

opm/parser/eclipse/EclipseState/Runspec.hpp
opm/parser/eclipse/EclipseState/Schedule/Network/Balance.hpp
src/opm/output/eclipse/CreateDoubHead.cpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Network/Balance.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ScheduleTests.cpp

Create valid default NETBALAN object.
~~Data update is required because we now output real default values for NETBALAN - also in the case when it is not in use, compared to previously where we just output 0.~~
Update 2: For the NETBALAN keyword there are three different "states":
1. The keyword is entered in the deck - read values from deck, all good.
2. The network model is enabled, but no NETBLAN keyword in deck: One default initialization
3. The network model is not enabled: A second default initialization
The alternatives 2 & 3 are implemented in new function:
```C++
Balance::Balance(bool network_active, const Tuning& tuning)
: calc_mode(CalcMode::TimeStepStart)
, calc_interval(0)
, m_thp_tolerance( NB::THP_CONVERGENCE_LIMIT::defaultValue )  
, m_thp_max_iter( …
```

Netbalan default

---

opm/parser/eclipse/Deck/DeckKeyword.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

I am in the process of cleaning up parts of the deck API. The codebase has literally hundreds of calls like:
```C++
if (keyword.name() == "XYZ") {  
....
}
```
in this PR I suggest replacing that with (only a couple of callsites to demonstrate):
```C++
if (keyword.is<ParserKeywords::XYZ>()) {
....
}
```
good idea?

Suggestion: use keyword.is<T>() instead of checking name?

---

opm/parser/eclipse/Parser/ParserItem.hpp

This should cut down quite significantly on coverity warnings

Initialize values used for overloading in ParserItem

---

opm/parser/eclipse/Deck/DeckView.hpp

Add missing include for unordered_map.

---

opm/output/eclipse/InteHEAD.hpp
opm/output/eclipse/VectorItems/connection.hpp
opm/output/eclipse/VectorItems/group.hpp
src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/InteHEAD.cpp

The important point is the resizing of the vectors - that is indirectly handled through the INTEHEAD updates (already merged). Personally I like mentioning this tracer data explicitly in the AggregateXXXX functions - but I agree it is not necessary and will not argue very hard.

Pad XCON, XGRP and RSEG vectors with tracer zero

---

src/opm/output/eclipse/RestartIO.cpp

The tracers have an appended 'F' to the name - for some reason.

Look up tracer name without trailing 'F' in restart writer

---

opm/parser/eclipse/EclipseState/TracerConfig.hpp
tests/parser/TracerTests.cpp

Tracers can be initialized in many ways - use `std::optional<>` to ensure that we do not continue with invalid input
Downstream: https://github.com/OPM/opm-simulators/pull/3707

Use std::optional<> for tracer details

---

opm/output/eclipse/InteHEAD.hpp
opm/output/eclipse/VectorItems/intehead.hpp
src/opm/output/eclipse/AggregateNetworkData.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/InteHEAD.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NETBALAN
tests/test_AggregateNetworkData.cpp

This pull request contains corrections to the output of information for external networks to the Eclipse compatible restart file. 
1. An integer flag that indicates whether an active network is present in the model or not
2. Output of default NETBALAN vallues if an active network is present but the NETBALAN keyword is not used.

Corrections to output of network data to Eclipse compatible restart file

---

opm/parser/eclipse/EclipseState/TracerConfig.hpp

The restart solution field tracer arrays have a trailing 'F' in the name - i.e. if a tracer is registered with name "S61" it will be "S61F" in the restart file. Don't know the full domain model here - so current implementation is just to append an 'F' - with this PR that is made very explicit.

Add tracer config function fname() == name + "F"

---

CMakeLists.txt
test_util/arraylist.cpp

simple program tOPMhat lists arrays (name, type and size) for a specified eclipse output file.

add program arraylist

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/Parser/ParseContext.cpp

Produces:
```
Error: The keyword GRID is not supported in the ACTIONX block
Error: Problem with keyword GRID
In opm-tests/actionx/ACTIONX_COMPLUMP.DATA line 355
The keyword GRID is not supported in the ACTIONX block
```
which is at least an improvement on: https://github.com/OPM/opm-common/issues/2893

Improve error message for unsupported ACTIONX keyword

---

src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp

NEXT is an alias for NEXTSTEP and does work with the ACTIONX when tested locally.

Update ActionX.cpp with NEXT

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Schedule/Action/WGNames.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/WGNames.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

This PR addresses the situation where a well is introduced/defined in ACTIONX and then manipulated with e.g. `WCONPROD` in the normal SCHEDULE section:
```
ACTIONX
...
/
WELSPECS
'NEW_WELL' .... /
/
ENDACTIO
TSTEP     --The ACTIONX must trigger True at some point here in order to define the well. 
100*30 /
WCONPROD
'NEW_WELL' .... /
/
```
In current master this fail with an exception when reaching `WCONPROD` in the Schedule construction. With this PR it will register that `NEW_WELL` will (hopefully ...) come with ACTIONX and only give a warning at the first pass of `WCONPROD`.

Actionx welspecs

---

src/opm/output/eclipse/WriteRFT.cpp

These render Flow's RFT files much more difficult to open in post-processing software such as ResInsight.

Don't Write RFT Records for Wells With No Connections

---

test_util/compareECL.cpp

-x options should not have any arguments.

fixing -x option for compareECL program

---

tests/rst_test_driver.sh
tests/rst_test_driver2.sh

Putting options at the end of the command makes the rst_deck_* tests fail on BSD systems, such as macOS, since opmhash uses getopt().

Fix driver, as POSIX or BSD getopt() stops on first non-option argument.

---

test_util/EclRegressionTest.hpp

When running the same data set twice it is unlikely that these keywords will give results that can be compared with the program compareECL. 
These keywords are not supported by Flow but some of these are commonly used by the commercial simulator Eclipse. 
In example the following keywords are requested with the NORNE_ATW2013 in opm-tests
```
"ELAPSED", "TCPUDAY", "TCPUTS", "TELAPLIN"
```
Description of added blacklisted keywords
```
ELAPSED - Elapsed time in seconds.
TCPUDAY - CPU time per day (or hour in lab units).
TCPUTS - CPU time per timestep in seconds.
TELAPLIN - Elapsed time per linear iteration in seconds.
TCPUH - Total CPU time for each gradient calculation (Gradient Option).
TCPUHT - Total CPU time for all gradient calculations (Gradient Option).
TCPUSCH - Total CPU time used …
```

update list of blacklisted keywords

---

src/opm/io/eclipse/ESmry.cpp

- SMSPEC/UNSMRY files from Eclipse normally have a number of empty keys
- ESmry::keywordList() - no longer return vectors with empty elements

ESmry - Ignore empty keys

---

src/opm/input/eclipse/EclipseState/InitConfig/Equil.cpp

This is more self-documenting than  numeric item indices.  While here, also switch to constructing the `EQUIL` record in place instead of forming a temporary and moving it into the vector.

Switch to Using Named Items For Extracting EQUIL Keyword Data

---

src/opm/output/eclipse/AggregateGroupData.cpp

The maximum supply of lift gas and/or the maximum total gas flow rate of a group may be defaulted in the context of lift gas optimisation.  In that case, the `std::optional<>` objects will be empty and we must not access the contained object through the `value()` member function.

Don't Access an Empty Optional Object

---

src/opm/output/eclipse/Summary.cpp

These quantities are reported in surface volume gas flow rate units.

Fix Unit of Measure for Dissolved Gas Flow Rates

---

src/opm/input/eclipse/EclipseState/Aquifer/NumericalAquifer/SingleNumericalAquifer.cpp
tests/parser/AquiferTests.cpp

The cell permeability used to compute aquifer to reservoir transmissibilities now take into account MULTX etc. in the cell.

Add permeability multiplier for connection between reservoir and aquifer

---

opm/input/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/input/eclipse/EclipseState/EclipseState.cpp
src/opm/input/eclipse/EclipseState/Grid/FieldPropsManager.cpp

This is a quick fix just fixing the immanent problem. 
The problem that occurs is the following. After loadbalancing the FieldPropsManager only has a non-nullptr to the FieldProperties on the process with rank=0. Therefore most of the calls to it will segfault. This has not been problem before changeset 2921838895. We did not make any calls to e.g. FieldProperties::apply_schedule_keywords during a simulation.
Now we do via  [eclproblem.hh#L1021-L1022](/OPM/opm-simulators/blob/3e4e62bc4f6f6f8a02eb2d2e4976dc2e2d956313/ebos/eclproblem.hh#L1021-L1022))
Closes #2922.
An open question is whether we are actually expecting field properties apart from the transmissibility multipliers to be changed 
during EclipseState::apply_schedule_keywords. Those will get lost! Only for the multipliers the …

Fixes parallel segfault for MULTFLT 

---

opm/output/eclipse/AggregateGroupData.hpp
opm/output/eclipse/VectorItems/group.hpp
opm/output/eclipse/VectorItems/well.hpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/output/eclipse/Summary.cpp

This commit ensures that the field, group, and well level cumulative production curves of solution/free oil and gas are continuous in a restarted simulation run.
Thanks to Torbjørn Skille for identifying the appropriate locations in `XGRP`/`XWEL` for outputting these items.

Save and Reload Free/Solution Gas/Oil Cumulatives in Restart

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SALTVD

According to eclipse/flow manuals, saltvd input should be lb/stb (Salinity in Units.hpp), not Density (lb/ft3).

Fix SALTVD unit

---

opm/io/eclipse/EclUtil.hpp
src/opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/input/eclipse/Schedule/SummaryState.cpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/EclUtil.cpp
tests/parser/SummaryConfigTests.cpp
tests/test_EclIO.cpp

This PR adds new nodes pertaining to the inter-region flows to the summary configuration keyword list.  We combine the pair of region IDs into a single `NUMS` value as part of creating the node. We also split inter-region nodes into a "supported" and an "unsupported" set, with the former containing the oil, gas, and water keywords.
To this end introduce new helper functions
```C++
int EclIO::combineSummaryNumbers(int, int);
std::tuple<int, int> EclIO::splitSummaryNumber(int);
```
that know about the relation
```
combined = n1 + 32768*(n2 + 10)
```
for one-based IDs `n1` and `n2` (typically region IDs).  Finally, register inter-region flow cumulatives for `SummaryState` as this is needed for correct accumulation.

Make SummaryConfig Nodes for Inter-Region Flows 

---

opm/input/eclipse/EclipseState/Tables/TableManager.hpp

Otherwise, the equality operators for a default-constructed `TableManager` object, mostly used in unit tests, will depend on uninitialised values.
Thanks to [at]akva2 for the initial clue to the underlying cause.

Ensure Proper Initialisation of All TableManager Member

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SURFCAPD

Otherwise, we get "missing keyword" errors at the parsing stage.

Ensure That Keyword Name Matches Filename

---

src/opm/input/eclipse/Schedule/UDQ/UDQSet.cpp
src/opm/output/eclipse/AggregateGroupData.cpp

This is needed for libfmt >= 8.1.0 as in that version the
cast to int was removed from inside the fmt::format call and an
assertion will fail:
```
In file included from /usr/include/fmt/format.h:48,
from /build/opm-common-2021.10/src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.cpp:22:
/usr/include/fmt/core.h: In instantiation of 'constexpr fmt::v8::detail::value<Context> fmt::v8::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; fmt::v8::detail::type <anonymous> = fmt::v8::detail::type::custom_type; T = Opm::UDQVarType&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]':
/usr/include/fmt/core.h:1855:77:   required from 'constexpr fmt::v8::format_arg_store<Context, Args>::format_arg_store(T&& ...) …
```

Cast enum classes to int when used in fmt::format.

---

msim/src/msim.cpp
opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

This PR is just a small preparation for some more PYACTION related updates.
At some stage the `Schedule` implementation was heavily rewritten in order to better support ACTIONX. The plan now is to update the execution of PYACTION to use the same mechanism - i.e. apply a bunch keywords and not call methods on the `Schedule`object when something should be changed.
Yes - I know it is but ugly; but the execution model of flow/eclipse is so complex that I think this is the only viable solution. That said - there is nothing here preventing a more elegant approach when/if that is possible. 
Downstream: https://github.com/OPM/opm-simulators/pull/3782

Pyaction applyaction

---

src/opm/input/eclipse/Schedule/Action/PyAction.cpp

Otherwise, we get build errors of the form "no declaration matches"

Update Signature for PyAction::run When !EMBEDDED_PYTHON

---

CMakeLists_files.cmake
examples/msim.cpp
msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
opm/input/eclipse/Schedule/Action/Actions.hpp
opm/input/eclipse/Schedule/Action/PyAction.hpp
opm/input/eclipse/Schedule/Action/State.hpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/SummaryState.hpp
python/cxx/summary_state.cpp
src/opm/input/eclipse/Schedule/Action/Actions.cpp
src/opm/input/eclipse/Schedule/Action/PyAction.cpp
src/opm/input/eclipse/Schedule/Action/State.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
tests/EMBEDDED_PYTHON.DATA
tests/msim/MSIM_PYACTION.DATA
tests/msim/action_count.py
tests/msim/test_msim.cpp
tests/msim/test_msim_ACTIONX.cpp
tests/msim/test_msim_EXIT.cpp
tests/parser/ACTIONX.cpp
tests/parser/EmbeddedPython.cpp

Previously the PYACTION return value was ignored, and the PYACTION would run for every timestep irrespective of the result. With this PR the return value is acknowledged.
Downstream: https://github.com/OPM/opm-simulators/pull/3794

Pyaction handle return

---

opm/input/eclipse/Schedule/Action/ASTNode.hpp
src/opm/input/eclipse/Schedule/Action/ASTNode.cpp
src/opm/input/eclipse/Schedule/Action/ActionAST.cpp
src/opm/input/eclipse/Schedule/Action/ActionParser.cpp
tests/parser/ACTIONX.cpp

Allow ACTIONX keywords with empty conditions, these ACTIONX keywords will always
evaluate to false. Main motivation is to facilitate dummy keywords for PYACTION.

Empty actionx

---

CMakeLists.txt

If cmake is run with `-DOPM_ENABLE_EMBEDDED_PYTHON=ON DOPM_ENABLE_PYTHON=OFF` a cmake error was produced because the library would depend on python/cxx/builtin_pybind11.cpp which would not be generated.
We fix this by doing the Python sanity check (deactivate embedded python if python is disabled) before running source_hook that adds the dependency.
Closes #2940

[cmake][bugfix] Test python/embedded python flags before source_hook.

---

CMakeLists.txt
python/setup.py.in

It is used verbatim in setup.py in the list that specifies the linker flage. Hence it needs to comma separted instead of using a   semicolon as separator.
Closes #2947

[bugfix] Make opm-common_PYTHON_LINKAGE a comma separated list.

---

python/setup.py.in

CC is the C compiler. CXX is the C++ compiler. Setuptools will use the C++ compiler for C++ code. Hence it is vital to set that
correctly. If it is not set the default C++ compiler will be used. (LDSHARED will be ignored for C++ as well as the first argument of compiler.linker_so)
Unfortunately it will use the first string as the CXX compiler and hence we need to strip ccache. Fortunately setuptools uses CC for the compilation and that works with gcc as well.
Closes #2952 
I just could not help fixing this for setuptools (for my own sanity which was nearly lost in this embarrassingly long process).

[python] Use correct C++ compiler for linking.

---

opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/R/REGION2REGION_PROBE
src/opm/input/eclipse/share/keywords/001_Eclipse300/R/REGION2REGION_PROBE_E300
tests/parser/SummaryConfigTests.cpp

This PR adds a new query
```C++
std::set<std::string> SummaryConfig::fip_regions_interreg_flow() const;
```
that retrieves the set of FIP array names (e.g., `FIPNUM` and `FIPXYZ`) that are associated to any inter-region flow summary keywords.  This query method returns an empty set if there are no inter-region flow summary keywords.
We also extend the `SummaryConfig` support for inter-region flows to be aware of those user-provided FIP arrays.  In other words, we now recognize, e.g., that
```
ROFT_XYZ
```
is the cumulative inter-region oil flow volume corresponding to regions defined by the `FIPXYZ` region definition.

Recognize Non-Default FIP Arrays for Inter-Region Flow Summary Keywords

---

src/opm/io/eclipse/ExtSmryOutput.cpp

This will give consistent summary key names for inter-region summary vectors in ESMRY file.

Split summary number for RXFT vectors in ESMRY file

---

CMakeLists_files.cmake
opm/output/data/InterRegFlow.hpp
opm/output/data/InterRegFlowMap.hpp
opm/output/eclipse/Summary.hpp
src/opm/output/data/InterRegFlowMap.cpp
src/opm/output/eclipse/Summary.cpp
tests/test_data_InterRegFlow.cpp
tests/test_data_InterRegFlowMap.cpp

This PR adds backing objects for creating and accumulating inter-regional flow rates on the simulator side and the communicating those flow rates to the parallel I/O rank for summary output purposes (e.g., as summary vectors `ROFT`, `RGFRG`, or `RWFT+`).
The bottom layer is a view over a linear range of elements which client code populates with signed connection flow rates.  Those linear ranges are then aggregated into a larger CSR-like mapping structure that pertains to a single region definition (e.g., `FIPNUM`).  These ranges support the `MessageBuffer` protocol for inter-process communication.  On the I/O side, client code will request elements pertaining to individual region ID pairs as needed.

Add Protocol Objects for Linearising and Accumulating Inter-Region Flows

---

src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/output/eclipse/Summary.cpp

If a well is entered in `WCON{INJE,PROD}` as status `'SHUT'` but later activated in `WELOPEN`, we must take care to record this status change in the well's internal `has_produced` or `has_injected` flags as appropriate.  Otherwise, the counts of "abandoned" wells (summary vectors `[FG]MW[IP]A`) will not be correct.
This PR fixes a problem that was identified in a client model.
While here, also correct a misspelling of "abandoned".

Update Injected/Produced Flag When Processing WELOPEN

---

src/opm/output/eclipse/Summary.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

This PR adds the glue code necessary to extract the pertinent flow rate values from an inter-region flow rate map and then accumulating those into the `SummaryState`.  We multiply with the timestep size if we're computing a cumulative total volume.

Add Summary Evaluation Functions For Inter-Region Flows

---

src/opm/output/data/InterRegFlowMap.cpp

Necessary to compile with clang.

Add missing <string> include for std::to_string().

---

src/opm/output/data/InterRegFlowMap.cpp

A lambda expression can read the value of a variable without capturing it if the variable
> has `const` non-volatile integral or enumeration type and has been initialized with a constant expression
Clang issues a diagnostic if such variables are captured so drop the `sz` from the explicit list of captures here.

Don't Needlessly Capture Constant Buffer Size

---

opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/VFPProdTable.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/VFPProdTable.cpp
tests/parser/TableManagerTests.cpp

A possible alternative to: #2966 
Downstream: https://github.com/OPM/opm-simulators/pull/3831

Convert default ALQ type to GRAT when gaslift optimization is active

---

src/opm/input/eclipse/EclipseState/Aquifer/Aquancon.cpp

it gives slight more information than simple `_Map_base::at`. 
we can also just not handling this aquifer like it does not exist. 
The PR basically does not change the simulation behavoir of the master branch, which terminates running by throwing with `_Map_base::at`.  With this PR, it throws with a little more information.

throw when there is no connection for analytical aquifer

---

CMakeLists.txt

Compiling will fail at a very late stage if python is enabled but setuptools not found and might cause surprises for novice users. It seems much better to issue an error during CMake with a meaningful error message. Might prevent some support issues in the future.
Inspired by @loveduah1 in OPM/opm-simulators#3822

[cmake] Send error for OPM_ENABLE_PYTHON=ON without setuptools

---

CMakeLists.txt
jenkins/build-opm-module.sh

Instead of checking whether this is Debian system we query the sitepackages path from Python. If it matches dist-packages then
we use dist-packages if we install below /usr, otherwise site-packages is used.
This will work on Debian as before, but also on other system that decide to use the same approach.

[python] Use dist-packages if it is used for Python's sitepackages

---

src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
tests/parser/data/integration_tests/IOConfig/RPT_TEST2.DATA

The commercial simulator does not support parenting a well directly to the `FIELD` group and Flow in multiple locations implicitly assumes that no well is parented directly to `FIELD` either.
With this PR we detect this situation at the parser stage and stop reading the input file.  In this case, we issue a diagnostic message of the form
```
Error: Problem with keyword WELSPECS
In SPE1CASE1.DATA line 384
Wells cannot be parented directly to 'FIELD'.
Wells entered with disallowed 'FIELD' parent group:
* PROD
* INJ
Error: Unrecoverable errors were encountered while loading input
```

Disallow Wells Parented Directly to FIELD

---

ExtraTests.cmake

when using as super-build these differ

fixed: use PROJECT_BINARY_DIR, not CMAKE_BINARY_DIR

---

cmake/Modules/UseVersion.cmake

One can now set the variable OPM_BINARY_PACKAGE_VERSION to a meaningful version string (e.g. Debian 11.2: 2021.10-4). When building outside of git it will be used as the project hash. If the variable is non-empty there will also be no timestamp in project-timestamp.hh (as this would break reproducible builds).
Note that if building from git or not setting the variable then everything will be like before.
This is the opm-common part of fixing OPM/opm-simulators#3832

Incude binary package version in project-version.h and skip timestamp

---

src/opm/output/eclipse/Summary.cpp

This commit recognises the summary vector `BNSAT` as a supported keyword.  This, in turn, enables retrieving the simulator's solvent saturation values at the block level as a time series.

Support Block Level Solvent Saturation Summary Output

---

redhat/opm-common.spec

- add parameter for which toolset to use
- build against openmpi3
- build with python support
- add boolean flags for the different mpi builds (mostly for testing)
- add parameter for appending extra token to package names.
this can be used for allowing multiple versions to be installed on the
same system.

update redhat packaging

---

cmake/Modules/Finddune-istl.cmake
cmake/Modules/OpmInit.cmake
cmake/Modules/OpmLibMain.cmake

As DUNE 2.8 uses CMake targets and always searches for these by default, the targets will be in the cmake configuration files and used for linking. Unfortunately, CMake package configuration files do not yet search for dependencies but rely on the DUNE build system (which we don't use). Hence our current approach will fail if we did not search for them and the targets are not defined.
In addition we make UMFPack mandatory (which I actually thought was the case already, but I obviously was wrong here.
Closes #2897

Use dune buildsystem defaults for MPI SuperLU, and Quadmath

---

jenkins/build-opm-module.sh

we need to be able to specify absolute refs to use for the repos
rather than a pull request number.
Backport of #2998

[backport] added: ability to use jenkins build scripts for release test building

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/C/COMPLUMP

The defaults of I, J, K1 and K2 in Eclipse keyword COMPLUMP should be zero according to the Eclipse manual. The text below is cut of from the manual:
```
Each record contains the following items:
1.
Well name, well name template, well list or well list template
A template enclosed in quotes can be used to refer to multiple wells or well lists. See "Well name and
well list template matching" in the ECLIPSE Technical Description for further details. Well list names
should be enclosed in quotes and begin with an asterisk (*). Well lists are constructed with the
keyword WLIST.
2.
I - location of connecting grid block(s)
DEFAULT: 0 (allows any I-value)
3.
J - location of connecting grid block(s)
DEFAULT: 0 (allows any J-value)
4.
K - location of upper connecting block in this completion …
```

Added default values for I, J, K1 and K2 in COMPLUMP

---

tests/parser/ACTIONX.cpp
tests/parser/FieldPropsTests.cpp
tests/parser/ScheduleTests.cpp
tests/test_nonuniformtablelinear.cpp
tests/test_uniformtablelinear.cpp

we want to compare with an epsilon since these have gone
through calculations.
This comes from @blattms debian packaging patches. Submitting here to lessen rebasing when doing a new release.

fixed: avoid direct floating point comparisons in tests

---

tests/parser/ACTIONX.cpp
tests/parser/FieldPropsTests.cpp
tests/parser/ScheduleTests.cpp
tests/test_nonuniformtablelinear.cpp
tests/test_uniformtablelinear.cpp

we want to compare with an epsilon since these have gone
through calculations
Backport of #3007

[backport] fixed: avoid direct floating point comparisons in tests

---

cmake/Modules/FindQuadmath.cmake
cmake/Modules/OpmInit.cmake

Quadmath is usually unused except when a dependency uses it and explicitly puts `QuadMath::QuadMath` into their CMake package configuration file.
On most platforms the compiler has Quadmath available by default. But on those that don't we should not stop CMake and fail.
Hence now we only print a message that Quadmath is not available.
Fixes fallout from #2995

Make not finding Quadmath non-fatal (e.g. not available on arm64)

---

cmake/Modules/FindQuadmath.cmake
cmake/Modules/OpmInit.cmake

Quadmath is usually unused except when a dependency uses it and explicitly puts QuadMath::QuadMath into their CMake package configuration file.
On most platforms the compiler has Quadmath available by default. But on those that don't we should not stop CMake and fail. Hence now we only print a message that Quadmath is not available.
Backport of #3012

[backport] Make not finding Quadmath non-fatal (e.g. not available on arm64)

---

CMakeLists.txt

This is for consistency with opm-simulators, which (always) installs them if they are built.
Closes #2976

Install python bindings as default.

---

CMakeLists.txt

This is for consistency with opm-simulators, which (always) installs them if they are built.
Backport of #3015

[backport] Install python bindings as default.

---

src/opm/output/eclipse/Summary.cpp

We now print "ACTIONX/UDQ using summary keywords (here: RPR) of category Region is
not yet supported." instead of "make_default_nodes does not yet support: RPR"

Improve error message for unsupported categories for UDQ/ACTIONX

---

cmake/Modules/OpmProject.cmake

We usually list all libraries that might be needed for linking in the
CMake package configuration files. This is needed when building static
libraries as we do not yet use CMake targets (which would allow to
list them differently). As we are doing this unconditionally and
also including the ones listed in modules that we depend on, changing
a library (e.g. moving from Python 3.9 to 3.10) requires a complete
rebuild of all modules to get rid of the stale dependency on
libpython3.9.
At least when building shared libraries listing the dependencies is
not needed and this patch simply removes all shared libraries form the
list in the CMake package configuration file. Thus we only need to
recompile the modules that have direct dependency on a stale library.
Backport of #3023 to release

[backport] Do not hard-code shared-libs in package configuration if not needed.

---

opm/input/eclipse/Utility/Functional.hpp

This removes a deprecation warning now, from C++20 this will become a compile error so we should change it.
For some information see https://en.cppreference.com/w/cpp/types/result_of

Use std::invoke and friends instead of the deprecated std::result_of.

---

CMakeLists.txt
cmake/Modules/PyInstallPrefix.cmake
python/cxx/schedule.cpp
python/tests/test_schedule.py

See use case downstream: https://github.com/OPM/opm-simulators/pull/3918
Adds a method `get_injection_properties()` to the Python interface to `Opm::Schedule` This method can be used to get information about `Well::WellInjectionProperties` for a given report step.
In order to avoid code duplication between `opm-simulators` and `opm-common`, logic in `CMakeLists.txt` was refactored out into `cmake/Modules/PyInstallPrefix.cmake`

Adds a method get_injection_properties() to the Python interface to Opm::Schedule

---

opm/input/eclipse/Deck/UDAValue.hpp
opm/input/eclipse/Schedule/Well/WVFPEXP.hpp
opm/output/eclipse/VectorItems/group.hpp
opm/output/eclipse/VectorItems/well.hpp
src/opm/input/eclipse/Schedule/Well/WVFPEXP.cpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
tests/test_AggregateGroupData.cpp
tests/test_AggregateWellData.cpp

In particular, add entries from `WECON`, `WGRUPCON`, and `WVFPEXP` and fix an incorrect item attribution for the `WTEST` 'reason' parameter.
Thanks to @tskille for invaluable assistance in identify these items.
While here, also refactor the main creation function for `SWEL` to assist future maintenance.

Identify Additional IWEL and SWEL Items

---

src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/ExtESmry.cpp
tests/test_ESmry.cpp
tests/test_ExtESmry.cpp

This PR is fixing a bug in load functions for both ESmry and ExtESmry. 
With current version of ESmry ( and similar with ExtESmry) the following code  
```c++
ESmry smry2("SPE1CASE1.SMSPEC");
auto fgor2a = smry2.get("FGOR");
smry2.loadData({"FGOR"});
auto fgor2b = smry2.get("FGOR");
```
will generate a vector fgor2b with double size compared with vector fgor2a since the vector FGOR is loaded twice from the disk.

ESmry and ExtESmry - Prevent loading data multiple times

---

opm/input/eclipse/Schedule/Network/Balance.hpp
opm/output/eclipse/DoubHEAD.hpp
opm/output/eclipse/VectorItems/doubhead.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Network/Balance.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/output/eclipse/CreateDoubHead.cpp
src/opm/output/eclipse/DoubHEAD.cpp

The current `Network::Balance` class applies default values a little too eagerly and this leads to problems for restarted simulation.  We must take care to preserve the "did this item have a value" state also in the restart file lest interactions with `TUNING` be lost there.
To this end, make the minimum timestep size for network balancing be an `std::optional<>` and use `std::nullopt` to represent "no value set" in the input file.  While here, also preserve negative balancing intervals exactly instead of replacing these values by zero.

Increase Compatibility of NETBALAN Restart Output

---

python/tests/data/JFUNC.DATA
python/tests/test_state.py
src/opm/input/eclipse/share/keywords/000_Eclipse100/J/JFUNC
src/opm/input/eclipse/share/keywords/000_Eclipse100/J/JFUNCR

We effectively ignore `JFUNC` data unless end-point scaling is activated through the `ENDSCALE` keyword in the `RUNSPEC` section. Alert the user to this fact by terminating the simulation run if the case uses `JFUNC` without `ENDSCALE` present in `RUNSPEC`.  In this case, issue a diagnostic message of the form
```
Error: Unrecoverable errors while loading input: Problem with keyword JFUNC
In CASE.DATA line 125
Incompatible keyword combination: JFUNC declared, but ENDSCALE is missing.
```

Require ENDSCALE When JFUNC Entered

---

src/opm/output/eclipse/AggregateGroupData.cpp
tests/test_AggregateGroupData.cpp

We need to honour a "small rate threshold" when outputting the lift gas max supply rate limit and total gas production limit.  This threshold renders the output discontinuous, but is needed for compatibility.

Increase Compatibility of GLO Restart Output

---

CMakeLists.txt
cmake/Templates/opm-project-config.cmake.in

See https://github.com/OPM/opm-simulators/pull/3918 for details.
Install the `install.py` python script such that it can be used by `opm-simulators` when building against an installed `opm-common`

WIP: Install the `install.py` script such that it can be reused by opm-simulators

---

tests/parser/ACTIONX.cpp

changed: use modern include file path

---

src/opm/output/eclipse/Summary.cpp

Keyword is implemented, but missing in Summary.cpp. Small fix also to be pushed in opm-simulators.

Output FOE

---

opm/input/eclipse/Utility/Functional.hpp

`opm-common/opm/input/eclipse/Utility/Functional.hpp` did not compile for g++-8.4.0, without this header.
Resolves https://github.com/OPM/opm-common/issues/3050.

Include header to compile with g++-8.4.0

---

src/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp

MULTZ is the only keyword that is stored in global representation
(i.e. with values for inactive cells, too) to allow the "PINCH ALL"
processing. This produced errors like:
```
Error:
An error occurred while creating the reservoir properties
Internal error: Region operations on 3D fields with global storage is
not implemented
```
With this change the error message has more information for the user
and might help to work around it:
```
Error:
An error occurred while creating the reservoir properties
Internal error: In file /path/to/file.inc line 3: MULTIREG region operation on 3D field MULTZ with global storage is not implemented!
```

Improve error message for region operations on multz

---

src/opm/io/eclipse/rst/state.cpp

The well list positions for individual wells (i.e., `IWLS`) need not be, and typically are not, strictly increasing in the restart files. Therefore we must only `resize()` the well name vectors if the `well_order` is strictly larger than the current size.  Otherwise, we lose information about which wells are in which well lists.

Don't Assume Increasing WLIST Position In Restart Files

---

opm/input/eclipse/EclipseState/Tables/FlatTable.hpp
src/opm/input/eclipse/EclipseState/Tables/PvtxTable.cpp
src/opm/input/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/input/eclipse/EclipseState/Tables/Tables.cpp
tests/parser/TableManagerTests.cpp

A simulation model may choose to give PVTW data as
```
PVTW
1.0 1.0 1.0e-5 0.2 0.0 /
/  -- record 2 (copied from record 1)
```
if, for instance, the oil and/or gas tables are different in regions 1 and 2, but the water is the same.  In this case we must properly copy record 1 into record 2 and essentially recreate the table.
To this end, decouple the `PvtwTable` from the `FlatTable` machinery and make the former into an independent type containing `vector<>` instead of inheriting from `vector<>`.  Implement the default->copy behaviour in the new constructor
```C++
PvtwTable::PvtwTable(const DeckKeyword&)
```
---
Update: I have now added similar behaviour for `PVDO`, `PVDG`, `PVTO`, `PVTG`, `DENSITY`, and `GRAVITY` too.  The latter two keywords use the same approach as `PVTW`, while the …

Treat All-Defaulted PVTW Record as Copy of Previous

---

opm/input/eclipse/EclipseState/Grid/FaultCollection.hpp
opm/input/eclipse/EclipseState/Tables/SimpleTable.hpp
opm/input/eclipse/EclipseState/Tables/TableSchema.hpp
opm/input/eclipse/EclipseState/Util/OrderedMap.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
tests/parser/OrderedMapTests.cpp

Warnings about too long names need to be generated in the validation code in opm-simulators.
Needs OPM/opm-simulators#3959

Use only first 8 characters as fault name when comparing/searching.

---

opm/common/utility/ActiveGridCells.hpp
opm/input/eclipse/EclipseState/Grid/GridDims.hpp
src/opm/input/eclipse/EclipseState/Grid/GridDims.cpp

This PR switches the Cartesian -> IJK decomposition in `GridDims` from K->J->I into the I->J->K order.  The latter is simpler.
While here, also consistently use `std::size_t` instead of `size_t`.

Streamline GridDims::getIJK()

---

opm/common/utility/ActiveGridCells.hpp
opm/input/eclipse/EclipseState/Grid/Box.hpp
opm/input/eclipse/EclipseState/Grid/BoxManager.hpp
src/opm/input/eclipse/EclipseState/Grid/Box.cpp
src/opm/input/eclipse/EclipseState/Grid/BoxManager.cpp
src/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
tests/parser/BoxTests.cpp
tests/parser/integration/BoxTest.cpp

This PR switches to constructing Box instances from a `GridDims` and two call-back functions instead of taking an `EclipseGrid`
directly.  The two call-back functions are a predicate for active cells and a translation from Cartesian to active cell indices respectively.
This is intended to simplify working with nested boxes, such as those that occur for local grid refinement.

Decouple Opm::Box From EclipseGrid

---

src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/M/MINPORV
src/opm/input/eclipse/share/keywords/000_Eclipse100/M/MINPV
src/opm/input/eclipse/share/keywords/900_OPM/M/MINPVFIL

Add support for MINPORV, which is an alias for MINPV. Also added additional checks, such that only one of MINPV, MINPORV and MINPVFIL can be active in the deck

Support MINPORV

---

opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/W/WPIMULT
tests/parser/ScheduleTests.cpp

An attempt to fix the running with multiple WIPMULT records.
The key modification here is that if `multiple records` within the `same report step` to a well has all defaulted and connection and completion information, only the `last` record will apply.

fixing multiple WPIMULT records

---

opm/input/eclipse/Schedule/Schedule.hpp
opm/output/eclipse/AggregateActionxData.hpp
src/opm/input/eclipse/Python/Python.cpp
src/opm/input/eclipse/Python/PythonInterp.hpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/Well/Connection.cpp
src/opm/output/eclipse/WriteInit.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WTEST.cpp
tests/test_AggregateAquiferData.cpp

Remove include in header and deal with consequences.
And clean list of includes in Schedule.hpp
Not really a big impact, from 532 build steps to 523 build steps according to ninja.

Cleanup Schedule.hpp usage

---

opm/output/eclipse/WriteRPT.hpp

Needed to compile with recent clang and libc++.

Add <cstddef> include for std::size_t.

---

ExtraTests.cmake

The input decks were removed from the opm-tests repository.  We **may** consider readding them from a new location at a later time.

Remove Consistency Checks for SPE10 Models

---

src/opm/io/eclipse/ESmry.cpp

Summary files generated by the Eclipse simulator creates a lot of time vectors which are not real data. These should be ignored by ESmry. The member function ESmry::makeKeyString will return an empty string for this entries and importantly the map arrayPos should not be updated with this vectors.

fixing bug in IO class ESmry

---

opm/common/utility/TimeService.hpp
src/opm/common/utility/TimeService.cpp

This function converts a std::tm to a std::time_t, assuming UTC and not local timezone. This is used instead of relying on
repeated calls to mktime(), which can fail on some system (BSD) for dates before 1900.
This was discovered by running a case with START date 1 JAN 1900, which when run in the CET zone is in 1899 (UTC).

Add and use portable_timegm().

---

opm/input/eclipse/EclipseState/Aquifer/Aquancon.hpp
opm/input/eclipse/EclipseState/Aquifer/AquiferConfig.hpp
src/opm/input/eclipse/EclipseState/Aquifer/Aquancon.cpp
src/opm/input/eclipse/EclipseState/Aquifer/AquiferConfig.cpp
src/opm/output/eclipse/AggregateAquiferData.cpp
tests/parser/AquiferTests.cpp

This is the upstream PR of  https://github.com/OPM/opm-simulators/pull/4015 . 
The following changes are introduced in this PR and https://github.com/OPM/opm-simulators/pull/4015 . 
1. For the situation that an defined analytical aquifer do not have valid connection, 
With the master branch, we will throw the following exception and terminate the running.
```
Program threw an exception: There is not connection associated with analztical aquifer 1
```
With this PR, we will give the following warning, and continue the simulation without terminating the running.
```
Warning: There is no valid connection associated with Carter-Tracy aquifer 1, this aquifer will be ignored in the simulation
```
2. For the situation that we define connections with undefined analytical aquifers, the running will …

Handling connection aquifer mismatch

---

opm/output/data/Wells.hpp
tests/test_Restart.cpp

After adding the `tracer` member the data::Rates class, it is no longer a POD. The same applies to data::Connection and data::Segment, since these contain data::Rates subobjects. In the serialization used for communicating these objects to other MPI ranks, this means they now need specific packSize(), pack() and unpack() methods. These must be implemented in opm-simulators (in ParallelRestart.cpp), but need access to the members. I have therefore added a friend declaration that enables this.
The second commit is a drive-by fix in the same file, operator== of Connection was not updated when adding the `trans_factor` member. This fix then caused a test failure, it turns out that the restart I/O does not treat the Connection objects completely. However, the data::Wells objects compared are …

Prepare for fixing packing of Rates, fix bug in Connection comparison operator

---

opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Schedule/Schedule.cpp

PR #3104 made me realize that we're not serializing all data members of the `Schedule` object.  It **probably** not a big deal, but this PR nevertheless adds serialization support for the `exit_status` member too.  While here, add proper testing of the `action_wgnames` and `completed_cells` too.
Finally, prefer template argument deduction to explicit template arguments when calling the `pack_unpack<>` helper.

Serialize All Schedule Data Members

---

opm/input/eclipse/Schedule/CompletedCells.hpp

the array is left uninitialized by the constructor.
the alternative is to add initialization, but I'm not sure if this was left undefined intentionally or not.

fixed: initialize dimensions in serializeObject

---

opm/input/eclipse/Schedule/CompletedCells.hpp

The existence of serializeOp in the data type is now detected at compile time.
Down/upstream of https://github.com/OPM/opm-simulators/pull/4051

adjust for array serializer API change

---

opm/output/data/Groups.hpp

Sits on top of https://github.com/OPM/opm-common/pull/3124
Sits on top of https://github.com/OPM/opm-common/pull/3123

data::GroupAndNetworkValues: add serializer support

---

opm/input/eclipse/Schedule/SummaryState.hpp
src/opm/input/eclipse/Schedule/SummaryState.cpp
tests/test_Summary.cpp

this appends information from one instance to another.
needed to handle semantics used in parallel serialization

added: append function in SummaryState

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/Network/Balance.hpp
opm/io/eclipse/rst/netbalan.hpp
opm/io/eclipse/rst/state.hpp
opm/output/eclipse/VectorItems/intehead.hpp
src/opm/input/eclipse/Schedule/Network/Balance.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/io/eclipse/rst/netbalan.cpp
src/opm/io/eclipse/rst/state.cpp
src/opm/output/eclipse/InteHEAD.cpp
tests/test_InteHEAD.cpp
tests/test_rst_netbalan.cpp

This PR loads NETBALAN parameters from the restart file and forms `Network::Balance` objects from these parameters.

Add Restart Support for NETBALAN Keyword

---

opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Schedule/Schedule.cpp

While useful for analysis in the case of failure, end users will typically not care that we "rerun" portions of the `SCHEDULE` section in response to triggering an action.  In the cases where we do need those messages they will be available in the `CASE.DBG` file instead.
---
As an example, with this PR and its downstream companion OPM/opm-simulators#4047, I get the following reduction in the number of lines&mdash;as reported by `wc -l`&mdash;in the `PRT` file of an [`ACTIONX_WPIMULT`](https://github.com/OPM/opm-tests/blob/b342b4e5f756d47d63f208490a50b9e948f9f8a1/actionx/ACTIONX_WPIMULT.DATA) run.
```
7649 ./master/ACTIONX_WPIMULT.PRT
6957 ./this-pr/ACTIONX_WPIMULT.PRT
```

Direct Verbose Action Messages to Debug File

---

opm/input/eclipse/Schedule/RFTConfig.hpp
opm/input/eclipse/Schedule/Well/WellConnections.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/RFTConfig.cpp
src/opm/input/eclipse/Schedule/Well/Connection.cpp
src/opm/input/eclipse/Schedule/Well/WellConnections.cpp
src/opm/output/eclipse/WriteRFT.cpp
tests/parser/RFTConfigTests.cpp

In preparation of supporting new data types (PLT and segment). Introduce a wrapper class, `WellRFTOutputData`, which knows about all supported data types and how to emit the RFT record header.  Defer specialised data type handling to dedicated record types and, to this end, rename the existing `WellRFT` class to `RFTRecord`.
While here, also apply `const` and sundry whitespace adjustments in the `WellConnections` code and the `WRFT*` keyword handlers.

Refactor RFT File Writing Code

---

CMakeLists.txt
opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.hpp
python/setup.py.in
tests/parser/EmbeddedPython.cpp

Found some stuff in a branch on my laptop.
- fix building python bindings on systems without openmp (e.g. clang when you forget to install libomp)
- add a missing virtual dtor
- respect rule-of-three
- workaround clang parsing issue in python test

Some janitoring

---

opm/input/eclipse/Schedule/Well/WellEconProductionLimits.hpp
opm/io/eclipse/rst/well.hpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/input/eclipse/Schedule/Well/WellEconProductionLimits.cpp
src/opm/io/eclipse/rst/well.cpp
tests/test_rst.cpp

Notably missing are
- Maximum gas-liquid ratio
- Maximum temperature
- Minimum reservoir fluid flow rate
- Follow-on well
We do not currently write those items to the restart file but will extend the support as need arises.

Add Restart Support for Known Well Level Economic Limits

---

src/opm/input/eclipse/EclipseState/Tables/TableManager.cpp

Lack of checking triggered an exception for programs not setting up logging exactly like OPM Flow (using the exact same backend name strings) when ran on cases where this condition (a warning about a fluid table) was triggered. In particular this includes the `wellgraph` tool.

Check that backend exists before logging.

---

opm/common/ErrorMacros.hpp

The use of double underscores (`__`) is reserved for the system (see eg. https://en.cppreference.com/w/cpp/language/identifiers ), hence this pull request renames the temporary variable `oss__` to the more verbose (but probably never shadowed) variable `opmErrorMacroOStringStream`.
This will also remove the constant warnings when running `clang-tidy` about reserved indentifiers on files that use any version of the `OPM_THROW` macros.

Remove use of reserved identifier in OPM_THROW.

---

opm/io/eclipse/SummaryNode.hpp
src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/SummaryNode.cpp
src/opm/output/eclipse/Summary.cpp
tests/test_Summary.cpp
tests/test_SummaryNode.cpp

This enables not using the non-standard node names
```
WOPRL__1
```
&c which increases post-processor compatibility of our `SMSPEC` files and enables detecting situations where we need to supply completion numbers for nodes that would otherwise be treated as pertaining to wells instead.

Add New Summary Node Category of Completion

---

opm/io/eclipse/ESmry.hpp
opm/io/eclipse/ExtESmry.hpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/ExtESmry.cpp

Start date in ESMRY file (format) have 7 elements, last element is milliseconds.

Fix bug in ExtESmry

---

src/opm/output/eclipse/Summary.cpp

`SummaryNode::number_` does not have a value for all summary keywords.
closes #3090

fixed: avoid use of uninitialized SummaryNode::number_

---

src/opm/io/eclipse/ERsm.cpp
test_util/EclRegressionTest.cpp
test_util/EclRegressionTest.hpp
test_util/compareECL.cpp

This improves output from compareECL when comparing summary files. 
Notice that the RSM file generated by the commercial simulator, for test model [`opm-tests/wvfpexp/WVFPEXP-01.DATA`](https://github.com/OPM/opm-tests/blob/9c3555ab26aa9df6a5d23a99e3a4aef6620ac01a/wvfpexp/WVFPEXP-01.DATA), exposes a BUG in Eclipse.
```
tskille@melwood:~/prog/test_data$ ../opm-common/build/bin/compareECL TEST-0_ECL TEST-0_ECL 1e-5 1e-5 -t SMRY
Comparing 'TEST-0_ECL' to 'TEST-0_ECL'.
Loading EGrid TEST-0_ECL.EGRID  ....  done.
Loading EGrid TEST-0_ECL.EGRID  ....  done.
Loading summary file TEST-0_ECL.SMSPEC  .... done
Loading summary file TEST-0_ECL.SMSPEC  .... done
Comparing summary files 
Checking 223  vectors  ...  done.
Loading RSM file TEST-0_ECL.RSM  .... Program threw an exception: Error loading RSM …
```

additional output from compareECL related to rsm files

---

CMakeLists.txt
cmake/Templates/opm-project-config.cmake.in

this needs to be different for the in-tree and installed config files.
i found the issue you were struggling with @blattms
this fixes it properly.

fixed: properly export opm-common_PYTHON_COMMON_DIR

---

CMakeLists.txt
GenerateKeywords.cmake
cmake/Modules/OpmCompile.cmake

for better IDE integration. while IDEs can identify headers in the source directories, having them specified is very convenient when doing, say, mass refactorings.

added: add headers to library definition

---

src/opm/input/eclipse/Schedule/Well/Connection.cpp
tests/parser/ConnectionTests.cpp

Some models will use lower-case strings to input the direction of penetration, e.g., `'x'` or `'z'`.  This PR extends our direction parser to support such strings.
This PR addresses Issue #3164.

Support Lower Case COMPDAT Direction Strings

---

opm/input/eclipse/Units/UnitSystem.hpp
src/opm/input/eclipse/Units/UnitSystem.cpp
tests/parser/UnitTests.cpp

Needed for summary and RFT file output of fluid flow velocity in well segments.
The velocity unit here is "length / second" rather than "length / time", so that's why we only need to convert the length unit when translating between input/output unit conventions and OPM's strict SI convention.

Add Unit for Pipeflow Velocity

---

opm/input/eclipse/EclipseState/Grid/FaceDir.hpp
src/opm/input/eclipse/EclipseState/Grid/FaceDir.cpp
tests/parser/FaceDirTests.cpp

this translates from a dune intersection id to a FaceDir::DirEnum.
Upstream of https://github.com/OPM/opm-simulators/pull/4171

added: FaceDir::FromIntersectionIndex

---

cmake/Modules/UseDamaris.cmake

Don't enable damaris if MPI was not enabled. Also reduce verbosity when damaris was not requested.

Damaris depends on MPI

---

cmake/Modules/UseDamaris.cmake

According to https://cmake.org/cmake/help/latest/module/FindMPI.html the capitalized version is what we should use.

Use MPI_FOUND not MPI_Found.

---

src/opm/input/eclipse/EclipseState/Runspec.cpp
tests/parser/RunspecTests.cpp

If the input model sets the maximum number of well lists per well to zero (or negative), then treat this as if the limit is defaulted and reset the value to the default (one).
Resolves #3194.

Ensure At Least One Well List per Well

---

cmake/Modules/FindMETIS.cmake

With master, I get lots of
```
WARNING: Preprocessor definitions containing '#' may not be passed on the compiler command line because many compilers do not support it.
CMake is dropping a preprocessor definition: METIS_API_VERSION=#define METIS_VER_MAJOR         5
Consider defining the macro in a (configured) header file.
```
The commented-out part seems to be necessary to avoid this.

Fix metis-related warnings

---

src/opm/input/eclipse/Schedule/MSW/Valve.cpp

to account for the unit conversion.
spotted by @bska

using SIDouble when creating Valve from a record

---

opm/input/eclipse/EclipseState/SimulationConfig/BCConfig.hpp
src/opm/input/eclipse/EclipseState/SimulationConfig/BCConfig.cpp
src/opm/input/eclipse/share/keywords/900_OPM/B/BC

The Dirichlet option has been missing in the BC keyword.

extend BCType with dirichlet

---

opm/io/eclipse/ExtSmryOutput.hpp
src/opm/io/eclipse/ExtSmryOutput.cpp

Delete temp esmry file when the rename temp ESMRY file to simulation ESMRY file.
With current master the following errors occurs from time to time. 
```
ERROR: Uncaught std::exception when running tasklet: filesystem error: cannot rename: No such file or directory [TMP_1667245070.ESMRY] [./TEST1_MASTER.ESMRY]. Trying to continue.
ERROR: Uncaught std::exception when running tasklet: filesystem error: cannot rename: No such file or directory [TMP_1667246438.ESMRY] [./TEST1_MASTER.ESMRY]. Trying to continue.
ERROR: Uncaught std::exception when running tasklet: filesystem error: cannot rename: No such file or directory [TMP_1667246626.ESMRY] [./TEST1_MASTER.ESMRY]. Trying to continue.
ERROR: Uncaught std::exception when running tasklet: filesystem error: cannot rename: No such file or …
```

Cleanup when ESMRY renamle fails

---

cmake/Templates/opm-project-config.cmake.in

When not using the OPM CMake build system magic a find_package(opm-module) did fail in some settings as the CMAKE_MODULE_PATH did not include the location of OpmPackge.cmake and the likes.
This fixes this by issuing a find_package(opm-common) for modules that are not opm-common.

[bufix,cmake] Fixes simple find_package(opm-module) calls

---

cmake/Modules/OpmPackage.cmake

This is broken for DUNE >= 2.8 and dune modules that use  OPM.
This reverts parts of 20e3202067 which opened a can of worms in conjunction with imported targets. This is a really ugly hack.
Together with #3203 this closes OPM/opm-grid#598

Make sure compilation is not tested when searching for DUNE/OPM module

---

cmake/Modules/OpmPackage.cmake

This is broken for DUNE >= 2.8 and dune module that use  OPM.

Make sure compilation is not tested.

---

src/opm/output/eclipse/WriteRFT.cpp
tests/test_RFT.cpp

We support both standard and multisegmented wells, but do not output every known PLT array.  Notably missing are
* `WELLPLT`
* Brine flow rate (`CONSRAT`)
* Phase flow rates through tubing (`CONxTUB`)
Computing `CONNXT` for multisegmented wells is somewhat involved, and requires sorting the connections according to branch number, segments, and tubing lengths.  We use an ancillary structure, an array of indices into a `WellConnections` object, along with a custom predicate to perform this sorting.
As an implementation detail, we handle PLT data for multisegmented wells as an extension of the PLT data for regular/standard wells. This extension is realised through dynamic polymorphism.
Add unit tests to cover PLT data for both well types.
This PR addresses some of the shortcomings raised in …

Add Basic PLT Information to RFT Output File

---

opm/input/eclipse/Schedule/UDQ/UDQASTNode.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQDefine.hpp
opm/input/eclipse/Schedule/UDQ/UDQEnums.hpp
opm/input/eclipse/Schedule/UDQ/UDQInput.hpp
opm/input/eclipse/Schedule/UDQ/UDQSet.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQASTNode.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQDefine.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQEnums.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQInput.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQParser.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQParser.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQSet.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQToken.cpp

In particular, introduce a number of helper functions for evaluating expressions, well variables, group variables, unary and binary function expressions, and direct number values.  This also, I believe, fixes a latent error in one group variable case which appears not to apply the 'sign' correctly.
While here, also wrap some long lines throughout this component. This is in preparation of adding support for UDQs at the segment level.

Reduce Level of Nesting in UDQASTNode::eval

---

opm/input/eclipse/EclipseState/SimulationConfig/BCConfig.hpp
opm/input/eclipse/EclipseState/SimulationConfig/RockConfig.hpp
opm/input/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
opm/input/eclipse/EclipseState/SimulationConfig/ThresholdPressure.hpp
src/opm/input/eclipse/EclipseState/EclipseState.cpp
src/opm/input/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
tests/parser/ThresholdPressureTest.cpp

To avoid deck usage downstream.

Internalize THPRESFT keyword

---

src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp

Needed to reflect the GRIDUNIT transformation in the EGRID output.

Apply GRIDUNIT Processing to COORD/ZCORN Output Copies

---

opm/common/utility/Serializer.hpp

In particular gcc11 is noisy..

fixed: zero initialize to avoid compiler warnings

---

test_util/EclRegressionTest.cpp

We should not be silently ignoring if reference case has no rft file, but new run has.
ref https://github.com/OPM/opm-tests/pull/853

changed: flag an error if just one case has a rft file

---

GenerateKeywords.cmake

the generated python code requires the copy_python target to setup the directory structure. without this, builds failed when building a specific target (ie not 'all') in a clean build tree

fixed: depend on the copy_python target

---

CMakeLists_files.cmake
opm/material/fluidmatrixinteractions/EclEpsConfig.hpp
opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
src/opm/material/fluidmatrixinteractions/EclEpsConfig.cpp

This to encapsulate EclipseState and some other headers.  While here, use class member initialization to avoid the need for a trivial constructor.
Also convert an enum to an enum class, cleaner in itself and allows for forwarding which is useful to avoid pulling in this header elsewhere.

EclEpsConfig: put initFromState in separate compile unit

---

CMakeLists_files.cmake
opm/material/fluidmatrixinteractions/EclEpsGridProperties.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
src/opm/material/fluidmatrixinteractions/EclEpsGridProperties.cpp

in particular this allows to encapsulate the EclipseState class usage.

changed: put EclEpsGridProperties constructor in separate compile unit

---

CMakeLists_files.cmake
opm/material/fluidmatrixinteractions/EclHysteresisConfig.hpp
src/opm/material/fluidmatrixinteractions/EclHysteresisConfig.cpp

in particular this allows to encapsulate the Runspec class usage. also use class member initialization instead of constructor.

changed: put EclHysteresisConfig initFromState in separate compile unit

---

CMakeLists_files.cmake
opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
src/opm/material/fluidmatrixinteractions/EclEpsScalingPoints.cpp
tests/test_eclmateriallawmanager.cpp

this allows to encapsulate EclipseState usage and iostream usage

EclEpsScalingPoints(Info): put init and print in separate compile unit

---

tests/test_Serialization.cpp

Hopefully the end of the uninitialized-variable-in-serialization-warnings story..

initialize variable to avoid compiler warnings

---

opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
opm/material/fluidmatrixinteractions/EclMultiplexerMaterial.hpp
opm/material/fluidmatrixinteractions/EclMultiplexerMaterialParams.hpp
opm/material/fluidmatrixinteractions/EclTwoPhaseMaterial.hpp
opm/material/fluidmatrixinteractions/EclTwoPhaseMaterialParams.hpp
opm/material/fluidmatrixinteractions/SatCurveMultiplexer.hpp
opm/material/fluidmatrixinteractions/SatCurveMultiplexerParams.hpp
opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/OilPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/WaterPvtMultiplexer.hpp

The name of the entries in these enums contains redundancies now that they have been converted to enum class. Remedy this to tidy code a little.

Reduce redundancy in some enums

---

opm/material/components/SimpleCO2.hpp

it should be up to instance sites to make every available for the templates to instance properly, even though we know we are instancing over Evaluations.

changed: remove include of Math.hpp

---

opm/input/eclipse/EclipseState/Grid/FieldProps.hpp

This is needed as it is used when calculating transmissibilities over pinched out cells. There it needs to behave the same way as MULTZ does.
Missing changes for OPM/opm-simulators#4320

Always use MULTZ- as a global array.

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/MSW/SegmentMatcher.hpp
src/opm/input/eclipse/Schedule/MSW/SegmentMatcher.cpp
tests/test_SegmentMatcher.cpp

The primary use case is identifying UDQ sets when the model defines UDQs at the segment level (`SU*`).  The call site will construct a `SegmentMatcher` object backed by a specific `ScheduleState`, and then segment-level UDQs will match against this to determine the correct UDQ set on which to define the quantity.

Add Facility For Identifying Specific Well Segments

---

tests/test_EvaluationFormat.cpp

That way, we get both strings printed if a test fails.

Prefer BOOST_CHECK_EQUAL

---

CMakeLists.txt

Otherwise, we get build failures if the Dune libraries and headers are outside of the system directories.

Link New Test to Dune Common

---

opm/input/eclipse/Schedule/MSW/SegmentMatcher.hpp

The enumerated `segments()` overload takes a well number, not a well name.
Pointy Hat: [at]bska

Fix Copy-Pasted Function Documentation

---

opm/input/eclipse/EclipseState/Util/OrderedMap.hpp
tests/parser/OrderedMapTests.cpp

for a (small) reduction in amount of sources pulling stream classes.

OrderedMap: avoid sstream usage

---

opm/common/OpmLog/TimerLog.hpp
src/opm/common/OpmLog/TimerLog.cpp

minor minor, but still better.

TimerLog: avoid sstream in header

---

CMakeLists_files.cmake
opm/common/utility/numeric/RootFinders.hpp
src/opm/common/utility/numeric/RootFinders.cpp

put logging functions in separate compile unit where we use {fmt}

RootFinders: avoid stream usage in header

---

CMakeLists_files.cmake
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp

EclMaterialLawManager: move most code to separate compile unit

---

opm/input/eclipse/Deck/Deck.hpp

ref https://github.com/OPM/opm-common/pull/1574

remove OPM_PARSER_DECK_API_WARNING

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityWaterPvt.hpp
src/opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityWaterPvt.cpp

ConstantCompressibilityWaterPvt: encapsulate EclipseState w/ friends

---

opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/GasPvtThermal.hpp
opm/material/fluidsystems/blackoilpvt/OilPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/OilPvtThermal.hpp
opm/material/fluidsystems/blackoilpvt/WaterPvtThermal.hpp

- (harmless but potentially troublesome) \ at end of macros
- what looks like a copy-paste faulty method name
- a reference to nonexistent method
the two latter have been harmless since code using them has never been instanced, but i'm working on changes that does so.

Some small fixes in material classes

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/DryGasPvt.hpp
opm/material/fluidsystems/blackoilpvt/WetHumidGasPvt.hpp
src/opm/material/fluidsystems/blackoilpvt/DryGasPvt.cpp

DryGasPvt: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/LiveOilPvt.hpp
opm/material/fluidsystems/blackoilpvt/WetGasPvt.hpp
src/opm/material/fluidsystems/blackoilpvt/LiveOilPvt.cpp

And replace asserts on user-defined data with exceptions.

LiveOilPvt: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/OilPvtThermal.hpp
src/opm/material/fluidsystems/blackoilpvt/OilPvtThermal.cpp

And replace assert on user-provided data with exceptions.

OilPvtThermal: encapsulate EclipseState w/ friends

---

cmake/Modules/FindQuadmath.cmake

this should only be set on the target if using QuadMath. every time cmake was rerun a build directory new entry was added, leading to very long compile commands eventually.

fixed: do not append to flags to CMAKE_CXX_FLAGS

---

CMakeLists_files.cmake
opm/material/components/CO2.hpp
opm/material/fluidsystems/BrineCO2FluidSystem.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp
src/opm/material/components/CO2.cpp
tests/test_components.cpp
tests/test_fluidsystems.cpp

this way we don't have to drag 6MB of tables into multiple compile units. 
some flexibility is lost (ie the template parameter for the table), but this is unused in the current code.
comment out some templates that do not instance as they are referring to non-existent table members.

CO2: encapsulate CO2Tables

---

opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Schedule/Schedule.cpp
tests/parser/MultisegmentWellTests.cpp
tests/test_InteHEAD.cpp

we can now forward Opm::Python
micro optimization. reduce Python.hpp hotness by 31% (51 less compile units, 113 instead of 164).

Schedule: move more code to compile unit

---

opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp
tests/test_Serialization.cpp

reduce hotness of RPTConfig.hpp by 94% (155 files, 10 files instead of 165)

Schedule.hpp: forward RPTConfig

---

opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
tests/parser/ScheduleSerializeTest.cpp
tests/parser/ScheduleTests.cpp

reduce hotness of WellTestConfig.hpp by 59% (101 files, 70 files instead of 171).

Schedule.hpp: forward WellTestConfig

---

msim/src/msim.cpp
opm/input/eclipse/Schedule/Action/SimulatorUpdate.hpp
opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

reduce hotness of SimulatorUpdate.hpp by 96% (154 files, 6 files instead of 160).

Forward SimulatorUpdate in Schedule

---

opm/input/eclipse/Schedule/ScheduleState.hpp
tests/test_Serialization.cpp

reduce hotness of NameOrder.hpp by 87% (139 files, 21 files instead of 160).

ScheduleState.hpp: forward (Group|Name)Order
