OPM/opm-common

- Makefile
- configure
- dune.module
this is required to continue supporting the build path via 'dunecontrol'.
(which is the easiest way to build the whole thing, at least until the 
"meta build" cmake scripts become available.)
since the opm-cmake does not contain any source files, placeholder
versions of the configure bash script and Makefile are
sufficient. These files are required because dunecontrol calls
'./configure' and 'make' unconditionally. (Also, the downstream
modules need to depend on opm-cmake to find the build macros...)
I also fixed the other modules which I care for in separate PRs...
> fix the opm-cmake duncontrol support

- cmake/Modules/opm-polymer-prereqs.cmake
Change made after initial branch of opm-cmake was lost.
> Fix prerequisites.

- cmake/Modules/FindPTScotch.cmake
- cmake/Modules/FindZOLTAN.cmake
- cmake/Modules/dune-cornerpoint-prereqs.cmake
There already is a module for finding Zoltan, which supports both ParMETIS and PT-Scotch underneath. While the former is only free for academic use the latter is true open source. Therefore
with this commit we add a module for finding PT-Scotch and add the necessary libraries and include paths for ZOLTAN.
This a port of the original PR OPM/opm-core#787
> [cmake] Add CMake module for finding PT-Scotch in dune-cornerpoint

- cmake/Modules/OpmLibMain.cmake
- cmake/Modules/OpmSatellites.cmake
- the tests are excluded from the 'all' build target
- the name is appended to a list called test_apps
this is intended to be used for generating an autotools style 'make
check' target, see https://github.com/OPM/opm-parser/pull/469 for an example
this is a simpler version than the current opm_add_satellite for tests without data dependencies.
> added: macro to add a single test

- cmake/Modules/FindERT.cmake
ERT sibling directories do not follow the normal conventions. add the expected dirs as well.
> added: look for ERT in some more sibling directories

- cmake/Modules/Findopm-parser.cmake
With this: https://github.com/OPM/opm-parser/pull/459/files in the pipeline the `Findopm-parser.cmake` will need to look in the parser build directory to find a generated header.
> Will look for generated headers in opm-parser

- cmake/Modules/OpmSatellites.cmake
the motivation for this is to fix the testing regressions seen by eWoms by switching to opm_add_test(); cf
http://www.opm-project.org/CDash/index.php?project=eWoms
it also requires the corresponding PR for eWoms to be merged. (whoever merges the opm-cmake PR should please also merge the one for eWoms.)
the meat of this PR is in the first patch (where I also tried to extend the comments for the macro considerably)
> Fix opm add test regressions

- cmake/Modules/FindERT.cmake
broke ERT sibling builds for opm-core. @joakim-hove for review.
> added: look for ecl_well include paths

- cmake/Modules/FindERT.cmake
Since: https://github.com/Ensembles/ert/pull/778 ert has had some *very basic* C++ wrappers; the intention is to use these classes to improve the readability of the EclipseWriter implementation in opm-core.
When this is merged people must upgrade the ERT distribution to get the new C++ library. In addition to this there is one more ERT incompatible change in the pipeline: https://github.com/Ensembles/ert/pull/783 - when that is merged these parser and core PRs must be merged as well:
- https://github.com/OPM/opm-core/pull/804
- https://github.com/OPM/opm-parser/pull/468
- https://github.com/OPM/opm-parser/pull/466
These ERT/opm-core/opm-parser PRs are all ready to be merged. To avoid unnecessary module upgrades for downstream developers please coordinate the merging of this PR with me.
> Updated FindERT.cmake to look for libeclxx.

- cmake/Modules/FindZOLTAN.cmake
- cmake/Scripts/configure
This PR fixes an issue when OPM is configured with dunecontrol.
> make configure work for ZOLTAN when used with dunecontrol.

- cmake/Scripts/configure
this makes the build system respect these flags if it is used with dunecontrol.
for people who do not use the configure wrapper script or who do not specify custom compiler flags, nothing changes.
> configure wrapper: switch the build type to "Custom" if any compiler flags are set

- cmake/Modules/Findlibrt.cmake
- cmake/Modules/ewoms-prereqs.cmake
it seems like old systems need to link to librt for this
function. (for newer ones it is already included in libc.)
> fix clock_gettime() on older systems

- cmake/Modules/OpmDoc.cmake
- cmake/Templates/Doxyfile
newer versions of doxgen complain about a few deprecated statements in the config file and also downstream modules should be able to specify their own layout file. this PR fixes these issues.
> some doxygen cleanups

- cmake/Modules/OpmStaticTargets.cmake
will be used for creating static benchmark executables.
> added: file for building opm modules static in your build tree

- cmake/Modules/OpmFiles.cmake
- cmake/Modules/OpmLibMain.cmake
- cmake/Modules/OpmStaticTargets.cmake
- add support for ADDITIONAL programs which are not built by default, yet not abandoned (i.e. attic doesn't fit)
- refine OpmStaticTargets/opm_from_git
- pass on toolchain file
- don't build examples in static directories
- allow non-install mode and custom targets
- use origin/master to make sure static source trees are built from the top should user re-execute the build in an existing build tree.
> Refine static targets

- cmake/Modules/FindParMETIS.cmake
- cmake/Modules/Finddune-istl.cmake
The AMG within dune-istl issues a warning if ParMETIS is not available.
The reason is that it uses ParMETIS or the ParMETIS bindings of PT-Scotch
to redistribute the load on the coarse levels. Even with an installed and
found PT-Scotch we need to adapt the include path and the libraries linked
to make it work.
Therefore this commit adds a module for searching for ParMETIS and activates
it whenever dune-istl is a dependency. With this the warning about missing
ParMETIS for flow_cp vanishes.
> Addes a module for finding ParMETIS or the ParMETIS interface of Scotch

- cmake/Scripts/configure
if the 'configure' wrapper is used, you will most likely use
dunecontrol. since duncontrol explicitly passes the paths for all the
dependencies, the "convenience" of the sibling search not wanted in
most cases.
> configure wrapper: disable the sibling search

- cmake/Modules/FindParMETIS.cmake
for me, 4292de413f56bb0511b26b7ee8412db88a9919de leads to linker errors
if the sequential metis library is required and the parallel version is not
installed.  see e.g.,
http://www.opm-project.org/CDash/viewBuildError.php?buildid=41290
The reason for this is a partial clash of the variable names which are
used by both modules. With this PR, the FindParMETIS module does not
write to any variables that are prefixed by "METIS_".
> FindParMETIS: use the FindMETIS module to deal with sequential METIS

- cmake/Modules/opm-material-prereqs.cmake
dune has a compatibility layer for std::conditional and some versions
of it emit a deprecation warning if the HAVE_TYPE_TRAITS macro is
undefined:
http://opm-project.org/CDash/viewBuildError.php?type=1&buildid=41175
> opm-material: add HAVE_TYPE_TRAITS to config.h

- cmake/Modules/opm-benchmarks-prereqs.cmake
- cmake/Modules/opm-polymer-prereqs.cmake
- cmake/Modules/opm-upscaling-prereqs.cmake
- cmake/Modules/opm-verteq-prereqs.cmake
a module requires at least headers to be marked as found by the macros
> changed: remove REQUIRED from opm-common

- cmake/Modules/FindParMETIS.cmake
This PR fixes a problem that occurs (for my tool chain) if I don't explicitly use the -DUSE_MPI=ON. Then opm-core fails to build because of MPI not been included but maybe required by third party packages.
> FindParMETIS: when USE_MPI is OFF the FindParMETIS check should not called.

- cmake/Modules/OpmSatellites.cmake
This is a work-around for an issue that presented when switching module opm-material's test framework to using the `opm_add_test` macro with automatically detected sources.  The macro would not find any
source files and subsequently end up effectively calling
```cmake
add_executable("${CURTEST_EXE_NAME}")
```
which promts CMake to respond with `incorrect number of parameters`.
There may be other, more fundamental, problems here, but this does at least restore the build of module opm-material on the Jenkins CI system.
> Use full path to auto-detected sources

- cmake/Modules/OpmSatellites.cmake
Commit f638ee8 contained a last-minute, untested change that caused downstream build failures.  Reference the correct variable,
```cmake
PROJECT_SOURCE_DIR
```
in place of the non-existent `CMAKE_PROJECT_SOURCE_DIR`.
Pointy hat: Bard.Skaflestad@sintef.no
> Reference correct variable in source-file auto-detection

- CMakeLists_files.cmake
- cmake/Modules/Findopm-common.cmake
- opm/common/utility/platform_dependent/disable_warnings.h
- opm/common/utility/platform_dependent/reenable_warnings.h
This PR will:
1. Add the warning disable/enable headers from opm-parser.
2. Updated the Findopm-common to actually search for the warning suppression header, so that Findopm-common can succeed. I guess `Findopm-common` will be updated again when a more interesting header is installed.
Currently the headers are also in opm-parser, but when/if this is merged I will create followup PR's in the other modules.
> Move warning suppression header

- cmake/Modules/dune-cornerpoint-prereqs.cmake
- cmake/Modules/opm-autodiff-prereqs.cmake
- cmake/Modules/opm-core-prereqs.cmake
After moving the headers to enable and disable external warnings to
opm-common, opm-common has become a required dependency for
dune-cornerpoint, opm-autodiff and opm-core.
> opm-common is REQUIRED

- CMakeLists_files.cmake
- opm/common/ErrorMacros.hpp
- opm/common/Exceptions.hpp
i.e., OPM_THROW(exception, message) and some excption classes.
note that this patch must be merged before those for the other modules but the others do not need to be merged after this one.
> add the error macros from opm-core

- cmake/Modules/Findopm-data.cmake
This caused trouble when the PROJECT_SOURCE_DIR is a symlink. When 'b' is a symlink, 'a/b/../' is not the same as 'a', but that is exactly what REALPATH does. In this case, it means that the opm-data is found (at ../ relative to the symlink), but the path that is set does not point to it.
This resulted in opm-data-dependent tests being run that then failed since the path was wrong.
This is the first time I have successfully debugged a cmake problem (message() is my new friend), so bear with me if the solution is rough... In order to get a release out soon, I'd appreciate a quick review (and merge if ok) by @andlaus, @bska, @joakim-hove, @blattms, @akva2 or @dr-robertk.
> Do not use REALPATH for OPM_DATA_ROOT.

- cmake/Modules/UseVersion.cmake
- cmake/Scripts/WriteVerSHA.cmake
The changes are (in the produced project-version.h headers):
- Add new macros PROJECT_VERSION_NAME and PROJECT_VERSION_HASH in addition to the existing PROJECT_VERSION.
- Add header include guards.
This will be included in the release (for rc2).
> Improve the UseVersion module.

- cmake/Modules/Finddune-alugrid.cmake
recently the `paramerge` branch has been made the new `master` version of dune-alugrid. this PR adapts the CMake module of the OPM build system to this change. Note that old versions of ALUGrid do not work with this anymore, but detecting whether a pre-merge or a post-merge version of dune-alugrid is installed would require a complete rewrite of Finddune-alugrid.cmake (as far as I can see). I'd appreciate if someone had a better solution.
> adapt Finddune-alugrid.cmake to the "paramerge" branch of dune-alugrid

- cmake/Modules/ConfigVars.cmake
newer versions of cmake (mine is 3.2.2) complain about policy CMP00054:
```
CMake Warning (dev) at /home/and/src/opm-common/cmake/Modules/ConfigVars.cmake:30 (if):
Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
Quoted variables like "FILE" will no longer be dereferenced when the policy
is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
/home/and/src/opm-common/cmake/Modules/OpmLibMain.cmake:173 (configure_vars)
CMakeLists.txt:109 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
since I'm pretty sure that the old …
> hack around CMake policy CMP00054

- cmake/Modules/Finddune-alugrid.cmake
The cmake version of dune-alugrid only provides one library. Therefore we need two checks here. 
The autotools check can be removed when support for dune 2.4 has been dropped (which will take a while).
> Finddune-alugrid: find the package when build with cmake or autotools

- .gitignore
- CMakeLists_files.cmake
- cmake/Modules/Findopm-common.cmake
- cmake/Modules/opm-common-prereqs.cmake
- opm/common/data/DataContainer.cpp
- opm/common/data/DataContainer.hpp
- tests/test_DataContainer.cpp
The main purpose of this PR is to tickle the build system into creating a new library `libopmcommon`, and ensure that the full build chain still works.
The actual content - `class DataContainer` - is meant to be used as a base class for / replacment for the `class ReservoirState` in opm-core - but that is somewhat into the future.
> Create library in opm-common

- cmake/Modules/FindERT.cmake
After: https://github.com/Ensembles/ert/pull/961 ert does no longer use #define based on probing for symbols in the header files. It should therefor be possible to simplify the FindERT.cmake module (somewhat ....)
> Simplified FindERT module

- cmake/Modules/OpmPackage.cmake
seems you cannot rely on the NOTFOUND postfix for compound if's.
addresses the valid issues from https://github.com/OPM/opm-material/issues/116
> fixed: workaround if() bug in cmake

- opm/common/data/SimulationDataContainer.cpp
- opm/common/data/SimulationDataContainer.hpp
- tests/test_SimulationDataContainer.cpp
With this in place - and https://github.com/OPM/opm-core/pull/954 merged - it should be possible to use the `SimulationDataContainer` as drop in replacement for `SimulatorState` in opm-core.
Currently this PR and: OPM/opm-core#954 can be merged independently.
> Added SimulationDataContainer::setCellDataComponent()

- cmake/Modules/dune-cornerpoint-prereqs.cmake
- cmake/Modules/opm-autodiff-prereqs.cmake
- cmake/Modules/opm-benchmarks-prereqs.cmake
- cmake/Modules/opm-core-prereqs.cmake
- cmake/Modules/opm-polymer-prereqs.cmake
- cmake/Modules/opm-porsol-prereqs.cmake
- cmake/Modules/opm-verteq-prereqs.cmake
as far as I can see, it is not used in any module except opm-upscaling
and it caused the configure stage to fail if I tried to use with a
self-compiled boost 1.60 (which I have to do in order to use clang on
any modern linux distribution.)
> remove the dependency on boost::iostreams if it is not used

- opm/common/data/SimulationDataContainer.cpp
- opm/common/data/SimulationDataContainer.hpp
Required - at least for now - for the `ParallellDebugOutput` implementation in opm-autodiff.
> Added non const cellData() access.

- cmake/Modules/opm-autodiff-prereqs.cmake
Previously, cmake succeeded even if opm-core or opm-common was not found.
The cause for this was that dune-cornerpoint was searched for first. As
it was not required it seems like opm-common and opm-core were treated as
optional, too.
This commit moves the opm modules to the opm section of the variable and
changes the order of the modules such that modules listed first do not
depend on modules listed afterwards. Now cmake fails if it cannot finy any
of the required modules.
> Make opm-core and opm-common a hard requirement.

- cmake/Modules/Findopm-output.cmake
- cmake/Modules/opm-output-prereqs.cmake
Currently opm-output will depend on opm-core when pushed out. This dependancy may be removed later. Should it?
The changes here will only be relevant for opm-output so it should be a safe PR
> Move OutputWriter to opm-output

- travis/build-opm-common-shared.sh
Added a travis build script to build a shared libopmcommon.
The underlying purpose of this is the same as for: #93.
> Added travis/build-opm-common-shared.sh

- cmake/Modules/OpmCompile.cmake
The purpose of this PR is to facilitate mixing of shared and static libraries; in particular this enables a static build of opm-common (the default) and a shared build of opm-parser (required for Python bindings).
This is mainly meant as a "glorified issue" - and not a ready to merge PR. Specifcally:
1. I don't know - maybe it is considered very bad form to mix static and shared libraries in this way?
2. Setting the flag globally from `OpmLibMain.cmake` is obviously not very clean - but I really had no clue of what was the Right&trade; location to set it?
> Add global target property: POSITION_INDEPENDENT_CODE

- opm/common/data/SimulationDataContainer.cpp
- opm/common/data/SimulationDataContainer.hpp
This is necessary in the short term to replace SimulatorState (in opm-core) with this class without performance loss. The intention is to enable merging of existing PRs (after some modifications) OPM/opm-core#962 and OPM/opm-autodiff#602. After that we'll move the explicit access function out of the SimulationDataContainer class and into concrete subclasses.
> Use reference pointers for fast field access.

- cmake/Modules/opm-material-prereqs.cmake
This PR will mark the `opm-common` module as required in the `opm-materiaø-prereqs.cmake` file. The ordering of `opm-common`  and `opm-parser` seems weird - but this seems to be what it takes!?
See: https://github.com/OPM/opm-common/pull/90
> Mark opm-common as required.

- cmake/Modules/opm-material-prereqs.cmake
packages marked REQUIRED must currently preceed optional ones. Also
C99 is not required by opm-material because that module only consists
of c++ code.
this is basically a follow-up of #92.
> opm-material-prereqs.cmake: fix the ordering of the dependencies

- cmake/Modules/opm-material-prereqs.cmake
Reverts OPM/opm-common#98
@andlaus this was necessary because of OPM/opm-core#985. Please resubmit if problem can be fixed.
> Revert "opm-material-prereqs.cmake: fix the ordering of the dependencies"

- cmake/Modules/opm-output-prereqs.cmake
- cmake/Modules/opm-upscaling-prereqs.cmake
Needed since CornerpointChopper and EclipseGridInspector is now in opm-output.
> Make opm-output REQUIRED for opm-upscaling.

- jenkins/README.md
- jenkins/build-opm-module.sh
- jenkins/build.sh
- jenkins/conv.xsl
- jenkins/convert.py
Hi,
I have been tasked with getting opm-output integrated in the Jenkins builds. The current Jenkins system has been annoying me to bits for a long time. Since I was going to work on it anyways, I decided to do a complete reboot.
The current Jenkins builds are fundamentally broken because they rely on global installations of the different modules. This by itself would not be a problem as such, however there is no upstream dependency tracking for build jobs, and jobs are spawned in parallel. This leads to all kinds of race conditions when multiple modules are updated in tandem. Which results in SPAM for whomever obtains the emails on build failures.
The only proper way to do it, is to build dedicated copies of dependencies as part of the build jobs, instead of using shared copies between …
> Jenkins reboot

- jenkins/setup-opm-data.sh
there are two modes:
- user supplies OPM_DATA_ROOT directly. in this case, the supplied
directory is copied into the workspace and used.
- user supplies OPM_DATA_ROOT_PREDEFINED. in this case, the
supplied path copied into the workspace unless a specific
PR is defined in the trigger comment.
is the commit message up to your standards now @bska ?
> add a jenkins script for setting up opm-data

- cmake/Modules/FindQuadmath.cmake
with this, it is now possible to disable quadruple precision math detection without hacks. (by setting USE_QUADMATH to ON or OFF)
(sometimes quadruple precision math is unwanted even though the compiler supports it.)
> refine FindQuadmath.cmake

- opm/common/ErrorMacros.hpp
This means that eventually all throws can be recorded in a log file, for example.
> Make OPM_THROW call OpmLog::error().

- cmake/Modules/OpmLibMain.cmake
- cmake/Modules/UseThreads.cmake
- cmake/Modules/opm-simulators-prereqs.cmake
This PR adds the necessary cmake functionality to add -pthread to the compiler flags. 
In addition HAVE_PTHREAD is added to config.h
USE_PTHREAD is ON by default an can be disabled setting it to OFF.
> Add pthread support.

- CMakeLists_files.cmake
- opm/common/OpmLog/LogBackend.cpp
- opm/common/OpmLog/LogBackend.hpp
- opm/common/OpmLog/LogUtil.cpp
- opm/common/OpmLog/LogUtil.hpp
- opm/common/OpmLog/Logger.cpp
- opm/common/OpmLog/Logger.hpp
- opm/common/OpmLog/MessageFormatter.hpp
- opm/common/OpmLog/OpmLog.cpp
- opm/common/OpmLog/OpmLog.hpp
- opm/common/OpmLog/StreamLog.cpp
- tests/test_OpmLog.cpp
This adds the possibility to configure how any back-end should decorate messages. Decoration here means adding a prefix and/or changing color depending on message type. The default is to have no decoration.
Actual decoration is handled by the concrete log backend calling the decorateMessage() protected method from the LogBackend superclass. So far only the StreamLog does this (it is the only log actually doing any output, all others inherit it).
Behavior should be preserved for now, with the exception of disappearing prefixes (like "warning: ") before log messages (unless client code configures the backend to use them).
I did some cleanup and docs for the LogBackend class, in the first commit, which can make reading the diff for that class a little unclear.
> Refine logging output

- cmake/Modules/ewoms-prereqs.cmake
this allows to remove the opm-parser dependency of opm-core without
breaking ewoms/ebos...
> ewoms-prereqs.cmake: make the optionaly depency on opm-parser explicit

- CMakeLists_files.cmake
- opm/common/OpmLog/CounterLog.cpp
- opm/common/OpmLog/CounterLog.hpp
- opm/common/OpmLog/EclipsePRTLog.cpp
- opm/common/OpmLog/EclipsePRTLog.hpp
- opm/common/OpmLog/LogBackend.cpp
- opm/common/OpmLog/LogBackend.hpp
- opm/common/OpmLog/Logger.cpp
- opm/common/OpmLog/Logger.hpp
- opm/common/OpmLog/MessageLimiter.hpp
- opm/common/OpmLog/OpmLog.cpp
- opm/common/OpmLog/OpmLog.hpp
- opm/common/OpmLog/StreamLog.cpp
- opm/common/OpmLog/StreamLog.hpp
- opm/common/OpmLog/TimerLog.cpp
- opm/common/OpmLog/TimerLog.hpp
- tests/test_OpmLog.cpp
- tests/test_messagelimiter.cpp
This changes the design of the LogBackend class and its subclasses, now the main virtual method is `addTaggedMessage()`. The former virtual method `addMessage()` is now a regular non-virtual method forwarding to `addTaggedMessage()`.
You can configure message limiting based on tags by passing a `MessageLimiter` to the `configureMessageLimiter()` method, which will then be used by the `includeMessage()` method. That method now takes an additional tag argument.
The most user-visible part of this is that there are new overloads of the static methods `OpmLog::warning()`, `OpmLog::error()` etc, that take message tags. To tie things together the `OpmLog` and `Logger` classes have also gotten new `addTaggedMessage()` methods, but they should mostly be used through the convenience methods such as …
> Message limits and tagged messages

- opm/common/OpmLog/OpmLog.cpp
- opm/common/OpmLog/OpmLog.hpp
- tests/test_OpmLog.cpp
Add a simple default logging which has std::cout as backend, use colored output. For prefix, user can set ``use_prefix`` to decide.
> Add default simple logging.

- opm/common/OpmLog/LogUtil.cpp
- tests/test_OpmLog.cpp
Using no code for black makes it easier to read output with color in editors etc.
> No longer emit default Ansi color code for black.

- cmake/Modules/FindERT.cmake
Ert has changed, and with it FindERT breaks.
> FindERT uses new EclKW interface.

- cmake/Modules/FindERT.cmake
The test program compiled fine, except that strings need to be escaped in CMake.
Mea culpa, signori.
> Fix typo in FindERT compile check

- opm/common/OpmLog/LogUtil.cpp
- opm/common/OpmLog/LogUtil.hpp
- opm/common/OpmLog/Logger.cpp
- opm/common/OpmLog/OpmLog.cpp
- opm/common/OpmLog/OpmLog.hpp
- tests/test_OpmLog.cpp
For some reasons, see https://github.com/OPM/opm-parser/pull/828. Lots of information that we don't want send them to stdout but  print file. This obviously can be done by the **tagged** functionality, but opm-parser does not support that, add a new message type could be the easiest way to achieve the target.
> Add prtinfo type

- opm/common/OpmLog/LogUtil.cpp
- opm/common/OpmLog/MessageFormatter.hpp
- tests/test_OpmLog.cpp
I think its better to make these four message types with prefix by default which can be a clear notification.
> Make Error, Problem, Error, Warning with prefix by default.

- cmake/Modules/opm-core-prereqs.cmake
- cmake/Modules/opm-output-prereqs.cmake
- travis/build-and-test.sh
Core depends on output, not the other way around.
See https://github.com/OPM/opm-output/pull/30
> Swap opm-core/opm-output dependencies

- jenkins/build.sh
update build order, opm-output moved in the dependency tree
> update jenkins build scripts

- cmake/Modules/Findopm-output.cmake
opm-output is about to remove the OutputWriter.hpp header, which means
this test program will break. Wells.hpp and default-constructed
data::Rates is a better fit for the future.
> Change Find-output test source code

- opm/common/OpmLog/LogUtil.cpp
- tests/test_OpmLog.cpp
For output, "msg + file name + line number" could be a better order. Just unify the output format as that for VFP checking in opm-parser.
> use the 'msg + file name + line number' format.

- cmake/Modules/FindCXX11Features.cmake
this test is quite fragile, takes relatively long and after OPM/opm-parser#850 it is not required anymore.
(actually, this PR can be merged independently of OPM/opm-parser#850: the effect is that HAVE_REGEX is always false.)
> FindCXX11Features.cmake: remove the test for `std::regex`

- cmake/Modules/FindERTPython.cmake
Make sure the ERT Python distribution is picked up if we are searching for an installed version in a non-standard location.
> FindERTPython will consider CMAKE_INSTALL_PREFIX.

- cmake/Modules/OpmPythonTest.cmake
- cmake/Modules/opm-simulators-prereqs.cmake
When working with output module comparison of the output files generated by flow with reference files is a quite common task. Schematically this involves the two steps:
1. Run `<TARGET_FILE:flow> input_file.data`.
2. Compare generated files with reference solution
Further requirements:
1. The comparison will typically involve floating point comparison of selected parts of Eclipse formatted output files - i.e. `diff` or similar shell utilities is to simple minded.
2. As seen from `cmake` the two steps must be coupled together as *one test*.
In this PR I suggest a python based solution, the solution consists of three parts:
1. `ERTPython` is added as an optional  requirement to `opm-simulator`. The Python distribution is built by default by ERT, and has been integrated in the travis build …
> Run Python / ERT based integration tests.

- cmake/Modules/FindERTPython.cmake
OK; build/travis hickup of Python test in opm-simulators.
Python code requires numpy - which is not checked for, and then fails. The update with this PR is to actually import the numpy requering offending class - thereby ensuring that the HAVE_ERT_PYTHON variable stays false.
> Findert python updates

- travis/build-and-test.sh
- travis/build-prereqs.sh
The python class: `ert.ecl.ecl_sum.EclSum` requires the `numpy` package; with this PR that is installed on the Travis build node before building. The `numpy` package is already installed on the Jenkins build server, that was why this was not discovered earlier - sorry about this last minute glitch.
Status Python based integration testing:
1. The dependencies are: python, `numpy` and the Python bindings for ert. If you are missing any of these the tests will be skipped silently.
2. Examples of tests are [here](https://github.com/OPM/opm-simulators/blob/master/CMakeLists.txt#L155) where some of the keywords from the INIT file in the SPE1 and Norne are compared with reference data - the script doing the comparison is [here](https://github.com/OPM/opm-simulators/blob/master/tests/compare_INIT. …
> Installing numpy using conda before building ert.

- cmake/Modules/Findopm-output.cmake
Added a CMake variable OPM_OUTPUT_BINARIES so that the CTest in [PR](https://github.com/OPM/opm-simulators/pull/754) can find the `opm-output/build/bin`-path.
> Added CMake variable OPM_OUTPUT_BINARIES

- cmake/Modules/Findopm-flowdiagnostics.cmake
- cmake/Modules/opm-flowdiagnostics-applications-prereqs.cmake
This commit recognizes the [opm-flowdiagnostics-applications](https://github.com/OPM/opm-flowdiagnostics-applications) module in OPM's centralised build system.  We make requisite changes to the FIND support for module opm-flowdiagnostics (header [`tarjan.h`](https://github.com/OPM/opm-flowdiagnostics/blob/master/opm/utility/graph/tarjan.h) is currently not public/installed) and make a first cut at explicit prerequisites for FD-Applications.
> Hook FD-Applications up to OPM build system

- cmake/Modules/FindERT.cmake
- cmake/Modules/FindERTPython.cmake
- jenkins/build.sh
- travis/build-prereqs.sh
In this https://github.com/Ensembles/ert/pull/1196 the ERT repository layout is changed to be more standard compliant. This PR updates jenkins/ and travis/ build configurations accordingly.
I will self-merge this when https://github.com/Ensembles/ert/pull/1196 has been merged - and this PR is green again; probably on monday.
> Ert repo reorg

- jenkins/build-opm-module.sh
- jenkins/build.sh
The reorganization allows handling ert as any other upstream except the necessary github url exception.
> simplify jenkins scripts after ert reorganization

- jenkins/build-opm-module.sh
- jenkins/build.sh
This adds multi-configuration support to the jenkins build scripts. It will be used to do mpi-enabled builds as well on jenkins. The mechanism is pretty simple; you have two environment variables BTYPES and CMAKE_TOOLCHAIN_FILES that is pre-filled by the user. Split and then put into an a-array instead of user supplying the a-array as those are a bugger on the command line. The toolchain files have 'full power', you can set compilers and options etc. (ie we can put -DUSE_MPI=1 in the toolchain file).
WIP, and includes PR #168 since i built on top of that.
@bska does this look acceptable ? should i remove the additional information?
Note that it will look slightly less clean in the output for downstreams (when some downstream is the main module), as i will have to clone opm-common first to …
> Add multiconfiguration support to jenkins scripts

- cmake/Modules/FindQuadmath.cmake
It needs to match the filename exacly, i.e. including the case.
> FindQuadmath.cmake: fix the first argument of find_package_handle_standard_args()

- cmake/Modules/Findopm-flowdiagnostics.cmake
This commit brings the system probe for module [opm-flowdiagnostics](https://github.com/OPM/opm-flowdiagnostics) up-to-date with recent changes in the public interface of the module's main entry point.  Commit OPM/opm-flowdiagnostics@8456e81 removed the nested type
```C++
Opm::FlowDiagnostics::Toolbox::PoreVolume
```
so we must drop all references to this type.
> Update opm-flowdiagnostics system probe for API change

- cmake/Modules/Findopm-output.cmake
- jenkins/build-opm-module.sh
This
- changes the name of cmake variables for locating regression test applications
- fixes a bug in the jenkins scripts, in particular, passing of opm-data root to the main module build.
Unrelated, but to aid testing I need a PR with both commits.
Replaces #161
> Change name of cmake variables and fix jenkins

- opm/common/data/SimulationDataContainer.cpp
- opm/common/data/SimulationDataContainer.hpp
This is because downstream code can benefit from the ordering guarantee.
Runs of small cases seem to have no differences and slowdowns, but I have not yet made a full Norne run to compare.
This should address the problem discussed in OPM/opm-simulators#772.
> Use map instead of unordered_map.

- opm/common/OpmLog/EclipsePRTLog.cpp
- opm/common/OpmLog/EclipsePRTLog.hpp
In a parallel run we need to be able to disable output in EclipsePRTLog
as only one process is allowed to output messages. This commit adds a
new defaulted constructor parameter to allow this.
> Allow disabling output in EclipsePRTLog.

- cmake/Modules/FindPETSc.cmake
newer petsc changed layout a bit. as of petsc 3.6.4 a
proper pkg-config file is ready for use.
additionally, align the find module with how petsc is expected to be
configured. the environment variable PETSC_DIR is the root of the source
tree and PETSC_ARCH is the build configuration, located in
$PETSC_DIR/$PETSC_ARCH
the old approach is kept for backwards compatibility but will not work
with newer petsc, in particular not if petsc is built static.
> changed: update petsc module for newer petsc

- cmake/Modules/Findopm-output.cmake
Due to upcoming changes in the opm-output: https://github.com/OPM/opm-output/pull/101 the Findopm-output module is updated. Due to the same ongoing updates we currently do not have any easily constructable symbols in opm-output, so the test does currently not involve linking.
Will update at a later stage when changes in opm-output have settled down.
This PR can be merged without any downstream changes, but it must be merged *before* https://github.com/OPM/opm-output/pull/101
> Update find output

- opm/common/ErrorMacros.hpp
The macro added is intended to solve a problem of noisy threads (in parallel) and also that exceptions due to linear solver trouble should be labeled "problem" and not "error" (i.e. it is quite common, and not something we can't handle). So this is intended as a replacement for #179.
Followup PRs are coming that will depend on this, but this can be merged independently.
@joakim-hove, @akva2: can one of you review this?
> Add OPM_THROW_NOLOG macro.

- cmake/Modules/FindCXX11Features.cmake
these defines are not used in OPM, but they are used in headers
from dune. 10x cola for me.
> fixed: turns out skipping the (unnecessary) c++11 tests cause issues

- cmake/Modules/opm-grid-prereqs.cmake
Since HAVE_DUNE_ISTL is used in the opm-grid, dune-istl needs to be tested for. It's as before not a hard dependency.
> [bugfix] since HAVE_DUNE_ISTL is used in opm-grid it should be tested for.

- cmake/Modules/Findcjson.cmake
- cmake/Modules/Findopm-parser.cmake
These fixes are needed to support externally installed cJSON libraries.
Please merge together with upcoming PR in opm-parser.
> Support external cjson

- cmake/Modules/opm-material-prereqs.cmake
a config.h variable was already set but the actual test was not run
for opm-material.
> opm-material: actually check for valgrind

- travis/build-and-test.sh
1. Disable ewoms testing.
2. Disable opm-upscaling completely
This should be temporary measures to get the Travis build testing to complete before it times out.
> Disable ewoms tests

- cmake/Modules/OpmCompile.cmake
Since this summer the situation with respect to warnings from third-party headers has been quite bad, since opm-parser stopped using the header suppression functionality. To avoid such warnings drowning out useful warnings I have been using the contents of this patch, which is something of a hack. One downside is that with this you will not get any warnings from headers in other modules than the one you currently compile, as they are tagged as system includes.
I hope some of the more cmake-skilled can comment on this and propose improvements so that we can get something like this by default.
> Silence warnings not from current module.

- cmake/Modules/OpmCompile.cmake
This makes the new behaviour of #202 optional, restoring old behaviour as default.
> Make use of system includes for cross-module optional.

- cmake/Modules/opm-grid-prereqs.cmake
previously opm-core guaranteed these.
Hopefully this is the last fallout from the grid/core reorganization.
> fixed: mpi and dune-istl needs to be explicity in opm-grid now

- CMakeLists_files.cmake
- opm/common/ResetLocale.hpp
Under some circumstances, some environments seem to set a locale which
they do not install. In turn this leads to std::runtime_errror being
thrown by some parts of Boost (for some versions) which causes
unsolicited program aborts.
This issue asside, it looks pretty weird if the e.g. the number format
is different than the that of the language used to print stuff by rest
of the simulation.
> Provide a free function to reset the localization settings

- CMakeLists_files.cmake
- opm/common/Valgrind.hpp
this moves the support code for quadruple precision floating point over from opm-material to opm-common. the rationale is that opm-common is a more natural place for this code and this functionality which may be useful in a wider scope than opm-material and its downstreams.
this PR requires some mob-up PRs for eWoms and opm-material.
> Minor reorg

- cmake/Modules/opm-flowdiagnostics-applications-prereqs.cmake
Incoming support for running solution acceptance tests in module [opm-flowdiagnostics-applications](https://github.com/OPM/opm-flowdiagnostics-applications) requires ability to work with regular expressions in C++.  OPM's minimum requirement of GCC 4.8 means we cannot rely on standard facilities in this respect.
> Request Boost.Regex to Support FD-Application Acceptance Tests

- opm/common/Valgrind.hpp
this emerged as during OPM/opm-material#200.
> move the infrastructure for valgrind client requests into the Opm namespace

- opm/common/utility/platform_dependent/disable_warnings.h
To avoid a lot of warnings from `mpi.h` when building in parallel.
> adding -Wcast-qual to disable_warnings.h

- opm/common/OpmLog/OpmLog.cpp
- opm/common/OpmLog/OpmLog.hpp
With this, it is now possible (at the call site) to turn off message colorization and change message tag limits when using the `setupSimpleDefaultLogging()` feature. Existing behaviour has been preserved with default arguments, so this PR requires no downstream changes (although it will trigger plenty of recompiles). Also added documentation for the function.
This should make it easier to start using logging functionality in programs such as the upscaling codes, as discussed in OPM/opm-grid#267.
Assigning @joakim-hove to review/merge as he has been involved with logging, but if any other maintainers feel like taking this please do.
> Make setupSimpleDefaultLogging() more flexible.

- cmake/Modules/FindERT.cmake
To support reading of files generated by IX there will be some changes to the ERT value types; hopefully silent. This is a preparation.
> Changed FindERT to create ecl_grid.

- CMakeLists.txt
caused issues with dune-control based builds.
> fix path written to in-tree config file

- cmake/Modules/FindCXX11Features.cmake
- cmake/Modules/Finddune-grid.cmake
This is needed to make OPM compile with 2.5. Otherwise dune-common
is not found because of missing std::decay_t support.
> dune 2.5 support

- cmake/Modules/FindERT.cmake
- travis/build-prereqs.sh
We have split the ERT repository in two parts, where the part relevant to OPM is located here:
https://github.com/Statoil/libecl
The existing Ensembles/ert repository will continue to work for some time; will gradually update the build system to use the new repository. When the sibling  build functionality is updated people will need to change repository, until then you should be able to sit 100% still.
> The travis build will use Statoil/libecl

- cmake/Modules/Findopm-core.cmake
namespace has been removed. Upstream of https://github.com/OPM/opm-core/pull/1160
> fix opm-core test

- cmake/Modules/UseOptimization.cmake
Changing default optimization from O2 to O3 has a large impact on computational performance, while it should not cause any problems. I have extensively tested the O3 option for weeks with no issues.
> Change release build optimization from -O2 to -O3

- opm/common/OpmLog/OpmLog.hpp
code is already in the namespace, some compilers consider this an error.
this PR is mainly to draw attention to the new static analysis jobs.
see https://ci.opm-project.org/job/opm-common-static-analysis/
each module will get such a job. they pull the git on a nightly schedule. this takes care of https://ci.opm-project.org/job/opm-common-static-analysis/1/testReport/junit/(root)/clang/cppcheck_opm_common_data_SimulationDataContainer_cpp/
> remove namespace qualifier

- opm/common/OpmLog/CounterLog.hpp
- opm/common/OpmLog/MessageFormatter.hpp
- opm/common/OpmLog/MessageLimiter.hpp
- opm/common/OpmLog/OpmLog.hpp
- opm/common/OpmLog/TimerLog.cpp
- opm/common/OpmLog/TimerLog.hpp
This quells all errors in this module.
- mark single-param constructors as explicit to avoid unexpected implicit casts
- initialize members (even though it does not point out a bug)
- pass by reference
- remove extra qualifications
> Fixes for warnings from static code analysis

- travis/build-prereqs.sh
It seems like OPM support for Dune 2.3 is going to be removed sooner rather than later. Also, all relevant distributions which I'm aware of seem to ship at least Dune-2.4 packages.
note that this patch switches to Dune 2.4.1 instead of the latest Dune
2.4 release (i.e., 2.4.2) because travis seems to block downloads from
sites it does not know -- in this case dune-project.org -- and the
Dune github mirrors seem to have been abandoned a few months ago and
thus do not feature dune 2.4.2.
> travis: switch from dune 2.3.1 to dune 2.4.1

- cmake/Modules/FindSuperLU.cmake
- cmake/Modules/OpmLibMain.cmake
make this default to off.
additionally, check that the found superlu version
is compatible with the dune-istl version in use.
in particular superlu5 is not compatible with dune-istl 2.4
this has been checked with dune-istl 2.4.1 on debian stretch (which defaults to superlu5). users should not be bitten any longer.
> changed: add option to disable superlu

- jenkins/update-opm-data.sh
The github API is paginated, and too many branches causes issues in the git-open-pull script.
> added: prune old branches from jenkins4opm remote on update_data calls

- jenkins/update-opm-data.sh
The generation of our devs is special. We have the attention span of the millennials and the memory of our parents ;)
This scripts around our limitations by checking for an existing PR for update-data calls. if it already exists,
the script just push the branch and comments on the PR it was triggered from.
> changed: do not open a new PR in repeated update-data calls

- cmake/Modules/Findopm-output.cmake
- cmake/Modules/OpmFind.cmake
- cmake/Modules/OpmPackage.cmake
- cmake/Modules/OpmSiblingSearch.cmake
- cmake/Templates/opm-project-config.cmake.in
We use ${module}_DIR to set the correct path when sibling search is activated. The package configuration files set all the necessary variables and we save us a lot of CMake magic.
Note that we previously used PkgConfig to find system installed DUNE and OPM packages. The paths found ended up as first hints in the find_* calls. Therefore the semantics might have been changed here. Previously system installed stuffed might have had higher priority than package found via sibling search.
We use the sibling search logic here as in the other modules.
This is at least a first step in simplifying our CMake scripts.
> Simplify dune/opm module search by relying on cmake package config files

- cmake/Modules/opm-simulators-prereqs.cmake
I am not sure if this is the correct place or correct way to do it. 
The reason for this is because a direct solver is required as part of the multisegment well solution procedure. 
Please suggest.
> [discussion] adding UMFpack to prerequisite of opm-simulators

- cmake/Modules/UseDuneVer.cmake
Since all supported DUNE versions have a CMake based build system,
when can drop the magic and use the module version exported by CMake
directly.
The magic used previously was broken when setting `CMAKE_INSTALL_LIBDIR` to
an absolute path.
> [cleanup] Use the module version that CMake exports directly.

- cmake/Modules/opm-simulators-prereqs.cmake
before OPM/opm-simulators#1309 it was required, but this was not enforced by the build system because the SuiteSparse tests are run by the opm-core build system first and UMFpack is optional there.
thanks to [at]akva2 and [at]blattms for the heads-up.
> don't mark UMFpack as required for opm-simulators

- cmake/Modules/OpmFiles.cmake
- cmake/Modules/OpmProject.cmake
With this commit @opm-project_NAME@_LIBRARY_DIRS will only be set if the module actually builds a library.
This should prevent linker warnings like 
```
ld: warning: directory not found for option '-L/path/opm-build-debug/opm-material/lib'
ld: warning: directory not found for option '-L/path/opm-build-debug/ewoms/lib'
```
> Only set the library directories if module builds a library.

- cmake/Modules/Findopm-core.cmake
it now sits in opm-common. yields confusing output as test
program compilation will succeed even if opm-common but not opm-core
is available.
> fixed: do not use ParameterGroup code in opm-core test program

- cmake/Modules/UseOptimization.cmake
It is useful for the CI system to have asserts enabled. While I could fiddle with CXX flags I think this is cleaner. ref https://github.com/OPM/opm-simulators/pull/1327
> added: option to not define NDEBUG for release builds

- CMakeLists_files.cmake
- opm/common/ConditionalStorage.hpp
- tests/test_ConditionalStorage.cpp
the class takes a boolean parameter as its first template parameter and a type name as the second. if the boolean parameter is false, nothing is stored, else an object of the type of the second template parameter gets created. this mechanism allows to disable member attributes based on compile time conditions.
The usage semantics of that class are that of a smart pointer class, i.e., the equivalent of
```c++
Foo foo;
foo.bar()
```
is
```c++
Opm::ConditionalStorage<true, Foo> foo;
foo->bar();
```
If the condition argument for the ConditionalStorage is false, that code will still compile but an exception is thrown at runtime.
> add a simple helper class that allows to store data members conditionally

- dune.module
since dune.module is primarily required for dunecontrol support and you cannot run dunecontrol without dune-common anyway, nothing changes for dunecontrol users.
for users who stubbornly refuse to use dunecontrol, nothing changes either because the dependencies are specified in opm-common-prereqs.cmake which stays untouched by this commit.
> add dune-common to the list of modules depended on by dune.module

- cmake/Modules/OpmInstall.cmake
- cmake/Modules/OpmProject.cmake
- cmake/Templates/opm-project-config.cmake.in
Otherwise implicit dependencies are search for. That was the case
for dune-geometry and dune-grid when configuring opm-core.
We also install the file now as wee need it for installed modules, too.
Fixes fallout of #304.
Closes #305.
> Include <module>-prereqs.cmake in <module>-config.cmake to process all dependencies

- opm/common/OpmLog/MessageLimiter.hpp
This bug did not affect Flow since it explicitly sets up all details related to logging. In parts of the code using default setups though, debug log messages would be suppressed.
> Corrected debug log output

- opm/core/utility/parameters/ParameterRequirement.hpp
quells a static analyzer warning
> changed: mark single-parameter constructor explicit

- cmake/Modules/Finddune-grid.cmake
- cmake/Modules/Finddune-uggrid.cmake
- cmake/Modules/OpmFind.cmake
UG will not work for newer DUNE versions any more.
This makes opm-grid compile with DUNE 2.6. Note sure whether this PR is all that is needed.
> Support dune-uggrid (successor of UG).

- cmake/Modules/OpmSatellites.cmake
- tests/test_OpmLog.cpp
- tests/test_SimulationDataContainer.cpp
- tests/test_cmp.cpp
- tests/test_cubic.cpp
- tests/test_messagelimiter.cpp
- tests/test_nonuniformtablelinear.cpp
- tests/test_param.cpp
- tests/test_sparsevector.cpp
- tests/test_uniformtablelinear.cpp
Downstreams: 
- https://github.com/OPM/opm-grid/pull/310
- https://github.com/OPM/opm-output/pull/254
- https://github.com/OPM/opm-simulators/pull/1406
- https://github.com/OPM/opm-upscaling/pull/250
Sidestream: 
- https://github.com/OPM/opm-parser/pull/1214
> fixed: set the boost dynamic test define if we build shared libs

- tests/test_OpmLog.cpp
- tests/test_SimulationDataContainer.cpp
- tests/test_cmp.cpp
- tests/test_cubic.cpp
- tests/test_messagelimiter.cpp
in most tests it already gets included, so let's fix that inconsistency The Right Way (TM).
> include config.h in all unit tests

- opm/parser/eclipse/EclipseState/Tables/SimpleTable.hpp
- src/opm/parser/eclipse/EclipseState/Tables/Tables.cpp
- tests/parser/integration/ParseKEYWORD.cpp
some rules are from testing output.
I removed
```
-        std::map<std::string, size_t> m_columnNames;
-        std::vector<std::vector<bool> > m_valueDefaulted;
```
from `SimpleTable`, potentially to reduce some confusion, since they are not used.
This PR is created for discussion, merge only when agreed.
> small fixes of the pvtables.

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Util/OrderedMap.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- tests/parser/OrderedMapTests.cpp
- tests/parser/ScheduleTests.cpp
Use `OrderedMap<Group>` to handle groups, to ensure that insert-order is retained.
> Ordered groups

- opm/parser/eclipse/EclipseState/Runspec.hpp
- opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
- src/opm/parser/eclipse/EclipseState/Runspec.cpp
- src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
- tests/parser/RunspecTests.cpp
- tests/parser/TableManagerTests.cpp
These values&mdash;region dimensions (REGDIMS) and well segment dimensions (WSEGDIMS)&mdash; are needed to correctly define portions of `INTEHEAD` in a restart step.
> Expose Additional Maximum Dimension Values to EclipseState Clients

- src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- src/opm/parser/eclipse/share/keywords/900_OPM/S/SPOLYMW
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
to initialize the polymer molecular weight.
Its unit is MDa, https://www.convertunits.com/info/MDa
For now, we treat it as a dimensionless value.
> adding keyword SPOLYMW

- src/opm/output/eclipse/Summary.cpp
In the case of restarted simulations this will embed the report step it has been restarted from in the generated SMSPEC file.
When this is merged you must update libecl to include: https://github.com/Statoil/libecl/pull/353
> Embed restart_step in restarted summary writer.

- src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PETOPTS
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/RSCONSTT
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
this adds the PETOPTS keyword and fixes the definition of RSCONSTT.
> Add PETOPTS

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
currently the only quantity that us used is the well temperature, i.e., specifying the fluid enthalpy does not have any effect.
> internalize the WINJTEMP keyword

- opm/test_util/EclFilesComparator.hpp
- src/opm/test_util/EclFilesComparator.cpp
The functionality to compare eclipse kewords from restart/iniit file would print a grid coordinate anyways if a comparison failed. This does not make much sense when e.g. comparing header keywords like `IWEL`; see for instance the test failure [here](https://ci.opm-project.org/job/opm-common-PR-builder/226/testReport/(root)/mpi/compareECLFiles_flow_SPE5CASE1/).
With this PR some size based heuristsics is used to infer whether a keyword represents of a 3D property - and should have i,j,k printed.
> Utility to compare keywords: check if grid parameter

- src/opm/output/eclipse/RestartIO.cpp
- tests/FIRST_SIM.DATA
Retrieve number of wells and completions at the beginning of the
simulated step. Otherwise a well introduced at the same time step as the
report will be included - even though there doesn't exist any simulated
data yet.
This issue would trigger a throw if WRFTPLT was added at the same time
step as a well is introduced in the schedule section.
The PR fixes https://github.com/OPM/opm-simulators/issues/1412.
It is necessary to change the reference timestep for which the simulator retrieves wells when initiating wellsmanager, otherwise this PR will introduce segfaults when a run is restarted at the same time as a well is introduced or there is a change in number of perforations. Necessary changes in simulator is added in https://github.com/OPM/opm-simulators/pull/1460
I have tried to be …
> Well info at correct step for save & load RESTART

- CMakeLists_files.cmake
- opm/output/eclipse/WriteRestartHelpers.hpp
- src/opm/output/eclipse/WellDataSerializers.cpp
- tests/test_serialize_ICON.cpp
The new function has been added to the file WriteRestartHelpers, and
intended to take over for the local function 'serialize_ICON' in
`restartIO.cpp` when `restartIO::save()` is to be updated.  The purpose
of the new implementation is to be compatible with Eclipse.
Note: this is just a rebasing of #393.
> Added new implementation of serialize_ICON

- CMakeLists_files.cmake
- opm/output/eclipse/WriteRestartHelpers.hpp
- src/opm/output/eclipse/WellDataSerializers.cpp
- tests/test_serialize_ICON.cpp
- tests/test_serialize_SCON.cpp
The value 'Kh' (effective for connection) is not directly available from
the Connection interface.  For the time being, a dummy value is used.
Computing the correct value for 'Kh' involves using the connection
transmissibility factor (avaliable), the well diameter (available), as
well as information about grid geometry (not immediately available), well
angle through connection cell (not immediately available, as far as I
can tell), and possibly a conversion factor.
Note: this is a rebase of #396.
> Added implementation of serialize_SCON

- CMakeLists_files.cmake
- opm/output/eclipse/EclipseIO.hpp
- opm/output/eclipse/RestartIO.hpp
- opm/output/eclipse/RestartValue.hpp
- src/opm/output/eclipse/EclipseIO.cpp
- src/opm/output/eclipse/RestartIO.cpp
- src/opm/output/eclipse/RestartValue.cpp
- tests/FIRST_SIM_THPRES.DATA
- tests/test_EclipseIO.cpp
- tests/test_RFT.cpp
- tests/test_Restart.cpp
- tests/test_writenumwells.cpp
When loading results from a restartfile they are returned in a container: `RestartValue` - and the calling scope will unpack it, however the corresponding `save( )` function takes the pieces which should be output more individually.
With this PR also the `save( )` function takes a `RestartValue` instance as input argument. In itself this change is not very interesting, but it is a preparation for storing `THPRES` values in the restart file.
> Save and load THPRES

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/WellTestConfig.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/WellTestConfig.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WTEST
- tests/parser/ScheduleTests.cpp
- tests/parser/WTEST.cpp
- tests/parser/data/integration_tests/IOConfig/RPT_TEST2.DATA
When a well is automatically closed by the simulator the WTEST keyword can be used to configure how the well should be tested as a candidate eligible for reopening.
With this PR a WellTestConfig object is added to the Schedule object. This PR configures *how* wells should be tested for reopening, it does not actually implement the reopening itself.
> Add WTEST configuration

- CMakeLists_files.cmake
- opm/output/eclipse/Summary.hpp
- opm/output/eclipse/SummaryState.hpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/output/eclipse/SummaryState.cpp
- tests/test_Summary.cpp
Preparation to check/look up summary variables run-time for e.g. UDQ / WTEST / ACTION and other niceties.
> Add SummaryState class to hold on to summary state.

- opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
- opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.hpp
- src/opm/parser/eclipse/EclipseState/EclipseState.cpp
- src/opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
- src/opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
- tests/parser/EclipseStateTests.cpp
- tests/parser/SimulationConfigTest.cpp
- tests/parser/ThresholdPressureTest.cpp
OK - in #391 we added support for writing THPRES data to restart file; now we are ready to read it.
> Ignore THPRES input for restart runs

- opm/output/eclipse/SummaryState.hpp
Required to compile with clang.
> Fix forgotten <string> include.

- opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCONHIST
- tests/parser/WellTests.cpp
and a zero-value THP limit for WCONPROD will not be treated as a THP limit.
The history matching part is slightly more tricky, was not handled by this PR yet.
> VFP related needs to be processed even without THP target/limit

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/WellTestState.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/WellTestState.cpp
- tests/parser/WTEST.cpp
This object should be instantiated and managed from the simulator; dangling here.
@totto82 : I hope this seems usable; please suggest changes.
> Add WellTestState object to keep track of automatically closed wells

- cmake/Modules/OpmProject.cmake
- cmake/Templates/opm-project-config.cmake.in
For this we need to set <dune-module>_PREFIX to some ominous value (at least for installed versions). ~I have no idea what I was thinking when implementing and naming it like this in DUNE.~ The name is actually correct, I just did not see it. <dune-module>_PREFIX  either set to where the module is installed to or the source directory for a build with uninstalled modules.
This is an ~untested~ shot to resolve the problem described in #300.
> Allow DUNE modules to locate the dune.module files during CMake run.

- opm/parser/eclipse/EclipseState/Schedule/WellTestState.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/WellTestState.cpp
quells a (recently introduced) static analyzer warning.
> fixed: pass by const ref

- src/opm/common/utility/numeric/calculateCellVol.cpp
Some compilers (notably GCC 5.4.0; default in Ubuntu 16.04) does not
do sufficient static analysis to determine that 'vect' is actually
exhaustively defined due to all indices being enumerated, and issue
a (spurious) warning that an unassigned value may be used.
This patch provides a default branch for the if-statements so that
'vect' is always assigned to, even in the eyes of the compiler. Since
entering this branch is unequivocally a bug, an assert is added so that
the null value is not mistakenly used.
> Add catch-all else clause to satisfy compiler

- opm/output/eclipse/Summary.hpp
- src/opm/output/eclipse/Summary.cpp
- tests/test_Summary.cpp
This change-set ensures that the following set of vectors are stored/updated in
Summary::add_timestep()
for all active wells and well groups (including FIELD):
* Production rates for Oil, Water, Gas, and Reservoir Volume (i.e., (O|W|G|V)PR).
* Cumulative production totals for Oil, Water, Gas, and Reservoir Volume (i.e., (O|W|G|V)PT).
* Injection rates for Water and Gas (i.e., (W|G)IR).
* Cumulative injection totals for Water and Gas ((W|G)IT).
* Producing Water Cut (WCT).
* Producing Gas/Oil ratio (GOR).
We additionally capture the well bottom-hole pressure (WBHP) for all wells that are active at the pertinent simulation step (sim_step).
Add an accessor function
```C++
const SummaryState& Summary::get_restart_vectors() const
```
that returns the `prev_state` which contains these summary …
> Summary: Calculate Independent Set of Vectors for Restart

- cmake/Modules/LibtoolArchives.cmake
Libtool uses libtool archive files (.la) to determine how to do a
platform-specific link. To generate these files, it is necessary to have
libtool installed on the system, since it will only accept files with
its own particular version number embedded. If libtool is not installed,
you probably don't need the libtool archive files either, so no .la is
generated. However, the status message sounded like libtool was probed
but not found, and that this was something that you should install.
This patch modifies the status message to make it more clear way libtool
was probed, and what the consequence of a missing libtool is (i.e. no
.la file for you).
> Improve status message when libtool is not present

- src/opm/common/OpmLog/OpmLog.cpp
MS gutted several of the POSIX functions a while ago under the pretense that these were in conflict with the C++ standard, since they contained non-underscored "vendor" functions. They have been moved to io.h
> Include vendor-specific header for isatty function

- examples/test_util/compareECL.cpp
- opm/test_util/EclFilesComparator.hpp
- src/opm/test_util/EclFilesComparator.cpp
In particular:
- Grid comparison will now also check that the active cells are the same,
not just that the number of active cells is identical.
- In the grid comparison, checking volumes is now optional, from compareECL
this feature is used by passing the '-V' option on the command line.
This replaces #439.
> Add more flexibility to compareECL.

- opm/parser/eclipse/EclipseState/Schedule/Connection.hpp
- opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
- src/opm/output/eclipse/RestartIO.cpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Connection.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQExpression.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/WellConnections.cpp
- src/opm/parser/eclipse/Units/UnitSystem.cpp
- tests/parser/UnitTests.cpp
This collects various minor fixes that probably have hurt no-one besides myself.
The first commit fixes a missing include (apparently transitively included on gcc).
The second fixes a buggy Segment::operator!=() and also cleans up warnings in that class.
The last just silences warnings in multiple files.
> Error and warning fixes

- src/opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
...for the Norne case at least, since it uses MULTREGT. For me this was ~3.5s out of ~5.5s total startup time.
Done by using a const reference instead of copying a map. Also use find() instead of operator[], the find() is guaranteed to succeed by the checks of the lines above it.
Found by profiling with Instruments, while looking for ill consequences of changing cell volume calculation (and not finding any).
> Massively improve the startup time for Flow

- opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp
- tests/parser/WellTests.cpp
for producers. The termination flag part is not handled yet.
The major difference is that, when we have `WHISTCTL` keyword, we overwrite the control mode (specified by the WCONHIST) instead of adding one. 
// TODO in the future
1. its effect on injectors, I guess only BHP control can be used or things can be more messy.
2. WHISTCTL is a schedule keyword. Its usage need to be verified by running.
> handling the over-writing control part of WHISTCTL

- CMakeLists.txt
- cmake/Templates/opm-project-config.cmake.in
While using dumux as a test case for using OPM from dune I stumbled over the error rerported in OPM/opm-grid#327:
```
CMake Error at /home/mblatt/src/dune/opm-2.6/opm-grid/opm-grid-prereqs.cmake:37 (find_package_deps):
Unknown CMake command "find_package_deps".
Call Stack (most recent call first):
/home/mblatt/src/dune/opm-2.6/opm-grid/opm-parallel/opm-grid-config.cmake:25 (include)
/home/mblatt/src/dune/opm-2.6/dune-common/cmake/modules/DuneMacros.cmake:178 (find_package)
/home/mblatt/src/dune/opm-2.6/dune-common/cmake/modules/DuneMacros.cmake:426 (find_dune_package)
/home/mblatt/src/dune/opm-2.6/dune-common/cmake/modules/DuneMacros.cmake:473 (dune_process_dependency_leafs)
/home/mblatt/src/dune/opm-2.6/dune-common/cmake/modules/DuneMacros.cmake:493 (dune_create_dependency_leafs) …
```
> Make calling prereq function possible without fuss

- opm/output/data/Wells.hpp
- opm/parser/eclipse/EclipseState/Schedule/Connection.hpp
- opm/parser/eclipse/EclipseState/Schedule/WellConnections.hpp
- opm/parser/eclipse/Units/UnitSystem.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Connection.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/WellConnections.cpp
- src/opm/parser/eclipse/Units/UnitSystem.cpp
- tests/parser/ConnectionTests.cpp
- tests/parser/MultisegmentWellTests.cpp
- tests/parser/UnitTests.cpp
- tests/parser/WellTests.cpp
- tests/test_RFT.cpp
- tests/test_Restart.cpp
- tests/test_Summary.cpp
- tests/test_Wells.cpp
Needed for restart output (especially, SCON), and also useful for computing the connection transmissibility factor (WI) in some cases if not supplied in COMPDAT.
For complete coverage, we also add a unit conversion type (`effective_Kh`) in order to produce SCON restart values that honour the run's unit conventions.  Finally, add simple checks for the unit conversion constants in the METRIC, FIELD, and LAB unit conventions to mirror the checks that were already there for PVT-M.
> Provide Effective Kh Product as an Extra Connection Property

- CMakeLists_files.cmake
- opm/output/eclipse/AggregateWellData.hpp
- opm/output/eclipse/CharArrayNullTerm.hpp
- opm/output/eclipse/VectorItems/intehead.hpp
- opm/output/eclipse/VectorItems/well.hpp
- opm/output/eclipse/WindowedArray.hpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/output/eclipse/InteHEAD.cpp
- src/opm/output/eclipse/Summary.cpp
- tests/test_AggregateWellData.cpp
- tests/test_CharArrayNullTerm.cpp
- tests/test_InteHEAD.cpp
- tests/test_WindowedArray.cpp
This change-set, a follow-up to #382 which was merged as #397, adds a new class that aggregates the `*WEL` vectors for restart purposes.  Using the data sources
* Simulation run's `Schedule` object
* Simulation run's `UnitSystem` object
* Current simulation step (`sim_step`)
* `WellRates` object from simulator at the end of `sim_step`
* `SummaryState` object from Summary class at the end of sim_step
this class will fill in the (presently) known elements of the `IWEL` (integers), `SWEL` (Real/float), `XWEL` (double precision), and `ZWEL` arrays for output to a restart file.  We distinguish contributions of data sources extracted directly from the simulation deck from those computed dynamically by the simulator--mostly to separate concerns and to enable independent testing.  If this …
> Revise Infrastructure for Well Arrays in Restart Files

- cmake/Modules/OpmSatellites.cmake
Currently there are two ways to add tests; either using the satellite system or by explicit calls to opm_add_test.
In the former, we remove the test_ prefix from test names. For the latter, we did not. This fixes the inconsistency.
> added: strip test_ prefix from tests added with opm_add_test

- jenkins/setup-opm-tests.sh
the update_data command needs a full opm-tests checkout,
not just a shallow clone of the PR branch. we thus first
copy the shared copy, then we pull the PR branch into that copy.
> fixed: allow using update_data with a opm-tests PR

- opm/parser/eclipse/Deck/DeckOutput.hpp
- src/opm/parser/eclipse/Deck/Deck.cpp
- src/opm/parser/eclipse/Deck/DeckOutput.cpp
Followup to https://github.com/OPM/opm-simulators/pull/1544
Increase output precision when writing deck streams.
> Add precision property to DeckOutput class - default = 10

- opm/parser/eclipse/Deck/Deck.hpp
- src/opm/parser/eclipse/Deck/Deck.cpp
- src/opm/parser/eclipse/EclipseState/InitConfig/InitConfig.cpp
- tests/parser/DeckTests.cpp
- tests/parser/InitConfigTest.cpp
- tests/test_Restart.cpp
Internalize the directory path of the datafile, to ensure that the path to restartfile is interpreted correctly. Should fix: https://github.com/OPM/opm-simulators/issues/1537
Test failure is due to line 31 here: https://github.com/OPM/opm-simulators/blob/master/tests/run-restart-regressionTest.sh
OK: The restart testi setup is based on searching for restart files from CWD and not from the location of the data file. Personally I think the semantics implemented by this PR is "correct", but of course that can be discussed. If we go for this semantcs we need to to make the following additional changes:
1. We can add a non-Eclipse commandline argument `--restart-path=` which means flow should search for restart files in this location instead of what is in the deck.
2. The setup must be updated …
> Restart cwd

- cmake/Modules/OpmDefaults.cmake
We have conducted quite extensive testing of the OpenMP implementation. In most cases it gives a nice performance improvement. In particular, the feature was turned on at linuxbenchmarking.com on August 5th, http://linuxbenchmarking.com/?open-porous-media-git , providing a good overview of typical performance impact.
In cases where you spawn more threads than there are resources on the hardware, the negative impact is very small. Hence, I suggest turning on OpenMP by default. Please note that a previous PR set the default number of threads to two per process (unless the number of available CPUs are less than twice the number of processes). This can be modified to a user specified number of threads per process at run time. Either through a command line switch, or through the usual …
> Make compiling with OpenMP default.

- opm/parser/eclipse/EclipseState/Grid/GridDims.hpp
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Grid/GridDims.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/EclipseGridTests.cpp
- tests/parser/SummaryConfigTests.cpp
Use plain C api for smspec node - instead of not-so-succesfull C++ wrapper. Later change to "proper" C++ implementation.
> Using plain C api for smspec_nodes

- CMakeLists.txt
I build opm-common as a shared library. This fixed my build.
> Fix build of tests when using shared library

- examples/test_util/EclRegressionTest.cpp
- examples/test_util/EclRegressionTest.hpp
- examples/test_util/compareECL.cpp
The compareECL program now has a new switch "-x" - if that switch is passed the program will not check that the number of keywords in two restart files is equal. Instead it will loop through all the keywords in the reference simulation and compare with the keywords from the new simulation.
The new switch is not used by jenkins in any way yet.
> Add option to ignore extra keywords in the regresstion testing

- tests/parser/ConnectionTests.cpp
Size must be equal to number of global (Cartesian) cells.
> Ensure Correctly Sized ACTNUM Vector

- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
- src/opm/output/eclipse/RestartIO.cpp
- src/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- tests/test_Restart.cpp
Problem: There is an incompatability between the restart files required for flow -> flow restart and flow -> eclipse restart. This PR is a first step towards facilitating a commandline switch akin to:
```
flow --opm-formatted-rst ....
```
which will write a restart file suitable for `flow -> flow` restart. This PR just adds a flag - and the necessary control logic - to the output code. The current PR does *not* imply any change in behaviour. When this has been merged the next step is to add a commandline option to `flow`. 
The loose plan behind the current PR is that the default behaviour will be to create an Eclipse compatible restart file, and that flow formatted will require an concious decision by the user. But that is a policy decision which must be taken as part of next PR; feel …
> Add opm_formatted property to the IOConfig

- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
See description here: https://github.com/OPM/opm-common/pull/488
This PR changes the default to Eclipse compatible restart files. This is a *policy* decision which I urge others to chime in on.
Downstream:
https://github.com/OPM/ewoms/pull/384
https://github.com/OPM/opm-simulators/pull/1569
**NB: For `flow` usage the more relevant default is the one used when registering the property tag - see: https://github.com/OPM/ewoms/pull/384**
> Make ecl compatible restart files default

- cmake/Templates/opm-project-config.cmake.in
Internally in equinor we have a system for installing inhouse developed software called Komodo[1]. That system stresses the cmake features of both the packages and the operators to the limit.
Currently I am struggling to build [sunbeam](https://github.com/Statoil/sunbeam/blob/master/CMakeLists.txt) which depends on opm-common through:
```
find_package(opm-common REQUIRED)
```
My installed version of `opm-common-config.cmake` ends like this:
```cmake
#ENABLE_ECL_INPUT is needed by opm-common-prereq.cmake
set(ENABLE_ECL_INPUT ON)
set(OPM_MACROS_ROOT /project/res/komodo/opm-common/root/share/opm)
list(APPEND CMAKE_MODULE_PATH ${OPM_MACROS_ROOT}/cmake/Modules)
include(OpmPackage) #Make macros availabe after find_package(opm-common)
set(COMPARE_SUMMARY_COMMAND …
```
> Komodo: cmake config changes

- opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.cpp
Since the ALQ value in WCON* keywords are not converted based on the unit of ALQ in the VFPPROD keyword, the interpolation can be wrong when ALQ value is there. 
This is a problem revealed during the debugging related to VFP/THP. The ALQ values in the WCON* keyword should have the same unit of the ALQ values in the VFPPROD keyword. We convert the unit of the ALQ values in the VFPPROD tables, while we do not convert the one in  the WCON* keywords. 
For some types of ALQ, like GRAT, it will cause the interpolation of the VFP tables crazy. 
This is the easiest "fix" I can imagine. I will use this for my debugging. Everyone is welcome to suggest some more correct fix for this problem. I will not be able to spend time on this very soon. 
There might be some testing failure.
> not converting the unit of ALQ value in VFPPROD

- src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
Reduces the amount of explicit arithmetic on `std::time_t` values and thereby, implicitly, the assumption of targeting Posix systems only.
Fixes #509.
> TimeMap: Use difftime() for Time Deltas as double

- opm/parser/eclipse/EclipseState/Schedule/WellConnections.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/WellConnections.cpp
This commit ensures that the data members 'headI' and 'headJ' are properly initialised in the constructor
```C++
WellConnections(const WellConnections&, const EclipseGrid&)
```
which in turn powers the implementation of
```C++
Well::getActiveConnections()
```
> WellConnections: Initialise Head in Copy Constructor

- opm/parser/eclipse/EclipseState/Schedule/GroupTree.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/GroupTree.cpp
Using const string as key type instead of plain string fails with libc++, the standard library implementation used by clang. The libc++ implementation assumes that map keys can be copied, and the standard requires map keys to be copyable.
Using `const string` as a value also fails with clang, I am not 100% sure why. It does severely restrict how you can interact with the container, and seems to make it noncopyable. The error is reported from `DynamicState<GroupTree>::update()`, the `std::fill()` call. Below is the horribly long compile message trail I get, it is somewhat hard to understand what is going on.
@joakim-hove I think this should be picked into the release branch due to severity (compilation failure).
```
In file included from …
```
> Use non-const string type in map.

- opm/parser/eclipse/Parser/ParseContext.hpp
- src/opm/parser/eclipse/Parser/ParseContext.cpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- tests/parser/ParseContextTests.cpp
With this it is possible to add keywords to the `ParseContext` which should be ignored.
>  Ability to ignore named keywords in ParseContext

- cmake/Modules/FindAlberta.cmake
- cmake/Modules/Finddune-grid.cmake
We do not use it in OPM, but for whatever reason I was experiencing
linker errors (unresolved symbol) when compiling ebos with DUNE 2.6
and g++-8.2. dune-grid exports its alberta wrapper libraries in dune-grid_LIBRARIES. Previously this did not pose a problem. Somehow it does now. If
I strip the libraries from the linker line everything is fine but this
is not a good solution.
Therefore I have added a test for Alberta that is triggered by the test of
dune-grid.
> Also search for Alberta (Fixes ebos compile issue with g++-8.2)

- CMakeLists.txt
- examples/msim.cpp
- msim/include/opm/msim/msim.hpp
- msim/src/msim.cpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
- tests/msim/test_msim.cpp
Have just added an absolute minimum cmake skeleton for an "input simulator". For the more advanced prediction based functionality we will need tighter interaction between the simulator and the data structures from opm-common.
This is a zeroth step in creating a test-bed to work back-and-forth between opm-common datastructures (typically what is in the `Schedule` classes) and the simulator. 
Comments welcome
> Add skeleton for input simulator

- opm/parser/eclipse/EclipseState/Grid/GridProperty.hpp
- src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- src/opm/parser/eclipse/EclipseState/Grid/GridProperty.cpp
- tests/parser/Eclipse3DPropertiesTests.cpp
The deckAssigned() query method is added to the GridProperty class to enable the
simulator to check whether a property has been explicitly assigned in the deck
or autocreated through the use of some EDIT operators like MULTIPLY.
The current opm parser functionality is quite weak on the *section* concept; i.e. we implement section awareness in the parsing process in a very limited degree. The fundamental ugliness in this problem - that the simulator should interpret the `TRANX` kyeword either as an absolute value, or alternatively as a multiplier, remains the same, but one can envision an alternative implementation based on a more section aware parsing process.
It was my intention to propose a downstream patch according to this [pseudo …
> Add deckAssigned() method to GridProperty + default construct TRAN

- opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
- src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MINPVV
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
- tests/parser/EclipseGridTests.cpp
Currently the code does not work with BOX and modifier keywords. A naive implementation would lead to circular dependency between EclipseGrid and EclipseState. @joakim-hove Any suggestions?
> Add support for minpvv

- src/opm/output/eclipse/Summary.cpp
- tests/summary_deck.DATA
- tests/test_Summary.cpp
The PR applies the PI multiplier just as opm-simulator does.
> Include WPIMULT for CTFAC output

- opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
- src/opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/T/THERMAL
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
- tests/parser/SimulationConfigTest.cpp
This commit introduces a new predicate,
```C++
bool SimulationConfig::isThermal() const
```
that determines whether or not either of the keywords
TEMP or THERMAL
are specified in the RUNSPEC section of a simulation run.
> Simulation Config: Add Predicate for Thermal Simulations

- src/opm/output/eclipse/Summary.cpp
- tests/FIRST_SIM.DATA
- tests/test_RFT.cpp
- tests/test_Restart.cpp
This commit, a preparation for restoring cumulative quantities from a restart file, reinitialises Summary::prev_time_elapsed in the case of simulation restart and adds a check to
```
Summary::write_timestep()
```
which throws if the input argument `secs_elapsed` is prior to the previously recorded elapsed time.  The latter is a change in the behaviour of `write_timestep()`, but ensures that we don't integrate rate quantities across a very large timestep in the case of simulation restart and also prevents double accumulation.
Update impacted unit tests accordingly, and move FIRST_SIM's START date into the RUNSPEC section where it belongs.  Note, in particular, that we alter the setup of `test_RFT.cpp:test_RFT2` here.  Previously that test would use a single `EclipseIO` object for both …
> Summary: Ensure that we don't step backwards during simulation

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/ActionAST.hpp
- opm/parser/eclipse/EclipseState/Schedule/ActionContext.hpp
- opm/parser/eclipse/EclipseState/Schedule/ActionX.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/ActionAST.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/ActionContext.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/ActionX.cpp
- tests/parser/ACTIONX.cpp
Will parse - and evaluate - the condition part of the ACTIONX keyword. Remaining steps:
1. Initialize the `ActionContext` object with proper values from the simulation, right now it is just explicitly assigned in tests.
2. Actually apply the keywords in the `ACTIONX` block.
3. Hook it all up in the simulator. 
Continuation of: https://github.com/OPM/opm-common/pull/539
> Actionx parse

- src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/STONE
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/STONE2
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
- tests/parser/ParserTests.cpp
This commit makes the parser aware of the keywords `STONE` and `STONE2` which both request that the simulation run use Stone's second model for three-phase relative permeability for oil.
The [material law manager](https://github.com/OPM/opm-material/blob/7cac10640e596047a03d86e8dc06f2aa9dbb2936/opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp#L465-L466) knows about these models and treats the former as an alias for the latter.
Note that we do not implement mutual exclusion between the Stone models in this PR.  If an input deck specifies (e.g.,) **both** `STONE` and `STONE1`, then this will silently imply `STONE2`.
Is there a way of recognising that mutually exclusive keywords have been supplied in the input deck?
> Recognise Requests for Stone's Second Model of 3-Phase Oil Relperm

- src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/RSCONST
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/RSCONSTT
- tests/parser/ParserTests.cpp
This commit ensures that we never try to read more than a single record of data when parsing the `RSCONST` keyword.  Previously, the parser would attempt to parse `RSCONST` as if it were an unbounded keyword that was terminated by an empty record.  This, in turn, would produce the diagnostic message
```
Inner exception: Malformed floating point number 'INCLUDE'
```
when trying to read a specification like
```
RSCONST
0.35  932  /
-- Check for these data in the future this is important
INCLUDE
'RP.dat'  /
```
While here, also implement `getSIDouble()` for the Rs value (item 1) in keywords `RSCONST` and `RSCONSTT` by adding the correct unit of measurement ("dimension") to the keyword specification.
Add unit tests to verify new behaviours.
> Correct RSCONST and RSCONSTT Specifications

- opm/parser/eclipse/EclipseState/IOConfig/IOConfig.hpp
- src/opm/parser/eclipse/EclipseState/IOConfig/IOConfig.cpp
- tests/parser/IOConfigTests.cpp
See: https://github.com/OPM/opm-simulators/issues/1653
The current PR is one approach; personally I do not see any very good and clean solution. Opinions welcome!
> Force UPPER_CASE when input deck has MixeDCase basename

- opm/parser/eclipse/EclipseState/Aquancon.hpp
- opm/parser/eclipse/EclipseState/AquiferCT.hpp
- src/opm/parser/eclipse/EclipseState/Aquancon.cpp
- src/opm/parser/eclipse/EclipseState/AquiferCT.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCT
- tests/parser/AquanconTests.cpp
- tests/parser/AquiferCTTests.cpp
* This will fix the issue where default values of the influx_coeff and aquifer pressure is required. Now it scans for nullptr instead.
* Corrects for the issue where only the global_index vector gets resized but not the other vectors.
Downstream: https://github.com/OPM/opm-simulators/pull/1571
> Fix for aquifer making connection

- opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.hpp
- src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
This needed for parallel runs as otherwise all processes will do logging. There will be a acompanion PR in ewoms
> Allow to switch of logging during getWriteRestartFile call.

- tests/test_RFT.cpp
- tests/test_Summary.cpp
Commit 334dbe4e (PR #579) broke GCC 4.9 (invoking explicit constructor with an empty `initializer_list<>`).  Restore build by using the actual type.
> Restore Build on GCC 4.9

- src/opm/output/eclipse/AggregateConnectionData.cpp
The previous logic was slightly incomplete in that it checked size inconsistencies for all connections, not just open connections. This, in turn would in turn generate diagnostics like
```
Report step 19/247 at day 252/3312, date = 16-Jul-1998
Time step 0, stepsize 16 days.
ERROR: Uncaught std::exception when running tasklet: Inconsistent number of open connections I in vector<Opm::data::Connection*> (3) in Well B-4H. Trying to continue.
```
With this update we look for size inconsistencies between a well's open connections and `data::Wells::connections` only.
This fixes #581
> Check Size Inconsistencies Only for Open Connections

- examples/test_util/compareECL.cpp
- examples/test_util/summaryRegressionTest.cpp
- examples/test_util/summaryRegressionTest.hpp
This commit adds the ability of `SummaryRegressionTest` to bypass the check for equal number keywords/summary vectors in the two result sets being compared.  The primary purpose of this is to continue comparing contents of existing summary vectors if new summary keywords are introduced in a GitHub Pull Request.
Extend the `compareECL` utility to take advantage of this ability.
> Make Summary Comparison Able to Ignore Different Number of Keywords

- src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
In PR #578 a bool was introduced that should determine whether we log warnings
during RestartConfig::getWriteRestartFile. Unfortunately, it introduced a bug that
made a false value of log return false from the function. This is fixed by this commit.
The bug fixed here made some parallel runs segfault. Sorry for the inconvenience.
> [bugfix] Fix influence of logging on return of getWriteRestartFile

- opm/parser/eclipse/EclipseState/EclipseConfig.hpp
- opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.hpp
- opm/parser/eclipse/Parser/ParseContext.hpp
- src/opm/parser/eclipse/EclipseState/EclipseConfig.cpp
- src/opm/parser/eclipse/EclipseState/EclipseState.cpp
- src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
- src/opm/parser/eclipse/Parser/ParseContext.cpp
- tests/parser/IOConfigTests.cpp
- tests/parser/RestartConfigTests.cpp
We now handle:
```
RPTRST
BASIC = 2 /
```
i.e. unquoted spaces around the "=". Regulated by the error mode `RPT_MIXED_STYLE` which defaults to `WARN`.
@alfbr: Please give this a spin and merge if appropriate.
> Parsecontext rpt

- opm/parser/eclipse/EclipseState/EclipseState.hpp
- src/opm/parser/eclipse/EclipseState/EclipseState.cpp
1. Remove `ParseContext` *member* from `EclipseState` class.
2. Change `EclipseState` constructor to take `const ParseContext&` argument instead of `ParseContext`
> Rm parsecontext

- opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
- tests/test_Summary.cpp
This PR adds a small method: `SummaryState::wells(const std::string&var)` which can be used to get a list of all the wells which are registered with a certain variable, i.e.
```C++
const auto& wwct_wells = summary_state.wells("WWCT");
```
will give you a `std::vector<std::string>` of all the wells which have a registered `WWCT` value in the `SummaryState` object. 
This functionality is needed for the `ACTIONX` implementation here: #566
> Add method wells() to the SummaryState class

- src/opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
- tests/parser/MULTREGTScannerTests.cpp
- tests/parser/integration/ParseKEYWORD.cpp
With this 
```
MULTREGT
1 2 1 /
2 1 2 /
/
```
will multiply transmissibilities between region 1 and 2 with 2.
> Make the ordering of MULTREGT arbitary

- src/opm/output/eclipse/Tables.cpp
- src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/ParseContext_EXIT1.cpp
- tests/test_Summary.cpp
The most exotic new one is related to the lambdas in Tables.cpp. The explanation is that, according to https://en.cppreference.com/w/cpp/language/lambda:
"A lambda expression can read the value of a variable without capturing it if the variable
- has const non-volatile integral or enumeration type and has been initialized with a constant expression, or 
- is constexpr and trivially copy constructible."
> Silence various warnings discovered with new version of clang.

- opm/parser/eclipse/EclipseState/Schedule/ActionAST.hpp
- opm/parser/eclipse/EclipseState/Schedule/ActionContext.hpp
- opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/ActionAST.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/ActionContext.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
- tests/parser/ACTIONX.cpp
- tests/test_Summary.cpp
The `ACTIONX` keyword can use wellname `?` which will be replaced with "All matching wells". 
There is some remaining ambiguity when it comes to nested conditons: https://github.com/OPM/opm-common/pull/566/commits/ce70d3a964b398f1a4267ce30ed564e6a6954f6c#diff-edbe5d8d3087796daa51ea7d26a7f8d1R170 - this will require a fine reading of the manual, and maybe some expert input.
> Add functionality to capture matching wells when evaluating ACTIONX

- opm/parser/eclipse/EclipseState/Schedule/WellInjectionProperties.hpp
- opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/WellInjectionProperties.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/WellProductionProperties.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/WellTests.cpp
- tests/parser/data/integration_tests/SCHEDULE/SCHEDULE_SHUT_WELL
Otherwise, we will get zero value BHP limits for history matching wells. 
With WELTARG and a well switching between injector and producer, the answer is unknown at this stage. 
It should be addressed in another PR with testing cases. 
In anyway, this PR makes things `more` correct and address some issue originally thought to be related to `ORAT`. It is a BHP limit problem. 
The downstream PR is https://github.com/OPM/opm-simulators/pull/1362 .
> fixing the BHP limit for the history matching wells

- jenkins/build-opm-module.sh
this is purely optional. opm-material will use this to make sure that auto-generated code does not get manually modified.
> jenkins: allow modules to specify a pre-build check

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/WList.hpp
- opm/parser/eclipse/EclipseState/Schedule/WListManager.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/WList.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/WListManager.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WLIST
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
- tests/parser/WLIST.cpp
The `WLIST` keyword is used to manage lists of wells. The motivation for implementing it here is to support the `ACTIONX` keyword where it is used - but I think that well lists can be used also in many of the other SCHEDULE keywords, but we have not encountered them in the wild yet,
> Add WList implementation

- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/SummaryConfigTests.cpp
- tests/summary_deck.DATA
- tests/test_Summary.cpp
This pullrequest contains an extension of the output of phase potential injection and production rates to Summary file for group levels and field level. The work here is based on the same output for wells, done in pullrequest #554 by @totto82 who also is informed about this addition. 
I will thank my collaborator @bska for valuable discussions and advice during the work.
> Add output of group and field phase potential injection and production rates to Summary file

- jenkins/build-opm-module.sh
the warning is
```
/var/lib/jenkins/workspace/opm-material-PR-builder/deps/opm-common/jenkins/build-opm-module.sh: line 88: cd: -D: invalid option
```
possibly, it is caused by `pushd` modifying the $1 variable (WTF?).
@akva2: this should fix the warning which you pointed out in OPM/opm-material#322. also, that warning probably appeared in every build since #605 was merged.
> try to get around a non-fatal bash warning in the jenkins build script

- src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
- tests/parser/TimeMapTest.cpp
If unit system is LAB, the TSTEP is interpreted as hours not days
> Fix TSTEP unit in LAB mode

- CMakeLists.txt
- examples/msim.cpp
- msim/include/opm/msim/msim.hpp
- msim/src/msim.cpp
- tests/msim/test_msim.cpp
Since ~October the opm-common codebase has had a mock simulator class `msim` - which has been added to simplify testing of `Schedule` / simulator interaction, in particualar inspired by the ongoing `ACTIONX` efforts.
The `msim` simulator has been hidden behind a CMake setting `ENABLE_MOCKSIM` which has been defaulted to `OFF`. With this PR the `ENABLE_MOCKSIM`defaults to `ON`, in addition there are some changes in the `msim` implementation - specifically it does *not* hold on to a `Schedule` object.
The first commit was just a minor reformatting I "needed" in a debugging effort; happy to skip that commit.
> Turn on the mock simulator by default

- src/opm/parser/eclipse/EclipseState/Schedule/Action/WellSet.hpp
This is necessary to avoid compile errors with clang. I guess <unordered_set> transitively includes <string> when using gcc's libstdc++.
> Add missing <string> include.

- opm/output/eclipse/EclipseIO.hpp
- src/opm/output/eclipse/EclipseIO.cpp
The `ACTIONX` needs access to the `SummaryState`object which has been properly initialized by the IO routine. The current PR is a not-very-elegant temporary fix, the slightly longer term fix to extract the `SummaryState`object out to application scope, but that will interfere with other ongoing work - so that can wait a bit.
> Export SummaryState from EclipseIO object

- opm/parser/eclipse/Parser/ParseContext.hpp
- src/opm/parser/eclipse/Parser/ErrorGuard.cpp
- src/opm/parser/eclipse/Parser/ParseContext.cpp
Add `ParseContext` recognized errors for unsupported keywords.
> Simulator missing keyword

- src/opm/output/eclipse/RestartIO.cpp
it looks like in data::Wells the index is global index.
The symptom is that for cases with non-active cells, which are the most of the practical cases, perforation rates and perforation pressure are not written in the UNRST file. 
Not saying this is the most proper way to fix the problem, while it points to the cause of the problem. 
In https://github.com/OPM/ewoms/pull/283 , we have already removed the perforations that locate in the inactive cells in the `schedule`, not sure whether this information can be used in the this part. 
I believe @bska has all the insight about this issue.
> [Disussion]using global_index in serialize_OPM_XWEL()

- tests/parser/UDQTests.cpp
to avoid unused variable compiler warnings
> changed: add some harmless comparisons to test

- src/opm/parser/eclipse/EclipseState/Schedule/WellConnections.cpp
- tests/parser/ScheduleTests.cpp
`COMPLNUM` is a method to join connections together as a *completion*, and then subsequently treat all those connections as one logical entity. If a completion number has not been explicitly assigned with the `COMPLNUM` keyword the connections get an automatically assigned completion number corresponding to the insert order of the connection. 
Previously we assigned negative numbers when assigning completion numbers automatically, to protect against mixing automatically assigned completion numbers and those which have been assigned with `COMPLUMP` - so although the explicit separation of manually and automatically assigned completions seem like a sane idea - in my opinion, it seems to be a feature that it should be possible, so now we implement this to. It should be noted that it is …
> Initial completion number set to connection number

- src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp
add `#include <cstdlib>` to support older version of clang.
> include `<cstdlib>`

- opm/output/eclipse/DoubHEAD.hpp
- opm/output/eclipse/LogiHEAD.hpp
- opm/output/eclipse/VectorItems/well.hpp
- opm/parser/eclipse/EclipseState/Runspec.hpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/output/eclipse/CreateDoubHead.cpp
- src/opm/output/eclipse/CreateLogiHead.cpp
- src/opm/output/eclipse/DoubHEAD.cpp
- src/opm/output/eclipse/LogiHEAD.cpp
- src/opm/parser/eclipse/EclipseState/Runspec.cpp
- tests/test_LogiHEAD.cpp
Changes are necessary to avoid Errors in Eclipse when restarting from a flow simulation  when using Hysteresis option and wells that allows crossflow.
> Add changes to correct problems/errors with Eclipse restarts from flow  with hysteresis and well crossflow

- src/opm/output/eclipse/Summary.cpp
With #632 the behaviour with summary variables was somewhat changed; you configure the summary variables you want - and then subsequently the summary object asks for them. At the time I thought only the (not yet activated) `UDQ` variables would create these warnings, but that seems to not be the case.
Temporarily just removing the warning.
> Temporarily remove warning about missing summary variables

- opm/parser/eclipse/Parser/ParseContext.hpp
- src/opm/parser/eclipse/Parser/ParseContext.cpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
- tests/parser/ParseContextTests.cpp
- tests/parser/ParserTests.cpp
The ParserContext error mode PARSE_LONG_KEYWORD is used to handle keywords
longer than 8 characters. The lenient option is to only consider the first 8
characters.
> Add ParseContext::PARSE_LONG_KEYWORD

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/ArrayDimChecker.hpp
- opm/parser/eclipse/EclipseState/Schedule/GroupTree.hpp
- opm/parser/eclipse/Parser/ParseContext.hpp
- src/opm/output/eclipse/CreateInteHead.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/ArrayDimChecker.cpp
- src/opm/parser/eclipse/Parser/ParseContext.cpp
- tests/expect-wdims.err.out
- tests/test_ArrayDimChecker.cpp
Add Tool for Checking Array Dimensions
This pull request&mdash;a second take on the previously proposed #636&mdash;introduces a new function,
```C++
Opm::checkConsistentArrayDimensions()
```
that inspects various dynamic array/table sizes and compares those to the maximum dimensions requested in the relevant `*DIMS` keywords of the `RUNSPEC` section.
At present we check only items one (1) through four (4) of `WELLDIMS` since those are directly relevant for the ECLIPSE-compatible output code. We leverage the `ErrorGuard` to integrate into the existing mechanism for terminating a simulation run if there's a parse failure.
Going through the `ParseContext`, we allow a user to opt in to run a case that violates one or more of these upper bounds.  In this case, we will size the output arrays of …
> Add Array Dimension Consistency Checker (Take 2)

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Runspec.hpp
- opm/parser/eclipse/EclipseState/Schedule/UDQContext.hpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQContext.cpp
- tests/parser/UDQTests.cpp
- tests/summary_deck.DATA
- tests/test_Summary.cpp
This PR will hook the UDQ system up to the summary output system; i.e. if you have asked for summary output of UDQ variable `WUBHP` you will get entries n the summary file with the correct keyword, and unit . but the numerical value will just be the UDQ default value.
> Summary udq

- CMakeLists_files.cmake
- opm/output/eclipse/AggregateGroupData.hpp
- opm/output/eclipse/DoubHEAD.hpp
- opm/output/eclipse/RestartIO.hpp
- opm/output/eclipse/Summary.hpp
- opm/output/eclipse/VectorItems/connection.hpp
- opm/output/eclipse/VectorItems/doubhead.hpp
- opm/output/eclipse/VectorItems/group.hpp
- opm/output/eclipse/VectorItems/msw.hpp
- opm/output/eclipse/VectorItems/well.hpp
- opm/output/eclipse/WriteRestartHelpers.hpp
- src/opm/output/eclipse/AggregateConnectionData.cpp
- src/opm/output/eclipse/AggregateGroupData.cpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/output/eclipse/CreateDoubHead.cpp
- src/opm/output/eclipse/DoubHEAD.cpp
- src/opm/output/eclipse/EclipseIO.cpp
- src/opm/output/eclipse/LoadRestart.cpp
- src/opm/output/eclipse/RestartIO.cpp
- src/opm/output/eclipse/Summary.cpp
- tests/test_AggregateWellData.cpp
- tests/test_Restart.cpp
- tests/test_Summary.cpp
This work-in-progress pull request extends the gateway restart function
```
RestartIO::load()
```
to also support starting a Flow simulation from an existing ECLIPSE compatible restart file.  This is the logical pairing of the previous PR #454 which added support for outputting such restarts files from Flow. 
We change the return type of `RestartIO::load()` from `RestartValue` to
```
std::pair<RestartValue, SummaryState>
```
with the pair's '.second' containing a small subset of the cumulative quantities available in the restart file's `XWEL` and `XGRP` output vectors.  That value is then passed into a new mutating function
```
Summary::reset_cumulative_quantities()
```
which overwrites the cumulative values of its internal `prev_state` object.
There are some aspects of this proposal that …
> Add Support for Restarting Flow from ECLIPSE Compatible Restart File

- CMakeLists.txt
Simpify by
- using opm_add_test
- remove the now unnecessary manual setting of the BOOST_TEST_DYN_LINK property (now done by opm_add_test)
> some cleanup in buildsystem

- src/opm/parser/eclipse/share/keywords/900_OPM/B/BCRATE
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
Question? Can I use more than 8 characters for the OPM specific keywords?  I may want to add a MOLRATEBC keyword in the future and want reasonable names.  
This is currently not used, but a similar implementation as for FREEBC is planned in the simulator.
> WIP Add OPM keyword for setting massrate for the boundary

- src/opm/parser/eclipse/share/keywords/900_OPM/P/PLYMWINJ
- src/opm/parser/eclipse/share/keywords/900_OPM/S/SKPRPOLY
- src/opm/parser/eclipse/share/keywords/900_OPM/S/SKPRWAT
- tests/parser/TableManagerTests.cpp
@GitPaean: 
The keywords `SKRPOLY` and `SKPRWAT` use the size type `UNKNOWN` to determine the number of records; the `UNKNOWN` size type is very weakly structured and if the things are not 100% correct that chance of problems is quite large - see e.g.: https://github.com/OPM/opm-common/pull/644
Have changed to `SLASH_TERMINATED` in this; if this way makes sense we will also have to add trailing `/` to the keywords in the `2D_POLYMER_INJECTIVITY` testcase.
> Use slash termination to determine size of keywords SKPRPOLY SKPRWAT

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunction.hpp
- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunctionTable.hpp
- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParams.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunction.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunctionTable.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParams.cpp
- tests/parser/UDQTests.cpp
When defining UDQ we have access to a set of functions, i.e. 
```
UDQ 
DEFINE WUPR1 1/(WWCT 'OP*') /   
DEFINE WUPR3 SORTA(WUPR1) /
/
```
here we use the functions `/` and `SORTA`. This PR introduces all these functions along with a container class to manage them. The random functions `RAND?` are based on #650 which must be merged first, but otherwise ~ready.
> Udq functions

- CMakeLists_files.cmake
- examples/opmhash.cpp
```
The purpose of the opmhash program is to load a deck and create a summary, by
diffing two such summaries it is simple to determine if two decks are similar.
For each keyword a hash of the normalized content is calculated. The output of
the program will look like this:
RUNSPEC  : 13167205945009276792
TITLE    : 16047371705964514902
DIMENS   : 1264233216877515756
NONNC    : 10052807539267647959
OIL      : 6013609912232720008
WATER    : 14106203893673265964
Total    : 7362809723723482303
Where the 'random' integer following each keyword is the hash of the content of
that keyword. The hashing is insensitive to changes in white-space and comments
and file location. At the bottom comes a total hash of the complete content. The
hash of each keyword is insensitive to shuffling of keywords, …
```
> Small utility to hash a deck

- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.hpp
- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQInput.hpp
- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.hpp
- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQWellSet.hpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQAssign.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunction.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQInput.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQWellSet.cpp
- tests/msim/actionx1.include
- tests/msim/test_msim_ACTIONX.cpp
- tests/parser/UDQTests.cpp
Lo and behold - the first actually working UDQ feature. If you request UDQ output in the summary section:
```
SUMMARY
...
WUBHP  -- Ask to get output of your personal BHP
/
..
SCHEDULE
UDQ
ASSIGN WUBHP 100 /       -- Your personal BHP is fixed to 100 BARSA
UNITS WUBHP 'BARSA' / 
/
```
and assign it to a *fixed* value in the SCHEDULE section you will get that value in the summary output file. Maybe not exactly a feature to kill for - but still :smile:
> Udq summary assign

- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.hpp
Include string to avoid a compile error with `Apple LLVM version 10.0.0 (clang-1000.10.44.4)`
> Include <string>

- redhat/opm-common.spec
something changed in os image so these directories
are not guaranteed to exists any longer. make them
> fixed: redhat packaging

- etc/opm_bash_completion.sh.in
if `which` thought there was an error, some ugly error messages were printed when pressing the tabulator key. note that this (probably) only affected people who used this as the default completor...
> tab completors: be quiet even if the `which` command would like to complain

- opm/parser/eclipse/Parser/ParserKeyword.hpp
- opm/parser/eclipse/Parser/ParserRecord.hpp
- opm/parser/eclipse/RawDeck/RawKeyword.hpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
- src/opm/parser/eclipse/Parser/ParserRecord.cpp
- tests/parser/UDQTests.cpp
All since the very first fumbling commits in opm-parser in 2013 the assumption that input records are terminated on `/` has held up; but now comes the `UDQ` and `ACTIONX` keywords which allow for general mathematical expressions - and hey presto: Here comes `/` which should *not* terminate the parsing.
This PR adds support for - on a per keyword basis - to terminate the record on the last `/` on the line instead of the first. The new behavior is coupled to the data property `RAW_STRING`(https://github.com/OPM/opm-common/pull/369) which does not strip quotes and retains `*`. Currently the new behavior only affects the keywords `UDQ` and `ACTIONX`.
> Raw strings

- cmake/Modules/OpmSatellites.cmake
this argument is optional and called *drumroll* `DEFAULT_ENABLE_IF`.
for a motivation, cf OPM/opm-simulators#1747.
> opm_add_test(): add condition to specify if a test ought to be compiled by default

- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQInput.hpp
- opm/parser/eclipse/Parser/ParseContext.hpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQInput.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- src/opm/parser/eclipse/Parser/ParseContext.cpp
- tests/parser/SummaryConfigTests.cpp
- tests/parser/UDQTests.cpp
In the wild we have encountered decks which request summary output of UDQ quantities which have not been defined - this PR adds ParseContext variable to configure how that should be handled. Defaults to a warning.
@totto82 : You could give this a spin.
> Udq parsecontext

- src/opm/output/eclipse/AggregateMSWData.cpp
- tests/test_AggregateMSWData.cpp
- signed/unsigned comparisons
- unused variables
- unused typedefs
The formatting that looks broken, is in fact correct. "Somebody" isn't following the surrounding code style (4 space indent, no tabs). If you prefer I can restore the original brokenness.
> fix warnings

- CMakeLists.txt
- jenkins/build-opm-module.sh
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
A refactoring of the wells in the opm-common repository has started:  https://github.com/OPM/opm-common/issues/624
The intention is to create a new well implementation side by side with the existing old implementation, and then switch over to use the new implementation when everything is ready. The new well code will be tested the normal way with unit tests, but the well code is complex - and it would be valuable to have some integration testing as early as possible - this PR is an attempt to address that.
The PR is based on a cmake option `ENABLE_WELL_TESTING` which will define the preprocessor symbol `WELL_TESTING` - and then if the `WELL_TESTING` symbol is defined a method `checkWells()` is added to the `Schedule` object - the `checkWells()` method will be called at the end of the …
> Add optional code for well testing

- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp
See: https://github.com/OPM/opm-common/issues/682
@bska: There was clearly a bug in the code - by just looking, and I have fixed it now. But I had problems reproducing the bug - valgrind which is my usual tool for such problems was all happy even before the fix.
> Fix bug with ouf of bounds access in UDQ parser

- opm/parser/eclipse/EclipseState/Schedule/Events.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/integration/ScheduleCreateFromDeck.cpp
With this PR the well events are moved from the well object to the Schedule object, to facilitate: #671 
This event code does not feel exactly right - but it works for now. Downstream PR in opm-simulators coming.
> Remove well events

- src/opm/output/eclipse/Summary.cpp
For METRIC units it doesn't matter, but for FIELDS is does.
> Output FIP as surface volumes

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/ConnectionTests.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/WellSolventTests.cpp
- tests/parser/WellTracerTests.cpp
All `Schedule::handleWxxx()` methods are implemented with will *names*. Removed `Schedule::getWells(pattern)` and `Schedule::getWellsMatching(pattern)`
A small step for the well model in opm-common, and an even smaller step for mankind - but still ...:-)
> Use wellnames

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/WellInjectionProperties.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellInjectionProperties.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/injection.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/injection.hpp
- tests/parser/WellTests.cpp
Handling of `WCONxxxx` keywords is extracted out from the `Schedule` implementation - to simplify implementation of an alternate well model.
> Wellproperties constructor

- src/opm/output/eclipse/AggregateMSWData.cpp
Added a fix for an index error for segment number in writing of RSEG data to eclipse compatible restart file. This fix is ready to be merged from my side.
> Added a fix for an index error in writing of RSEG data to ECL Restart file

- jenkins/build-opm-module.sh
use this to enable ebos extensions in opm-simulators.
replaces #689 
i think this is a better solution @andlaus
> added: array of extra cmake parameters for each module

- src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/I/ISGLPC
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/I/ISWLPC
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/ROCK
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SGLPC
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SWLPC
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
they are just like their non-PC postfixed counterparts, except that they only apply to capillary pressures, not to the relperms and they seem to overwrite the values specified via S[WG]L for the capillary pressures but not for relperms.
> add the S[WG]LPC and IS[WG]LPC keywords

- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
Since the well targets are only updated when a well event is triggered this bug may case significant changes in the solution.
> update well event also for WCONINJH

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
- opm/parser/eclipse/EclipseState/Schedule/RFTConfig.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
- src/opm/output/eclipse/EclipseIO.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/RFTConfig.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- tests/parser/DynamicStateTests.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/integration/ScheduleCreateFromDeck.cpp
Most of the settings in the Schedule section work as: "Set X=Y - and it will apply until explicitly set to Z", and for this use case the `DynamicState<T>` datastructure has served us well, however when configuring RFT output we have both the alternatives:
1. Set this setting exactly once.
2. Set this setting - *when the well opens*
These two do not fit that well with the `DynamicState<T>` - to facilitate the big well refactor: #681 this PR extracts the rft configuration out from the well object.
https://github.com/OPM/opm-simulators/pull/1779
> Add class RFTConfig

- opm/parser/eclipse/EclipseState/checkDeck.hpp
- opm/parser/eclipse/Parser/ParseContext.hpp
- src/opm/parser/eclipse/EclipseState/checkDeck.cpp
- src/opm/parser/eclipse/Parser/ParseContext.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FILEUNIT
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
- tests/parser/integration/CheckDeckValidity.cpp
This PR is incomplete as a full implementation would imply a major rewrite of the core parser. the rationale for this is to make it easier to use deck editors which like to add this keyword to all files (petrel?): it causes the parser not to trip if it encounters FILEUNIT and also, the `Opm::checkDeck()` function prints a warning if a unit system specified via FILEUNIT is not identical to the unit system of the deck.
> Implement FILEUNIT

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
- tests/parser/WellTests.cpp
Use default copy constructor and handleWCONPROD() and handleWCONHIST() for
prediction and history wells respectively. With this PR the carrying of state from one timestep to the next has (hopefully) become clearer and less error prone.
Purpose is again simplification of "the big well refactor".
> Refactor WellProductionProperties construction

- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
- tests/parser/UDQTests.cpp
@jalvestad : With this you should get the udq tokens in a reasonably digestiible form, the tokens returned here assumed to space separated - i.e. the output string should be something like
```python
s = " ".join(tokens)
```
in Python speak. The tokens do not replicate the input exactly - in particular:
1. Quotes around string identifiers has been removed.
2. The input string has been split on separators - i.e. `"'FOPT'*2"` &rightarrow; `{"FOPT", "*", "2"}`
I *think* this is the form that should be used when storing in the `ZUDL` vector.
```C++
const auto& udq_input = schedule.getUDQConfig( time_step );
const auto& udq_defs = udq_input.definitions();
for (const auto& udq_def : udq_defs) {
const std::vector<std::string>& tokens = udq_def.tokens();
....
}
```
> Internalize UDQ tokens in the UDQ define keyword

- src/opm/parser/eclipse/EclipseState/checkDeck.cpp
the FILEUNIT functionality currently does not work because the name of the unit system specified by the keyword is almost always fully capitalized (e.g., "FIELD"), while the name of the unit system returned by the parser isn't (e.g., "Field"). This patch "fixes" this by simply capitalizing all strings.
> fix FILEUNIT

- examples/msim.cpp
- msim/src/msim.cpp
- src/opm/output/eclipse/AggregateGroupData.cpp
- src/opm/output/eclipse/AggregateMSWData.cpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/ArrayDimChecker.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/RFTConfig.cpp
- src/opm/parser/eclipse/EclipseState/Tables/Rock2dTable.cpp
- src/opm/parser/eclipse/EclipseState/Tables/Rock2dtrTable.cpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- tests/msim/test_msim.cpp
- tests/msim/test_msim_ACTIONX.cpp
- tests/test_AggregateConnectionData.cpp
Namely:
- unused parameter
- type qualifiers ignored ...
- catchinhg polymorphic type ... by value
> Removes nearly all warnings experienced with g++-8.3

- src/opm/parser/eclipse/share/keywords/000_Eclipse100/C/CARFIN
The keyword `CARFIN` was configured top be slash terminated, it should rather have fixed size = 1. We will now *parse* the CARFIN keyword, but the LGR processing does not work at all ...
> Add "size" : 1 attribute to CARFIN keyword

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.hpp
- src/opm/output/eclipse/AggregateGroupData.cpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- tests/parser/ScheduleTests.cpp
The `Schedule`class had two methods
```C++
Schedule::getWells(const std::string& group_name, size_t time_step);
```
and
```C++
Schedule::getChildWells(const std::string& group_name, size_t time_step);
```
the former was recursive, the latter only returned the wells which were immediate children of the `group_name` group. These two functions have been combined in one:
```C++
Schedule::getChildWells(..., Enum query_mode);
```
> Remove Schedule::getWells(group, step)

- src/opm/output/eclipse/RestartIO.cpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
Some sites calling: `Schedule::getWells()` only ever access the *name* of the well, these call sites have been updated to use `Schedule::wellNames()` instead.
> Use wellNames() instead of getWells()

- src/opm/output/eclipse/AggregateMSWData.cpp
This Improvement / correction enables handling more general MSW data  for writing to
Eclipse compatible restart file.
I will thank Baard Skaflestad for good assistance and collaboration.
> An improvement / correction of the writing of MSW data to Eclipse compatible restart file

- opm/output/eclipse/AggregateGroupData.hpp
- opm/output/eclipse/AggregateWellData.hpp
- src/opm/output/eclipse/AggregateGroupData.cpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/output/eclipse/RestartIO.cpp
- tests/test_AggregateGroupData.cpp
- tests/test_AggregateWellData.cpp
This commit removes the restriction that cumulative totals are not output in the case of creating OPM Extended Restart files.  There was a reason why we did not do this when the new restart facility was introduced, but that reason no longer applies.
This is an enabling step towards merging PR #703.
> Restart: Provide Continuous Cumulatives in OPM Extended Files

- CMakeLists_files.cmake
- GenerateKeywords.cmake
- opm/parser/eclipse/Deck/DeckItem.hpp
- opm/parser/eclipse/Deck/UDAValue.hpp
- opm/parser/eclipse/Parser/ParserItem.hpp
- opm/parser/eclipse/Units/Dimension.hpp
- opm/parser/eclipse/Utility/Typetools.hpp
- src/opm/parser/eclipse/Deck/DeckItem.cpp
- src/opm/parser/eclipse/Deck/DeckOutput.cpp
- src/opm/parser/eclipse/Deck/UDAValue.cpp
- src/opm/parser/eclipse/Generator/KeywordGenerator.cpp
- src/opm/parser/eclipse/Parser/ParserItem.cpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
- src/opm/parser/eclipse/Parser/ParserRecord.cpp
- src/opm/parser/eclipse/RawDeck/StarToken.cpp
- src/opm/parser/eclipse/Units/Dimension.cpp
- tests/parser/UDQTests.cpp
- tests/parser/UnitTests.cpp
*Starting* to use the UDA values. Have introduced a type `UDAValue`which can be string or double, and then use that in the `DeckItem` datastructure. With this work the UDA values are carried all the way into the `Deck` - but the `Schedule`datastructures still ask for double values - updating the `Schedule` layer will be the next step.
Working with this has revealed some less-than-elegant elements of the `{Parser, Deck, UnitSystem}` interaction - the unit system handling in the `UDAValue` implementation is *not* particularly elegant - but it works for now. 
Happy to get some review, but I will go :skier: for a couple of days now and will not respond to review comments.
> UDA values in the deck

- examples/test_util/EclFile.cpp
- examples/test_util/EclUtil.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
1. Fix compile error due to missing includes (might just bite clang users though)
2. Fix for control mode bug that cause Norne to fail (or rather worse: run but produce totally wrong results).
The control mode bug fix might not be completely sufficient, but at least it recovers the running of Norne.
@akva2 the second commit should be picked to the release branch (sorry for the extra work), unless @joakim-hove has a better alternative.
> Two small but critical fixes

- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
- tests/parser/ScheduleTests.cpp
@joakim-hove , please suggest whether it is something you want. It covers the correction introduced in https://github.com/OPM/opm-common/pull/746 , while it is included in a test specified for WHISCTL.
> modifying the ScheduleTests to handle control mode change with WCONHIST

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- tests/parser/GroupTests.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/WellTests.cpp
As part of: https://github.com/OPM/opm-common/pull/711 a regression was introduced which has broken a relevant field case. The bug is in the interaction between the `WHISTCTL, WELSPECS` and `WCONHIST` keywords, and arises in the situation where the `WHISTCTL`keyword is entered *before* the well is specified with `WELSPECS`. That worked - by accident - prior to https://github.com/OPM/opm-common/pull/711 - now it should work again - and continue to do so.
Thank you to @totto82 for actually identifing the problem.
@atgeirr / @totto82 I am grateful if you can take this for a spin.
> Internalize a global WHISTCTL setting in the Schedule object

- CMakeLists_files.cmake
- opm/output/eclipse/LogiHEAD.hpp
- opm/output/eclipse/VectorItems/logihead.hpp
- src/opm/output/eclipse/EclipseIO.cpp
- src/opm/output/eclipse/LogiHEAD.cpp
- tests/test_LogiHEAD.cpp
This pull request&mdash;the second of two and the follow-up to PR #700 &mdash;hooks the code to normalise ~~prepares OPM Flow's INIT file output code for writing structurally correct PVT table entries to the TAB vector.~~ input PVT tables into the INIT file's `TAB` vector up to Flow's INIT file writer.
In particular, we switch to using
```C++
void Tables::addPVTTables(const EclipseState& es)
```
in place of the existing `addPVTO()`, `addPVTG()`, and `addPVTW()` functions.  This, in turn, activates table normalisation for all `PV{D,T}{G,O}`, `PVCDO`, and `PVTW` keywords and produces ECLIPSE compatibly sized and structured TAB vector representations for these data sources and changes the contents and size of the `TAB` vector in the INIT file. 
As a prerequisite for this work, to enable …
> Structurally Correct PVT Tables in INIT File (Part 2)

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Well2.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/WellPolymerProperties.hpp
- opm/parser/eclipse/Parser/ParseContext.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well2.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellPolymerProperties.cpp
- src/opm/parser/eclipse/Parser/ParseContext.cpp
- tests/parser/ConnectionTests.cpp
- tests/parser/MultisegmentWellTests.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/data/integration_tests/IOConfig/RPT_TEST2.DATA
- tests/parser/integration/ParseKEYWORD.cpp
- tests/parser/integration/ScheduleCreateFromDeck.cpp
[This is #674 which was accidentally closed due to some git fat fingering]
This is the first step of an implementation of: #624 - which again is part of the UDQ / UDA work; it should now be ~ready for review. Observe that when this is merged it will have no immediately visible effect - the new well implementation Well2 will exist side by side with the existing implementation Well - and downstream will exclusively use the old Well. As part of this PR an system for well integration testing is integrated into the Schedule constructor - this is briefly described here: #680. When this is merged I encourage all developers to configure opm-common with:
```
bash% cmake .. -DENABLE_WELL_TEST=ON
```
then the automatic "Well ≡ Well2" test will be run as part of Schedule construction; please report …
> Add alternative well implementation Well2

- opm/output/eclipse/Summary.hpp
- src/opm/output/eclipse/Summary.cpp
- tests/test_Summary.cpp
The `SummaryState`class is becoming more important for the UDQ/ACTIONX work. In this PR we factor out a `Summary::eval() const` method from the `Summary::add_timestep()` method - that way evaulating the `SummaryState` is indepenent of the output code.
This work has revieled some less-than-optimal aspects of the `Summary` class - namely the internal state, will see if that can be improved as part of this PR. Update: the internal state has partly been addressed here: https://github.com/OPM/opm-common/pull/768
> Split Summary::add_timestep in eval()

- examples/test_util/EclFilesComparator.cpp
Turns out that for clang this is no a bool and therefore a template
specialization is missing. We workaround this by some template (black) magic
that does the explicit instantiation for clang and for others adds another
unused instantiation for char.
Alternative to #771
> Fixes clang linking error when using std::vector<bool>::const_reference.

- src/opm/output/eclipse/CreateLogiHead.cpp
- src/opm/output/eclipse/LogiHEAD.cpp
- tests/test_LogiHEAD.cpp
This pull request makes it possible to write eclipse compatible restart files for various types of PVT data:
PVDO, PVDG
PVTO, PVDG
PVTO, PVTG
This pull request is necessary for the ecl-compatible restart file to work a number of relevant field models.
This pull request builds on pull request #707 which needs to be merges before this pull request can be merged.
> Generalize eclipse compatible restart to a broad set of PVT-options

- opm/parser/eclipse/EclipseState/Schedule/Well/Well2.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well2.cpp
This PR adds a new method:
```
bool Well2::predictionMode() const;
```
which can be used to query if the well is currently in prediction mode.
> Add method bool Well2::predictionMode()

- examples/test_util/EclRegressionTest.cpp
- examples/test_util/compareECL.cpp
.. case, but not for test case. 
1. argument is reference case, 2. argument is test case. compareECL will fail if output files are present for reference case but not for test case.
> update of compareECL, failes test if output file present for reference 

- tests/parser/UDQTests.cpp
This test inadvertently "tested" two things - bot a parsing error and a keyerror. The parsing error was the purpose of the test, and the faulty key has been corrected.
> UDQ error test - use correct well variablec

- CMakeLists_files.cmake
- opm/io/eclipse/ERst.hpp
- opm/io/eclipse/EclFile.hpp
- opm/io/eclipse/EclOutput.hpp
- opm/io/eclipse/OutputStream.hpp
- src/opm/io/eclipse/ERst.cpp
- src/opm/io/eclipse/EclFile.cpp
- src/opm/io/eclipse/EclOutput.cpp
- src/opm/io/eclipse/OutputStream.cpp
- tests/test_OutputStream.cpp
This change-set equips the ECLIPSE I/O classes introduced in PR #699 with additional operations to enable writing formatted/unformatted and unified/separate restart files in terms of class `EclOutput`.
In particular, we introduce a new file manager
```C++
class Opm::ecl::OutputStream::Restart;
```
that knows about the high-level structure of a sequence of restart steps and is responsible for opening writable streams a appropriate write positions&mdash;specified in terms of sequence numbers (SEQNUM values).  The intended use of the `Restart` class is
```C++
{
Restart rst(resultSet, formatted, unified);
rst.prepareStep(17);
auto& rstFile = rst.stream();
rstFile.write("INTEHEAD", ihead)
// ... other headers, and group/well/segment &c arrays ...
message("STARTSOL", rstFile); …
```
> Add Restart I/O Operations to New ECLIPSE I/O Classes

- src/opm/io/eclipse/OutputStream.cpp
this is not supported in older version of boost::filesystem.
furthermore, it was always an experimental feature and
and has been deprecated in newer versions.
generic_string is available in all versions, so use that.
> fixed: avoid usage of boost::filesystem::path::generic()

- src/opm/output/eclipse/AggregateConnectionData.cpp
- src/opm/output/eclipse/AggregateMSWData.cpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/output/eclipse/RestartIO.cpp
This change-set is a brief intermission in the work towards using the ECLIPSE I/O classes introduced in PR #699 as the fundamental components for Flow's restart I/O functionality.  Briefly, we remove function (and lambda) arguments that became unused in the output code as of commit 94b160258 (PR #731) and also restore the original indentation levels from before that PR.
> Restart Output Code Reformatting

- src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
- tests/test_Summary.cpp
The algorithm to detect totals in the `SummaryState` class was too simple, have copied the hard-coded list from `libecl`.
> Correctly detect totals in SummaryState

- opm/io/eclipse/ERst.hpp
- src/opm/io/eclipse/ERst.cpp
- tests/test_ERst.cpp
This commit makes class `Opm::EclIO::ERst` able to open separate restart files (`*.X000n`, `*.F000n`).  Specifically, we refactor the existing class constructor body into a new helper function `initUnified`.  We add a new helper function `initSeparate` that builds the requisite indices in the case of a single report step, and make the constructor body call `initUnified` or `initSeparate` depending on whether or not the SEQNUM keyword exists in the restart stream.
Add two new unit tests to exercise the new ability.
> Teach ERst About Separate Restart Files

- opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
- tests/test_Summary.cpp
Needed when the well rates are fetched from the summary state. Not in use yet.
@blattms : The ultimate purpose of this PR is that the function the function `Summary::eval_timestep(SummaryState& st, ...)` will be called on IO rank and then the updated `SummaryState` object will be distributed - i.e. something like this:
```
if (my_rank == 0) {
summary.eval_timestep( st, .... );
std::vector<char> buffer = st.serialize();
MPI_Bcast( buffer, .... );
} else {
std::vector<char> buffer;
MPI_Recv(buffer);
st.deserialize( buffer );
}
```
with a suitable amount `mpi_barrier` calls sprinkled around - does it seem reasonable?
> Add serialization of SummaryState

- src/opm/output/eclipse/LoadRestart.cpp
@bska: Good if this can be carried over to #797  ~~are you certain that the `RestartView` at all needs the `sim_step` member?~~
> Add public access to report_step in RestartView()

- .gitmodules
- python/.gitmodules
Suggested patch for #803.
You can observe the changed behavior by comparing cloning opm-common master recursively:
```
git clone -q --recursive git@github.com:OPM/opm-common.git
```
with cloning this branch recursively:
```
git clone -b submodule_fix -q --recursive git@github.com:markusdregi/opm-common.git
```
> Move .gitmodules to root

- msim/include/opm/msim/msim.hpp
- msim/src/msim.cpp
- opm/output/eclipse/EclipseIO.hpp
- opm/output/eclipse/RestartIO.hpp
- opm/output/eclipse/Summary.hpp
- opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
- src/opm/output/eclipse/EclipseIO.cpp
- src/opm/output/eclipse/LoadRestart.cpp
- src/opm/output/eclipse/Summary.cpp
- tests/test_EclipseIO.cpp
- tests/test_RFT.cpp
- tests/test_Restart.cpp
- tests/test_Summary.cpp
- tests/test_writenumwells.cpp
Extract the `Summary::eval()` function out from the `Summary::add_timestep()`. The purpose of this is again to support UDQ - where evaluation of summary vectors and the output of summary results is separated.
Contains #800.
Followup PR in opm-simulators: https://github.com/OPM/opm-simulators/pull/1874
> Use eval timestep

- opm/parser/eclipse/Deck/UDAValue.hpp
- src/opm/parser/eclipse/Deck/UDAValue.cpp
- tests/parser/UDQTests.cpp
The system for units does not really play nicely with the `UDAValue` class. This is a band aid fix.
The proper fix is to pass the dimension object along when constructing the UDAValue, but that will require quite invasive low-level changes to the deck construction code; will come back to that.
> Uda value reset

- src/opm/output/eclipse/LoadRestart.cpp
This pull request reimplements the private `RestartFileView` class of file `LoadRestart.cpp` in terms of the [`ERst`](https://github.com/OPM/opm-common/blob/4cde0ac8a85a6ec878272674dc17d052384f51fe/opm/io/eclipse/ERst.hpp) class.  The latter supports all operations we currently need, although we can no longer use a 'const' object since loading arrays mutates the `ERst` instance.
Most changes here are fairly mechanic and most of the new complexity concerns how to identify a vector (keyword) of a particular element type.  We make special concessions for `INTEHEAD`, since this vector plays a central role in accessing the other data vectors.  The mutability of `RestartFileView` is underscored by using `shared_ptr<>` in various helper facilities.
While here, also remove `sim_step` arguments …
> Reimplement RestartIO::load() in Terms of Class ERst

- test_util/EclRegressionTest.hpp
Some Items in SWEL array stem from the reservoir voidage rate target item of producer wells on history controls (WCONHIST). Hence not only on static input data.
> Use tolerances from command line for restart array SWEL

- msim/src/msim.cpp
- opm/output/eclipse/EclipseIO.hpp
- src/opm/output/eclipse/EclipseIO.cpp
- tests/test_EclipseIO.cpp
- tests/test_RFT.cpp
- tests/test_Restart.cpp
- tests/test_writenumwells.cpp
Remove unused arguments to `Summary::add_timestep()`
> Remove unused arguments from EclipseIO::writeTimestep()

- examples/msim.cpp
- msim/include/opm/msim/msim.hpp
- msim/src/msim.cpp
- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/Deck/DeckItem.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.hpp
- tests/msim/test_msim.cpp
- tests/msim/test_msim_ACTIONX.cpp
- tests/parser/UDQTests.cpp
The first six commits are trivial - and part of #812. The purpose of the final commit is to ensure that scalar UDQ values are correctly scattered all wells/groups in a set.
> Udq eval set

- opm/parser/eclipse/EclipseState/Schedule/Well/Well2.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well2.cpp
- tests/parser/WellTests.cpp
This PR adds some accessors to the Well object bypassing the `SummaryState`object. This is slightly hacky, possibly the properties should be split in two structs - one which is UDQ aware and one which is not?
This will do for now though.
The downstream pr: https://github.com/OPM/opm-simulators/pull/1888 depends on this.
> Add Well2::injectorType() accessor

- tests/parser/ParserTests.cpp
- tests/parser/WellTests.cpp
> remove unused variables

- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.cpp
- tests/parser/UDQTests.cpp
In a UDQ expression where the well has been fully qualified:
```
UDQ  
DEFINE WUOPRU (WOPR OP1 - 150) * 0.90 /
/
```
the return value should be a wellset where all wells have the same value.
> UDQSet::eval - make sure to return well node

- src/opm/parser/eclipse/EclipseState/Schedule/ArrayDimChecker.cpp
It is perfectly fine to have groups whose size (number of children) is equal to the declared maximum (Item 4 of WELLDIMS).  It is only questionable to have groups whose active size exceeds that of the declared maximum.
Pointy Hat: @bska
> Array Dimension Checker: Correct Groupsize Criterion

- src/opm/output/eclipse/CreateInteHead.cpp
Commit 7986e99e (PR #640) intended to make OPM Flow able to run simulation cases whose active number of groups might exceed the declared maximum number of (non-FIELD) groups (Item 3 of RUNSPEC keyword `WELLDIMS`).  However, the commit failed to ensure that Item 21 of INTEHEAD always contained the larger of `WELLDIMS(3)` and the actual number of active groups.
This, in turn, meant that downstream consumers&mdash;such as the code to [enumerate groups according to their order of appearance](https://github.com/OPM/opm-common/blob/599ed7136fbfaeeee61379e4dfe94a002e2b98f0/src/opm/output/eclipse/AggregateGroupData.cpp#L92-L104) in the simulation deck&mdash;would generate subscripts/indices that were out of bounds for the allocated tables.  Flow's restart code would then not produce any output …
> INTEHEAD: Store Actual Maximum Number of Groups in Item 21

- opm/io/eclipse/ESmry.hpp
- opm/output/eclipse/AggregateGroupData.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/InjectionControls.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/ProductionControls.hpp
- src/opm/io/eclipse/ESmry.cpp
- src/opm/output/eclipse/AggregateGroupData.cpp
- src/opm/output/eclipse/AggregateMSWData.cpp
- src/opm/output/eclipse/RestartIO.cpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/output/eclipse/Tables.cpp
- src/opm/parser/eclipse/Deck/UDAValue.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionAST.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well2.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellInjectionProperties.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
- src/opm/parser/eclipse/Parser/ParserItem.cpp
- test_util/EclRegressionTest.cpp
- tests/test_AggregateGroupData.cpp
This silences many, but not all shadowing warnings in opm-common.
Includes minor refactoring of ESMry and AggregateGroupData undertaken with the aid of the original authors to ensure correctness.
> Silence shadowing warnings

- src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFETP
- tests/parser/AquifetpTests.cpp
Original (and incorrect) description:
Without this you get
```sh
$ opmpack path/to/opm-tests/flow_diagnostic_test/SIMPLE_SUMMARY2.DATA > /dev/null
terminate called after throwing an instance of 'std::invalid_argument'
what():  
Failed to parse keyword: AQUCT
Starting at location: path/to/opm-tests/flow_diagnostic_test/SIMPLE_SUMMARY2.DATA(189)
Inner exception: Malformed integer 'AQUANCON'
Aborted
```
This PR makes the `opmpack` command succeed.
---
Updated description:
The number of records is unrelated to AQUDIMS Item 5 (NANAQU).  That item sets the maximum aquifer ID permissible as Item 1 of AQUFETP (and other keywords related to analytic aquifers).
Update unit test accordingly.
> Don't Infer Number of AQUFETP Records from AQUDIMS

- CMakeLists_files.cmake
- opm/io/eclipse/OutputStream.hpp
- opm/output/eclipse/WriteInit.hpp
- src/opm/io/eclipse/OutputStream.cpp
- src/opm/output/eclipse/EclipseIO.cpp
- src/opm/output/eclipse/WriteInit.cpp
- tests/test_OutputStream.cpp
This Pull Request introduces a new file manager,
```C++
class Opm::EclIO::OutputStream::Init
```
that replaces the low-level operations of Flow's INIT file writer.  The implementation uses the [`EclOutput`](https://github.com/OPM/opm-common/blob/bf752c81a572f91a81cdb5668c1922d975a25bc4/opm/io/eclipse/EclOutput.hpp#L36) class and is very similar to that of the `Restart` stream introduced in commit 992d3b0.  It handles both formatted (`*.FINIT`) and unformatted (`*.INIT`) outputfiles.  The commonality between the two file managers might possibly be extracted to a base class at a later time.
We furthermore add a new free function, `void Opm::InitIO::write()`, that extracts the current known outputs from `Opm::EclipseIO::Impl::writeINITFile()` into a separate file (`WriteInit.cpp`) and writes …
> Replace LibECL Backend in Flow's INIT File Writing

- opm/parser/eclipse/RawDeck/RawConsts.hpp
- tests/parser/ParserTests.cpp
Seems some windows edtiors (Notepad++) insert the character ASCII 1 (Start Of Header - SOH) when editing. Ignore it as whitespace.
> Ignore character SOH (ASCII 1) while parsing

- opm/parser/eclipse/EclipseState/Schedule/RFTConfig.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/RFTConfig.cpp
- tests/parser/ScheduleTests.cpp
The RFT configuration is surprisingly complex; the first open timestep was wrong when RFT was requested through the WRFTPLT keyword
> Fix bug in RFTConfig first open - for WRFTPLT keyword

- src/opm/parser/eclipse/Deck/DeckOutput.cpp
UDA values and dimensions - it is f...ng mess. I think this should "fix" it - and make #774 green.
:crossed_fingers:
> When writing deck output the UDAValue will write raw values

- opm/parser/eclipse/EclipseState/InitConfig/InitConfig.hpp
- src/opm/parser/eclipse/EclipseState/InitConfig/InitConfig.cpp
- tests/parser/InitConfigTest.cpp
This commit extends the InitConfig class to support querying whether or not the `FILLEPS` keyword is present in the PROPS section.  Note that we only look for the keyword in PROPS (not the whole input deck), since the keyword is only permitted in PROPS.
Add unit tests to exercise the new ability.
> InitConfig: Internalize FILLEPS Keyword

- opm/parser/eclipse/EclipseState/InitConfig/InitConfig.hpp
- src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
- src/opm/parser/eclipse/EclipseState/InitConfig/InitConfig.cpp
- tests/parser/InitConfigTest.cpp
The endpoint arrays (SWLPC, SGU, KRORW etc) can all be automatically generated from the unscaled input saturation function tables.  This PR marks them as such, which is useful if the input deck specifies `FILLEPS`.
While testing this I also came across a model for which SATNUM was zero in decativated cells (i.e., those for which ACTNUM is also explicitly zero in the input deck).  This PR therefore also allows SATNUM and IMBNUM to be zero in inactive cells when running the saturation function property initialisation functions.
> Support Automatic Generation of Saturation Function Properties

- opm/parser/eclipse/EclipseState/Schedule/Well/WellTestConfig.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestConfig.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.cpp
- tests/parser/WTEST.cpp
The main thing this PR is trying to fix is that, the number of testing attempts need to be counted even a well is re-opened. 
Basically it means, the total number of attempts need to be counted regardless how many times we re-open or re-close a well. 
In the current master, it will be re-counted every time a well is closed. 
The downstream PRs are coming, but please begin suggesting whether you want it to be done in a different way. I do realize the full support of WTEST can be rather not easy, let us do it step by step. 
This issue is reported by @tskille .
> not removing the well from WellTestState when testing is successful

- cmake/Modules/UseWarnings.cmake
This turns on more warning flags by default in the OPM build system. The idea is to have fewer annoying warnings for developers, and that the original developer of some new code is better able to address warnings from that code than others. For some, this will make opm a lot more noisy when it comes to warnings, but that will also serve as motivation to address them... In the longer term, stricter warning flags should put us in the situation where OPM compiles warning-clean all the time, so any time you see a warning it is from the code you are working on right now. That is an ideal that might not be met, as compilers and platforms differ, but stricter defaults should push us in that direction.
The "master plan" is something like this:
- Find an appropriate but rich set of warning options …
> Turn on -Wextra and -Wshadow warning flags.

- CMakeLists.txt
Cmake symbol `ENABLE_PYTHON` was in conflict with ... libecl?
> Rename cmake symbol ENABLE_PYTHON -> OPM_ENABLE_PYTHON

- opm/parser/eclipse/EclipseState/Schedule/Well/WellTestConfig.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestConfig.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.cpp
- tests/parser/WTEST.cpp
so we can easily tell when a new WTEST keyword joins.
When a new WTEST keyword, we will reset the counting of the num_attempt
and maximum number of attempts for the associated well.
> recording the report step that WTEST keyword is specified

- opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.hpp
- src/opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMROCK
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
- tests/parser/FoamTests.cpp
Adding FOAMROCK made it necessary to refactor FoamConfig, and add code to ensure consistency of FOAMROCK and FOAMFSC (same number of records). This was helped by the constructor for FoamConfig taking a Deck rather than a keyword, thanks for the advice before! Before refactoring I ran clang-format on the class to prevent annoyance, the PR therefore looks bigger than it really is.
> Add FOAMROCK including FoamConfig support and test.

- jenkins/build-opm-module.sh
This is mostly just to see if it saves jenkins from libecl. If merged it would remove all ability to specify libecl PRs etc.
> Set default commit to use for libecl to a known OPM-compatible commit

- opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.hpp
- src/opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.cpp
- src/opm/parser/eclipse/EclipseState/InitConfig/InitConfig.cpp
I know I said the previous PR would be the last... However, now I have connected all the dots and of course some logic was off.
This is necessary to support the table-based gas mobility reduction model (using FOAMMOB) which is the only one we will support initially. In order to extend support to the function-based model the FOAMFSC-related things have been kept.
> Allow FOAM without FOAMFSC

- opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.cpp
- tests/parser/WTEST.cpp
WELOPEN and WCON* can open well closed due to various reasons, physical
or economic.
If a well is shut with WELOPEN and WCON*, we do not try to re-open it
through WTEST.
@tskille , if you have something to add about the logic here, please do that. 
WIP is because the tests have not been fixed. 
There will a downstream PR from opm-simulators.
> WELOPEN and WCON* interact with WECON and WTEST

- jenkins/build-opm-module.sh
With https://github.com/equinor/libecl/pull/637 merged opm *should* build with libecl master again.
> Remove hardcoded libecl commit in jenkins pipeline

- opm/parser/eclipse/EclipseState/Schedule/Group/Group2.hpp
Just some everyday janitoring. It seems no code relies on implicit conversions yet at least.
> mark constructor explicit

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- python/sunbeam/schedule.cpp
- src/opm/output/eclipse/AggregateGroupData.cpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/output/eclipse/LoadRestart.cpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/GroupTests.cpp
- tests/parser/ScheduleTests.cpp
First step on group rewrite:
1. Add method `Schedule::groupNames()`
2. Remove `Schedule::getGroups()`
This is to align with the way it is done for the wells - where it has worked reasonably well.
Downstream: https://github.com/OPM/opm-simulators/pull/1939
> Add method Schedule::groupNames()

- src/opm/io/eclipse/ERst.cpp
- tests/test_ERst.cpp
"Load on demand" means that vectors are automatically loaded from disk when using member function getRst (if not already loaded by available member function loadReportStepNumber(int number) ).
Base class EclFile already have this functionality. So all that is needed for this is to remove if statement and throw in current version of ERst
> Enabling load on the demand for class ERst

- opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
- opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.cpp
- tests/parser/GroupTests.cpp
Introduce an enum GroupType to designate the type of a group. This was previously implemented with *two* boolean fields, hence the API allowed a situation where a group was both a producer and an injector - seems the SPE9_CP_GROUP test relied on this behavior, so it is retained through the use of bitmask behavior - but it seems slightly dubious. Maybe the SPE9_CP_GROUP test should get some scrutiny?
> Add enum GroupType

- test_util/convertECL.cpp
Added two new options for program convertECL. Both of these are valid for unified restart files.
* `-r <restartNumber>`: select one specific report step and convert only this 
* `-l `will list avaliable report step in selected unified restart file
Unified restart files are often huge and converting the entire file can be time consuming. After file is converted these huge formatted files are not easy to work with. 
This options will be useful especially for working with QC of restart functionality
> convertECL, new option for unified restart file

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Util/IOrderSet.hpp
- tests/parser/OrderedMapTests.cpp
To be able to output eclipse formatted restart files there are several occasions where we need to retain the ordering from the input file. This PR implements a small set container `iorder_set<T>` which guarantees that - similar in idea to `OrderedMap<K,T>`
> Add insert ordered set

- src/opm/output/eclipse/WriteInit.cpp
This PR is a work in progress and an early draft of INIT-file output of the saturation function scaled end-point arrays (e.g., SWL, SGU, SOWCR, KRORW, PCG).  At present we support drainage and imbibition currve scaling arrays, but do not output directional keywords (e.g., SGUX-).
This PR takes a few shortcuts in the treatment of defaulted values.  Defaulted values are supposed to be output as `-1.0E+20`, but we (currently) output those values as filled in from the unscaled tables.  In other words, this PR behaves as if the input deck always specifies FILLEPS, although there is no handling of ENPTVD.  We will address those shortcomings either in this PR or as future work.
> INIT File Saturation Function End-Point Scaling

- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
The restart format imposes several ordering requirements which are not strictly required by the simulator itself, since the full eclipse restart capabilities have come a bit later in the process many of these ordering requirements are implemented as an afterthought, and not really integrated in the underlying datastructures.
In the ongoing `Group`&rightarrow; `Group2` transition I try respect the necessary ordering requirements from the outset, thereby reducing the need for impedance matching code (quitre significantly ...). As a precursor to this the current PR will sort the wells in `Schedule::getChildWells2()` according to appearance in the deck, previously this was the ordering imposed by `std::set`. The test failures from this PR is that the wells are now sorted differently, and …
> Sort the child wells according to insert index

- CMakeLists.txt
use a custom output to avoid rebuilds
currently, the python bindings are built on every make invocation,
including the 'make install' command.
this improves on this situation by tracking whether or not the target
needs to be rebuilt through a custom output and dependencies.
the list of dependencies is not very pretty, but necessary when
linking two build systems like this.
> Improve sunbeam build

- opm/parser/eclipse/Utility/Stringview.hpp
- tests/parser/StringTests.cpp
Small utility functions needed to parse/extract Python code from deck.
> Add string_view::starts_with() and string_view::find() methods

- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- tests/parser/GroupTests.cpp
A quirk of the GCONPROD keyword which was not correctly handled
> GCONPROD: The exceed action should be unconditionally set to RATE

- test_util/compareECL.cpp
Update of compareECL. Checks that at least one output file (EGRID, INIT, SMSPEC, RFT or UNRST) exists  for reference case. Throws if not the case.
> Update of compareECL - check output files for reference case 

- src/opm/output/eclipse/Summary.cpp
It turns out this is sufficient to fix issue #943.
The GTNode class returned by groupTree() as well as the function groupTree() can be removed as well, with only very minor changes otherwise. I will make a separate PR for that, so this can be merged in the meantime as a quick fix for the immediate problem.
> Remove an unused call that is very slow.

- opm/parser/eclipse/Parser/ParserKeyword.hpp
- opm/parser/eclipse/Parser/ParserRecord.hpp
- opm/parser/eclipse/RawDeck/RawKeyword.hpp
- opm/parser/eclipse/RawDeck/RawRecord.hpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
- src/opm/parser/eclipse/Parser/ParserRecord.cpp
- src/opm/parser/eclipse/RawDeck/RawKeyword.cpp
- src/opm/parser/eclipse/RawDeck/RawRecord.cpp
- tests/parser/DeckTests.cpp
- tests/parser/ParserTests.cpp
- tests/parser/RawKeywordTests.cpp
Deep down in the ancient text-handling code of the parser; not a friendly place ... :-(
> Remove superfluos check in RawKeyword assembly

- cmake/Modules/OpmLibMain.cmake
- cmake/Scripts/CheckCommits.cmake
I was tasked with enabling parallel test execution by default. Sadly CMake does not allow use to customize the built-in test target.
You can run tests in parallel using 'make test ARGS=-jN' , or equivalently using 'ctest -jN'. But you cannot set a default value for the ARGS environment variable for the test target.
The 'check' target, however, is our custom target to build and execute tests. Here I can enable this by default. This is the closest I can get to automated parallel execution.
@alfbr
> Execute tests in parallel for the 'check' target

- opm/io/eclipse/EclFile.hpp
- src/opm/io/eclipse/EclFile.cpp
The following PR includes an updated version of class EclFile. There is no change to the API, but read efficiency for ASCII files has been improved.
**RH7 workstation at Equinor** using formatted unified restart file (12 report steps) from a field model.
**Example1**, Open with EclFile and loading all data 
```
Opm::EclIO::EclFile file1("MODEL.FUNRST")
File1.loadData()
```
current: 12.1s , updated EclFile: 7.1s
**Example2**, Open with ERst and loading 1 report step 
```
Opm::EclIO::ERst file1("MODEL.FUNRST")
File1.loadReportStepNumber(107)
```
current: 1.4s , updated EclFile: 0.7s
**Debian workstation at home** using formatted unified restart file (8 report steps) from field model (slightly larger file). 
**Example1**, Open with EclFile and loading all data 
current: 33.3s , updated …
> EclFile - improved ascii read efficiency

- src/opm/output/eclipse/AggregateConnectionData.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- tests/test_AggregateConnectionData.cpp
During the massive well refactor a bug had sneaked in for the situation that a well is completed in a cell which is subsequently deactived by flow; there was an error in the book keeping for the ICON and SCON restart vectors.
Thank you to @jalvestad for extremely good debugging.
> Correct ICON and SCON when flow has deacivated connection cell

- tests/test_RFT.cpp
This PR switches the `test_RFT` unit test to using the [`ERft`](https://github.com/OPM/opm-common/blob/d06c0bfebbdba2d77ca8e9d5200661be015c0568/opm/io/eclipse/ERft.hpp) class introduced in commit 24a8efb2 (PR #699).  This is the first step towards reimplementing the RFT file output in terms of class [`EclOutput`](https://github.com/OPM/opm-common/blob/d06c0bfebbdba2d77ca8e9d5200661be015c0568/opm/io/eclipse/EclOutput.hpp).
The downside to doing this is that we can no longer use the node-based queries of libecl and have to implement a wrapper on top of the raw vectors to be able to ask for the pressure in a given connection's cell.  Still, this is part of a larger effort to decouple OPM from libecl in time for the next public release.
> Reimplement RFT Unit Test in Terms of 'ERft' Class

- tests/test_RFT.cpp
`BOOST_TEST_FAIL` was a figment of my imagination.
Sorry about the breakage.
> RFT Unit Test: Use Actual 'BOOST_FAIL' Macro

- src/opm/io/eclipse/EclFile.cpp
if there is no dot, p is -1 which leads to an exception thrown
> fixed: dereferencing string at index -1 is not adviced.

- src/opm/parser/eclipse/Parser/ParseContext.cpp
- tests/test_ArrayDimChecker.cpp
The `ParseContext::EXIT1` and `ParseContext::DELAYED_EXIT1` tells the simulator to terminate with `std::exit(1)` - this is a quite brutal exit, and in particular a traceback
is sometimes presented[1,2]. This draws the users attention away from the error message, this PR changes the error handling mode to `ParseContext::THROW_EXCEPTION` - this will still stop the execution - but sligtly less brutal; and in particular the traceback is no longer displayed.
[1]: opm/flow does not explicitly request this traceback in any way, looking at the symbols involved it seems to come from the `pthreads` runtime system, probably from the io thread. I do not know if we can disable this traceback in any way.
[2]: Just to illustrate the lack of control of this traceback - I can not reproduce it on my …
>  Default error handler for WELLDIMS errors is exception

- CMakeLists_files.cmake
- src/opm/parser/eclipse/EclipseState/Schedule/ArrayDimChecker.cpp
- tests/expect-wdims.chldg.err.out
- tests/test_ArrayDimChecker.cpp
This PR extends the `maxGroupSize` function to also consider the sizes of node groups (i.e., the number of child nodes/child groups) when determining what the largest group size is on a particular step.
Prompted by [discussion](https://github.com/OPM/opm-common/pull/947#issuecomment-528284603) in PR #947.
> Fix ArrayDimsChecker's Maximum Group Size (WELLDIMS) Check

- src/opm/common/OpmLog/StreamLog.cpp
- tests/test_OpmLog.cpp
A minor improvement, promised in OPM/opm-simulators#1995.
> Make StreamLog throw if it fails to open file.

- python/setup.py
happens on jenkins,
```
Traceback (most recent call last):
File "python/setup.py", line 29, in <module>
os.environ['PYTHONPATH'] += ':' + pkg_path_root
File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
raise KeyError(key)
KeyError: 'PYTHONPATH'
```
> fixed: quell exception if PYTHONPATH env var is nonexistent

- jenkins/build-opm-module.sh
Leftover from a previous iteration of the python binding building.
> remove unused opm-common module specific OPM_PREFIX_PATH option

- cmake/Modules/OpmSatellites.cmake
a disabled test is disabled. end of story.
i never saw the point to this option. if a test is disabled, it is disabled.
> changed: remove ADD_DISABLED_CTEST option

- opm/parser/eclipse/EclipseState/Schedule/Action/Condition.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Action/Actions.cpp
- tests/parser/ACTIONX.cpp
The internalization of ACTIONX conditions for restart did not accept <= and >= for some reason.
> Accept <= and >= in the ActionX::Condition

- opm/parser/eclipse/Deck/DeckKeyword.hpp
- src/opm/parser/eclipse/Deck/DeckKeyword.cpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
- tests/parser/DeckTests.cpp
This is a preparation to be able to create `DeckKeywords` from Python, and also a step to clean up some mess in the unit system handling which was introduced with the UDQ/UDA work.
Downstream: https://github.com/OPM/opm-upscaling/pull/274
> Add ParserKeyword member to DeckKeyword

- python/cxx/eclipse_grid.cpp
- python/cxx/eclipse_state.cpp
- python/cxx/table_manager.cpp
- python/python/opm/_common.py
- python/python/opm/io/ecl_state/__init__.py
- python/python/opm/io/parser/properties.py
- python/tests/test_parse.py
- python/tests/test_props.py
- python/tests/test_state.py
- python/tests/test_state2.py
This PR removes the old python class EclipseState and reintroduces it directly through pybind11.
> Replace python class EclipseState

- opm/parser/eclipse/Deck/Deck.hpp
- opm/parser/eclipse/Deck/DeckKeyword.hpp
- src/opm/parser/eclipse/Deck/Deck.cpp
- src/opm/parser/eclipse/Deck/DeckKeyword.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/DeckTests.cpp
- tests/parser/EclipseGridTests.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/SectionTests.cpp
- tests/parser/TimeMapTest.cpp
The `DeckKeyword::DeckKeyword(const std::string&)` constructor has been removed
and the `DeckKeyword` now requires a `ParserKeyword` pointer in the constructor.
> Deck constructor

- opm/parser/eclipse/Parser/Parser.hpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- tests/parser/ParserTests.cpp
- tests/parser/integration/IntegrationTests.cpp
Minor step to support Python. The use of pointer semantics was quite funny anyways.
> Use ParserKeyword values in Parser instead std::unique_ptr<>

- CMakeLists_files.cmake
- opm/io/eclipse/OutputStream.hpp
- opm/output/eclipse/WriteRFT.hpp
- src/opm/io/eclipse/OutputStream.cpp
- src/opm/output/eclipse/WriteRFT.cpp
- tests/test_OutputStream.cpp
- tests/test_RFT.cpp
This PR implements a new file writing function
```C++
void Opm::RftIO::write();
```
that is intended to replace the current RFT output functionality defined in terms of private class [`RFT` ](https://github.com/OPM/opm-common/blob/a7956bcf3186d532b4f0a23910c136ade6a158db/src/opm/output/eclipse/EclipseIO.cpp#L73-L89) in `EclipseIO.cpp`.  We support the basic RFT output consisting of
* Timestamp (elapsed and date)
* `WELLETC` metadata including all unit conventions
* Connection cell (I,J,K), connection cell hostgrid (blank for main grid only), connection cell centre depth, connection cell pressure, and connection cell water and gas saturations
Connections in inactive cells are omitted.  Note that unit of measure strings aren't implemented in terms of …
> Add New RFT File Writer

- python/setup.py
libopmcommon_python.so is not copied during install. This PR fixes it. 
setup.py: 
This is wrong: 
package_data={
'': ['cxx/libopmcommon_python.so']
},
It should be:
package_data={'opm': ['libopmcommon_python.so']},
> setup.py: package_data: readjusted target and origin of libopmcommon.so

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- tests/parser/ScheduleTests.cpp
This commit adds a new query method,
```C++
bool Schedule::hasGroup(groupName, timeStep)
```
which report whether or not a particular named group exists at a particular time step (zero-based report step index).  If this function returns 'true', then it is always safe to call
```C++
Schedule::getGroup2(groupName, timeStep)
```
with the same arguments.  Otherwise, the latter will throw an exception.
The new `hasGroup` overload thus enables the same query types as the existing `hasWell` overload set.  The immediate use case for this new overload is a reworking of the system for evaluating derived summary parameters (e.g., FOPT or GGLR).
Add a new unit test to exercise the new overload.
> Schedule: Add Query For Particular Group at Particular Time

- msim/src/msim.cpp
- opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
- tests/parser/ACTIONX.cpp
- tests/parser/GroupTests.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/UDQTests.cpp
- tests/parser/WellTests.cpp
- tests/parser/integration/ParseKEYWORD.cpp
- tests/parser/integration/ScheduleCreateFromDeck.cpp
- tests/test_AggregateGroupData.cpp
- tests/test_AggregateMSWData.cpp
- tests/test_AggregateWellData.cpp
- tests/test_EclipseIO.cpp
- tests/test_RFT.cpp
- tests/test_Restart.cpp
- tests/test_Summary.cpp
- tests/test_writenumwells.cpp
To be able to keep track of how far the simulation has progressed - in true date. This is ultimately needed in the `ACTIONX` implementation, where you can check the simulation date with statements of the type:
```
...
'MNTH = 6' AND 'YEAR > 2020' ...
```
Downstream: https://github.com/OPM/opm-simulators/pull/2018
> Add std::time start_time argument to SummaryState

- python/python/opm/_common.py
- python/python/opm/io/parser/__init__.py
- python/tests/test_parser.py
Does not have a Python constructor (yet at least)
> Do not import ParserKeyword in Python

- tests/parser/EclipseGridTests.cpp
We'll access the array out-of-bounds otherwise when passing the pointer to the `EclipseGrid` constructor.
> Ensure ACTNUM Has Expect Number of Elements

- opm/parser/eclipse/Deck/DeckKeyword.hpp
- python/cxx/deck_keyword.cpp
- python/cxx/parser.cpp
- python/python/opm/_common.py
- python/python/opm/io/deck/__init__.py
- python/tests/test_parser.py
- src/opm/parser/eclipse/Deck/DeckKeyword.cpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
- tests/parser/DeckTests.cpp
- tests/parser/EclipseGridTests.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/SectionTests.cpp
- tests/parser/TimeMapTest.cpp
parserkeyword can create deckkeyword.
python parserkeyword: removed create_deckkeyword.
DeckKeyword: member parser_keyword is shared_ptr.
python DeckKeyword constructor.
python: no exposure of ParserKeyword.
DeckKeyword: shared_ptr<ParserKeyword> -> ParskerKeyword.
python/cxx/deck_keyword.cpp: cosntructor takes arg const ParskerKeyword&.
test_parser.py: simplified test_pyinut.
...
> python: DeckKeyword constructor, w/ ParserKeyword arg.

- opm/parser/eclipse/EclipseState/InitConfig/Equil.hpp
- src/opm/parser/eclipse/EclipseState/InitConfig/Equil.cpp
A small refactor to avoid spreading `Deckxxx`datastructures. 
Followup: https://github.com/OPM/opm-simulators/pull/2020
> Changed EquilRecord to take SI values instead of DeckRecord

- opm/io/eclipse/EGrid.hpp
- src/opm/io/eclipse/EGrid.cpp
- test_util/EclRegressionTest.cpp
- tests/test_EGrid.cpp
The arguments in function `getCellCorners(...)` are changed from `std::vector<double>` to `std::array<double,8>`. This change was triggered by similar modification of function `calculateCellVol(...)`
```C++
double calculateCellVol(const std::array<double,8>& X, const std::array<double,8>& Y, const std::array<double,8>& Z);
```
The modification in `calculateCellVol `was part of PR #1009.
> Changed EGrid API, function getCellCorners.

- opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/SummaryConfigTests.cpp
This PR reimplements the `SummaryNode` class in order not to use the `ecl::smspec_node` class from LibECL.  Consequently, we remove class `SummaryConfig`'s binding to LibECL.
Class `SummaryNode` maintains the same information as before.  We also implement a "named constructor" strategy to assign data members that only make sense for a subset of the node categories.  The previous member function `type` is renamed to `category` to identify the attachment category (e.g., Well, Group, Field, Block, Region).  In turn, we introduce a new `type` member function to identify the parameter kind (e.g, pressure, rate, cumulative total, well count) represented by a given node.  We furthermore capture whether or not the node is a user defined quantity (i.e., a UDQ).
We reimplement the keyword …
> Decouple SummaryConfig Class From LibECL

- opm/parser/eclipse/Deck/DeckItem.hpp
- src/opm/parser/eclipse/Deck/DeckItem.cpp
- tests/parser/integration/ParseKEYWORD.cpp
For dimensionsfull input properties like `PERMX` and `PORO` the `DeckItem` class used to have two `std::vector<double>`members, holding both the raw input values and the SI converted values. With this PR only one `std::vector<double>` is used and the data is transparently converted after what the user wants. 
This is in many ways less elegant; in particular the state changes in the `DeckItem` object - whcih are hidden behind a `mutable`modifier. The reason for doing this is that it is a quite low hanging fruit in reducing the memory consumption of the `Deck` datastructure; the absolute best case limit is 50% reduction memory; realistically 30%???
> DeckItem - use same store for both si and raw

- opm/parser/eclipse/Units/UnitSystem.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well2.cpp
- src/opm/parser/eclipse/Units/UnitSystem.cpp
- tests/parser/TimeMapTest.cpp
- tests/parser/UnitTests.cpp
This commit decouples the `UnitSystem` class from the LibECL type `ert_ecl_unit_enum`.  This, in turn, makes `UnitSystem` independent of LibECL.
Update the unit test accordingly, and include `<ert/util/util.h>` where needed.  This header was included transitively through `UnitSystem.hpp` before.
> Make UnitSystem Independent of LibECL

- opm/output/eclipse/Tables.hpp
- src/opm/output/eclipse/Tables.cpp
- tests/test_Tables.cpp
This commit removes the original member functions
```
void Tables::addPVTO()
void Tables::addPVTW()
void Tables::addPVTG()
```
since these are no longer needed.  The PVT tables are now defined in terms of the `addPVTTables()` member function
While here, also remove the fwrite() free function which was defined in terms of LibECL types.
Update the unit test accordingly.
> Table Linearisation: Remove Original PVT Functions

- CMakeLists_files.cmake
- opm/output/eclipse/VectorItems/tabdims.hpp
- src/opm/output/eclipse/Tables.cpp
- tests/test_Tables.cpp
This commit makes the table linearisation code independent of LibECL's `ecl_kw_magic.h` header.  In particular, we add a new set of vector items (`tabdims.hpp`) that describe the items we currently define and reimplement the member functions of the `Tables` class in terms of these items.
Update the unit test accordingly.
> Decouple Table Linearisation from LibECL

- opm/io/eclipse/EclOutput.hpp
- opm/io/eclipse/OutputStream.hpp
- src/opm/io/eclipse/OutputStream.cpp
- tests/test_OutputStream.cpp
This commit introduces a new `OutputStream` class for representing the summary specification file (`.SMSPEC`).  The stream is constructed with constant data (output directory, basename, start date &c), and provides a single `write()` member function that outputs a summary specification.
Each call to write rewinds the underlying stream's output position.  Class `EclOutput` grants friendship to the new output stream class in order to support easy stream rewinding.
Add a unit test to exercise the new class.
> Add File Manager Stream for Summary Specification

- msim/src/msim.cpp
- opm/io/eclipse/EclOutput.hpp
- opm/output/eclipse/EclipseIO.hpp
- src/opm/io/eclipse/EclOutput.cpp
- src/opm/io/eclipse/OutputStream.cpp
- src/opm/output/eclipse/EclipseIO.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/test_Summary.cpp
This PR consists of a few preparatory steps towards introducing a new writer for Flow's summary file (`*.UNSMRY` or `*.S000n`).
In particular, we
* Add a stream flushing operation to class `EclOutput`
* Ensure that connection keywords (e.g., `COPT`, `CWPR`) have correct types&mdash;especially cumulative totals vs. instantaneous rates&mdash;to fix an error in PR #1049 (commit 70daf0f2c)
* Forward-declare the `out::Summary` class in `EclipseIO.cpp` since the `EclipseIO` class does not substantively use `out::Summary` in its public implementation.  This reduces the build coupling slightly.
* Ensure that the files/result sets created in `test_Summary.cpp` always have uppercase filenames.
> Prepare New Summary Writer

- src/opm/output/eclipse/Summary.cpp
This PR pulls the table of evaluation functions out of the `Opm` namespace and into the existing anonymous namespace of Summary.cpp.  We do the same to the `well_efficiency_factor()` function.
This is an intermediate step towards enabling new writer code for Flow's summary files.
> Make Summary.cpp's Function Table Fully Private

- python/tests/test_parse.py
- python/tests/test_parse_deck.py
This PR circumvents the use of some parser functions from parser_module.py in tests.
> python: rewrite of tests using ParseContext.

- tests/parser/DeckValueTests.cpp
A compiler error has been reported on the: 
```C++
BOOST_CHECK( DeckKeyword( parser_keyword, {record1, record1}), std::invalid_argument);
```
"unfortunately" it works on my machine, and also on Jenkins - so the "fix" is a bit in the blind.
> Compile fixup

- python/cxx/deck_keyword.cpp
- python/tests/test_parser.py
Python:
Introducing a new `DeckKeyword` constructor:
```Python
DeckKeyword(Parserkeyword, [ record1, record2, .. etc] )
record1 = [value1, value2, ... etc.]
```
Possible use:
```Python
dkw = DeckKeyword(parser["CBMOPTS"], [["3*", "A", "B", "C", "2*", 0.375]])
```
> python: new DeckKeyword constructor takes DeckRecords

- opm/output/eclipse/Summary.hpp
- src/opm/io/eclipse/OutputStream.cpp
- src/opm/output/eclipse/Summary.cpp
- tests/test_OutputStream.cpp
This PR replaces the existing system for writing summary and specification (SMSPEC) files with a new implementation based on class `EclOutput`.  We package the evaluators of individual parameters in a set of classes determined by the parameter's category which each implement a virtual `update()` function.  This update function ultimately writes new values into a `SummaryState` object.
Add a factory-like system for instantiating the appropriate class depending on a `SummaryNode`'s `category()`.  Also, add a helper class for managing the parameters that a configured in a simulation
model's SUMMARY section in order to distinguish these from those parameters that are merely needed for restart purposes.  The summary class's `eval()` function then becomes a loop over the evaluators for …
> New summary writer

- opm/output/eclipse/RestartValue.hpp
Otherwise we cannot even resize a vector of it and this will be needed for restart when getting rid off the global grid on all processes.
I guess this should be uncontroversial?
> Make RestartKey default contructable.

- opm/output/eclipse/Summary.hpp
- src/opm/io/eclipse/OutputStream.cpp
- src/opm/output/eclipse/Summary.cpp
- tests/test_OutputStream.cpp
Backports PR #1082 to release/2019.10
Beginning of original message:
"This PR replaces the existing system for writing summary and specification (SMSPEC) files with a new implementation based on class EclOutput. We package the evaluators of individual parameters in a set of classes determined by the parameter's category which each implement a virtual update() function. This update function ultimately writes new values into a SummaryState object..."
> Backport PR 1082

- opm/parser/eclipse/EclipseState/Grid/GridProperty.hpp
- src/opm/output/eclipse/RegionCache.cpp
- src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- src/opm/parser/eclipse/EclipseState/Grid/GridProperties.cpp
- src/opm/parser/eclipse/EclipseState/Grid/GridProperty.cpp
- src/opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
- src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
- src/opm/parser/eclipse/EclipseState/Grid/TransMult.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
- tests/parser/ADDREGTests.cpp
- tests/parser/CopyRegTests.cpp
- tests/parser/Eclipse3DPropertiesTests.cpp
- tests/parser/EclipseStateTests.cpp
- tests/parser/EqualRegTests.cpp
- tests/parser/GridPropertyTests.cpp
- tests/parser/MultiRegTests.cpp
- tests/parser/PORVTests.cpp
- tests/parser/SatfuncPropertyInitializersTests.cpp
- tests/parser/integration/BoxTest.cpp
The PR #1046 was a late night hack to reduce memory usage in the 3D property system; that implementation was quite rushed and should probably die a silent death in `/dev/null` - but the point still remains that a refactoring of the property system is overdue, see also discussion here: https://github.com/OPM/opm-common/issues/929.
One of the commits from #1046 was to remove the `GridProperty::iget()` and `GridProperty::iset()` methods; that commit is recovered from #1046 in this PR. The reason I want to merge this is that the `iget()` - and in particular the `iget(i,j,k)` overload "peeks to much into" the implementation; and removing these methods should buy some freedom in changing the internals of the `GridProperty` class.
Downstream: 
https://github.com/OPM/opm-grid/pull/390 …
> Remove index access to GridProperty<T>

- opm/io/eclipse/ESmry.hpp
- src/opm/io/eclipse/ESmry.cpp
- tests/test_ESmry.cpp
Also notice the functionality for loading base run data has been improved 
```C++
explicit ESmry(const std::string& filename, bool loadBaseRunData=false);
```
This now support cases where restart run has unified results files but are restarted from a base runs with non-unified result files (and restart run with non-unified and base run with unified). 
The current version of ESmry have bugs with respect to base run with formatted result files and restart run with unformatted/binary (and visa versa). These bugs are now fixed.
> Updates of ESmry - now supporting non-unified result files.

- cmake/Modules/OpmSiblingSearch.cmake
but source lying around.
If you set CMAKE_INSTALL_PREFIX, have the dependencies installed there, but
the source of them lying around in the parent directory of the build
directory, then the build will fail starting with opm-models because
we assume that ../opm-material is a build directory and set opm-material_DIR
to it. CMake will complain about not finding opm-material-config.cmake or
Opm-materialConfig.cmake. With this commit we will only set opm-material_DIR
if the directory contains a file CMakeCache.txt (which should be the case in
a configured build directory.
Directory outline of the failing situation is
```
- ${CMAKE_INSTALL_PREFIX} # where all dependencies are installed
- parent_dir
|____ opm-common #source dir
|____ opm-material #source dir
|____ ...
|____ build #build …
```
> Allow building a module with dependencies installed (backport of #1110)

- tests/test_Restart.cpp
the tuple-from-initializer-list constructor is explicit.
ref https://ci.opm-project.org/job/opm-nightly-xenial/131/console
in particular
```
/build/opm-common-2019-10-17-gite815194/tests/test_Restart.cpp: In function 'Opm::EclIO::EclFile::EclEntry {anonymous}::ecl_file_iget_named_kw(Opm::EclIO::ERst&, const string&, int)':
/build/opm-common-2019-10-17-gite815194/tests/test_Restart.cpp:78:67: error: converting to 'Opm::EclIO::EclFile::EclEntry {aka std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Opm::EclIO::eclArrType, int>}' from initializer list would use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const char (&)[14], Opm::EclIO::eclArrType, int}; <template-parameter-2-2> = …
```
> fixed: build using gcc 5 (ubuntu xenial)

- tests/test_Restart.cpp
the tuple-from-initializer-list constructor is explicit.
Backport of #1116 to release.
> fixed: build using gcc 5 (ubuntu xenial) (backport of PR #1116

- CMakeLists.txt
this improves build throughput on jenkins since building this
large file will overlap more with other build tasks.
> changed: put the generated ParserKeywords.cpp first in list

- src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
We pass an int pointer to the function initCornerPointGrid.
With ACTNUM  this pointer was initialized with data pointer
of an int vector that we threw away before the function call
(otherwise it was null). To fix this we move the int-vector up one
scope.
> Fix memory error during EclipseGrid creation with Actnum. (backport PR #1125)

- CMakeLists_files.cmake
- examples/opmhash.cpp
- opm/common/OpmLog/Location.hpp
- opm/common/OpmLog/LogUtil.hpp
- opm/parser/eclipse/Deck/DeckKeyword.hpp
- opm/parser/eclipse/EclipseState/Schedule/Action/Condition.hpp
- opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
- src/opm/common/OpmLog/LogUtil.cpp
- src/opm/parser/eclipse/Deck/DeckKeyword.cpp
- src/opm/parser/eclipse/EclipseState/EclipseState.cpp
- src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Action/Condition.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.cpp
- src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
- src/opm/parser/eclipse/EclipseState/checkDeck.cpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
- src/opm/parser/eclipse/Parser/raw/RawKeyword.cpp
- src/opm/parser/eclipse/Parser/raw/RawKeyword.hpp
- src/opm/parser/eclipse/RawDeck/RawKeyword.cpp
- tests/parser/ACTIONX.cpp
- tests/test_OpmLog.cpp
Created a smal struct to keep track of the position of a keyword in the input deck; file and linenumber. For keywords which are created by parsing a string the filename will be `<memory string>`.
The location is passed as constructor argument to `DeckKeyword`so that the `DeckKeyword::setLocation()` could be removed - we all love immutable Riiigght?!
> Add small struct DeckKeyword::Location to simplify error reporting

- src/opm/common/utility/numeric/calculateCellVol.cpp
- src/opm/output/eclipse/AggregateMSWData.cpp
- src/opm/output/eclipse/AggregateUDQData.cpp
- src/opm/output/eclipse/CreateDoubHead.cpp
- src/opm/parser/eclipse/Deck/DeckItem.cpp
- src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
backports all fixes from #1096 that apply to release, i.e. all but 11462f7
> Some janitoring (partial backport of pr #1096)

- opm/parser/eclipse/EclipseState/Eclipse3DProperties.hpp
- opm/parser/eclipse/EclipseState/Grid/GridProperty.hpp
- src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- src/opm/parser/eclipse/EclipseState/Grid/GridProperty.cpp
- tests/parser/GridPropertyTests.cpp
- tests/parser/TransMultTests.cpp
New comment in code:
```C++      
/*  
The opm input handling is not really section aware, some keywords
should be handeled differently in the EDIT section and the GRID
section. In particular this applies top the transmissibility
multipliers MULT(XYZ) where they should be assigned and reassigned in
the GRID section, and applied multiplicatively in the EDIT section.
Here we have special cased hack for the MULT(XYZ) keywords, there are
probably other keywords as well which also should be handeled
differently in the GRID and EDIT sections, but this is handeled on a
bug by bug basis.
*/
```
It should be noted that a more significant refactoring of the 3D properties is under way: https://github.com/OPM/opm-common/pull/1056
> Multiply MULT(XYZ) keywords in the EDIT section

- jenkins/update-opm-tests.sh
happens when people manually close a previously opened PR
for the branch.
> fixed: allow branch to exist in opm-tests PR repo, but no PR

- python/tests/test_parser.py
- python/tests/test_state.py
- src/opm/parser/eclipse/EclipseState/Eclipse3DProperties.cpp
- src/opm/parser/eclipse/EclipseState/Grid/setKeywordBox.cpp
- tests/parser/EclipseStateTests.cpp
This relates to opm-simulators: issue https://github.com/OPM/opm-simulators/issues/2097.
When using BOX:
```
BOX
1* 1 1 1 3 3 /
```
This causes an exception. 
This PR remedies the situation.
> BOX keyword: using defaultApplied.

- opm/parser/eclipse/EclipseState/Aquancon.hpp
- src/opm/parser/eclipse/EclipseState/Aquancon.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFETP
- tests/parser/AquanconTests.cpp
By default, the aquifer connections can only be specified at the faces between active and inactive cells. 
The current implementation does not consider this logic, this PR is adding this part. 
It fixes running of some small test cases, while it looks there are still something missing for more larger and more complicated models. 
And also, when coming to active and inactive cells, some later grid processing might add more inactive cells. This PR does not consider these situations. 
Nevertheless, this PR is improving the implementation.
> improvements related to Aquifer modeling

- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
- tests/parser/UDQTests.cpp
This function will return a `std::set<UDQTokenType>` for all the the tokens which are in use for a `UDQDefine`statement. It is weird functionality - but hopefully useful for restart.
> Udq token types

- src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/MSW/updatingConnectionsWithSegments.cpp
- tests/parser/EclipseGridTests.cpp
- tests/parser/EclipseStateTests.cpp
- tests/parser/MultisegmentWellTests.cpp
- tests/parser/UDQTests.cpp
This PR addresses a few minor issues that I discovered when running opm-common's unit tests with [Address Sanitizer](https://en.wikipedia.org/wiki/AddressSanitizer).
Specifically
1. Do not use a deck's `ACTNUM` vector ~even~ if incorrectly sized.  This broke the [ACTNUM_BEST_EFFORT](https://github.com/OPM/opm-common/blob/390a29d425ecd5c57026a7e6731180f55a00785e/tests/parser/EclipseGridTests.cpp#L799-L801) unit test (index out of bounds).  With the new changes coming in the property systems this will be less needed for full decks, but we may need it for unit tests.
2. Leaking memory if `newConnectionsWithSegments` throws an exception.  Fixed by using a `unique_ptr<>` internally and returning the `.release()` of that `unique_ptr`.  Arguably, the function should return a `unique_ptr` itself …
> Resolve Address Sanitizer Issues

- opm/output/eclipse/VectorItems/intehead.hpp
- src/opm/output/eclipse/InteHEAD.cpp
- src/opm/output/eclipse/RestartIO.cpp
This changeset adds a simple one-line record to the screen and, typically, the .PRT file, each time a set of restart values are output to the (or a) restart file.  Format of the output is along the lines of
```
Restart file written for report step: 169/247.  Date: 2003/09/13
```
This is intended as simple information for human readers.  Machine readable data is already output to the actual restart files.
---
As an example, with this you can use a command like
```sh
$ grep '^Restart file' ./NORNE_ATW2013.PRT
```
to get output like
```
Restart file written for report step:   0/247.  Date: 1997/11/06
Restart file written for report step:   1/247.  Date: 1997/11/14
Restart file written for report step:   2/247.  Date: 1997/12/01
Restart file written for report step:   3/247.  Date: 1997/12/17 …
```
> Record Output of Restart File Data

- CMakeLists.txt
When opm-common is configured to embed the Python interpreter libpython must be linked transitively by downstream modules. Hacked into the venerable *Works for me* state here.
> Add Python library to opm-common_LIBRARIES cmake variable

- CMakeLists_files.cmake
- opm/common/utility/numeric/RootFinders.hpp
- tests/test_RootFinders.cpp
This new method is more robust, and improves performance with certain tricky functions, some of which are encountered in the well/thp code.
The method works by looking at the length of the bracketing interval, and if its length is not reduced enough (by a factor of sqrt(1/2), guaranteeing we accept no more than twice the number of steps required by bisection) we use a bisection step instead of a regula falsi step.
A test was added, it was previously missing for these methods. The test is a regression not functionality test, in that it only checks that the number of iterations used match the expected number.
This PR can be merged by itself. As it changes no existing methods it is a candidate for self-merging.
> Add combined regula falsi + bisection method, and test.

- opm/io/eclipse/ERst.hpp
- src/opm/io/eclipse/ERst.cpp
- src/opm/output/eclipse/LoadRestart.cpp
- test_util/EclRegressionTest.cpp
- test_util/convertECL.cpp
- tests/msim/test_msim.cpp
- tests/test_ERst.cpp
- tests/test_EclipseIO.cpp
- tests/test_OutputStream.cpp
- tests/test_Restart.cpp
Aquifer related array names in the restart output file (Eclipse format) can occur more that once for a given report step number. This will be the case if a model contains more that one analytic aquifer connected to the grid. Multiple instances of array names will also occur for models with local grid refinements (LGR). 
The API for the ERst class has been extended with more member functions in order to handle multiple instances of array names within a given report step.
This PR also include updates for program convertECL. The current version of the program have a bug with option -r if multiple instances of a array name occur. This has been fixed with this PR.
Notice that the program compareECL will also need an update, but this is not included in this PR.
> updates of ERst API, supports multiple occurrence of array names

- src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFETP
It makes difference for `FIELD` unit. 
Just for confirmation, 
the definition of the PI is `sm^3/day/bars`, it should be `LiquidSurfaceVolume/Pressure*Time`, instead of `LiquidSurfaceVolume/Pressure/Time`, right?
> correcting the unit in the AQUFETP definition

- opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
- tests/parser/RestartConfigTests.cpp
- tests/parser/TimeMapTest.cpp
This is intended to address problems with restart files not getting written at timesteps when they really should, based on the RPTRST keyword.
This logic happens in the TimeMap class. My interpretation of the "restart frequency logic" is (paraphrasing from code comment): return true (i.e. write a restart file) if the step is the first of each n-month or n-month period, starting from start_timestep - 1. Note that I did not change that API-quirk (subtracting 1) in order to avoid having to change too much other code.
Developed using test-driven development, so any bugs will have to be demonstrated by an added failing test (or pointing out that a test is wrong). :-) The changes to RestartConfigTests.cpp have been considered carefully by me to be correct, i.e. the existing test was wrong. …
> Fix TimeMap::isTimestepInFirstOfMonthsYearsSequence() method.

- opm/parser/eclipse/EclipseState/Grid/Box.hpp
- src/opm/parser/eclipse/EclipseState/Grid/Box.cpp
- tests/parser/integration/BoxTest.cpp
The box implementation was written at a time when I though you could create boxes within boxes; that is not the case. Rather a `BOX` within a `BOX` range will refer to the global box.
This PR is a small step in the 3D properties refactoring, when that is merged everything box related can be simplified further.
> Simplify the BOX implementation - prepare to drop the manager

- test_util/summary.cpp
The abs() call is ambiguous, and that is good: otherwise the abs(int) overload from C would be the one called on at least my (clang-using) system. Including `<cmath>` and explicitly using `std::fabs` is the clearest way to fix this.
Note that if you really need a generic abs() for a template context where you need to handle both integer and floating-point numbers, you can use the std::abs() template from `<cmath>` (since C++17, used to be only in `<cstdlib>` together with the C-inherited abs(int) overload).
I also took the liberty of updating the copyright header the way I assumed it should be. @tskille please check!
> Fix abs() ambiguity, add copyright headers.

- src/opm/parser/eclipse/share/keywords/000_Eclipse100/C/COALNUM
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMFCN
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCONPRI
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GIALL
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MASSFLOW
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MESSAGE
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PARAOPTS
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PCG32D
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PCW32D
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/RPTRST
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
added keywords GCONPRI, GIALL, MASSFLOW, MESSAGE, OUTSOL, PARAOPTS,  PVG32D, PCW32D.
The list of 'special' keywords that are not readable by the opm-parser system has been updated.
> added some 'special' keywords. Reorganized list of 'special' keywords.

- redhat/opm-common.spec
for some reason, rh7 does not link cmake3 to cmake,
while rh6 and rh8 does. cmake3 works everywhere.
> fixed: a regression snuck in while enabling redhat 8

- src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WPOTCALC
This keyword belongs in RUNSPEC at least in the documentation for Eclipse 100 2017.1.
> Change section for WPOTCALC keyword to RUNSPEC

- opm/parser/eclipse/EclipseState/Grid/NNC.hpp
- python/cxx/eclipse_state.cpp
- src/opm/output/eclipse/WriteInit.cpp
- src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
- tests/parser/integration/NNCTests.cpp
the two classes EDITNNC and NNC are very similar, which makes templating
useful. this small difference makes it hard to do. unify them.
> changed: rename accessor to data()

- src/opm/io/eclipse/EclFile.cpp
I noticed while profiling something else that restart file writing was taking much more time than it used to. And 99% of that time was spent in the ignore() call modified here. Replacing it with seekg() seems to give far better performance.
> Use seekg() rather than ignore() to skip ahead.

- opm/output/data/Wells.hpp
- src/opm/output/eclipse/LoadRestart.cpp
- src/opm/output/eclipse/RestartIO.cpp
Currently, only parts of the connection members are serialized in the XWEL structure.
while not really a problem, it became a problem for me due to https://github.com/OPM/opm-common/pull/1265
currently the test itself implements comparison operators. but since i add them globally in that PR, I had to remove the ones in the test file, and consequently I need all members serialized/deserialized for the test to still pass.
> added: serialize the whole connection struct to OPM_XWEL

- opm/output/eclipse/VectorItems/msw.hpp
This commit identifies certain items in restart vectors ISEG and RSEG that pertain to valves (keyword `WSEGVALV`) and spiral ICDs (keyword `WSEGSICD`).  In particular, we identify segment type flag and a couple of relevant values for this flag.  Also, relevant parameters that describe the geometry and pressure drops of these devices.
Thanks to @tskille and @jalvestad for assistance in classifying these items.
> Prepare Restart File Support for Valves and ICDs

- src/opm/output/eclipse/AggregateMSWData.cpp
This pull request contains a fix for the ISEG[0] parameter in the Eclipse compatible Restart file. 
The fix will trigger changes in the reference data for ISEG[0], in the case: 
opm-tests/msw_3d_hfa 3D_MSW.DATA case. This has been checked vs. E100 results.
> correction to ISEG[0] in AggregateMSWData.cpp

- opm/output/data/Cells.hpp
- opm/output/data/Wells.hpp
- opm/output/eclipse/RestartValue.hpp
- tests/test_Restart.cpp
This will be used for some tests in opm-simulators. I open this early to help explain why https://github.com/OPM/opm-common/pull/1266 is required.
> added: comparison operators for various output structures

- src/opm/output/eclipse/LoadRestart.cpp
- src/opm/output/eclipse/RestartIO.cpp
- tests/test_Restart.cpp
This fixes test_Restart.
I am sorry for the breakage. Due to several screwups I was falsely under the impression that the test passed.
1) I had accidentially squashed an initializer for the thp variable in an unrelated commit in the branch where I tested.
2) I thought I had tested on jenkins, but I ran the downstream builder and the tests here were not executed.
I have here opted to rather fix the serialization than adding the initializer. Since all data in these structs are uninitialized, I don't want to just initialize the one entry. I rather leave it up to those two know this code better to decide whether proper initialization is too costly to have or not. Since this again only affects the XWEL code and that is slated for removal, I chose the "local" fix.
> fixed: serialize thp to OPM_XWEL

- src/opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
The transmissibility multiplier is used in a loop over all elements, and the copying from only active to global was expenseive. Temp fix.
> Disable use of FieldPropsManager in MULTREGTScanner

- opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
- tests/parser/TransMultTests.cpp
The FieldPropsmanager had a default constructor - but that produced an invalid instance.
> Fp default

- opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
- src/opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
Cache the region properties for the transmissibility multipliers - to enable testing of the new 3D implementation.
Replace #1284 as fix for performance regression in #1240.
> Transmult regions

- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
Makes things safer - and a step on the way towards a meaningful default constructor.
> Remove grid member from FieldProps

- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
- tests/parser/FieldPropsTests.cpp
Comment in code:
```c++
/*
The ACTNUM and PORV keywords are special cased with quite extensive
postprocessing, and should be access through the special ::porv() and
::actnum() methods instead of the general ::get<T>( ) method. These two
keywords are also hidden from the keys<T>() vectors.
*/
```
> Special case ACTNUM and PORV in the FieldProps keys() method

- opm/parser/eclipse/EclipseState/Grid/TransMult.hpp
- src/opm/parser/eclipse/EclipseState/EclipseState.cpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
- src/opm/parser/eclipse/EclipseState/Grid/TransMult.cpp
- tests/parser/TransMultTests.cpp
YAPR in the endless stream of small refactorings to prepare for new 3D implementation.
> Use std::vector<double> instead of GridProperty<double> in TransMult

- src/opm/output/eclipse/WriteInit.cpp
The code to write INIT files has a loop over all int properties; this typically includes the "ACTNUM" keyword - which should not be output to the INIT file (I think ....?). This PR - with the necessary update_data is again a preparation for the 3D refactor.
In the `FieldProps`based implementation the `ACTNUM`field is treated differently, and it will not be necessary to special case at the output level.
> Make sure the ACTNUM field is not output to the INIT file

- CMakeLists_files.cmake
- opm/output/data/Aquifer.hpp
- opm/output/eclipse/RestartValue.hpp
- opm/output/eclipse/VectorItems/aquifer.hpp
- opm/output/eclipse/VectorItems/intehead.hpp
- src/opm/output/eclipse/InteHEAD.cpp
- src/opm/output/eclipse/LoadRestart.cpp
This adds a basic protocol for retrieving simple scalar data for each analytic aquifer, specifically from `XAAQ`.  At the moment we only support retrieving the aquifer pressure and the total produced liquid volume from the aquifer and into the reservoir model.
> Load Restart: Support Basic Quantities from Analytic Aquifers

- opm/parser/eclipse/Deck/DeckItem.hpp
- opm/parser/eclipse/Deck/DeckKeyword.hpp
- src/opm/parser/eclipse/Deck/DeckItem.cpp
- src/opm/parser/eclipse/Deck/DeckKeyword.cpp
- src/opm/parser/eclipse/Parser/ParserItem.cpp
- tests/parser/DeckValueTests.cpp
- tests/parser/ParserTests.cpp
Default values have been an endless source of small quibbles. With this PR we export the distinction between valid defaults and invalid defaults.
> Differentiate between valid and invalid default values while parsing

- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Action/ASTNode.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Action/ASTNode.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionValue.hpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/ACTIONX.cpp
This is response to issues https://github.com/OPM/opm-common/issues/1243 and https://github.com/OPM/opm-common/issues/1243.
ASTNode will be supplied with a variable determining what type of keyword (function) is used. This is the FuncType func_type variable.
> added enum class FuncType for ASTNode.

- opm/output/data/Wells.hpp
- src/opm/output/eclipse/AggregateWellData.cpp
The summary keywords `FMWPR` and `FMWIN`count the number of flowing producers and injectors. In current code a well is set to flowing if one of the [Rates](https://github.com/OPM/opm-common/blob/master/opm/output/data/Wells.hpp#L37) is set; however it does not check the numeric value - i.e. if a rate is set to `0.0` the well will counted as flowing.
In this PR the numerical values is checked.
> Determine that wells are flowing from nonzero rates

- opm/parser/eclipse/Python/Python.hpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- src/opm/parser/eclipse/Parser/raw/RawConsts.hpp
- src/opm/parser/eclipse/Python/EmbedModule.hpp
- src/opm/parser/eclipse/Python/Python.cpp
- src/opm/parser/eclipse/Python/PythonInterp.cpp
- src/opm/parser/eclipse/Python/PythonInterp.hpp
- src/opm/parser/eclipse/share/keywords/900_OPM/P/PYINPUT
- tests/parser/EmbeddedPython.cpp
This allows python code to be written in eclipse .DATA files. 
Note: it is not yet possible to embed Python while still running python (e.g. the below example is not possible for the python Parser.).
The syntax is:
```
PYINPUT
import numpy as np
dx = np.array([0.25, 0.25, 0.25, 0.25])
active_unit_system = context.deck.active_unit_system()
default_unit_system = context.deck.default_unit_system()        
kw = context.DeckKeyword( context.parser['DX'], dx, active_unit_system, default_unit_system )
context.deck.add(kw)
<<<
```
Some reading:  https://stackoverflow.com/questions/24656088/static-member-variable-for-class-that-is-dynamically-loaded
> Parse PYINPUT

- test_util/EclRegressionTest.cpp
- test_util/compareECL.cpp
~~This PR adds a new flag `bool allowKeywordReorder` which is passed to the function comparing keywordlist in the `EclRegressionTest` class. For `INIT` files a value of `true` is passed, whereas `false` - corresponding to current behavior is passed to the other files.~~
With this PR the INIT files are special cases somewhat in the regression testing: If it is detected that the keywords have been reordered that is flagged as an error, but the comparison continues, and if at the end of the test run *only* the keyword order has been changed that can be read from the error message.
The motivation for this is #1236 - where the regression tests fail because the `xxxNUM` keywords are reordered in the new implementation. The current orderering is quite random, and it feels a bit weird to add …
> Regression testing: Detect reordering of keywords in the INIT file

- opm/parser/eclipse/Units/UnitSystem.hpp
- opm/parser/eclipse/Units/Units.hpp
- src/opm/parser/eclipse/Units/UnitSystem.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGSICD
- tests/parser/UnitTests.cpp
This PR introduces a couple of new units of measure for ICD-related quantities, especially AICD and SICD strength parameters.  Add base unit "GeomVolume" ([Length]**3) and 'measure' entities
```
geometric_volume      (= GeomVolume)
geometric_volume_rate (= GeomVolume / Time)
icd_strength          (= Pressure / (GeomVolume / Time)**2)
```
Add conversion factor unit tests for these, and also complete the set of unit tests for FIELD, LAB, and PVT_M to cover measures that were not already there.
Also add a parser Dimension ("GeometricVolume") to play the role of [Length]**3 in .json files.
> Add Dedicated Units of Measurement for SICD Strength Parameter

- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
The implementation of direct TRANx manipulations in the keyword is hacky at best; still so ;-(
> Add default init for TRAN keywords + dimension

- opm/parser/eclipse/Parser/ParserKeyword.hpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/STOG
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
- tests/parser/ParserTests.cpp
Keywords such as STOG, STOW, STWG has the following structure:
record1 : a value
record2: a table
This structure may repeat itself. There is no support for this in opm-common and the keywords are on the 'special' keyword list. 
This PR makes it possible to create support for these keywords. 
also keyword STOG has been added.
> introducing keywords using alternating records.

- opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
- src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
The satfunc initializers get a grid argument; but they actually only need the cell depths. This changes to use cell depth.
> Satfunc initializers get cell_depth instead of grid argument

- opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
- src/opm/parser/eclipse/EclipseState/EclipseState.cpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
- tests/parser/FieldPropsTests.cpp
When postprocessing has deactivated some cells the active cells in the `FieldProps` must be updated. This was previously done with a `reset_grid()` call - now it is instead `reset_actnum()`. We work on a strict need to know basis!
> Fp reset actnum

- opm/output/eclipse/VectorItems/msw.hpp
- opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
- src/opm/output/eclipse/AggregateMSWData.cpp
This commit identifies well segments that correspond to SICDs (input keyword `WSEGSICD`) and captures those in the ISEG vector.  Furthermore, we output characteristic properties of such SICD segments (e.g, the length, the base strength, calibration fluid properties) in the RSEG vector.
Thanks to @tskille and @jalvestad for invaluable assistance in identifying these items.
---
Note that this PR depends on both PRs #1269 and #1251 and must not be merged before those are installed in master. On top of those PRs, we change only the `AggregateMSWData.cpp` file. This PR can be used separately for testing purposes.
> Add Restart File Support for Spiral Inflow-Control Devices

- CMakeLists_files.cmake
- opm/common/utility/ActiveGridCells.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
- src/opm/common/utility/ActiveGridCells.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
- tests/parser/ScheduleTests.cpp
- tests/test_ActiveGridCells.cpp
To do this we only need to query whether a cell is active or not by its cartesian index. Constructing an EclipseGrid just for that seem overkill and will in the future not be possible anymore on all ranks of a parallel run. Hence we construct a simple utility class the only uses the information of the globalCell arrays.
This will need a downstream PR in opm-simulators.
> Use minimal information when filtering connections

- src/opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
Previously there was a hard check that the region values in the THPRES keyword was <= max(EQLNUM); just use a warning and ignore it.
> THPRES: Warning if region values exceed max(EQLNUM)

- opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
- tests/parser/FieldPropsTests.cpp
There are many callsites where we get a properyty from the container - and then forget about it.Do not let the container grow in this case.
> Add FieldPropsManager::get_copy() which does not add to container

- src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
The guide rate properties was not included in the GroupProducrtionProperties== - this was masked by another bug, but lead to false positive here: https://github.com/OPM/opm-common/pull/1329/files
> Add GuideRate properties to GroupProduction::operator==

- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
> fix initialization list order

- opm/parser/eclipse/Deck/DeckKeyword.hpp
- src/opm/parser/eclipse/Deck/DeckKeyword.cpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
This seems unused. Less entangled (and helps serialization).
> remove unused member parser_keyword from DeckKeyword

- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
Observe that the thermal keywords are added *without* any default initialization; that is according to the documentation - but unfortunately the old code had default initialization which then was nonsensical.
This will induce downstream changes in opm-material
> Add support for keywords THxxxx in FieldProps

- src/opm/output/eclipse/WriteInit.cpp
There is a tiny bug in WriteInit.cpp: lack of bracket for function 'writePoreVolume'.
> WriteInit.cpp fix

- opm/parser/eclipse/EclipseState/Edit/EDITNNC.hpp
- opm/parser/eclipse/EclipseState/Grid/NNC.hpp
- opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.hpp
- opm/parser/eclipse/EclipseState/Tables/ColumnSchema.hpp
- opm/parser/eclipse/EclipseState/Tables/Rock2dTable.hpp
- opm/parser/eclipse/EclipseState/Tables/Rock2dtrTable.hpp
- opm/parser/eclipse/EclipseState/Tables/TableSchema.hpp
- opm/parser/eclipse/EclipseState/Util/OrderedMap.hpp
- src/opm/parser/eclipse/EclipseState/Edit/EDITNNC.cpp
- src/opm/parser/eclipse/EclipseState/Grid/NNC.cpp
- src/opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
- src/opm/parser/eclipse/EclipseState/Tables/ColumnSchema.cpp
- src/opm/parser/eclipse/EclipseState/Tables/Rock2dTable.cpp
- src/opm/parser/eclipse/EclipseState/Tables/Rock2dtrTable.cpp
- src/opm/parser/eclipse/EclipseState/Tables/TableSchema.cpp
I am working towards enabling parsing the input file only on the root process in parallel. This means the all the data types that come out of this needs to be serialized for mpi broadcast.
Since we are doing the serialization external to the classes, this means we need accessors for all private data, and the ability to recreate the classes from separately stored data. Since I, and I know others, are not particular found of mutable class state accessors, this means a constructor taking the data as parameters. Finally, to enable testing, equality operators must be available.
This is the first flush of class modifications required. More to come, but bite size is of value here.
> Preparation for serialization support

- opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp
- opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp
- src/opm/output/eclipse/AggregateMSWData.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- tests/parser/MultisegmentWellTests.cpp
This PR adds support for identifying well segments that correspond to valves (input keyword `WSEGVALV`) and captures those in the ISEG vector.  Furthermore, we output characteristic properties of such valve segments (e.g, the valve length, the base strength, and cross-sectional area) in the RSEG vector.
Thanks to @tskille and @jalvestad for invaluable assistance in identifying these items.
---
Note that this PR depends on both PRs #1269 and #1257 and must not be merged before those are installed in master.  On top of those PRs, we change only the `AggregateMSWData.cpp` file.  This PR can be used separately for testing purposes.
> Add Restart File Support for WSEGVALV Devices

- src/opm/output/eclipse/AggregateMSWData.cpp
not sure if this is actually the desired outcome, but i'm not changing anything except killing the warning.
> add a default to quell unhandled value in switch warning

- opm/parser/eclipse/Deck/DeckKeyword.hpp
- opm/parser/eclipse/Parser/ParserEnums.hpp
- opm/parser/eclipse/Parser/ParserKeyword.hpp
- src/opm/parser/eclipse/Deck/DeckKeyword.cpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- src/opm/parser/eclipse/Parser/ParserEnums.cpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
- src/opm/parser/eclipse/Parser/raw/RawEnums.hpp
- src/opm/parser/eclipse/Parser/raw/RawKeyword.cpp
- src/opm/parser/eclipse/Parser/raw/RawKeyword.hpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/C/CECONT
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCUTBACT
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GECONT
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MPFNNC
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
- tests/parser/ParserTests.cpp
This PR makes it possible to parse keywords with a nested record structure, referred to as double-record keywords. Such keywords are `CECONT`, `GCUTBACT`, `GECONT` and `MPFNNC`.
Example:
```
CECONT
PROD1 4* CON NO /
TR1 1000.0 0.5 /
TR2 2* 1* 0.8 2* /
TR3 1500.0 0.1 /
/
PROD2 5 6 3 3 CON+ NO /
TR3 100.0 0.05 /
/
PROD3 6* /
TR4 200 5* /
PLY 1* 0.7 /
/
/
```
For this PR, `DeckKeyword` has been added a bool signifying a "double-record" structure. However, no structural change has been med to the `m_recordList` structure. The records are dumped into the m_recordList structure, with a empty record signifying the end of a set of records. 
Also for this PR: keywords `CECONT`, `GCUTBACT`, `GECONT` and `MPFNNC` are added.
> Can parse keywords of type double-record. 

- opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQASTNode.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQSet.cpp
- tests/parser/UDQTests.cpp
The initial version of the UDQ parser parsed expressions like:
```
A - B - C
```
incorrectly - what was actually evaluated was: `A - (B - C)`. Fixed now. Current needs some polish before it is in a mergeable state, but I put it put for early testing.
> UDQ parse A - B - C

- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- tests/parser/ScheduleTests.cpp
This is ugly. The embedded comment in `handleWELTARG()` explains the situation.
The culprit here is that the handling of dimensions in the UDA quantities is not well designed; it should not be too difficult to fix, but for the Christmas deadline I would suggest going with this band-aid solution; it has been tested on large relevant field case and seems to work.
I had to comment out one test with quite intricate BHP behavior.
> Temporarily bypass the unit conversion in handleWELTARG

- jenkins/update-opm-tests.sh
Avoid non-sense issues in opm-tests.
@bska this should take care of it.
> fixed: do not open a issue/PR if no tests failed

- src/opm/parser/eclipse/Parser/Parser.cpp
- src/opm/parser/eclipse/share/keywords/000_Eclipse100/U/UDT
- src/opm/parser/eclipse/share/keywords/keyword_list.cmake
- tests/parser/ParserTests.cpp
UDT is the last known keyword. 
It has been postponed for a while due to its complicated structure. 
This PR modifies the parser code so that the Parser will handle UDT keywords (skip them), but will not add them to deck.
> Parser will skip keyword UDT.

- python/cxx/eclipse_grid.cpp
- python/tests/test_props.py
Adding python bindings for more member functions in class Opm::EclipseGrid. 
- get a numpy array for all grid cells (in one go) using Opm::EclipseGrid::getCellVolume(...)
- get a numpy array for all grid cells (in one go) using Opm::EclipseGrid::getCellDepth(...)
- get cell depth for individual cells using Opm::EclipseGrid::getCellDepth(...)
> additional python bindings for eclipse_grid

- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
This commit ensures that we record a "well open" event whenever
```
Schedule::updateWellStatus
```
switches a well's status to OPEN.  We need this information in order to correctly output RFT data configured with WRFT or the FOPN option of keyword WRFTPLT.  Previously, we recorded such events only in the context of the WELOPEN keyword.
> Schedule: Record RFT Well Open Events on Status Changes

- opm/parser/eclipse/Parser/ParserRecord.hpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- src/opm/parser/eclipse/Parser/ParserRecord.cpp
- src/opm/parser/eclipse/Parser/raw/RawKeyword.cpp
- src/opm/parser/eclipse/Parser/raw/RawKeyword.hpp
- src/opm/parser/eclipse/share/keywords/900_OPM/P/PYACTION
- src/opm/parser/eclipse/share/keywords/900_OPM/P/PYINPUT
- tests/parser/EmbeddedPython.cpp
- tests/parser/PYACTION.cpp
Small baby refactorings to enable multi record Python keywords:
```
PYACTION
WWCT /
if context.well_var("OP1", "WWCT") > 0.80:
context.schedule.shut_well("OP1")
PYEND
```
the important point is the normal first record "WWCT /". 
There will be more steps.
> Py code records

- opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
- src/opm/parser/eclipse/Deck/DeckItem.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- tests/test_ArrayDimChecker.cpp
There are a few more, but some at least are related to the field property refactoring so not worth touching. The DeckItem.cpp change might require a small explanation: the template in question is specialized in the code above, so the explicit instantiation does not do anything.
> Silence some warnings.

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/Action/PyAction.hpp
- opm/parser/eclipse/Python/Python.hpp
- python/cxx/summary_state.cpp
- python/tests/test_summarystate.py
- src/opm/parser/eclipse/EclipseState/Schedule/Action/PyAction.cpp
- src/opm/parser/eclipse/Python/Python.cpp
- src/opm/parser/eclipse/Python/PythonInterp.cpp
- src/opm/parser/eclipse/Python/PythonInterp.hpp
- tests/parser/EmbeddedPython.cpp
Expose basic functionality for calling python code in the Schedule section.
Right now it is not hooked up in the main simulator - only in a test. The technical bit and pieces of this now works; the most important open question - in my head at least - is how we should configure/determine *when* the `PYACTION` code should run. The `ACTIONX` has a well defined configuration for this which we can choose to copy, but personally I do not think that is optimal.
**ACTIONX:**
First of all it should be noted that the `ACTIONX` keyword is actually mainly a *condition*, the actual *action* is  a list of normal `SCHEDULE` section keywords - i.e.
```
-- Define the condition:
ACTIONX
<NAME>   <TRIGGER_COUNT=1>   <TRIGGER_WAIT>  /
'WWCT'  'OP1' > 0.80 /
/
WELOPEN
'OP1'  'SHUT' /
/
ENDACTIO
```
When this …
> Use pyaction

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/RFTConfig.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/RFTConfig.cpp
- tests/parser/RFTConfigTests.cpp
- tests/parser/ScheduleTests.cpp
Generally, this commit captures more of the surrounding context of calls to the `updateRFT()` and `updatePLT()` member functions.  We need this additional context in order to handle the conflicting semantics of output requests `WRFT` and `WRFTPLT:FOPN`.  The former generates RFT output when the well opens if this event does not happen earlier in the simulation schedule than the output request.  Otherwise no RFT data is emitted.  The latter outputs RFT data at request time if well opens no later than the request; otherwise at well-open time.
To this end, switch the `well_open_rft_name` data member from an `unordered_set` of well names into an `unordered_map` from well names to RFT output request times.  With this additional information we can use `well_open_rft_time` to infer the …
> Rework RFT Config to Handle More Cases

- opm/common/utility/TimeService.hpp
- opm/parser/eclipse/Deck/UDAValue.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
- opm/parser/eclipse/EclipseState/Util/OrderedMap.hpp
- opm/parser/eclipse/Units/Dimension.hpp
- src/opm/common/utility/TimeService.cpp
- src/opm/parser/eclipse/Deck/UDAValue.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
- src/opm/parser/eclipse/Units/Dimension.cpp
This contains various fixes for the schedule serialization.
However, I cannot make this work properly without the use of mutable accessors. I do not understand why it makes a difference, but it does; if i serialize into a temporary and pass the well and group maps through the constructor, everything goes tits up in the SPE9_CP_GROUP test and I cannot figure out why (the rest of the tests pass fine). If I however deserialize directly into the member, everything appears to be working fine.
I have separated out the mutable accessor addition and marked the commit as temporary. I hope that some more eyes can help me crack this problem.
Likewise, there are separate commits marked as temporary in the downstream.
> More serialization effort

- opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
With the new constructor added in #1425 it should be possible to serialize using the normal (new) constructor; have therefor removed the code specially added for serialization. 
PR in opm-simulators coming.
> Time map rm cons

- opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
- tests/parser/TimeMapTest.cpp
Add optional restart information to a a time_map. If the restart information is provided in the time map constructor the time points before the restart date are blanked out with an invalid value.
Another step on this journey: https://github.com/OPM/opm-common/issues/1396
> Time map restart

- opm/parser/eclipse/EclipseState/Runspec.hpp
- src/opm/parser/eclipse/EclipseState/Runspec.cpp
- tests/parser/RunspecTests.cpp
This commit internalises the TOLCRIT keyword into the `EclipseState` for subsequent use in determining critical saturations when processing saturation function keywords such as SGOF and SOF3. Specifically, we add a new type
```
Opm::SatFuncControls
```
that, at present, stores only the TOLCRIT data item (defaulted to the keyword's default value).  Client code can then retrieve the value by calling the
```C++
SatFuncControls::minimumRelpermMobilityThreshold()
```
member function.
Add a new data member of this type to the `Opm::Runspec` class so that we complete the chain from `EclipseState`, and a few simple unit tests to exercise the expected functionality.
> Internalise TOLCRIT Keyword

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/SimulationConfig/BCConfig.hpp
- opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
- src/opm/parser/eclipse/EclipseState/SimulationConfig/BCConfig.cpp
- src/opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
Simple class to internalize Boundary Conditions in EclipseState - and reduce Deck usage downstream.
> Add class to internalize BC keyword - and add to SimulationConfig

- opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
- python/cxx/field_props.cpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/output/eclipse/WriteInit.cpp
- src/opm/parser/eclipse/EclipseState/EclipseState.cpp
- src/opm/parser/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
- src/opm/parser/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
- src/opm/parser/eclipse/Python/PythonInterp.hpp
- tests/parser/EclipseGridTests.cpp
- tests/parser/EclipseStateTests.cpp
- tests/parser/FieldPropsTests.cpp
- tests/parser/MULTREGTScannerTests.cpp
- tests/parser/MultiRegTests.cpp
- tests/parser/ThresholdPressureTest.cpp
- tests/parser/TransMultTests.cpp
- tests/parser/integration/BoxTest.cpp
- tests/test_regionCache.cpp
motivation: an upcoming parallel frontend to the field props manager.
templated functions cannot be virtualized, and thus having these exposed
would give a great chance of confusing the users in the downstream
code, where properties would be caught from the (potentially) empty
backend instead of from the frontend.
i realize this isn't necessarily the most popular change, but i cannot get around it without complicating matters a lot in the downstreams. this is the smallest cost in my opinion.
> changed: hide the templated 'has' and 'get' interfaces in FieldPropsManager

- opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.hpp
- opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.hpp
- src/opm/output/eclipse/WriteInit.cpp
- src/opm/parser/eclipse/EclipseState/EclipseState.cpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldProps.hpp
- src/opm/parser/eclipse/EclipseState/Grid/FieldPropsManager.cpp
- src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
- tests/parser/ACTIONX.cpp
- tests/parser/ConnectionTests.cpp
- tests/parser/FieldPropsTests.cpp
- tests/parser/GeomodifierTests.cpp
- tests/parser/GroupTests.cpp
- tests/parser/MULTREGTScannerTests.cpp
- tests/parser/MessageLimitTests.cpp
- tests/parser/MultiRegTests.cpp
- tests/parser/ParseContextTests.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/SimulationConfigTest.cpp
- tests/parser/ThresholdPressureTest.cpp
- tests/parser/TransMultTests.cpp
- tests/parser/TuningTests.cpp
- tests/parser/UDQTests.cpp
- tests/parser/WLIST.cpp
- tests/parser/WellSolventTests.cpp
- tests/parser/WellTests.cpp
- tests/parser/WellTracerTests.cpp
- tests/parser/integration/ParseKEYWORD.cpp
- tests/parser/integration/ScheduleCreateFromDeck.cpp
This changeset passes the run's notion of its active phases, an object of type `Opm::Phases`, through to the initialisation layer for the saturation functions' scaling properties.  In particular, this allows us to discriminate between the phases and to not index into tables or properties that would not be appropriate (e.g., maximum gas saturation (SGU) in a simulation run without active gas).
Moreover, we now have enough information to know to look for SOF2 in two-phase run using family II saturation function keywords.  These changes are necessary in order to extend Flow's support for the FILLEPS output request to two-phase runs.
As a result, this allows us to reenable honouring the `FILLEPS` keyword when outputting the INIT file for two-phase systems (O/G and O/W).  This was disabled in …
> INIT File: Reenable FILLEPS for Two-Phase Systems

- opm/output/eclipse/InteHEAD.hpp
- opm/parser/eclipse/Units/UnitSystem.hpp
- src/opm/output/eclipse/CreateInteHead.cpp
- src/opm/output/eclipse/InteHEAD.cpp
- src/opm/parser/eclipse/Units/UnitSystem.cpp
- tests/parser/UnitTests.cpp
- tests/test_InteHEAD.cpp
To enable instantiating the unit system from a restart/init file. Writing of INTEHEAD keyword uses `UnitSystem` class instead of intermediate enum `RestartIO::UnitSystem` which has been removed.
> Add UnitSystem functionality to handle eclipse integer id

- opm/output/data/Wells.hpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/output/eclipse/LoadRestart.cpp
- tests/test_RFT.cpp
- tests/test_Summary.cpp
This PR introduces a new protocol for communicating a well's active constraint (i.e., its current target control mode) between the running simulator and the restart file.  In particular, we add a new type
```
Opm::data::CurrentControl
```
whose data members indicate if the well is a producer or injector and, depending on that state, carries information about the pertinent active control mode.  The `prod` member should be defined for producing wells and the `inj` member should be defined for injectors.  Default-constructed objects of this type are 'invalid' and not output to the restart file.  Add a `CurrentControl` member to the `Opm::data::Well` type to enable communicating this information using existing restart interfaces.
Expand existing unit tests to exercise the new data member.
> Add Restart Infrastructure for Well's Active Control

- opm/parser/eclipse/EclipseState/AquiferCT.hpp
- opm/parser/eclipse/EclipseState/Aquifetp.hpp
- src/opm/parser/eclipse/EclipseState/AquiferCT.cpp
- src/opm/parser/eclipse/EclipseState/Aquifetp.cpp
- tests/parser/AquiferCTTests.cpp
- tests/parser/AquifetpTests.cpp
The purpose of this PR is to internalize the Aquifer configuration in the EclipseState and thereby reduce deck usage downstream. This PR just contains initial refactoring, and not the final step moving the Aquifer code in under the EclipseState umbrella.
Downstream: https://github.com/OPM/opm-simulators/pull/2319
> Eclstate aquifer

- test_util/EclRegressionTest.cpp
DOUBHEAD array is set to be using strict tolerances in compareECL since this array holds data which is not dependent on simulation results. 
This is not 100% true since item number 2 (DOUBHEAD[1]) is related to size of next simulation step (used by flow when restarting). This property is highly dependent on simulation results. 
Suggesting to skip this item when testing DOUBHEAD. The alternative would be to stop using strict tolerances on DOUBHEAD array.
> Disable checking of DOUBHEAD[1] with compareECL

- GenerateKeywords.cmake
- opm-common-prereqs.cmake
- opm/parser/eclipse/Parser/ParserKeyword.hpp
- src/opm/io/eclipse/ERst.cpp
- src/opm/parser/eclipse/Parser/ParserKeyword.cpp
Just preparing this for when we decide to move to gcc 4.9 as minimum.
> changed: use std::regex instead of boost::regex

- opm/common/utility/platform_dependent/disable_warnings.h
- opm/io/eclipse/rst/group.hpp
- opm/io/eclipse/rst/well.hpp
- opm/output/eclipse/DoubHEAD.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQParser.hpp
- tests/parser/FieldPropsTests.cpp
- tests/parser/UDQTests.cpp
- tests/rst_load.cpp
With this, opm-common compiles warning-free with clang for me.
> Silence a few warnings, remove some end-of-line whitespace.

- src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQFunctionTable.cpp
The comment in the code explains the change. Basically, we cannot expect two `unordered_map` objects to have the same (un)order of elements. Without this, I get a test failure in opm-simulators for `test_ParallelRestart`.
> Fix operator==() of UDQFunctionTable.

- opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
- src/opm/output/eclipse/AggregateGroupData.cpp
- src/opm/output/eclipse/AggregateUDQData.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
- tests/parser/GroupTests.cpp
- tests/parser/integration/ScheduleCreateFromDeck.cpp
The GCONINJE keyword can be used to specify multiple phases. This PR implements support for that.
Observe the second commit where the original code use integer value '3' for the gas phase in the restart file; this can not possibly carry over to the multiple phases situation. I guessed the value 4 which is used elsewhere when creating a phase sum; alternatively this should be quite different?
Good if some of the restart experts could take a look.
Apart from the [Temp] commit I consider this complete now. Will let it linger until someone find the time to implement the necessary changes downstream.
> Support multiple phases in group injection

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- tests/parser/ScheduleRestartTests.cpp
This PR adds an optional `const RstState *` to the `Schedule`constructor - to facilitate loading/initializing the `Schedule` object from restart information. The PR only has an api change - actually "doing something" is still on my machine.
Part of #1396
> Schedule add rst argument

- cmake/Modules/OpmLibMain.cmake
> fixed: guess -std=c++17 flag if cmake version is too old

- opm/parser/eclipse/EclipseState/Tables/BrineDensityTable.hpp
This is partially my fault. The build test in https://github.com/OPM/opm-material/pull/392#event-3043667816 was outdated since it sat for a long time without being processed. https://github.com/OPM/opm-material/pull/395 introduced the requirement for begin() / end on the data container passed.
> fixed: add begin/end members to BrineDensityTable

- opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
- tests/parser/TimeMapTest.cpp
> Internalize the existence of SKIPREST in the TimeMap

- src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
This means we accept strings such as "Sep" and "oCT" as valid months, not just "SEP" and "OCT".
> Use upper case to look up month numbers.

- examples/opmpack.cpp
- opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.hpp
- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- opm/parser/eclipse/Units/Units.hpp
- opm/parser/eclipse/Utility/String.hpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/parser/eclipse/Deck/DeckItem.cpp
- src/opm/parser/eclipse/EclipseState/EclipseState.cpp
- src/opm/parser/eclipse/EclipseState/Grid/PinchMode.cpp
- src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
- src/opm/parser/eclipse/EclipseState/checkDeck.cpp
- src/opm/parser/eclipse/Parser/ParseContext.cpp
- src/opm/parser/eclipse/Parser/Parser.cpp
- src/opm/parser/eclipse/Parser/raw/RawKeyword.cpp
- src/opm/parser/eclipse/RawDeck/RawKeyword.cpp
- src/opm/parser/eclipse/Units/UnitSystem.cpp
- tests/parser/InitConfigTest.cpp
- tests/parser/ParseContext_EXIT1.cpp
- tests/parser/ParserIncludeTests.cpp
- tests/parser/ParserTests.cpp
- tests/parser/StringTests.cpp
- tests/parser/integration/IncludeTest.cpp
- tests/parser/integration/parse_write.cpp
- use already introduced trim functions more
- use already introduced uppercase functions
- use strtoul instead of lexical_cast
- add replace_all replacement
- add split_string replacement
- avoid use of join
> Continue replacing boost usage

- src/opm/output/eclipse/AggregateConnectionData.cpp
I *think* the background for this `std::abs` was that we used to have a home made scheme where connections were assigned negative completion numbers internally. This scheme has now ended - and the use `std::abs( )` in the output code just looks misleading.
> Store complnum value directly without taking std::abs()

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/AquiferConfig.hpp
- opm/parser/eclipse/EclipseState/EclipseState.hpp
- src/opm/parser/eclipse/EclipseState/AquiferConfig.cpp
- src/opm/parser/eclipse/EclipseState/EclipseState.cpp
- tests/parser/AquiferTests.cpp
This PR adds a `AquiferConfig`class to the `EclipseState` - this should be the final "remove deck usage from Aquifers" PR - was a longer haul than I had anticipated.
~~#1452 should be merged first.~~
> Eclstate aquifer config

- CMakeLists.txt
- ExtraTests.cmake
- cmake/Modules/OpmSatellites.cmake
Motivation: Being able to build without boost libraries (of course there is more to that which will come later).
> changed: disable building of test suite if Boost::test is not found

- opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp
This also refactors the get() methods to have a single common implementation rather than copies with tiny differences.
> Add overloads to eval() and get() for simpler generic usage.

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
In order to improve error message in the case of invalid well name
Part of #1396
> Add report_step argument to Schedule::invalidNamePattern()

- examples/opmpack.cpp
fixes build with gcc 7
closes #1513
> changed: use constructs available in filesystem TS to obtain relative path

- opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- tests/parser/GroupTests.cpp
The method has very similar intended usage as the method of the same name in the Well class.
Requires opm-simulator PR for the serialization.
> Add Group::isAvailableForGroupControl() method.

- opm/parser/eclipse/Deck/DeckItem.hpp
- opm/parser/eclipse/Deck/UDAValue.hpp
- python/cxx/deck_keyword.cpp
- python/python/opm/_common.py
- python/python/opm/io/deck/__init__.py
- python/tests/data/SPE1CASE1.DATA
- python/tests/test_parse_deck.py
This PR is fixing missing support for getting values from deck items which can be UDQ.
in example, current version of **DeckKeyword** in **opm.io.deck** will raise the following error when trying to get target oil rate (item 4 in WCONPROD). 
```
ValueError: DeckItem::value_ref<double> Item of wrong type. this->type: UDAValue OIL_TARGET
```
This PR also includes changes to the API for a few of the member functions.  Main motivations for these additional changes is to make the api simpler to use.
> Python bindings for DeckItem, adding support for UDA type

- CMakeLists_files.cmake
- opm/parser/eclipse/EclipseState/Schedule/ScheduleTypes.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/ScheduleTypes.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellInjectionProperties.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/injection.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/eval_uda.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/eval_uda.hpp
- tests/parser/ScheduleTests.cpp
- tests/parser/WellTests.cpp
- tests/test_restartwellinfo.cpp
The type of a well - i.e. injector/producer and the phase is a surprsingly flickety small piece of code. As preparation/simplification for #1396 I am in the process of creating a small class for it, and as a preparation for that again - the current `InjectorType` enum is moved out from the `Well` class to a separate compilation unit; that again is a preparation to avoid circular dependencies.
I don't *really* like this change myself, but it gets the job done.
Dwonstream: https://github.com/OPM/opm-simulators/pull/2389
> Move enum Well:InjectorType to new file ScheduleTypes

- opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.hpp
- src/opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.cpp
This makes no sense to me. The limits should be checked in the model (in fact, they are also checked there already).
> changed: don't enforce foam model limits in parser

- opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.hpp
- src/opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.cpp
Foam cases should run without FOAMOPTS available. That means
we need to default the mobility model to a valid value.
This also adds enum value 'FUNC' and handles setting the default model
if only transport phase is unspecified.
> fixed: update FoamConfig defaults

- opm/parser/eclipse/EclipseState/Tables/PlyshlogTable.hpp
- opm/parser/eclipse/EclipseState/Tables/RocktabTable.hpp
- opm/parser/eclipse/EclipseState/Tables/TableContainer.hpp
- src/opm/parser/eclipse/EclipseState/Tables/TableContainer.cpp
- src/opm/parser/eclipse/EclipseState/Tables/Tables.cpp
These extend the SimpleTable class and thus needs to be serialized as the actual types.
> Prepare serialization for PlyshlogTable and RocktabTable

- opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
- tests/parser/integration/ScheduleCreateFromDeck.cpp
In order to support the extended network model going forwards, the method `Opm::Group::parent()` is split in the API into two new methods, `Opm::Group::control_group()` and `Opm::Group::flow_group()`. These methods give the names of the parent node in the group control hierarchy and network structure, respectively.
While for the standard network model these two values will be the same (and the same as `::parent()`), code that presently calls `::parent()` should be revisited with an eye to the question of which parent group is desired.
> Separates Opm::Group::parent() for the extended network model

- opm/parser/eclipse/Deck/UDAValue.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
- opm/parser/eclipse/Units/Dimension.hpp
- opm/parser/eclipse/Units/UnitSystem.hpp
- src/opm/parser/eclipse/Deck/DeckItem.cpp
- src/opm/parser/eclipse/Deck/UDAValue.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellInjectionProperties.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
- src/opm/parser/eclipse/Units/Dimension.cpp
- src/opm/parser/eclipse/Units/UnitSystem.cpp
- tests/parser/DeckTests.cpp
- tests/parser/UDQTests.cpp
- tests/parser/UnitTests.cpp
- tests/parser/WellTests.cpp
UDA values and dimensions have been a long source of frustration. The main point about this PR is to ensure that UDAValues (i.e. rates in this case) have the correct unit irrespective of whether the come from the `Schedule` / `Deck` or the restart file.
In addition there are several small drive-by improvements/simplifications in the `Dimension` and `UDAValue` classes.
Downstream: https://github.com/OPM/opm-simulators/pull/2414
Part of #1396
> Uda value dim constructor

- opm/output/eclipse/VectorItems/well.hpp
- opm/parser/eclipse/EclipseState/Schedule/ScheduleTypes.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/output/eclipse/LoadRestart.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/ScheduleTypes.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- tests/parser/WTEST.cpp
- tests/parser/WellTests.cpp
The type of a well - i.e. injector/producer and the phase is a surprsingly flickety small piece of code; implemented as a class here. ~~Depends on: #1527 and https://github.com/OPM/opm-simulators/pull/2389 which must be merged first.~~
This is not very elegant - and might not be the final solution; but it works for now.
Downstream: https://github.com/OPM/opm-simulators/pull/2392
Part of #1396
> Add WellTypes class

- src/opm/parser/eclipse/EclipseState/Schedule/OilVaporizationProperties.cpp
in particular the UNDEF -> false condition causes issues
in user code.
> simplify the OilVaporization equality operator

- cmake/Modules/FindParMETIS.cmake
This fixes a cmake issue by adding the missing include(CheckIncludeFile).
> [bugfix][cmake] Fix FindParMETIS check

- src/opm/output/eclipse/AggregateMSWData.cpp
The `AggregataeMSWData.cpp` implementation did not use the named enums when assembling information.
> Use enum values to look up indices when assembling segment info

- opm/parser/eclipse/EclipseState/EclipseState.hpp
This moves serialization of EclipseState closer to home.
> add serialization template to EclipseState

- opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
- src/opm/io/eclipse/rst/connection.cpp
Changed the numerical value used to indicate: "No this connection is not attached to a segment". This is to simplify ecl interop.
Part of #1396
> The numerical value 0 is used to signify no connection <-> segment

- opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
- src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
I see no reason why these are shared_ptr. Let's simplify.
> changed: store Regdims and Eqldims as regular members, not shared ptrs

- opm/parser/eclipse/EclipseState/EclipseState.hpp
- opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp
Add a has() method to the GuideRate class, for use downstream.
Also silence a warning due to missing virtual destructor for EclipseState. Although the missing destructor so far did not lead to bugs as far as I can tell (the derived class is used through shared_ptr<EclipseState>, but constructed through the templated constructor which embeds a type-erased proper destruction mechanism), it is better to do it as it would be expected (for example, naked pointer deletes will then work correctly instead of slicing).
> Add GuideRate::has() method.

- opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/MSW/Compsegs.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
When attaching a segment to a connection the connections `insert_index`was updated. This gave complications when restarting.
Part of #1396
> Fixed: do not update insert_index when linking segment -> connection

- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/SummaryConfigTests.cpp
This feature adds API support for the `RUNSUM` keyword in `Opm::SummaryConfig`, through:
1. The `RUNSUM` keyword being read and added as an `Opm::SummaryNode`
2. The method `Opm::SummaryConfig::createRunSummary` being exposed to test for its presence
> Adding support for the RUNSUM keyword in Opm::SummaryConfig

- opm/io/eclipse/ESmry.hpp
- src/opm/io/eclipse/ESmry.cpp
- tests/test_ESmry.cpp
This feature adds support for inspecting the units in use for a given key in an ESmry object. This is achieved by extending the `Opm::EclIO::ESmry` API as follows:
`const std::string& Opm::EclIO::ESmry::get_unit(const std::string&) const` is added, returning the units name (e.g. `"DAYS"`, `"STB/DAY"`) for the given key if present, raising an exception otherwise.
> Adding support for inspecting units to Opm::EclIO::ESmry

- opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
This minifix resolves an issue where two structs were forward declared as classes, resulting in a number of compiler warnings:
1. `Opm::RestartIO::RstConnection`
2. `Opm::RestartIO::RstWell`
> Minifix: Fixes forward declaration compiler warnings

- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
Time to start replacing external serialization with internal serialization. This moves the SummaryConfig class completely to the new approach.
> add serialization template to SummaryNode

- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionParser.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/SummaryConfigTests.cpp
This feature renames `Opm::SummaryNode` to `Opm::SummaryConfigNode`, in preparation for introducing a different type under the name `Opm::SummaryNode`.
> Rename SummaryNode to SummaryConfigNode

- opm/io/eclipse/EclFile.hpp
- opm/io/eclipse/EclOutput.hpp
- opm/io/eclipse/EclUtil.hpp
- src/opm/io/eclipse/EclFile.cpp
- src/opm/io/eclipse/EclOutput.cpp
- src/opm/io/eclipse/EclUtil.cpp
- test_util/convertECL.cpp
- tests/test_ERst.cpp
- tests/test_EclIO.cpp
- EclIO classes have been updated to support arrays with size beyond numeric limits for integers
- int data type changed to data type long int in EclEntry tuple in EclFile.hpp
- the standard 16 byte header used when size of array are within range for int data type
- an alternative 20 byte binary header used when size of an array is beyon numeric limits for int
The EclFile binary array header contains 24 bytes, where 8 bytes is used to specify that the header contains 16 bytes of header data. Example below of a standard binary header
```
size on disk   4 |    8   |     4 |   4 |  4     
example       16 |  ZCORN | 79200 | REAL| 16
```
This header will be used whenever the size of the array is within limits for 4 byte integers. This ensures that we are supporting existing post processing …
> Adding support for larger EclFile arrays

- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
- tests/parser/ConnectionTests.cpp
- tests/parser/MultisegmentWellTests.cpp
- tests/parser/ScheduleTests.cpp
A small trivial refactor to support #1601
Dwonstream: https://github.com/OPM/opm-simulators/pull/2481
> Move Connection::Order member from Well to WellConnections

- src/opm/output/eclipse/Summary.cpp
> adding a few connection summary keywords

- CMakeLists_files.cmake
- msim/src/msim.cpp
- opm/output/data/Groups.hpp
- opm/output/eclipse/Summary.hpp
- opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
- src/opm/output/eclipse/Summary.cpp
- tests/UDQ_ACTIONX_TEST1_U.DATA
- tests/test_Summary.cpp
- tests/test_Summary_Group.cpp
This pullrequest includes changes in opm-common needed to hold the current Production and Injection Group control parameters for use in output to summary file and for use in output of Eclipse Compatible restart file. The changes to write the control status to the summary file is also included. 
This pull request is needed for opm/opm-simulators#2459 to be able to build.
The pull request is ready for review and merge from my side.
> Changes in opm-common for current Production/Injection Group Control parameters

- opm/parser/eclipse/EclipseState/Schedule/Well/Connection.hpp
- opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
- tests/parser/ConnectionTests.cpp
- tests/parser/MultisegmentWellTests.cpp
- tests/parser/ScheduleTests.cpp
To provide some safety for matching up simulated connection data and declared connection data when writing restart file.
> Add global_index to Connections

- opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
gcc is more forgiving with default template parameters than clang.
Closes #1610
> fixed: make a two-param map template for splitDynMap

- opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
- src/opm/output/eclipse/AggregateWellData.cpp
- src/opm/output/eclipse/Summary.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
- tests/parser/ScheduleTests.cpp
- tests/parser/WellTests.cpp
- tests/test_Summary.cpp
- tests/test_Summary_Group.cpp
This PR adds support for the SUMMARY section `WMCTL` keyword.  This keyword outputs a numeric code, an integer value, for all configured wells at all times and enables more visual inspection of how 
the wells' active controls change over time--either in response to explicit target modes in the input or as a result of limits becoming active.
Some example `WMCTL` values are
* `-1`: Well is under control by a containing group
* `0`: Well is shut
* `1`: Well is controlled by its own oil-rate target
* `2`: Well is controlled by its own water-rate target
* `3`: Well is controlled by its own gas-rate target
* `4`: Well is controlled by its own liquid-rate target
* `5`: Well is controlled by its own reservoir voidage volume replacement rate target
* `6`: Well is controlled by its own tubing-head …
> Support Outputting Active Well Control to Summary File

- opm/parser/eclipse/Parser/Parser.hpp
- src/opm/parser/eclipse/Parser/Parser.cpp
The implementation uses `std::stack` and therefore needs a declaration of this type in scope.  This apparently built by accident earlier. While here, also include a few other headers to make `Parser.[hc]pp` more self-contained.
> Parser.cpp: Include Missing Header

- src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.cpp
R1 is supposed to be water-liquid ratio and R2 is gas-liquid ratio for target LIQ.
> fix bug in guiderate model

- opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
Another tiny compile fix, uncovered when refactoring downstream.
> Add missing header inclusion.

- opm/io/eclipse/EclFile.hpp
- opm/io/eclipse/EclOutput.hpp
- opm/io/eclipse/EclUtil.hpp
- python/cxx/eclipse_io.cpp
- src/opm/io/eclipse/EclFile.cpp
- src/opm/io/eclipse/EclOutput.cpp
- src/opm/io/eclipse/EclUtil.cpp
- tests/test_ERst.cpp
All EclIO classes and associated tests has been checked and updated. This includes cpp file for python bindings
- long int -> int64_t
- unsigned long int -> uint64_t
> replacing long int and unsigned long int

- src/opm/output/eclipse/LoadRestart.cpp
Use global index when assembling connection rates / pressure from XCON keyword in restart file.
> Load restart XCON data

- src/opm/output/eclipse/AggregateConnectionData.cpp
- tests/test_AggregateConnectionData.cpp
This is in top of #1615 
As part of #1396 - and specifically the MSW support the connections are shuffled around in different orders. With this PR the connection rates supplied from the simulator - and eventually output to the XCON vector - are assembled based on the global index of connection - thereby allowing different storage order in `WellConnections` and `data::Well::Connection` (and the restart file ....).
The (second to ...) last commit in this series changes a test (which I had written ....). Grateful if someone takes a look at that.
This PR also changes the XCON vector in the MSW test and will require an update_data before it can be merged. I argue that there is a bug in master for how the XCON data is distributed , and that this PR fixes the bug - but please double check my …
> Get connection rates from well rates object

- opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
- src/opm/output/eclipse/AggregateConnectionData.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
- src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
- tests/parser/WellTests.cpp
1. If the well is MSW the ~~wells~~ connections in the WellConnection class is sorted in output
order in the ::order() method, and retained that way.
2. Add method WellConnection::output() which return a vector of connection
pointers sorted in output order.
The purpose of this is to recover the correct connection order when initializing the `WellConnections` from a restart file. Part of #1396
> Changes in WellConnection ordering

- src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
This simplifies logic downstream, otherwise we will need to check explicitly for the "FIELD" group name in more places.
> Make the FIELD group unavailable for higher level control.
