OPM/opm-common

src/opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculator.cpp

Fix warning with unused variable

---

opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
src/opm/io/eclipse/EclFile.cpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp

Built with clang, it had some useful complaints.

Some bug fixes

---

opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
tests/parser/DynamicStateTests.cpp

Add function DynamicState::update_range()

---

tests/parser/ACTIONX.cpp

Add test for boolean logic

---

opm/parser/eclipse/EclipseState/Schedule/Action/Condition.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Condition.cpp
tests/parser/ACTIONX.cpp

There are quirks enough for everyone :-)

Handle parenthesis in the Actionx::Condition class

---

opm/parser/eclipse/EclipseState/Schedule/MSW/AICD.hpp
opm/parser/eclipse/EclipseState/Schedule/MSW/SICD.hpp
src/opm/parser/eclipse/EclipseState/Schedule/MSW/AICD.cpp

Fix AutoICD serialization and make it testable.

Fix AutoICD serialization

---

opm/output/data/Aquifer.hpp

Add serialization for aquifers

---

tests/parser/ScheduleTests.cpp

Use raw string literals for test decks.

Multiline strings

---

opm/parser/eclipse/EclipseState/Schedule/TimeMap.hpp
src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp

Use start_time instead of invalid time as dummy for restart

---

src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
tests/parser/ScheduleTests.cpp
tests/parser/TimeMapTest.cpp

Timemap allow rst

---

src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp

Use std::make_shared<> instead of new

---

opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculator.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculator.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/PAvgCalculatorCollection.cpp
tests/parser/PAvgTests.cpp

Small improvements / preparations for WBP summary keyword

Wbp improvements

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/output/eclipse/CreateDoubHead.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/TuningTests.cpp
tests/test_DoubHEAD.cpp

Handle the `Tuning` as part of `ScheduleState`.
Downstream: https://github.com/OPM/opm-simulators/pull/3005

Schedule tuning

---

opm/parser/eclipse/EclipseState/Schedule/Action/Condition.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Condition.cpp
tests/parser/ACTIONX.cpp

Small utility function to simplify #2188

Add Condition::open_paren() and Condition::close_paren()

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/ScheduleTests.cpp

Internalize the nupcol property in the new `ScheduleState`class.
Downstream: https://github.com/OPM/opm-simulators/pull/3004

Schedule nupcol

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/output/eclipse/DoubHEAD.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/ScheduleTests.cpp

Downstream: 
https://github.com/OPM/opm-material/pull/437
https://github.com/OPM/opm-simulators/pull/3007

Schedule oilvap

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp

First steps to allow repeated iterations over the keywords in the `SCHEDULE` section.

Sched rerun

---

opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/Schedule/Events.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Events.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/EventTests.cpp
tests/parser/GeomodifierTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/TuningTests.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp
tests/parser/integration/TransMultIntegrationTests.cpp

Use `ScheduleState` to manage events
Dwonstream: https://github.com/OPM/opm-simulators/pull/3010

Sched events

---

opm/parser/eclipse/EclipseState/Schedule/MessageLimits.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/MessageLimits.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/MessageLimitTests.cpp

Internalize the `MESSAGES` keyword in the `ScheduleState` class
Downstream: https://github.com/OPM/opm-simulators/pull/3011

Sched message limits

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp

Another small step in the #2176 sequel

Sched global whistctl mode

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/ScheduleTests.cpp

Downstream: https://github.com/OPM/opm-simulators/pull/3013

Handle well test configuration with ScheduleState

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/GroupTests.cpp

Downstream: https://github.com/OPM/opm-simulators/pull/3015

Manage GConSale and GConSump with ScheduleState object

---

msim/src/msim.cpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/WLIST.cpp

Handle Well Lists with ScheduleState
Dwonstream: https://github.com/OPM/opm-simulators/pull/3016

Sched wlist

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/NetworkTests.cpp

Another step in the #2176 refactor

Manage Network configuration with ScheduleState

---

CMakeLists_files.cmake
opm/parser/eclipse/EclipseState/Aquifer/Aquancon.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/Aquancon.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferHelpers.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferHelpers.hpp

to make function neighborCellInsideReservoirAndActive more reusable.

creating AquiferHelpers

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Static schedule information has been collected in a separate struct

Assemble static schedule information in ScheduleStatic

---

msim/src/msim.cpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/CreateActionxDims.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/ACTIONX.cpp

Downstream: https://github.com/OPM/opm-simulators/pull/3021

Sched action

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/output/eclipse/AggregateUDQData.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/UDQTests.cpp

Use ScheduleState to handle UDQ active

Sched udq active

---

src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/output/eclipse/AggregateUDQData.cpp
tests/parser/ScheduleTests.cpp
tests/test_LGOData.cpp
tests/test_restartwellinfo.cpp

Use ordinary map commits

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/GroupTests.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

Remove member to track create time from Group

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Small step in the #2176 sequel

Use names in api for group-group update

---

python/cxx/schedule.cpp
python/tests/test_schedule.py

Add very basic Python wrapping for ScheduleState

---

opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
opm/parser/eclipse/EclipseState/Tables/FlatTable.hpp
opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/parser/eclipse/EclipseState/Tables/Tables.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/D/DIFFC
tests/parser/TableManagerTests.cpp

This adds the necessary keywords to support diffusion in Flow.

Add support for DIFFC and DIFFUSE

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellMatcher.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellOrder.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellMatcher.cpp
tests/parser/ScheduleTests.cpp
tests/parser/UDQTests.cpp

Wells from wellmatcher are sorted by insert order

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/WellTestConfig.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestConfig.cpp

Another step in the #2176 sequel

Rename schedulestate updates

---

python/setup-test.sh.in

Small utility useful for local testing.

Fix bug in python/setup-test.sh.in

---

src/opm/parser/eclipse/Deck/DeckItem.cpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFET
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFETP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENDSCALE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENKRVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENPCVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENPTVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENSPCVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FLUXTYPE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMFCN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/I/IMKRVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/I/IMPTVD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/ROCKPAMA
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SCDPDIMS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/S/SIGMA
src/opm/parser/eclipse/share/keywords/000_Eclipse100/T/TEMPNODE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/T/TRPLPORO
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WELSOMIN
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGSOLV

Uncovered by trying to parse the test suite supplied with Eclipse.
Some missing, some typos, some inconsistencies.

Fix bugs in keyword definitions

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/ScheduleSerializeTest.cpp

Ma - look I can write templates ;-)
@bska - can you take this for a ride?
<sub>Bjarne, forgive him, for he do not know what he is doing.</sub>

Pack only unique VFP tables

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
python/cxx/schedule.cpp
python/tests/test_schedule.py
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ArrayDimChecker.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/ScheduleSerializeTest.cpp
tests/parser/ScheduleTests.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

Use ScheduleState to manage groups. Part of #2176

Group sched state

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WTEST.cpp

Revert #2158
Part of #2176 - preparation for #2264

Well status scalar

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

Remove unused arguments

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp

Remove UDQParams( Deck ) constructor

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
tests/parser/ScheduleTests.cpp
tests/parser/UDQTests.cpp

Sched unique

---

src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp

Avoid use after move

---

opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
tests/parser/ACTIONX.cpp

From an ACTIONX keyword: export the list of wells requesting in this ACTIONX keyword which request WELPI

Export list of WELPI wells from an ACTIONX keyword

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/NameOrder.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/NameOrder.cpp
tests/parser/ScheduleTests.cpp

Well get by insert index

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp

Response to: https://github.com/OPM/opm-common/pull/2284#pullrequestreview-587540638

Use template predicate and perfect forwarding

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/ACTIONX.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

Small change to simplify WELPI + ACTIONX
Dwonstream: https://github.com/OPM/opm-simulators/pull/3057

Store target_wellpi in simple map member of ScheduleState

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

It is getting close - very close ;-)

Handle WELPI + ACTIONX

---

src/opm/parser/eclipse/EclipseState/Aquifer/Aquancon.cpp
tests/parser/AquiferTests.cpp

Implement add and multiply semantics for repeated AQUANCON keywords

---

opm/parser/eclipse/EclipseState/Aquifer/Aquancon.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/Aquancon.cpp
tests/parser/AquiferTests.cpp

Since OPM/opm-common#2297 this multiplier has been fixed at 1.0 - removing it completely.

Remove aqucon mult

---

opm/parser/eclipse/EclipseState/Schedule/VFPInjTable.hpp
opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.hpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/VFPInjTable.cpp
src/opm/parser/eclipse/EclipseState/Schedule/VFPProdTable.cpp
tests/parser/ScheduleTests.cpp
tests/parser/TableManagerTests.cpp
tests/parser/WellTests.cpp

- Add member KeywordLocation to vfp tables
- Improve error messages
- Remove `array_type` typedef - use `std::vector<double>`
- Use class based enums
- Replace `assert(x)` -> `if (!x) throw`
Downstream: https://github.com/OPM/opm-simulators/pull/3066

VFP Table updates

---

src/opm/output/eclipse/Summary.cpp

@jalvestad : I believe this should be right!

 Network variables are stored with SummaryState::update_group_var

---

opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.hpp

MIcro micro changes to refactor RestartConfig

Restart config

---

opm/parser/eclipse/EclipseState/Schedule/RFTConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/WriteRFT.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/RFTConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/parser/RFTConfigTests.cpp
tests/parser/ScheduleRestartTests.cpp
tests/parser/ScheduleSerializeTest.cpp
tests/parser/ScheduleTests.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

Handle RFT with the SchedState mechanism

Use SchedState to handle RFT configuration

---

src/opm/output/eclipse/EclipseIO.cpp

This member function is no longer constant time so it makes sense to limit the number of calls.

Call Schedule::first_RFT() Once Only

---

opm/common/utility/numeric/RootFinders.hpp

@tskille please see if this fixes your issue.

Do not print debug message to LOG/PRT file

---

src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp

SummaryConfig: allow region numbers beyond NUMFIP

Region input error

---

opm/common/utility/TimeService.hpp
opm/parser/eclipse/EclipseState/Schedule/DynamicState.hpp
opm/parser/eclipse/EclipseState/Schedule/RFTConfig.hpp
src/opm/common/utility/TimeService.cpp
src/opm/io/eclipse/ERsm.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/IOConfig/RestartConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionContext.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp
src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQContext.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/DynamicStateTests.cpp
tests/parser/TimeMapTest.cpp

More schedule refactor cleanups.

Remove timemap

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
python/cxx/schedule.cpp
python/tests/test_schedule.py
src/opm/output/eclipse/EclipseIO.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/integration/IOConfigIntegrationTest.cpp

More preparations for schdeule refactor finalization
Downstream: https://github.com/OPM/opm-simulators/pull/3100

Hide RestartConfig as private member of Schedule class

---

tests/parser/IOConfigTests.cpp
tests/parser/RestartConfigTests.cpp

Use multiline string literals

---

tests/parser/RestartConfigTests.cpp

Use the `Schedule`object instead of the `RestartConfig` object when testing the restart configuration. Preparation to remove the RestartConfig object completely.

Use schedule object in testing of restart configuration

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.hpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRate.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCONINJE
tests/parser/ScheduleTests.cpp

Internalize guiderate config items from GCONINJE

Gconinje guiderate

---

opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquiferCell.hpp

adding init_pressure in the serilization of NumericalAquiferCell

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp
tests/VFP_CASE.DATA
tests/parser/RestartConfigTests.cpp
tests/parser/ScheduleTests.cpp

Add month and year bookkeeping in order to implement restart configuration in ScheduleState

Sched state sim step

---

CMakeLists.txt

Remove cmake include of pybind11 CMakeLists.txt

---

opm/common/utility/TimeService.hpp
opm/io/eclipse/EGrid.hpp
opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/SingleNumericalAquifer.hpp
tests/parser/RestartConfigTests.cpp
tests/parser/ScheduleTests.cpp

This fixes a compile issue for me, and silences warnings.

Minor fixes

---

tests/parser/RestartConfigTests.cpp

Small preparation for: https://github.com/OPM/opm-common/pull/2347

Remove special mnemomics from testing

---

opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp

Small simple way to get directly at well CMODE

Add shortcuts to get injectorcontrols from Well

---

opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.cpp

upstream of PR https://github.com/OPM/opm-grid/pull/516.

function to ouput the cell volume for numerical aquifer cells

---

opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
tests/test_Summary.cpp

The main usage of this class will be here: https://github.com/OPM/opm-common/pull/2373

Add special treatment of connection variables in SummaryState

---

tests/test_Restart.cpp

Update creation of test data to support: https://github.com/OPM/opm-common/pull/2373

Update test fixtures

---

tests/parser/RestartConfigTests.cpp

Part of: https://github.com/OPM/opm-common/pull/2347

Fix test assert and temporarily disable

---

opm/output/data/Aquifer.hpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/output/eclipse/Summary.cpp

This commit adds support for calculating and outputting the CT-specific summary vectors "AAQTD" (dimensionless time, real time divided by aquifer's time constant) and "AAQPD" (dimensionless pressure-influence function evaluated at dimensionless time).

Support CT-Aquifer Dimensionless P/T Summary Vectors

---

opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/Aquancon.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/Grid/FieldProps.cpp

Partial fix to: https://github.com/OPM/opm-simulators/issues/3126

Aquifer grid order

---

src/opm/output/eclipse/Summary.cpp

The summary vectors
```
AAQP (pressure), AAQR (rate), AAQT (volume)
```
must be available for output to the restart file's `XAAQ` array for all analytic aquifers.  Additionally, the summary vectors
```
AAQTD (dimensionless time), AAQPD (dimensionless pressure)
```
must be available for restart output to `XAAQ` in the case of Carter-Tracy aquifers.
This PR ensures that those values are always calculated and stored in the `SummaryState`.

Configure Aquifer Summary Output Needed for Restart

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Make sure a confusing last report step message is not written out

---

src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCONINJE

Yet another small rst inspired change

Rename GCONINJE item and use compiled constants

---

opm/parser/eclipse/EclipseState/Runspec.hpp

Add custom comparison function for Welldims to simplify restart testing

Add Welldims comparison ignoring location member

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Micro improvement for increased clarity

Move restart information to ScheduleStatic

---

opm/parser/eclipse/EclipseState/Schedule/ScheduleState.hpp

Reorder members in ScheduleState

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp

Replace DIY optional with std::optional

Use std::optional<Phase> instead of std::pair<Phase, bool>

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Fix an oversight from the Schedule refactor effort

Add schedule deck member to Schedule::operator==()

---

opm/parser/eclipse/EclipseState/EclipseConfig.hpp
src/opm/parser/eclipse/EclipseState/EclipseConfig.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp

Ecl config fix

---

opm/parser/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/parser/eclipse/EclipseState/Tables/TableManager.cpp

Some issues(?) with restart and JFunc - this is just a minor improvement on the way. Maybe it fixes it?

Use std::optional instead of std::shared_ptr to manage JFunc

---

tests/test_InteHEAD.cpp

Including the maximum number of well lists per well and maximum dynamic well lists added in commit 278cd0a24 (PR #2368).

Initialise All Well Table Dimensions

---

redhat/opm-common.spec

fix redhat packaging

---

src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp

Ahhh - this should be the last nail in the : https://github.com/OPM/opm-simulators/pull/3062 coffin

Make sure the affected_wells variable is passed to applyWellopen()

---

CMakeLists.txt
python/setup.py.in

Issues building with lto
- missing source file
- some libfmt issues (mostly also seen with lto)

Fix some python bindings issues

---

opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
tests/parser/EclipseGridTests.cpp

We all like `mutable`- riiiiight!
Downstream: https://github.com/OPM/opm-simulators/pull/3153

Store the active volume with a mutable in the grid

---

python/cxx/eclipse_io.cpp
python/tests/test_erst.py

> bug related to occurence parameter in function get_erst_vector(..)
> additional python unittest related to this function

fixing bug for python bindings ERst

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
tests/parser/GroupTests.cpp

Another microstep in the restart sequel

Return std::optional<Phase> for Group::topup_phase()

---

opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateConfig.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateConfig.cpp

Another optional in the restart effort

Use std::optional<> in GuideRateConfig

---

opm/parser/eclipse/EclipseState/Grid/FieldData.hpp

Needed for Debian sid and maybe testing.

Include stdexcept header to fix compilation with g++-10

---

src/opm/output/eclipse/Summary.cpp

Inspired in @bska PR #2426 :smile:

Fix Well Temperature Output

---

src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp

Fix to issue reported by @jalvestad

let cmode FLD override yes/no in item8 in GCONPROD and GCONINJE

---

opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.hpp
opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquiferConnection.hpp
opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.hpp
opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/SingleNumericalAquifer.hpp
opm/parser/eclipse/EclipseState/EclipseState.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/Aquancon.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferConfig.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferHelpers.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferHelpers.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquiferConnection.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.cpp
src/opm/parser/eclipse/EclipseState/Aquifer/NumericalAquifer/SingleNumericalAquifer.cpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
tests/parser/AquiferTests.cpp

Downstream PRs are https://github.com/OPM/opm-grid/pull/517 and https://github.com/OPM/opm-simulators/pull/3134 and OPM/opm-upscaling#331

Using pinched grid for numerical aquifer

---

opm/parser/eclipse/EclipseState/Grid/TranCalculator.hpp
src/opm/parser/eclipse/EclipseState/Grid/TranCalculator.cpp

fixed: include <limits> in TranCalculator

---

src/opm/io/eclipse/rst/connection.cpp
src/opm/parser/eclipse/EclipseState/Schedule/RFTConfig.cpp

fixed: include <stdexcept> in RFTConfig.cpp

---

src/opm/output/eclipse/Summary.cpp

This PR makes the `find_wells()` helper function return a vector of (`const`) `Well` pointers instead of fully fledged `Well` objects. This, in turn, eliminates quite a bit of the overhead of evaluating well-based summary vectors (i.e., well, group, field, and connection level vectors).

Don't Copy Well Objects During Summary Vector Evaluation

---

examples/opmhash.cpp
examples/wellgraph.cpp
src/opm/output/eclipse/Summary.cpp

Fixes compile errors with clang.

Add missing <sstream> include.

---

python/generate-pypi-package.sh
python/setup-docker-image.sh

changed: python 3.5 is no longer support in pypi

---

opm/parser/eclipse/EclipseState/Schedule/Events.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Events.cpp
tests/parser/EventTests.cpp

Small step for opm - even smaller for mankind
Downstream: https://github.com/OPM/opm-simulators/pull/3221

Add method WellGroupEvents.at() to get individual events

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/O/OPTIONS

Eclipse 2019.1 reference manual goes to item number 319

Extend number of parameters to OPTIONS keyword.

---

opm/parser/eclipse/Deck/DeckOutput.hpp
src/opm/parser/eclipse/Deck/Deck.cpp
src/opm/parser/eclipse/Deck/DeckOutput.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
tests/parser/DeckTests.cpp

Make sure ACTIONX output is formatted as opmpack - to simplify debugging
@jalvestad : You might want to include this to ensure that the formatting from opmpack and ACTIONX restart output is identical.

Actionx output sep

---

opm/parser/eclipse/EclipseState/Schedule/Events.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

Downstream: https://github.com/OPM/opm-simulators/pull/3288

Add new well event for wells which have been touched by ACTIONX

---

tests/parser/UDQTests.cpp

Don't Increment Loop Counter Twice

---

opm/parser/eclipse/EclipseState/Runspec.hpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
tests/parser/RunspecTests.cpp

Nupcol updates

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellConnections.cpp
tests/parser/ScheduleTests.cpp

Return the number of open connections in a `ConnectionSet`

Add method ConnectionSet::num_open()

---

opm/output/data/Groups.hpp
opm/output/data/GuideRateValue.hpp
opm/output/data/Wells.hpp
tests/test_Wells.cpp

Json output is for simpliyfiung the debugging of restart.

Wells output json

---

opm/output/eclipse/AggregateGroupData.hpp
opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp

Introduce and use functions to convert group control modes to enums.

Group cmode

---

CMakeLists.txt
cmake/Modules/OpmBashCompletion.cmake
cmake/Modules/OpmFind.cmake
cmake/Modules/UseDynamicBoost.cmake

These should not interfere with packaging (famous last words...)

Further patches to the build system from Debian unstable packaging.

---

test_util/EclRegressionTest.cpp

More details in error message when comparing restart files

Update restart output from EclRegressionTest

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Add restart group to Schedule object

Add Schedule::addGroup( const RstGroup& ) overload

---

src/opm/parser/eclipse/Deck/DeckKeyword.cpp

Make sure deck output of TITLE has trailing newline

---

CMakeLists_files.cmake
opm/io/eclipse/rst/state.hpp
opm/output/eclipse/UDQDims.hpp
src/opm/io/eclipse/rst/state.cpp
src/opm/output/eclipse/UDQDims.cpp
tests/UDQ_TEST_WCONPROD_IUAD-2.DATA
tests/test_AggregateUDQData.cpp
tests/test_rst.cpp

Some early stage - quite trivial preparations for UDQ restart.

Udq rst preparations

---

opm/parser/eclipse/Parser/ParserKeyword.hpp
src/opm/parser/eclipse/Parser/Parser.cpp
src/opm/parser/eclipse/Parser/ParserKeyword.cpp

A small simplification / imrovement to get the valid sections out from a ParserKeyword.

Keyword sections

---

opm/parser/eclipse/Deck/DeckOutput.hpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/AggregateUDQData.cpp
tests/parser/ParserTests.cpp
tests/test_AggregateActionxData.cpp

Exctract some small changes from: #2518

Jostein commits

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WELLDIMS

Fix missing entry and defaults to eliminate false warning messages.

WELLDIMS Fix Up

---

src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQToken.cpp

Preparation for loading UDQ strings from restart file

Update UDQ parsing - preparation for restart load

---

src/opm/output/eclipse/AggregateUDQData.cpp
src/opm/output/eclipse/CreateUdqDims.cpp
src/opm/output/eclipse/UDQDims.cpp

Picked UDQ related stuff from: https://github.com/OPM/opm-common/pull/2518

UDQ output updates

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCON
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EHYSTR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NETWORK
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NNC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/U/UDQDIMS

Added item counter for checking and comment for E300 parameters.

AQUCON, AQUCT, EHYSTR, NETWORK, NNC and UDQDIMS Changes

---

opm/output/data/Wells.hpp
opm/parser/eclipse/EclipseState/TracerConfig.hpp
src/opm/output/eclipse/Summary.cpp
src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/EclipseState/TracerConfig.cpp
tests/parser/SummaryConfigTests.cpp
tests/parser/TracerTests.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

There is a corresponding PR for opm-simulators.
Downstream: https://github.com/OPM/opm-simulators/pull/3239

Support for tracer summary curves, WT(I/P)(R/T/C).

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQState.cpp

Preparation to load from restart file

Refactor UDQ state to use plain maps

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EDITNNC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMFSC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMOPTS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/V/VISCREF

JSON updates

---

src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp

Add COMPLUMP and WPIMULT as AXTIONX enabled keywords

---

tests/parser/integration/ParseKEYWORD.cpp

Remove minor test statement which creates complication for: #2549

Remove test check for number of items in record

---

src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCON
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUFETP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/C/COMPDAT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EQUIL
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCONINJE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCONPROD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/M/MESSAGES
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NMESSAGE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/P/PLYMAX
src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/REGDIMS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/R/RESTART
src/opm/parser/eclipse/share/keywords/keyword_list.cmake

AQUCON, AQUCT, AQUFETP, EQUIL, MESSAGES, PLYMAX, REGDIMS, and RESTART

Update Various JSON Definitions

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EDITNNC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EHYSTR
src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/EQLDIMS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GCONSUMP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GEFAC
src/opm/parser/eclipse/share/keywords/000_Eclipse100/G/GUIDERAT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NODEPROP
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCONHIST
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCONINJE
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCONINJH
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WCONPROD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WECON
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WELSPECS
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WLIFTOPT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WRFTPLT
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGAICD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGSICD
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGVALV
tests/parser/integration/ParseKEYWORD.cpp

Mostly item and comments, except for:
NODEPROP
WCONHIST

JSON Revised Definitions

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/T/TRACERS

Added item for checking, no other changes.

Update TRACERS JSON

---

opm/io/eclipse/ESmry.hpp
src/opm/io/eclipse/ESmry.cpp
tests/test_ESmry.cpp

This function will check if all time steps are available in the summary file. 
Notie that this will not be the case if RPTONLY has been used with the commercial simulator. Flow is not yet supporting this, but we might in the future.

new member function in ESmry

---

src/opm/parser/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp

Note: two-phase gas-water system is not yet enabled

fix for two phase gas-water system

---

src/opm/io/eclipse/ESmry.cpp

In particular, use `vector<>` as a buffer in place of a manually `new`-ed up `char*`.

Don't Manage Resources Manually

---

src/opm/parser/eclipse/EclipseState/InitConfig/FoamConfig.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/F/FOAMFSC
tests/parser/FoamTests.cpp

Start of foam validation refactoring. 
Actually I Think it is OK as is.

Enforce keyword requirement with "requires": []

---

src/opm/parser/eclipse/EclipseState/Schedule/Group/GuideRateModel.cpp

To allow for validation in the simulator.

Delay error condition to GuideRateModel::eval() time

---

src/opm/io/eclipse/EclFile.cpp

also fixes a harmless error where delete was used instead of delete[]

changed: use std::vector<char> instead of raw char arrays

---

src/opm/output/eclipse/AggregateGroupData.cpp

simpflifications, moving around, whites space and other trivial changes, in an attempt to understand this quite complex code.

Igrp simplification2

---

CMakeLists_files.cmake
opm/io/eclipse/ESmry.hpp
opm/io/eclipse/ESmryOutput.hpp
opm/output/eclipse/EclipseIO.hpp
opm/output/eclipse/Summary.hpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/ESmryOutput.cpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/Summary.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp

adding support for writing lodsmry
- ESMRY file is re-written for every time step
- file ESRMY optimized for fast loading of selected vectors
- This PR is dependent on PR OPM/opm-simulators#3453

Support for writing ESMRY file 

---

opm/parser/eclipse/EclipseState/Aquifer/Aquancon.hpp
opm/parser/eclipse/EclipseState/Aquifer/Aquifetp.hpp
opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/Grid/EclipseGrid.hpp
opm/parser/eclipse/EclipseState/Grid/MapAxes.hpp
opm/parser/eclipse/EclipseState/Tables/TLMixpar.hpp
opm/utility/EModel.hpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionValue.cpp
src/opm/utility/EModel.cpp
tests/test_AggregateAquiferData.cpp
tests/test_Tables.cpp

These might be slightly more controversial as they actually require some small code changes.

Some more SCA warning cleanup

---

src/opm/io/eclipse/ExtESmry.cpp
tests/test_ExtESmry.cpp

- segfault when loading more that one vector
- test ExtESmry updated, now failing without this fix

fixing bug in ExtESmry

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Trivial commits extracted from: #2608

Skiprest bug trivial

---

src/opm/output/eclipse/AggregateMSWData.cpp
tests/test_AggregateMSWData.cpp

Use SummaryState::get_well_var() with default

---

CMakeLists_files.cmake
opm/common/utility/FileSystem.hpp
src/opm/common/utility/FileSystem.cpp
src/opm/io/eclipse/ESmry.cpp
tests/test_FileSystem.cpp

the filesystem TS did not include proximate. implement
a poor man's version and use this when necessary

fix build with gcc7

---

jenkins/update-opm-tests.sh

the use of environment variables makes it less flexible.
required by https://github.com/OPM/opm-simulators/pull/3477

changed: pass more information as parameters

---

opm/io/eclipse/EGrid.hpp
src/opm/io/eclipse/EGrid.cpp

adding support in class EGrid for reading MAPAXES and MAPUNITS from egrid file

Adding support for handling MAPAXES and MAPUNITS

---

opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQActive.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.hpp
opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQInput.hpp
src/opm/output/eclipse/AggregateUDQData.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQActive.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQConfig.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQInput.cpp
tests/parser/UDQTests.cpp

Many small trivial changes as part of warming up for loading UDA state from restart file.

Uda rst trivial

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Minor fixup in output from Schedule + actionx parsing

Fix prefix with output from schedule parse in ACTIONX mode

---

opm/io/eclipse/ExtESmry.hpp
python/cxx/eclipse_io.cpp
python/opm/_common.py
python/tests/test_esmry.py

- Used for loading data from summary file ESMRY

Adding python bindings for class ExtESmry

---

cmake/Modules/UseOptimization.cmake

To keep @joakim-hove sanity intact.

changed: default to asserts enabled in release mode

---

cmake/Modules/FindMETIS.cmake

With version 2.8 DUNE will specify imported target METIS::METIS for the linker and introduces a METIS_API_VERSION to distinguish different versions. This patch introduces these to the find module used by OPM.

Fix FindMETIS for DUNE 2.8.

---

src/opm/output/eclipse/Summary.cpp

Another actionx special casing.

Intercept month keywords earlier in Summary creation

---

src/opm/io/eclipse/EclOutput.cpp

- significant improvements on performance
- writing blocks of data from disk, rather that one by one element

Update of class EclOutput

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/output/eclipse/AggregateUDQData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp

I think this is correct - but some verification awaits

 Ensure that UDA is only active for one phase in restart file 

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

Part of ACTIONX testing (and fixing ...) effort.

Schedule rename runtime

---

opm/parser/eclipse/EclipseState/Schedule/Group/GPMaint.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/GPMaint.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
tests/parser/GroupTests.cpp

Downstream: https://github.com/OPM/opm-simulators/pull/3500

Gpmaint state

---

opm/parser/eclipse/EclipseState/Schedule/Group/Group.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Group/Group.cpp
tests/parser/GroupTests.cpp

Small preparation for GPMAINT
Dwonstream: https://github.com/OPM/opm-simulators/pull/3504

Use Group class to query for  controls

---

opm/common/utility/String.hpp
opm/common/utility/TimeService.hpp
opm/io/eclipse/rst/header.hpp
opm/output/eclipse/WriteRestartHelpers.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Actions.hpp
src/opm/common/utility/TimeService.cpp
src/opm/io/eclipse/rst/header.cpp
src/opm/output/eclipse/CreateActionRSTDims.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Actions.cpp
tests/parser/ACTIONX.cpp

More small commits for rst actionx

Rst actionx commits

---

CMakeLists_files.cmake
opm/output/eclipse/AggregateActionxData.hpp
opm/output/eclipse/VectorItems/action.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Condition.hpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/output/eclipse/CreateActionRSTDims.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Condition.cpp

Use named constants for the actionx - condition related vectors when creating restart files. Also some small updates/simplifications here and there in the restart output. The named constants will be reused when loading the restart information back in.

Action rst const

---

src/opm/parser/eclipse/Parser/Parser.cpp
tests/parser/UDQTests.cpp

Special case parsing for UDQ keywords.

Special case treatment of trailing slash for UDQ keywords

---

opm/parser/eclipse/Deck/DeckOutput.hpp
src/opm/parser/eclipse/Deck/DeckKeyword.cpp
src/opm/parser/eclipse/Deck/DeckOutput.cpp
tests/parser/DeckTests.cpp

Small changes towards an application to create a restart deck.

Ensure that normal keywords are not split on output

---

opm/common/utility/parameters/ParameterGroup_impl.hpp

Detected by linitian run on Debian package for opm-upscaling.

Fixed spelling of assignment,

---

tests/test_SummaryNode.cpp

Also use nullopt instead of blank string for fip_region member.

fixed: add missing field initializers

---

opm/io/eclipse/rst/action.hpp
opm/io/eclipse/rst/state.hpp
opm/output/eclipse/VectorItems/action.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/Actdims.hpp
src/opm/io/eclipse/rst/state.cpp
src/opm/output/eclipse/AggregateActionxData.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/Actdims.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
tests/parser/ScheduleRestartTests.cpp

With this PR we will load the Keywords in the ACTIONX blocks and have them ready for eval.

Rst actionx keywords

---

src/opm/io/eclipse/ERsm.cpp

Compare with startdate and not first simulation date

---

src/opm/io/eclipse/ERsm.cpp

More fiddling with RSM testing ;-(

Special case comparison with zero

---

tests/WorkArea.cpp
tests/parser/EclipseGridTests.cpp
tests/test_AggregateActionxData.cpp
tests/test_AggregateUDQData.cpp
tests/test_ERft.cpp
tests/test_ERst.cpp
tests/test_ESmry.cpp
tests/test_EclIO.cpp
tests/test_EclRegressionTest.cpp
tests/test_ExtESmry.cpp
tests/test_restartwellinfo.cpp

Ensure that tests in opm-common can run with readonly tests/ directory. I had some Heisenbugs

Readonly testing

---

opm/parser/eclipse/EclipseState/Aquifer/AquiferCT.hpp
src/opm/parser/eclipse/EclipseState/Aquifer/AquiferCT.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUCT
tests/test_AggregateAquiferData.cpp

Item 13 may be useful when aquifers are combined with CO2STORE

add item 13 in AQUCT

---

opm/parser/eclipse/Deck/Deck.hpp
src/opm/parser/eclipse/Deck/Deck.cpp
src/opm/parser/eclipse/Parser/Parser.cpp
tests/parser/DeckTests.cpp

Preparations for create a restart deck utlity

Deck tree commits

---

opm/common/utility/TimeService.hpp
opm/parser/eclipse/EclipseState/Runspec.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.hpp
src/opm/common/utility/TimeService.cpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp
tests/parser/ScheduleTests.cpp

Mange simulation start from RunSpec class

Runspec sim start

---

opm/parser/eclipse/Deck/Deck.hpp
opm/parser/eclipse/Deck/DeckKeyword.hpp
src/opm/parser/eclipse/Deck/Deck.cpp
src/opm/parser/eclipse/Deck/DeckKeyword.cpp

Deck tree commits ii

---

src/opm/parser/eclipse/Parser/Parser.cpp

Use fs:proximate() due to missing fs::relative()

---

opm/io/eclipse/rst/action.hpp
opm/io/eclipse/rst/state.hpp
opm/parser/eclipse/EclipseState/Schedule/Action/State.hpp
src/opm/io/eclipse/rst/action.cpp
src/opm/io/eclipse/rst/state.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/State.cpp
tests/parser/ScheduleRestartTests.cpp

Load the number of times an action has run, and the time for the last eval - from the restart file.

Load action state

---

opm/common/utility/String.hpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQDefine.cpp
src/opm/parser/eclipse/EclipseState/Schedule/UDQ/UDQEnums.cpp
tests/parser/StringTests.cpp

Avoid exceptions in happy path when parsing UDQ floatign point numbers. To simplify debugging

Use strtod

---

examples/opmhash.cpp

Utility to enable deck comparisons

Add multi deck comparison to opmhash

---

jenkins/build-opm-module.sh

fixed: sneaky ; was supposed to be :

---

src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp

Add WTEST to allowed ACTIONX Keywords

Add WTEST to Allowed ACTIONX Keywords

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.cpp

Solves issue https://github.com/OPM/opm-simulators/issues/3555

add method that open all completions

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WECON

https://github.com/OPM/opm-simulators/issues/3555

fix unit item 5 and item 6 WECON

---

src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp

Add network member to ScheduleState::operator==()

---

src/opm/parser/eclipse/share/keywords/000_Eclipse100/N/NETBALAN
tests/parser/ScheduleTests.cpp

Netbalan commits

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.cpp
tests/MessageBuffer.cpp
tests/parser/WTEST.cpp
tests/test_data_GuideRateValue.cpp

Preparation for WTEST restart support
Downstream: https://github.com/OPM/opm-simulators/pull/3566

1: Wtest state serialize

---

opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellTestState.cpp
tests/test_AggregateWellData.cpp

Load WTEST state from restart file
Downstream: https://github.com/OPM/opm-simulators/pull/3594

Wtest state rst load

---

examples/rst_deck.cpp
opm/parser/eclipse/Deck/FileDeck.hpp
src/opm/parser/eclipse/Deck/FileDeck.cpp
tests/parser/ScheduleRestartTests.cpp

Fix a bug in rst_deck + refactor and add test.

Move some code from rst_deck application to FileDeck class

---

opm/parser/eclipse/EclipseState/Schedule/Network/Balance.hpp

Use struct consistently for Tuning.

---

opm/parser/eclipse/Deck/UDAValue.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/parser/eclipse/Deck/UDAValue.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellInjectionProperties.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WTMULT
tests/parser/ScheduleTests.cpp
tests/parser/UDQTests.cpp

Basic support for WTMULT

---

src/opm/io/eclipse/rst/header.cpp
src/opm/io/eclipse/rst/well.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/share/keywords/000_Eclipse100/L/LIFTOPT

Fix some wrong item lookups when loading LIFTOPT from rst file

Gaslift rst fixup

---

opm/parser/eclipse/Deck/Deck.hpp
opm/parser/eclipse/Deck/DeckSection.hpp
src/opm/parser/eclipse/Deck/Deck.cpp
src/opm/parser/eclipse/Deck/DeckSection.cpp

Rename DeckView -> DeckViewInternal
This is a temporary step in order make the name DeckView available for a new class. The DeckViewInternal will be removed.

Rename DeckView -> DeckViewInternal

---

src/opm/output/eclipse/Summary.cpp

Change sign of gas lift rate calculated from IGLR and ALQ value

---

opm/parser/eclipse/EclipseState/EclipseState.hpp
opm/parser/eclipse/EclipseState/MICPpara.hpp
src/opm/parser/eclipse/EclipseState/EclipseState.cpp
src/opm/parser/eclipse/EclipseState/MICPpara.cpp

Minor refactor to get details out from core EclipseState

Refactor construction of Microbial growth constructor

---

opm/parser/eclipse/Deck/Deck.hpp
src/opm/parser/eclipse/Deck/Deck.cpp

The previous use of pointer semantics was only to mimic optional - use the real deal.

Use std::optional< > for Deck unitsystem

---

jenkins/setup-opm-tests.sh
jenkins/update-opm-tests.sh

this to allow for update_data from opm-tests

added: tell update_data where to start branch from

---

CMakeLists.txt

Remove remnants from the large Schedule refactor.

Remove stale compile definition SCHEDULE_DEBUG

---

opm/parser/eclipse/EclipseState/Schedule/Action/SimulatorUpdate.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
tests/parser/ACTIONX.cpp

Enable use of MULTXYZ keywords as ACTIONX keywords
Downstream: https://github.com/OPM/opm-simulators/pull/3686

Action multxyz

---

opm/parser/eclipse/Deck/Deck.hpp
python/cxx/deck.cpp
src/opm/parser/eclipse/Deck/Deck.cpp
src/opm/parser/eclipse/Deck/DeckSection.cpp
src/opm/parser/eclipse/EclipseState/Grid/EclipseGrid.cpp
src/opm/parser/eclipse/EclipseState/checkDeck.cpp
src/opm/parser/eclipse/Parser/Parser.cpp
tests/parser/DeckTests.cpp
tests/parser/integration/parse_write.cpp

Replace `Deck::getKeyword(std::size_t)` with `Deck::operator[](std::size:_t)` - extracted commit from: https://github.com/OPM/opm-common/pull/2850

Replace std size

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Add kw compsegs

---

opm/parser/eclipse/EclipseState/TracerConfig.hpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/parser/eclipse/EclipseState/TracerConfig.cpp

Add a keyword ZTRACER before the tracer solution data in restart files.

Add ztracer keyword to restart file

---

opm/parser/eclipse/EclipseState/Runspec.hpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/parser/eclipse/EclipseState/Runspec.cpp

Magic numbers provided by @tskille

Update INTEHEAD vector to take tracer data into account

---

opm/parser/eclipse/EclipseState/Schedule/Network/Balance.hpp
opm/parser/eclipse/Units/UnitSystem.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Network/Balance.cpp
src/opm/parser/eclipse/Units/UnitSystem.cpp

We might have more of these ... :fearful:

Make sure units are correct for default initialized NETBALAN

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.hpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp
tests/parser/ScheduleTests.cpp

WIth this the keywords of the Schedule section are dumped as a deck.

Implement schedule dump to deck functionality

---

opm/parser/eclipse/Deck/DeckRecord.hpp
opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.hpp
src/opm/parser/eclipse/Deck/DeckRecord.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp
tests/parser/ScheduleTests.cpp

Schedule deck start

---

opm/parser/eclipse/EclipseState/TracerConfig.hpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/parser/eclipse/EclipseState/TracerConfig.cpp

These tracer changes were lost somewhere.
Will be new tracer vectors in the norne reperf test

Tracer name fixup

---

opm/io/eclipse/rst/header.hpp
opm/io/eclipse/rst/state.hpp
opm/io/eclipse/rst/well.hpp
opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp
src/opm/io/eclipse/rst/header.cpp
src/opm/io/eclipse/rst/state.cpp
src/opm/io/eclipse/rst/well.cpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp
tests/test_AggregateWellData.cpp
tests/test_InteHEAD.cpp
tests/test_rst.cpp

Load tracer rates and tracer cumulatives from restart file.
test update: OPM/opm-tests#689

Rst load tracer rate

---

src/opm/output/eclipse/Summary.cpp

Needed for https://github.com/OPM/opm-simulators/pull/2584

add Field vectors to required list

---

opm/io/eclipse/ESmry.hpp
opm/io/eclipse/ExtESmry.hpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/ESmry_write_rsm.cpp
src/opm/io/eclipse/ExtESmry.cpp
test_util/EclRegressionTest.cpp
tests/test_ESmry.cpp

* add function for returning root name
* add function for returning I/O duration (opening and loading)
*  rename member function LoadData() to loadData()

updates of ESmry and ExtESmry

---

src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp

Adding COMPSEGS, WELSEGS and WSEGVALV to ACTIONX keyword list to test WSEGVALV usage.

Add COMPSEGS, WELSEGS and WSEGVALV to ACTIONX

---

src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

COMPSEGS keyword has a special first record; that was not taken into account when prefetching the required grid indices.

Prefetch compsegs

---

opm/io/eclipse/rst/segment.hpp
opm/io/eclipse/rst/udq.hpp

added #include <algorithm>, as it did not compile with GNU compiler version 11.1.

added #include <algorithm>

---

src/opm/parser/eclipse/EclipseState/Schedule/ScheduleState.cpp

Add missing ACTION comparison in ScheduleState

---

opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp
src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp
src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp

Refactor Schedule handlerContext usage

---

src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp

Update ActionX.cpp for Typo

---

test_util/arraylist.cpp

@tskille please confirm that copyright header is correct.

Add missing include, and copyright header.

---

src/opm/parser/eclipse/EclipseState/Schedule/Action/ActionX.cpp

The WTMULT keyword has recently been implemented and this PR adds the keyword to the list of ACTIONX supported keywords.

Update ActionX.cpp with WTMULT

---

src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp

Fix for: https://github.com/OPM/opm-common/issues/2891#issuecomment-996415529
Unfortunately the test case still does not run - but now the error message is: 
```
flow: /home/hove/work/OPM/opm-simulators/opm/simulators/wells/BlackoilWellModelGeneric.cpp:701: std::vector<std::reference_wrapper<Opm::ParallelWellInfo> > Opm::BlackoilWellModelGeneric::createLocalParallelWellInfo(const std::vector<Opm::Well>&): Assertion `pwell != parallel_well_info_.end() && *pwell == wellPair' failed.
[ws:572228] *** Process received signal ***
[ws:572228] Signal: Aborted (6)
[ws:572228] Signal code:  (-6)
```
i.e. something quite different.

Handle ACTIONX delayed WELSPECS for keywords WELSEGS and COMPSEGS

---

src/opm/input/eclipse/share/keywords/900_OPM/S/SALTPVD

Note this is an OPM keyword  not present in the commercial simulator.
This PR is part of a few PRs to be  submitted for salt precipitation feature.

Corrected dimensions of SALTPVD

---

CMakeLists_files.cmake
GenerateKeywords.cmake
opm/common/utility/shmatch.hpp
src/opm/common/utility/shmatch.cpp
src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/input/eclipse/Parser/ParseContext.cpp
src/opm/input/eclipse/Schedule/Action/ASTNode.cpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQASTNode.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQSet.cpp
src/opm/input/eclipse/Schedule/Well/WListManager.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/input/eclipse/Schedule/Well/WellMatcher.cpp
src/opm/input/eclipse/Schedule/Well/injection.cpp
src/opm/io/eclipse/ESmry.cpp
src/opm/io/eclipse/ExtESmry.cpp
tests/parser/StringTests.cpp

Needed a break from manual writing

Use std::regex to implement fnmatch()

---

src/opm/common/utility/shmatch.cpp

Remove stale #include <fnamatch.h>

---

README.md

Make it clear what is in the repository. Might help people finding it via search engines.

Slightly improve readme

---

CMakeLists_files.cmake
msim/src/msim.cpp
opm/input/eclipse/Schedule/Action/Actions.hpp
opm/input/eclipse/Schedule/Action/PyAction.hpp
opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Python/PyRunModule.cpp
src/opm/input/eclipse/Python/PyRunModule.hpp
src/opm/input/eclipse/Schedule/Action/Actions.cpp
src/opm/input/eclipse/Schedule/Action/PyAction.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
tests/msim/MSIM_PYACTION_ACTIONX.DATA
tests/msim/action1.py
tests/msim/action2.py
tests/msim/action3.py
tests/msim/test_msim_ACTIONX.cpp
tests/parser/EmbeddedPython.cpp
tests/wclose.py

Continuation of: https://github.com/OPM/opm-common/pull/2932
Downstream: 
https://github.com/OPM/opm-simulators/pull/3787
https://github.com/OPM/opm-tests/pull/714

Pyaction use actionx

---

python/setup.py.in

@alfbr : This is work in progress - but you could give it a spin.

Make sure env variable CC is set also if no ccache

---

opm/input/eclipse/Deck/DeckItem.hpp
python/cxx/deck_keyword.cpp
python/tests/test_parse.py

Export RawString as std::string to Python

---

python/generate-pypi-package.sh
python/setup-docker-image.sh

Closes https://github.com/OPM/opm-common/issues/2969

add python 3.10 to pypi builds

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp

We define a valid cell geometry as one in which all components of all eight corner vertices of a cell have finite coordinate values (absolute value less than `1.0E+20`) and at least one pair of pillar vertices are separated by a positive distance.

Add Means of Detecting Valid Cell Geometries

---

cmake/Modules/Finddune-istl.cmake
cmake/Modules/OpmInit.cmake
cmake/Modules/OpmLibMain.cmake

[backport] Use dune buildsystem defaults

---

jenkins/build-opm-module.sh

we need to be able to specify absolute refs to use for the repos
rather than a pull request number.

added: ability to use jenkins build scripts for release test building

---

src/opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp
src/opm/input/eclipse/Schedule/Well/WellProductionProperties.cpp

Updating the BHP target appears to have been a copy-paste error.

Update THP Target in Case of THP Control

---

test_util/arraylist.cpp
tests/test_ERst.cpp

Spelling fixes (valied -> valid).

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/C/COMPLUMP

[backport] Added default values for I, J, K1 and K2

---

src/opm/input/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp

Fix warnings introduced in #2917

fix warning due to  missing else in satfuncs

---

src/opm/input/eclipse/Parser/Parser.cpp
tests/parser/FieldPropsTests.cpp
tests/parser/ParseDATAWithDefault.cpp
tests/parser/SimulationConfigTest.cpp
tests/parser/test_ReportConfig.cpp

This will hopefully aid the user in resolving the underlying issue.

Attribute Missing Terminator to Keyword/File/Line

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Well/Well.cpp

Needed for restart file compatibility.

Provide Accessor for WGRUPCON's Raw Phase Value

---

opm/input/eclipse/EclipseState/Tables/SimpleTable.hpp
src/opm/input/eclipse/EclipseState/Tables/SimpleTable.cpp
src/opm/input/eclipse/EclipseState/Tables/TableManager.cpp

and reduce some code duplication.
Before:
```
Error: 
An error occurred while creating the reservoir properties
Internal error: Number of columns in the data file isinconsistent with the ones specified
```
After:
```
Error: Problem with keyword SWOF
In E100.DATA line 114.
Internal error: Number of columns in the data file 7 is inconsistent with the specified item size 4
```

Improve error logging

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/W/WCONINJE
src/opm/input/eclipse/share/keywords/000_Eclipse100/W/WCONINJH

See issue https://github.com/OPM/opm-simulators/issues/3850

implement item 10 WCONINJE

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/D/DIFF
src/opm/input/eclipse/share/keywords/000_Eclipse100/H/HAxxxxxx
src/opm/input/eclipse/share/keywords/000_Eclipse100/H/HMMULTxx
src/opm/input/eclipse/share/keywords/000_Eclipse100/H/HMxxxxxx
src/opm/input/eclipse/share/keywords/000_Eclipse100/K/KRNUM

This fixes issue #3053 for me.

Fix typo in KRNUM json file

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp

This is needed to initialize ALuGrid from Deck. This PR will be necessary before continuing  PR OPM/opm-simulators#3930.

assert if Alugrid can be initialized from Deck: check format and geometry

---

src/opm/input/eclipse/EclipseState/Tables/Tables.cpp

Use case is table copy for PVTW.

Extract Helper for Single Table Record Construction

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SOLWNUM

This PR fixes a typo in the "sections" property name

Fix eclipse SOLWNUM json file

---

examples/msim.cpp
msim/include/opm/msim/msim.hpp
opm/input/eclipse/Deck/DeckSection.hpp
opm/input/eclipse/Schedule/ScheduleDeck.hpp
src/opm/input/eclipse/EclipseState/EclipseConfig.cpp
src/opm/input/eclipse/EclipseState/Grid/FaultCollection.cpp
src/opm/input/eclipse/EclipseState/Grid/FieldPropsManager.cpp
src/opm/input/eclipse/EclipseState/Grid/TransMult.cpp
src/opm/input/eclipse/EclipseState/IOConfig/IOConfig.cpp
src/opm/input/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
src/opm/input/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp
src/opm/input/eclipse/EclipseState/checkDeck.cpp
src/opm/input/eclipse/Parser/ParserRecord.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/ScheduleDeck.cpp
tests/msim/test_msim.cpp
tests/msim/test_msim_ACTIONX.cpp
tests/msim/test_msim_EXIT.cpp
tests/parser/SectionTests.cpp
tests/parser/SimulationConfigTest.cpp

and deal with the consequences.
Before:
```
touch Deck.hpp && ninja
[1/705] Building CXX object ...
```
After:
```
touch Deck.hpp && ninja
[1/638] Building CXX object ...
```

changed: remove include of Deck.hpp in header

---

CMakeLists.txt
cmake/Modules/FindValgrind.cmake

- proper case in valgrind findrule
- remove a faulty brace

Small buildsystem fixes

---

src/opm/input/eclipse/Schedule/Schedule.cpp

Without this, I have a field case that fails.
Behaviour may be wrong in corner cases that have the action triggering at the same time as WPIMULT keywords are present in the deck, but I thing it is probably not worth it to address.

Enable using WPIMULT in ACTIONX.

---

src/opm/input/eclipse/EclipseState/Aquifer/Aquancon.cpp

Also add tags to the Aquancon inactive connection warnings. This allows their appearance to be limited to some count (typically 10).

AQUANCON: Add a summarizing warning stating the number of inactive connection ignored

---

opm/input/eclipse/Deck/DeckItem.hpp
opm/input/eclipse/Schedule/Schedule.hpp

Up/downstream of https://github.com/OPM/opm-simulators/pull/4052

adjust for vector serializer API change

---

opm/input/eclipse/Schedule/Action/ActionResult.hpp

Up/downstream of https://github.com/OPM/opm-simulators/pull/4053
Sits on top of https://github.com/OPM/opm-common/pull/3116

adjust for set serializer API change

---

opm/input/eclipse/EclipseState/Grid/TransMult.hpp
opm/input/eclipse/Schedule/Action/State.hpp
opm/input/eclipse/Schedule/RFTConfig.hpp
opm/input/eclipse/Schedule/RPTConfig.hpp
opm/input/eclipse/Schedule/RSTConfig.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQState.hpp
opm/input/eclipse/Schedule/Well/NameOrder.hpp
opm/input/eclipse/Schedule/Well/WListManager.hpp

Up/downstream of https://github.com/OPM/opm-simulators/pull/4055
Sits on top of https://github.com/OPM/opm-common/pull/3116

adjust for map serializer API change

---

opm/output/data/Wells.hpp

Sits on top of https://github.com/OPM/opm-common/pull/3128

data::Connection: add serializer support

---

opm/output/data/Groups.hpp

Sits on top of https://github.com/OPM/opm-common/pull/3121

data::GroupGuideRates: add serializer support

---

opm/output/data/Wells.hpp

Sits on top of https://github.com/OPM/opm-common/pull/3130
Sits on top of https://github.com/OPM/opm-common/pull/3129

data::Segment: add serializer support

---

opm/output/data/Groups.hpp

Sits on top of https://github.com/OPM/opm-common/pull/3122

data::GroupData: add serializer support

---

opm/output/data/Wells.hpp

Sits on top of https://github.com/OPM/opm-common/pull/3133

data::Wells: add serializer support

---

opm/output/data/Aquifer.hpp

Sits on top of https://github.com/OPM/opm-common/pull/3135
Sits on top of https://github.com/OPM/opm-common/pull/3136
Sits on top of https://github.com/OPM/opm-common/pull/3137

data::AquiferData: add serializer support

---

opm/output/data/Wells.hpp

Always sad to see friends go, but these friends are now imaginary.

drop unused friend declarations

---

opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.hpp
opm/input/eclipse/EclipseState/Grid/TranCalculator.hpp
src/opm/input/eclipse/EclipseState/Grid/FieldPropsManager.cpp

and some accessors to enable downstream to use it

added: support serialization for TranCalculator

---

CMakeLists_files.cmake
opm/common/utility/Serializer.hpp
tests/SimplePacker.hpp
tests/test_Serialization.cpp

add tests using a simple memcpy based packer
Sits on top of https://github.com/OPM/opm-common/pull/3148

Import serializer code from opm-simulators

---

CMakeLists_files.cmake
opm/input/eclipse/EclipseState/Grid/FaceDir.hpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/utility/CopyablePtr.hpp
src/opm/input/eclipse/EclipseState/Grid/FaceDir.cpp
tests/test_CopyablePtr.cpp

See https://github.com/OPM/opm-simulators/pull/4048 for more information

Add support for directional relative permeabilties

---

opm/input/eclipse/Schedule/RFTConfig.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/RFTConfig.cpp
tests/parser/RFTConfigTests.cpp

In preparation of adding RFT file output support for segment data.

Internalise WRFTPLT Segment Option

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/N/NETBALAN

Add item numbers for NETBALAN.

---

opm/input/eclipse/Schedule/MSW/Segment.hpp
opm/input/eclipse/Schedule/MSW/WellSegments.hpp
src/opm/input/eclipse/Schedule/MSW/Segment.cpp
src/opm/input/eclipse/Schedule/MSW/WellSegments.cpp
tests/parser/MultisegmentWellTests.cpp

These are not used in the simulation, but needed/useful for the `SEG` option of the `WRFTPLT` keyword.

Add XY Coordinates to Segment's Node

---

opm/input/eclipse/EclipseState/Runspec.hpp
src/opm/input/eclipse/EclipseState/Runspec.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/E/EHYSTR

Some additional input from kw `EHYSTR` to support Killough's approach for hysteresis in relperm and cap-pressure.

Support for capillary pressure hysteresis.

---

python/opm/tools/time_vector.py

Minor update so time stamp adheres to HH:MM:SS[.SSSS]  (+ some formatting improvements)

Fix time stamp output from time_vector.py so it is Ecl compatible

---

opm/input/eclipse/EclipseState/SimulationConfig/BCConfig.hpp
src/opm/input/eclipse/EclipseState/SimulationConfig/BCConfig.cpp
src/opm/input/eclipse/share/keywords/900_OPM/B/BC
tests/parser/SimulationConfigTest.cpp

change order of direction and type in BC and support default ijk

---

cmake/Templates/style.css
docs/man1/arraylist.1
docs/man1/compareECL.1
docs/man1/convertECL.1
docs/man1/opmhash.1
docs/man1/opmpack.1
docs/man1/rst_deck.1
docs/man1/summary.1
test_util/EclRegressionTest.cpp
test_util/EclRegressionTest.hpp
test_util/arraylist.cpp
test_util/compareECL.cpp
test_util/convertECL.cpp
tests/test_EclRegressionTest.cpp

The consistent usage of "spesific" (which i think is wrong) makes me a bit uneasy. Fixed it to specific anyway. Please double check.
Also update and fixed the manpages.

Spelling fixes and manpage updates from Debian packages

---

test_util/convertECL.cpp

option -g will output a grdecl file. Input file should be formatted or unformatted ECL files. A option -o can be used to specify output file name. Option -o only valid together with -g option.

Update convertECL to support conversion to grdecl files

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/W/WPOLYMER

it does not look like it is needed.

removing SPECIAL from WPOLYMER definition

---

opm/input/eclipse/Schedule/MSW/WellSegments.hpp
src/opm/input/eclipse/Schedule/MSW/WellSegments.cpp
src/opm/output/eclipse/WriteRFT.cpp
tests/test_RFT.cpp

We're missing the following quantities
* Flow velocities (`SEGxVEL`)
* Holdup fractions (`SEGxHF`)
* Phase viscosity (`SEGxVIS`)
These require additional dynamic values from the simulator and will be introduced in upcoming work.

Enable SEG Type RFT File Output

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp
tests/parser/ScheduleTests.cpp

store temperature for all wells not just injectors

---

src/opm/output/eclipse/WriteRFT.cpp
tests/test_RFT.cpp

This PR adds support for outputting the flow velocity, the holdup fraction, and the phase viscosity to the RFT file arrays
* SEGxVEL
* SEGxHF
* SEGxVIS
Values provided directly by simulator so we only need to convert to output units.

Finish Outputting Per Segment Dynamic State to RFT File

---

CMakeLists.txt
CMakeLists_files.cmake

Some regressions accumlated over the years. Kinda shows that there are no users using these options...

Fix build with ENABLE_ECL_INPUT=0

---

opm/input/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
python/cxx/eclipse_config.cpp
src/opm/input/eclipse/EclipseState/Runspec.cpp
src/opm/input/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
src/opm/input/eclipse/share/keywords/900_OPM/D/DISGASW
src/opm/input/eclipse/share/keywords/keyword_list.cmake
tests/parser/RunspecTests.cpp

Support combination of GAS + WATER with CO2STORE. Allow for Gas to dissolve into water enabled by GASINWAT.

Support CO2STORE with GAS + WATER

---

src/opm/input/eclipse/EclipseState/EclipseState.cpp

Improve Error Message for MULTFLT see [#3062](/OPM/opm-common/pull/3062#issuecomment-1185473384)

Improve Error Message for MULTFLT

---

python/setup-docker-image.sh

pypi: add dune-common dependency

---

opm/material/fluidmatrixinteractions/EclEpsTwoPhaseLawParams.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp

No usage of EclipseState in these classes.

Remove unused includes

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
src/opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp

And move some logging to OpmLog instead of cerr.

Co2BrinePvt: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/densead/EvaluationFormat.hpp
tests/test_EvaluationFormat.cpp

added: fmt formatter for Evaluation

---

CMakeLists.txt
CMakeLists_files.cmake

changed: put dune-enabled tests in separate list

---

opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp

remove unused ctor and explicit comparison operator

BrineCo2Pvt: some cleanups

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp
src/opm/material/fluidsystems/blackoilpvt/Co2GasPvt.cpp

And move some logging to OpmLog instead of cerr.

Co2GasPvt: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityOilPvt.hpp
src/opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityOilPvt.cpp

 ConstantCompressibilityOilPvt: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/DeadOilPvt.hpp
src/opm/material/fluidsystems/blackoilpvt/DeadOilPvt.cpp

DeadOilPvt: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/DryHumidGasPvt.hpp
src/opm/material/fluidsystems/blackoilpvt/DryHumidGasPvt.cpp

DryHumidGasPvt: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/SolventPvt.hpp
src/opm/material/fluidsystems/blackoilpvt/SolventPvt.cpp

And replace assert on user-provided data with an exception.

SolventPvt: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/WaterPvtThermal.hpp
src/opm/material/fluidsystems/blackoilpvt/WaterPvtThermal.cpp

And replace assert on user-provided data with exceptions.

WaterPvtThermal: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/WetGasPvt.hpp
src/opm/material/fluidsystems/blackoilpvt/WetGasPvt.cpp

And replace asserts on user-provided data with exceptions.

WetGasPvt: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/WetHumidGasPvt.hpp
src/opm/material/fluidsystems/blackoilpvt/WetHumidGasPvt.cpp
tests/test_co2brinepvt.cpp
tests/test_eclblackoilfluidsystem.cpp
tests/test_eclblackoilpvt.cpp
tests/test_fluidsystems.cpp

And replace asserts on user-provided data with exceptions.
Also add a missing class member initialization.

 WetHumidGasPvt: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/BlackOilFluidSystem.hpp
src/opm/material/fluidsystems/BlackOilFluidSystem.cpp
tests/test_fluidsystems.cpp

And replace assert on user-provided data with an exception.

BlackOilFluidSystem: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.hpp
src/opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.cpp

GasPvtMultiplexer: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/OilPvtMultiplexer.hpp
src/opm/material/fluidsystems/blackoilpvt/OilPvtMultiplexer.cpp

OilPvtMultiplexer: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
opm/material/fluidsystems/blackoilpvt/WaterPvtMultiplexer.hpp
src/opm/material/fluidsystems/blackoilpvt/WaterPvtMultiplexer.cpp

Sits on top of https://github.com/OPM/opm-common/pull/3261

WaterPvtMultiplexer: encapsulate EclipseState w/ friends

---

CMakeLists_files.cmake
bin/genEvalSpecializations.py
opm-common-prereqs.cmake
opm/common/utility/Demangle.hpp
opm/material/checkFluidSystem.hpp
opm/material/densead/Evaluation.hpp
opm/material/eos/PengRobinson.hpp
opm/material/fluidmatrixinteractions/ThreePhaseParkerVanGenuchtenParams.hpp
opm/material/fluidsystems/BaseFluidSystem.hpp
src/opm/common/utility/Demangle.cpp
tests/checkComponent.hpp
tests/test_2dtables.cpp
tests/test_blackoilfluidstate.cpp
tests/test_co2brine_ptflash.cpp
tests/test_co2brinepvt.cpp
tests/test_components.cpp
tests/test_densead.cpp
tests/test_eclblackoilfluidsystem.cpp
tests/test_eclblackoilpvt.cpp
tests/test_eclmateriallawmanager.cpp
tests/test_fluidmatrixinteractions.cpp
tests/test_fluidsystems.cpp
tests/test_immiscibleflash.cpp
tests/test_ncpflash.cpp
tests/test_pengrobinson.cpp
tests/test_spline.cpp
tests/test_tabulation.cpp
tests/test_threecomponents_ptflash.cpp

In particular this should fix build again. Can you test @bska or are you already on vacation?

Minimize dune dependencies

---

CMakeLists_files.cmake
bin/genEvalSpecializations.py
opm/material/densead/DynamicEvaluation.hpp
opm/material/densead/Evaluation.hpp
opm/material/densead/Evaluation1.hpp
opm/material/densead/Evaluation10.hpp
opm/material/densead/Evaluation11.hpp
opm/material/densead/Evaluation12.hpp
opm/material/densead/Evaluation2.hpp
opm/material/densead/Evaluation3.hpp
opm/material/densead/Evaluation4.hpp
opm/material/densead/Evaluation5.hpp
opm/material/densead/Evaluation6.hpp
opm/material/densead/Evaluation7.hpp
opm/material/densead/Evaluation8.hpp
opm/material/densead/Evaluation9.hpp
src/opm/material/densead/Evaluation.cpp

- header scrub
- circular include mess
- move ostream support to compile unit

Cleanup in evaluations

---

CMakeLists_files.cmake
opm/input/eclipse/EclipseState/InitConfig/FoamConfig.hpp
opm/input/eclipse/EclipseState/Phase.hpp
opm/input/eclipse/EclipseState/Runspec.hpp
opm/input/eclipse/EclipseState/TracerConfig.hpp
opm/input/eclipse/Schedule/Group/Group.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
opm/input/eclipse/Schedule/ScheduleTypes.hpp
opm/input/eclipse/Schedule/UDQ/UDQActive.hpp
opm/input/eclipse/Schedule/Well/Well.hpp
opm/io/eclipse/rst/state.hpp
opm/io/eclipse/rst/udq.hpp
src/opm/input/eclipse/EclipseState/Phase.cpp
src/opm/input/eclipse/EclipseState/TracerConfig.cpp
src/opm/input/eclipse/Schedule/ArrayDimChecker.cpp
src/opm/input/eclipse/Schedule/Group/GConSale.cpp
src/opm/input/eclipse/Schedule/Group/GConSump.cpp
src/opm/input/eclipse/Schedule/Group/GuideRate.cpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/ScheduleDeck.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/input/eclipse/Schedule/Well/injection.hpp
src/opm/material/fluidmatrixinteractions/EclEpsScalingPoints.cpp
src/opm/output/eclipse/AggregateNetworkData.cpp
src/opm/output/eclipse/CreateLogiHead.cpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/output/eclipse/Tables.cpp

- split out Phase enum
- remove unnecessary includes

Some Runspec improvements

---

examples/make_ext_smry.cpp

If opening smspec fails, the program will now print a warning and continue with next summary file.

update of make_ext_smry program

---

opm/input/eclipse/Schedule/Action/ActionContext.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
src/opm/input/eclipse/Schedule/Action/ASTNode.cpp
src/opm/output/eclipse/AggregateWListData.cpp
tests/parser/ScheduleRestartTests.cpp
tests/test_AggregateActionxData.cpp

reduce hotness of WListManager.hpp by 84% (146 files, 27 files instead of 173)

ScheduleState.hpp: forward WListManager

---

opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
opm/output/eclipse/AggregateNetworkData.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp
src/opm/output/eclipse/AggregateGroupData.cpp
src/opm/output/eclipse/CreateDoubHead.cpp
src/opm/output/eclipse/CreateInteHead.cpp
tests/test_Serialization.cpp

reduce hotness of ExtNetwork.hpp by 89% (147 files, 18 files instead of 165)

ScheduleState.hpp: forward Network::ExtNetwork

---

opm/input/eclipse/Schedule/ScheduleState.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp
src/opm/output/eclipse/CreateInteHead.cpp
tests/test_Serialization.cpp

Reduce hotness of Balance.hpp by 93% (153 files, 12 files instead of 165)

ScheduleState.hpp: forward Network::Balance

---

msim/src/msim.cpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp
src/opm/output/eclipse/CreateActionRSTDims.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/output/eclipse/Summary.cpp
tests/parser/EmbeddedPython.cpp
tests/parser/ScheduleRestartTests.cpp
tests/test_AggregateActionxData.cpp

Reduce hotness of Actions.hpp by 87% (145 files, 21 files instead of 166)

ScheduleState.hpp: forward Action::Actions

---

opm/input/eclipse/Schedule/ScheduleState.hpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp

Reduce hotness of UDQConfig.hpp by 83% (140 files, 28 files instead of 168)

ScheduleState.hpp: forward UDQConfig

---

opm/input/eclipse/Schedule/Well/Well.hpp
python/cxx/well.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/output/eclipse/AggregateConnectionData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/LoadRestart.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/output/eclipse/report/WELSPECS.cpp
tests/parser/ACTIONX.cpp
tests/parser/integration/ParseKEYWORD.cpp
tests/test_AggregateConnectionData.cpp
tests/test_Restart.cpp
tests/test_Serialization.cpp

Reduces hotness of WellConnections.hpp by 82% (235 files, 51 instead of 286)

Well.hpp: forward WellConnections

---

opm/input/eclipse/Schedule/MSW/WellSegments.hpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/output/eclipse/AggregateMSWData.cpp
src/opm/output/eclipse/AggregateWellData.cpp
src/opm/output/eclipse/Summary.cpp
src/opm/output/eclipse/report/WELSPECS.cpp
tests/parser/MultisegmentWellTests.cpp
tests/parser/integration/ParseKEYWORD.cpp
tests/test_Serialization.cpp

Reduces hotness of WellSegments.hpp by 90% (256 files, 29 files instead of 285)

Well.hpp: forward WellSegments

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
tests/parser/ScheduleTests.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

Reduces hotness of WellFoamProperties.hpp by 96% (273 files, 11 files instead of 284)

Well.hpp: forward WellFoamProperties

---

src/opm/input/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/input/eclipse/EclipseState/Tables/Tables.cpp
src/opm/input/eclipse/share/keywords/900_OPM/P/PERMFACT

PERMFACT table was using equilibration regions instead of PVT regions.

Permfact table fix

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
tests/parser/ScheduleTests.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

Reduces hotness of WellPolymerProperties.hpp by 96% (274 files, 11 files instead of 285)

Well.hpp: forward WellPolymerProperties

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
tests/test_Serialization.cpp

Reduces hotness for WellMIPCProperties.hpp by 97% (276 files, 9 files instead of 285)

Well.hpp: forward WellMICPProperties

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp
tests/test_Serialization.cpp

Reduce hotness of WellEconProductionLimits.hpp by 96% (273 files, 11 files instead of 284)

Well.hpp: forward WellEconProductionLimits

---

opm/input/eclipse/Schedule/Well/Well.hpp

Reduce hotness of ActiveGridCells.hpp by 97% (277 files, 9 files instead of 286)

Well.hpp: remove unnecessary ActiveGridCells.hpp include

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/output/eclipse/AggregateWellData.cpp
tests/parser/ScheduleTests.cpp
tests/test_Serialization.cpp

Reduce hotness of WVFPEXP.hpp by 96% (273 files, 12 files instead of 285)

Well.hpp: forward WVFPEXP

---

opm/input/eclipse/EclipseState/Grid/FieldPropsManager.hpp
opm/input/eclipse/EclipseState/Grid/Keywords.hpp

Reduce hotness of FieldData.hpp by 96% (202 files, 9 files instead of 211)

FieldPropsManager.hpp: forward FieldData

---

opm/output/eclipse/EclipseIO.hpp
opm/output/eclipse/RestartIO.hpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/RestartIO.cpp
tests/test_EclipseIO.cpp
tests/test_RFT.cpp
tests/test_restartwellinfo.cpp

Reduce hotness of RestartValue.hpp by 13% (7 files, 48 files instead of 55)

(Eclipse|Restart)IO: forward Restart(Key|Value)

---

opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.hpp
opm/input/eclipse/EclipseState/Grid/TranCalculator.hpp
src/opm/input/eclipse/EclipseState/Grid/FieldPropsManager.cpp

Reduce hotness of TranCalculator.hpp by 80% (171 files, 42 files instead of 213)

FieldPropsManager.hpp: forward TranCalculator

---

opm/input/eclipse/Schedule/Well/WellTestConfig.hpp
opm/input/eclipse/Schedule/Well/WellTestState.hpp

Reduce hotness of WellTestConfig.hpp by 77% (53 files, 16 files instead of 69)

WellTestState: forward WellTestConfig

---

opm/io/eclipse/ExtSmryOutput.hpp
opm/output/eclipse/EclipseIO.hpp
src/opm/input/eclipse/Schedule/Well/Connection.cpp

No big gains to be had here but still..

Some small header cleanups

---

opm/input/eclipse/Schedule/UDQ/UDQFunction.hpp
opm/input/eclipse/Schedule/UDQ/UDQFunctionTable.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQFunction.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQFunctionTable.cpp

Mostly for readability and maintainability.

Adjust Whitespace And Simplify Logic Slightly

---

opm/input/eclipse/Schedule/Well/NameOrder.hpp
src/opm/input/eclipse/Schedule/Well/NameOrder.cpp

Mostly whitespace, but one instance of preferring a standard algorithm over a raw loop.

Slight Polish to NameOrder Component

---

src/opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp

This commit switches the implementation of eval_define() into a single loop over `UDQConfig::input_index` instead of multiple loops over subsets of the same input index.  While this is more complex logic, it saves forming multiple intermediate quantities that will for the most part be discarded.
This is also in preparation of adding support for segment level UDQs, which would necessitate another loop in the previous control structure.
While here, also switch to using structured bindings where appropriate and pruning a few other intermediate objects.

Fuse Multiple DEFINE Types Into Single Evaluation Loop

---

opm/input/eclipse/Schedule/Action/ActionContext.hpp
src/opm/input/eclipse/Schedule/Action/ActionContext.cpp
src/opm/output/eclipse/AggregateActionxData.cpp
tests/test_Serialization.cpp

Reduce hotness of SummaryState.hpp by 38% (42 files, 68 instead of 110)

ActionContext: forward SummaryState

---

msim/src/msim.cpp
opm/output/eclipse/Summary.hpp
src/opm/output/eclipse/Summary.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp

Not a big thing, 8 files instead of 11.

Summary.hpp: forward PAvgCalculatorCollection

---

bin/genEvalSpecializations.py
opm/material/densead/DynamicEvaluation.hpp
opm/material/densead/Evaluation.hpp
opm/material/densead/Evaluation1.hpp
opm/material/densead/Evaluation10.hpp
opm/material/densead/Evaluation11.hpp
opm/material/densead/Evaluation12.hpp
opm/material/densead/Evaluation2.hpp
opm/material/densead/Evaluation3.hpp
opm/material/densead/Evaluation4.hpp
opm/material/densead/Evaluation5.hpp
opm/material/densead/Evaluation6.hpp
opm/material/densead/Evaluation7.hpp
opm/material/densead/Evaluation8.hpp
opm/material/densead/Evaluation9.hpp

Sits on top of https://github.com/OPM/opm-common/pull/3383
For restart.

Evaluation: add serialization support

---

opm/input/eclipse/Schedule/Group/GPMaint.hpp

Sits on top of https://github.com/OPM/opm-common/pull/3388

GPMaint::State: add serialization support

---

opm/input/eclipse/Schedule/Group/GuideRate.hpp
src/opm/input/eclipse/Schedule/Group/GuideRate.cpp

Sits on top of https://github.com/OPM/opm-common/pull/3392

GuideRate: add serialization support

---

opm/material/fluidstates/BlackOilFluidState.hpp

Removed unnecessary comment

---

tests/test_Serialization.cpp

follow-up to comment in https://github.com/OPM/opm-simulators/pull/4420

test_Serialization: mark variables const

---

opm/material/fluidmatrixinteractions/EclMultiplexerMaterial.hpp
opm/material/fluidsystems/BlackOilFluidSystem.hpp

Same as in opm-simulator. See that pullrequest for more.

added timingblocks most important functions

---

opm/input/eclipse/Schedule/Group/GPMaint.hpp
src/opm/input/eclipse/Schedule/Group/GPMaint.cpp

while at it, move some code to cpp file and add missing headers

GPMaint::State: add comparison operator

---

src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerHystParams.cpp

Bug was introduced in #3364
Test case in OPM/opm-tests#888
With this PR the old results are reproduced

BUGFIX JFUNC,  use the correct config file when getting the endpoints

---

src/opm/input/eclipse/EclipseState/Runspec.cpp

these were moved to Phase.cpp in f8e0319 but
I forgot to remove them from Runspec.cpp

fixed: remove duplicated symbols

---

CMakeLists_files.cmake
opm/input/eclipse/EclipseState/Runspec.hpp
opm/input/eclipse/EclipseState/Tables/GsfTable.hpp
opm/input/eclipse/EclipseState/Tables/TableManager.hpp
opm/input/eclipse/EclipseState/Tables/WsfTable.hpp
opm/output/eclipse/Tables.hpp
src/opm/input/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
src/opm/input/eclipse/EclipseState/Runspec.cpp
src/opm/input/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/input/eclipse/EclipseState/Tables/Tables.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SGFN
src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SGOF
src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SLGOF
src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SWFN
src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SWOF
src/opm/input/eclipse/share/keywords/001_Eclipse300/G/GSF
src/opm/input/eclipse/share/keywords/001_Eclipse300/W/WSF
src/opm/input/eclipse/share/keywords/keyword_list.cmake
src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp
src/opm/output/eclipse/Tables.cpp
tests/material/test_eclmateriallawmanager.cpp

See test case https://github.com/OPM/opm-tests/pull/902

Implement WSF/GSF satfunc familiy for CO2STORE

---

opm/input/eclipse/EclipseState/SimulationConfig/ThresholdPressure.hpp
src/opm/input/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp

needed to print thresholdpressure to prt files

add accessor for m_irreversible in ThresholdPressure

---

opm/material/common/Tabulated1DFunction.hpp
opm/material/common/UniformXTabulated2DFunction.hpp
opm/material/fluidmatrixinteractions/EclDefaultMaterialParams.hpp
opm/material/fluidmatrixinteractions/EclEpsTwoPhaseLawParams.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterial.hpp
opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityWaterPvt.hpp
opm/material/fluidsystems/blackoilpvt/DryGasPvt.hpp

- removed use of shared pointers give almost factor 2 improvement in relperm evaluation
- added interface for reusing indices in evaluation.
- fixed missing refernce in DryGas..

New property 

---

opm/material/fluidstates/FluidStateFugacityModules.hpp
src/opm/input/eclipse/EclipseState/Grid/MinpvMode.cpp

Plus a missing include I ran into..

MinpvMode: avoid missing return value with NDEBUG

---

opm/output/data/Cells.hpp
tests/test_EclipseIO.cpp
tests/test_Restart.cpp
tests/test_Solution.cpp

This enables using in-place construction in `Solution::insert()`.

Add Constructors for CellData Objects

---

src/opm/input/eclipse/EclipseState/Runspec.cpp
src/opm/input/eclipse/share/keywords/001_Eclipse300/C/CNAMES
src/opm/input/eclipse/share/keywords/001_Eclipse300/F/FIELDSEP
src/opm/input/eclipse/share/keywords/001_Eclipse300/G/GASWAT
src/opm/input/eclipse/share/keywords/001_Eclipse300/G/GSF
src/opm/input/eclipse/share/keywords/001_Eclipse300/H/HWELLS
src/opm/input/eclipse/share/keywords/001_Eclipse300/N/NCOMPS
src/opm/input/eclipse/share/keywords/001_Eclipse300/S/SOLID
src/opm/input/eclipse/share/keywords/001_Eclipse300/W/WELLSTRE
src/opm/input/eclipse/share/keywords/001_Eclipse300/W/WINJGAS
src/opm/input/eclipse/share/keywords/001_Eclipse300/W/WSF
src/opm/input/eclipse/share/keywords/001_Eclipse300/Z/ZMFVD
src/opm/input/eclipse/share/keywords/keyword_list.cmake

Preparation for https://github.com/OPM/opm-tests/pull/902

CO2STORE + GASWAT parsing

---

opm/output/data/Solution.hpp
src/opm/output/data/Solution.cpp

It's a generally useful technique that's never slower than construct followed by move.

Enable In-Place Element Construction in Insert()

---

cmake/Modules/Finddune-polygongrid.cmake

- this added need finding polygongrid.
- if make the dune-fem in opm consistent with optional dependencies

fixed error if dune-fem is buildt with polygongrid

---

opm/material/components/H2O.hpp

fixes compilation if QUADMATH is detected

fixed missing include

---

opm/material/components/Brine.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp

Two bugs was noticed during close inspection. Thanks to @svenn-t for noticing the sign bug.

Fix thermal + co2

---

opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
src/opm/input/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp

Enable hysteresis in water gas 2p model

---

dune.module
opm/material/constraintsolvers/ImmiscibleFlash.hpp
opm/material/constraintsolvers/MiscibleMultiPhaseComposition.hpp
opm/material/constraintsolvers/NcpFlash.hpp
opm/material/constraintsolvers/PTFlash.hpp

In preparation for bumping to dune 2.7. Leaving in draft mode as we should merge this close to 23.04 release.

minimum dune version required is now 2.7

---

src/opm/input/eclipse/EclipseState/Aquifer/AquiferCT.cpp
src/opm/input/eclipse/EclipseState/Aquifer/Aquifetp.cpp

with master branch, only the last instance will be caught for these two keywords.
It is a followup for PR #3468

checking all the instances of AQUCT and AQUFETP keywords

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp

which is not needed anymore after https://github.com/OPM/opm-common/pull/3463 getting merged. 
So I am removing this function for good.

removing Well::canOpen() function

---

src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

This PR adds sanity checking to the cell references of block level summary vectors (e.g., BPR or BGSAT).  If the summary vector references a cell that's outside the models declared dimensions we issue a warning and ignore that particular summary vector request.

Check for Invalid Cells in Block Level Summary Vectors

---

opm/material/thermal/EclSolidEnergyLawMultiplexer.hpp
opm/material/thermal/EclSolidEnergyLawMultiplexerParams.hpp
opm/material/thermal/EclThermalConductionLawMultiplexer.hpp
opm/material/thermal/EclThermalConductionLawMultiplexerParams.hpp
opm/material/thermal/EclThermalLawManager.hpp
src/opm/material/thermal/EclThermalLawManager.cpp

More type safety, not duplicated per template instance.

Convert thermal enums to enum class

---

src/opm/input/eclipse/Schedule/KeywordHandlers.cpp

Achieving no impact on next time step needs to be handled separately.

Changing TUNING semantics to 'only change when specified'. 

---

CMakeLists_files.cmake
examples/co2brinepvt.cpp
opm/material/binarycoefficients/Brine_CO2.hpp
opm/material/components/BrineDynamic.hpp
opm/material/fluidsystems/BrineCO2FluidSystem.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp
src/opm/material/fluidsystems/BlackOilFluidSystem.cpp
src/opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp
src/opm/material/fluidsystems/blackoilpvt/Co2GasPvt.cpp
tests/material/test_components.cpp

This allows for combination of CO2STORE and BRINE. 
Need some more testing before it can be merge i.e. lets make it a draft PR.

Combine brine + co2store

---

test_util/EclFilesComparator.cpp

See https://github.com/OPM/opm-simulators/pull/4660#issuecomment-1560076137

Calculate deviation such that different signs are accounted for.

---

tests/material/checkComponent.hpp
tests/material/test_components.cpp

- improve output
- convert to boost::test

test_components: Some janitoring

---

tests/material/test_co2brinepvt.cpp

- avoid dead stores
- convert to boost::test

test_co2brinepvt: Some janitoring

---

tests/material/test_immiscibleflash.cpp

Sadly there is no support for templated fixtures so I have to do it manually.

test_immiscibleflash: convert to boost::test

---

tests/material/test_2dtables.cpp

And drop the shared ptrs, move semantics works just fine.

test_2dtables: convert to boost::test

---

tests/material/test_fluidmatrixinteractions.cpp

Not really a unit test, as it only checks api conformance.

test_fluidmatrixinteractions: convert to boost::test

---

opm/material/fluidsystems/BlackOilFluidSystem.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/BrineH2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp
opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityBrinePvt.hpp
opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityOilPvt.hpp
opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityWaterPvt.hpp
opm/material/fluidsystems/blackoilpvt/DeadOilPvt.hpp
opm/material/fluidsystems/blackoilpvt/DryGasPvt.hpp
opm/material/fluidsystems/blackoilpvt/DryHumidGasPvt.hpp
opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/GasPvtThermal.hpp
opm/material/fluidsystems/blackoilpvt/H2GasPvt.hpp
opm/material/fluidsystems/blackoilpvt/LiveOilPvt.hpp
opm/material/fluidsystems/blackoilpvt/OilPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/OilPvtThermal.hpp
opm/material/fluidsystems/blackoilpvt/SolventPvt.hpp
opm/material/fluidsystems/blackoilpvt/WaterPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/WaterPvtThermal.hpp
opm/material/fluidsystems/blackoilpvt/WetGasPvt.hpp
opm/material/fluidsystems/blackoilpvt/WetHumidGasPvt.hpp

Needed to properly handle dynamic values from SCHEDULE

added: setters for the vappars in pvt classes

---

src/opm/input/eclipse/Python/Python.cpp

- removed try catch in non python runs

Remove throw in normal runs

---

src/opm/output/eclipse/Summary.cpp

FPRP and RPRP seems to have been lost some time. The simulator part is already working.

add missing FPRP and RPRP

---

opm/input/eclipse/EclipseState/EclipseState.hpp
src/opm/input/eclipse/EclipseState/EclipseState.cpp
tests/parser/FaultTests.cpp

I'm not entirely sure I understood the relations here entirely. In particular, if there are multiple records in EDIT we multiply with all of them. Is that proper or is the idea that it should be last-record-in-grid times last-record-in-edit ?

fixed: properly combine MULTFLT from GRID and EDIT

---

opm/material/fluidmatrixinteractions/EclDefaultMaterial.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
opm/material/fluidmatrixinteractions/EclMultiplexerMaterial.hpp
opm/material/fluidmatrixinteractions/EclStone1Material.hpp
opm/material/fluidmatrixinteractions/EclStone2Material.hpp
opm/material/fluidmatrixinteractions/EclTwoPhaseMaterial.hpp

- added changed values to hysteris calles

Changed hyst

---

src/opm/input/eclipse/Parser/ParserItem.cpp

The reason is to allow sharing default values with the opm-models/simulators parameter system.

Let int and float parser items have constexpr default values

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/E/EQLDIMS

Changing value to be consistent with current implementation.

Changing default value for number of pressure points used in equilibration

---

src/opm/output/eclipse/Summary.cpp
tests/SOFR_TEST.DATA
tests/summary_deck.DATA
tests/test_Summary.cpp

In particular, recognize the summary vectors
- SDENx -- Phase density of phase `x` (segment conditions)
- SDENM -- Fluid mixture density without flowing fraction exponents
- SMDEN -- Fluid mixture density with flowing fraction exponents
- BxDEN and BDENx -- Phase density of phase `x`
Phase `x` is one of `O` (oil), `G` (gas), or `W` (water).

Add Summary Output of Fluid Densities at Block and Segment Levels

---

opm/material/fluidmatrixinteractions/EclTwoPhaseMaterial.hpp
opm/material/fluidmatrixinteractions/EclTwoPhaseMaterialParams.hpp

Changes to make it possible to directly use non multiplexers.

Fixes for two-phase relperm

---

.clang-format

not saying it is used or useful, but my IDE complained about it.

removing duplicated key in .clang-format

---

opm/input/eclipse/EclipseState/Util/OrderedMap.hpp

We don't need `std::string` in the hashing operations, so lift those restrictions.

Implement OrderedMap in Terms of String_View

---

opm/input/eclipse/Units/UnitSystem.hpp
opm/input/eclipse/Units/Units.hpp
src/opm/input/eclipse/Units/UnitSystem.cpp
tests/parser/UnitTests.cpp

Parts per million (ppm). We are not distinguishing PPM volume or PPM mass, or other forms. Will update when it comes to be necessary.

adding unit PPM

---

CMakeLists_files.cmake
tests/parser/BCConfigTests.cpp

Very basic and only positive tests and all that but at least there is some testing.

added: basic tests for BCCON / BCPROP

---

opm/input/eclipse/Units/UnitSystem.hpp
opm/input/eclipse/Units/Units.hpp
src/opm/input/eclipse/Units/UnitSystem.cpp
tests/parser/UnitTests.cpp

preparing for a summary output related to area, finding out that we do not have a are dimension.

adding unit area

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/input/eclipse/share/keywords/900_OPM/W/WINJFCNC

restarting related is missing for now.

handle UDQ value for WINJFCNC

---

opm/input/eclipse/Schedule/Group/Group.hpp
python/cxx/group.cpp
src/opm/input/eclipse/Schedule/Group/Group.cpp

after GRUPNET is processed, vfp_table is not useful for GROUP class anymore.

removing the vfp_table member from Group class

---

opm/input/eclipse/Schedule/Well/WellInjectionControls.hpp
opm/input/eclipse/Schedule/Well/WellProductionControls.hpp

Add a few functions that enable removing/adding active inj/prod controls. Needed for _implicit_ version of potential/ipr calculations.

Utility functions for manipulation of well-controls

---

opm/material/common/ConditionalStorage.hpp

@GitPaean had some grief due to missing initialization of temperature in the BlackoilFluidState.

fixed: initialize data in ConditionalStorage

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp

Should resolve https://github.com/OPM/opm-simulators/issues/4222

Ensure numerical aquifer cells get the correct depth

---

opm/common/TimingMacros.hpp
opm/material/binarycoefficients/Brine_CO2.hpp
opm/material/components/CO2.hpp
opm/material/components/SimpleHuDuanH2O.hpp
opm/material/fluidmatrixinteractions/EclDefaultMaterial.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLaw.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
opm/material/fluidmatrixinteractions/EclMultiplexerMaterial.hpp
opm/material/fluidmatrixinteractions/EclTwoPhaseMaterial.hpp
opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterial.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp

- more timing macros and more timing of co2store

More timing

---

opm/material/components/C1.hpp
opm/material/components/C10.hpp
opm/material/components/SimpleCO2.hpp
opm/material/constraintsolvers/PTFlash.hpp
opm/material/eos/PengRobinson.hpp
opm/material/eos/PengRobinsonMixture.hpp
opm/material/fluidsystems/Co2BrineFluidSystem.hh
opm/material/fluidsystems/PTFlashParameterCache.hpp
opm/material/fluidsystems/ThreeComponentFluidSystem.hh
opm/material/viscositymodels/LBC.hpp
tests/material/test_co2brine_ptflash.cpp
tests/material/test_threecomponents_ptflash.cpp

This is mostly done by @trinemykk , some by @svenn-t .  I did some cleaning up and corrections. 
Some commits will be squashed later.  Creating this PR for now to test the jenkins.

various correction to prepare for the PTFlash simulation

---

opm/input/eclipse/EclipseState/Runspec.hpp
src/opm/input/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
src/opm/input/eclipse/EclipseState/Runspec.cpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp
src/opm/output/eclipse/Tables.cpp
tests/parser/FieldPropsTests.cpp

Support for SGWFN sat functions (format type 2)

---

CMakeLists_files.cmake

Purely cosmetic but I was in the area so..

changed: sort UDQ headers/sources in alphabetical order

---

opm/material/constraintsolvers/PTFlash.hpp

adding removing some white spaces in PTFlash.hpp
Will self-merge when jenkins approves.

outputting the maxIterations in the PTFlash failure message

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQContext.hpp
opm/input/eclipse/Schedule/UDQ/UDT.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQContext.cpp
src/opm/input/eclipse/Schedule/UDQ/UDT.cpp
tests/parser/UDQTests.cpp
tests/parser/UDTTests.cpp
tests/test_AggregateUDQData.cpp

This adds the container for UDTs and adds slots for them in UDQConfig and UDQContext.
Note this is limited to 1D UDTs only.

Prepare for UDT support

---

opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Parser/Parser.cpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/U/UDT
tests/parser/ParserTests.cpp
tests/parser/UDTTests.cpp

This adds parsing support for 1D UDTs. Sits on top of https://github.com/OPM/opm-common/pull/3725

Add parsing for UDT

---

cmake/Modules/OpmInit.cmake

Backport of pr 3710

---

opm/input/eclipse/Parser/ParseContext.hpp
opm/input/eclipse/Schedule/Action/ActionX.hpp
src/opm/input/eclipse/Parser/ParseContext.cpp
src/opm/input/eclipse/Schedule/Action/ActionParser.cpp
src/opm/input/eclipse/Schedule/Action/ActionX.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

Better error handling for problems in conditions of ACTIONX

---

opm/input/eclipse/Schedule/UDQ/UDQASTNode.hpp
opm/input/eclipse/Schedule/UDQ/UDQEnums.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQASTNode.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQDefine.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQEnums.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQParser.cpp
src/opm/io/eclipse/SummaryNode.cpp
tests/parser/ParserTests.cpp
tests/parser/UDQTests.cpp

This adds support for UDT lookups in UDQs.
Sits on top of https://github.com/OPM/opm-common/pull/3727

Add support for UDT lookups in UDQs

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/W/WDFACCOR

We were missing the `Area` component.

Fix Dimension of D-Factor Correlation 'A' Coefficient

---

opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp
src/opm/input/eclipse/Schedule/Well/WellProductionProperties.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/F/FBHPDEF
tests/parser/WellTests.cpp

This adds support for the FBHPDEF keyword.

implement support for FBHPDEF

---

src/opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp
src/opm/material/fluidsystems/blackoilpvt/Co2GasPvt.cpp

This outputs the reference density used by the CO2STORE model.

Add info about surface density from CO2STORE model

---

CMakeLists_files.cmake
opm/input/eclipse/EclipseState/IOConfig/FIPConfig.hpp
src/opm/input/eclipse/EclipseState/IOConfig/FIPConfig.cpp
tests/parser/FIPConfigTests.cpp

this parses FIP related flags from RPT(SCHED|SOL)

added: FIPConfig class

---

docs/man1/arraylist.1
docs/man1/co2brinepvt.1
docs/man1/compareECL.1
docs/man1/convertECL.1
docs/man1/opmhash.1
docs/man1/opmpack.1
docs/man1/rst_deck.1
docs/man1/summary.1

[backport] Update and improve man pages for release

---

test_util/arraylist.cpp

segmentation fault due to missing argument is not very nice.

Fix segmentation fault if file name is missing after arraylist command.

---

opm/input/eclipse/Schedule/Network/ExtNetwork.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Network/ExtNetwork.cpp
tests/parser/NetworkTests.cpp

Possible alternative to:  https://github.com/OPM/opm-common/pull/3674 (?)

Support networks with multiple fixed-pressure nodes

---

opm/material/fluidstates/BlackOilFluidState.hpp

Following  [#4973](https://github.com/OPM/opm-simulators/pull/4973)

Renaming enableEvaporation to enableVapwat

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Schedule/HandlerContext.cpp
src/opm/input/eclipse/Schedule/HandlerContext.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/MSW/WelSegsSet.cpp
src/opm/input/eclipse/Schedule/MSW/WelSegsSet.hpp
src/opm/input/eclipse/Schedule/Schedule.cpp

HandlerContext: put in separate compilation unit

---

src/opm/output/eclipse/AggregateMSWData.cpp
tests/test_AggregateMSWData.cpp

This commit places more conditions on the branch discovery order than the previous work in commit 6d3ee57dd (PR #3696).  In particular, we now ensure that branches are discovered ("created") in the order of increasing segment number of the branch outlet segment. Furthermore, if multiple branches have the same outlet segment, then we sort those branches on their increasing branch IDs.
To this end, switch from using a `std::queue<int>` to using a `std::priority_queue<KickOffPoint>`, with the `KickOffPoint` being a custom structure holding the kick-off segment, the branch outlet segment, and the branch ID and a custom `operator<()` to plug into the `priority_queue<>` heap mechanism.
This new sort order changes the result of certain unit tests, but those changes are expected and desired.

Revise Branch Discovery Order for MSW Output

---

src/opm/input/eclipse/EclipseState/EclipseState.cpp
tests/parser/LgrTests.cpp

Otherwise people will experience linker error when trying to use it.
Closes #3787

Also define function EclipseState::hasInputLgr

---

CMakeLists_files.cmake
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/MSW/MSWKeywordHandlers.cpp
src/opm/input/eclipse/Schedule/MSW/MSWKeywordHandlers.hpp

Here I might have missed some keywords that I don't know is MSW specific..

move MSW keyword handlers to separate file

---

opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.hpp
src/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/input/eclipse/EclipseState/Grid/FieldPropsManager.cpp

returns a list of all FIP keywords encountered

added: FieldProps(Manager)::fip_regions

---

opm/input/eclipse/EclipseState/WagHysteresisConfig.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
src/opm/input/eclipse/EclipseState/WagHysteresisConfig.cpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerInitParams.cpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp

Avoid EclipseState.hpp in headers

---

src/opm/input/eclipse/Schedule/Well/WellPropertiesKeywordHandlers.cpp

That way we can remove one level of nesting.  While here, also ensure that we have a new 'scalingApplicable' object for each well lest we potentially run into conflicting definitions of the eligible connections.

Use Early Return for Runtime WELPI Handling

---

src/opm/input/eclipse/Parser/Parser.cpp

Ignore everything between SKIP|SKIP100|SKIP300 and ENDSKIP

Support SKIP/ENDSKIP, i.e., ignore everything between.

---

CMakeLists_files.cmake
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/RXXKeywordHandlers.cpp
src/opm/input/eclipse/Schedule/RXXKeywordHandlers.hpp

And some indent cleanup for remaining handlers.

move RFT/RPT/RST keyword handlers to separate file

---

src/opm/output/eclipse/WriteInit.cpp
tests/test_EclipseIO.cpp

This commit makes the INIT file writing code aware of the `SWATINIT` array and will output this array to the INIT file if it exists in the input deck.

Output SWATINIT Array to INIT File if Present

---

opm/output/data/Cells.hpp
opm/output/data/Solution.hpp
src/opm/output/data/Solution.cpp
src/opm/output/eclipse/RestartIO.cpp
src/opm/output/eclipse/WriteInit.cpp
tests/msim/test_msim.cpp
tests/test_EclipseIO.cpp
tests/test_Restart.cpp
tests/test_Solution.cpp

This in preparation for output of CNV_xx vectors which should be stored as integers.

data::CellData: add support for integer vectors

---

CMakeLists_files.cmake
opm/common/utility/Visitor.hpp
tests/test_Visitor.cpp

This adds a helper class for implementing the visitor-overloadset-idiom plus a small test.

added: helper class for implementing visitor overload sets

---

opm/output/data/Cells.hpp
src/opm/output/eclipse/RestartIO.cpp

This adds writing of INT restart vectors using visitors. I've included #3278 for simplicity. If you want, we can handle that one separately first.

RestartIO: Handle INT vectors

---

opm/material/checkFluidSystem.hpp
opm/material/eos/PengRobinson.hpp
opm/material/eos/PengRobinsonParamsMixture.hpp
opm/material/fluidsystems/PTFlashParameterCache.hpp
opm/material/fluidsystems/ThreeComponentFluidSystem.hh
tests/material/test_fluidsystems.cpp

not totally sure it is doing the right thing in the right manner. Will look into it more.

adding ThreeComponentFluidSystem to test_fluidsystem

---

src/opm/input/eclipse/share/keywords/001_Eclipse300/C/CREFW
src/opm/input/eclipse/share/keywords/001_Eclipse300/C/CREFWS
src/opm/input/eclipse/share/keywords/keyword_list.cmake

removing CREFS, which is likely a typo when creating the keyword.

adding CREFW and CREFWS

---

opm/output/eclipse/Inplace.hpp
src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/F/FIELD_PROBE
src/opm/input/eclipse/share/keywords/000_Eclipse100/R/REGION_PROBE
src/opm/output/eclipse/Inplace.cpp
src/opm/output/eclipse/Summary.cpp

This adds mass output of in-place CO2.

Add mass co2 in place summary vectors

---

opm/material/components/Air.hpp
opm/material/components/Brine.hpp
opm/material/components/BrineDynamic.hpp
opm/material/components/C1.hpp
opm/material/components/C10.hpp
opm/material/components/CO2.hpp
opm/material/components/Component.hpp
opm/material/components/Dnapl.hpp
opm/material/components/H2O.hpp
opm/material/components/Lnapl.hpp
opm/material/components/Mesitylene.hpp
opm/material/components/N2.hpp
opm/material/components/SimpleCO2.hpp
opm/material/components/SimpleH2O.hpp
opm/material/components/SimpleHuDuanH2O.hpp
opm/material/components/TabulatedComponent.hpp
opm/material/components/Unit.hpp
opm/material/components/Xylene.hpp
opm/material/fluidsystems/BaseFluidSystem.hpp
opm/material/fluidsystems/BrineCO2FluidSystem.hpp
opm/material/fluidsystems/Co2BrineFluidSystem.hh
opm/material/fluidsystems/GenericOilGasFluidSystem.hpp
opm/material/fluidsystems/H2ON2FluidSystem.hpp
opm/material/fluidsystems/H2ON2LiquidPhaseFluidSystem.hpp
opm/material/fluidsystems/Spe5FluidSystem.hpp
opm/material/fluidsystems/ThreeComponentFluidSystem.hh
opm/material/fluidsystems/TwoPhaseImmiscibleFluidSystem.hpp
tests/material/checkComponent.hpp

it was motivated by 
https://github.com/OPM/opm-models/pull/855#issuecomment-1898584501

using more std::string_view instead of char*

---

src/opm/input/eclipse/Schedule/HandlerContext.cpp
src/opm/input/eclipse/Schedule/HandlerContext.hpp
src/opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp

Pair with https://github.com/OPM/opm-simulators/pull/5124.

Add open well events for WCONHIST and WCONINJH

---

src/opm/input/eclipse/Schedule/RSTConfig.cpp

Following https://github.com/OPM/opm-simulators/pull/5126

Write PCGW in the restart file

---

opm/input/eclipse/Deck/Deck.hpp
opm/input/eclipse/Parser/Parser.hpp
python/tests/test_parse_deck.py
src/opm/input/eclipse/Parser/Parser.cpp
tests/parser/ParserTests.cpp

* Supporting that EDIT, REGIONS and SUMMARY section is optional
* RUNSPEC needed for parsing, but keywords removed from deck after parsing if not needed

Improved parsing of individual sections

---

opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp

Add missing include discovered by downstream header reshuffling.

add missing include

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Network/NetworkKeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
tests/parser/NetworkTests.cpp

This PR is required by https://github.com/OPM/opm-simulators/pull/4935

disable guide rates and set control mode to THP for wells with autochoke

---

opm/input/eclipse/Schedule/RSTConfig.cpp
opm/input/eclipse/Schedule/RSTConfig.hpp
tests/parser/RestartConfigTests.cpp

This PR extends our handling of the `RPTSOL` keyword when the `'RESTART'` flag is present.  This is in preparation of adding support for outputting fluid-in-place arrays (`FIP*`, `RFIP*`, `SFIP*`) to the restart file when the input specifies something along the lines of
```
SOLUTION
-- ...
RPTSOL
RESTART=2 FIP /
-- ...
SCHEDULE
```
In this case, we need to treat flags other than `RESTART` as restart file output requests and confer those requests on to the simulation layer.  We nevertheless need to ensure that those requests apply only to the time=0 (SEQNUM=0) time point, so introduce a new helper, `solution_only_keywords`, to track those flags which must **not** be forwarded to subsequent time points and remove those as part of `RSTConfig::first()`.
At this time we use the `RPTSCHED` …

Internalise RPTSOL Flags for Restart File Output

---

opm/output/eclipse/RestartIO.cpp
tests/test_Restart.cpp

This PR introduces special case logic for outputting per-cell fluid-in-place arrays.  In particular, we intercept arrays tagged as `RESTART_SOLUTION` and named as
* FIP{OIL,WAT,GAS}
* RFIP{OIL,WAT,GAS}
* SFIP{OIL,WAT,GAS}
and write those in a separate function (`writeFluidInPlace()`) instead of as part of `writeRegularSolutionVectors()`.  We also add special compatibility logic to output `SFIP*` as alias/copy of `FIP*` if no `RFIP*` or `SFIP*` arrays exist in [`RestartValue::solution`](https://github.com/OPM/opm-common/blob/c4d25b479fb810da828ca0cb033a1dc2e4434055/opm/output/eclipse/RestartValue.hpp#L78).

Add Restart File Output for Fluid-In-Place Arrays

---

opm/material/constraintsolvers/PTFlash.hpp
tests/material/test_co2brine_ptflash.cpp

it is a replacement for https://github.com/OPM/opm-common/pull/3846.

Compositional: Rewrite flash to use vapor fraction, add tests for Rachford-Rice

---

test_util/summary.cpp

Enable output of summary vectors without any header info.

New option for summary program

---

opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp

When handling UDQs and, especially, `ACTIONX` condition blocks, it is permissible to treat `FIELD` as a regular group.  In particular, an `ACTIONX` condition block might use conditions such as
```
GGOR 'FIELD' > 123.4 AND /
GOPR 'FIELD' < 654.3 /
```
and we need to be prepared to handle those.  We therefore bypass the check for `group == "FIELD"` in `keywordG()` in this particular context.
We nevertheless preserve the `FIELD` group exclusion when processing ordinary group level keywords which don't name specific groups in the SUMMARY section such as
```
GOPR
/
```
Future work may elect to include `FIELD` in this context too.

Selectively Bypass FIELD Exclusion From Group Level Keywords

---

opm/input/eclipse/Parser/Parser.cpp
python/cxx/parser.cpp

adding section keywords RUNSPEC and EDIT to eclSectionType

fix python bindings for parser

---

opm/input/eclipse/Schedule/Schedule.hpp
test_util/EclRegressionTest.cpp

Fix some debug iterator failures:
- missing initialization
- broken erase-loop iterator usage.

Some debug-iterator Janitoring

---

docs/man1/compareECL.1
test_util/EclRegressionTest.cpp
test_util/EclRegressionTest.hpp
test_util/compareECL.cpp
tests/test_EclRegressionTest.cpp

The extra keywords are printed out

For compareECL: Add option to accept extra keywords for both runs

---

opm/input/eclipse/EclipseState/Runspec.cpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLaw.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
opm/material/fluidmatrixinteractions/EclMultiplexerMaterial.hpp
opm/material/fluidmatrixinteractions/EclTwoPhaseMaterial.hpp
opm/material/fluidmatrixinteractions/SatCurveMultiplexer.hpp
tests/material/test_hysteresis.cpp

Only Killough hysteresis is supported. The implementation is the same as for the nonwetting phase hysteresis
Some unit tests added

Support hysteresis for wetting phase

---

opm/input/eclipse/Schedule/SummaryState.cpp
opm/input/eclipse/Schedule/SummaryState.hpp
opm/output/eclipse/Summary.cpp

This is in preparation of adding support for using region-level summary vectors in the defining expressions of field-level UDQs.

Introduce Special SummaryState Handling for Region Variables

---

CMakeLists_files.cmake
examples/hysteresis.cpp

A first step to simplify the testing of the hysteresis model.

Add small application for extracting relative permeability with hysteresis

---

opm/output/eclipse/Summary.cpp

The bare value 0.0 will be treated as 0 K and output as $-273.15$ or $-459.67$ depending on the unit convention.  This is typically not what we want.  This commit switches to using an appropriately dimensioned zero value generated by `UnitSystem::to_si(0.0)` as the fallback value for non-existent results.  That value will, in turn, be output as the value 0.0 in the summary file.  This is more in line with typical engineering expectations.

Use Unit-Aware Zero Value for Temperature

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp
python/cxx/schedule.cpp
tests/msim/MSIM_PYACTION_OPEN_WELL_AT_PAST_REPORT_STEP.DATA
tests/msim/MSIM_PYACTION_OPEN_WELL_AT_TOO_LATE_REPORT_STEP.DATA
tests/msim/action3.py
tests/msim/open_well_past.py
tests/msim/open_well_too_late.py
tests/msim/test_msim_ACTIONX.cpp

Add functionality to embedded python code for PYACTION: open/close/shut a well without specifying a report step; the report step will then be the current report step

Add functionality to embedded python code for PYACTION: open/close/shut a well without specifying a report step

---

opm/input/eclipse/Schedule/SummaryState.cpp

A number of `get*var()` functions were of the form
```C++
if (! has_var(map, var, entity, subEntity)) {
throw SomeException { ... };
}
return map.at(var).at(entity).at(subEntity);
```
which, if `has_var()` returns `true`, ends up looking up the `var`, the `entity`, and the `subEntity` twice inside `map`.  This PR switches to using the appropriate `.find()` expressions directly. While there is a considerable cost in code complexity compared to the original implementation, this is nevertheless justified by not having to look up each key twice.  Moreover, by using `find()` we have more context by which to phrase the diagnostic messages instead of the generic message that gets generated inside `map<>::at()`.
While here, also switch to using `fmt::format()` as a means of constructing composite …

Eliminate Duplicate Map Lookups in SummaryState

---

opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp

quell potentially uninitialized use warnings
ref https://ci.opm-project.org/job/opm-simulators/2176/gcc/folder.1573348989/

fixed: initialize Swmaxd_

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp

correcting m_input_coord to m_input_zcorn

---

opm/input/eclipse/Schedule/Well/PAvgCalculator.cpp
opm/input/eclipse/Schedule/Well/PAvgCalculator.hpp
opm/input/eclipse/Schedule/Well/PAvgCalculatorCollection.cpp
opm/input/eclipse/Schedule/Well/PAvgCalculatorCollection.hpp
opm/input/eclipse/Schedule/Well/PAvgDynamicSourceData.cpp
opm/input/eclipse/Schedule/Well/PAvgDynamicSourceData.hpp
tests/parser/PAvgTests.cpp
tests/test_PAvgCalculator.cpp
tests/test_PAvgDynamicSourceData.cpp

Extracted from https://github.com/OPM/opm-common/pull/4016

PAvgCalculator: template Scalar type

---

opm/common/utility/Serializer.hpp
opm/input/eclipse/Deck/UDAValue.cpp
opm/input/eclipse/Deck/UDAValue.hpp

This simplifies the code and makes it a bit easier to reason about. Might be possible to move to std::variant, but taking a smaller step here.
Also fix a minor bug in the serializer. @akva2 please check the second commit!

Use std::optional instead of bool and double

---

opm/input/eclipse/EclipseState/Grid/FieldProps.cpp

We need the actual element if it exists, so don't go through the count() member function just to check for existence.  While here, also move `get_keyword_from_alias()` into an anonymous namespace to suppress warnings about missing declarations.

Don't Look Up Map Elements Twice

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/io/eclipse/rst/group.cpp
opm/io/eclipse/rst/group.hpp
opm/io/eclipse/rst/well.cpp
opm/output/eclipse/AggregateGroupData.cpp
opm/output/eclipse/LoadRestart.cpp
opm/output/eclipse/VectorItems/group.hpp
opm/output/eclipse/VectorItems/well.hpp

Revert "Support restart with VREP in GCONINJE"

---

opm/input/eclipse/Deck/DeckItem.cpp

We would previously issue a message of the form
> No dimension has been set for item'X'; can not ask for SI data
This PR adds a space between the word "item" and the beginning quote of the item name.  We also rephrase the message slightly to read
> No dimension defined for item 'X'; cannot request SI data.
instead.  Finally, while here, also reduce code duplication.

Fix DeckItem Diagnostic Message

---

opm/input/eclipse/Deck/DeckOutput.cpp
opm/material/fluidsystems/BlackOilFluidSystem.hpp

Fixing two sets of warnings from clang.

Silence warnings

---

opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingInfo.cpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingInfo.hpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingKeywordHandlers.cpp
opm/input/eclipse/share/keywords/000_Eclipse100/G/GRUPMAST
tests/parser/ReservoirCouplingTests.cpp

See downstream https://github.com/OPM/opm-simulators/pull/5436 and https://github.com/OPM/opm-simulators/pull/5437 for more information.

Add support for GRUPMAST

---

cmake/Modules/FindMETIS.cmake

If the METIS header is from scotch, then we also need to search for PtScotch and link to it. For this we now detect scotch and adapt the METIS::METIS target to inlude PtScotch. We also force our build system to use the target instead of the library for linking to also get the necessary flags automatically.
If PtScotch is used as a metis replacement then we explicitely request METIS version 5 API by defining SCOTCH_METIS_VERSION appropriately.
Note that without this PR our config.h will contain `#define HAVE_METIS TRUE`

[cmake] Properly support scotch as a metis replacement.

---

cmake/Modules/FindMETIS.cmake

Based on https://github.com/OPM/opm-common/pull/4115/

 [cmake] Properly support scotch as a metis replacement

---

opm/input/eclipse/Schedule/MSW/MSWKeywordHandlers.cpp

Wells in the affected well list will be updated during time steps not only report steps.

Add wells modified with WSEGVAL to affected well list

---

opm/input/eclipse/Schedule/RSTConfig.cpp

Output support for RSWSAT and RVWSAT

Output support for RSWSAT and RVWSAT

---

CMakeLists_files.cmake
opm/common/utility/DemangledType.cpp
opm/common/utility/DemangledType.hpp
opm/material/checkFluidSystem.hpp
opm/material/fluidsystems/BaseFluidSystem.hpp
tests/material/checkComponent.hpp

I use it to output the Type name defined in TypeTag.

adding a utility function getDemangledType()

---

opm/input/eclipse/Schedule/Well/PAvgCalculator.cpp
opm/input/eclipse/Schedule/Well/PAvgCalculatorCollection.cpp
opm/input/eclipse/Schedule/Well/PAvgDynamicSourceData.cpp

PAvgXXX: instantiate for float

---

msim/src/msim.cpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp
tests/parser/ACTIONX.cpp

Schedule::applyActions: handle float wellpi map

---

opm/input/eclipse/Schedule/MixingRateControlKeywordHandlers.cpp
opm/input/eclipse/Schedule/OilVaporizationProperties.cpp
opm/input/eclipse/Schedule/OilVaporizationProperties.hpp
opm/input/eclipse/share/keywords/900_OPM/D/DRSDTCON
tests/parser/ScheduleTests.cpp

Most importantly drsdtcon can now be deactivated locally by setting first item to < 0

Support multiple pvt regions for drsdtcon

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/io/eclipse/rst/state.cpp
opm/io/eclipse/rst/state.hpp
opm/output/eclipse/CreateInteHead.cpp
opm/output/eclipse/DoubHEAD.cpp
opm/output/eclipse/InteHEAD.cpp
opm/output/eclipse/InteHEAD.hpp
opm/output/eclipse/VectorItems/doubhead.hpp
opm/output/eclipse/VectorItems/intehead.hpp

Only DRSDT, not DRSDTR for now.

Add restart support for DRSDT

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Well/WellEnums.cpp
opm/input/eclipse/Schedule/Well/WellEnums.hpp
opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp

Set WHISTCTL mode after restart.

WHISTCTL restart

---

python/generate-pypi-package.sh
python/requirements.txt
python/setup.py.in

for some reason the previously used 'grab all them files' doesn't include the summary directory so we have to force it by generating a MANIFEST.in file.

Fix python packaging

---

jenkins/build.sh
jenkins/update-opm-tests.sh

Ref https://github.com/OPM/opm-simulators/pull/4627

remove opm-models from jenkins downstream list

---

opm/material/eos/PengRobinsonParams.hpp

Quell warnings, https://ci.opm-project.org/job/opm-common/2225/gcc/source.1cb34c86-2306-4321-912c-908268b4e1e6/#93

PengRobinsonParams: initialize members

---

external/resinsight/LibCore/cvfObject.h
msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
opm/input/eclipse/Schedule/KeywordHandlers.cpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/io/eclipse/SummaryNode.cpp
opm/output/eclipse/AggregateActionxData.hpp
opm/output/eclipse/AggregateNetworkData.cpp
opm/output/eclipse/EclipseGridInspector.cpp
opm/output/eclipse/report/WELSPECS.cpp
test_util/EclFilesComparator.cpp
test_util/EclFilesComparator.hpp
test_util/convertECL.cpp
tests/parser/ScheduleTests.cpp
tests/test_EclIO.cpp

A small drip of addressing static analyzer analytics.

Static analyzers: Address some parameter-can-be-const analytics

---

opm/input/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
opm/input/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
opm/material/fluidstates/BlackOilFluidState.hpp
opm/material/fluidsystems/BlackOilFluidSystem.cpp
opm/material/fluidsystems/BlackOilFluidSystem.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/BrineH2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp
opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityBrinePvt.hpp
opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityOilPvt.hpp
opm/material/fluidsystems/blackoilpvt/ConstantCompressibilityWaterPvt.hpp
opm/material/fluidsystems/blackoilpvt/DeadOilPvt.hpp
opm/material/fluidsystems/blackoilpvt/DryGasPvt.hpp
opm/material/fluidsystems/blackoilpvt/DryHumidGasPvt.hpp
opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/GasPvtThermal.cpp
opm/material/fluidsystems/blackoilpvt/GasPvtThermal.hpp
opm/material/fluidsystems/blackoilpvt/H2GasPvt.hpp
opm/material/fluidsystems/blackoilpvt/LiveOilPvt.hpp
opm/material/fluidsystems/blackoilpvt/OilPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/OilPvtThermal.hpp
opm/material/fluidsystems/blackoilpvt/WaterPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/WaterPvtThermal.hpp
opm/material/fluidsystems/blackoilpvt/WetGasPvt.hpp
opm/material/fluidsystems/blackoilpvt/WetHumidGasPvt.hpp
opm/output/eclipse/Summary.cpp

-- added mixing model for thermal blackoil
-- TEMP is now set energy=enthalpy
-- THERMAL use enthalpy and energy different
This is draft pullrequest befor all commits are removed.

Blackoilthermal fixes final

---

opm/common/utility/Serializer.hpp

And remove dune 2.6 workaround

Fix serializer - don't pass nullptr to packers

---

external/resinsight/LibCore/cvfObject.cpp
external/resinsight/LibCore/cvfSystem.cpp
external/resinsight/LibGeometry/cvfBoundingBoxTree.cpp
external/resinsight/LibGeometry/cvfRay.cpp
opm/common/utility/parameters/ParameterGroup.cpp
opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
opm/input/eclipse/Parser/Parser.cpp
opm/input/eclipse/Schedule/BCProp.cpp
opm/input/eclipse/Schedule/Source.cpp
opm/input/eclipse/Schedule/UDQ/UDQActive.cpp
opm/input/eclipse/Schedule/UDQ/UDQFunction.cpp
opm/input/eclipse/Schedule/Well/PAvgCalculator.cpp
opm/io/eclipse/EclOutput.cpp
opm/json/JsonObject.cpp
opm/output/eclipse/AggregateMSWData.cpp
test_util/EclRegressionTest.cpp
tests/parser/UDQTests.cpp
tests/parser/WLIST.cpp

Some more low hanging fruits..

More janitoring to address static analyzer analytics

---

opm/input/eclipse/EclipseState/Tables/Tables.cpp

fixed: assign to correct member

---

opm/input/eclipse/EclipseState/Grid/NNC.cpp

fixed: copy-paste error in serialization test method

---

opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.cpp
opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/OilPvtMultiplexer.cpp
opm/material/fluidsystems/blackoilpvt/OilPvtMultiplexer.hpp
opm/material/fluidsystems/blackoilpvt/WaterPvtMultiplexer.cpp
opm/material/fluidsystems/blackoilpvt/WaterPvtMultiplexer.hpp

Slightly less code to build over and over. Also initialize member, avoid const qualifier on functions returning values,
simplify implementation of mixingEnergy() and mark it const.

(Gas|Oil|Water)PvtMultiplexer: move more code to translation unit

---

opm/input/eclipse/EclipseState/Tables/EzrokhiTable.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp
tests/test_Serialization.cpp

Two hard to detect c/p bugs. That's why we want tests!

Fix ezrokhi in parallell

---

opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp

fixed: only one liquidMixType_ required

---

opm/material/constraintsolvers/PTFlash.hpp

fixed: increase iteration count

---

opm/material/constraintsolvers/PTFlash.hpp

with the master branch, the test introduced in https://github.com/OPM/opm-models/pull/845 can not run through with the SSI + Newton PTFlash method. The major reason is because it enters the Newton solution process with 0 or 1 valued L (single phase).
Through bounding the Lmin and Lmax between 0. and 1., it looks running fine now.  Maybe more strict criteria need to be check whether we should jump into the Newton method.

improving the SSI + Newton PTFlash method 

---

opm/input/eclipse/Schedule/VFPProdTable.cpp
opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp
opm/material/common/PolynomialUtils.hpp

fixed: add missing throw for exceptions

---

opm/input/eclipse/EclipseState/Grid/FieldData.cpp
opm/input/eclipse/EclipseState/Grid/FieldData.hpp
opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
tests/parser/FieldPropsTests.cpp

Support COPY for FieldData with global storage.

---

opm/input/eclipse/Schedule/Well/WellCompletionKeywordHandlers.cpp

Currently a warning with 'well is not connected to the grid' is output if any connection is not connected to the grid. With this PR there is only a warning if the well is unconnected after the entire COMPDAT record is processed.

Avoid erroneous messages of wells not connected to the grid

---

opm/input/eclipse/Deck/UDAValue.hpp
opm/input/eclipse/Schedule/Action/Actions.cpp
opm/input/eclipse/Schedule/Group/GConSale.cpp
opm/input/eclipse/Schedule/Group/GConSump.cpp
opm/input/eclipse/Schedule/Well/WINJMULT.hpp
opm/input/eclipse/Schedule/Well/WellPolymerProperties.cpp
opm/input/eclipse/Utility/Typetools.hpp

Some drive-by removal/additions of headers

Some header cleanups

---

opm/input/eclipse/Schedule/Well/FilterCake.hpp

(reset from WellFilterCake in opm-simulators)

Make sf_multiplier mutable to be able to reset it 

---

opm/common/utility/numeric/MonotCubicInterpolator.hpp

MonotCubicInterpolator: initialize members

---

opm/material/common/UniformTabulated2DFunction.hpp

If change in https://github.com/OPM/opm-utilities/pull/86 passes through we need another ctor that accepts nested arrays instead of just nested vectors. For now both generated tables use the same dimensions so this is hardcoded right now for simplicity.

Make pvt tables nested arrays instead of vectors

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/ScheduleState.cpp

aids debugging as it makes it easy to comment out entries without having to edit other lines

changed: reformat a couple of comparison operators

---

opm/input/eclipse/Schedule/CompletedCells.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQParams.cpp

Fix some mostly harmless but inconsistent serialization issues

Fix some serialization issues

---

opm/input/eclipse/Schedule/CompletedCells.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQParams.cpp

Fixes some mostly harmless but inconsistent serialization issues
---
Back-ports PR #4286 to the release branch for OPM 2024.10.

Fix some parallel object serialization issues

---

opm/material/fluidsystems/BlackOilFluidSystem.hpp

The `is_mixing` object indirectly detected that function `internalEnergy()` was being used only on the supported gas, oil, and water phases.  Be more explicit about this by adding a default clause to the phase switch.

Revise Phase Logic for Internal Energy

---

opm/material/components/CO2.hpp
opm/material/components/CO2Tables.hpp

Remove include of config.h in header and some unrelated cosmetics.

fixed: never include config.h in a header

---

opm/input/eclipse/Schedule/Schedule.cpp
tests/test_Restart.cpp

Address some static analyzer noise.

Use standard algorithms instead of raw loops

---

opm/input/eclipse/EclipseState/Runspec.hpp
opm/input/eclipse/Schedule/ScheduleDeck.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
opm/input/eclipse/Schedule/ScheduleTypes.hpp

Quell some more static analyzer noise

add missing initialization

---

external/resinsight/LibCore/cvfPlane.h
external/resinsight/LibCore/cvfTimer.h
external/resinsight/LibGeometry/cvfBoundingBoxTree.cpp
external/resinsight/LibGeometry/cvfBoundingBoxTree.h
external/resinsight/LibGeometry/cvfRay.h
opm/common/OpmLog/TimerLog.hpp

Quell some static analyzer issues

add missing overrides

---

external/resinsight/ReservoirDataModel/RigHexIntersectionTools.cpp
external/resinsight/cafPdmCore/cafSignal.cpp
external/resinsight/cafPdmCore/cafSignal.h
opm/input/eclipse/EclipseState/Grid/TranCalculator.cpp
opm/input/eclipse/EclipseState/Grid/TranCalculator.hpp
opm/input/eclipse/Schedule/RSTConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQParser.cpp
opm/io/eclipse/ESmry.cpp
opm/io/eclipse/rst/state.cpp
opm/material/common/ConditionalStorage.hpp
opm/material/common/UniformTabulated2DFunction.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLaw.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
opm/material/fluidmatrixinteractions/EclStone1Material.hpp
opm/material/fluidmatrixinteractions/EclStone2Material.hpp
opm/material/fluidmatrixinteractions/EclTwoPhaseMaterial.hpp
opm/material/fluidmatrixinteractions/LinearMaterial.hpp
opm/material/fluidmatrixinteractions/NullMaterial.hpp
opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterial.hpp
opm/material/fluidmatrixinteractions/RegularizedBrooksCorey.hpp
opm/material/fluidmatrixinteractions/TwoPhaseLETCurves.hpp
opm/material/fluidsystems/BlackOilFluidSystem.cpp
opm/output/eclipse/AggregateNetworkData.cpp
tests/test_Restart.cpp

A mixed bag of static analyzer warnings

Various static analyzer analytics

---

opm/input/eclipse/Schedule/Well/WellMatcher.cpp

Use Std::Move()

---

opm/input/eclipse/Schedule/Action/ActionContext.cpp
opm/input/eclipse/Schedule/Action/ActionContext.hpp

Switch to using `reference_wrapper<>` to manage the borrowed objects and use `string_view` as parameter types where possible.
While here, add Doxygen-style documentation to the member functions and data members.

Refurbish Action::Context Implementation

---

docs/man1/arraylist.1
docs/man1/co2brinepvt.1
docs/man1/compareECL.1
docs/man1/convertECL.1
docs/man1/opmhash.1
docs/man1/opmpack.1
docs/man1/rst_deck.1
docs/man1/summary.1
examples/co2brinepvt.cpp
test_util/compareECL.cpp

Someone should double check the units documented in co2brinepvt.1  These seem to have changed since previous releases.

Update manpages for release

---

docs/man1/arraylist.1
docs/man1/co2brinepvt.1
docs/man1/compareECL.1
docs/man1/convertECL.1
docs/man1/opmhash.1
docs/man1/opmpack.1
docs/man1/rst_deck.1
docs/man1/summary.1
examples/co2brinepvt.cpp
test_util/compareECL.cpp

Back-ports PR #4297 to the release branch for the OPM 2024.10 release.

Update manual pages for release

---

opm/common/utility/Serializer.hpp
opm/common/utility/Visitor.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerHystParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerInitParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp

Here I am 100% sure that these are fixes.

Fix the obvious typos in the license specifications.

---

opm/input/eclipse/Schedule/Network/NetworkKeywordHandlers.cpp

using std::string instead of const char*

---

opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQKeywordHandlers.cpp

This commit adds support for using the special name selector '?' in well level UDQ assignments within an ACTIONX block.  In particular, we now support ACTIONX blocks like
ACTIONX
TESTW 25 1 /
DAY > 10 AND /
WMCTL '*PROD?' = 0 /
/
UDQ
ASSIGN WU_TEST '?' 1 /
/
ENDACTIO
in which the selector `'?'` represents all wells from all well lists matching the well list template `'*PROD?'` for which the `WMCTL` is zero, meaning the well is shut.
To this end, make a tiny wrapper inside `UDQConfig` for
Action::Result::MatchingEntities
that provides a way to forward those entities into
UDQConfig::add_record()
without making `UDQConfig` itself depend on `Action::Result`.  We then add a new private member function
UDQConfig::add_assign_wellvar()
that knows how to forward dynamically selected well names …

Support Dynamic Well Names in UDQ Assignments in ACTIONX Blocks

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/io/eclipse/rst/group.cpp
opm/io/eclipse/rst/group.hpp
opm/output/eclipse/AggregateGroupData.cpp
opm/output/eclipse/AggregateGroupData.hpp
opm/output/eclipse/LoadRestart.cpp
opm/output/eclipse/Summary.cpp
opm/output/eclipse/VectorItems/group.hpp

Support summary vectors GGCR, GGIMR, GGCT, GGIMT, FGCR, FGIMR, FGCT, FGIMT + restart i/o.

Support gas consumption/import summary output and restart i/o

---

opm/input/eclipse/EclipseState/SimulationConfig/ThresholdPressure.cpp

https://github.com/OPM/opm-simulators/pull/5743

Issue a warning if THPRES is present in a restart run

---

opm/input/eclipse/Schedule/Action/ActionResult.cpp
tests/parser/ACTIONX.cpp

The result set intersection logic in commit c2a9d2f9d (PR #4340) failed to properly separate the cases of a match set not being applicable&ndash;e.g., in the case of a field level scalar condition&ndash;and a match set being empty.  This matters when there are multiple clauses being combined with the conjunction `AND`.  In that case the overall condition may be satisfied, but there may be no single well (or group) that satisfies all clauses whence the resulting match set should be empty.  The initial "empty set" handling might then, erroneously, pick the match set of the last clause.
This commit amends the empty set logic by marking the `wells_` as `optional<>`.  We now treat `nullopt` as "not applicable" and a non-null, but empty, match set as a true empty set the intersection by which …

Properly Distinguish Empty from Not Applicable Match Set

---

opm/input/eclipse/share/keywords/000_Eclipse100/G/GCONINJE

Needed for https://github.com/OPM/opm-common/pull/4346

Avoid setting UDAs to 0 default in GCONINJE

---

opm/material/binarycoefficients/Brine_CO2.hpp

Gives a minor speedup to this code (10+ % faster assembly).

Avoid unneeded calls to pow() and log().

---

cmake/Modules/FindHYPRE.cmake

Accompanying PR to https://github.com/OPM/opm-simulators/pull/5762.
I have attempted to make this support using Hypre from the system packages (e.g. apt install libhypre) and local installations. Note that for GPU support, a local installation from source is the only alternative.

Add FindHYPRE.cmake file

---

opm/input/eclipse/Deck/Deck.cpp
opm/input/eclipse/Deck/Deck.hpp
opm/input/eclipse/Deck/DeckItem.hpp
opm/input/eclipse/Deck/DeckView.cpp
opm/input/eclipse/Parser/ErrorGuard.cpp
opm/input/eclipse/Parser/raw/RawRecord.cpp
opm/input/eclipse/Parser/raw/StarToken.cpp
opm/input/eclipse/Parser/raw/StarToken.hpp
opm/input/eclipse/Schedule/ArrayDimChecker.cpp
opm/input/eclipse/Schedule/MSW/WelSegsSet.cpp
opm/input/eclipse/Utility/Typetools.hpp
opm/io/eclipse/RestartFileView.hpp
opm/output/eclipse/CreateInteHead.cpp
opm/output/eclipse/WriteRPT.hpp
opm/output/eclipse/report/WELSPECS.cpp

Add some, remove some.
Credit @magnesj

Janitoring: some header cleanups

---

cmake/Modules/FindAMGX.cmake

Accompanying PR to https://github.com/OPM/opm-simulators/pull/5808.

Add FindAMGX.cmake file

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
opm/input/eclipse/Parser/ErrorGuard.cpp
opm/input/eclipse/Schedule/Action/ActionParser.hpp
opm/output/eclipse/Tables.cpp

Some small fixes to improve portability and compiler compatibility.

Janitoring: address some portability issues

---

opm/input/eclipse/Deck/DeckTree.cpp
opm/input/eclipse/Deck/FileDeck.cpp
opm/input/eclipse/EclipseState/IOConfig/IOConfig.cpp
opm/input/eclipse/Parser/Parser.cpp
opm/io/eclipse/EGrid.cpp
opm/io/eclipse/ESmry.cpp
opm/io/eclipse/ESmry.hpp
opm/io/eclipse/ESmry_write_rsm.cpp
opm/io/eclipse/EclUtil.cpp
opm/io/eclipse/ExtESmry.hpp
opm/output/eclipse/EclipseIO.cpp

- use generic path format instead of native where appropriate
- add byteswap intrinsic for msvc

Add some changes required for ResInsight integration

---

opm/input/eclipse/Schedule/Group/Group.cpp
opm/input/eclipse/Schedule/Group/Group.hpp
opm/input/eclipse/Schedule/Network/NetworkKeywordHandlers.cpp

This PR is required by https://github.com/OPM/opm-simulators/pull/5754

group method to label if a group is an autochoke group

---

python/cxx/schedule.cpp

…, keeping backwards compatibility.
These are actually the report steps, so reportstep is correct, timestep is wrong.

 Change variable and function names with timestep in python class Schedule to reportstep

---

opm/input/eclipse/Schedule/Well/WCYCLE.cpp
opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp

a new block does not invalidate the previous ones. misunderstanding on my behalf..

fixed: WCYCLE keywords needs to be processed additively

---

opm/io/eclipse/rst/state.cpp

Converting the `char[8]`-valued elements of ZUDL to `std::string` will trim trailing blank spaces.  This, in turn, runs the risk of removing essential blanks which could turn the scalar summary vector
GEFF TEST
into (the undefined) UDQ set
GEFFTEST
which would create parse errors if included in the defining expression of a field level UDQ.
This is, in effect, the same problem as was handled for ZLACT (ACTIONX) in commit 091a508a9 (PR #3827), but we use different solution here.  Instead of going through `PaddedOutputString<8>`, we use an explicit field-width of 8 characters in the `fmt::format()` function call.  This is, hopefully, no less efficient than going through a loop over `PaddedOutputString<>`.

Don't Blindly Trim Trailing Blanks in UDQ Defintions

---

CMakeLists_files.cmake
opm/common/utility/ThreadSafeMapBuilder.hpp
tests/test_ThreadSafeMapBuilder.cpp

this is an utility class for building maps in openmp loops

added: ThreadSafeMapBuilder utility

---

CMakeLists_files.cmake
opm/material/common/FastSmallVector.hpp
tests/test_FastSmallVector.cpp

These changes were made with the intention of using FastSmallVector in another part of the code, but then I did not end up using it there. No need to waste them though, the improvements could be useful in other contexts.
Also added unit test, which was missing.

FastSmallVector improvements

---

opm/input/eclipse/EclipseState/Tables/SimpleTable.cpp
opm/input/eclipse/EclipseState/Tables/TableContainer.cpp
opm/input/eclipse/EclipseState/Tables/TableContainer.hpp
opm/input/eclipse/EclipseState/Tables/TableManager.cpp
tests/material/test_eclblackoilpvt.cpp

In particular
- Split some long lines
- Prefer in-place construction where possible
- Prefer `//` comments

Varnish SimpleTable Component

---

opm/input/eclipse/Units/UnitSystem.cpp
opm/input/eclipse/Units/UnitSystem.hpp
opm/input/eclipse/Units/Units.hpp
opm/output/eclipse/WriteInit.cpp
tests/parser/UnitTests.cpp

Writing THCONR to INIT

---

external/resinsight/ReservoirDataModel/cvfGeometryTools.cpp
external/resinsight/cafHexGridIntersectionTools/cafHexGridIntersectionTools.h
opm/common/utility/numeric/GeometryUtil.hpp
opm/common/utility/numeric/VectorUtil.hpp
opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp

While here, also trim end-of-line whitespace.

Remove Needless Closing Brace Semicolons

---

opm/material/common/UniformTabulated2DFunction.hpp
opm/material/components/CO2Tables.hpp
opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterialParams.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp

connected to https://github.com/OPM/opm-simulators/pull/5980

Refactor make_view and copy_to_gpu

---

opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.cpp
opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.hpp

This class takes ownership of a loose voidptr provided in some constructors. This refactoring can make the class a bit more intelligible and easier to maintain as the ownership is now implied by the type.

Refactor gasPvtMultiplexer to use unique_ptr over loose void*

---

opm/input/eclipse/EclipseState/Runspec.cpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp
opm/material/fluidsystems/blackoilpvt/BrineH2Pvt.cpp

Removing/adding some line breaks for cosmetics. In addition, setting the output for co2/h2store conforming to deck units.

Improving terminal/dbg output

---

opm/input/eclipse/Schedule/Schedule.cpp

This commit amends the restart time handling of VREP groups different from the group itself to special case the FIELD group. Commit 092f0a2e7 (PR #4108) added the basic feature, but missed the subtle edge case that the FIELD group's restart file group index differs from the Schedule object's group index for FIELD.  More importantly, the PR reviewer overlooked this aspect as well.
This commit takes that distinction into account by adding a special case for FIELD that treats the voidage group index equal to the maximum number of groups in the field as FIELD itself.

Add Special Case Restart Handling for VREP Group FIELD

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
opm/input/eclipse/Schedule/ScheduleGrid.hpp

Janitoring: Remove newly introduced issues

---

opm/input/eclipse/Units/UnitSystem.cpp
opm/input/eclipse/Units/UnitSystem.hpp
opm/input/eclipse/Units/Units.hpp
tests/parser/UnitTests.cpp

to be used for pressure differences

added: dedicated pressure_drop measure

---

opm/output/eclipse/Summary.cpp

this is needed for RPTSCHED WELLS=2 output

add CWCT to list of extra connection vectors 

---

opm/material/constraintsolvers/PTFlash.hpp

This fixes the building In Sequoia 15.4, cmake 4.0.0, Apple clang version 17.0.0 (clang-1700.0.13.3).

Fix to broken build in macOS

---

opm/output/eclipse/Summary.cpp
opm/output/eclipse/Summary.hpp

for https://github.com/OPM/opm-simulators/pull/6132

using std::optional for initial inplace

---

opm/input/eclipse/Schedule/Source.cpp
opm/input/eclipse/Schedule/Source.hpp
tests/parser/SourceTests.cpp

I added this for some machine learning stuff, and now it broke. This PR restores the method, and thus my stuff.
Also some simplifications and cosmetics.

Source: Re-add the addSourceCell method

---

opm/input/eclipse/Schedule/ScheduleState.hpp

While here, also re-sort the include statements.
@multitalentloes: This PR is **not** intended for the 2025.04 release.

Remove Unused ScheduleState Members

---

opm/input/eclipse/Schedule/Group/GuideRate.cpp
opm/input/eclipse/Schedule/Group/GuideRate.hpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/Well/WellTestConfig.cpp
opm/input/eclipse/Schedule/Well/WellTestConfig.hpp

less code requires less mantenance potentially.

removing something not used or not defined even

---

opm/input/eclipse/Schedule/MSW/WellSegments.cpp

fixed: depth and length parameters were swapped

---

opm/input/eclipse/Schedule/MSW/WellSegments.cpp

Regression tests produce the same results on my machine. All other tests pass, I consider this safe to merge for RC3.

backport of pr 4580

---

examples/networkgraph.cpp
opm/input/eclipse/EclipseState/Grid/CarfinManager.cpp
opm/input/eclipse/EclipseState/Grid/CarfinManager.hpp
opm/input/eclipse/EclipseState/Tables/TableSchema.cpp
opm/input/eclipse/EclipseState/Tables/TableSchema.hpp
opm/input/eclipse/Parser/Parser.cpp
opm/input/eclipse/Schedule/HandlerContext.cpp
opm/input/eclipse/Schedule/HandlerContext.hpp
opm/input/eclipse/Schedule/UDQ/UDQActive.hpp
opm/output/eclipse/AggregateNetworkData.cpp

and some drive-by tidy ups. First commit is an actual bug fix.

Janitoring: fix some static analyzer issues

---

opm/input/eclipse/Schedule/MSW/WellSegments.cpp
tests/parser/MultisegmentWellTests.cpp

with ABS mode.
it triggered attention from understanding the PR https://github.com/OPM/opm-common/pull/4580

we can handle multiple semgents per WELSEGS record

---

docs/man1/arraylist.1
docs/man1/co2brinepvt.1
docs/man1/convertECL.1
docs/man1/opmhash.1
docs/man1/opmpack.1
docs/man1/rst_deck.1
docs/man1/summary.1

No new functionality or changes in regression tests, safe to add for release

Backport of pr 4591

---

.github/workflows/manual_label_checker.yml

Also enable in this repo. As agreed in meeeting.

add github action for checking manual labels

---

opm/output/data/Wells.hpp

Before https://github.com/OPM/opm-simulators/pull/6238 was merged, several processes wrote output data for the same well in some cases.
After discussing with @vkip and @blattms, I've added this throw and warning to make sure a problem like this will not go unnoticed in the future.

Throw if two processes try to write different output data for the same well, warn if they try to write the same

---

opm/input/eclipse/Schedule/Well/WListManager.cpp

In particular, switch to an $O(N \log N)$ algorithm based on sorted indices instead of the current $O(N^2)$ approach.

Reduce Cost of WListManager::wells()

---

opm/input/eclipse/EclipseState/Tables/PvtxTable.cpp
opm/input/eclipse/EclipseState/Tables/PvtxTable.hpp

In particular
- Make `PvtxTable::init()` "protected"
- Prefer standard algorithms to raw loops
- Prefer `std::size_t`
- Split individual stages of `init()` into separate helper functions
- Add Doxygen-style function and data member documentation
This is in preparation of adding a stage that will expand missing undersaturated states.
We make `init()` "protected" because general client code has no way of meeting the function's requirements.  Only derived types are able to set the "schema" members prior to calling the function.

Varnish PvtxTable Implementation

---

opm/material/fluidmatrixinteractions/EclMaterialLawManagerInitParams.cpp

Hardly a big thing, but also very cheap to add..

multithread material parameter initialization

---

CMakeLists_files.cmake
opm/common/utility/SymmTensor.cpp
opm/common/utility/SymmTensor.hpp
opm/common/utility/VoigtArray.cpp
opm/common/utility/VoigtArray.hpp
tests/test_SymmTensor.cpp
tests/test_VoigtArray.cpp

These fundamental types will also be useful in the state classes in this repo so let's move them up the chain.

import VoigtArray and SymmTensor from opm-simulators

---

opm/input/eclipse/Schedule/Group/GroupKeywordHandlers.cpp

In current master GEFAC values entered after NODEPROP are not accounted for - this PR ensures GEFAC updates are also reflected in the network efficiencies.

Ensure GEFAC properly updates network efficiencies

---

opm/material/fluidsystems/BlackOilFluidSystem.cpp
opm/material/fluidsystems/BlackOilFluidSystem.hpp
opm/material/fluidsystems/BlackOilFluidSystemNonStatic.hpp
opm/material/fluidsystems/BlackOilFluidSystem_macrotemplate.hpp
opm/material/fluidsystems/blackoilpvt/GasPvtMultiplexer.hpp

Makes the code simpler and easier to understand.

Remove pointers from BlackOilFluidSystem.

---

opm/output/eclipse/WriteInit.cpp
tests/parser/LgrOutputTests.cpp
tests/test_AggregateWellDataLGR.cpp

Quell newly introduced analytics.

Janitoring: Quell some static analyzer analytics

---

opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
tests/parser/SummaryConfigTests.cpp

This PR adds logic to the RxFT (e.g., `ROFT`, `RGFTL`) summary node formation process to inspect the region indices involved and exclude any index pair for which at least one index exceeds the maximum supported region index.  Here, we define the maximum supported index as the maximum of the run's declared maximum FIP index (item 1 of the `REGDIMS` keyword) and the maximum active region index in a particular region set (`FIPNUM`, `FIPABC`, &c).
Suppose the maximum region index in `FIPNUM` is 3 and that `REGDIMS(1)` is 3 as well.  Before this PR, a summary request of the form
ROFT
1 2 /
1 3 /
2 3 /
1 4 /
4 5 /
/
possibly left over from an earlier version of the input deck, would generate an out-of-bounds index error in an internal data vector when evaluating the "1 4" or the "4 5" index …

Ignore RxFT Summary Vectors for OOB Regions

---

opm/input/eclipse/Units/UnitSystem.cpp
opm/input/eclipse/Units/Units.hpp
opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYADS
opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYADSS
opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYMAX
opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYSHLOG
opm/input/eclipse/share/keywords/000_Eclipse100/P/PLYVISC
opm/input/eclipse/share/keywords/000_Eclipse100/W/WPOLYMER
opm/input/eclipse/share/keywords/900_OPM/S/SKPRPOLY
tests/parser/integration/ScheduleCreateFromDeck.cpp

There is not density involved, it should be Concentration in the first place. 
Was thinking to merge the three concentrations, while decided that we need to agree first.  But the naming change of the PolymerDensity is a good thing to do.

renaming PolymerDensity to PolymerConcentration and using Salinity for the third item in WPOLYMER

---

opm/output/data/Wells.hpp

Communicate Connection Result's LGR Grid ID in Parallel

---

CMakeLists_files.cmake
opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/input/eclipse/EclipseState/Grid/Operate.cpp
opm/input/eclipse/EclipseState/Grid/Operate.hpp
opm/input/eclipse/share/keywords/000_Eclipse100/O/OPERATE
tests/parser/OperateTests.cpp

This PR aims to address the reported issue in https://github.com/OPM/opm-simulators/issues/4597

Consistent unit handling in OPERATE

---

.gitignore
opm/input/eclipse/EclipseState/Grid/MinpvMode.cpp
opm/input/eclipse/Schedule/UDQ/UDT.cpp

Fixing a warning in the UDT.cpp file and adding .DS_Store to .gitignore (macOS).

Fixing a warning and ignoring DS_Store files
