opm/input/eclipse/Schedule/ScheduleState.hpp
tests/parser/ScheduleSerializeTest.cpp
tests/test_Serialization.cpp

reduce hotness of GConSump.hpp by 92% (152 files, 13 files instead of 165)

ScheduleState.hpp: forward GConSump

---

opm/input/eclipse/Schedule/ScheduleState.hpp
tests/parser/ScheduleSerializeTest.cpp

reduces hotness of GConSale.hpp by 92% (151 files, 13 instead of 164)

ScheduleState.hpp: forward GConSale

---

opm/input/eclipse/Schedule/ScheduleState.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp

Reduces hotness of RFTConfig.hpp by 93% (153 files, 12 files instead of 165)

ScheduleState.hpp: forward RFTConfig

---

opm/input/eclipse/Schedule/MSW/SegmentMatcher.hpp
src/opm/input/eclipse/Schedule/MSW/SegmentMatcher.cpp

This way we can forward-declare the class and won't have include the `SegmentMatcher` header whenever we need to declare a function that takes or returns a `SegmentSet`.
Inspired by recent work by [at]akva2.

Pull SegmentSet Out to Main OPM Namespace

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
tests/test_Serialization.cpp

Reduces hotness of WellBrineProperties.hpp by 95% (276 files, 8 files instead of 284)

Well.hpp: forward WellBrineProperties

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
tests/parser/WellTracerTests.cpp

Reduces hotness of WellTracerProperties.hpp by 97% (276 files, 8 files instead of 284)

Well.hpp: forward WellTracerProperties

---

opm/input/eclipse/Schedule/UDQ/UDQState.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQState.cpp

The serialization code handles nested structures out of the box and does not need dedicated logic anymore.
While here, also move the serializationTestObject member function's implementation to the .cpp file.

Prefer Standard Serialization Mechanism for UDQState

---

opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/Well/Well.hpp

Forward declare structs as struct, not class, to silence warnings.

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Well/Well.cpp

Reduces hotness of Units.hpp by 54% (183 files, 155 files instead of 338)

Well.hpp: remove unnecessary Units.hpp include

---

CMakeLists_files.cmake
opm/material/thermal/EclThermalLawManager.hpp
src/opm/material/thermal/EclThermalLawManager.cpp

To encapsulate various types and avoid repeated compilation.

EclThermalLawManager: move code to separate compile unit

---

src/opm/input/eclipse/Schedule/Network/ExtNetwork.cpp

Master branch uses std::map::insert(), the new value will not be used if the node exists already.

we need to update the nodal pressure when a new NODEPROP is specified in the schedule

---

opm/input/eclipse/Schedule/UDQ/UDQSet.hpp
opm/input/eclipse/Schedule/UDQ/UDQState.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQSet.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQState.cpp

This is in preparation of adding UDQs at the segment level.  We will probably need to rethink the UDQ scalars and UDQ sets at some point, since the lookup and assignment operations become more expensive from adding this piece of information.
While here, also add containers for segment level UDQs to the UDQ state object.  These are currently unused, but adding them here simplifies follow-up work.

Add Numbered Item to UDQ Scalars

---

src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp

Terminal output before this commit:
```
[ 46%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp.o
/Users/dmar/Github/opm/opm-common/src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp:154:67: error: use 'template' keyword to treat 'getTable' as a dependent template name
const SgfnTable& sgfnTable = tableManager.getSgfnTables().getTable<SgfnTable>( satRegionIdx );
^
template 
/Users/dmar/Github/opm/opm-common/src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp:157:71: error: use 'template' keyword to treat 'getTable' as a dependent template name
const Sof2Table& sof2Table = tableManager.getSof2Tables().getTable<Sof2Table>( satRegionIdx );
^
template 
...
```

Fixing broken built in macOS

---

opm/input/eclipse/Schedule/UDQ/UDQAssign.hpp
opm/input/eclipse/Schedule/UDQ/UDQSet.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQAssign.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQSet.cpp
tests/parser/UDQTests.cpp

This PR adds support for constructing UDQ `ASSIGN` records for enumerated well items such as those encountered in UDQs at the segment level, e.g.,
```
ASSIGN SUSPECT PROD01    123.456 /
ASSIGN SUSPECT PROD02 17 654.321 /
```
We do not support this syntax quite yet, but this is a step on the way there.

Prepare for Handling UDQ ASSIGN for Segments

---

opm/input/eclipse/Schedule/UDQ/UDQDefine.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQDefine.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQEnums.cpp
tests/parser/UDQTests.cpp

Needed in order to support segment sets which, potentially, have both a well name pattern and a segment number.
This change also means that we now support *parsing* block (cell) UDQ sets like
```
BPR 11 22 33
```
and that, in turn, means we detect unsupported UDQ types later than we used to.  That also means that the error detection exception type changes, so update affected unit tests accordingly.
While here also rework the implementation of the `UDQDefine` constructor in order to construct `UDQDefine::m_tokens` in the initialiser list and move scalar value scattering out to a set of helper functions in preparation of adding support for segment level UDQs.

Recognise Numbers as Part of UDQ Set Selector

---

CMakeLists_files.cmake
opm/common/utility/MemPacker.hpp
opm/common/utility/Serializer.hpp
src/opm/common/utility/MemPacker.cpp
tests/test_Serialization.cpp

Make it a public header so it can be reused elsewhere.
This is a the start of a PR series enabling "perfect restart" of simulators.

changed: rename the packer used in test_Serialization to MemPacker

---

opm/common/utility/MemPacker.hpp

In the admittedly special case that `position` is equal to the buffer's `size()` and `n == 0`, then the expression
```C++
&buffer[position]
```
will index out of bounds.  Use the safer expression
```C++
buffer.data() + position
```
instead since that's valid when position <= size().
Detected by libstdc++'s debug mode (checked iterators).

Don't Index Out of Bounds in Vector

---

opm/common/ErrorMacros.hpp

The intend to define a marco which can be used for timing blocks in OPM.
- if successfully merged one can add  OPM_TIMEBLOCK for full coverage of main functions and OPM_TIMEBLOCK_LOCAL for small portions of code.
-  The consent has been used to time intensivequantities and linearsolvers in the experimental for flow_blackoil_fast

Added empty macro which can be used for timing with for example Tracy

---

src/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
tests/parser/FieldPropsTests.cpp

Not only the last keyword.
Note I'm rather blind on the details here, but it seems like a logical fix if multiple copies of the keyword is actually allowed in the spec.

fixed: process all MULTREGP entries in the deck

---

opm/input/eclipse/Schedule/SummaryState.hpp
src/opm/input/eclipse/Schedule/SummaryState.cpp
src/opm/output/eclipse/Summary.cpp

Enables easier access for UDQ/ACTIONX purposes.
While here, also move the `serializationTestObject()` member function's implementation to the .cpp file and reorder the member function implementations to match the declaration order in the header.

Add Separate SummaryState Data Member for Segment Level Values

---

opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/EclipseState/Aquifer/AquiferCT.cpp
src/opm/input/eclipse/EclipseState/Aquifer/Aquifetp.cpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp

We are not supporting AQUCT and AQUFETP as SCHEDULE keywords yet. They are only supported as keywords in SOLUTION section. 
But if in the DATA file, there are AQUCT and AQUFETP keywords in the SCHEDULE section, with the master branch, there will be unexpected effects in the results. 
In the master branch, we use the last keyword (`const auto& aqufetpKeyword = deck.get<AQUFETP>().back();`) in the DATA file to generate the AQUCT and AQUFETP aquifers.  If there are AQUCT and AQUFETP keywords in the SCHEDULE section, they will use the last one in the SCHEDULE and not considering the one in the SOLUTION section at all.
At the same time, the implementation in the master branch does not consider that multiple AQUCT or AQUFETP keywords can be input, and also only uses the last one, which is also …

throw when AQUCT and AQUFETP are used as SCHEDULE keywords

---

src/opm/output/eclipse/AggregateWellData.cpp

The water injection rate was missing from the Void Production Rate

Add WWVIR to VoidPRRate

---

opm/input/eclipse/EclipseState/Grid/FieldProps.hpp

The simulator supports HEATCR and HEATCRT but they where missing from the field prosps.

Add missing HEATCR and HEATCRT to props

---

opm/material/fluidmatrixinteractions/DirectionalMaterialLawParams.hpp
opm/material/fluidmatrixinteractions/EclDefaultMaterialParams.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
opm/material/fluidmatrixinteractions/EclMultiplexerMaterialParams.hpp
opm/material/fluidmatrixinteractions/EclStone1MaterialParams.hpp
opm/material/fluidmatrixinteractions/EclStone2MaterialParams.hpp
opm/material/fluidmatrixinteractions/EclTwoPhaseMaterialParams.hpp
opm/material/fluidmatrixinteractions/SatCurveMultiplexerParams.hpp

These need to be stored or restart won't be 'perfect'.

Restart serialization: add hysteresis parameters

---

src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp

```
/Users/dmar/Github/opm/opm-common/src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp:303:64: error: use 'template' keyword to treat 'getTable' as a dependent template name
const GsfTable& gsfTable = tableManager.getGsfTables().getTable<GsfTable>( satRegionIdx );
^
template 
/Users/dmar/Github/opm/opm-common/src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp:304:64: error: use 'template' keyword to treat 'getTable' as a dependent template name
const WsfTable& wsfTable = tableManager.getWsfTables().getTable<WsfTable>( satRegionIdx );
^
template
```

Fixing the broken build in macOS

---

opm/input/eclipse/EclipseState/IOConfig/IOConfig.hpp
src/opm/input/eclipse/EclipseState/IOConfig/IOConfig.cpp

returns the input directory
I couldn't find this recorded anywhere else (only in the deck). Please feel free to correct me if I missed something.

added: getInputDir in IOConfig

---

CMakeLists_files.cmake
opm/common/ErrorMacros.hpp
opm/common/TimingMacros.hpp
opm/material/fluidmatrixinteractions/EclMultiplexerMaterial.hpp
opm/material/fluidsystems/BlackOilFluidSystem.hpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
tests/material/test_fluidmatrixinteractions.cpp

My OCD twitched. Separation of concerns, no reason to pull in strings, exceptions, logging.

split out timing macros to separate header

---

src/opm/input/eclipse/Python/PythonInterp.cpp

This restores the ability to stop the simulator using ctrl-c when compiled with PyAction support.

fixed: disable python SIGINT signal handler for the embedded interpreter

---

src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp

This is in preparation of adding support for writing those objects to the restart file.  We need a consistent view of active aquifers for that purpose.

Preserve SCHEDULE Section AQUFLUX Objects Across Report Steps

---

src/opm/output/eclipse/ActiveIndexByColumns.cpp
tests/test_ActiveIndexByColumns.cpp

As mentioned in #2331, the restart file's enumeration of active cells connected to analytic aquifers follows a column-based scheme.  Recent work on compatibility prompted by real field models with the constant flux analytic aquifer type (see also PRs #3378 and OPM/opm-simulators#4429) has shown that the enumeration of the columns also must account for the horizontal model dimension (keyword `DIMENS`).  If `Nx >= Ny` (`DIMENS(1) >= DIMENS(2)`) then the columns are enumerated with the `J` index cycling faster than the `I` index.  On the other hand, when `Ny > Nx` the `I` index is supposed to cycle more quickly than the `J` index.
This PR guarantees that he innermost loop is always across the model layers while we ensure that the 'outer' loop always iterates over an index range that is at …

Enumerate Columns According to Horizontal Model Dimensions

---

src/opm/output/eclipse/ActiveIndexByColumns.cpp

This commit fixes the current broken built in clang
```
[ 15%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/output/eclipse/AggregateGroupData.cpp.o
/Users/dmar/Github/opm/opm-common/src/opm/output/eclipse/ActiveIndexByColumns.cpp:88:45: error: 'outer' in capture list does not name a variable
[&cartDims, &getIJK, outer, middle]
^
```

fix to broken built with clang

---

src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp

```C++
// TODO need to check if gas/water sg
```
I have done the check and indeed the first implementation was wrong...

fix cap-press GSF

---

opm/common/utility/Serializer.hpp

It also does not support `empty()`, either. Oh my...
Instead we use the old fashioned way of checking the size and then either return the address of the first element or a `nullptr`.
Closes OPM/opm-simulators#4472 if also OPM/opm-grid#633 is merged.

Do not use FieldVector::data() mehod as it misses from DUNE 2.6.

---

opm/input/eclipse/EclipseState/Aquifer/AquiferFlux.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
opm/output/eclipse/AggregateAquiferData.hpp
opm/output/eclipse/InteHEAD.hpp
opm/output/eclipse/VectorItems/aquifer.hpp
src/opm/input/eclipse/EclipseState/Aquifer/AquiferFlux.cpp
src/opm/output/eclipse/AggregateAquiferData.cpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/EclipseIO.cpp
src/opm/output/eclipse/InteHEAD.cpp
src/opm/output/eclipse/RestartIO.cpp
tests/test_AggregateAquiferData.cpp

We support constant flux aquifers (`AQUFLUX` keyword) entered both in the `SOLUTION` and in the `SCHEDULE` sections.  The primary structural change is that we have to support analytic aquifers being introduced dynamically, whence the connection information (`xCAQ`) must be captured without knowing the full set of analytic aquifers.  We therefore allocate those output arrays purely from the maximum sizes entered in the `RUNSPEC` section whereas we defer determining the maximum aquifer ID to the point of capturing the dynamic values.
The `xAAQ` values for constant flux aquifers amount to a new aquifer type integer value (=2) in `IAAQ[11]` and the flux value in `SAAQ[0]`.  When running the [`AQFLUX-01`]() example model we now get the following values in `SAAQ[0]`.  These correspond to the …

Add Restart File Output Support for Constant Flux Aquifers

---

opm/material/common/quad.hpp

In general we'd need to link to dune-common (`target_link_library`) to get the appropriate include directories for Dune in that case, but in this specific instance we can get by with not specialising Dune's `className` function if Dune is not available.
Thanks to [at]akva2 for suggesting this workaround.

Restore Builds With Dune in Non-Default Installed Locations

---

opm/input/eclipse/EclipseState/Aquifer/AquiferFlux.hpp
opm/io/eclipse/rst/aquifer.hpp
opm/output/data/Aquifer.hpp
src/opm/input/eclipse/EclipseState/Aquifer/AquiferFlux.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/io/eclipse/rst/aquifer.cpp
src/opm/output/eclipse/LoadRestart.cpp

This PR adds logic and structures for bringing in constant flux aquifer objects&mdash;keyword `AQUFLUX`&mdash;from the restart file and forming the requisite dynamic objects in the `Schedule`.
In particular, the `RstAquifer` gets a new bare-bones representation of these aquifer types and we add new constant flux aquifer objects to the pertinent `ScheduleState` when these exist.  We also add this aquifer type to `data::Aquifers` in preparation of reinitialising the simulator's aquifer container from the restart file.  In particular, this needs the total produced volume from the aquifer so far.

Load Constant Flux Aquifer Objects from Restart File

---

opm/input/eclipse/EclipseState/Tables/FlatTable.hpp
opm/input/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/input/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/input/eclipse/EclipseState/Tables/Tables.cpp
src/opm/input/eclipse/share/keywords/001_Eclipse300/D/DIFFCGAS
src/opm/input/eclipse/share/keywords/001_Eclipse300/D/DIFFCWAT
src/opm/input/eclipse/share/keywords/keyword_list.cmake
src/opm/material/fluidsystems/BlackOilFluidSystem.cpp
tests/parser/TableManagerTests.cpp

This make it possible to specify diffusion coefficients for CO2STORE cases using the DIFFCGAS and DIFFCWAT keywords for gas-water cases. For gas-oil + co2store you will still need to use the DIFFC keywords. Note that if neither of these keywords are used by DIFFUSE is active the simulator will use default values computed based on temperature and pressure in the reservoir using correlation in the literature.

Support DIFFCGAS and DIFFCWAT for the CO2STORE module

---

opm/input/eclipse/EclipseState/SimulationConfig/BCConfig.hpp
src/opm/input/eclipse/EclipseState/SimulationConfig/BCConfig.cpp

With the THERMAL option the temperature is kept constant at the given boundary by allowing for heat conduction only. In other words no fluid flow only heat.

add THERMAL option to BC

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
opm/input/eclipse/EclipseState/Grid/TransMult.hpp
src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
tests/parser/EclipseGridTests.cpp

This is needed to prevent creation of NNCs if  the empty gap created by pinched out cells is larger than this threshold.

EclipseGrid: make option 3 (MAX_EMPTY_GAP) of PINCH available

---

src/opm/input/eclipse/EclipseState/Aquifer/AquiferCT.cpp
src/opm/input/eclipse/EclipseState/Aquifer/Aquifetp.cpp

This reverts commit a89136f1f24c9886fb335b99b93dad23fc815628.
Partly to fix https://github.com/OPM/opm-tests/issues/938 .
The original commit did not consider that AQUCT and AQUFETP can be `GRID` and `PROPS` keywords also.

Revert "only using the AQUCT and AQUFETP in SOLUTION section"

---

opm/input/eclipse/EclipseState/Grid/NNC.hpp
src/opm/input/eclipse/EclipseState/Grid/NNC.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/E/EDITNNCR
tests/parser/integration/NNCTests.cpp

If there is an EDITNNCR entry and a NNC entry for the same cell pair then the the corresponding NNC entry is removedas it will be overwritten anyway.
If there is an EDITNNC entry and an EDITNNCR entry for the same cell pair then the EDITNNC entry is removed while internalizing EDITNNCR.
Order matters for EDITNNCR entries in the sense that later specified values will overwrite previous entries when we internalize.
Note that similar to EDITNNC only the first 7 options are represented and the rest is ignored by OPM flow.
Note that EDITNNCR entries for neighboring cells are ignored (like for EDITNNC).
When actually storing the entries of EDITNNCR we treat them as NNCs internally. Hence we should be able to activate EDITNNCR in opm-simulators with out adding code actually handling EDITNNCR …

Internalize EDITNNCR keyword and make it available with the other NNC information.

---

src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
tests/parser/ScheduleTests.cpp

The PR aims at solving a issue reported by @vkip . 
In the case,  the well setup related to the issue is as follows, 
```
WCONPROD
'PROD-2'   'SHUT'  'RESV'  4*  0.0 1.0 1* 0 1.0 5* /
/
DATES
1 'FEB' 2000 /
/
WELOPEN
'PROD-2' 'OPEN'  5* /
/
WELTARG
'PROD-2' 'RESV'  2000.0 /
/
-- 31.000000 days from start of simulation ( 1 'JAN' 2000 )
DATES
1 'JUN' 2000 /
/
```
With the master branch, FLOW will not be able to open the well `PROD-2` with WELOPEN, since the well `PROD-2` disallows crossflow and also has a zero rate constraint. And WELOPEN does not consider the later `WELTARG` is changing the rate constraint to be non-zero. 
In this PR, we let us WELOPEN open the well without checking the rate constraint and crossflow specification.  Then we have two options to go after this. 
1.  the …

not forbidding WELOPEN wells with zero rate and disallowing crossflow

---

CMakeLists_files.cmake
external/resinsight/LibCore/cvfTrace.cpp

I am experiencing undefined references for g++-12  without it
```
/usr/lib/ccache/c++ -g -O2 -ffile-prefix-map=/build/opm-common-2023.04~git20230412.8473d9b8e+ds=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -pipe -fopenmp -pthread -Wl,-z,relro CMakeFiles/ACTIONX.dir/tests/parser/ACTIONX.cpp.o -o bin/ACTIONX  -Wl,-rpath,"/build/opm-common-2023.04~git20230412.8473d9b8e+ds/obj-x86_64-linux-gnu/lib" lib/libopmcommon.so.2023.04 /usr/lib/x86_64-linux-gnu/libfmt.so.9.1.0 /usr/lib/x86_64-linux-gnu/libpython3.11.so /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0 /usr/lib/x86_64-linux-gnu/libcjson.so /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.74.0 /usr/lib/gcc/x86_64-linux-gnu/12/libgomp.so /usr/lib/x86_64-linux-gnu/libpthread.a …
```

Added missing file for grid independent well specification.

---

CMakeLists.txt

It is needed as we will call pybind11_add_module which calls python3_add_library (in recent pybind11 versions). That function is only there if the development component is searched for and found.
Note that the issue is not there for older pybind11 version (pre 2020 without the file pybind11NewTools.cmake)
I hope this does not break anything with older versions. 
Leaving it to the release manager whether to port this to the release. IMHO that might make sense, though.
Closes #3475

Always search for Development component of Python.

---

CMakeLists.txt

It is needed as we will call pybind11_add_module which calls python3_add_library (in recent pybind11 versions). That function is only there if the development component is searched for and found.

Backport #3478: Always search for Development component of Python.

---

opm/input/eclipse/Schedule/UDQ/UDQDefine.hpp
opm/input/eclipse/Schedule/UDQ/UDQToken.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQDefine.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQToken.cpp

this went unnoticed since there are no UDQDefines in the pre-simulation Schedule broadcast for parallel. however it causes issues for serialized restarts

fixed: missing serialization of tokens in UDQDefine

---

opm/input/eclipse/Parser/ParseContext.hpp
src/opm/common/utility/OpmInputError.cpp
src/opm/input/eclipse/Parser/ParseContext.cpp
src/opm/input/eclipse/Schedule/Group/Group.cpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
tests/parser/GroupTests.cpp
tests/test_OpmInputError_format.cpp

This relaxes the restriction on parents. Also moves the handling of this to the ParseContext system, and (only somewhat related) makes it clear that mixing wells and groups as children of a single group (which is still forbidden) is a user input error, not an internal error.
Requires https://github.com/OPM/opm-simulators/pull/4608 downstream.

Allow FIELD group as parent for wells

---

opm/input/eclipse/EclipseState/SimulationConfig/RockConfig.hpp
opm/input/eclipse/EclipseState/Tables/FlatTable.hpp
src/opm/input/eclipse/EclipseState/SimulationConfig/RockConfig.cpp
src/opm/input/eclipse/EclipseState/Tables/Tables.cpp
tests/parser/SimulationConfigTest.cpp
tests/parser/TableManagerTests.cpp

This PR adds the expected behaviour for all-defaulted records in `ROCK`, provided the all-defaulted records are not the first of the keyword.  Similarly to, e.g. `PVTW`, all-defaulted records are treated as copies of the immediately preceding record.
In other words, given
```
ROCK
-- REF. PRES   COMPRESSIBILITY
280.000        5.6E-5 /
/
```
the second record is supposed to be a copy of the first.

Implement Proper Record Copying Behaviour for ROCK

---

python/CMakeLists.txt
python/generate-pypi-package.sh
python/pyproject.toml
python/setup-docker-image.sh
python/setup.py.in

the vanilla setup-tools doesn't get the triplet correctly for some reason. also use cmake from pip as cmake 3.16 in the image has a bug in the python find rule.
after exhaustive searching i gave up beating setuptools into behaving and just went for skbuild. it's a bit naughty since it needs a dummy cmakelists but this works at least.

changed: build python wheels using skbuild

---

python/CMakeLists.txt
python/generate-pypi-package.sh
python/pyproject.toml
python/setup-docker-image.sh
python/setup.py.in

the vanilla setup-tools doesn't get the triplet correctly for some reason. also use cmake from pip as cmake 3.16 in the image has a bug in the python find rule

Backport #3490: changed: build python wheels using skbuild

---

CMakeLists.txt

The change to unconditionally search for Development broke the pypi builders. The reason is that the manylinux2014 docker images used to build does not contain the embedding headers.
Since this is more correct in general, I opted to fix it like this instead of hackery in the pypi builder.
Also remove outdated check for setuptools. No longer required, only used for the pypi builder and that checks this thoroughly on its own.

Python: avoid searching from Development.Embed unless required

---

opm/input/eclipse/Schedule/MSW/WellSegments.hpp
opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/MSW/WellSegments.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/output/eclipse/CreateInteHead.cpp

The `[IR]SEG` and `ILB[RS]` arrays must be able to accommodate the maximum number of segments and branches used in the run.  This PR incorporates the dynamic maximum sizes.  If those sizes exceed the maximum values entered in `WSEGDIMS`, then the resulting restart file will not be fully compatible with other simulation software.

Dimension Segment Related Restart Arrays According to Dynamic Size

---

src/opm/input/eclipse/Schedule/ArrayDimChecker.cpp

That way, they could become reusable for other keywords and we can exploit the commonality between MAXWELLS and MAXGROUPS.  Moreover, we can reduce the visual clutter of the body of each checking function and fix some singular/plural mismatches in the diagnostic messages.

Split WELLDIMS Error Message Formatting Out to Helper Functions

---

opm/common/utility/numeric/cmp.hpp

Don't rely on clients using
```C++
#include <string.h>
```
before including `cmp.hpp`.

Use Memcmp From Standard Namespace

---

jenkins/build-opm-module.sh

There are no gpu's on jenkins. Use test labels to disable them.

jenkins: do not execute GPU tests

---

src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/input/eclipse/share/keywords/001_Eclipse300/W/WELL_PROBE_COMP
src/opm/input/eclipse/share/keywords/keyword_list.cmake

I can run https://github.com/OPM/opm-tests/pull/959 using this implementation. 
It parses: "WXMF", "WYMF", "WZMF", "WCGMR", "WCOMR" , but does not output anything.

Parse compositional summary keywords

---

opm/material/densead/EvaluationFormat.hpp

formatting should not be time critical. use the method instead of the template param. the template param is -1 for dynamically sized evaluations which means the formatter tries to allocate a very large array..

fixed: handle dynamically sized evaluations in {fmt} formatter

---

external/resinsight/LibCore/cvfVector4.inl

Found while analyzing output from static analyzers. Also sent upstream, https://github.com/OPM/ResInsight/pull/10256

fixed: do not compare index 2 twice

---

opm/material/fluidsystems/blackoilpvt/BrineH2Pvt.hpp

in particular the missing header broke build with -DNDEBUG.
due to https://github.com/OPM/opm-common/blob/master/opm/material/densead/Evaluation.hpp#L35 no longer saving our a*s.

BrineH2Pvt: include prerequisite headers

---

tests/material/test_tabulation.cpp

- adjust tolerances so the test actually pass
- convert to boost::test
i have no idea how sane this test is, but as-is is has a bunch of failed comparisons that only cause prints to the screen while the test still pass (just run ctest -V tabulation and see for yourself..)

test_tabulation: Some janitoring

---

src/opm/output/eclipse/Summary.cpp

then it should get a zero. otherwise, the old values will be used.
this is part of the investigation for a reported issue with @bska .

[testing] update summary quantities even there is no wells associated with it

---

tests/material/test_blackoilfluidstate.cpp

Not really a unit test as this only tests api conformance, but at least we have a better canvas for adding some actual tests.

test_blackoilfluidstate: convert to boost::test

---

opm/input/eclipse/EclipseState/Tables/GasvisctTable.hpp
opm/input/eclipse/EclipseState/Tables/TableManager.hpp
opm/material/fluidsystems/blackoilpvt/GasPvtThermal.hpp
opm/material/fluidsystems/blackoilpvt/WaterPvtThermal.hpp
src/opm/input/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/input/eclipse/EclipseState/Tables/Tables.cpp
src/opm/material/fluidsystems/blackoilpvt/GasPvtThermal.cpp
src/opm/material/fluidsystems/blackoilpvt/OilPvtThermal.cpp

GASVISCT is a E300 keyword and requires COMPS keyword. OPM current implementation would simply give this error:
That would happen because the implementation was trying to access the content of COMPS that was not there and there was no safeguard for that. 
I went ahead and implemented this keyword for a black-oil gas, considering we don't have support compositional formulation.  In the future it can be extended for compositional. 
Note, for now I just assumed references RV and RVW = 0, we could add these two parameters to the keyword VISCREF or create a new keyword for gas. What do you think @OPMUSER?
PS: I will add a test case in opm-tests today.

Implement GASVISCT for black-oil [Bug fix]

---

opm/input/eclipse/Schedule/Well/WellConnections.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Well/WellConnections.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/W/WELSPECS
src/opm/input/eclipse/share/keywords/900_OPM/C/COMPTRAJ
src/opm/input/eclipse/share/keywords/900_OPM/W/WELTRAJ

In this PR some defaults have been aded to the json files `COMPTRAJ` and `WELTRAJ`.
Furthermore `WELSPECS` json file is adjusted to allow defaults (`1*`) for `HEAD_I` and `HEAD_J`. With this change  of `WELSPECS` the (standard) well can fully be specified grid independent together with `WELTRAJ` and `COMPTRAJ` keywords.

adding defaults to json files

---

opm/input/eclipse/EclipseState/Runspec.hpp
opm/input/eclipse/Parser/ParseContext.hpp
src/opm/input/eclipse/EclipseState/Runspec.cpp
src/opm/input/eclipse/Parser/ParseContext.cpp
src/opm/input/eclipse/Schedule/ArrayDimChecker.cpp
tests/test_ArrayDimChecker.cpp

In particular, check that
1. Number of MS wells $\le$ WSEGDIMS(1)
2. Number of segments per well $\le$ WSEGDIMS(2)
3. Number of branches per well $\le$ WSEGDIMS(3)
for all report steps in the simulation run.
Example diagnostic message of a case that violates limits 2 and 3:
```
Error: Problem with keyword WSEGDIMS
In CASE.DATA line 60
The case has a multi-segmented well with 246 well segments, but at most 200 are allowed in WSEGDIMS.
Please increase item 2 of WSEGDIMS to at least 246
Error: Problem with keyword WSEGDIMS
In CASE.DATA line 60
The case has a multi-segmented well with 105 lateral branches, but at most 5 are allowed in WSEGDIMS.
Please increase item 3 of WSEGDIMS to at least 105
```
when running with `--parsing-strictness=high`.
---
To this end, also capture the originating …

Test Dynamic Segment Dimensions Against WSEGDIMS Limits

---

CMakeLists.txt

Mmh. That binary is from opm-material. While it was never installed there, we did install its man page (:flushed: Was me of course :grimacing:)
Closes #3474

Also install co2brinepvt as we install the manpage.

---

tests/parser/EmbeddedPython.cpp

In particular,
* Emit more useful diagnostic messages if a test fails
* Catch up to changing semantics of certain `Python` class member functions
* Handle the case of Python's `NumPy` module not being available
PR #3561 switched `Python::exec()` to return `false` instead of throwing an exception if the configuration does not have `EMBEDDED_PYTHON` so we must account for this in the corresponding unit test.

Fix Embedded Python Test

---

src/opm/input/eclipse/Schedule/Group/Group.cpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
tests/parser/GroupTests.cpp
tests/parser/ScheduleTests.cpp

This PR is to allow for default value `NONE` of item 7 of `GCONPROD`. So far only `RATE` was allowed for item 7 (see https://github.com/OPM/opm-simulators/pull/4593)

Allow NONE for item 7 in GCONPROD

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/Well/PAvgDynamicSourceData.hpp
src/opm/input/eclipse/Schedule/Well/PAvgDynamicSourceData.cpp
tests/test_PAvgDynamicSourceData.cpp

This commit adds a new container class,
```
PAvgDynamicSourceData
```
which wraps a single `vector<double>` which in turn backs source data items for
* pressure values
* fluid mixture densities
* dynamic pore-volumes
at a collection of source locations-active cells or well reservoir connections.  We provide read-only and read-write accessors to the underlying data items for a single source location through subscript operator (read only) and named assignment (`set()`, read-write) member functions.  The latter is available only when the underlying range of data values is mutable (e.g., `SourceDataSpan<double>`) as opposed to immutable (e.g., `SourceDataSpan<const double>`).

Add Container for Dynamic WBPn Source Values

---

opm/material/fluidmatrixinteractions/EclTwoPhaseMaterial.hpp
opm/output/data/Wells.hpp
opm/output/eclipse/Summary.hpp
src/opm/output/eclipse/Summary.cpp
tests/test_Summary_Group.cpp

In particular
* Tag a single argument constructor as `explicit`,
* Remove an unused private function
* Fix mismatched tags (`struct` vs. `class`) in forward declaration
* Return 'false' in an impossible `updateHyst()` case
While here, also use a real `UnitSystem` object instead of creating a METRIC system just to infer unit strings.

Fix A Couple of Compiler and Static Code Analysis Warnings

---

opm/material/fluidmatrixinteractions/EclDefaultMaterial.hpp

Added need function to use standalone ecldefault relperms. 
The intent is to be used with flowexperimental:flow_blackoil_fast, which can give significant speedup of property update.

-- added function need to test solver without multiplexer

---

src/opm/input/eclipse/EclipseState/Tables/Ppcwmax.cpp

Don't Narrow String Literal to Bool

---

opm/input/eclipse/Schedule/Well/PAvg.hpp
src/opm/input/eclipse/Schedule/Well/PAvg.cpp

Mostly for readability.  While here, also switch to using compiled item names instead of raw strings to access the DeckItems which constitute the WPAVE and WWPAVE keywords.
Split off from #3559.

Reformat PAvg Class

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/Well/Connection.hpp
opm/input/eclipse/Schedule/Well/WINJMULT.hpp
opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/Well/Connection.cpp
src/opm/input/eclipse/Schedule/Well/WINJMULT.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp

with more testing, it looks like when multiple records are entered. The records with WREV mode and records with CIRR and CREV modes work differently in term of overwriting the previous records. So it is necessary to store them separately.

separating the WINJMULT for well and connections

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/Well/PAvgCalculator.hpp
opm/input/eclipse/Schedule/Well/PAvgCalculatorCollection.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Well/PAvgCalculator.cpp
src/opm/input/eclipse/Schedule/Well/PAvgCalculatorCollection.cpp
tests/parser/PAvgTests.cpp
tests/test_PAvgCalculator.cpp

This PR implements the `WPAVE` keyword and its associate WBPn well level report quantities.  We support all valid settings of `WPAVE` and `WWPAVE`.  The various weighted averages are accumulated through compensated summation of both the numerator and denominator terms for the inner block, the direct/immediate level 1 neighbours, and the diagonal level 2 neighbours.  We combine those contributions to the `WBP`, `WBP4`, `WBP5`, and `WBP9` terms when we "commit" the contributions (`Accumulator::commitContributions()`), per connection for values weighted by the connection transmissibility factor, and per well for values weighted by pore volumes.
We distinguish `OPEN` from `ALL` connections through callback functions in the implementation of `accumulateLocalContributions()` and the per …

Reimplement WBPn Calculation Procedure

---

msim/src/msim.cpp
tests/msim/test_msim_ACTIONX.cpp

The MSIM `report_step` is a [one-based index](https://github.com/OPM/opm-common/blob/d6ed5f754c60ee053601ea63ae6dab7b5c6b2b9f/msim/src/msim.cpp#L60) so we must subtract one before looking up the pertinent `Schedule` information.

Fix MSIM UDQ Configuration Lookup

---

src/opm/input/eclipse/Parser/Parser.cpp

```
Error: Unknown keyword: KEY6
Error: Unrecoverable errors while loading input: Problem with keyword
In <memory string> line 0
Unknown keyword: KEY6
```
does not tell the user where his/her error is.
This is now changed to
```
Error: Unknown keyword: KEY6
Error: Unrecoverable errors while loading input: Problem with keyword NE6
In /path/to/include/grid/file.inc line 7
Unknown keyword: KEY6
```
which gives the user a greater chance of finding out what is wrong.

Provide file and line for errors because of unknown keywords.

---

external/resinsight/LibCore/cvfTrace.cpp

Not sure how we should maintain this external code in principle, but avoiding a build warning should be ok I think.

Fix warning from external code.

---

src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
src/opm/input/eclipse/EclipseState/Grid/GridDims.cpp
src/opm/input/eclipse/Parser/Parser.cpp

An include directive with a path with trailing whitespace, e.g.
```
INCLUDE
'/home/model/../include/file_trailing_ws.ext ' /
```
would produce the following error currently:
```
Error: No such file: /home/model/../include/file_trailing_ws.ext
```
The problem is really hard to detect for the user. As it seems that other simulators always trim these strings we now do the same and allow the above input.

trim trailing and leading whitespace of paths in INCLUDE

---

opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
src/opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp

I bug was introduced in https://github.com/OPM/opm-common/pull/3433 that neglected the input salinity

BUGFIX: Use salinity values when salt concentration (BRINE) is not considered

---

opm/output/data/Wells.hpp
src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SEGMENT_PROBE
src/opm/output/eclipse/Summary.cpp

This PR adds the requisite backing storage and parser support for capturing and transporting simulator-level calculation of 
phase and mixture density value for purpose of summary file output.  To this end, make `SegmentQuantity` into a template on a set of defined items and make `SegmentPhaseQuantity` into a specialisation of this template.  Add a new specialisation, `SegmentPhaseDensity`, which holds phase densities (oil, gas, water), and fluid mixture densities with and without flowing fraction exponents.
These will be used to transport the values needed to output segment level summary vectors
* SDENx -- Phase density of phase 'x' (O, G, W)
* SDENM -- Fluid mixture density without flowing fraction exponents
* SMDEN -- Fluid mixture density with flowing fraction exponents

Add Transport Protocol for Segment Level Phase Densities

---

src/opm/input/eclipse/EclipseState/Tables/TableManager.cpp

This PR fixes missing location information in the table-related code

Fix table-related error messages

---

src/opm/output/eclipse/Summary.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

This PR hooks the WBPn result vectors up to the summary file writing process.

Emit WBPn Summary Vectors to Summary Result File

---

opm/input/eclipse/Schedule/Action/SimulatorUpdate.hpp
opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp

This commit adds a new member, well_structure_change, to the `SimulatorUpdate` structure.  The member defaults to `false`, but will be set to `true` if an `ACTIONX` block contains at least one of a select group of keywords that affect the model's well topology.
In particular, set this member to `true` if the `ACTIONX` block has at least one of the keywords
- COMPDAT
- WELOPEN
- WELSPECS
This will enable adding simulator logic to open or create wells in the middle of a report step.

Add Facility for Recording ACTIONX Well Structure Changes

---

opm/io/eclipse/EclFile.hpp
opm/io/eclipse/EclUtil.hpp
src/opm/io/eclipse/EclFile.cpp
src/opm/io/eclipse/EclUtil.cpp

Without the include compilation fails with
```
/opm/io/eclipse/EclFile.hpp:92:17: error: ‘uint64_t’ was not declared in this scope
92 |     std::vector<uint64_t> ifStreamPos;
|                 ^~~~~~~~
In file included from src/opm/io/eclipse/EclOutput.cpp:20:
opm/io/eclipse/EclUtil.hpp:56:5: error: 'uint64_t' does not name a type
56 |     uint64_t sizeOnDiskBinary(int64_t num, Opm::EclIO::eclArrType arrType, int elementSize);
|     ^~~~~~~~
```

Added missing include of cstdint for GCC-13

---

opm/material/constraintsolvers/PTFlash.hpp

Previously we did read and write out of bounds as num_equations might be bigger than numComponents. For GCC-13 this even caused endless loops.
Closes #3603

[bugfix] Use numComponents when accessing K_/moleFractions_ in PTFlash.

---

opm/common/Exceptions.hpp

Indeed that is more intuitive. I guess the previous name was due to copy & paste and forgetting to change things afterwards.
should be merged together with OPM/opm-simulators#4756

Rename LinearTimeSteppingBreakdown to TimeSteppingBreakdown

---

opm/material/fluidmatrixinteractions/EclTwoPhaseMaterial.hpp
opm/material/fluidmatrixinteractions/EclTwoPhaseMaterialParams.hpp

quell unused parameter warnings

---

tests/parser/GroupTests.cpp

I noticed this while reading https://github.com/OPM/opm-common/pull/3609 
I'm fine with that going in first.

GroupTests: use raw string literals

---

opm/input/eclipse/Deck/DeckSection.hpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/input/eclipse/EclipseState/checkDeck.cpp
src/opm/input/eclipse/Parser/Parser.cpp
tests/parser/SectionTests.cpp
tests/parser/integration/CheckDeckValidity.cpp

That will make those (e.g. EDITNNC in the GRiD section) fatal. In addition we now also check (region) operations on keywords such as
```
MULTIPLY
'TRANX' 2.0 /
'TRANY' 4.0 /
/

Register errors concerning section topology in ErrorGuard.

---

opm/input/eclipse/Schedule/Network/ExtNetwork.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Network/ExtNetwork.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
tests/parser/NetworkTests.cpp

Nodes with default properties do not need any NODEPROP entries and can be implicitly created by being referred to in BRANPROP. This fixes a bug where such cases would cause an exception.
Creating as draft until test case has been added.

Allow implicit creation of production network nodes.

---

opm/material/components/H2.hpp
tests/material/test_components.cpp

The new implemented model is the same as used by NIST and Coolprop. It improves the accuracy significantly compared to the old model (much lower tolerance in unit tests).

Improved gas viscosity model for hydrogen

---

opm/common/TimingMacros.hpp

To make it easier for people to use tracy. Currently only simulators (downstream coming) is setup to use it.

TimingMacros: add definitions for using tracy

---

opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
src/opm/input/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp

These are not directionally dependent, and they have a unit string of `Pressure`.  This didn't use to matter, but upcoming changes
will depend on the unit string being correct.
While here, also tidy up an unused array left over from commit 146be0aa2 (PR #1749), and take care to remove a macro definition so that it does not escape the file in which it is defined.

Properly Classify Capillary Pressure Keywords

---

opm/input/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
src/opm/input/eclipse/EclipseState/Grid/MULTREGTScanner.cpp

A numeric index serves the same purpose as a pointer in this very specific instance and also has the benefit of being easily transferable between processes.  This, in turn, means we can remove the 'getSearchMap()' and 'constructSearchMap()' member functions.

Switch to Numeric Indices for Record References

---

opm/input/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
src/opm/input/eclipse/EclipseState/Grid/MULTREGTScanner.cpp

This PR replaces the data members `nx`, `ny`, and `nz` with a copy of the `GridDims` object passed as an argument to the constructor.  In turn, this enables using `GridDims::getIJK()` to compute the cell's IJK tuple from its global Cartesian index instead of implementing the same calculation locally (and incorrectly).
While here, also include the layer index (K) in determining whether or not a connection is an NNC, and do this just once instead of once for each MULTREGT record.  Cells (I,J,K) and (I,J,K+3) might be connected across pinched-out layers and for the purposes of MULTREGT that connection should be treated as an NNC.

Use Existing Cartesian-to-IJK Functionality to Determine NNCs in MULTREGT

---

src/opm/io/eclipse/ESmry_write_rsm.cpp

We use log10 of the value to compute the scale factor. This only makes sense for positive values. For zero it returns -HUGE_VAL and for negative values it returns nan where supported.
Unfortunately on some platforms (e.g. mips64el) further operations in nan resulted in values so large that the scale factors were to large for the columns. This resulted in invalid_argument exceptions in strtod which were hard to debug. Out of pure luck on many platforms the scale factors still were zero in this case.
To fix this we now always use a scale factor 0 for values less or equal to zero. This fixes e.g. Debian packages on mips64el.
In addition we now make sure that printed scale factors have less characters than the column width. Otherwise parsing the *.RSM file might fail because of throwing …

Pevent undefined behavior of ESMry scale factors for values <=0.

---

src/opm/output/eclipse/WriteInit.cpp

we want to match the commercial simulator here

fixed: restore order of 'standard' fields in init file

---

src/opm/input/eclipse/EclipseState/Aquifer/AquiferHelpers.cpp
src/opm/input/eclipse/EclipseState/Aquifer/AquiferHelpers.hpp
src/opm/input/eclipse/EclipseState/Aquifer/NumericalAquifer/SingleNumericalAquifer.cpp

since we forcefully make numerical aquifer cells active. If a connection cells is neighboring a numerical aquifer cell, we should create NNC for this connection.   The current code will not create the NNC connection because it is a numerical aquifer cell is considered to be an active cell and the connection will be considered as connecting two active cells.

not considering numerical aquifers cells inside reservoir

---

src/opm/input/eclipse/Schedule/MSW/Compsegs.cpp

Perform the connection-depth-from-segments calculations even if the segment number is specified.

Avoid connection depth = 0 when segment is specified without depth in COMPSEGS

---

opm/input/eclipse/Schedule/Tuning.hpp
opm/output/eclipse/VectorItems/doubhead.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp
src/opm/input/eclipse/Schedule/Tuning.cpp
src/opm/io/eclipse/rst/state.cpp
src/opm/output/eclipse/DoubHEAD.cpp
src/opm/output/eclipse/LoadRestart.cpp
tests/parser/TuningTests.cpp

Facilitates using max time step from TUNING.TSINIT or NEXTSTEP only when specified.
Also fixes persistent NEXTSTEP behavior by triggering tuning events at all report steps until persistence is turned off again. 
Updated TuningTests.cpp accordingly

TUNING/NEXT[STEP]: Facilitate using max time step only when specified

---

opm/input/eclipse/Parser/Parser.hpp
src/opm/input/eclipse/Parser/Parser.cpp
tests/parser/ParserTests.cpp

This PR adds targeted support for identifying keywords whose names exceed the maximum compatibility keyword length limit.  This, in turn, enables seamless recognition of extension keywords such as
```
STRESSEQUILNUM
```
without compromising the parser's ability to identify long keyword names that match existing keywords in the first eight characters. For example, the input string `GUIDERATE` will still match the keyword `GUIDERAT` (without the trailing "E") and will not be accidentally treated as a SUMMARY section request to output a group level UDQ vector.
To this end split keyword recognition into two parts.  The 'base' checks that the input string looks like a valid keyword and, if so, matches the string against the builtin set of known keywords.  The full keyword recognition process …

Recognise Extension Keywords Whose Names Exceed Size Limits

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/Group/GroupEconProductionLimits.hpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
src/opm/input/eclipse/Schedule/Group/GroupEconProductionLimits.cpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/G/GECON
tests/parser/GroupTests.cpp
tests/parser/ScheduleSerializeTest.cpp
tests/test_Serialization.cpp

Implements support for the GECON keyword. Note that restart IO support has not been added yet. See also companion PR https://github.com/OPM/opm-simulators/pull/4819 in opm-simulators for more information.

Implement support for GECON keyword

---

opm/input/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.hpp
src/opm/input/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.cpp
tests/parser/AquiferTests.cpp

This commit adds a new, focused, member function
```
NumericalAquifers::allAquiferCellIds()
```
which returns a vector of those Cartesian/global cells that have been marked as defining the model's numerical aquifers through the `AQUNUM` keyword.  We intend to use this to identify those NNCs that go to numerical aquifers&ndash;or between numerical aquifer cells&ndash;as those may need special treatment when processing the `MULTREGT` keyword.

Add Method for Identifying Numerical Aquifer Cell IDs

---

opm/input/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
src/opm/input/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
tests/parser/MULTREGTScannerTests.cpp

In particular, reorder the functions in the implementation file, mostly to group related functions and have the same order in the
declaration and the implementation files.  While here, also replace an `enum` with a strong `enum` since the type does not need to support arithmetic operations.
Finally, fix an error in the handling of the "default" region set.  Keyword `MULTREGT` has an independent default region set ([`MULTNUM`](https://github.com/OPM/opm-common/blob/a0e72a62c4790ed78910391a393bf9e1bc9347d9/src/opm/input/eclipse/share/keywords/000_Eclipse100/M/MULTREGT#L34)) and does not use the `GRIDOPTS`-based region set protocol of other `*REG` keywords.  Using that protocol ended up generating an input error when processing a description such as
```
MULTNUM
...
/
-- ...
MULTREGT
1 2 0.1 …
```

Tidy Up MULTREGT Scanner Implementation File

---

opm/material/viscositymodels/LBC.hpp
src/opm/input/eclipse/Generator/KeywordGenerator.cpp
src/opm/io/eclipse/EInit.cpp

These generate diagnostic messages from GCC at `-pedantic` levels.

Remove Unnecessary Semicolons on Closing Braces

---

opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp

Make it a warning instead of an error to specify an invalid control mode in WCONINJH. Motivated by the need to accept deck output that contain this error, that is generated by preprocessing tools.
The generated files may specify RESV, and the engineers expect this to be ignored, and the default (RATE) control being used instead.

Allow invalid WCONINJH control mode

---

opm/input/eclipse/Parser/ParserKeyword.hpp
src/opm/input/eclipse/Parser/ParserKeyword.cpp

This is mostly to have a general solution for matching region level summary keywords which may reference a user-defined region set (`FIP` keyword, e.g., `FIPXYZ`) through tags like
* `RPR__XYZ` &ndash; Average pressure in region, FIPXYZ region set
* `ROPR_XYZ` &ndash; Oil production rate in region, FIPXYZ region set
* `RODENXYZ` &ndash; Average oil density in region, FIPXYZ region set
The initial approach introduced in commit cfbafc236 was limited to selected keywords.
To this end, add a new data member
```C++
std::string ParserKeyword::m_matchRegexSuffix
```
and introduce a new member function
```C++
bool ParserKeyword::matchesDeckNames()
```
which matches a candidate keyword string against the `m_deckNames`, and, if applicable, as a regular expression against `m_deckNames` when appended …

Support Regular Expression Suffix for Keyword Matching

---

opm/input/eclipse/EclipseState/Grid/MULTREGTScanner.hpp
opm/input/eclipse/EclipseState/Grid/TransMult.hpp
src/opm/input/eclipse/EclipseState/EclipseState.cpp
src/opm/input/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
src/opm/input/eclipse/EclipseState/Grid/TransMult.cpp
tests/parser/MULTREGTScannerTests.cpp

This PR implements the `NOAQUNNC` behaviour in member function
```C++
MULTREGTScanner::getRegionMultiplier()
```
We use a new data member `MULTREGTScanner::aquifer_cells` to identify connections to and within numerical aquifers and ignore those if the record stipulates `NOAQUNNC` behaviour.  This data member holds a sorted sequence of Cartesian/global cell indices corresponding to the cells which comprise the model's numerical aquifers.  These are needed to properly identify whether or not a connection&ndash;i.e., a cell pair&ndash;would constitute a "numerical aquifer connection" and be subject to `NOAQUNNC` treatment.
We assign the numerical aquifer cells as part of member function
```C++
EclipseState::conveyNumericalAquiferEffects()
```
which runs at `EclipseState` construction time. …

Implement NOAQUNNC Region Multiplier Behaviour in MULTREGT

---

opm/io/eclipse/SummaryNode.hpp
src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/io/eclipse/SummaryNode.cpp
src/opm/output/eclipse/Summary.cpp

Region level summary keywords may have suffixes which refer to user defined region sets (`FIP*` keyword).  This commit prunes those suffixes when performing function lookup, so that we do not get false negatives.
To this end, introduce a new helper function
```C++
EclIO::SummaryNode::normalise_region_keyword()
```
and use this both when determining the summary keyword type (rate, cumulative, pressure &c) and when looking up evaluation functions for region level summary vectors.  The new helper could arguably have been integrated into the existing `normalise_keyword()` helper function, but that would have necessitated a different change elsewhere in the code base.  For now, we keep this helper as a separate function.

Normalise Region Level Summary Keywords for Lookup Purposes

---

src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp

Computing geometric cell depths before proper initialization of the grid was not a good idea..

Fixing segfault due to use of uninitialized grid properties

---

src/opm/input/eclipse/EclipseState/Grid/MULTREGTScanner.cpp
tests/parser/MULTREGTScannerTests.cpp

If multiple records, from different region sets and region IDs--e.g., both regions 1/2 in `'M'` (`MULTNUM`) and regions 2/3 in `'F'` (`FLUXNUM`) applies to the same connection as might be the case in
```
MULTREGT
1 2  0.5  1*  'NNC'  'F' /
2 3  0.1  1*  'NNC'  'M' /
/
```
then the total multiplier value is the product of the values from each record.
This PR revises the region set loop to accumulate the total multiplier value instead of "just" returning the first match.

Accumulate Total Multiplier From All Region Sets

---

src/opm/output/eclipse/Summary.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

We calculate these, for now, as
```
WPIx = WOPR / (WBPx - WBHP)
```
but it is possible that we may have to revise this definition, especially for injectors.

Add Support for WPIx Summary Vectors

---

src/opm/output/eclipse/Summary.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

The simulator already calculates the requisite values, but due to the requisite summary keyword `RPRH` not being listed among the known region level vectors the output layer did not write the values to the summary file.  This PR adds the requisite table entry.

Emit Region Level Average Pressure Weighted by HC Volume

---

src/opm/input/eclipse/share/keywords/000_Eclipse100/R/REGION_PROBE
tests/parser/SummaryConfigTests.cpp

This PR switches the existing, somewhat spotty, support for matching region set tags on region level summary vector keywords. We leverage the recent support for `deck_name_regex_suffix` keys in the JSON keyword model&ndash;see PR #3673&ndash;to extend the keyword matching algorithm to also account for these region set tags.
There is a potential for false positives here, but we'll use this as an initial proof-of-concept implementation.

Support Region Set Tags For All Region Level Summary Vectors

---

opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
src/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
tests/parser/FieldPropsTests.cpp

This PR switches the region set tag matching algorithm to using unique prefixes.  This enables the parser to recognise that the summary vector
```
ROPR_UNI
```
should match up with the user defined region set `FIPUNIT`.  In the current master sources, the above summary vector would produce a diagnostic message saying that the region set `FIPUNI` (without the final `T`) does not exist.
We add a prefix-to-canonical region set name translation table to the `FieldProps` class and funnel all FIP-like requests through this translation table.  In the case of non-unique prefixes-e.g., `FIPUNIT` and `FIPUNIX`, we currently elect to have the last keyword entered in the simulation model "win".  This behaviour may be altered in the future if deemed appropriate/necessary.
Note: This is an alternative …

Match Region Sets by Unique Prefix

---

src/opm/output/eclipse/RegionCache.cpp
tests/test_regionCache.cpp

The simulator reports `data::Connection` objects tied to global Cartesian cell indices whence using the 'active_index' leads to match failures and incorrect rate attribution at the region level. In one field case we got region level rates and cumulatives, e.g., `ROPR` and `ROPT`, of zero reported to the summary file when the expected values should be non-zero.

Match Connection-to-Region in Terms of Global Cell Indices

---

src/opm/input/eclipse/Schedule/MSW/Segment.cpp

If one `WELSEGS` keyword does not redefine every existing segment, then we risk adding the same inlet segment multiple times.  If that happens, we get a segment structure for which there might appear to be multiple inlet segments on the same branch which is not possible in a tree structure.  This PR prevents that situation by only adding the new segment number if it is not already listed in `m_inlet_segments`.

Prevent Duplicate Inlet Segments

---

opm/input/eclipse/Schedule/MSW/Valve.hpp
opm/output/eclipse/AggregateMSWData.hpp
opm/output/eclipse/VectorItems/msw.hpp
src/opm/input/eclipse/Schedule/MSW/Valve.cpp
src/opm/output/eclipse/AggregateMSWData.cpp
tests/test_AggregateMSWData.cpp

The existing approach was a little too fragile in the light of unexpected segment/branch numbering schemes and would occasionally populate the output arrays in unexpected/inconsistent ways.  This issue was especially pronounced for the `ILBR` and `ILBS` arrays.
This new version switches to a strict depth-first search order of the segment tree, with the additional restriction that we search to the end (toe) of the current branch before starting to search the next branch.  Branches are enqueued in order of discovery.  To simplify the array references we also switch `AggregateMSWData::iLBR_` to a `WindowedMatrix<int>` and use named item indices instead of pure numeric values.
We also ensure to set the `ISEG` open/shut flag for valves (keyword `WSEGVALVE`).  This was missing in the earlier …

Fix Multiple Issues in MSW Output Array Creation Logic

---

src/opm/input/eclipse/Parser/Parser.cpp
tests/parser/integration/CheckDeckValidity.cpp

If there are errors at the top level (e.g. RUNSPEC comes after NOECHO), we might get very many errors and the user might miss the relevant ones on top.
To fix this we will now print those errors last just before exiting the simulator because of these errors.

Make top level section errors more prominent / Allow global keywords before RUNSPEC

---

msim/src/msim.cpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/UDQ/UDQASTNode.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQContext.hpp
opm/input/eclipse/Schedule/UDQ/UDQDefine.hpp
opm/input/eclipse/Schedule/UDQ/UDQSet.hpp
opm/io/eclipse/SummaryNode.hpp
src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/SummaryState.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQASTNode.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQContext.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQDefine.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQSet.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/S/SEGMENT_PROBE
src/opm/output/eclipse/Summary.cpp
tests/parser/UDQTests.cpp
tests/test_AggregateUDQData.cpp
tests/test_Restart.cpp

This commit adds support for calculating UDQs at the segment level, i.e., UDQs named 'SU*'.  This necessitates an API change for the UDQ context constructor and, transitively, every function that forms UDQ context objects.  We pass a factory function that will create segment matcher objects on demand, and provide a default implementation of this factory function in the Schedule class.
While here, also add support for outputting segment level UDQs to the summary file.  We calculate all segment level UDQs and add the values to the summary state for possible use in ACTIONXtoo.  The latter is not yet tested.

Compute Segment Level UDQ Values

---

opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQContext.hpp
opm/input/eclipse/Schedule/UDQ/UDQState.hpp
src/opm/input/eclipse/Schedule/ScheduleState.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQContext.cpp
src/opm/input/eclipse/Schedule/UDQ/UDQState.cpp
tests/parser/UDQTests.cpp

The existing implementation used the UDQ State object to track pending `ASSIGN` operations, mainly in terms of the report step index, but this implies that the logic implicitly assumes an `ASSIGN` operation can run at most once per report step.  That assumption usually holds, but fails if the `ASSIGN` operation is triggered from an `ACTIONX` block that happens to run multiple times within a report step.
This PR instead introduces a new data member,
```
UDQConfig::pending_assignments_
```
that keeps track of all `ASSIGN` operations that have been added for the current report step.  We clear those pending assignments when forming a new `Schedule` block (`ScheduleState` object), under the assumption that all pending `ASSIGN` operations have been affected at the previous time level (report …

Track Pending Assignments in UDQ Configuration Object

---

opm/input/eclipse/Schedule/Schedule.hpp

Fixes
```
/opm/input/eclipse/Schedule/Schedule.hpp:241:14: error: ‘function’ in namespace ‘std’ does not name a template type
241 |         std::function<std::unique_ptr<SegmentMatcher>()> segmentMatcherFactory(std::size_t report_step) const;
|              ^~~~~~~~
```
This should also fix the benchmarking on ytelses.com

Include missing functional header to fix compilation with g++-12

---

opm/input/eclipse/Schedule/Schedule.hpp
src/opm/input/eclipse/Schedule/Action/ActionX.cpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp

This adds support for WLIST in ACTION.
It is quite conservative in what is supported, in particular for now only WELOPEN is allowed to be processed for lists
that are empty until actions are processed. This should likely be extended to some more keywords before merge.

Add support for WLIST in ACTIONX

---

src/opm/input/eclipse/Schedule/SummaryState.cpp
tests/parser/UDQTests.cpp

Member function `SummaryState::update_udq()` did not take into account the possibility that wells or groups might not yet have come online. In particular, `UDQSet::operator[](const string&)` will [throw an exception](https://github.com/OPM/opm-common/blob/a4f9fb1dd855d7c9183b095f4b3194ae43786413/src/opm/input/eclipse/Schedule/UDQ/UDQSet.cpp#L496-L498) if the argument string does not name an existing member of the UDQ set.
This PR makes the call to `operator[]()` conditional on the named entity existing and thereby enables updating well and group level UDQs before these names have been entered in, e.g., `WELSPECS` or `GRUPTREE`.  Missing entities get the `undefined_value`.

Don't Reference Non-Existent W/G Names From UDQ Set

---

opm/input/eclipse/EclipseState/Runspec.hpp
src/opm/input/eclipse/EclipseState/Grid/SatfuncPropertyInitializers.cpp
src/opm/input/eclipse/EclipseState/Runspec.cpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp
src/opm/output/eclipse/Tables.cpp
tests/parser/FieldPropsTests.cpp

Although in the manual it is stated that SGWFN is supported, the simulator ends with
```
Simulation aborted as program threw an unexpected exception: Could not allocate the problem: Saturation functions must be specified using either family 1 or family 2 keywords
Use either SGOF (or SLGOF) and/or SWOF or SGFN/SWFN and SOF2/SOF3
```
This PR adds support for this keyword. It has been tested using the first table in [SGOF_R.INCL](https://github.com/OPM/opm-tests/blob/master/three_phase_relperm/SGOF_R.INCL) in two CO2STORE decks (the first one with GAS OIL SGOF and the second one with GAS WATER SGWFN (see attached zip)), giving the same results.
[Test_sgwfn_sgof.zip](https://github.com/OPM/opm-common/files/12860948/Test_sgwfn_sgof.zip)

Support for SGWFN sat functions (format type 2)

---

CMakeLists_files.cmake

to let other modules be able to access it.

adding ThreeComponentFluidSystem.hh to CMakeLists_files

---

src/opm/input/eclipse/Schedule/SummaryState.cpp
tests/parser/UDQTests.cpp

Backport of #3708
Member function SummaryState::update_udq() did not take into account the possibility that wells or groups might not yet have come online. In particular, UDQSet::operator[](const string&) will throw an exception if the argument string does not name an existing member of the UDQ set.
This commit makes the call to operator[]() conditional on the named entity existing and thereby enables updating well and group level UDQs before these names have been entered in, e.g., WELSPECS or GRUPTREE.  Missing entities get the 'undefined_value'.

Don't Reference Non-Existent W/G Names From UDQ Set (Release)

---

src/opm/output/eclipse/AggregateActionxData.cpp

backport of #3713 
The rest of the code allows an ACTIONX keyword without any condition (Such an action will never be evaluated). Yet AggregateActionXData assumed that there is always at least one condition. This lead to a segmentation fault if that was not the case.
It seemed like iAC[offset + Ix::FirstGreater] is used nowhere and therefore we now always use 0 there. I was not brave enouogh to remove the storage for it, because I fear this might break backwards compatibility of the output layer.

[fix] AggregateActionX: Do not assume an ACTIONX condition exists

---

CMakeLists_files.cmake
opm/common/utility/CSRGraphFromCoordinates.hpp
opm/common/utility/CSRGraphFromCoordinates_impl.hpp
opm/output/data/InterRegFlowMap.hpp
src/opm/output/data/InterRegFlowMap.cpp
tests/test_CSRGraphFromCoordinates.cpp

This commit extracts the internal helpers of class
```
InterRegFlowMap
```
out to a new public helper class template, `CSRGraphFromCoordinates`. Client code can, at the expense of one additional data member and some dynamic memory, elect to track the index pairs.  This enables O(1) assembly per element when used as part of a CSR matrix with a value array, SA.
Class `CSRGraphFromCoordinates` does not track values.  It is purely for the sake of forming the IA and JA structure arrays.  Upon calling `compress()`, column indices are sorted per row and duplicate column indices condensed to a single, unique, representative.

Extract Facility to Form CSR Representations of Graphs

---

opm/input/eclipse/Schedule/Events.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp

Some SCHEDULE keywords can set a well to be OPEN to open a reviouly STOP or SHUT well. The well is SHUT/STOP due to various causes (SCHEDULE, economical, physical, etc.) For now, the WELOPEN, WCONPROD and WCONINJE keywords are considered with this event. In the future, other keywords can be involved if found to have the similar OPENing functionality.
I was struggling the name of the event, any suggestions are welcome.

introducing a new event type REQUEST_OPEN_WELL

---

opm/common/utility/numeric/linearInterpolation.hpp

Remove tabs and reformat. And replace home-grown binary search with std::lower_bound.

linearInterpolation.hpp: reformat and use stl

---

cmake/Modules/OpmInit.cmake

Running simulations on those does not make sense as it seriously limits the time span that can be simulated. In addition the OPM code neglects 32bit issues at various places as it was written at a time where 64bit was already ubiquitous.
Currently, we would fail in some regression tests on 32bit systems. With this change CMake will already check whether it is run on a 64bit (or higher) system and already fail if this is not the case.
A patch I never upstreamed from Debian.

Make CMake fail on non-64bit systems.

---

opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/Well/Well.hpp
src/opm/input/eclipse/Schedule/KeywordHandlers.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
tests/parser/WellTests.cpp

This PR enables updating individual well properties for one or more wells using the `WELSPECS` keyword.  In particular, this revised logic enables changing the controlling group without affecting any other well property such as the location of the well head or the well reference depth.
Defaulted properties do not affect change in `Well::update*()`.  This, in turn, begets a change to the logic of how we update the reference depths.  Previously, we always interpreted a defaulted reference depth item as
> Compute the reference depth from the location of the well's reservoir connections
We now alter this interpretation slightly to mean
> Don't recompute the reference depth if the input has already assigned a numerical value for this property
If the input has never assigned an explicit …

Support Changing Selected Well Properties Through WELSPECS

---

opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp

This commit adds a new, very specialised, operation to the material law manager,
```C++
void EclMaterialLawManager::applyRestartSwatInit(cell, maxPcow)
```
This will apply a `SWATINIT`-like rescaling of the oil/water capillary pressure curve based on a caller-provided maximum capillary pressure value.  The primary use case is this maximum value being taken from the `PPCW` array in a restart file at simulation restart time.  We assign the `maxPcow` member of the associate `EpsInfo` structure and reinitialise the `EpsPoints` structure using this new information. The latter is needed lest the `maxPcnw()` function return incorrect values in restarted simulations.

Support SWATINIT-Like Rescaling of PCOW at Restart

---

opm/input/eclipse/Parser/ParseContext.hpp
opm/input/eclipse/Schedule/Action/ActionX.hpp
src/opm/input/eclipse/Parser/ParseContext.cpp
src/opm/input/eclipse/Schedule/Action/ActionParser.cpp
src/opm/input/eclipse/Schedule/Action/ActionX.cpp
src/opm/input/eclipse/Schedule/Schedule.cpp
tests/parser/ACTIONX.cpp

When encountering these (e.g. a number instead of an expression on the left hand side) the simulator would immediately abort with an error message like:
```
Error: An error occurred while creating the reservoir schedule
Internal error: Extra unhandled data starting with token[0] = 135
Error: Unrecoverable errors while loading input: Extra unhandled data starting with token[0] = 135
```
(The message above is for the number 135 on the left hand side)
With this change we now use the usual way of handling errors and warnings in the parser and continue parsing.
The error message for the problem above is now
```
Error: condition of action EX1 has the following error: Left side of comparsion (135) has to be an expression!
Error: Problem with keyword ACTIONX
In model.schedule line 562
condition …
```

Better error handling for problems in conditions of ACTIONX.

---

opm/common/utility/numeric/linearInterpolation.hpp

Error message concerning use of std::tie which needs <tuple> header, for g++ (Debian 12.2.0-14) 12.2.0. File: linearInterpolation.hpp, line 94.

Missing header for g++ 12.2.0

---

src/opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp

Fixed a bug where setting SATNUM in COMPDAT (option no. 7) to a value other than cell SATNUM resulted in Segmentation fault in two-phase cases. Now we check which two-phase approach is active and set correct rel. perm. parameters accordingly.

Fix well connection rel. perm. parameters for two-phase cases 

---

cmake/Modules/OpmSatellites.cmake

This also fixes the linker issue in https://github.com/OPM/opm-simulators/pull/4966

Fix to linker error in building tests (clang, macOS)

---

src/opm/input/eclipse/Schedule/KeywordHandlers.cpp

When first evaluating ACTIONX the WLISTS might not even exist. In addition they may be empty.
We support WLIST for the following well keywords in ACTIONX:
COMPDAT, COMPLUMP, WCONINJE, WCONPROD, WECON, WEFAC, WELOPEN, WELPI, WELSPECS, WELTARG, WGRUPCON, WPIMULT, WSEGVALV, WTEST, WTMULT,  WELSPECS
These keywords that probably allow WLIST, still insist they are never empty: WELTRAJ, COMPTRAJ, CSKIN, WCONHIST, WCONINJH, WFOAM, WINJMULT, WINJTEMP, WLIFTOPT, WMICP, WINJCLN, WINJDAM, WINJFCNC, WPMITAB, WPOLYMER, WSALT, WSEGSICD, WSEGAICD, WSKPTAB, WSOLVENT, WTEMP, WTRACER, WVFPDP, WVFPEXP, WWPAVE, WPAVEDEP, WRFT, WRFTPLT
These are currently not allowed in ACTIONX.

Support WLIST for all allowed well keywords in ACTIONX.

---

opm/input/eclipse/Schedule/ScheduleState.hpp

I can't see why the duplicate is necessary and it certainly is error prone upon adding new members.
The only reason I can think of for wanting two implementations would be if only non-mutable access is wanted for some member. This is not the case now though, so yeah...

ScheduleState: avoid duplicate const/mutable implementation

---

opm/input/eclipse/Units/UnitSystem.hpp
src/opm/input/eclipse/Units/UnitSystem.cpp

There is no need for these to require that the `UnitSystem` be mutable.

Make UnitSystem::*_si(string) Const Members

---

cmake/Modules/UseDamaris.cmake

In the current setup, `USE_DAMARIS_LIB` is set to `OFF` by default, but setting it to `ON` does not issue an error if Damaris is not found. This PR issues an error if `USE_DAMARIS_LIB==ON` and Damaris is not found.

Fail if Damaris is requested and not found

---

src/opm/input/eclipse/Schedule/KeywordHandlers.cpp

…for various schedule keywords. Facilitates using parsing strictness to determine behavior.

Let ParseContext handle what happens if no well match is found 

---

python/generate-pypi-package.sh

Now that we have a bumped pybind11 we can enable these two versions as well.
Part of #3658

pypi: build for python 3.11 and 3.12

---

opm/common/utility/CSRGraphFromCoordinates.hpp
opm/common/utility/CSRGraphFromCoordinates_impl.hpp
tests/test_CSRGraphFromCoordinates.cpp

This PR builds on the previous work in #3660 and adds a new class template argument,
```C++
bool PermitSelfConnections
```
with a default value of `false` to class template `CSRGraphFromCoordinates`.  This enables client code to configure whether or not function
```C++
void CSRGraphFromCoordinates::addConnection(VertexID v1, VertexID v2);
```
creates a connection from `v1` to `v2` if `v1 == v2`.  The default state preserves the current behaviour which ignores such connections.
Permitting self connections makes the class slightly more general to uses cases outside inter-region flow accumulation.

Make Self Connection Behaviour Configurable

---

opm/input/eclipse/Schedule/Well/Connection.hpp
src/opm/input/eclipse/Schedule/MSW/Compsegs.cpp
src/opm/input/eclipse/Schedule/Well/Connection.cpp
src/opm/input/eclipse/Schedule/Well/WellConnections.cpp

we should not dereference it for STDW where it is expected to be empty

fixed: pass through perf-range as an optional

---

tests/material/test_components.cpp

1.66 already has the boost::fpc scope
Well, this came back to bite me pretty quick. In EL8 boost 1.66 is in use...

fixed: adjust boost version check

---

cmake/Modules/DownloadFmt.cmake

rather than doing a full MakeAvailable, only download, prepare then use from source directory.
old approach caused some issues in certain build configurations.

fixed: refine the libfmt fetchcontent approach

---

cmake/Modules/DownloadFmt.cmake

have to check that it has not been populated before. we have to push two variables up to the parent scope

fixed: downloaded libfmt with a super build

---

opm/input/eclipse/Schedule/Group/GroupEconProductionLimits.hpp
src/opm/input/eclipse/Schedule/Group/GroupEconProductionLimits.cpp
src/opm/input/eclipse/Schedule/Group/GroupKeywordHandlers.cpp

Remove unneeded UnitSystem include and forward Schedule and SummaryState.

GroupEconProductionLimits: clean up includes

---

opm/output/eclipse/AggregateActionxData.hpp
src/opm/output/eclipse/AggregateActionxData.cpp
tests/test_AggregateActionxData.cpp

This PR is a quick-fix for a very peculiar problem in the `SACN` restart file output array.  We expect that a more complete fix will involve refactoring.  The problem is, that in conditions such as
```
MNTH >= FEB
```
in an `ACTIONX` condition block, the current master sources will unexpectedly interpret the leading `F` in `FEB` as introducing a field-level summary quantity (e.g., `FOPR`, `FPR`, or `FU_BAR`).  This, in turn, will lead to outputting a value of zero to the corresponding `SACN` item instead of the numerical month index for February (= 2).  When restarting a case with this erroneous specification the user will be greeted with an inscrutable diagnostic message, possibly referring to internal details of `std::unordered_map<>` (as retrieved from …

Hotfix for Month String 'FEB' Condition Restart Output Problem

---

opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp
opm/material/fluidsystems/blackoilpvt/H2GasPvt.hpp
tests/material/test_components.cpp

We assume that the density and the internal energy of the gas phase is not affected by the water content.
This avoid usage of gasDensity/gasInternalEnergy based on ideal gas assumptions implemented in simpleHuDuanH2O.hpp.
Add test that compares liquidEnthalpy of SimpleHuDuanH2O and H2O based on IAPWS

Fix invB from density in co2/h2 store and use density/internalEnergy from co2/h2 directly

---

src/opm/io/eclipse/rst/state.cpp

Converting the `char[8]`-valued elements of the `ZLACT` restart file array to `std::string` will trailing trim blank spaces.  In certain circumstances, this process will end up removing meaningful blanks and create run-on keyword data strings that can no longer be parsed in context.
As an example, the `ACTIONX` block
```
WPIMULT
'PROD1' 1.23456 3* 1 4 /
```
might be stored in `ZLACT` as
```
ZLACT[0]: "WPIMULT "
ZLACT[1]: "        "
ZLACT[2]: "\n      "
ZLACT[3]: "'PROD1' "
ZLACT[4]: "1.23456 "
ZLACT[5]: "3* 1 4 /"
```
Upon restart, the string conversion would then trim the trailing blanks and we would get the keyword specification
```
WPIMULT
'PROD1'1.234563* 1 4 /
```
which the restart parser object is unable to make sense of.  That, in turn, means that we might get a diagnostic message …

Do Not Blindly Remove Blanks in ZLACT

---

examples/make_ext_smry.cpp

The PR is improving program make_ext_smry with respect to robustness. The program will now check if number of time steps are in summary file is greater that 0 before trying to write an ESMRY file.

make_ext_smry update - check if time step data exists

---

src/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp

That way, in-place quantities will go through the short-to-canonical name translation in `FieldProps` regardless of their origin&ndash;e.g., `RPTSOL`/`RPTSCHED` or explicit `SUMMARY` section vectors.

Publish Short Region Set Names Only

---

opm/io/eclipse/rst/udq.hpp
src/opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
src/opm/io/eclipse/rst/udq.cpp

The current master sources implicitly assume that all UDQs loaded from the restart file have an `UPDATE` status of `ON`.  This commit allows the restart code to inspect the actual update status and to use that status in the UDQ configuration object when restarting the simulation run.
Closes #3808

Restore UDQ Update Status on Simulation Restart

---

opm/material/thermal/EclThermalLawManager.hpp
src/opm/material/thermal/EclThermalLawManager.cpp

To support local grid refinement, when the grid is a CpGrid with LGRs, the field properties for leaf grid view cells are inherited from parent cells or the equivalent coarse cell from level zero. For this reason, a new (function) argument has been added in some EclThermalMaterialLawManager members functions.
Closes #3825

Lookup the origin cell index when defining field properties on EclThermalLawManager

---

src/opm/input/eclipse/Deck/UDAValue.cpp
src/opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp
src/opm/input/eclipse/Schedule/Well/WellProductionProperties.cpp
tests/parser/DeckTests.cpp
tests/parser/GroupTests.cpp

Note: With this addition, the utility function 'bool is_udq(const std::string&)' is defined at five different locations (SummaryConfig.cpp, UDQState.cpp, UDQContext.cpp, UDQASTNode.cpp and now UDAValue.cpp). Would probably make sense to unify these? (indepent of this PR..)

Check if UDQ name is valid (not necessarily defined) when creating UDAs

---

tests/test_cubic.cpp

It looks the same in github, but in git on the command line I see a difference, and I get a compiler warning.
```
-//            B<E5>rd Skaflestad     <bard.skaflestad@sintef.no>
+//            Bård Skaflestad     <bard.skaflestad@sintef.no>
```

Fix encoding of file to silence warning.

---

opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerHystParams.cpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerInitParams.cpp
tests/material/test_eclmateriallawmanager.cpp

A function argument has been added in many member functions of EclMaterialLawManager(HystParams) to support LGRs. To main goal is to be able to assign the lookup index of a leaf grid view cell, which is the index of its parent or equivalent cell on level zero, when the grid is a CpGrid with LGRs.

Refactor HystParams to support LGRs

---

opm/input/eclipse/EclipseState/Grid/FaultCollection.hpp
src/opm/input/eclipse/EclipseState/EclipseState.cpp
src/opm/input/eclipse/EclipseState/Grid/FaultCollection.cpp
tests/parser/FaultTests.cpp

it matches the behavior of the reference simulator in that it truncates patterns at the asterisk. if truncation is necessary a warning is issued

added: support pattern matching in MULTFLT

---

opm/input/eclipse/Schedule/Well/Well.hpp
opm/io/eclipse/rst/header.hpp
opm/output/eclipse/VectorItems/intehead.hpp
src/opm/input/eclipse/Schedule/Schedule.cpp
src/opm/input/eclipse/Schedule/Well/Well.cpp
src/opm/io/eclipse/rst/header.cpp
tests/test_rst.cpp

The current master sources conflates history control with the `WHISTCTL` setting, thus failing to respect any control mode setting in `WCONHIST` in the case of simulation restart in the historic period.
This PR decouples any `WHISTCTL` setting (`INTEHEAD[71]`) from that of the control mode setting specified in `WCONHIST` thereby supporting both modes when a simulation is restarted in the historic period. This, in turn, fixes simulation restart on a real field.

Decouple WHISTCTL From History Control Setting on Restart

---

src/opm/input/eclipse/Units/UnitSystem.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/T/TABDIMS
src/opm/input/eclipse/share/keywords/001_Eclipse300/A/ACF
src/opm/input/eclipse/share/keywords/001_Eclipse300/B/BIC
src/opm/input/eclipse/share/keywords/001_Eclipse300/C/CREF
src/opm/input/eclipse/share/keywords/001_Eclipse300/C/CREFS
src/opm/input/eclipse/share/keywords/001_Eclipse300/D/DREF
src/opm/input/eclipse/share/keywords/001_Eclipse300/D/DREFS
src/opm/input/eclipse/share/keywords/001_Eclipse300/E/EOS
src/opm/input/eclipse/share/keywords/001_Eclipse300/E/EOSNUM
src/opm/input/eclipse/share/keywords/001_Eclipse300/M/MW
src/opm/input/eclipse/share/keywords/001_Eclipse300/M/MWS
src/opm/input/eclipse/share/keywords/001_Eclipse300/P/PCRIT
src/opm/input/eclipse/share/keywords/001_Eclipse300/P/PREF
src/opm/input/eclipse/share/keywords/001_Eclipse300/P/PREFS
src/opm/input/eclipse/share/keywords/001_Eclipse300/T/TCRIT
src/opm/input/eclipse/share/keywords/001_Eclipse300/T/TREF
src/opm/input/eclipse/share/keywords/001_Eclipse300/T/TREFS
src/opm/input/eclipse/share/keywords/001_Eclipse300/V/VCRIT
src/opm/input/eclipse/share/keywords/001_Eclipse300/X/XMF
src/opm/input/eclipse/share/keywords/001_Eclipse300/Y/YMF
src/opm/input/eclipse/share/keywords/001_Eclipse300/Z/ZFACT1
src/opm/input/eclipse/share/keywords/001_Eclipse300/Z/ZFACT1S
src/opm/input/eclipse/share/keywords/001_Eclipse300/Z/ZFACTOR
src/opm/input/eclipse/share/keywords/001_Eclipse300/Z/ZFACTORS
src/opm/input/eclipse/share/keywords/keyword_list.cmake

ACF, BIC, EOS, EOSNUM, PCRIT, TCRIT, VCRIT, XMF, YMF
Not necessarily all correct, but helping to have an overview when creating the keywords. 
Some adjustments are expected when actually implementing them.

add definitions of ACF, BIC, EOS, EOSNUM, PCRIT, TCRIT, VCRIT, XMF and YMF

---

src/opm/output/eclipse/report/WELSPECS.cpp

Without this fix, when requesting
```
RTPSCHED
'WELSPECS'
```
in the deck, the PRT and DBG files will have something that looks like this:
```
FIELD

GROUP1

 …
```

Use the correct string constructor.

---

opm/material/fluidsystems/ThreeComponentFluidSystem.hh

Compiler warns that dens may be returned uninitialized if the if-clause is false. As this is a two-phase gas and oil only class, the correct thing is to assert() on the phase index.

Replace if with assert in gas-oil only code.

---

bin/genEvalSpecializations.py
opm/material/densead/Evaluation.hpp

It was found when debugging a problem with NaN derivatives.

output the derivatives of the Evaluation types

---

opm/material/common/UniformTabulated2DFunction.hpp

remove warnings in co2store when NDEBUG is on. In CO2STORE can be slow if a lot of extrapolation is done.
In simulations one should limit the pressures by --temperature-min/max --pressure-min/max so that table is ok.

remove warnings in co2store with NDEBUG on

---

CMakeLists_files.cmake
opm/material/checkFluidSystem.hpp
opm/material/constraintsolvers/CompositionFromFugacities.hpp
opm/material/fluidsystems/BaseFluidSystem.hpp
opm/material/fluidsystems/BlackOilFluidSystem.hpp
opm/material/fluidsystems/BrineCO2FluidSystem.hpp
opm/material/fluidsystems/Co2BrineFluidSystem.hh
opm/material/fluidsystems/GasPhase.hpp
opm/material/fluidsystems/GenericFluidSystem.hh
opm/material/fluidsystems/GenericOilGasFluidSystem.hpp
opm/material/fluidsystems/H2OAirFluidSystem.hpp
opm/material/fluidsystems/H2OAirMesityleneFluidSystem.hpp
opm/material/fluidsystems/H2OAirXyleneFluidSystem.hpp
opm/material/fluidsystems/H2ON2FluidSystem.hpp
opm/material/fluidsystems/H2ON2LiquidPhaseFluidSystem.hpp
opm/material/fluidsystems/LiquidPhase.hpp
opm/material/fluidsystems/SinglePhaseFluidSystem.hpp
opm/material/fluidsystems/Spe5FluidSystem.hpp
opm/material/fluidsystems/ThreeComponentFluidSystem.hh
opm/material/fluidsystems/TwoPhaseImmiscibleFluidSystem.hpp
src/opm/material/fluidsystems/BlackOilFluidSystem.cpp
tests/material/test_fluidsystems.cpp

it has the NumComp as a template parameter, so that we can instantiate FluidSystem with different number of components.
And also, we can add different components into the FluidSystem.
The main purpose of this PR is that for ThreeComponentFluidSystem, (for example, it is used in [co2ptflashproblem.hh](https://github.com/OPM/opm-models/pull/855/files#diff-089d65d691a91b833ea8ff392384b0258fd92ccb7312aa308463a5d51b3cee3b) )
Both the number of the components and number of the components are fixed. (Three Components, and they are the predefined CO2, C1 and C10 respectively. )
Not totally sure if will always work, but with the GenericFluidSystem introduced in this PR, we can specify the number of the components (compilation time), and also the component (the component does not need to be …

adding GenericOilGasFluidSystem.hh to contain different components

---

opm/input/eclipse/Schedule/Source.hpp
src/opm/input/eclipse/Schedule/Source.cpp
src/opm/input/eclipse/share/keywords/900_OPM/S/SOURCE
tests/parser/SourceTests.cpp

For thermal runs with Source you can either specify the enthalpy or the temperature. If temperature is given, the simulator will compute the enthalpy from the temperature given and the pressure in the cell.

Add temperature as optional input for Source

---

opm/output/eclipse/Inplace.hpp
src/opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
src/opm/input/eclipse/share/keywords/000_Eclipse100/F/FIELD_PROBE
src/opm/input/eclipse/share/keywords/000_Eclipse100/R/REGION_PROBE
src/opm/output/eclipse/Inplace.cpp
src/opm/output/eclipse/Summary.cpp

Reverts OPM/opm-common#3868
We must merge the original along with its downstream companion OPM/opm-simulators#5114.

Revert "Add mass co2 in place summary vectors"

---

opm/output/data/Wells.hpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp
tests/test_Wells.cpp

This PR adds a new data member to the `data::Connection` structure,
```C++
double data::Connection::compact_mult
```
This provides a slot in which the simulator can communicate transmissibility multiplier values resulting from rock compaction. The goal is to be able to distinguish background transmissibility factors from the effective transmissibility factors which include rock compaction effects.

Collect Dynamic Connection Level Transmissibilty Multiplier

---

opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
opm/material/thermal/EclThermalLawManager.hpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
src/opm/material/fluidmatrixinteractions/EclMaterialLawManagerInitParams.cpp
src/opm/material/thermal/EclThermalLawManager.cpp
tests/material/test_eclmateriallawmanager.cpp

Unnecessary function argument numElements  has been removed in OPM/opm-grid#704. Associated PR in opm-simulators is coming soon.

[refactor] Remove numElems in lookup assigners

---

opm/output/eclipse/InteHEAD.hpp
opm/output/eclipse/VectorItems/intehead.hpp
src/opm/output/eclipse/CreateInteHead.cpp
src/opm/output/eclipse/InteHEAD.cpp

In particular, identify more UDQ-related items in INTEHEAD and add more members to `InteHEAD::UdqParam` to hold counts of additional UDQ categories.
While here, also ensure that default-constructed objects of various `InteHEAD::*` structures have well-defined values.

Prepare for Adding Segment Level UDQ Information to Restart File

---

src/opm/io/eclipse/EclFile.cpp

This issue was noticed here: https://github.com/OPM/opm-common/issues/1037.
When a faulty file is detected, the program still continues because the error is caught here: https://github.com/OPM/opm-models/blob/a89ccecaa38aa552873a7a90f50902eb7327abd1/opm/models/parallel/tasklets.hh#L234
@blattms Is this the intended behavior or is this something to be discussed?

Print a meaningful error message in case a (possibly faulty) output file cannot be loaded.

---

opm/input/eclipse/EclipseState/Runspec.hpp
src/opm/input/eclipse/EclipseState/Runspec.cpp
tests/parser/RunspecTests.cpp

This commit extends the `NetworkDims::active()` function to return true also for runs using the standard network model (keyword `GRUPNET`).  Previously, this member function would return true only for runs using the extended network model.
This matters, because the initial network balance object's constructor in member function [`Schedule::create_first()`](https://github.com/OPM/opm-common/blob/d63ec44775ccab11ca6d61d3adf51e7662e38fd3/src/opm/input/eclipse/Schedule/Schedule.cpp#L2223) performs different actions depending on whether or not the `NetworkDims` are "active".  In particular, its pressure convergence limit will be [set to zero](https://github.com/OPM/opm-common/blob/d63ec44775ccab11ca6d61d3adf51e7662e38fd3/src/opm/input/eclipse/Schedule/Network/Balance.cpp#L117) unless networks …

Identify Standard Network as Active for NETBALAN Initialisation

---

opm/input/eclipse/EclipseState/Tables/TableManager.hpp
src/opm/input/eclipse/EclipseState/Tables/TableManager.cpp
src/opm/input/eclipse/share/keywords/001_Eclipse300/D/DIFFAGAS
src/opm/input/eclipse/share/keywords/001_Eclipse300/D/DIFFAWAT
src/opm/input/eclipse/share/keywords/001_Eclipse300/D/DIFFCWAT
src/opm/input/eclipse/share/keywords/keyword_list.cmake
tests/parser/TableManagerTests.cpp

Adds keywords DIFFAGAS and DIFFAWAT which are equivalent with DIFFCGAS and DIFFCWAT assumes a mass and not mol fraction formulation of diffusion.

Add mass fraction diffusion coefficients

---

opm/input/eclipse/Schedule/Well/WellInjectionControls.hpp
opm/input/eclipse/Schedule/Well/WellProductionControls.hpp
src/opm/input/eclipse/Schedule/HandlerContext.cpp
src/opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp
tests/parser/ScheduleTests.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp

The PR is targeting the following scenario. 
```
WELSPECS with crossflow on
WCONHIST give a ZERO rate
DATES
WELSPECS with crossflow off.
DATES
WELSPECS with crossflow on
```
Basically, part of the properties from the WELSPECS can be updated without providing a new WCON* keyword.  Then for the scenario with zero rate constraints from the WCON* keyword, the well status might be OPEN or SHUT depending on the new WELSPECS input. 
The current master could not handle the above behavior. 
I also include the aut shut-in in the PR, but that is not the motivation of the PR, just seeing it should be done in the same manner.

updating crossflow and auto-shutin with new WELSPECS

---

src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp

Typo fixed: x -> nx, in the error message regarding ZCORN size.

[typo]  Corrected error message on ZCORN size

---

opm/io/eclipse/EGrid.hpp
src/opm/io/eclipse/EGrid.cpp

Adding support for NUMRES > 1 and keyword COORDSYS.
coordinates are now calculated with correct coordinate lines if NUMES > 1

Updated of class Opm::EclIO::EGrid

---

opm/io/eclipse/rst/connection.hpp
opm/output/eclipse/VectorItems/connection.hpp
src/opm/input/eclipse/Schedule/Well/Connection.cpp
src/opm/io/eclipse/rst/connection.cpp
src/opm/output/eclipse/AggregateConnectionData.cpp
tests/test_AggregateConnectionData.cpp

This PR writes the value of the denominator expression in Peaceman's formula to `SCON[6]` and the connection's interval length to `SCON[31]` in the restart file.  Using this information at restart time is the subject of follow-up work.

Store Peaceman Denominator and Connection Length in Restart File

---

opm/input/eclipse/Schedule/Action/Enums.hpp
src/opm/input/eclipse/Schedule/Action/ActionValue.cpp
src/opm/input/eclipse/Schedule/Action/Condition.cpp
src/opm/input/eclipse/Schedule/Action/Enums.cpp
tests/parser/ACTIONX.cpp

This is was already started but some bits and pieces where missing. This made the code not detecting the comparator `!=` or `.ne` leading to error messages as:
```
Could not determine right hand side / comparator for ACTIONX keyword at  ...
```
While at it, we now at least check the creation of all operators. Still, the test suite has quite some holes in this area...
This is WIP because I want to also test a new test in opm-tests first.

Fix/complete support for operator .ne. (!=) in ACTIONX

---

opm/output/eclipse/VectorItems/connection.hpp
src/opm/output/eclipse/AggregateConnectionData.cpp
tests/test_AggregateConnectionData.cpp

`SCON[0]` holds the effective connection transmissibility factor, including pressure dependent multipliers such as those arising from rock compaction.  This PR distinguishes `SCON[0]` from `SCON[11]`, with the latter holding the background from geometry and "static" multipliers (e.g., keywords `WPIMULT` and `WELPI`).

Distinguish Background From Effective CTFs

---

tests/material/test_binarycoefficients.cpp

This fixes build with boost 1.66 which is in use on RHEL8. Support for using std::tuple for the type list was added in boost 1.67.

fixed: build with boost 1.66

---

cmake/Modules/FindZOLTAN.cmake

QOL for redhat, so users don't have to specify zoltan paths manually.
RHEL does not install mpi dependent libs in standard paths but rather in paths which are made available for runtime using the mpi/xxx modules. However, these paths are not supplied on configure time forcing manual specification when building on rhel. To make life easier for those users, supply the hints provided in the ```MPI_INCLUDE``` and ```MPI_LIB``` environment variables supplied by the module command.

fixed: add hints in zoltan find rule to work with RH mpi folder structure

---

cmake/Modules/UseCompVer.cmake

In:
`Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: x86_64-apple-darwin22.6.0`
it results in the following error:
```
CMake Error at /Users/dmar/Github/opm/build/opm-common/opm-common-config.cmake:74 (include):
include could not find requested file:
/Users/dmar/Github/opm/build/opm-common/opm-common-targets.cmake
Call Stack (most recent call first):
CMakeLists.txt:54 (find_package)
```
which is fixed by reverting part of https://github.com/OPM/opm-common/commit/78ecc958e7c6558018321965de50e50e339e5cbb

Fix to build in macOS

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp

(when reprocessing the schedule section after action application.)

Facilitate respecting low parsing strictness in actions 

---

CMakeLists_files.cmake
opm/input/eclipse/EclipseState/SimulationConfig/DatumDepth.cpp
opm/input/eclipse/EclipseState/SimulationConfig/DatumDepth.hpp
opm/input/eclipse/share/keywords/000_Eclipse100/D/DATUMRX
tests/test_DatumDepth.cpp
tests/test_Serialization.cpp

The input keywords `EQUIL`, `DATUM`, `DATUMR`, and `DATUMRX` define global or per-region depths to which per-cell phase pressures may be corrected.  These depths go into calculating the `BPPO`, `BPPG`, and `BPPW` summary vectors.  This PR introduces a new helper class, `DatumDepth`, which internalises the information contained in those keywords and supports retrieving pertinent datum depths given a region ID and a region set name.
While here, also amend the data model for the `DATUMRX` keyword.  If the region set name is defaulted&ndash;or entered as all blanks&ndash;then that should be treated as the built-in `FIPNUM` region set.

Add Container for Datum Depths From Simulation Input

---

opm/output/eclipse/Inplace.cpp
opm/output/eclipse/Inplace.hpp
tests/test_Inplace.cpp

The pure phases are treated differently from the others in the context of per-cell restart file output (result arrays `FIP*`, `RFIP*`, and `SFIP*`) so we should have a way excluding those from the general handling.  To this end, introduce a new helper function,
```
Inplace::mixingPhases()
```
which returns the list of known "phases" apart from the OIL, WATER, and GAS cases.  We then reimplement the helper function `phases()` in terms of `mixingPhases()`.

Separate Pure From Mixing "Phases" in In-Place Categories

---

opm/input/eclipse/EclipseState/SimulationConfig/SimulationConfig.cpp
opm/input/eclipse/EclipseState/SimulationConfig/SimulationConfig.hpp
tests/parser/SimulationConfigTest.cpp

This PR adds a `DatumDepth` data member to the `SimulationConfig` type and initialises this member from the `SOLUTION` section.  This, in turn, publishes the model's explicitly or implicitly defined datum depths&ndash;either global or per-region&ndash;to client code which may then use this to calculate depth-corrected phase pressures such as the `BPPO`, `BPPG`, and `BPPW` summary vectors.

Internalise Model's Datum Depth from SOLUTION Section

---

opm/output/eclipse/Summary.cpp

This PR makes the per-cell (block) summary vector configuration system aware of the depth-corrected phase pressure vectors
```
BPPO, BPPG, BPPW
```
These will now be output to the summary file if requested from the `SUMMARY` section.

Enable Summary File Output of Depth-Corrected Phase Pressures

---

opm/output/eclipse/AggregateConnectionData.cpp
opm/output/eclipse/AggregateWellData.cpp
opm/output/eclipse/VectorItems/connection.hpp
opm/output/eclipse/VectorItems/well.hpp
tests/test_AggregateConnectionData.cpp
tests/test_AggregateWellData.cpp

In particular the Dake model D-factor correlation parameters `A`, `B`, and `C` go into `SWEL` at locations 104, 105, and 106,
respectively.  Additionally, the static product
```math
A \cdot (K / K_0)^B \cdot \phi^C \cdot (K / (r_w \cdot h))
```
goes into `SCON[37]` of the affected reservoir connections.

Write D-Factor Correlation Parameters to Restart File

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/ScheduleState.cpp
tests/parser/ScheduleTests.cpp
tests/parser/TuningTests.cpp

If there was a TUNING keyword recorded then it will also be part of all ScheduleState for later report steps. This becomes a problem for TSINIT which should only apply to one report step if another TUNING_EVENT happens.
Based on #3949 for convenience.

Make sure TSINIT of TUNING only applies to one report step.

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp
tests/parser/ScheduleTests.cpp
tests/parser/TuningTests.cpp

This in preparation for correct NEXTSTEP handling during ACTIONX. The problem is that there is only a ScheduleState per report step. This is changed by ACTIONX to have the TUNING_CHANGE event. We can query the event from the simulator and react upon it. Once we react we want to prevent future reactioms during the same report step. Otherwise the size specified with NEXTSTEP would be used for every substep.
This PR allows to clear an event of a report step.

Allow simulator to clear events of a report step.

---

opm/input/eclipse/Schedule/Well/Connection.cpp
opm/input/eclipse/Schedule/Well/WDFAC.cpp
opm/input/eclipse/Schedule/Well/WDFAC.hpp
opm/input/eclipse/Schedule/Well/Well.cpp
opm/io/eclipse/rst/connection.cpp
opm/io/eclipse/rst/connection.hpp
opm/io/eclipse/rst/state.cpp
opm/io/eclipse/rst/well.cpp
opm/io/eclipse/rst/well.hpp

This PR loads the connection level Peaceman denominator value, static D-factor correlation coefficient, and connection interval length from the restart file and forwards these values from the `RstConnection` type to the regular `Connection` type.  Furthermore, we load the well-level D-factor correlation parameters `A`, `B`, and `C` of the `WDFACCOR` keyword into the `WDFAC` type at restart time.
Collectively, these changes enable restarting simulation runs using the `WDFACCOR` keyword.

Load D-Factor Correlation Parameters From Restart File

---

opm/input/eclipse/EclipseState/EclipseState.cpp
opm/input/eclipse/EclipseState/EclipseState.hpp
opm/input/eclipse/EclipseState/Runspec.cpp
opm/input/eclipse/EclipseState/Runspec.hpp
opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp
opm/input/eclipse/Schedule/Group/Group.cpp
opm/input/eclipse/Schedule/Group/Group.hpp
opm/input/eclipse/Schedule/SummaryState.cpp
opm/input/eclipse/Schedule/SummaryState.hpp
opm/input/eclipse/Schedule/UDQ/UDQASTNode.hpp
opm/input/eclipse/Schedule/UDQ/UDQDefine.cpp
opm/input/eclipse/Schedule/UDQ/UDQParser.cpp
opm/input/eclipse/Schedule/UDQ/UDQParser.hpp
opm/input/eclipse/Units/UnitSystem.hpp
opm/output/eclipse/Summary.cpp

Mostly by splitting up long lines and re-sorting include statements. The one big API change here is that we make the UDQ expression parser private to the implementation file and switch to returning a `unique_ptr<>` directly instead of a `UDQASTNode` which is then used to form a `shared_ptr<>`.
All of this is in preparation of adding support for using region level summary vectors in the defining expressions of field-level UDQs.

Tidy Up Certain Implementation Files

---

opm/io/eclipse/EGrid.cpp

When the `GRIDHEAD` source is a properly constructed restart file it is okay to assume that `GRIDHEAD` has at least 25 elements, but in the context of a manually created regression/unit test that assumption might not hold.
Play it safe by checking the number of elements before indexing into the array here.

Don't Index Out of Bounds for GRIDHEAD

---

opm/material/common/UniformTabulated2DFunction.hpp

The parameter does not get referenced in Release builds which define `NDEBUG`.
While here, ensure that we include all requisite standard headers.

Tag Extrapolation Flag as Maybe-Unused

---

cmake/Modules/UseVCSInfo.cmake
cmake/Scripts/WriteVerSHA.cmake

Missed these as they run on build time and not configure time.
Also fix a regression introduced in previous replacement round.

Finalize exec_program replacement

---

opm/io/eclipse/SummaryNode.cpp

In particular, we should be able to recognise that
- FIPAB1
- FIPAB2
denote different region sets when normalising the region set names.

Support Numbers in User Defined Region Set Names

---

opm/input/eclipse/EclipseState/Compositional/CompositionalConfig.cpp
opm/input/eclipse/EclipseState/Compositional/CompositionalConfig.hpp

This means we can also move the `<fmt/format.h>` header to the implementation file whence translation units which transitively include `CompositionalConfig.hpp`, e.g., through `EcliseState.hpp` need not have format.h in the build's include path.
While here, also move the static function
```
warningForExistingCompKeywords
```
to the implementation file since this function is used only in that translation unit.

Move 'processKeyword' to Implementation File

---

opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
opm/output/eclipse/RegionCache.cpp
opm/output/eclipse/RegionCache.hpp

In particular, the `SummaryConfig` class did not properly account for non-default region sets&ndash;e.g., `FIPABC`&ndash;in all aspects of region level summary keyword processing.  For instance, keywords like `RGPR_ABC` would be classified as an `Unknown` type instead of a `Rate` keyword.  Moreover, the `require3DField()` member function would similarly fail to recognize those kinds of region-level keywords.  This PR switches to using `SummaryConfig::match()` as part of the implementation of `require3DField()`.
While here, also refactor the `RegionCache` construction process in preparation of adding support for region-level summary vectors in `UDQs` and `ACTIONX` condition blocks.  Since we don't know which summary keywords are ultimately referenced until we've parsed the complete …

Fix Numerous Smaller Issues in the SummaryConfig Type

---

opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.hpp

This PR adds a new helper function,
```
SummaryConfig::registerRequisiteUDQorActionSummaryKeys
```
which allows the caller to pass a list (`vector<string>`) of summary vector names that are used in the defining expressions of UDQs and in the condition blocks of `ACTIONX` keywords.  The `SummaryConfig` object will expand the list to a full sequence of summary nodes and include those in the internal list of "known" vectors.  The function returns those nodes which did not already exist from processing the `SUMMARY` section at construction time.
This is in preparation of generalising the `UDQ`/`ACTIONX` support in [`Summary.cpp`](https://github.com/OPM/opm-common/blob/07715bb44fdcb921340ffafd011de6031356c37f/opm/output/eclipse/Summary.cpp#L4559-L4563) to also include region-level summary …

Enable SummaryConfig Inclusion of UDQ/ACTIONX Vectors

---

opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp

It is not used, but creates warnings about uninitialized variables.

Comment unused EclHysteriseTwoPhaseLawParam::krwSwMdc_

---

opm/io/eclipse/EGrid.cpp

Pointy hat split in two and shared between perpetrator and reviewer.
Caught by debug iterator build.

fixed: assignment intended, not comparison

---

opm/input/eclipse/Schedule/Well/PAvgCalculator.cpp
opm/input/eclipse/Schedule/Well/PAvgCalculator.hpp
tests/test_PAvgCalculator.cpp

This PR allows for the possibility that not all well connections might be in active cells for the purpose of calculcating the WBPn summary vectors.  This situation might arise when "re-parsing" portions of the SCHEDULE section following the successful triggering of an `ACTIONX` block.  In this case, the well's connections might not be filtered down to the active set only through a call to member function `Schedule::filterConnections()` so it is better to add some logic here that will filter out the inactive connections.
To this end, add three new members to the `PAvgCalculator` class:
- Data member `numInputConns_` records the number of original well connections&ndash;i.e., `Well::getConnections().size()`.  The vector of connection-based source locations must be sized according to this …

Relax Assumption That All Connections are Active

---

CMakeLists_files.cmake
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
tests/material/test_hysteresis.cpp

This adds a set of test cases for the Carlson and Killough hysteresis model. The test uses linear relative permeability to make it simple to compute the reference solutions.

Add testing for hysteresis

---

opm/output/eclipse/EclipseIO.cpp
opm/output/eclipse/EclipseIO.hpp
opm/output/eclipse/Summary.cpp
opm/output/eclipse/Summary.hpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp

This PR introduces and uses a new member function
```
SummaryConfig::registerRequisiteUDQorActionSummaryKeys()
```
as a means of constructing the expanded set of summary nodes referenced by defining expressions for UDQs and in condition blocks of the `ACTIONX` keyword.  We switch to using the `Evaluator::Factory` to construct evaluation function objects for those additional summary nodes.  In principle, this change enables using all known summary vector categories as part of the defining expressions in a `UDQ`, but additional testing is needed before claim to fully support such usage.
Since this change enables using region-level keywords here, we defer construction of the `regionCache_` until we've fully expanded the set of UDQs and `ACTIONX` keywords.
The downside to this change is that …

Expand Set of Categories for UDQ and ACTIONX Summary Vectors

---

opm/material/fluidsystems/BaseFluidSystem.hpp
opm/material/fluidsystems/BlackOilFluidSystem.hpp

there might be something I am not aware of this, but it looks like returning `bool` should be the better practice?

returning bool for phaseIsActive() function

---

opm/input/eclipse/Schedule/KeywordHandlers.cpp

With just the warning, this will go almost unnoticed

Throw an error on PYACTION keyword if flow was built without embedded Pytion

---

opm/input/eclipse/EclipseState/EclipseState.cpp
opm/input/eclipse/EclipseState/Grid/Box.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.hpp
opm/input/eclipse/share/keywords/000_Eclipse100/M/MULT_XYZ

This is for MULTX, MULTX-, MULTY, MULTY-, MULTZ, MULTZ-.
Previously, EQUALS MULT* would have reset the multiplier of the GRID section and multiple occurrences of MULT* in the EDIT section would have been applied cummulatively.
Now the EDIT section has its own multiplier (stored in FieldProperties with a prefix) which is applied to the one of the GRID section (without prefix) when we leave the EDIT section.
Hence for multiple occurrences the last one wins and EQUALS MULT* can be used to only reset some values of the multiplier that will be applied to the one of the GRID section.
This bugfix form #3997 where also test for this are added. Tests without writing MULT* to INIT are unfortunately not possible. Here we will be able to see whether any regression tests are failing.

[bugfix] Fix multiplier handling in the EDIT section.

---

CMakeLists.txt
CMakeLists_files.cmake
opm/input/eclipse/Python/PyRunModule.cpp
opm/input/eclipse/Python/PyRunModule.hpp
opm/input/eclipse/Python/PythonInterp.cpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/SummaryState.hpp
python/README.md
python/cxx/eclipse_state.cpp
python/cxx/export.cpp
python/cxx/export.hpp
python/cxx/schedule.cpp
python/cxx/summary_state.cpp
tests/action_missing_run.py
tests/msim/MSIM_PYACTION_NO_RUN_FUNCTION.DATA
tests/msim/action2_no_run_function.py
tests/msim/action_count_no_run_function.py
tests/msim/test_msim_ACTIONX.cpp
tests/parser/PYACTION.cpp

- Make the EclipseState, Schedule, SummaryState available as attributes of the module opm_embedded instead
- This enables tooltips for writing code in a python ide by typing opm_embedded.<tab>
- The code will still be backwards compatible

Remove the need for a run-function in the python code

---

opm/input/eclipse/Schedule/Well/Well.hpp
opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp
opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp
opm/input/eclipse/Schedule/Well/WellProductionProperties.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp
tests/parser/data/integration_tests/SCHEDULE/SCHEDULE_WELLS2
tests/test_AggregateGroupData.cpp
tests/test_GuideRate.cpp

When we have non-defaulted THP constraint, we have to make sure to provide a VFP table for it. 
When we refer to a VFP table, we make sure the table is valid/defined. 
Originally, the plan was to checking whether VFP table is properly defined from the simulator, but it turns out to be extremely difficult to do it well/properly. The main point was to trigger the throw before all the possible circumstances that can utilize it. 
At the end, it can be the decent solution to do it from the parser side, avoiding to consider all kinds of complicated SCHEDULE setup.

makre sure defining VFP table for THP processing

---

CMakeLists_files.cmake
opm/input/eclipse/EclipseState/Grid/RegionSetMatcher.cpp
opm/input/eclipse/EclipseState/Grid/RegionSetMatcher.hpp
tests/test_RegionSetMatcher.cpp

The primary use case is determining the set of region indices used to define region level UDQs, or to evaluate region level expressions which go into other UDQs, e.g., at the field level.  Typical region level quantities in this context are
* `ROPR`: Oil production rate in all regions of *all* region sets
* `ROPR_NUM`: Oil production rate in all regions of standard/predefined `FIPNUM` region set
* `ROPR_ABC`: Oil production rate in all regions of user defined `FIPABC` region set.
* `ROPR_ABC 42`: Oil production rate in region 42 of user defined `FIPABC` region set.
The user initiates the matching process by constructing a `SetDescriptor` object, filling in the known pieces of information&ndash;the vector name and region ID&ndash;if applicable.  A `SetDescriptor` region ID will match all …

Add Facility for Matching Region Level Summary Vector Expressions

---

opm/input/eclipse/EclipseState/EclipseState.cpp
opm/input/eclipse/EclipseState/EclipseState.hpp

This PR adds two new member functions
```
EclipseState::computeFipRegionStatistics()
EclipseState::fipRegionStatistics()
```
the first of which constructs a FIP region statistics object for the current run's fluid-in-place region and the second of which returns that object.  The initial design constructed the object on first call to `fipRegionStatistics()`, but this does not work in parallel.

Add Procedure for Calculating Basic FIP Region Statistics

---

opm/input/eclipse/Schedule/UDQ/UDQASTNode.cpp
opm/input/eclipse/Schedule/UDQ/UDQAssign.cpp
opm/input/eclipse/Schedule/UDQ/UDQAssign.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQDefine.cpp
opm/input/eclipse/Schedule/UDQ/UDQSet.cpp
opm/input/eclipse/Schedule/UDQ/UDQSet.hpp
tests/parser/UDQTests.cpp

When we add support for using region-level summary vectors in the defining expressions of field-level UDQs, we need to represent other collections of (name,number) pairs.  In other words, we don't just need enumerated well items anymore.
This generalisation means that the existing segment-level `UDQSet` support becomes a little more opaque since we now assign the item's `name` instead of the item's `well`, but this is nevertheless preferable to introducing another type for a very similar concept.

Rename UDQSet's Enumerated Item Type

---

msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQContext.cpp
opm/input/eclipse/Schedule/UDQ/UDQContext.hpp
opm/input/eclipse/Schedule/UDQ/UDQEnums.cpp
tests/parser/UDQTests.cpp
tests/test_AggregateUDQData.cpp
tests/test_Restart.cpp

This PR prepares the `UDQContext` for including additional summary vector categories when computing UDQ values.  We introduce a new wrapper type,
```C++
struct UDQContext::MatcherFactories
```
whose members are callback functions to create appropriate matcher objects for the corresponding category.  At this time we support the original matcher for segment-level summary vectors and the recently introduced `RegionSetMatcher` for region-level summary vectors.
We furthermore add a new region set matcher factory parameter to `UDQConfig::eval()` in preparation of activating the region-level support.  The region-level factory is unused at this time, but will be activated in follow-up work.

Prepare for Including Region Level Quantities in Field Level UDQs

---

opm/input/eclipse/Schedule/UDQ/UDQASTNode.cpp
opm/input/eclipse/Schedule/UDQ/UDQASTNode.hpp
opm/input/eclipse/Schedule/UDQ/UDQContext.cpp
opm/input/eclipse/Schedule/UDQ/UDQContext.hpp
opm/input/eclipse/Schedule/UDQ/UDQSet.cpp
opm/input/eclipse/Schedule/UDQ/UDQSet.hpp

This PR activates support for using region-level summary vectors in the defining expressions of field-level UDQs.  In particular, we add support for evaluating region-level expressions in the UDQ AST node, retrieving the values of region-level variables as UDQ sets, and matching region-level expressions in the UDQ context.
Collectively, these changes enable evaluating UDQs defined as
```
UDQ
DEFINE FURE2 (ROIP_RE2 2)+(ROIP_RE2 4)+(ROIP_RE2 5) /
DEFINE FUGIRD ((0.3*(RGPR_RE2 1)+(RGPR_RE2 2)+(RGPR_RE2 3))/(GEFF TEST)*(1+FUGASX))   /
DEFINE FUGIRDX (ROIP_RE2 2)/(FURE2)*(0.3*(RGPR_RE2 1)+(RGPR_RE2 2)+(RGPR_RE2 3))/(GEFF TEST)*(1+FUGASX)  /
/
```
which occur in the [`UDQ_REG-01`](https://github.com/OPM/opm-tests/blob/e17200d24e198baea9e1628b42b695231b299396/udq_actionx/UDQ_REG-01.DATA#L309-L323 …

Enable Using Region Level Quantities in Field Level UDQs

---

test_util/EclRegressionTest.cpp
test_util/EclRegressionTest.hpp

Fix EclRegressionTest.cpp-functionality to accept extra keywords 

---

opm/input/eclipse/EclipseState/EclipseState.cpp
opm/input/eclipse/EclipseState/EclipseState.hpp
opm/input/eclipse/EclipseState/Grid/TransMult.cpp
opm/input/eclipse/EclipseState/Grid/TransMult.hpp
opm/output/eclipse/WriteInit.cpp
test_util/summary.cpp
tests/test_EclipseIO.cpp

When we write these they will also have the fault multipliers applied.
All MULT? (without trailing "-") arrays are always written. If the first item of GRIDOPTS is NO we will write just those MULT?- arrays that have be specified in the model. If first item of GRIDOPTS is YES then all MULT?- arrays are written.
Note that flow will not abort if the first item of GRIDOPTS is NO, but MULT?- arrays are present. Instead it will still apply those multipliers and continue with the simulation. Other simulators might abort in this case.
I am using `data::Solution` to hold the values for writing. I hope that this approach works and I prevented any unit conversion. Would be good if @bska would double check whether this is sound.

[feature] Write Multipliers (MULTX, MULTX+, etc) to the INIT file.

---

opm/input/eclipse/EclipseState/EclipseState.cpp
opm/input/eclipse/EclipseState/EclipseState.hpp
opm/input/eclipse/EclipseState/IOConfig/IOConfig.cpp
opm/input/eclipse/EclipseState/IOConfig/IOConfig.hpp
opm/output/eclipse/WriteInit.cpp

The `EclipseState`'s input grid's active cells might not coincide with the set of active cells after grid processing&ndash;e.g., due to 
`MINPV`. This commit switches the INIT file's `MULT*` array output to using the `EclipseIO`'s notion of the run's active cells and sizes the defaulted `MULT*` arrays according to that set.
To this end, move the 'write all mult* minus' flag to the `IOConfig` object and form the requisite `MULT*` array `data::Solution` object at the time of output.
While here, also modernise the `IOConfig` implementation files.

Size Defaulted MULT* Arrays From Active Cells in Output

---

CMakeLists_files.cmake
opm/input/eclipse/Parser/ParseContext.cpp
opm/input/eclipse/Parser/ParseContext.hpp
opm/input/eclipse/Python/PyRunModule.cpp
opm/input/eclipse/Schedule/Action/PyAction.cpp
opm/input/eclipse/Schedule/Action/PyAction.hpp
opm/input/eclipse/Schedule/Schedule.cpp
tests/msim/MSIM_PYACTION_INSERT_INVALID_KEYWORD.DATA
tests/msim/insert_invalid_keyword.py
tests/msim/test_msim_ACTIONX.cpp

Before, there was no such check, I've added all keywords I've tested so far to the valid list, and I'll keep adding more keywords after having tested them.
Also, I've added the keyword "WELTARG" from https://github.com/OPM/opm-simulators/blob/master/python/test/test_schedule.py
@hakonhagland: Did you do more tests with the "insert_keywords" function for other keywords that are not in this [list](https://github.com/OPM/opm-common/pull/4008/files#diff-c473c725418b8f6963c6e2b19371ebaab58f49f41334deef2b666082e7637740R40) yet?
If so, I will add the respective keywords!

Fix: Add mechansim to check if a keyword is a valid PYACTION keyword for being inserted

---

opm/output/eclipse/WriteInit.cpp
tests/test_EclipseIO.cpp

This output was missing from the init file previously. Now MULTPV will be output if it is specified in the GRID or EDIT section.
Support for MULTPV in the SCHEDULE section will be added in an upcoming PR. I need to sort out the parallel handling of that.

Write MULTPV to INIT-file and fix a few minor issues with multiple MULTPV occurrences

---

tests/material/test_binarycoefficients.cpp

this is copied from test_components.cpp and is necessary to fix build on RHEL7.

fixed: fix close_at_tolerance in test_binarycoefficients.cpp with old boost

---

cmake/Modules/FindAlberta.cmake

Dune 2.9 expects Alberta targets to available as PkgConfig::Albertaxd.
These are patches done by @blattms for debian packaging. My contribution is exactly opening the PR for getting them into the main repo.
Should be in the release since dune 2.9 will be what the release is based on and users should be able to build the sources on their own, not just use the binary packages.

Fix alberta for dune 2.9

---

opm/input/eclipse/Schedule/Well/Well.cpp

It does not address the situation that some segments are not specified within the WELSEGS keyword. 
It gives the following error message when WELSGES is missing totally, 
```
Error: Problem with keyword COMPSEGS
In /home/kaib/OPM-master-test/opm/opm-tests/model1/include/history_msw.sch line 52
WELSEGS needs to be specified for well PROD-2 before COMPSEGS being parsed.
```

WELSEGS needs to be specified before COMPSEGS

---

opm/output/eclipse/Tables.cpp

The L and T parameter is mixed up in the output code.

fix LET output to init file

---

opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/output/eclipse/WriteInit.cpp
tests/test_EclipseIO.cpp

This output was missing from the init file previously. Now MULTPV will be output if it is specified in the GRID or EDIT section. 
Support for MULTPV in the SCHEDULE section will be added in an upcoming PR. I need to sort out the parallel handling of that.
This is is #4015 again

Write MULTPV to INIT-file

---

cmake/Modules/FindQuadMath.cmake
examples/make_ext_smry.cpp
opm/material/common/quad.hpp

In gcc-14 std::numeric_limits already has a specialization for __float128. Use a probe to detect this fact.
And add a missing include.
Closes #4062

Fix build with gcc-14

---

opm/output/eclipse/WriteInit.cpp

The writing takes place after the loadbalancing during which the field properties are adjusted to the local grid. Hence we need to explicitly query the field properties for the global grid. Otherwise the writer will throw because the arrays are smaller than expected,
Closes OPM/opm-simulators#5359

[bugfix] Fix deadlock when outputting MULTPV to INIT file in parallel.

---

opm/input/eclipse/Schedule/SummaryState.cpp
opm/input/eclipse/Schedule/SummaryState.hpp

This commit adds a new `SummaryState` constructor which makes the class aware of the value used for undefined UDQs&ndash;i.e., [`UDQPARAM(3)`](https://github.com/OPM/opm-common/blob/95795867abc0a2a9a8af1a568387fd4799b0de10/opm/input/eclipse/share/keywords/000_Eclipse100/U/UDQPARAM#L18-L22). Follow-up work will utilise this awareness to provide fallback values for the `get*var()` member functions in the case of requests for UDQs.

Make SummaryState Aware of Undefined UDQ Value

---

msim/src/msim.cpp
opm/output/eclipse/Summary.cpp
tests/parser/ACTIONX.cpp
tests/parser/GroupTests.cpp
tests/parser/ScheduleRestartTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/UDQTests.cpp
tests/parser/WellTests.cpp
tests/parser/integration/ParseKEYWORD.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp
tests/test_AggregateActionxData.cpp
tests/test_AggregateAquiferData.cpp
tests/test_AggregateConnectionData.cpp
tests/test_AggregateGroupData.cpp
tests/test_AggregateMSWData.cpp
tests/test_AggregateNetworkData.cpp
tests/test_AggregateUDQData.cpp
tests/test_AggregateWellData.cpp
tests/test_EclipseIO.cpp
tests/test_LGOData.cpp
tests/test_RFT.cpp
tests/test_Restart.cpp
tests/test_Summary.cpp
tests/test_Summary_Group.cpp
tests/test_restartwellinfo.cpp
tests/test_rst.cpp

This PR switches to calling the `SummaryState` constructor which is aware of the value of undefined UDQs (#4052) directly.  In most cases we pick the actual value from `UDQPARAM(3)`, with a fallback provided by the `Runspec` class if `UDQPARAM` is not specified, but certain unit tests which do not care about UDQs just get the value 0.0 as the second parameter.
This is in preparation of making the undefined UDQ value mandatory in follow-up work.

Make SummaryState Objects Aware of Undefined UDQ Value

---

opm/output/data/Wells.hpp

Mostly to ensure that default-constructed objects have a well defined initial state.

Initialize data::Connection Members by Default

---

opm/input/eclipse/Parser/ParserKeyword.cpp
opm/output/eclipse/AggregateConnectionData.cpp

We must never call `forward<>()` in a loop[%].
[%] Poor understanding by [at]bska.

Don't Use Moved-From Objects

---

test_util/summary.cpp

The underlying `ESmry` type is able to process formatted files, so we can handle those as well.

Support Formatted SMSPEC File in Summary Utility

---

opm/io/eclipse/ESmry.cpp

This avoids a possible access-after-end on (old) line 895, if p1 is npos (maximum positive value == size_t(-1)). Also, the find_first_of etc. are returning unsigned numbers, so changing the variables to match.

Improve reading possibly corrupt summary file.

---

opm/input/eclipse/Schedule/SummaryState.cpp
opm/input/eclipse/Schedule/SummaryState.hpp
tests/parser/EmbeddedPython.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

This PR switches to using the "undefined" value (`SummaryState::udq_undefined`) as a fallback default for undefined or missing user-defined quantities in the `SummaryState::has*()` and `SummaryState::get*var()` member functions.  In particular, we use this fallback value if the request is a well UDQ in member functions `(has|get)_well_var()`, a group UDQ in `(has|get)_group_var()`, or a segment UDQ in `(has|get)_segment_var()`.
Other UDQ categories, e.g., region, will be provided as needed.

Fall Back to Undefined Value for Missing UDQs

---

opm/input/eclipse/Schedule/Action/ASTNode.cpp
opm/input/eclipse/Schedule/Action/ASTNode.hpp
opm/input/eclipse/Schedule/Action/ActionParser.cpp
opm/input/eclipse/Schedule/Action/ActionParser.hpp
opm/input/eclipse/Schedule/Action/ActionValue.cpp
opm/input/eclipse/Schedule/Action/ActionValue.hpp

Otherwise, we risk making decisions based on left-over data.
While here, mark a couple of constructors as `explicit`, split some long lines, and prefer `fmt::format()` for generating diagnostic messages.

Initialise All Data Members in AST Node Constructors

---

opm/input/eclipse/Schedule/Group/GTNode.cpp
opm/input/eclipse/Schedule/Group/GTNode.hpp

Mostly to placate static analyzers.
While here, switch to `fmt::format()` for generating diagnostic messages and adjust whitespace.

Explicitly Initialise GTNode Parent as Nullopt

---

opm/input/eclipse/EclipseState/EclipseState.cpp
opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.cpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.hpp
tests/parser/ACTIONX.cpp
tests/parser/ConnectionTests.cpp
tests/parser/FieldPropsTests.cpp
tests/parser/GroupTests.cpp
tests/parser/MULTREGTScannerTests.cpp
tests/parser/MultisegmentWellTests.cpp
tests/parser/ScheduleTests.cpp
tests/parser/SimulationConfigTest.cpp
tests/parser/WellSolventTests.cpp
tests/parser/WellTracerTests.cpp
tests/parser/integration/ParseKEYWORD.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp
tests/test_InteHEAD.cpp

Reason: Certain workflows de-activate cells by setting PORO=0 while at the same time setting the region numbers (e.g., SATNUM) to invalid values (not supported by current master).

Update actnum in FieldProps and EclipseGrid right after scanning GRID+EDIT

---

opm/input/eclipse/EclipseState/Runspec.cpp
opm/input/eclipse/EclipseState/Runspec.hpp

Also make the Tracers::serializationTestObject() initialize all members.

Bugfix for RunSpec: multiple members were ignored in comparison and serialization.

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Well/WellTestConfig.cpp
opm/input/eclipse/Schedule/Well/WellTestConfig.hpp
opm/input/eclipse/Schedule/Well/WellTestState.cpp

Specifically
* Allow a well test closure reason that appear to be written for some wells that are shut during history
* Do not use guide rate models with NONE target (apparently also be written during history)

Increase restart compatibility 

---

opm/input/eclipse/Schedule/Well/Well.cpp
opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp
opm/input/eclipse/Schedule/Well/WellProductionProperties.cpp

The controls() functions are returning incompletely initialized objects. While there is no risk, since the remaining prediction_mode members are set in the calling function, it is better to set them inside controls().

Move initialization of prediction_mode members.

---

opm/input/eclipse/Schedule/Action/ActionX.cpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Well/WellPropertiesKeywordHandlers.cpp

We need to inform the simulator about possible changes to wells when running `WTMULT` in an `ACTIONX` block.  Recording the keyword's affected wells in the handler context enables the simulator to run any requisite post-action operations such as updating the active wells' operating targets.  Without the call to
```
HandlerContext::affected_well
```
those post-action operations might not run.

Trigger Target Update From WTMULT in ACTIONX

---

opm/input/eclipse/Schedule/UDQ/UDQFunction.cpp
opm/input/eclipse/Schedule/UDQ/UDQFunctionTable.cpp

The `SORTA` (ascending) and `SORTD` (descending) UDQ set operations are both implemented in terms of the `SORT` helper function.  Reduce the memory requirements of this helper function by sorting the indices of the defined elements instead of the elements and their associate function value.  It is easier to sort indices into the UDQ set than to combine the index and a predicate value.
While here, also (slightly) reduce the cost of `UDQFunctionTable::get()` by not looking up the named function twice when it exists in the function table.

Reduce Memory Requirements for UDQ SORT Operations

---

opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
opm/input/eclipse/EclipseState/TracerConfig.cpp
opm/input/eclipse/EclipseState/TracerConfig.hpp
opm/input/eclipse/share/keywords/000_Eclipse100/S/SEGMENT_PROBE
opm/output/eclipse/AggregateWellData.cpp
opm/output/eclipse/Summary.cpp

Needed in (draft) PR: https://github.com/OPM/opm-simulators/pull/5268.

Correct suffix for solution tracers

---

opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.cpp
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp

This sets the salinity in the CO2Store module
It also make it possible to run CO2STORE with multiple pvt regions without crashing

BUGFIX: Fix salinity input co2 module

---

opm/input/eclipse/Deck/value_status.hpp

Just return the value of a logical expression instead of having multiple statements of the form
```C++
if (condition)
return true;
```

Simplify Implementation of Value Status Predicates

---

opm/input/eclipse/EclipseState/Grid/FieldData.hpp
opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
tests/parser/FieldPropsTests.cpp
tests/parser/MultiRegTests.cpp

In particular,
* Prefer in-place map element construction where possible, and `insert_or_assign()` where not
* Apply `const` where meaningful
* Hoist constant conditions/objects out of loops
* Split long lines and make a few other whitespace adjustments
* Prefer prefix increment and `//` comments
* Remove an unneeded static object
* Add `{}` to single statement control structures
* Separate `OPERATER` handling out from the other `*REG` operations (`ADDREG`, `EQUALREG`, `MULTIREG`).  The distinctions are greater than the commonalities and that justifies separate handling.
This is in preparation of making our implementation of array operations like `COPY` more strict.

Varnish FieldProps Implementation

---

opm/input/eclipse/Schedule/MSW/SICD.cpp
opm/input/eclipse/Schedule/MSW/Segment.cpp
opm/io/eclipse/rst/segment.cpp
opm/io/eclipse/rst/segment.hpp
opm/output/eclipse/AggregateMSWData.cpp
opm/output/eclipse/VectorItems/msw.hpp
tests/test_AggregateMSWData.cpp

Previously, we would save this information&ndash;but never restore it&ndash;only for autonomous ICDs ("AICD").  This PR expands our restart support for segment level "devices" (Spiral ICDs, Autonomous ICDs, Valves) to utilise more of the information that is available in the restart file.  We introduce constructors for the device types from `RstSegment` and defer the reconstitution to those constructors.
While working on this, I also noticed a problem in the current master sources.  The [`icd_length`](https://github.com/OPM/opm-common/blob/2d2c262d881ab04e7bd8caa80a0b932440a8686e/opm/io/eclipse/rst/segment.cpp#L85) is treated as if it represents a volumetric flow rate at reservoir conditions, but it must be treated as a length.

Save and Restore ICD Scaling Factor for SICDs Too

---

opm/input/eclipse/share/keywords/000_Eclipse100/W/WELL_PROBE
opm/output/eclipse/Summary.cpp
tests/summary_deck.DATA
tests/test_Summary.cpp

This PR implements the well level target/limit summary vectors
* `WBHPT` (well level BHP target/limit)
* `W[OGLVW]PRT` (well level phase flow production rate target/limit)
* `W[OGVW]IRT` (well level phase flow injection rate target/limit)
with `O` representing oil, `G` representing gas, `L` representing liquid, `V` representing reservoir voidage (`RESV`), and `W` representing water.

Output Well Level Control Limits to Summary File

---

opm/output/eclipse/EclipseIO.cpp
opm/output/eclipse/EclipseIO.hpp

With this you can output restart files every time step if --enable-write-all-solutions=true 
The numbering of the restart and summary files will follow the time step index and not the report index. 
This will not be compatible with restart, but it is sometimes useful to investigate the results at every time step. 
Note that we still don't support RPTRST BASIC=6. For that I image more work needs to be done.

make it possible to output every timestep

---

opm/output/eclipse/EclipseIO.hpp

Does so for me locally at least, with gcc 11.3.0.

Add missing '#include <optional>' that can break compilation.

---

opm/common/ErrorMacros.hpp

OPM_THROW will increase the error count reported in the PRT file. For most of the NumericalProblems thrown this is not what we want as the simulation carries on and errors should halt the simulation. This commit adds another macro OPM_THROW_PROBLEM that will not increase the error count but the problem count.
Note that the counters reported in the PRT are often used to find out whether a simulation succeeded. Hence the error count should only be nonzero if the simulation did abort.

Add macro to throw exceptions indicating only problems.

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/KeywordHandlers.cpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingInfo.cpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingInfo.hpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingKeywordHandlers.cpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingKeywordHandlers.hpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/ScheduleState.hpp
tests/parser/ReservoirCouplingTests.cpp

See downstream https://github.com/OPM/opm-simulators/pull/5436 for more information.

Add support for SLAVES keyword

---

opm/material/fluidsystems/BlackOilFluidSystem.hpp

Note that the FluidSystem::density is not used to compute the density of the fluid in the intensive quantities that is used in the equation, but FluidSystem::density is used in the well model and the enthalpy calculations.

BUGFIX. Use rsw not rswsat in density calculations

---

examples/hysteresis.cpp
opm/material/fluidmatrixinteractions/EclDefaultMaterial.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLaw.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
opm/material/fluidmatrixinteractions/EclMultiplexerMaterial.hpp
opm/material/fluidmatrixinteractions/EclStone1Material.hpp
opm/material/fluidmatrixinteractions/EclStone2Material.hpp
opm/material/fluidmatrixinteractions/EclTwoPhaseMaterial.hpp
opm/output/eclipse/LoadRestart.cpp
opm/output/eclipse/RestartIO.cpp
tests/material/test_eclmateriallawmanager.cpp
tests/material/test_hysteresis.cpp

- New tests for restart is added for gasoil, oilwater nonwetting hysteresis
- 3-Phase tests are added for Baker (default), Stone 1 and Stone 2
- hysteresis parameter set and get methods directly work on min/max saturations to avoid conversion in output layer
UPDATE
- fix for wetting phase hysteresis

Add new tests and corresponing fixes in the hysteresis model

---

opm/material/fluidsystems/BlackOilFluidSystem.cpp
opm/material/fluidsystems/BlackOilFluidSystem.hpp

For co2storage and h2storage we dont have a concept of tables and should not spend time on checking if we are at the saturated front

Add option to not use saturated tables

---

opm/input/eclipse/Deck/FileDeck.cpp

Correctly iterate through container while erasing. This would fail if for example the last keyword of a block is erased. Also the iteration endpoint was not updated correctly.
This may cause some fallout for tests that use the rst_deck program to generate a restart deck automatically.

Bugfix in FileDeck class

---

opm/input/eclipse/Schedule/MixingRateControlKeywordHandlers.cpp
opm/input/eclipse/Schedule/OilVaporizationProperties.cpp
opm/input/eclipse/Schedule/OilVaporizationProperties.hpp
opm/input/eclipse/share/keywords/900_OPM/D/DRSDTCON
opm/material/fluidstates/BlackOilFluidState.hpp
opm/material/fluidsystems/BlackOilFluidSystem.hpp
tests/parser/ScheduleTests.cpp

connected to opm-models (OPM/opm-models#902) and opm-simulators (OPM/opm-simulators#5418)

parameters to extend drsdtcon

---

opm/input/eclipse/EclipseState/Compositional/CompositionalConfig.cpp
opm/input/eclipse/EclipseState/Compositional/CompositionalConfig.hpp
opm/input/eclipse/EclipseState/EclipseState.cpp
opm/input/eclipse/EclipseState/EclipseState.hpp
opm/input/eclipse/EclipseState/Grid/FieldData.hpp
opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.cpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.hpp
opm/input/eclipse/EclipseState/Grid/Keywords.hpp
tests/parser/CompositionalTests.cpp

It is part of the PR https://github.com/OPM/opm-common/pull/4045 , while split it out with the hope that it might be easier for the reviewing process. 
The main change is that we allow `Fieldprops` to handle multiple values per cell.

parsing XMF and YMF from SOLUTION section

---

opm/material/fluidmatrixinteractions/EclEpsGridProperties.cpp
opm/material/fluidmatrixinteractions/EclEpsGridProperties.hpp
opm/material/fluidmatrixinteractions/EclEpsScalingPoints.cpp
opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp

These copies may have been needed in the past, but that is no longer the case.  EPS property arrays such as `SWL`, `SOGCR`, and `SGU` are backed by long-term storage in the `FieldPropsManager` so we can use pointers to those instead of storing separate copies of these within the `EclEpsGridProperties` structure.
While here, move the `EclEpsScalingPointsInfo::update()` function into the `.cpp` file as it does not need direct access to any data members of `EclEpsScalingPointsInfo`.  Finally, move the Leverett J-function initialisation to a separate member function to reduce the cognitive load on reading `EclEpsScalingPointsInfo<>::extractScaled()`.

Don't Needlessly Copy EPS Property Arrays

---

opm/input/eclipse/Schedule/HandlerContext.cpp

At present we issue diagnostic messages of the form
```
Warning: No matching wells for ACTIONX WTMULTin CASE.DATA line 123.
```
This commit amends the diagnostic message to read
```
Warning: No matching wells for ACTIONX keyword 'WTMULT' in CASE.DATA line 123.
```
instead.
While here, also switch to `//` comments.

Improve ACTIONX Diagnostic Message

---

CMakeLists.txt
cmake/Modules/FindQuadMath.cmake

this target is always linked if dune-fem is enabled, while we only want the define for targets where we want to actually use quads

changed: remove HAVE_QUAD compile definition from QuadMath::QuadMath target

---

opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQInput.cpp
opm/input/eclipse/Schedule/UDQ/UDQInput.hpp

We don't actually need full copies of the moderately large `UDQDefine` or `UDQAssign` objects, so switch to storing pointers to the objects managed by `UDQConfig` instead.  This makes `UDQConfig::input()` slightly less expensive.
While here, also make the trivial `UDQInput` member functions inline.

Don't Generate Independent UDQ Objects for Output Purposes

---

opm/output/eclipse/AggregateUDQData.cpp
opm/output/eclipse/UDQDims.cpp
opm/output/eclipse/UDQDims.hpp
tests/test_AggregateUDQData.cpp

This is in preparation of adding support for outputting segment level UDQs to the restart file.
We add a named accessors for the individual UDQ dimension elements and provide the `UDQDims::data()` vector only as a fallback alternative.  We intend to remove that alternative at some point in the future, because having multiple sources of truth will likely lead to inconsistencies.  Instead, we now hold a reference to the report step's `INTEHEAD` vector and forward all dimension requests to that array.

Switch to Named Accessors for UDQ Dimensions

---

opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterial.hpp
opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterialParams.hpp

A few minor revisions:
- Generalize the type storing the interpolation tables, default to the std::vector<Scalar> used earlier to avoid code changes other places
- Add a constructor to simplify instantiation process.
- Throw exception if the finalization step requires reordering the buffers while the underlying data container is const, this is useful when instantiating the class with a read-only view that will be done later to avoid allocations inside GPU kernel code. 
- Run clang format to make the file more consistent
- Fix typo in pcnwSamples(), the "w" should come before the "n", there was a mismatch between the variable and the function retrieving it

Update piecewiseLinearTwoPhaseMaterialParams header

---

cmake/Modules/FindMETIS.cmake
cmake/Modules/FindScotch.cmake

Without this change, building opm-grid resulted in an import error on my system when libscotchmetis-dev was installed and only libptscotch-7.0 and libscotch-dev but not libptscotch-dev.
This PR is not relevant for the user manual.

Include Scotch when scotchmetis is used

---

opm/io/eclipse/EGrid.cpp

Adding missing conditional to avoid nans.

Fix nans in EGrid::getCellCorners

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp

Description is here: https://github.com/OPM/opm-simulators/pull/5488

Add possibleFutureConnections to Schedule

---

cmake/Modules/UseFortranWrappers.cmake

In particular this causes issues if building on jenkins for fortran enabled code (ie opm-upscaling) in debug mode.

fixed: quote string parameter to avoid missing parameter if empty

---

opm/input/eclipse/Units/UnitSystem.cpp
opm/input/eclipse/share/keywords/900_OPM/G/GASJT
opm/input/eclipse/share/keywords/900_OPM/O/OILJT
opm/input/eclipse/share/keywords/900_OPM/T/THERMEXR
opm/input/eclipse/share/keywords/900_OPM/W/WATJT

make sure the offset will not be discarded.
it was spotted when trying to review https://github.com/OPM/opm-simulators/pull/5490 .

fixing the parsing of unit with string "Temperature"

---

opm/input/eclipse/Schedule/Well/Well.cpp
opm/input/eclipse/Schedule/Well/Well.hpp
opm/input/eclipse/Schedule/Well/WellPropertiesKeywordHandlers.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp

Make it possible to check if temperature is defaulted or not. For CO2STORE runs we would like to use the perforation temperature as default if WTEMP or WINJTEMP is not set. In particular this apply to isothermal runs

only set well temperature if WTEMP or WINJTEMP is set

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp

Now it contains the global ids of the perforated cells for each well instead of the coordinates ijk.
This PR is not relevant for the reference manual.

Change type of possibleFutureConnections to std::unordered_map<std::string, std::set<int>>

---

CMakeLists_files.cmake
bin/genEvalSpecializations.py
opm/common/utility/gpuDecorators.hpp
opm/material/common/EnsureFinalized.hpp
opm/material/common/MathToolbox.hpp
opm/material/densead/DynamicEvaluation.hpp
opm/material/densead/Evaluation.cpp
opm/material/densead/Evaluation.hpp
opm/material/densead/Evaluation1.hpp
opm/material/densead/Evaluation10.hpp
opm/material/densead/Evaluation11.hpp
opm/material/densead/Evaluation12.hpp
opm/material/densead/Evaluation2.hpp
opm/material/densead/Evaluation3.hpp
opm/material/densead/Evaluation4.hpp
opm/material/densead/Evaluation5.hpp
opm/material/densead/Evaluation6.hpp
opm/material/densead/Evaluation7.hpp
opm/material/densead/Evaluation8.hpp
opm/material/densead/Evaluation9.hpp
opm/material/densead/Math.hpp
opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterial.hpp
opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterialParams.hpp

Start work on property evaluation on GPUs 
- Make header with macros for function decoration needed by cuda/hip
- decorate functions that must be callable from both the cpu and gpu
- implement make_view functions that will be used in cuda kernels later to serve as the interface to the property data

Prepare PiecewiseLinearTwoPhaseMaterial for GPU support

---

dune.module

Time to bump the minimum dune version. Users on ubuntu can find dune 2.9 packages for 22.04 in the ppa.

bump minimum dune version to 2.9

---

opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLaw.hpp
opm/material/fluidmatrixinteractions/EclHysteresisTwoPhaseLawParams.hpp
tests/material/test_hysteresis.cpp

Follow the formulation as in Killough 1976 more naivly
Most importantly the nonwetting phase saturation is used to determine the turning points.

Fix wetting phase hysteresis

---

CMakeLists_files.cmake
opm/input/eclipse/EclipseState/Grid/FieldData.cpp
opm/input/eclipse/EclipseState/Grid/FieldData.hpp
opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.cpp
tests/parser/FieldPropsTests.cpp

This PR adds defined value checking to the source array from which we're copying in a `COPY` operation&ndash;either with the `COPY` or with the `COPYREG` keywords.  We count the number of source array values which do not have the status of `deck_value` and if this count is positive, then we throw an `OpmInputError` exception which halts further input processing.
As an example of this behaviour, the (deliberately faulty) setup
```
EQUALS
-- SGL not defined prior to this point
'SGL' 0.0 2* 2* 1 5 /
/
COPY
SGL SWL 2* 2* 4 7 /
/
```
will generate an "Error" of the form
```
Error: Problem with keyword COPY
In USER_ERR_COPY_BOX_PARTIALLY_UNDEF.DATA line 195
Copying from source array SGL in BOX (1-13, 1-22, 4-7)
would generate an undefined result in 572 blocks of target array SWL.
```
and stop …

Stop Processing if COPYing From Undefined Source Array

---

opm/input/eclipse/EclipseState/Grid/FieldProps.cpp

We need the actual element if it exists, so don't go through the `count()` member function just to check for existence only to call the `at()` member function directly thereafter.  This PR is a continuation of PR #4100 (commit c720f3296), but for different map objects.
While here, also reduce the scope of a few iterator objects.

Don't Look Up Map Elements Twice

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
opm/input/eclipse/Schedule/ScheduleGrid.cpp

This ensures that the user is warned about well connections to cells that will be deactivated due to MINPV/MINPVV, and also avoids a hard crash (in ParallelWellInfo) if any such well is re-completed at a later stage in the simulation.

COMPDAT: Skip connections to cells that will be deactivated due to MINPV/MINPVV 

---

opm/material/common/UniformXTabulated2DFunction.hpp

These are required changes to enable float support in opm-simulators. I only open the PR to give visibility to those who want to test with float. You are free to comment if you find something of course but I do not ask for this to be merged in this form.

Add necessary templating to support float in simulators

---

opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp

Allow UDQ expressions like the one below (which, as far as I can see, cause no harm):
UDQ
ASSIGN FU_NNN 123456 /
UPDATE FU_NNN NEXT /
/

UDQ: Allow UPDATE after ASSIGN

---

opm/common/utility/shmatch.cpp
opm/input/eclipse/Schedule/SummaryState.cpp
opm/input/eclipse/Schedule/SummaryState.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQContext.cpp
tests/parser/UDQTests.cpp

Properly handle the following: 
```
UDQ
ASSIGN WURST 'A-*' 1.23e4 /
/
```

Fix assignment of selected well variables, also if quoted.

---

opm/input/eclipse/Schedule/UDQ/UDQFunction.cpp
opm/input/eclipse/Schedule/UDQ/UDQFunction.hpp

There's no need to have this function available to the world, since it's only used to implement `SORTA` and `SORTD`.
While here, switch to taking the predicate as an input parameter instead of hard coding `<` or `>` based on a conditional.

Make UDQ SORT Function Backend Private

---

tests/parser/UDQTests.cpp

.. which also happens to break compilation with GCC 13.2.1 ..

Remove debug print

---

python/cxx/eclipse_io.cpp
python/tests/test_esmry.py

Give ability for python scripts to easily
- get list of dates for summary results
- obtain the units for a summary vector.

Export some ESMRY methods to python

---

opm/common/utility/MemPacker.cpp
opm/common/utility/MemPacker.hpp

This to quell various static analyzer warnings

MemPacker: mark buffer const in unpacker functions

---

opm/common/utility/Serializer.hpp

regression in 067d6d44460548e10610b5c753bd2db76bb1887f
This broke among other things test_Serialization running with debug iterator, https://ci.opm-project.org/job/opm-common-static-analysis/461/testReport/(root)/debug_iterator/Serialization/

fixed: do not dereference null pointers

---

opm/input/eclipse/EclipseState/Compositional/CompositionalConfig.hpp
opm/material/fluidsystems/GenericOilGasFluidSystem.hpp

1. extends the `FieldData` to it can handle multiple values per cell for the purpose of the keywords XMF and YMF, which holds the num_comp values per grid cells. 
2. based on above, it handles the parsing of the keywords XMF and YMF
3. extends GenericOilGasFluidSystem so it can be used by the downstream simulators. It introduces some dummy interface, hopefully some refactoring can come later to the remove the dummy interfaces.

compositional 

---

opm/input/eclipse/Schedule/Group/GroupEconProductionLimits.hpp

Noticed some unwanted rebuilding while working on the serializer stuff lately, this is the reason. There is no need for these includes.

remove unnecessary includes

---

bin/genEvalSpecializations.py
opm/material/densead/DynamicEvaluation.hpp
opm/material/densead/Evaluation.hpp
opm/material/densead/Evaluation1.hpp
opm/material/densead/Evaluation10.hpp
opm/material/densead/Evaluation11.hpp
opm/material/densead/Evaluation12.hpp
opm/material/densead/Evaluation2.hpp
opm/material/densead/Evaluation3.hpp
opm/material/densead/Evaluation4.hpp
opm/material/densead/Evaluation5.hpp
opm/material/densead/Evaluation6.hpp
opm/material/densead/Evaluation7.hpp
opm/material/densead/Evaluation8.hpp
opm/material/densead/Evaluation9.hpp

These decorates produces warnings further down the line when instantiated in opm-simulators

remove unneccesary decorators

---

opm/io/eclipse/EclUtil.cpp
opm/io/eclipse/EclUtil.hpp
test_util/convertECL.cpp

The I/O code and simulator does not support this grid type, but we should nevertheless be able to convert between the formatted and the unformatted version of this file.

Recognize .GRID/.FGRID File Types

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp

Inspect item 2 of `GDFILE`, default `'U'` (Unformatted), and pass this on to the `EclFile` constructor introduced in commit 02b02189 (i.e., in PR #2390) as an aid to the reader.  That way we won't have to guess the format based on the file extension.
While here, also make a couple of minor adjustments to the grid construction function&ndash;mostly to eliminate short-lived intermediate objects.

Make GDFILE Implementation Aware of Formatted/Unformatted Flag

---

opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterialParams.hpp

OPM_THROW is not supported in gpu code, replaced with an assert in the device code

avoid OPM_THROW in gpu code

---

opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterialParams.hpp

Fix for making sure https://github.com/OPM/opm-simulators/pull/5597 builds without warnings.
This function does not need to be supported on the GPU

remove unneeded decorator causing warnings

---

opm/input/eclipse/Schedule/Well/Well.hpp
opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp
opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp
opm/input/eclipse/Schedule/Well/WellProductionProperties.cpp
tests/parser/ScheduleTests.cpp
tests/parser/WellTests.cpp
tests/test_rst.cpp

For WCONHIST and WCONINJH default vfp table is the previous one

Use previous vfp table if default in historical runs

---

opm/material/components/Air.hpp
opm/material/components/Component.hpp
opm/material/components/H2O.hpp
opm/material/components/TabulatedComponent.hpp

fixes debug build of test_components. I can't precisely answer why this did not trigger in release builds but.. Regressed in e3f737b8c2a9ef613759ad57dbb3aa7293265c90

fixed: make isTabulated constexpr and explicit use from base class

---

opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
tests/parser/FieldPropsTests.cpp

Extracted from #4181 with added tests.

Support OPERATE for FieldData with global storage.

---

opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
tests/parser/FieldPropsTests.cpp

The existence checks introduced in commit 90be095 (PR #4109) turned out to be a little too restrictive.  Recent experience suggests that we need to permit array operations like `ADD` or `MULTIPLY` on the `MULT*` arrays (`MULT[XYZ]` and `MULT[XYZ]-`) even if these arrays have not yet been explicitly defined in the input deck.
This commit re-enables those array operations for property arrays whose `multiplier` flag is `true`.

Permit Operating on Defaulted MULT* Arrays

---

opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
tests/parser/FieldPropsTests.cpp

For region operations we only make sure that global arrays have correct values for active cells.
This means that values get lost for inactive cells of the regions. In this case we at least issue a warning.
This is the last PR that I factor out from #4181

Allow region operator on global 3D fields (poor man's version) 

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/ScheduleBlock.cpp
opm/input/eclipse/Schedule/ScheduleBlock.hpp
opm/input/eclipse/Schedule/ScheduleDeck.cpp
opm/input/eclipse/Schedule/ScheduleDeck.hpp
tests/msim/test_msim.cpp
tests/parser/ScheduleRestartTests.cpp
tests/parser/ScheduleTests.cpp
tests/rst_test.cpp

This becomes very significant with large schedules. This is probably too naive but I want to check fallout.

changed: only keep keywords in sched_deck if there are actions

---

opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/Well/Well.cpp
opm/input/eclipse/Schedule/Well/Well.hpp

this becomes significant in large schedules with lots of well data

changed: store a pointer to the static unit system instead of a copy per well

---

opm/input/eclipse/Schedule/Well/WellTestState.cpp
opm/input/eclipse/Schedule/Well/WellTestState.hpp
test_util/EclRegressionTest.cpp
tests/parser/ScheduleRestartTests.cpp
tests/test_AggregateUDQData.cpp
tests/test_Restart.cpp
tests/test_restartwellinfo.cpp

In particular
- Explicitly include some headers that will not be available through transitive inclusion
- Remove some unneeded objects/helper functions
- Move helper functions into anonymous namespaces where appropriate
- Re-sort `#include` statements

Prepare for Restarting Models With Segment Level UDQs

---

opm/material/fluidsystems/GenericOilGasFluidSystem.hpp

using const causes linking error when using it for the OutputBlackoilModule (testing, will implement an OutputCompostionalModule).  Should using `constexpr` in the first place.

using constexpr for GenericOilGasFluidSystem indices

---

CMakeLists.txt
opm-common-prereqs.cmake
opm/common/utility/shmatch.cpp

If available, use fnmatch instead of regex. Continuation of #3995

Use a probe for fnmatch.h

---

opm/common/Exceptions.hpp

Adding an exception for the convergence monitoring being introduced in https://github.com/OPM/opm-simulators/pull/5590.
The exception is used to raise a convergence monitoring error, such that the timestep is chopped.

Add exception for convergence monitoring

---

opm/input/eclipse/Schedule/Schedule.cpp

Drive-by simplification. This wrapper serves no purpose.

cleanup: remove useless wrapper function

---

opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/input/eclipse/share/keywords/001_Eclipse300/Z/ZMF
opm/input/eclipse/share/keywords/keyword_list.cmake
opm/material/fluidsystems/GenericOilGasFluidSystem.hpp
tests/parser/CompositionalTests.cpp

The keyword ZMF is used to specify the mole fraction of a component per cell.  It is a keyword for SOLUTION section.

adding ZMF keyword

---

python/setup.py.in

This has been forgotten at some point. Causes warnings while packaging.

fixed: list opm.io.summary package in setup.py

---

test_util/convertECL.cpp

Adds the ability to convert standard output format LGR to FLGR.

convertECL supports converting .LGR to .FLGR and vice versa

---

opm/input/eclipse/Units/UnitSystem.cpp
tests/parser/UnitTests.cpp

Appears to have been simply forgotten when this function was first added in commit d8d6749337 (PR #2620).  Without this we fail loading a restarted simulation run with UDAs for GCONPROD's GRAT limit and issue a diagnostic of the form
> ```
> Internal error: No dimension for UDA control 'GCONPROD_GRAT'
> ```

Add Missing UDA Dimension for GCONPROD GRAT Limit

---

CMakeLists.txt
cmake/Modules/DownloadPyBind11.cmake
python/MANIFEST.in
python/generate-pypi-package.sh
python/setup.py.in

numpy2 is now the default in python repositories, and we need to bump the embedded pybind11 to support it.
The new version of pybind11 does however not support python < 3.8. We therefore use the old version for python 3.6 and 3.7, and the new version for >= 3.8.
Closes #2350
(edited by @blattms: added closes statement)

Bump embedded pybind11 version to enable numpy2 support

---

tests/parser/TransMultTests.cpp

Mostly to ensure that our current `EQUALREG` implementation continues to work in the future.

Add Unit Tests for EQUALREG on MULTY

---

opm/input/eclipse/Schedule/Schedule.cpp

This appears to have been inadvertently missed in commit 8a77f5bd9 (PR #4234) which, as a consequence, partially reverted commit 6b94c5091 (PR #3112).

Log Action Messages to Debug File

---

opm/input/eclipse/Schedule/Schedule.cpp

`Map_member::get()` returns a `const T&` and it's essential to convey this information onto the `back_inserter` lest that helper select the wrong overload of `vector<>::push_back()`.  The current code ended up in the r-value overload `vector<>::push_back(T&&)` and this is undesirable when the `Well` objects must continue to live within the `ScheduleState`.
I completely missed this whilst reviewing #4219.

Preserve Value Category When Copying Well Objects

---

opm/io/eclipse/ESmry.hpp

Back-port of PR #4256 for OPM 2024.10 Release.

[fix] Added missing include needed for g++-14

---

opm/input/eclipse/EclipseState/IOConfig/IOConfig.hpp
opm/output/eclipse/LoadRestart.cpp
opm/output/eclipse/RestartIO.cpp
opm/output/eclipse/RestartValue.cpp
tests/test_Restart.cpp

These no longer serve any purpose as all of their contents are available in the regular restart arrays&ndash;notably `IWEL` and `[SX]WEL`.

Retire OPM_?WEL Arrays

---

opm/input/eclipse/Schedule/UDQ/UDQAssign.cpp
opm/input/eclipse/Schedule/UDQ/UDQAssign.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQEnums.hpp
opm/input/eclipse/Schedule/UDQ/UDQState.cpp
opm/io/eclipse/rst/state.cpp
opm/io/eclipse/rst/state.hpp
opm/io/eclipse/rst/udq.cpp
opm/io/eclipse/rst/udq.hpp
opm/output/eclipse/CreateInteHead.cpp
opm/output/eclipse/InteHEAD.cpp
opm/output/eclipse/InteHEAD.hpp
tests/parser/UDQTests.cpp

This PR reimplements the `RestartIO::RstUDQ` type with a view towards introducing support for restarting simulation runs containing user defined quantities (UDQs) associated to the segments of multi-segmented wells.  In particular, we replace the current value container with a back-end based on the `CSRGraphFromCoordinates` helper class.  This, in turn, enables supporting UDQ values at the sub-entity level of a top-level entity such as the segments of a multi-segmented well.
We more clearly distinguish the producing side&ndash;i.e., the layer which loads information from a restart file&ndash;from the consuming side&ndash;i.e., the client code which forms `UDQConfig` and `UDQState` objects based on the restart file information, and require the producing side to signal when the restart …

Generalise Restart Representation of UDQs

---

opm/input/eclipse/Schedule/UDQ/UDQAssign.cpp
opm/input/eclipse/Schedule/UDQ/UDQAssign.hpp
opm/input/eclipse/Schedule/UDQ/UDQState.cpp
opm/input/eclipse/Schedule/UDQ/UDQState.hpp
opm/io/eclipse/rst/header.cpp
opm/io/eclipse/rst/header.hpp
opm/io/eclipse/rst/state.cpp
opm/output/eclipse/AggregateUDQData.cpp
opm/output/eclipse/AggregateUDQData.hpp
opm/output/eclipse/LoadRestart.cpp
opm/output/eclipse/RestartIO.cpp
opm/output/eclipse/UDQDims.cpp
opm/output/eclipse/UDQDims.hpp
opm/output/eclipse/WindowedArray.hpp

This PR adds support for outputting and reloading the `DUDS` restart file array which holds values of segment level UDQs (`SU*`) in an (#segments)-by-(# MS wells)-by-(#segment level UDQs) dense structure.  Undefined `SU*` values represented by the usual default `UDQ` restart value (`-3.0e+20`).
As a help to efficiency, we defer to class `UDQState` to export the UDQ values pertaining to all segments of a single MS well.  This is easier than providing an interface based on values for a single segment at a time.  On the reloading side, we introduce a new member function `UDQVectors::currentSegmentUDQValue()` which exposes a similar range of values for all segments of a single MS well.  While here, also rework the internals of `UDQVectors` to resemble the structure of RstState's UDQ support.

Add Restart File Support for Segment Level UDQs

---

test_util/convertECL.cpp

fixed a bug that `convertECL` could not identify files with lowercase extensions.

convertECL supports input files with lowercase extensions

---

opm/output/eclipse/AggregateActionxData.cpp
opm/output/eclipse/AggregateGroupData.cpp
opm/output/eclipse/AggregateWellData.cpp

We've had a long-standing problem in our linearisation logic for restart file well data.  We were calling `forward<>(obj)` repeatedly and the only reason this didn't blow up is that it captured a unit system by reference.  Use a guaranteed safe call instead.
While here, also fix a similar problem for the group data and split some long lines in preparation of altering the implementation of ACTIONX match sets.

Don't Move From Object Twice

---

opm/common/utility/Serializer.hpp

commit https://github.com/OPM/opm-common/commit/067d6d44460548e10610b5c753bd2db76bb1887f aimed to
keep the shared nature of shared pointers when deserializing.
the problem is that assigning multiple shared ptrs to the same
raw pointer does not enable any sharing, it only leads to multiple
deletions. fix this by properly holding a shared pointer in the map.
convert the adresses that is serialized to keep track of what pointers were
shared on the sender side to integers (uintptr_t) rather than serializing
them as void pointers. this is clearer and in principle more correct as
it is rather unclear how a serializer should handle a void pointer, and
it only worked by "accident" since std::is_pod_v happens to return true
for a void*.
while at it make sure to clear out pointer maps after …

Fix serialization of shared pointers

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/ScheduleState.hpp
tests/parser/ScheduleSerializeTest.cpp
tests/test_Serialization.cpp

Now that the serializer handles de-duping of shared_ptrs we can just rely on this instead of manually making lists.
This simplifies the serialization and is a nice speed boost in addition since we avoid lots of value-based comparisons.
Fix missing serialization for ResCoup info while at it.
Also simplify Schedule::unique - we can just compare pointers instead of values.
The downstream needs to be merged in tandem.

Simplify schedule serialization

---

opm/input/eclipse/Schedule/Action/SimulatorUpdate.hpp
opm/input/eclipse/Schedule/HandlerContext.cpp
opm/input/eclipse/Schedule/HandlerContext.hpp
opm/input/eclipse/Schedule/Well/WellPropertiesKeywordHandlers.cpp
tests/parser/ACTIONX.cpp

This way, the simulator layer has more information by which to decide if applying a CTF update is safe/sufficient or if it needs to fully rebuild its internal representation of the simulation wells.

Record ACTIONX Wells Affected by WELPI Separately

---

opm/input/eclipse/Schedule/Well/NameOrder.cpp
opm/input/eclipse/Schedule/Well/NameOrder.hpp

In particular, implement a number of single-statement trivial member functions in-line and leverage the return value of `map<>::emplace()` to simplify the operation of adding a new name to `NameOrder`.

Simplify {Name,Group}Order Implementation

---

opm/input/eclipse/EclipseState/EclipseState.cpp
opm/input/eclipse/EclipseState/EclipseState.hpp
opm/input/eclipse/EclipseState/Grid/FieldProps.cpp
opm/input/eclipse/EclipseState/Grid/FieldProps.hpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.cpp
opm/input/eclipse/EclipseState/Grid/FieldPropsManager.hpp

this happens when grid processing removed cells (pinch, minpv, ..). in particular the actnum in the grid_ptr member (ie EclipseState::getInputGrid()) does not reflect the additional inactive cells, and thus the active_index in the Box are not the same as those in the FieldData (which has been modified in the call to FieldProps::reset_actnum). this causes oob indexing in handle_schedule_keywords / multiply_deck.
this is a minimal fix to fix the oob indexing. there might be more dragons hidden in the output where the inconsistent actnum from the input grid is used.

fixed: out-of-bounds indexing in FieldProps

---

opm/input/eclipse/Schedule/UDQ/UDQContext.cpp
opm/input/eclipse/Schedule/UDQ/UDQContext.hpp

The no-argument overloads of member functions
* [`WellMatcher::wells()`](https://github.com/OPM/opm-common/blob/c82b52776a13ea3085212e4c4dcc9201847d86d9/opm/input/eclipse/Schedule/Well/WellMatcher.hpp#L129-L130)
* [`SummaryState::groups()`](https://github.com/OPM/opm-common/blob/c82b52776a13ea3085212e4c4dcc9201847d86d9/opm/input/eclipse/Schedule/SummaryState.hpp#L130)
return references to `const`.  Don't convert these to independent objects on the caller's behalf.  If the caller wants independent objects, they can create such objects at the call site.

Don't Needlessly Copy Well/Group Names

---

tests/test_CopyablePtr.cpp
tests/test_calculateCellVol.cpp
tests/test_cubic.cpp

building as c++-20 this causes errors
I started investigating the changes needed for building as c++-20. This is a simple thing that needs addressing.

fixed: test-suites needs a name

---

opm/output/eclipse/EclipseIO.hpp
opm/output/eclipse/RestartIO.hpp

they are involved in std::vector parameters with default (empty) values. causes issues when building as c++-20.

fixed: cannot forward these entities

---

opm/common/OpmLog/KeywordLocation.cpp
opm/common/utility/OpmInputError.cpp
opm/input/eclipse/Parser/Parser.cpp
opm/material/densead/EvaluationFormat.hpp

fmt wants to do compile time validation of format strings under c++-20. mark formatting strings constexpr where possible, and mark formats runtime to disable validation where not possible.

fixed: use constexpr formats and/or mark format strings runtime

---

msim/src/msim.cpp
opm/input/eclipse/Schedule/UDQ/UDQAssign.cpp
opm/input/eclipse/Schedule/UDQ/UDQAssign.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
tests/parser/UDQTests.cpp
tests/test_Restart.cpp

This commit introduces more general entity matching for UDQ assignments.  This is in preparation of adding support for assignment statements within an ACTIONX block using the `"?"` selector to identify wells and/or groups.
We add new member functions
```
UDQSet UDQAssign::eval(entities, matcher) const
```
with `entities` being a vector of either well/group names or a vector of enumerated items such as the known segments of all MS wells and `matcher` being a call-back function that translates a selector to a vector of specific entities.  Those are, in turn, expected to be a subset of the input entities.  The result value is sized according to the input entities and only those entities identified by the `matcher` will have a defined value.
We reimplement the `UDQConfig`'s well and group …

Generalise Entity Matching for UDQ Assignment

---

opm/common/utility/MemPacker.hpp
opm/common/utility/Serializer.hpp
opm/material/checkFluidSystem.hpp
opm/material/common/quad.hpp
opm/material/constraintsolvers/CompositionFromFugacities.hpp
opm/material/constraintsolvers/NcpFlash.hpp
opm/material/constraintsolvers/PTFlash.hpp

- use constexpr instead of anonymous enums
- avoid use of std::is_pod_v - it is deprecated in c++-20. instead implement it ourself in terms of std::is_trivial && std::is_standard_layout

Quell c++-20 warnings

---

msim/include/opm/msim/msim.hpp
msim/src/msim.cpp
tests/msim/test_msim_ACTIONX.cpp

There can only be one embedded Python interpreter in a program, as Python will never totally cleaned up if it is embedded (using pybind11).
Unfortunately, test_msim_ACTIONX.cpp created a couple Python interpreters and with Python 3.12 this resulted in double frees and other memory problems.
This commit fixes this by creating the Python interpreter in a static shared_ptr and making the tests use that.
Only relevant for tests, but fixes issues with Python 3.12 (e.g. on Debian/Ubuntu). Marking it for the release, anyway.

Fix Python usage in msim and its tests.

---

opm/input/eclipse/Schedule/Action/State.cpp
opm/input/eclipse/Schedule/Action/State.hpp
opm/output/eclipse/AggregateWellData.cpp
tests/parser/ACTIONX.cpp

This PR introduces a separate storage layer for matching entities&ndash;typically wells&ndash;in the `Action::State` object.  This is in preparation of making `Action::Result` more general, and that will make the `Result` object harder to serialize.  The new `Action::State::MatchSet` type has the usual serialization support, but is expected to be limited to wells, since that's what's needed for restart file output purposes.
We switch the internals of `Action::State` to storing `MatchSet`s instead and `Action::State::result()` will now return a pointer to a `MatchSet` instead of an `optional<Action::Result>`.  Update callers accordingly.
While here, switch `Action::State::run_count()` to use `map<>::find()` instead of `map<>::at()` since the former enables controlling which exception type …

Decouple Action::State From Action::Result

---

opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp

leads to deref of empty string.
fixes debug_iter failure in ScheduleRestartTests

fixed: check for and don't try to add an empty unit

---

opm/input/eclipse/Schedule/Action/ASTNode.cpp
opm/input/eclipse/Schedule/Action/ASTNode.hpp
opm/input/eclipse/Schedule/Action/ActionValue.cpp
opm/input/eclipse/Schedule/Action/ActionValue.hpp

This is in preparation of making the set of entities matching a "true" condition more general.  While here, also split nested conditional out to separate helper functions for readability and switch to taking `string_view` parameters where possible.  Finally, add Doxygen-style documentation to both classes and remove `Action::` namespace prefix where appropriate.

Refactor Action::State and Action::Value

---

CMakeLists_files.cmake
opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
opm/input/eclipse/Schedule/Well/WellConnections.cpp
tests/SPE1CASE1_WELTRAJ_2.DATA
tests/parser/ConnectionTests.cpp

The WELTRAJ and COMPTRAJ keywords were added some time ago to enable specification of trajectory wells. This PR fixed a few issues:
- Any MAPAXES specifications were not handled, and cases with the origin not at zero failed. To solve this, the well coordinates are now transformed when they are read.
- There was a bug in COMPTRAJ where defaulting the saturation table column was not handled, leading to segmentation faults.
- The code for for converting the trajectory to cell indices only took the top and bottom coordinates into account, effectively assuming linear trajectories. Now intermediate points are added, allowing arbitrary trajectories.
The existing test case had its origin at zero, and a linear trajectory, which does not test the fixes. Therefore a new test case is added that has …

Fix WELTRAJ/COMPTRAJ keyword handling

---

opm/input/eclipse/EclipseState/Grid/GridDims.cpp
opm/input/eclipse/Parser/ParseContext.cpp
opm/input/eclipse/Parser/ParseContext.hpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp

Previously we threw an exception that was poorly handled by the logging system. The user e.g. saw:
```
Reading from: BLA.INC line 2
Error: An error occurred while creating the reservoir schedule
Internal error: input IJK index above valid range
Error: Unrecoverable errors while loading input: input IJK index above valid range
```
With this commit we use the ParseContext to give a more meaningful error message like:
```
Error: Problem with COMPDAT in ACTIONX
In BLA.INC line 19
Cell (83, 273, 47) of well EX_WA is not part of the grid (Input IJK index (83, 273, 47) not part of grid with dimensions 169x359x46.).
Error: Problem with keyword COMPDAT
In BLA.INC line 19
Problem with COMPDAT in ACTIONX
In BLA.INC line 19
Cell (83, 273, 47) of well EX_WA is not part of the grid (Input IJK index …
```

Give meaningful error for out-of-range well perforations in ACTIONX.

---

opm/input/eclipse/Schedule/Action/ActionAST.cpp
opm/input/eclipse/Schedule/Action/ActionAST.hpp
opm/input/eclipse/Schedule/Action/ActionX.cpp
opm/input/eclipse/Schedule/Action/ActionX.hpp

In particular,
* Add Doxygen-style documentation
* Prefer `//`-style comments
* Make objects `const` where possible
* Prefer in-place construction&ndash;e.g., `vector<>::emplace_back()`
* Prefer initialisation lists to constructor body
* Remove unneeded `Action::` namespace prefixes

Polish Parts of ACTIONX Implementation

---

opm/input/eclipse/Schedule/Action/ASTNode.cpp
opm/input/eclipse/Schedule/Action/ASTNode.hpp
opm/input/eclipse/Schedule/Action/ActionParser.cpp

There's no need to copy the child objects since they will go out of scope in the Action::Parser member functions anyway.  Better to transfer the ownership to the parent node directly.

Take ASTNode Children by R-Value Reference

---

opm/input/eclipse/Schedule/Action/ASTNode.cpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Well/WellMatcher.cpp

This PR adds support for using a leading backslash character (`\`) to disambiguate a leading wildcard (`*` or `?`) in a name pattern as being truly a wildcard.  In particular, this means that the ACTIONX condition
WMCTL '\*RO*' = 0
will be satisfied for all shut wells with the character sequence 'RO' anywhere in the name and that
WCONPROD
'\*RO*' 'OPEN' 'GRAT'  2*  500.0   2*  90.0 /
/
will apply to all wells with the same character sequence 'RO' anywhere in the name.  On the other hand, `'*RO*'` matches all well lists whose names begin with the characters 'RO'.  Similarly, `'\*H'` matches all wells whose names end in 'H' while `'*H'` matches the single well list '*H'.
This disambiguation also applies to the wildcard '?'.  A leading backslash enables `'\?????'` to match all wells whose …

Recognise Leading Backslash as Wildcard Escape Sequence

---

cmake/Modules/FindSuiteSparse.cmake
cmake/Modules/Finddune-istl.cmake

This is in line with DUNE since 2015 and fixes problems when trying to use opm-grid as a DUNE module.

[cmake] Use uppercase for components in FindSuitesparse

---

opm/input/eclipse/Parser/ErrorGuard.cpp
opm/input/eclipse/Parser/ErrorGuard.hpp

This is needed to let errors in the topology show up in the log files, too.
Currently, those are only printed to cerr and the simulator will end with the following line that also appears in the log file: "Error: Unrecoverable errors while loading input:"
Unfortunately, this line (and the log files) will not contain any usable error message and there no other message about the error in the log files.
With this commit we let ErrorGuard::dump return a string with all errors. Those are slightly reformatted to have error message and file information on one line. This string will be used in opm-simulators to print something meaningful to the log files.

Let ErrorGuard::dump return an error string for logging.

---

opm/input/eclipse/Schedule/Well/WellEnums.cpp
opm/input/eclipse/Schedule/Well/WellEnums.hpp

That way, out-of-tree users of `WellEnums.hpp` won't have to have libfmt installed in a central location.

Move WELTARG CMode Formatting to Implementation File

---

opm/input/eclipse/Schedule/UDQ/UDQActive.cpp
opm/input/eclipse/Schedule/UDQ/UDQActive.hpp

This is mostly to exploit commonalities between the group level production and injection cases, and to prepare for adding support for field level UDAs.
While here, add Doxygen-style documentation to the `UDQActive` members, remove unused/unimplemented member functions (e.g., `udq_hash()`, `wg_hash()`, `update_input()`) and reorder the logic in `UDQActive::update()` in order to reduce levels of nesting.

Split UDA Restart File Loading out to Helper Functions

---

cmake/Modules/ConfigVars.cmake

Only values 0 or 1 were handled correctly.
A value defined to TRUE, ON, OFF would have made the value appear in the config.h as text e.g.
```
#define BLA TRUE
```
This caused a lot of trouble with refactored DUNE build system.

Fixed handling of CMake Bool in config.h

---

opm/input/eclipse/Schedule/Group/Group.cpp
opm/output/eclipse/AggregateGroupData.cpp

Background: Restoring all limits from restart appears required to get the correct group information. In particular, a production group controlled by a higher-level group is currently restored as GroupType::NONE, causing differences in the .UNRST output of the restart run.

Write group limits to restart even if not controlled

---

opm/input/eclipse/Parser/ErrorGuard.cpp
opm/input/eclipse/Parser/ErrorGuard.hpp

Refactoring after #4305.
The dump() function is now back to only dumping to stderr. In this class it is used by terminate(), possibly via the destructor. Use in other classes should be unnnecessary, I considered making it private but decided not to for convenience of debugging.
The formattedErrors() messages are no longer reformatted by a regexp, but keep their original style (see below).
Example of output:
```
Unrecoverable errors while loading input:
The GRID section must be followed by EDIT or PROPS instead of GRID
In file /Users/atgeirr/opm/src/opm-tests/spe1/SPE1CASE2_WRONGORDER.DATA, line 108
The GRID section must be followed by EDIT or PROPS instead of GRID
In file /Users/atgeirr/opm/src/opm-tests/spe1/SPE1CASE2_WRONGORDER.DATA, line 110
The PROPS section must be followed by …
```

Refactor ErrorGuard, adding formattedErrors() function.

---

opm/input/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.cpp
opm/input/eclipse/EclipseState/Aquifer/NumericalAquifer/NumericalAquifers.hpp
opm/input/eclipse/EclipseState/Aquifer/NumericalAquifer/SingleNumericalAquifer.cpp
opm/input/eclipse/EclipseState/Aquifer/NumericalAquifer/SingleNumericalAquifer.hpp
opm/input/eclipse/EclipseState/EclipseState.cpp

Current master eventually fails due to dividing by zero when trying to compute the CNV error for any numerical aquifer cells with zero porosity.

Guard against zero pore volume numerical aquifer cells

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/UDQ/UDQActive.cpp
opm/input/eclipse/Schedule/UDQ/UDQActive.hpp
opm/io/eclipse/rst/udq.cpp
opm/io/eclipse/rst/udq.hpp
opm/output/eclipse/AggregateUDQData.cpp
opm/output/eclipse/AggregateUDQData.hpp
opm/output/eclipse/CreateInteHead.cpp
opm/output/eclipse/VectorItems/udq.hpp

In particular, this commit amends the logic for saving and reloading the IUAD and IUAP restart file arrays to account for the differences in how UDAs apply to the 'FIELD' group in the GCONPROD and GCONINJE keywords.  Notably, IUAD[2] is two (2) for field level UDAs, and we store two copies of the number one (1) into IUAP for each field level UDA.
While here, move the `ig_phase()` and `iuap_data()` helper functions into their appropriate namespaces and remove the logic which detected, and excluded field level UDAs from consideration in INTEHEAD.

Add Restart File Support for Field Level UDAs

---

cmake/Templates/opm-project-config.cmake.in

As this ends up in e.g. opm-common_config.cmake, calling find_package(opm-common) will modify the CMAKE_MODULE_PATH in a downstream module if not restored. Since we only need this modification locally it is nice to restore the variable.

[cmake] Restore CMAKE_MODULE_PATH after temporary modification

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp
tests/parser/ScheduleTests.cpp

Client code should not call these, but instead prefer to look up individual objects by name.

Remove Unused (and Expensive) Well/Group Functions

---

opm/common/utility/MemPacker.cpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/ScheduleBlock.cpp
opm/input/eclipse/Schedule/ScheduleDeck.cpp
opm/input/eclipse/Schedule/ScheduleState.cpp
opm/io/eclipse/ERsm.cpp
opm/io/eclipse/ESmry.cpp
opm/io/eclipse/ExtESmry.cpp
tests/test_ESmry.cpp

OPM Flow could not handle deck files with sub-second report steps due to multiple separate issues.
- Use of `std::chrono::duration_cast<std::chrono::seconds>`. This casts any duration to std::chrono::seconds, which is a duration class with 1 second tick, storing the count of ticks in an integer. So it has 1s resolution. The cast is only needed when going from a duration storing the tick count in a float or double to one with integer count anyway, so it can be avoided some of the time, when we stay with double representation for durations. The Opm::time_point uses integer representation, but with a 1ms tick. So when converting to that we must do the duration_cast, but I think 1ms resolution is fine.
- Clamping to time_t resolution, which is 1s. This was done because of serialization for …

Fix subsecond timesteps

---

opm/input/eclipse/Parser/Parser.cpp
opm/input/eclipse/Parser/ParserItem.cpp
opm/input/eclipse/Parser/raw/RawRecord.cpp
opm/input/eclipse/Schedule/UDQ/UDQEnums.cpp

std::string_view does not have a constructor that takes an iterator and a size, it only has a constructor that takes a raw pointer and a size. this only worked by pure luck as the gnu implementation happens to use raw pointers for the iterator type for string_views, but this is not guaranteed by the standard. we should not rely on implementation details.
this fixes this in various ways depending on the context.
if you want i can squash things up, it was just convenient to have it split like this for bisection purposes.

string_view usage: fix misuse

---

opm/common/utility/OpmInputError.cpp
opm/common/utility/OpmInputError.hpp
opm/input/eclipse/Parser/Parser.cpp
tests/parser/integration/ParseKEYWORD.cpp

In particular, do not mix automatic formatting requests (empty braces, `{}`) with manual formatting requests (argument IDs and/or named arguments).  The `std::format()` function of C++20 has the same limitation, so it's beneficial to prepare for this now.
While here, prefer `//`-style comments, tidy up include statements and make objects `const` where possible.

Abide by FMT-v11 Format String Requirements

---

opm/input/eclipse/Schedule/Well/Well.cpp
opm/input/eclipse/Schedule/Well/Well.hpp

In particular
- Avoid copying `shared_ptr<>` objects when moving them is sufficient
- Don't return a `const vector` from `getConnections(int) const`
- Don't copy the `connections` member (twice) when looping in the various `handle*()` functions
- Don't copy the `record` argument when a reference is sufficient
- Split long lines
- Prefer `//`-style comments
- Prefer `fmt::format()` to `std::to_string()`
- Add braces to blocks
- Move function opening braces to next lines
- Make most parameters `const`

Varnish Well Member Function Implementations

---

opm/input/eclipse/Schedule/Well/PAvgCalculator.cpp
opm/input/eclipse/Schedule/Well/PAvgCalculator.hpp
opm/input/eclipse/Schedule/Well/PAvgDynamicSourceData.hpp
tests/test_PAvgCalculator.cpp

The original approach accumulated a per-connection average pressure and then adjusted this to the reference depth using the associated mixture density.  This is mostly okay for normal, vertical wells but biases the result for horizontal connections.  This revised approach uses the common mixture density, but corrects each cell pressure individually based on that cell's centre depth before aggregating the per-connection contributions.
To this end, re-purpose the original `connectionPressureOffset()` member function to compute the mixture density and affect depth correction as part of handling each individual contribution in `accumulateLocalContributions()`.  As a simple, though possibly wasteful, way to get the cell centre depth, defer this calculation to another `DynamicSourceData` item. …

Revise Depth Correction Algorithm for WBPn

---

opm/input/eclipse/EclipseState/SimulationConfig/RockConfig.cpp
opm/input/eclipse/EclipseState/SimulationConfig/RockConfig.hpp
tests/parser/SimulationConfigTest.cpp

This PR allows for parsing ROCKOPTS item 2 with options STORE or NOSTORE (default).
Needed in https://github.com/OPM/opm-simulators/pull/5785

ROCKOPTS item 2

---

opm/input/eclipse/Schedule/Schedule.cpp

If `report_step` is zero, then the current master sources might end up generating a division by zero.  This problem was not noticed by the reviewer when this code was introduced in commit 0eb1b95fc (PR #2347) and has escaped all review until now.
As far as I can tell the `output_interval` isn't really used and the real fix might just be to remove the feature altogether, but that's a larger API change that's better handled in follow-up work.  For now, just ensure that we don't divide by zero and that we implement more or less what the option's intended to do.

Fix Latent Divide By Zero Error

---

.gitignore

The VSCode editor likes to put files in a .vs or .vscode directory. Exclude all such files from version control.

Simplify Using VSCode Editor

---

opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp

Looks like a typo in the array index

Typo in Ezrokhi viscosity coefficients message

---

opm/io/eclipse/ESmry.cpp
opm/io/eclipse/RestartFileView.cpp
opm/io/eclipse/rst/header.cpp

Several adjustments based on testing on regression test datasets in ResInsight.
One commit is related to performance, avoid loading data until requested.

Minor adjustments

---

opm/material/components/BrineDynamic.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp

add necessary make_view and move_to_gpu functions to have brineCo2Pvt on the gpu

Gpu support brineco2pvt

---

opm/input/eclipse/Schedule/Action/PyAction.cpp

Depends on https://github.com/OPM/opm-simulators/pull/5830 and https://github.com/OPM/opm-tests/pull/1270.
With this PR, the keyword WTMULT is activated for the use in a PYACTION.

Add WTMULT to PyAction Keywords

---

opm/input/eclipse/Schedule/Action/ActionX.cpp

- Remove GRUPTARG, GSATINJE and GSATPROD from list of supported keywords by ActionX since they are not supported by flow, see: https://github.com/OPM/opm-simulators/blob/96132fefcf0275a7d6b87de6a5b6e4cc0cb25ed7/opm/simulators/utils/UnsupportedFlowKeywords.cpp#L248, https://github.com/OPM/opm-simulators/blob/96132fefcf0275a7d6b87de6a5b6e4cc0cb25ed7/opm/simulators/utils/UnsupportedFlowKeywords.cpp#L249 and https://github.com/OPM/opm-simulators/blob/96132fefcf0275a7d6b87de6a5b6e4cc0cb25ed7/opm/simulators/utils/UnsupportedFlowKeywords.cpp#L256
- Remove TEST since this is not a keyword

ACTIONX: mark GRUPTARG, GSATINJE, GSATPROD and TEST as unsupported

---

opm/input/eclipse/Schedule/Action/PyAction.cpp

This PR depends on https://github.com/OPM/opm-simulators/pull/5836 and https://github.com/OPM/opm-tests/pull/1273.
With this PR, the keyword WLIST is activated for the use in a Pyaction.

Activate WLIST for use in Pyaction

---

opm/input/eclipse/Schedule/Events.hpp

Switch to using the `UINT64_C` macro from `<cstdint>` to ensure we're bitshifting literals of appropriate width for a `std::uint64_t`.
While here, also switch to `//`-style comments.

Use Appropriate Integer Literals for ScheduleEvents

---

opm/input/eclipse/Schedule/Events.cpp
opm/input/eclipse/Schedule/Events.hpp
tests/parser/EventTests.cpp

In particular,
* Group `const` methods together
* Prefer explicit diagnostic messages over those generated by the system's implementation of `unordered_map<>::at()`.
* Use `std::uint64_t` consistently throughout
* Add Doxygen-style documentation to each data member and member function.
* Include all requisite headers
This is in preparation of adding event object "merging".

Varnish Events Implementation

---

opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterialParams.hpp

Finalization is adjusted to avoid the cpu accessing values from gpumemory, in particular, a mutable buffer. Avoiding the finalization for the GPU instances is less robust, solutions to this are welcome.
move_to_gpu is added to `PiecewiseLinearTwoPhaseMaterialParams` to make managament of GPU instances easier, and design more consistent with other classes.

GPU PiecewiseLinearTwoPhaseMaterialParams maintenance and bugfix

---

opm/material/common/UniformTabulated2DFunction.hpp
opm/material/components/CO2Tables.hpp
opm/material/fluidmatrixinteractions/PiecewiseLinearTwoPhaseMaterialParams.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/Co2GasPvt.hpp

To avoid confusion with move semantics in C++ `move_to_gpu` is renamed to `copy_to_gpu` as the movement of data to the GPU does not invalidate the existing CPU copy.

refactor move_to_gpu

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp

Commit 0ee3694947 (PR #4393) unconditionally writes the value '1' to GRIDHEAD[25]. This causes changes in existing reference EGRID files.
Until this is better understood revert this change. Also was the mouth with soap to trim out those nasty whitespaces at eol.

Revert lgr change

---

opm/input/eclipse/Schedule/Action/ActionX.cpp
opm/input/eclipse/Schedule/Action/PyAction.cpp

The PR https://github.com/OPM/opm-simulators/pull/5848 depends on https://github.com/OPM/opm-tests/pull/1278, so https://github.com/OPM/opm-tests/pull/1278 should be merged first. This PR is technically independent, but should still be merged before https://github.com/OPM/opm-simulators/pull/5848.
For the reference manual: With this, I've checked how the INCLUDE keyword can be used from a PyAction script. The path to the included files can be given relative to the location of the python script (as done in https://github.com/OPM/opm-tests/pull/1278) by retrieving the location of the python script as ` script_location = os.path.dirname(os.path.abspath(__file__))` and using that or as an absolute path.
A pure relative path does not work here, also using variables from the DATA file does not …

Add comment about INCLUDE keyword for Pyaction and ACTIONX

---

opm/input/eclipse/Schedule/Action/ActionX.cpp
opm/input/eclipse/Schedule/Action/PyAction.cpp

The PR https://github.com/OPM/opm-simulators/pull/5846 depends on this PR and on https://github.com/OPM/opm-tests/pull/1277, this PR and https://github.com/OPM/opm-tests/pull/1277 should be merged first.
For the reference manual:
With this PR, the keyword GEFAC is made available for inserting it into the simulation from an ACTIONX block and from PYACTION code.

 Add GEFAC to allowed keywords in ACTIONX block and in PYACTION

---

opm/input/eclipse/Schedule/UDQ/UDQDefine.cpp

Needed for libfmt v11 and forgotten in commit 0e63b8304.
Pointy Hat: [at]bska

Include Ranges.h for fmt::join()

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/ResCoup/MasterMinimumTimeStep.cpp
opm/input/eclipse/Schedule/ResCoup/MasterMinimumTimeStep.hpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingInfo.cpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingInfo.hpp
tests/parser/ReservoirCouplingTests.cpp

Adds support for the `RCMASTS` keyword in reservoir coupling.

Adds support for the RCMASTS keyword

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/ResCoup/CouplingFile.cpp
opm/input/eclipse/Schedule/ResCoup/CouplingFile.hpp
opm/input/eclipse/Schedule/ResCoup/MasterMinimumTimeStep.cpp
opm/input/eclipse/Schedule/ResCoup/MasterMinimumTimeStep.hpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingInfo.cpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingInfo.hpp
opm/input/eclipse/Schedule/ResCoup/ReservoirCouplingKeywordHandlers.cpp
tests/parser/ReservoirCouplingTests.cpp

Builds on #4272 which should be merged first.
Adds support for the DUMPCUPL keyword in reservoir coupling.

Adds support for the DUMPCUPL keyword

---

opm/material/constraintsolvers/PTFlash.hpp
tests/material/test_co2brine_ptflash.cpp
tests/material/test_threecomponents_ptflash.cpp

so that we can based on the mole fractions and pressure and temperature to perform the PTFlash::solve(). 
The current way needs too much information that might not be helpful/needed, which makes the usage hard, mostly to create the input for the function, for example, initializing input to perform PTFlash::solve() in the wellbore, which requires to initialize/create the input on site.

simplying the function interface of PTFlash::solve()

---

opm/input/eclipse/Schedule/Events.cpp
opm/input/eclipse/Schedule/Events.hpp
opm/input/eclipse/Schedule/Schedule.cpp
tests/parser/EventTests.cpp

Commit 092f0a2e (PR #4108) introduced logic to ensure that events added at the restart time&ndash;e.g., group level controls&ndash;would be available during the first time step after restart.  This empirically improved non-linear convergence for certain field cases.
This change did however have the unintended side effect of clearing any other events that might happen on the first report step after the restart time.  If, in particular, that included introducing a new well (WELSPECS keyword), then the events system would lose the new well and any subsequent changes to the well (e.g., WCONPROD or WELOPEN) would then throw an exception for the unknown well in
```
WellGroupEvents::addEvent(well, evt)
```
This PR switches the unconditional 'update_wellgroup_events()' call of commit 092f0a2e …

Don't Lose Events Introduced Immediately After Restart

---

opm/input/eclipse/Schedule/Action/PyAction.cpp

Missed whilst reviewing #4434.

Fix Signature for PyAction::run() Without Embedded Python

---

CMakeLists_files.cmake
opm/input/eclipse/EclipseState/Compositional/CompositionalConfig.cpp
opm/input/eclipse/EclipseState/Compositional/CompositionalConfig.hpp
opm/material/checkFluidSystem.hpp
opm/material/constraintsolvers/PTFlash.hpp
opm/material/eos/CubicEOS.hpp
opm/material/eos/CubicEOSParams.hpp
opm/material/eos/PRParams.hpp
opm/material/eos/RKParams.hpp
opm/material/eos/SRKParams.hpp
opm/material/fluidsystems/Co2BrineFluidSystem.hh
opm/material/fluidsystems/GenericOilGasFluidSystem.hpp
opm/material/fluidsystems/PTFlashParameterCache.hpp
opm/material/fluidsystems/ThreeComponentFluidSystem.hh
tests/material/test_co2brine_ptflash.cpp
tests/material/test_threecomponents_ptflash.cpp

Implemented a general cubic EOS code to calculate EOS parameters with cubic formulations other than just Peng-Robinson. Added the Redlich-Kwong and Soave-Redlich-Kwong EOS formulations. The chosen EOS type must be set when initializing a PTFlashParameterCache instance.

General cubic EOS formulation

---

opm/io/eclipse/rst/state.cpp

If the base run sets these, and the restarted run does not, then we would reset them to their default values in the restarted run.

Reload MSW Iteration Parameters on Restart

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/Group/GSatProd.cpp
opm/input/eclipse/Schedule/Group/GSatProd.hpp
opm/input/eclipse/Schedule/Group/GroupKeywordHandlers.cpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/ScheduleState.cpp
opm/input/eclipse/Schedule/ScheduleState.hpp
opm/input/eclipse/share/keywords/000_Eclipse100/G/GSATPROD
opm/output/eclipse/Summary.cpp
tests/parser/GroupTests.cpp
tests/parser/ScheduleSerializeTest.cpp
tests/test_Serialization.cpp

The simulator part is still missing, but this can be merged on it own.

 Add support for GSATPROD in the input/output code

---

opm/input/eclipse/Schedule/Action/Actions.cpp
opm/input/eclipse/Schedule/Action/Actions.hpp

In particular, provide Doxygen-style documentation for the members of class Action::Actions.
While here, also tag data members with a trailing underscore, split name-based action object lookup out to a helper function, and split some long lines.

Document Action Object Collection

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/Well/NameOrder.cpp
opm/input/eclipse/Schedule/Well/NameOrder.hpp

This PR introduces a new member function
```C++
std::vector<std::string> GroupOrder::names(const std::string& pattern)
```
which returns a sequence of group names that match a certain pattern.  This is in preparation of adding such group name pattern matching in UDQ contexts, especially for assignments.  We then reimplement `Schedule::groupNames(const std::string& pattern)` in terms of this new member function.
While here, also add Doxygen-style documentation to the `NameOrder` and `GroupOrder` classes, and simplify some of the related functions in the `Schedule` class.

Push Group Name Pattern Matching Into GroupOrder Class

---

CMakeLists_files.cmake
opm/common/OpmLog/OpmLog.cpp
opm/common/OpmLog/OpmLog.hpp
opm/input/eclipse/Python/PyRunModule.cpp
python/cxx/log.cpp
tests/logger.py
tests/parser/PYACTION.cpp

This PR fixes logging messages with the OpmLog from embedded Python code.
This used to work and then stopped working at some point, I've now added a test for this (https://github.com/OPM/opm-common/pull/4440/commits/07fb92733edd72b0014d8d920d577da6b8a879c4) and made the test pass.
The issue was that the internal logger of the static class OpmLog was not set when OpmLog was called from embedded python code.
I have added a function [setLogger](https://github.com/OPM/opm-common/pull/4440/files#diff-a70a2bb12ffbd4bb87c6cf329a5ca80fe3e2e99f93132c0e467c78fa6d082c89R56) to the OpmLog such that the Logger can be set using [a python function on the python object OpmLog](https://github.com/OPM/opm-common/pull/4440/files#diff-34cbbda5f94972afb132c4c5a03f2b881c4da5b820b74eb2ee1569aab9180cf7R47).
I'm …

Fix PyAction OpmLog

---

opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp

The attached variant of [NETWORK_MODEL5_STDW_AUTOCHK_V2.DATA](https://github.com/OPM/opm-tests/blob/master/network/NETWORK_MODEL5_STDW_AUTOCHK.DATA) illustrates the problem (crashes in master, should work with this PR): 
[NETWORK_MODEL5_STDW_AUTOCHK_V2.DATA.gz](https://github.com/user-attachments/files/18454068/NETWORK_MODEL5_STDW_AUTOCHK_V2.DATA.gz)

Ensure setting GRUP control in WCONPROD works for wells in auto-choke groups

---

opm/input/eclipse/Schedule/Action/ActionAST.cpp
opm/input/eclipse/Schedule/Action/ActionParser.cpp
opm/input/eclipse/Schedule/Action/ActionParser.hpp
opm/input/eclipse/Schedule/Action/ActionX.cpp
opm/input/eclipse/Schedule/Action/Condition.cpp
tests/parser/ACTIONX.cpp

Client code does not need to know that we have a stateful object which tracks the current "token position" while recursively constructing the condition tree.  To this end, move the "parser" type into the .cpp file and provide a top-level entry point,
```C++
unique_ptr<ASTNode> parseCondition(const vector<string>& tokens)
```
that will form the actual condition evaluation tree (`ASTNode`).  This also removes the otherwise orphaned `ParseNode` type.  We return a `unique_ptr` because that's directly usable in the `AST` type (PR #4442).
While here, also add a bit of documentation to the parser's member functions to help future maintainers understand each function's role&ndash;especially the `parse_*()` functions.

Simplify Action Condition Parsing API

---

cmake/Modules/OpmDefaults.cmake
cmake/Modules/OpmInit.cmake
cmake/Modules/OpmSatellites.cmake

minimum version (as indicated with cmake_minium_required) is atleast 3.10 which was released in 2017

prune support for old cmake versions in build system

---

opm/output/eclipse/Inplace.cpp
opm/output/eclipse/Inplace.hpp

Currently this code is in anon namespace in https://github.com/OPM/opm-simulators/blob/master/opm/simulators/flow/GenericOutputBlackoilModule.cpp#L69
Working on some refactoring and need access to this function in several contexts. Figured closer to home is the appropriate location for this code. While at it I replaced the switch nest with a map lookup.

added: translation helper for Inplace::Phase -> ECL textual represention

---

opm/material/common/Tabulated1DFunction.hpp

Separated out since it needs downstream changes and it can be argued that this ctor not being explicit has merit.

Tabulated1DFunction: mark constructor explicit

---

opm/input/eclipse/Schedule/Action/ASTNode.cpp
tests/parser/ACTIONX.cpp

This PR translates `ACTIONX` condition region quantities of the form
```
RPR 1 RE3
```
i.e., including the region set name `RE3` (FIPRE3) into the common summary vector format
```
RPR__RE3 1
```
which is expected elsewhere.  Doing so enables using the former syntax in `ACTIONX` conditions like
```
RPR 1 RE3 < 215 /
```
without incurring significant downstream changes in the vector evaluation code.  Defaulted (`'1*'`) or blank (`' '`) region set names are treated as the default region set (FIPNUM).

Canonicalise Region Selectors in Action Conditions

---

opm/output/eclipse/LoadRestart.cpp

Empty UDQ names ('________') may be written to the restart file, which cause empty UDQ strings upon load, and assertion failure in `udq.front()`...

Do not try to restore UDQ unit strings as UDQ vars

---

CMakeLists_files.cmake
opm/common/utility/ConstexprAssert.hpp

this will cause a compile time error if used at compile time and a regular assert if used at runtime

added: constexpr_assert macro

---

opm/input/eclipse/Schedule/MSW/Segment.cpp
opm/input/eclipse/Schedule/MSW/Segment.hpp

fixed: sadly, std::pow is not constexpr with clang

---

examples/rst_deck.cpp
opm/input/eclipse/Deck/FileDeck.cpp
opm/input/eclipse/Deck/FileDeck.hpp

In particular,
- Reduce scope of objects
- Make types that don't need to be `public:` into `private:`
- Push all uses of libfmt into .cpp files
- Make objects 'const' where possible
- Split long lines

Varnish FileDeck and rst_deck Implementations

---

opm/material/common/FastSmallVector.hpp

Quells downstream warning
```
In file included from /home/akva/kode/opm/opm-common/opm/material/densead/EvaluationSpecializations.hpp:34,
from /home/akva/kode/opm/opm-common/opm/material/densead/Evaluation.hpp:631,
from /home/akva/kode/opm/opm-simulators/opm/simulators/aquifers/AquiferAnalytical.hpp:32,
from /home/akva/kode/opm/opm-simulators/opm/simulators/aquifers/AquiferCarterTracy.hpp:30,
from /home/akva/kode/opm/opm-simulators/opm/simulators/aquifers/BlackoilAquiferModel.hpp:32,
from /home/akva/kode/opm/opm-simulators/opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp:43,
from /home/akva/kode/opm/opm-simulators/flow/flow_oilwater_polymer.cpp:25:
In member function ‘Opm::DenseAd::Evaluation<ValueT, -1, staticSize>& Opm::DenseAd::Evaluation<ValueT, -1, staticSize>::operator-=(const …
```

FastSmallVector: initialize array member

---

CMakeLists_files.cmake
opm-common-prereqs.cmake

There is a buildsystem global way to enable/disable OpenMP. We should not be manually looking for it in prereqs.
Also disable openmp-only test when openmp is disabled.

Fix OpenMP

---

CMakeLists_files.cmake
opm/common/CriticalError.hpp
tests/test_critical_error.cpp

I have added a simple exception class `CriticalError` which is supposed to wrap normal exceptions and rethrow them as critical exceptions where errors can not be recovered easily.
This is relevant for the linear solver system where a caught exception is typically treated by lowering time steps. This leads to the unfortunate side effect that some errors^* in the JSON file will be treated by reducing time steps until the limit is reached and the simulation is crashed, with few error messages to the actual problem that caused the problem.
One could also add a constructor that only takes an error message to let coders directly throw a critical error message.
^* Setting `--linear-solver` to point to the following json will cause this behaviour:
```JSON
{
"preconditioner": "ParOverILU0"
}
``` …

Introduced the CriticalError exception class.

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp
tests/parser/LgrOutputTests.cpp

**PR Description:**  
This PR introduces routines for parsing the refinement into `EclipseGrid` object. The key changes include:
- `EclipseGrid::set_lgr_refinement` and `EclipseGridLGR::set_lgr_refinement` now allow applying LGR refinements based on a specified tag (`lgr_tag`), coordinates (`coord`), and `zcorn` values.  
- The `set_lgr_refinement` calls in `LgrOutputTests.cpp` were updated to use the new method with `lgr_tag`.

Add utility methods to parse LGR refinement.

---

opm/material/fluidsystems/BlackOilDefaultIndexTraits.hpp
opm/material/fluidsystems/BlackOilFluidSystem.hpp

The one/two phase indices class uses negative values for inactive components (though not really relevant, but it's a source of confusion). Likewise, the GenericOilGasFluidSystem uses ints. 
To avoid nasty casts in generic code, make the fluidsystems consistently use int, even though the blackoil indices are always positive.

BlackoilFluidSystem: use int for component indices

---

CMakeLists_files.cmake
opm/common/utility/numeric/GridUtil.cpp
opm/common/utility/numeric/GridUtil.hpp
tests/test_Uns2CPG.cpp

Grid Utility Functions for Unstructured Grid Conversion into CPG format
This pull request introduces a set of utility functions in the `GridUtil` namespace to facilitate unstructured grid indexing and conversion from an unstructured mesh representation to a corner-point grid (CPG) format. The key functions include:
- `pillar_to_flat_array(pillar)`: Flattens a pillar-based coordinate representation into a linear array.
- `convertUnsToCPG(coord_uns, element, nx, ny, nz)`: Converts an unstructured mesh into a corner-point grid representation, generating `coord_cpg` and `zcorn_cpg` arrays.
- Introduced `convertUnsToCPG`, which processes an unstructured mesh into a corner-point grid representation by:
- Extracting pillar coordinates.
- Mapping mesh elements to pillar-based coordinates.
- …

 Grid Utility Functions for Unstructured Grid Conversion into CPG format

---

CMakeLists_files.cmake
opm/material/constraintsolvers/PTFlash.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerHystParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerInitParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp
opm/material/fluidsystems/Co2BrineFluidSystem.hh
opm/material/fluidsystems/GenericOilGasFluidSystem.hpp
opm/material/fluidsystems/GenericOilGasWaterFluidSystem.hpp
opm/material/fluidsystems/PTFlashParameterCache.hpp
opm/material/fluidsystems/ThreeComponentFluidSystem.hh
tests/material/test_fluidsystems.cpp

The compositional fluid system is expanded to three phases where the water phase is a "dummy"/immiscible phase. Water phase properties are given through PVT functions the same way as in the black oil fluid system.

Added "dummy" water phase to compositional fluid system

---

opm/material/fluidmatrixinteractions/EclHysteresisConfig.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp

In particular move some simplified query functions from the manager to the config class.
This allows downstreams to only work with the config class, and still not know the internal magic numbers.

Some improvements to EclHysteresisConfig

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp

Since EclipseGrid is now inherited from, I added a virtual destructor, eliminating a warning from clang. Possibly this fixes a real problem (incomplete deletion of object) if you own EclipseGridLGR objects from EclipseGrid (smart) pointers, not sure if that actually happens in the code currently.
Also reindented and reformatted, giving EclipseGridLGR the standard 4-space indent, and removing tons of end-of-line whitespace.

Some polish for EclipseGrid, EclipseGridLGR

---

opm/input/eclipse/Schedule/Group/Group.cpp
opm/input/eclipse/Schedule/Group/Group.hpp
opm/input/eclipse/Schedule/Group/GroupKeywordHandlers.cpp
opm/input/eclipse/Schedule/Network/ExtNetwork.cpp
opm/input/eclipse/Schedule/Network/ExtNetwork.hpp
opm/input/eclipse/Schedule/Network/NetworkKeywordHandlers.cpp
opm/input/eclipse/Schedule/Network/Node.cpp
opm/input/eclipse/Schedule/Network/Node.hpp
opm/input/eclipse/Schedule/Well/Well.cpp
opm/input/eclipse/Schedule/Well/Well.hpp
opm/input/eclipse/Schedule/Well/WellPropertiesKeywordHandlers.cpp
opm/input/eclipse/share/keywords/000_Eclipse100/G/GEFAC
opm/input/eclipse/share/keywords/000_Eclipse100/W/WEFAC
tests/parser/GroupTests.cpp
tests/parser/WellTests.cpp

No restart support here - will come in a separate PR.

Support instantaneous flow rates in extended network (WEFAC and GEFAC item 3)

---

opm/io/eclipse/rst/well.cpp

The `ISEG[0]` sequence does not follow the regular segment numbering so we can't use that value to determine if a segment is active, especially not if there are gaps in the segment numbering.
While here, also refactor the `RstSegment` creation process, and especially the offsets into `ISEG` and `RSEG`, to better demonstrate each constituent part.

Check Branch Number to Determine if Segment is Active at Restart Time

---

opm/input/eclipse/Parser/Parser.cpp
tests/parser/ParseContextTests.cpp

When the file is parsed, anything after '/' is treated as a comment with one exception. When parser expects a keyword but the line contains something else, the function `handleRandomText` (which body was addressed in this commit) is called. If the line contains only a single '/', the response depends on the `PARSE_RANDOM_SLASH` variable (throw, warn, or ignore). 
This is the only place where the text after '/' makes a difference and this commit removes the irregularity.

Unify parsing lines starting with slash

---

opm/input/eclipse/Schedule/Well/Well.cpp
opm/input/eclipse/Schedule/Well/Well.hpp
opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp
tests/parser/WellTests.cpp

This pull request introduces several enhancements to the well handling capabilities, specifically focusing on Local Grid Refinement (LGR) wells. The main changes include:
- **Implementation of the `WELSPECL` keyword** to handle wells specified in LGR regions.
- **Addition of new methods** in the `Well` class to manage LGR wells, including methods to flag, set, and retrieve LGR well tags.
- **Unit tests** added to verify the correct handling of LGR wells and the `WELSPECL` keyword.
- Added `WellLGR` test with a string containing a deck with two LGR wells.
- Created `handleWELSPECL` method to manage `WELSPECL` keyword.
- Implemented `WELSPECL` keyword and added unit tests to verify well handling in LGR regions.

Implement LGR Wells Handling and WELSPECL Keyword Support

---

opm/common/ErrorMacros.hpp
opm/common/utility/gpuDecorators.hpp

This will allow us to keep code such as 
```C++
OPM_THROW(std::exception, "Message");
```
also in the GPU kernels. The alternative would be to wrap every such throw-statement in the following manner:
```C++
#if OPM_IS_INSIDE_DEVICE_FUNCTION
assert(false);
#else
OPM_THROW(std::exception, "Message");
#endif
```
Note that while it is possible to supply the message to assert as well, this is not really practically feasible in all the places the throw macro is used, and it is probably not needed either.
While not necessary for this to build, I have also included unit tests for the updated macros in the [opm-simulators PR 5962](https://github.com/OPM/opm-simulators/pull/5962)

Error macros now have GPU variant.

---

opm/input/eclipse/Schedule/Well/WellPropertiesKeywordHandlers.cpp

If the WEFAC keyword is run from an ACTIONX block in the middle of a report step, then we need to notify the simulator in order that the factor be immediately updated in the simulator.  Abuse the "well structure changed" notification (commit 5f0941677, PR #3600) to signal that the simulator's notion of its wells must be updated in this case.
While here, switch to using compiled item names in the WEFAC keyword handler to add a little bit of compile-time error checking if these names ever change.

Notify Simulator Layer if Well's Efficiency Factor Changes

---

opm/input/eclipse/Schedule/ScheduleState.hpp

NVCC seems to evaluate the `else` branch of a chain of `constexpr if` even though the `else` branch is never instantiated. 
We need this fix since we will at some point include the fixed header file in a `.cu` file compiled by NVCC.

Fix for NVCC

---

opm/input/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp
opm/input/eclipse/Schedule/ScheduleState.cpp
opm/input/eclipse/Schedule/ScheduleState.hpp
opm/input/eclipse/Schedule/Well/Well.hpp
opm/input/eclipse/Schedule/Well/WellInjectionProperties.cpp
opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp
opm/input/eclipse/share/keywords/001_Eclipse300/W/WELLSTRE
opm/input/eclipse/share/keywords/001_Eclipse300/W/WELL_PROBE_COMP
opm/material/constraintsolvers/PTFlash.hpp

This PR is providing some necessary elements for the compositional simulation with wells. It mostly including the following elements, 
1. parsing the schedule keywords WINJGAS and WELLSTRE
2. making PTFlash::solve() can handle arbitrary number of derivatives from the input AD variables. 
3. adding WAMF in the summary keywords
The PR can be reviewed and merged by itself without the downstream PR https://github.com/OPM/opm-simulators/pull/6042 .

Compositional well

---

opm/input/eclipse/Schedule/UDQ/UDQActive.cpp
opm/input/eclipse/Schedule/UDQ/UDQActive.hpp
opm/io/eclipse/rst/udq.cpp
opm/io/eclipse/rst/udq.hpp
opm/output/eclipse/AggregateUDQData.cpp
opm/output/eclipse/VectorItems/udq.hpp
tests/parser/UDQTests.cpp

Commit 937d69d23 (PR #4357) treated `IUAD[2]` as a type flag, with the value 1 signifying a UDA at the well- or "regular" group level and the value 2 signifying a FIELD level UDA.  This PR revises this interpretation and instead treats `IUAD[2]` as the corresponding number of IUAP elements for the UDA.
This is in preparation of some upcoming compatibility work.

Revise Interpretation of IUAD[2]

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/VFPProdTable.cpp
opm/input/eclipse/Schedule/VFPProdTable.hpp

This commit amends the ALQ restart dimension handling of commit dac5e4ec7 (PR #4271) to also include VFP tables that are defined at the restart step itself.  The most common case for this is when the restart run does not use SKIPREST, but instead proceeds directly to begin the simulation based on objects from the restart file.  In this case, the input is typically structured as
SOLUTION
RESTART
'BASE' 42 /
SUMMARY
-- ...
SCHEDULE
INCLUDE
'vfp-tables.inc' /
TSTEP
9*10.11 /
-- ...
END
and we need to be sure that the VFP tables from 'vfp-tables.inc' are usable for determining the ALQ types and their corresponding Dimension objects.
To this end, we create a simple helper class,
ALQTypesAtRestartTime
which aggregates the ALQ types of any previously loaded VFP tables …

Load ALQ Types From Restart Step's VFP Tables if Available

---

opm/material/binarycoefficients/Brine_CO2.hpp

Note In Spycher Pruess 2010 they say 31C which is inconsistent with the critical temperature (30.95C) we use in OPM. For consistancy we change to critical temperature.

Only compute psat when needed

---

opm/material/fluidstates/BlackOilFluidState.hpp

Static variables do not work well on the GPU, so these have to be removed in some way.
We also have set-functions for all of these variables so I do not really see why we should allocate extra static variables here, running the tests now to make sure this is safe.

remove scalar references and static variables

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp

this will be used in action handling to avoid re-processing events that only should execute at start of a report step

added: utility function to clear out all events at a given report step

---

opm/input/eclipse/Schedule/Schedule.cpp
opm/io/eclipse/rst/group.cpp
opm/io/eclipse/rst/group.hpp
opm/io/eclipse/rst/network.hpp
opm/output/eclipse/AggregateGroupData.cpp
opm/output/eclipse/VectorItems/group.hpp

This PR ensures that the setting for whether or not the lift gas of a leaf node's corresponding group's subordinate wells should be added to the node's produced gas entering the node in an extended model production network.  In short, this commit saves and restores [item 4](https://github.com/OPM/opm-common/blob/a6e4b524da7ee6edf3d5ac07540fcb9d3fbaf4b2/opm/input/eclipse/share/keywords/000_Eclipse100/N/NODEPROP#L26-L31) of `NODEPROP` for leaf nodes in an extended network.

Save and Restore Network Node's Lift Gas as Produced Gas Setting

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp

Replace string vector return types with reference wrappers in `get_all_lgr_labels()` and `get_all_labels()` to avoid unnecessary string copying. This change improves performance and reduces memory usage when working with label collections.
- Modified `get_all_lgr_labels()` to return `std::vector<std::reference_wrapper<const std::string>>` 
- Modified `get_all_labels()` to use the same reference-based approach
**I have accidentally closed this PR and therefore I am reopening it.**

LGR: Optimize label retrieval functions to use references instead of copies

---

opm/input/eclipse/EclipseState/Tables/TableManager.cpp
opm/input/eclipse/share/keywords/900_OPM/P/PERMFACT

This adds flexibility to set different `PERMFACT` tables per `SATNUM`.
Relevant for the Reference Manual (I will do a PR to the manual to document this).

PERMFACT for each saturation region

---

opm/input/eclipse/Schedule/MSW/Compsegs.cpp

Some tools output distance_start = distance_end for very short perforation lengths, so allowing this would be convenient.

Allow zero-length records in COMPSEGS

---

opm/io/eclipse/rst/group.hpp
opm/io/eclipse/rst/well.hpp

That way we don't impose a second `double` :arrow_right: `float` conversion after `float` :arrow_right: `double` for unit conversion.  This enables reaching the maximum lift gas injection rate in an example model, but is nevertheless at best a stop-gap measure.  GLO results in restarted runs typically do not yet match those of the base run.

Store GLO Limits as Double Precision on Restart

---

opm/input/eclipse/Schedule/MSW/WellSegments.cpp
opm/input/eclipse/Schedule/MSW/WellSegments.hpp
opm/input/eclipse/Schedule/Well/Well.cpp
tests/parser/MultisegmentWellTests.cpp

It will give warning when there is segments that are defined with depth change larger than the segment length. 
Something like the following,
```
Warning:  Segment 3 of well PROD01 has a depth change of 26 meters, while it has a length of 25 meters, which is unphysical.
Warning:  Segment 4 of well PROD01 has a depth change of 33 meters, while it has a length of 25 meters, which is unphysical.
```
It is using the internal unit system `SI`, it might be better to use the original unit from the DATA file, while it might be more involved. Please suggest.

trying to warn about too big segment depth change

---

opm/input/eclipse/Schedule/Group/Group.cpp
opm/input/eclipse/Schedule/Schedule.cpp

It needs https://github.com/OPM/opm-common/pull/4439 to have the fully support to restart from case with GCONINJE setup. 
This PR only contains how to recover the running from the RESTART information, https://github.com/OPM/opm-common/pull/4439  will output the relative information to the RESTART file.

restarting from case with GCONINJE setup

---

opm/output/eclipse/EclipseIO.cpp
opm/output/eclipse/EclipseIO.hpp

The objective of this work is to reduce the reader's cognitive load when working with the `EclipseIO::writeTimeStep()` function.  To this end, pull most of the detailed instructions into individual helper functions in the `EclipseIO::Impl` class, such as
* `Impl::writeSummaryFile()`
* `Impl::writeRestartFile()`
* `Impl::writeRftFile()`
* `Impl::writePrtFileReports()`
* `Impl::loadRestart()`
This furthermore enables making the data members of `EclipseIO::Impl` `private` which prevents writing code that accesses these objects directly.

Refactor Top Level EclipseIO Implementation

---

opm/input/eclipse/Schedule/Action/ActionX.cpp
opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp

This is now battle tested by the client.

Support  WCONHIST/WCONINJ in ACTIONX

---

CMakeLists_files.cmake
opm/common/utility/CSRGraphFromCoordinates.hpp
opm/common/utility/CSRGraphFromCoordinates_impl.hpp
tests/test_CSRGraphFromCoordinates_Merge.cpp

This PR adds vertex merging functionality to the `CSRGraphFromCoordinates` class. This class is used as a backend for creating the input to the partitioner in nonlinear domain decomposition (NLDD). The main purpose of this new functionality is to support grouping cells perforated by a well into a single entity before subdomain partitioning. However, the implementation is general and can be used for other methods that use this class. This ensures that no well can be split across NLDD subdomains, which allows supporting NLDD for more complicated field cases and creating better partitions around wells.
The implementation uses a disjoint-set (union-find) data structure to efficiently track vertex groups and their relationships. Overlapping vertex groups are automatically merged. When merges …

Add vertex merging functionality to CSRGraphFromCoordinates

---

opm/output/eclipse/Summary.cpp

needed for MSW PRT report
I'm not sure about the SxFV entries, there is no type for velocity, not sure what the consequence of the parameter is.

make SxHF, SxFV and SPRxx required segment summary entries

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/CompletedCells.cpp
opm/input/eclipse/Schedule/CompletedCells.hpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/input/eclipse/Schedule/Schedule.hpp
opm/input/eclipse/Schedule/ScheduleGrid.cpp
opm/input/eclipse/Schedule/ScheduleGrid.hpp
tests/parser/ACTIONX.cpp
tests/parser/FieldPropsTests.cpp
tests/parser/GeomodifierTests.cpp
tests/parser/GroupTests.cpp
tests/parser/MessageLimitTests.cpp
tests/parser/NetworkTests.cpp
tests/parser/ParseContextTests.cpp
tests/parser/ReservoirCouplingTests.cpp
tests/parser/ScheduleSerializeTest.cpp
tests/parser/ScheduleTests.cpp
tests/parser/TuningTests.cpp
tests/parser/UDQTests.cpp
tests/parser/UDTTests.cpp
tests/parser/WLIST.cpp
tests/parser/WellSolventTests.cpp
tests/parser/WellTests.cpp
tests/parser/WellTracerTests.cpp
tests/parser/integration/ParseKEYWORD.cpp
tests/parser/integration/ScheduleCreateFromDeck.cpp
tests/test_CompletedCells.cpp
tests/test_InteHEAD.cpp
tests/test_ScheduleGrid.cpp

This PR adds support for numerical aquifers to the main grid portion of the `ScheduleGrid` dynamic container.  In turn, this means we extract properties such as the permability, porosity, and net-to-gross ratio from the numerical aquifer object instead of the main grid's property container if a `CompletedCells::Cell` happens to be in a numerical aquifer.  This enables inferring proper values for the $Kh$ product and the connection length which go into various reports and, importantly, the `SCON` restart file array.  Prior to this, we would risk getting NaN values for these quantities as the main grid's permeability value would be [explicitly reset to zero](https://github.com/OPM/opm-common/blob/09c29a356fa81db03ba2b8a1db500d765941cc40/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp#L231 …

Get COMPDAT Properties From Numerical Aquifer if Needed

---

opm/input/eclipse/Schedule/RSTConfig.cpp
opm/input/eclipse/Schedule/RSTConfig.hpp
opm/io/eclipse/RestartFileView.cpp
opm/io/eclipse/RestartFileView.hpp
opm/output/eclipse/EclipseIO.cpp
opm/output/eclipse/EclipseIO.hpp
opm/output/eclipse/LoadRestart.cpp
opm/output/eclipse/RestartIO.hpp
tests/parser/RestartConfigTests.cpp

This will be used to generate initial FIP report in restarted runs.
Also adds a related helper function which only loads solution data from the restart file. This is needed, as
the output at report step 0 does not contain all data.

changed: always write step 0 to restart file

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/RPTConfig.cpp
opm/input/eclipse/Schedule/RPTConfig.hpp
opm/input/eclipse/Schedule/RPTKeywordNormalisation.cpp
opm/input/eclipse/Schedule/RPTKeywordNormalisation.hpp
opm/input/eclipse/Schedule/RSTConfig.cpp
opm/input/eclipse/Schedule/RXXKeywordHandlers.cpp
opm/input/eclipse/Schedule/RptschedKeywordNormalisation.cpp
opm/input/eclipse/Schedule/RptschedKeywordNormalisation.hpp
opm/input/eclipse/Schedule/SimpleRPTIntegerControlHandler.cpp
opm/input/eclipse/Schedule/SimpleRPTIntegerControlHandler.hpp
tests/test_RPTConfig.cpp

The "integer control" format support in `RPTSCHED` influenced only the restart-like processing in `RSTConfig` and had no counterpart in the `RPTConfig` class.  This commit corrects this omission and restores PRT file report generation for the older style `RPTSCHED` keyword.  As an example, the `NORNE_ATW2013` example model now gets injection, production, cumulative and `WELSPECS` reports whereas this was missing before.
We don't expect that there are many new cases using this format, but this commit does at ensure that we don't remove useful reports for some existing simulation models.
To this end, extract the restart-like integer control handling to a new helper class, `RPTKeywordNormalisation`, which consumes both mnemonics and integer controls and generates a `map<string,int>` of …

Support Report Generation With Integer Controls

---

python/tests/test_emodel.py

The sum function in Python 3.12 switched to using Neumaier summation for floats for better accuracy. This broke one of the unit tests. With this change we use numpy.sum to fix the failing test, which still uses the not so accurate summation algorithm of sum as in Python 3.11
Not really a patch that I am proud of. Our way of testing is a bit shaky here.

Use numpy.sum instead of sum to fix test with Python 3.12 

---

opm/output/eclipse/WriteRPT.cpp
opm/output/eclipse/WriteRPT.hpp
opm/output/eclipse/report/WELSPECS.cpp

In particular,
- Split long lines.
- Switch to initialising objects, especially references, using assignment syntax (`=`) instead of construction (`{}`).
- Move function opening braces to next line.
- Remove blanks before semicolons.
- Apply `const` where reasonable.
- Move static objects into function-local scopes where reasonable.
- Reverse conditionals to enable "early continue".
- Rename `workers::write_WELSPECS()` to `workers::wellSpecification()`.
This is in preparation to replacing hard-coded date stamps with dynamic information.

Varnish WELSPECS Report Implementation

---

opm/output/eclipse/report/WELSPECS.cpp

This PR replaces the static "RUN AT" timestamp currently used in the `WELSPECS` report (`RPTSCHED` keyword) with the current (local) time when the report is emitted.
As an example, following #4526, the NORNE_ATW2013 PRT file contains well specification report headers of the form
```
Report step  7/247 at day 143/3312, date = 29-Mar-1998
**************************************************************************                             
WELSPECS AT       0.00 DAYS *                                                                        * FLOW                        
REPORT   0     31 DEC 2007  *                                                                        * RUN AT 12:41 ON 12 SEP 2016 
************************************************************************** …
```

Use Dynamic Timestamp in WELSPECS Report

---

CMakeLists_files.cmake
opm/output/eclipse/EclipseIO.cpp
opm/output/eclipse/WriteRPT.cpp
opm/output/eclipse/report/WellSpecification.cpp
opm/output/eclipse/report/WellSpecification.hpp

This PR replaces the hard-coded "REPORT" and "WELSPECS" strings with ones derived from the actual elapsed time and report step dates.
While here, rename the `WELSPECS.cpp` file to something slightly more human friendly and move the function declaration to a separate header.  Furthermore, pull the MSW reports for individual wells out to separate helper functions to limit the cognitive load for readers of the main `wellSpecification()` function.

Use Dynamic Elapsed Time and Dates for WELSPECS Report

---

opm/input/eclipse/Schedule/Source.cpp
opm/input/eclipse/Schedule/Source.hpp
tests/parser/ScheduleTests.cpp
tests/parser/SourceTests.cpp

With many entries in SOURCE, which can be the case when coupling other simulators to Flow, looking up a vector was very slow. Changing the structure to std::map makes looking up ijk indices much faster.
Removed the functions "hasHrate" and "hasTemperature" since "hrate" and "temperature" functions now return std::optional which can be used for checking instead.
Companion PR: https://github.com/OPM/opm-simulators/pull/6140

Faster SOURCE lookup with many entries

---

CMakeLists_files.cmake
examples/networkgraph.cpp

The PR is introducing a new application networkgraph. This can be used to visualize a production network (extended network model). This visualization is also including wells. 
Input for this program can be both a data deck and an unified restart file.  The user can specify the report step to be visualized with option -r. Default report step is the final report step.
Output from this application run with model 
https://github.com/OPM/opm-tests/blob/master/model5/5_NETWORK_MODEL5_STDW.DATA
output to the terminal will be like this.
```
Report step : 01 'JUL' 2020 00:00:00
o (PLAT-A) --[5]-- +(B1) :  B-1H B-2H B-3H
\
--[4]-- +(C1) :  C-1H C-2H
Fixed pressure nodes: 
PLAT-A = 21.00
```

New application for viewing a production network

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/ScheduleState.hpp
opm/input/eclipse/Schedule/Well/WellFractureSeeds.cpp
opm/input/eclipse/Schedule/Well/WellFractureSeeds.hpp
opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp
opm/input/eclipse/share/keywords/900_OPM/W/WSEED
opm/input/eclipse/share/keywords/keyword_list.cmake
tests/parser/ScheduleSerializeTest.cpp
tests/parser/ScheduleTests.cpp
tests/test_Serialization.cpp
tests/test_WellFractureSeeds.cpp

This PR introduces a new, OPM specific, SCHEDULE section keyword
```
WSEED
```
for use in defining seed points for hydraulic fracturing.  This keyword is limited to use in the context of runs that enable geomechanical processing through the `MECH` keyword in the RUNSPEC section.  When enabled, the `WSEED` keyword has the following general structure
```
WSEED
WellName  I J K  nx ny nz /
WellName  I J K  nx ny nz /
-- ...
WellName  I J K  nx ny nz /
/
```
in which `WellName` is a well name, a well name template, a well list, or a well list template.  I,J,K are coordinates of existing reservoir connections (COMPDAT keyword) and nx,ny,nz are components of a vector normal to fracturing plane.  They need not be a unit vector.  All keyword items are required.
We collect all seeds for a single …

Add New Keyword for Hydraulic Fracturing Seeds at Well Connections

---

examples/networkgraph.cpp

Some standard janitoring chores.
whitespace, braces, constness, use of standard algorithms (to quell sca warnings), removal of unused members.
Not entirely sure about the last commit, it removes a method that is unused, that maybe was used during development, maybe is intended to be used later. If the latter I'll change the commit to comment it out instead.

NetworkGraph: some janitoring

---

external/resinsight/LibCore/cvfAssert.cpp
external/resinsight/LibCore/cvfAssert.h

While this is very minor since it's just some small global data being reachable at end of application, it clogs up valgrind error logs and is an easy fix so..

fixed: plug minor memory leak

---

opm/material/components/TabulatedComponent.hpp

And tidy up some other things while at it.
While the leak is minor, in that nobody is likely to call this more than once in a run, it clogs up valgrind error logs.

TabulatedComponent: fix memory leak

---

opm/ml/ml_model.cpp
opm/ml/ml_model.hpp
python/opm/ml/ml_tools/kerasify.py
tests/ml/ml_model_test.cpp
tests/ml/ml_tools/generateunittests.py

All files based on those of https://github.com/moof2k/kerasify should keep the same license.
The exceptions are files that we have generated ourselves. I men those below tests/ml/ml_tools/include/ and tests/ml/ml_tools/model. The former is contained only code from NORCE, for the latter I have no idee, yet.
It would make my life a but easier if this makes it into the release. Otherwise I will backport to the packages.
This is already checked by @totto82

Use correct MIT license for all files based on kerasify

---

cmake/Modules/DownloadFmt.cmake

With gcc 14.2.0 (Ubuntu 24.10), I get a lot of warnings like this
```
/home/hakon/test/opm/opm/opm-simulators/build/_deps/fmt-src/include/fmt/ranges.h:215:59: warning: self-comparison always evaluates to true [-Wtautological-compare]
215 |                                integer_sequence<bool, (Is == Is)...>);
|                                                        ~~~^~~~~
```
when compiling. By adding the `SYSTEM` option to `include_directories()` for the format library, cmake will skip the warnings for the format library headers. See also: https://github.com/fmtlib/fmt/issues/3830

Prevent tautological-compare warnings for format.h with gcc 14.2.0

---

cmake/Modules/FindAMGX.cmake

Library no longer exists in cuda 12.9. While this should really be a AMGX version check, there is no version there to check, it has not had a release in years.

remove nvToolsExt from AMGX dependency list

---

opm/output/eclipse/Summary.cpp

Changed the names of arguments representing the numerator and denominator of the division.
I think div_unit() should convert volume/time to rate NOT rate/time to volume.

Fix div_unit

---

CMakeLists_files.cmake
opm/material/fluidsystems/BlackOilDefaultFluidSystemIndices.hpp
opm/material/fluidsystems/BlackOilFluidSystem.cpp
opm/material/fluidsystems/BlackOilFluidSystem_macrotemplate.hpp
opm/material/fluidsystems/BlackOilFunctions.hpp
opm/material/thermal/EclThermalLawManager.cpp

Motivation is to more clearly name the various classes providing indices.
Downstream PR also required.

Rename BlackOilDefaultIndexTraits -> BlackOilDefaultFluidSystemIndices

---

opm/io/eclipse/ESmry.cpp
opm/io/eclipse/ESmry.hpp

WIth this PR we are now able to open summary files (SMSPEC and UNSMRY) from simulator TNavigator using Opm::EclIO::ESmry.

Ignoring TNavigator spesific arrays in summary file

---

opm/input/eclipse/Parser/ParseContext.cpp

Following the introduction (6d7d82dd8, #4362) and use (OPM/opm-simulators@0238f4533, OPM/opm-simulators#5765) of member function `ErrorGuard::formattedErrors()`, the diagnostic messages for `DELAYED_EXIT1` will be printed to both the console and the PRT file at the end of the parsing process.  There is no longer a need to print these immediately at the point of the `ParseContext::handleError()` call.

Don't Log Errors Immediately for DELAYED_EXIT1

---

opm/input/eclipse/Schedule/UDQ/UDQASTNode.cpp
opm/input/eclipse/Schedule/UDQ/UDQASTNode.hpp
opm/input/eclipse/Schedule/UDQ/UDQDefine.cpp
opm/input/eclipse/Schedule/UDQ/UDQDefine.hpp
opm/input/eclipse/Schedule/UDQ/UDQEnums.hpp
tests/parser/UDQTests.cpp

This PR adds a simple structure for holding Schedule objects that are needed to evaluate the defining expression of a UDQ.  The immediate use case is to enable issuing diagnostic messages for UDQ DEFINE statements that name objects&ndash;e.g., wells or groups&ndash;which do not exist at the point of definition.
We give the `UDQDefine` class the ability to generate this kind of collection by recursively populating the collection through its child `ASTNode`.

Support Identifying Requisite UDQ Schedule Objects

---

opm/input/eclipse/Schedule/Well/WList.cpp
opm/input/eclipse/Schedule/Well/WList.hpp
opm/input/eclipse/Schedule/Well/WListManager.cpp
opm/input/eclipse/Schedule/Well/WListManager.hpp

In particular split the function into three helpers to deal with the individual cases,
- New list where none exist (`createNewWList()`)
- New empty list with existing name (`clearExistingWList()`)
- New non-empty list with existing name (`resetExistingWList()`)
There are further opportunities to simplify this class, but this handles the most immediate readability issues and enables making `WList::wells()` return a reference to its internal vector instead of a copy of the same.

Tidy Up WListManager::newList Implementation

---

opm/input/eclipse/Schedule/HandlerContext.cpp
opm/input/eclipse/Schedule/HandlerContext.hpp
opm/input/eclipse/Schedule/Well/NameOrder.cpp
opm/input/eclipse/Schedule/Well/NameOrder.hpp
opm/input/eclipse/Schedule/Well/WList.hpp
opm/input/eclipse/Schedule/Well/WListManager.cpp
opm/input/eclipse/Schedule/Well/WListManager.hpp
opm/input/eclipse/Schedule/Well/WellMatcher.cpp
opm/input/eclipse/Schedule/Well/WellMatcher.hpp
tests/parser/ScheduleTests.cpp

This enables slightly less expensive existence checks than calling `Schedule::wellNames()` and `Schedule::groupNames()` and checking if the resulting name list is empty.  The immediate use case is to enable issuing diagnostic messages for UDQ DEFINE statements that name objects which do not exist at the point of definition.  Cf. commit 8263aea9b9f06b79cde3842a0ff26a5eaa976545 (#4612)
To this end, add helper functions
* `WellMatcher::hasWell()`
* `GroupOrder::anyMatchingGroups()`
and implement the predicates in terms of these helper functions. The former is effectively the computational engine of `WellMatcher::wells()` without forming a vector of strings, and the latter is the internals of `GroupOrder::names()` with the same provision.
One small quirk of `WellMatcher::hasWell()` is that if …

Add Well/Group Existence Predicates to HandlerContext

---

opm/input/eclipse/EclipseState/Tables/PvtxTable.cpp
opm/input/eclipse/EclipseState/Tables/PvtxTable.hpp
tests/parser/integration/ParseKEYWORD.cpp

Outside of a single unit test, the member function
```
PvtxTable::evaluate(x1, x2)
```
isn't actually used anywhere in the simulator.  Remove it to reduce the maintenance cost of the `PvtxTable` class.

Remove Unused PvtxTable Member Function

---

opm/input/eclipse/Schedule/ScheduleStatic.cpp
opm/input/eclipse/Schedule/ScheduleStatic.hpp

In particular
- Add missing headers and re-sort include statements
- Add braces to single-statement blocks
- Add Doxygen-style documentation
- Ensure all data members are accounted for in `operator==()`, `serializeOp()`, and `serializationTestObject()`.
This is in preparation of forming an initial report configuration object (`RPTConfig`) from the RPTSOL keyword in the SOLUTION section.

Varnish ScheduleStatic Implementation

---

opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp
opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp

This is a C++20 header that may or may not be available when compiling in C++17 mode.  Since it's not actually used here, just remove the include statement.
While here, also tidy up the include statements in the `EclipseGrid.cpp` implementation file.

Don't Include <ranges> Header

---

opm/input/eclipse/Parser/ParseContext.cpp
opm/input/eclipse/Parser/ParseContext.hpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.cpp
opm/input/eclipse/Schedule/UDQ/UDQConfig.hpp
opm/input/eclipse/Schedule/UDQ/UDQKeywordHandlers.cpp
tests/msim/test_msim_ACTIONX.cpp
tests/parser/UDQTests.cpp
tests/test_AggregateUDQData.cpp
tests/test_AggregateWListData.cpp

This PR adds logic to check if all wells/groups needed in a UDQ DEFINE statement are present at the point of definition.  In particular, wells must have been introduced through WELSPECS prior to the UDQ keyword if any specific well name is used in the defining expression.  Similarly, well lists must have been introduced and populated through WLIST before using the well list name in the UDQ. Finally, groups must be introduced through WELSPECS or GRUPTREE before using any specific group names in the defining expression.
If this requirement is not met, the parsing process will halt at the end of reading the full SCHEDULE section in order that all such problems may be diagnosed in a single run.  Some example output is shown below.
To this end, make `UDQConfig::add_record()` return an …

Diagnose Missing Wells/Groups in UDQ DEFINE Statements

---

opm/input/eclipse/Schedule/MSW/Segment.cpp
opm/input/eclipse/Schedule/MSW/WellSegments.cpp

With the master branch, we got some message like the following due to rounding error from `diameter*input_roughness/diameter`
```
Warning: Well G segment 76 to 76: Too high roughness 1.500e-05 is limited to 1.500e-05 to avoid singularity in friction factor calculation.
```
this PR refactor the calculation to avoid that. 
And also, the PR adds the line number and file name for the warning to help diagnostic .

update how to determine too high roughness

---

opm/input/eclipse/EclipseState/InitConfig/InitConfig.cpp
tests/parser/InitConfigTest.cpp

OPM Flow does not support restarting a simulation run from report step zero.  Previously, this would manifest in a very inscrutable diagnostic message of the form
```
Array ZGRP not found in sequence 0
```
which, while accurate, does not tell the user what the problem is.
This PR verifies that the restart step supplied as item 2 of the RESTART keyword is at least one (1).  If not, we now generate a diagnostic message of the form
```
Error: Problem with keyword RESTART
In CASE.DATA line 1729
OPM does not support restarting a simulation before report number 1
```
and stop processing the input file.

Emit Usable Diagnostic for Unuspported Restart Report Number

---

opm/input/eclipse/Schedule/Group/Group.cpp
opm/input/eclipse/Schedule/Group/Group.hpp
opm/input/eclipse/Schedule/Group/GroupKeywordHandlers.cpp

then it is possible to enforce specific action for oil rate alone, mostly to enforce RATE actions for the setting mode in GCONPROD.
allRates can be removed if there is no need for output, which remains to be checked.

refactoring GroupLimitAction, adding exceed action for oil for GCONPROD keyword

---

ExtraTests.cmake

The case got removed through https://github.com/OPM/opm-tests/pull/1353 . 
Now it looks like breaking the test from opm-common. 
I am suggesting to remove this test to recover the master build.

removing the test related to deleted spe9/SPE9_CP_GROUP.DATA

---

opm/input/eclipse/Schedule/Group/GroupKeywordHandlers.cpp

This handles GCONPROD item 2 correctly for cases like the following:
```
GCONPROD
'PLAT-A' 'ORAT' 20000.0  30000.0   1* 40000.0  'RATE' /
'M5S'    'FLD'  500.0    30000.0   1* 40000.0  'WELL'  'YES' 1 'OIL' /
/
```
Here, the M5S group will now be treating ORAT as its control, which in turn will change the procedure for breaking the oil limit from WELL to RATE.
There are a few things that could still be considered: for the following case
```
GCONPROD
'PLAT-A' 'LRAT' 20000.0  30000.0   1* 40000.0  'RATE' /
'M5S'    'FLD'  500.0    30000.0   1* 40000.0  'WELL'  'YES' 1 'OIL' /
'PLAT-A' 'ORAT' 20000.0  30000.0   1* 40000.0  'RATE' /
/
```
it is not clear if it should give identical results as the first one (since the last line overrides the first), or if the FLD control for M5S should become …

Interpret GCONPROD FLD controls as inheriting control from parent(s).

---

opm/input/eclipse/Schedule/Group/GuideRate.cpp
opm/input/eclipse/Schedule/Group/GuideRate.hpp
opm/input/eclipse/Schedule/Group/GuideRateModel.cpp
opm/input/eclipse/Schedule/Group/GuideRateModel.hpp
tests/parser/GroupTests.cpp

We see this problem for a field case, it stops the simulation.

returning zero guide rate instead of throw due to invalid denominator.

---

opm/output/eclipse/EclipseIO.cpp
opm/output/eclipse/EclipseIO.hpp

In particular, add Doxygen-style comments to member functions and data members.  While here, document function parameters and return values of the main `EclipseIO` class in a similar style.
While here, also remove the declaration of the member function
```
EclipseIO::overwriteInitialOIP
```
This function was introduced in PR OPM/opm-output#198, but was rather shortlived.  The implementation, though not the declaration, was removed in PR OPM/opm-output#235.

Document Internal EclipseIO::Impl Class

---

opm/material/fluidstates/BlackOilFluidState.hpp

Never used (read) by OPM Flow, was always redundant since all phase pressures are stored in this class anyway. Should save 12 doubles per cell for a 3-phase simulation, or 96 MB per million cells.
Requires a very small downstream update.
Manual: reduce memory consumption during simulation by 96 MB per million cells.

Remove unused capillary pressure storage.

---

opm/material/checkFluidSystem.hpp
opm/material/common/ConditionalStorage.hpp
tests/test_ConditionalStorage.cpp

Instead of throwing, this will now be a compile error.
This will require downstream changes.
Manual: Makes some types of run-time errors into compile-time errors, making it easier to avoid certain types of programming mistakes.

Remove conversions and accessors for empty ConditionalStorage.

---

opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp
tests/parser/ScheduleTests.cpp

This PR exempts empty well lists from the "missing well" treatment in the `WELTARG` keyword handler.  It is possible for well lists to become empty due to `MOV` operations, especially when run from an `ACTIONX` block, and we should accept this situation and not change any targets.  This commit does issue a tagged warning though, so the first few times this happens the user will be  notified in the console.  All such warnings will nevertheless appear in the PRT and DBG files.
While here, also switch to using compiled item names in the same keyword handler.  This improves the maintainability if those item names ever change.

Allow Empty Well Lists in WELTARG Handler

---

opm/input/eclipse/Parser/Parser.cpp

This will happen if users forget the trailing slash. OPM flow will simply neglect all the arguments until the next trailing slash.
This might not be what the user wants or expects. Now we at least issue a warning.
We could also treat it as an error, though.
An example out of the wilderness:
```
INCLUDE
'file1.inc'
INCLUDE
'file2.inc'
/
```
the user forgot the trailing slash after the first INCLUDE.
The warning will now be:
```
Warning: The keyword INCLUDE has more than 1 argument. The following will be ignored:
INCLUDE file2.inc
Maybe a trailing slash (/) is missing?
In file ROOTFILE.DATA, line 55
```

Error if INCLUDE keyword has multiple arguments.

---

.clang-format

There seems to be a consensus that `struct` definitions should have their opening brace on a newline. The current `.clang-format` file places the brace on the same line as the struct (derived from `BreakBeforeBraces: Linux,`). This PR makes the brace come on a newline.
That is, the old version format as
```C++
struct Somestruct {
```
whereas this format as 
```C++
struct Somestruct
{
```

Now formatting struct with braces on newline

---

opm/common/utility/VoigtArray.hpp

Quell newly introduced (or well, newly noticed) static analyzer warnings-

Janitoring: mark constructor explicit

---

CMakeLists_files.cmake
opm/input/eclipse/Schedule/Group/GSatProd.hpp
opm/output/eclipse/Summary.cpp
tests/test_Summary_GSatProd.cpp

This PR amends the summary vector calculation of group and field level cumulative production volumes (`[FG]xPT`) to incorporate group level efficiency factors (`GEFAC`).  These efficiency factors must be included in the normal way, whence rates need factors below the current level whereas cumulatives need factors from all levels.

Account for Group Level Efficiency Factors in Satellite Production

---

opm/output/eclipse/Summary.cpp

Avoid uncaught exceptions for groups that are not (yet) defined.

Check that group exists before accessing

---

opm/input/eclipse/EclipseState/Util/IOrderSet.hpp
opm/input/eclipse/Schedule/Group/Group.cpp
opm/input/eclipse/Schedule/Group/Group.hpp

In particular
* Split long lines
* Put braces around single-statement blocks
* Move functions' opening braces to new line
* Prefer logical operators to multiple `if()` conditions
* Use `IOrderSet<>::insert()`'s return value directly instead of checking `count()` followed by `insert()`
* Don't return `const` objects by value
While here, also replace the two-argument constructor for forming `IOrderSet<>` objects with an initial sequence of elements.  The two-argument version could potentially lead to forming objects with an inconsistent view of the set's elements and was only used to form serialisation test objects for class Group in any case.

Revamp Implementation Files for Opm::Group

---

CMakeLists_files.cmake
opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerHystParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawTwoPhaseTypes.hpp

to simplify reuse.
The nesting allows sharing these type aliases in the subclasses. When splitting out the nested classes, a lot of these need to be repeated. This adds a helper class to limit the repeating to a handful of using statements from the helper instead.
Extracted from https://github.com/OPM/opm-common/pull/4706

changed: add a helper class for two phase material law types

---

examples/rst_deck.cpp
opm/common/OpmLog/KeywordLocation.hpp
opm/input/eclipse/Deck/DeckKeyword.cpp
opm/input/eclipse/Deck/DeckKeyword.hpp
opm/input/eclipse/Deck/DeckTree.cpp
opm/input/eclipse/Deck/FileDeck.cpp
opm/input/eclipse/Deck/FileDeck.hpp
opm/input/eclipse/Deck/ImportContainer.cpp

Allows rst_deck to function with binary (IMPORT'ed) input files. Works with all modes (inline|copy|shared), but for now the 'copy' mode will write ASCII format files even though the input was binary.

Add support for binary input files in FileDeck and rst_deck

---

examples/hysteresis.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerHystParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerInitParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerReadEffectiveParams.cpp
tests/material/test_eclmateriallawmanager.cpp
tests/material/test_hysteresis.cpp

The nested classes (ref https://github.com/OPM/opm-common/pull/4706) naturally gives a grouping of the manager and its utility classes. When un-nesting this becomes less clear, so to keep this intact, we achieve this by using a ```namespace Opm::EclMaterialLaw``` instead. Since ```Opm::EclMaterialLaw::EclMaterialLawManager``` is a mouthful, I have opted to rename the class to Manager, ie, ```Opm::EclMaterialLaw::Manager```

EclMaterialLawManager: put in namespace and rename

---

CMakeLists_files.cmake
opm/material/fluidmatrixinteractions/EclMaterialLawHystParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawHystParams.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManagerInitParams.cpp

Un-nest the HystParams class, ref https://github.com/OPM/opm-common/pull/4706

EclMaterialLawManager::InitParams::HystParams: rename EclMaterialLaw::HystParams

---

CMakeLists_files.cmake
opm/material/fluidmatrixinteractions/EclMaterialLawHystParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawHystParams.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawInitParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawInitParams.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp
opm/material/fluidmatrixinteractions/EclMaterialLawReadEffectiveParams.cpp
opm/material/fluidmatrixinteractions/EclMaterialLawReadEffectiveParams.hpp

and un-nest the class.
This is the final step in this series. Sorry about the back-and-forth (ie, this removes some accessors added earlier), but they were necessary until I had the final refactor with the Params structure in place.
The Params structure is the tool used to avoid the anti-pattern of friend classes.

EclMaterialLawManager::InitParams: rename EclMaterialLaw::InitParams

---

CMakeLists_files.cmake
opm/material/fluidsystems/BlackOilDefaultFluidSystemIndices.hpp
opm/material/fluidsystems/BlackOilFluidSystem.cpp
opm/material/fluidsystems/BlackOilFluidSystem_macrotemplate.hpp
opm/material/fluidsystems/PhaseUsageInfo.cpp
opm/material/fluidsystems/PhaseUsageInfo.hpp
tests/test_PhaseUsageInfo.cpp

Introducing PhaseUageInfo (named can be changed) which can be used in FluidSystem or passed around for the classes that do not have FluidSystem accessible. Purpose is to remove the usage of `PhaseUsage` and avoid to have a separate phase Index from it.

Removing phase usage 

---

opm/input/eclipse/Parser/Parser.cpp
opm/input/eclipse/Parser/Parser.hpp
opm/input/eclipse/Schedule/Schedule.cpp
python/cxx/schedule.cpp

Processing PYACTIONs that use `schedule.insert_keywords` at every time step currently produces a LOT of output. This PR silences the output from re-parsing the schedule section, unless --debug-verbosity-level >= 3 (in which case the output goes to OpmLog::debug).

Avoid excessive output from PyAction schedule.insert_keywords

---

cmake/Modules/FindHYPRE.cmake

hypre 3.0 has a define HYPRE_USING_CUDA_STREAMS line even when built with HIP which matches the prevous line and thus caused havoc

fixed: need to check for the full definition line

---

opm/input/eclipse/Schedule/Group/Group.cpp
opm/input/eclipse/Schedule/Schedule.cpp
opm/io/eclipse/rst/group.cpp
opm/io/eclipse/rst/group.hpp
opm/output/eclipse/AggregateGroupData.cpp
opm/output/eclipse/VectorItems/group.hpp

We save the production rates in the regular SGRP items used for GCONPROD and furthermore record the satellite status in the IGRP item used for the "group type".  On restart, we load the group type and record satellite production flag if the group has active production limits when the group type is satellite.
While here, also do slight reformatting of `AggregateGroupData.cpp` to split long lines and insert braces around single statement blocks close to other changes.
Note: LGR items are intentionally omitted here.  Satellite groups do not have children and therefore typically do not influence LGRs.

Add Restart Support for Satellite Production Rates

---

opm/material/components/Brine.hpp
opm/material/components/BrineDynamic.hpp
opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp
opm/material/fluidsystems/blackoilpvt/BrineH2Pvt.hpp

This is an attempt to speed up property evaluation of CO2STORE cases by ensuring that we calculate (pure) water density once instead of 3 times.
Somewhat surprising to me, it only seemed to give ~5% faster properties, despite the pure water density function showing up as taking a significant part (at least 25%) of the time in profiling. This could be due to cache effects, or other reasons.
I still think it is worthwhile to get this in, even though the effect was less than hoped for.

Improve CO2STORE property evaluation performance

---

python/CMakeLists.txt
python/pyproject.toml
python/setup.py.in

From private communication with @akva2: When building the python modules in the docker container (see [opm-simulators/python/docker](https://github.com/OPM/opm-simulators/tree/master/python/docker)) some warnings were shown when running `python setup.py`, see [generate-pypi-package.sh](https://github.com/OPM/opm-simulators/blob/00e9b6b276e0f5d0f9e4cdf619987a327c40294c/python/docker/scripts/generate-pypi-package.sh#L145). Try to modernize to use [pypa/build](https://build.pypa.io/en/stable/) instead to get rid of warnings. See also companion PR https://github.com/OPM/opm-simulators/pull/6461
Example warning:
```
#16 959.8 /opt/python/cp312-cp312/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:90: SetuptoolsDeprecationWarning: setup.py install is deprecated.
#16 959.8 !!
#16 959.8 …
```

Fix python setup.py warnings

---

opm/input/eclipse/Schedule/HandlerContext.hpp

The enum is based on `std::unint8_t`, which is not available without including `cstdint`.

Added include of cstdint

---

opm/input/eclipse/share/keywords/900_OPM/S/SALTSOL

I believe item 1 (SALTSOL) should have units of Salinity (LB/STB) rather than density (LB/FT3) to be consistent with e.g. SALTVD. This only affects FIELD units.
This replaces #3883.

SALTSOL: change units of item 1 to Salinity (3)

---

opm/input/eclipse/share/keywords/000_Eclipse100/W/WECON

Following on from:
Support opening of following-on well [opm-simulators#6050](https://github.com/OPM/opm-simulators/pull/6050)

WECON keyword item 9: remove comment 'Not supported'

---

opm/input/eclipse/Schedule/UDQ/UDQFunction.cpp
tests/parser/UDQTests.cpp

The existing implementation of POW (exponentiation operator, "`^`") supports UDQ sets of the same size only.  This commit extends this support to handle combinations of UDQ sets and UDQ scalars, e.g.,
(well level UDQ) ^ scalar
scalar ^ (group level UDQ)

Support UDQ Set/Scalar Operation for POW

---

examples/opmpack.cpp
opm/input/eclipse/EclipseState/EclipseConfig.cpp
opm/input/eclipse/EclipseState/EclipseConfig.hpp
opm/input/eclipse/EclipseState/EclipseState.cpp
opm/input/eclipse/EclipseState/InitConfig/Equil.cpp
opm/input/eclipse/EclipseState/InitConfig/Equil.hpp
opm/input/eclipse/EclipseState/InitConfig/InitConfig.cpp
opm/input/eclipse/EclipseState/InitConfig/InitConfig.hpp
tests/parser/InitConfigTest.cpp
tests/parser/ThresholdPressureTest.cpp

In its current form, it gives the following error message when three phases are all present. 
```
Error: 
An error occurred while creating the reservoir properties
Internal error: EQUILIBRATION DATA ERROR FOR REGION 1,
THE GAS-OIL CONTACT LIES BELOW THE WATER-OIL CONTACT.
Error: Unrecoverable errors while loading input:
EQUILIBRATION DATA ERROR FOR REGION 1,
THE GAS-OIL CONTACT LIES BELOW THE WATER-OIL CONTACT.
```
not totally sure whether it is the correct place to throw, while it is first prototype.

throw when GOC lies below WOC in EQUIL keyword

---

CMakeLists.txt

Continuation of commit 6387f9317 (PR #4663).  Following commit 17d9ab348 (PR #4774) more tests must link to Dune-common in order to get the correct include paths for `<dune/common/typetraits.hh>` that gets transitively included through [`Evaluation.hpp`](https://github.com/OPM/opm-common/blob/899ae3afae7c23d54b017db45c45ac29908d0e2e/opm/material/densead/Evaluation.hpp#L46-L48).

Conditionally Link More Tests to Dune-Common
